### ISSUE TITLE
404 on https://zod.js.org/ 

### ISSUE THREAD

**Issue by iest** [colinhacks/zod#1007]
https://zod.js.org/
<img width="603" alt="Screenshot 2022-03-10 at 12 10 30" src="https://user-images.githubusercontent.com/1926464/157658999-710cf44e-d9e7-43ee-93b7-a2a12fbd9345.png">

**Comment by autumnblazey** [comment]
I think there is a repo setting that needs to be changed for github pages to work? I think everything looks good in the `gh-pages` branch (`CNAME` looks fine)
<img width="1086" alt="Screenshot 2022-03-16 at 22 03 07" src="https://user-images.githubusercontent.com/49562048/158740703-508a1fea-038f-4dca-9cba-eef7554b22e4.png">

**Comment by FlorianWendelborn** [comment]
Still happening

**Comment by iest** [comment]
Guess the site URL was updated to https://zod.dev? Closing 🚫
