### ISSUE TITLE
Feature Proposal: Preprocessed string types

### ISSUE THREAD

**Issue by prescience-data** [colinhacks/zod#1019]
I use Zod heavily for parsing environment variables and in each project need to reimplement transformer definitions to convert the raw env object (either from `process.env` or `dotenv`) to their intended types.

What would alleviate a bunch of pain in this use case is having built in `<number|boolean|bigint|null>String()`, for example:

```typescript
const isString = (value: unknown) : value is string => typeof value === "string"

const booleanString = z.preprocess(
  (value) => (isString(value) ? value === "true" : value),
  z.boolean()
)

const numberString = z.preprocess(
  (value) => (isString(value) ? parseInt(value) : value),
  z.number()
)

const bigintString = z.preprocess(
  (value) => (isString(value) ? BigInt(value) : value),
  z.bigint()
)

const nullString = z.preprocess(
  (value) => (isString(value) && value === "null" ? null : value),
  z.null()
)
```

The ideal implementation would be for the `z` import to provide these like:

```typescript
import { z } from "zod"

const EnvSchema = z.object({
  FOO_NUMBER: z.numberString().default(100),
  BAR_BOOL: z.booleanString().default(false)
  // etc...
})

```

Happy to do an MR if this is something that might be accepted?

**Comment by FlorianWendelborn** [comment]
To me this looks more like something that could/should be implemented by a utility library. You could even include the schema itself in it, by using it like `z.preprocess(...castToString)`, so it’d really not be a lot of added code if this isn’t in `zod` itself.

**Comment by prescience-data** [comment]
Maybe a better / more abstract interface could be something like

```typescript
z.from(z.string()).number()
```

which would have the additional isomorphic benefit of things like

```typescript
z.from(z.bigint()).number()
```

**Comment by ConProgramming** [comment]
For any modern googlers - the solution is [coercion](https://github.com/colinhacks/zod#coercion-for-primitives)
