### ISSUE TITLE
Allow configurable access to unknown keys and their values within `refine` and `superRefine`

### ISSUE THREAD

**Issue by Aaronius** [colinhacks/zod#1032]
As outlined in https://github.com/colinhacks/zod/discussions/1029, I have an object like so:

```
{
  a: "foo",
  b: "foo"
}
```

which I'm validating using a schema like this:

```
z.object({
  a: z.string()
}).refine((input) => {
  // I need to reference b here
});
```

I can access `b` if I call `passthrough()` before `refine()`, like this:

```
z.object({
  a: z.string()
})
.passthrough()
.refine((input) => {
  // I need to reference b here
});
```

but I don't want `b` to actually be passed through though. 

@scotttrinh suggested adding the b schema and using `refine` to do the check and then use `transform` to only return a.

@scotttrinh's solution works, but it seems more optimal if Zod would add an option to `RefineParams` (passed as a second argument to `refine`) that would could be configured to include unknown keys to be included in `input`.

**Comment by Aaronius** [comment]
Re-open please.

**Comment by scotttrinh** [comment]
Unfortunately I doubt this is something we are likely to actually add. From the standpoint of zod, the behavior you get when defining a normal `z.object` schema is that it only returns the known keys and there is no way for the schema to know if you want access to it later. Adding some kind of configuration for this edge case would have to be done at the `z.object` level (so we don't throw away the unspecified data) which means we'd have to store this extra data somewhere else just in case you need it later. That adds performance overhead to those who don't use this feature. Furthermore this doesn't seem like something we want to add complexity around given the tradeoffs here. I still maintain that `transform` is the correct and explicit way to deal with this.

**Comment by Aaronius** [comment]
Thanks for the explanation.
