### ISSUE TITLE
Getting Zod to Accept Undefined as a value

### ISSUE THREAD

**Issue by dylpick14** [colinhacks/zod#1037]
Hi, Im working on a pretty Dynamic form with a few conditional statements. However, when I submit the form, I have all the unused variables as undefined (because they are not defined in the form since they were not used) I keep getting the following error: 
"unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "all",
            "path": [
              "recipientType"
            ],
            "message": "Expected all, received undefined"
          }
        ],
        "name": "ZodError"
      },
      
 It should be receiving undefined in this case because I did not click the All Value in my form. I was wondering if there was a way to either ignore the ZodError, or allow it to be undefined.

**Comment by FlorianWendelborn** [comment]
@dylpick14 can you provide your schema? Please [use code blocks](https://gist.github.com/stevenyap/7038119#coding---block) for readability when you do.

Without the schema, my most likely guess is that you’re missing a `.optional()` on the schema, but it’s impossible to say for sure what’s happening.
