### ISSUE TITLE
Callback on function arguments throws error

### ISSUE THREAD

**Issue by DarkenLM** [colinhacks/zod#1044]
I've started using this package to automatically infer types for Typescript declarations and to ensure object schemas, however I've came across some issues when it comes to having callbacks on functions.

When declarating a function like this:
```js
function processAndCallback(num, string, callback) {
    // Process data...
    callback(err, "some string", 0)
}
```
And using a Zod Schema like:
```js
const schema = z.function()
  .args(
    z.number(),
    z.string(),	
    z.function()
        .args(
            z.instanceof(Error),
            z.string({
                invalid_type_error: "Paramether must be a string value",
            }),
            z.number({
                invalid_type_error: "Paramether must be a numeric value",
            })
        )
        .returns(z.void())
        .implement((err: Error, address: string, family: number) => {
            err;
            address;
            family;

            return;
        })
    )
    .returns(z.void())
    .implement((err, options, callback) => {
        err;
        options;
        callback;

        return;
    })
```

The following error is thrown:
```
Argument of type '[ZodNumber, ZodString, (err: Error, address: string, family: number) => void]' is not assignable to parameter of type '[] | [ZodTypeAny, ...ZodTypeAny[]]'.
  Type '[ZodNumber, ZodString, (err: Error, address: string, family: number) => void]' is not assignable to type '[ZodTypeAny, ...ZodTypeAny[]]'.
    Type at positions 1 through 2 in source is not compatible with type at position 1 in target.
      Type 'ZodString | ((err: Error, address: string, family: number) => void)' is not assignable to type 'ZodTypeAny'.
        Type '(err: Error, address: string, family: number) => void' is missing the following properties from type 'ZodType<any, any, any>': _type, _output, _input, _def, and 30 more.
```

What I pretend is generating names for the arguments of the callback on the callback function for Typescript Declarations.
The only way I found that could do it was using `z.function().implement()`. Is there another way?

**Comment by andresgutgon** [comment]
Args is a Tuple, not sure if that can help you https://github.com/colinhacks/zod/blob/master/src/types.ts#L2776

**Comment by DarkenLM** [comment]
@andresgutgon unfortunately, I'm new to Typescript, so I still have some difficulty understanding it's syntax. This is what I managed to understand:
- ZodFunction accepts two arguments: `Args` and `Returns`.
- `Args` is a ZodTuple, so in `z.function()` I should wrap the arguments on a `z.tuple()`
- `Returns` can be anything.

I couldn't really understand how the InnerTypeOfFunction related to the arguments, nor how implements is breaking everything, but when using a declaration with the function argument alone, I get the following message:
```
Type '(str: string) => void' is missing the following properties from type 'ZodType<any, any, any>': _type, _output, _input, _def, and 30 more.
```

Code:
```js
const func = z.function(
    z.tuple([
        z.function(
            z.tuple([
                z.string()
            ]),
            z.void()
        ).implement((str) => {
            str;

            return;
        })
    ]), 
    z.void()
)
```

Do I need to use `implement` differently?

**Comment by andresgutgon** [comment]
So you want a function that receive a function as argument?

Can you put here what you want to achieve without zod in plain javascript?

**Comment by DarkenLM** [comment]
@andresgutgon What I'm trying to achieve is a function that looks like this:
```js
function lookup(hostname, callback) {
    try {
        // Process data
        callback(null, "output string", 0)
    } catch (e) {
        callback(e, null, null)
    }
    
    return;
}
```
Where:
- `hostname` is a string
- `callback` is a function that returns nothing and accepts the arguments:
    - `err`: An Error, if existent
    - `address`: A string, if existent
    - `family`: A number, if existent

The function may also be defined like:
```js
function lookup(hostname, options, callback) {
    try {
        // Process data
        callback(null, "output string", 0)
    } catch (e) {
        callback(e, null, null)
    }
    
    return;
}
```

That has all the arguments of the previous, with the adition of `options`, which is an object structured like:
 - `family` is a number
- `hints` is a number
- `all` is a boolean
 - `verbatim` is a boolean

**Comment by andresgutgon** [comment]
Why don't you pass `onSuccess` and `onError` callbacks? That would simplify things. `callback` function is doing too many things :)

**Comment by DarkenLM** [comment]
@andresgutgon I am dependent on an API (specifically [Node's DNS lookup](https://nodejs.org/api/dns.html#dnslookuphostname-options-callback)), and I would like to not have to build a wrapper around it.

**Comment by andresgutgon** [comment]
I think I got it. So what you want to type with Zod is the callback function of Node's DNS look function?

**Comment by DarkenLM** [comment]
@andresgutgon I want to type with Zod the lookup function itself, including the callback function.

**Comment by andresgutgon** [comment]
Ok I did some tries but not sure it's working ok. In any case I left it here https://codesandbox.io/s/awesome-dubinsky-mqzj93?file=/src/index.ts

**Comment by andresgutgon** [comment]
Another source of reference are the types of Node https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/dns.d.ts#L118-L122

**Comment by DarkenLM** [comment]
@andresgutgon After tinkering around with your solution, I managed to make it work. You have my deepest appreciation.

For anyone who may find this issue with the same problem, here's the final schema:
```ts
const allowedFamilyNumbers = [0, 4, 6];
const family = z
    .number()
    .refine((num: number) => allowedFamilyNumbers.includes(num))
    .default(0)
    .optional();
const options = z.object({
    family,
    hints: z.number().optional(),
    all: z.boolean().optional(),
    verbatim: z.boolean().optional()
});

const errorArg = z.instanceof(Error);
const address = z.string();
const callbackArgs = z.union([
    errorArg.or(z.null()),
    address.nullable(),
    family.nullable(),
    z.unknown()
]);

const callbackFnSchema = z.function().args(callbackArgs).returns(z.void());

// Final schema
const fnTypeWithOptn = z.function(z.tuple([
    z.string(),
    options,
    callbackFnSchema
])).returns(z.void())

const fnTypeNoOptn = z.function(z.tuple([
    z.string(),
    callbackFnSchema
])).returns(z.void())

const schemaType = z.union([
    z.null(),
    fnTypeNoOptn,
    fnTypeWithOptn
])
```

The above schema accepts as valid:
- `null`
- a function defined like:
```ts
function lookupOne(hostname: string, options: z.infer<typeof options>, callback: z.infer<typeof callbackFnSchema>): void {
    try {
        // Process data
        callback(null, "address", 0);
    } catch (e) {
        callback(e, null, null);
    }
    return;
}
```
- a function defined like:
```ts
function lookupOne(hostname: string, callback: z.infer<typeof callbackFnSchema>): void {
    try {
        // Process data
        callback(null, "address", 0);
    } catch (e) {
        callback(e, null, null);
    }
    return;
}
```
