### ISSUE TITLE
ZodType<Output> does not get the correct output of a union with transformations.

### ISSUE THREAD

**Issue by ricardo-devis-agullo** [colinhacks/zod#1049]
Given this code

```typescript
import { z } from 'zod';

const stringToNumber = z.string().transform((val) => val.length);

const Data = z.object({
  prop: z.union([z.number(), stringToNumber])
});

function Parse<Output>(type: z.ZodType<Output>, data: unknown): Output {
  return type.parse(data);
}

const directlyParsed = Data.parse({}); // { prop: number; }
const indirectlyParsed = Parse(Data, {}); // { prop: string | number; }
```

Extracting the output on `indirectlyParsed` returns `string | number` instead of the correct one which should be just `number`. Am I doing something wrong or is there a problem with ZodType here?

**Comment by ricardo-devis-agullo** [comment]
I found out that it works if I redefine the Parse function like this

```typescript
function Parse<T extends z.ZodType<any>>(type: T, data: unknown): z.output<T> {
  return type.parse(data);
}
```

Is that how I'm supposed to define it?

**Comment by colinhacks** [comment]
Yep, that's the proper way. I just wrote a guide to help others who encounter this same difficulty: https://github.com/colinhacks/zod#writing-generic-functions

**Comment by ricardo-devis-agullo** [comment]
Thank you! Sorry, I didn't find that on the README before.
