### ISSUE TITLE
Configurable default settings

### ISSUE THREAD

**Issue by TkinterinShanghai** [colinhacks/zod#1053]
It would be nice to enforce a certain coding style with zod such as using `.strict()` by default for all objects or forcing the user to set `.min()` and `.max()` for all Numbers and Strings. Maybe introducing a config file could allow the user to tune those default settings.

**Comment by FlorianWendelborn** [comment]
> such as `.strict()` by default

Could be an option, I’d personally also prefer a default `strict` mode.

> `.min()` and `.max()`

In my opinion, this is better solved with an `eslint` plugin. This option basically wouldn’t change the runtime behavior at all and will have pretty bad DX when implemented on `zod`’s side as you’d only get a runtime error...

As an `eslint` plugin, you’d get instant feedback.

**Comment by TkinterinShanghai** [comment]
True, eslint could probably take care of this, too. Didnt think of that. But also the checks are kept track of already like this

```javascript
return new ZodString({
      ...this._def,
      checks: [...this._def.checks, check],
    });
// ...
min(minLength: number, message?: errorUtil.ErrMessage) {
    return this._addCheck({
      kind: "min",
      value: minLength,
      ...errorUtil.errToObj(message),
    });
  }
```

Maybe by checking if "min" and "max" both exist on the instance could be solved with just using Typescript.
