### ISSUE TITLE
z.record returns partial type when using enum with a 2nd schema

### ISSUE THREAD

**Issue by Thygoddess** [colinhacks/zod#1061]
Love this library, and while I was updating a site to the latest version, I realized something had changed on `z.record`. I had been using `record`  with two schemas as described in the changelog, since I realized it was allowed and the readme documentation seemed behind on fancy functionality:

```
const schema = z.record(z.enum(["Tuna", "Trout"]), z.boolean());
type schema = z.infer<typeof schema>; // Record<"Tuna" | "Trout", boolean>
```

This was working fine until around v3.13.2. Now the result seems to be `Partial<Record<"Tuna" | "Trout", boolean>>`

**Comment by colinhacks** [comment]
https://github.com/colinhacks/zod/issues/992
