### ISSUE TITLE
z.shape, infer and TypeScript

### ISSUE THREAD

**Issue by 3x071c** [colinhacks/zod#1064]
I have the following function, which generically validates a value of a poperty on an object, with zod:
```ts
import type { z } from 'zod';

const validateValue = <M extends z.ZodObject<z.ZodRawShape>, T extends keyof M["shape"]>(
    model: M,
	field: T,
	value: z.infer<M["shape"][T]>,
): z.infer<M["shape"][T]> => model.shape[field].parse(value) as z.infer<M["shape"][T]>;
```

This leads to multiple problems:

- TypeScript claims that the `model.shape[field]` object could possibly be undefined (I have all strict flags on), but this can't be true because the type of `field` is a generic key of `model["shape"]`
- My ESLint configuration (`@typescript-eslint/no-unsafe-return`) complains that the return type of `.parse(value)` is `any`, but since it is explicitly assessed to be `z.infer<M["shape"][T]>`, this must mean said type is `any`, which makes the function unusable for type safety.

Does anyone know what I can do to make this work fully type-safe, i.e. preventing calls with bad field/value parameters?

**Comment by colinhacks** [comment]
This works:

```ts
const validateValue = <
  Shape extends z.ZodRawShape,
  M extends z.ZodObject<Shape, any, any, any, any>,
  T extends keyof Shape
>(
  model: M,
  field: T,
  value: z.infer<M["shape"][T]>
): z.infer<M["shape"][T]> => {
  return model.shape[field].parse(value);
};
```

By extracting the shape into its own parameter, you're telling TypeScript that the ZodObject's shape and the target of `keyof` are the same value. Generics are weird sometimes.

**Comment by 3x071c** [comment]
@colinhacks Thanks, that looks a lot better already. However, pasting your snippet into my editor, I'm still getting the same error messages. The TypeScript one can be circumvented easily enough with optional chaining (`?.parse(value)`), even though that still doesn't make sense (as written above) because `model.shape[field]` can't ever be undefined. For now, I'm ignoring the ESLint rule, but it's bleeding into all function consumers as well (I'm not sure if `z.infer<M["shape"][T]>` being inferred as `any` is the fault of zod, my code or the ESLint rule). Any ideas?

**Comment by 3x071c** [comment]
I want to use the function like I would the following function, which is fully type-safe and gets autocompletion/IntelliSense:
```ts
const validateValue = <
	O extends Record<string, unknown>,
	K extends keyof O,
	V extends O[K],
>(
	obj: O,
	key: K,
	value: V,
) => {
	return obj[key] === value;
};

const a = validateValue({ foo: "bar", foobar: "baz" } as const, "foobar", "baz");
```

**Comment by 3x071c** [comment]
@colinhacks Update: I've found a way to replicate the above example with zod, in a fully type-safe manner:
```ts
const validateValue = <
  O extends Record<string, unknown>,
  S extends { [K in keyof O]: z.ZodType<O[K]> },
  M extends z.ZodObject<S>
>(
  model: M,
  field: keyof O,
  value: O[typeof field]
) => {
  return model.shape[field].parse(value);
};

const Model = z.object({
  foo: z.string(),
  foobar: z.string(),
});
type Model = z.infer<typeof Model>;

const b = validateValue<Model, typeof Model["shape"], typeof Model>(Model, "foobar", "bar");
```

This approach comes at the downside of having to manually pass the generic types, they aren't properly inferred from the first parameter as without them, there's no IntelliSense and type-safety for the `field` parameter and no type-safety for the `value` parameter.

Still looking for a "perfect" solution that doesn't require passing the generics by hand.
