### ISSUE TITLE
`schema.safeParse(...).error.flatten()` return type and `z.inferFlattenedErrors<...>` don't match

### ISSUE THREAD

**Issue by mubaraqwahab** [colinhacks/zod#1068]
I'm trying to create a function that takes an object and a generic ZodObject schema and validates the object against the schema. But TypeScript complains that the error object from `schema.safeParse(...).error.flatten()` has a different type than `z.inferFlattenedErrors<...>`.

I've reduced my code to where the error is below:

```ts
import { z } from "zod";

type BaseSchema = z.ZodObject<Record<string, z.ZodTypeAny>>;

type Arg<Schema extends BaseSchema> = {
  fields: Record<string, string | null>;
  schema: Schema;
  onSuccess: (data: z.infer<Schema>) => Promise<Response>;
  onFailure: (data: z.inferFlattenedErrors<Schema>) => Promise<Response>;
};

export async function v<Schema extends BaseSchema>({
  fields,
  schema,
  onSuccess,
  onFailure
}: Arg<Schema>): Promise<Response> {
  const validation = schema.safeParse(fields);

  if (validation.success) {
    return await onSuccess(validation.data);
  } else {
    const error = validation.error.flatten();

    // This fails
    const response = await onFailure(error);

    // So I have to do this instead
    // const response = await onFailure(error as z.inferFlattenedErrors<Schema>);

    return response;
  }
}
```

[Demo](https://codesandbox.io/s/relaxed-turing-x55ycj?file=/src/index.ts).

The complaint is that the `.flatten()` error has this shape:

```
{
  formErrors: string[];
  fieldErrors: {
      [k: string]: string[];  // issue here
  };
}
```

while the `z.inferFlattenedErrors<...>` has this shape:

```
{
  formErrors: string[];
  fieldErrors: {
    [P in allKeys<TypeOf<Schema>>]?: string[] | undefined;  // issue here
  };
}
```

I found this in zod's source that looks related to my problem: the `fieldErrors` keys from the `.flatten()` error are typed as strings.

https://github.com/colinhacks/zod/blob/753f627504a6801d3637a33efab6ad87b216d4a6/src/ZodError.ts#L234-L247

Is this intentional or am I doing something wrong please? Thank you.

**Comment by colinhacks** [comment]
Yeah that's a problem. `inferFlattenedErrors` got merged a few months ago as a quick and dirty fix, but it doesn't properly handle nested types, arrays, etc. I didn't want `.flatten()` to return an invalid type. Unfortunately properly typing `flatten` isn't easy - I tried and it quickly causes some thorny `excessively deep` type errors. 

In general, I wouldn't recommend using `flatten` at all in your scenario. It'll be easier to print/handle errors using the plain ZodError object; it contains more complete information as well.
