### ISSUE TITLE
Type inference on schema with passthrough()

### ISSUE THREAD

**Issue by StigKorsnes** [colinhacks/zod#1069]
Hi,
Vscode infers this code:
```
const test=z.object({id:z.string()}).passthrough()
type Typetest=z.infer<typeof test>
```
to be
```
type Typetest ={
id:string
}
```
Is this correct? I was thinking about using this pattern to have a converter for "id", so I can transform the id objects before I ship my data (which is a document including id) off to the db driver. I was thinking that Typetest should display "id" and then some..

**Comment by colinhacks** [comment]
Not sure what you're asking here. What do you think the type should be?

**Comment by StigKorsnes** [comment]
Well, I'm no Typescript expert so might be wrong. What I am saying is that I read the type as only having "id". Should I rather be reading it as a "contract" of at least having an "id", like an interface? I was thinking more in lines of T &{ id:string} , but T might be to generic here.. Again, no Typescript expert.
