### ISSUE TITLE
Only validate if input is checked

### ISSUE THREAD

**Issue by 0bon** [colinhacks/zod#1077]
I have the following schema:
```
const schema = z.object({
    checks: z.object({
        enable: z.boolean(),
        max: z.number().min(1),
        every: z.number(),
    }),
});
```
If `enable` is true, then `max` and `every` should be validated, otherwise they should be omitted. Is this possible with Zod ? I tried tinkering with `refine()` but I could not get it to work.

**Comment by scotttrinh** [comment]
You can model this as a union like:

[CodeSandbox](https://codesandbox.io/s/angry-water-d3izpd?file=/src/index.ts)
```ts
const schema = z.object({
  checks: z.discriminatedUnion("enable", [
    z.object({
      enable: z.literal(false)
      // Depending on your runtime needs, you can define the other keys, too
      // max: z.any() or max: z.undefined(), etc.
    }),
    z.object({
      enable: z.literal(true),
      max: z.number().min(1),
      every: z.number()
    })
  ])
});
```

**Comment by 0bon** [comment]
Thanks. This does not seem to work as expected.
When I check the `enable` checkbox, and submit without specifying anything for `max` or `every`, I don't get any error messages ?

**Comment by scotttrinh** [comment]
Can you log out the value that is passed to the schema? Maybe there is something that is getting passed to it unexpectedly and is passing the parser? As you can see in the CodeSandbox, that case _should_ be covered but form handling is a bit tricky compared to JSON.

**Comment by 0bon** [comment]
@scotttrinh Console.log reveals that boolean values are generated  everytime the checkbox is clicked, although in string format. Changing to `z.literal('true')` does not fix this issue either. See link below: The code doesn't run (not familar with codesandbox) but it should give you an idea of the setup.

https://codesandbox.io/s/sharp-surf-ojv1ny?file=/src/index.js

**Comment by 0bon** [comment]
@scotttrinh After some step debugging, it appears that the type=number inputs with no value are set as "undefined". Does Zod have an issue with fields that are undefined ?
