### ISSUE TITLE
The inferred type of '...' cannot be named without a reference to '..node_modules/zod/lib'. This is likely not portable. A type annotation is necessary.

### ISSUE THREAD

**Issue by mr-bjerre** [colinhacks/zod#1082]
I realize that this is most likely not a bug at zod but maybe it is!?

I have a package that exposes an API to firestore with zod validation. I'm using generics to determine the type of data returned based on the validation schema given.

But when I install the package and create my client I get a lot of errors like this

```
The inferred type of 'databaseClient' cannot be named without a reference to '../../firestore-zod/node_modules/zod/lib'. This is likely not portable. A type annotation is necessary.ts(2742)
```

I don't really understand the issue but I'm guessing it's related to using `z.infer<typeof validationSchema>`? Anyone able to help to get around it?

**Comment by scotttrinh** [comment]
@mr-bjerre 

Can you link to the repo? I'm not sure exactly how much help we can be here, but maybe myself or someone else reading can offer some guidance or just a second pair of eyes on the issue.

**Comment by mr-bjerre** [comment]
I'll try to create a reproducible example. Unfortunately the current repro is private

**Comment by mr-bjerre** [comment]
@scotttrinh I have a repo [here](https://github.com/mr-bjerre/zod-issue) now. Note it is using `pnpm` and `turborepo`. Let me know if I should provide more info. 

The error appears if you clone and then run the following commands

```
pnpm install
pnpm build
```

**Comment by mr-bjerre** [comment]
I've noted something interesting. If I install `zod` in `domain-db` and create the [schema here instead of importing ](https://github.com/mr-bjerre/zod-issue/blob/23c4bb3a95aa5041f94b943222811644e54ad155/packages/domain-db/src/index.ts#L2)then it works. Not sure if that helps to determine what the issue is

**Comment by stefanmo** [comment]
Out of the blue I have a similar issue as well. Did you manage to figure it out?

**Comment by mr-bjerre** [comment]
> Out of the blue I have a similar issue as well. Did you manage to figure it out? It's the same thing, if I create the schema inside a file it doesn't complain.

I just went with my last comment (reorganised my repo)

**Comment by egmacke** [comment]
I realise this thread has been closed, but has anyone found a solution to this?

I've started getting this issue with a mature project using zod when we're upgrading our libraries (which export types and schema) from CommonJS to ESM.

Any solutions (or even a better understanding of the error) would be appreciated

**Comment by zaida04** [comment]
For anyone who comes across this error and is using PNPM, adding `"preserveSymlinks": true` to my tsconfig.json worked for me.

**Comment by almuyna** [comment]
> @scotttrinh I have a repo [here](https://github.com/mr-bjerre/zod-issue) now. Note it is using `pnpm` and `turborepo`. Let me know if I should provide more info.
> 
> The error appears if you clone and then run the following commands
> 
> ```
> pnpm install
> pnpm build
> ```

I think i found the solution but don't known why.

Re-export zod from your wrapper package, either in `firestore-zod `or `validators` is ok.
```ts
export * from 'zod';
```

**Comment by komeilm76** [comment]
```
import core from 'captain-america-core';
export const test = core .server.api.login.schema;
```

The inferred type of 'test' cannot be named without a reference to '***/node_modules/zod'. This is likely not portable. A type annotation is necessary.ts(2742).

 i have not good solution for this error , but worked.
 
```
import core from 'captain-america-core';
export const test = core .server.api.login.schema as typeof core .server.api.login.schema;

```
This is a ridiculous solution, but it works.😂😐

**Comment by Stam2000** [comment]
i removed ` "composite": true` from my `tsconfig.json` and it worked

**Comment by de-tester** [comment]
To the future me or anyone who came across this issue. 

If you are using monorepo or have it as a shared package make sure that zod version in the app that using the package with schemas is the same as the package itself. In my case there was minor differences in the versions. Using same version or even better locking it in the pnpm catalog fixed the issue.

**Comment by michalquantum** [comment]
import type { oas31 } from 'zod-openapi';
const document: oas31.OpenAPIObject = createDocument({...
