### ISSUE TITLE
Generating on-the-fly zod validation objects for 3rd party libs

### ISSUE THREAD

**Issue by famouspotatoes** [colinhacks/zod#1086]
I used yup for years in a totally half-assed way because it didn't have typescript support. I have since fallen absolutely in love with zod and I'm now validating nearly everything. And most of my type definitions are coming from `z.infer<typeof MyZodSchema>`.

However the only deficiency I have found is the ability to support validation for 3rd party types.

My best example of this is the Stripe library. Nowadays, Stripe actually provides a very robust set of types for their very many entities (customers, subscriptions, charges, payment methods, etc, it goes on and on).

You can use these types easily like this:
```
import {Stripe} from 'stripe';
const customer: Stripe.Customer = {
  // ... a bunch of properties here ...
};
```

But I would like to be able to validate these types as well. This is particularly useful when I have cached stripe objects in browser storage (or async storage for mobile) and I need to validate that they are not corrupted before consuming them.

I have seen some people create some codegen tools to go from typescript interface -> zod schema, but is there any way to do this in code on the fly? I'm working on stripe lib right now, but I can imagine doing this for many other libraries as well.

Thanks again for the great lib!!

**Comment by scotttrinh** [comment]
@famouspotatoes 

> is there any way to do this in code on the fly

If you mean "at runtime", then no. TypeScript types do not have a runtime representation with the exception of `enum`. So, you have a few different options for 3rd party libraries:

1. Use a codegen tool (existing or write your own)
2. Only validate the properties that you actually use at runtime, and use `passthrough` to preserve non-checked properties

We use option 2 for most 3rd party data which gives us the runtime safety we care about without needing to keep things in sync with published types from 3rd parties. I've also found that most 3rd parties provide very loose types anyway where almost all keys are optional/nullable.

> This is particularly useful when I have cached stripe objects in browser storage (or async storage for mobile) and I need to validate that they are not corrupted before consuming them.

If you can't trust your cache, and there are good reasons to be defensive about this especially with something like Stripe, then I'd say you're going to have to go the codegen route. Another option there is to encrypt or sign your cache so you can at least rule out tampering.

---

I'm going to close this issue, but feel free to continue posting your thoughts here or asking questions.
