### ISSUE TITLE
Suggested feature: z.enumMap() 

### ISSUE THREAD

**Issue by Padraic-O-Mhuiris** [colinhacks/zod#1092]
Given the updated change in 3.13.3, (#992), where the z.record function now correctly types as a `Partial<Record>` I wonder if it's possible to introduce some validation for exhaustively checking object keys against an enum (or even a union but haven't gone in depth there).

I have created a helper function to create such a schema but I feel it might be something to consider for the core library with a correct type?

The code:

```typescript
export const enumMap = <
  T extends [string, ...string[]],
  U extends z.ZodTypeAny,
>(
  enumeration: z.ZodEnum<T>,
  obj: U,
) => {
  const validateKeysInEnum = <I extends any>(
    record: Record<string, I>,
  ): record is Record<
    typeof enumeration.enum[keyof typeof enumeration.enum], // Yes this is ugly
    I
  > => Object.keys(record).every((key) => enumeration.safeParse(key).success)
  return z.record(obj).refine(validateKeysInEnum)
}

// produces a gnarly z.ZodEffects<> due to refinement?
const myEnumMap = enumMap(
  z.enum(['aaa', 'bbb', 'ccc', 'dddd']),
  z.object({ hhh: z.literal('a') }),
) 

// Zod does infer the type correctly:
// {
//   aaa: {
//     hhh: 'a'
//   }
//   bbb: {
//     hhh: 'a'
//   }
//   ccc: {
//     hhh: 'a'
//   }
//   ddd: {
//     hhh: 'a'
//   }
// }
export type MyEnumMap = z.infer<typeof x>
```

I am fairly new to using Zod and so there may be several reasons not to do this and I may be passing by good reasons to do this but I thought I should share. I don't believe the refinement will lead to easier composition with other schemas. Ideally I would be looking for a solution that can reconcile the current `z.record` behaviour which removes the `Partial` aspect

**Comment by FlorianWendelborn** [comment]
@stale this is still relevant

**Comment by alopezrainspell** [comment]
+1

**Comment by Josh68** [comment]
+1

**Comment by JeViCo** [comment]
+1
