### ISSUE TITLE
Add Custom Message To Enum

### ISSUE THREAD

**Issue by enchorb** [colinhacks/zod#1094]
First off, love this library seems to solve all my teams pain points! The one thing we can't figure out is adding a custom message to an enum type, something like the following:

```
z.enum(['apple', 'orange', 'banana'], {
  message: 'You must select an acceptable fruit',
});
```

**Comment by viktordanko** [comment]
I'm also dealing with this issue right now :/

**Comment by viktordanko** [comment]
Might be a duplicate -> https://github.com/colinhacks/zod/issues/580

**Comment by ElaxDev** [comment]
This haven't been resolved yet, right?

**Comment by the-black-viper** [comment]
Would also be nice to include this feature as I encountered this use case very often.
