### ISSUE TITLE
enum of integers

### ISSUE THREAD

**Issue by oriolcx** [colinhacks/zod#1103]
Would it be feasible to create an enum of integers?

TypeScript seems to accept unions of integers, being able to have also a schema would be great.

Very nice and useful library.

**Comment by CGamesPlay** [comment]
What are you trying to achieve here? If you want to map a set of named strings to numbers, that's what TypeScript's `enum` and [`z.nativeEnum`](https://github.com/colinhacks/zod#native-enums) already do. If you want to restrict the set of integers that pass a schema, that's what `z.union` does.

```typescript
const ValidNumber = union([z.literal(1), z.literal(2), z.literal(3)]);
type ValidNumber = z.infer<typeof ValidNumber>;
const ret = ValidNumber.parse(17); // Throws an error
```

**Comment by oriolcx** [comment]
Many thanks for your answer. As you say, union will do the job. I have not been very sensible on that one.
