### ISSUE TITLE
Deno missing z.infer ?

### ISSUE THREAD

**Issue by EzzatOmar** [colinhacks/zod#1120]
As a deno user I can't find z.infer.
Idk if I'm doing something wrong but if there is no z.infer implementation I would strongly suggest to add a Note in the docs.

**Comment by FlorianWendelborn** [comment]
@EzzatOmar Does `z.output` work as a workaround?

**Comment by EzzatOmar** [comment]
z.output returns an object not a type.
Not sure how to turn this into a type.

**Comment by FlorianWendelborn** [comment]
@EzzatOmar it really shouldn't return an object. Are you sure you're using it correctly? <https://github.com/colinhacks/zod#type-inference>

**Comment by colinhacks** [comment]
`z.infer` is a type alias and is only available in places where TypeScript expects a type. So you can't do this:

```ts
const schema = z.string()
z.infer<typeof schema>;
```

You need to assign to something:

```ts
const schema = z.string()
type schema = z.infer<typeof schema>;
```
