### ISSUE TITLE
Add deepPassthrough method

### ISSUE THREAD

**Issue by KilgoreTroute07** [colinhacks/zod#1124]
Currently if you have an object schema that is multiple layers deep, calling "passthrough" on the top level object will only allow additional keys on that level.  I don't think this is a bug, as I can understand why you wouldn't want to automatically apply it to the whole object.  But I think having that functionality as an option would be nice.

The reason I think this is a good idea, is that in a situation where you want to allow extra keys on a nested object in certain conditions, but not in others (on the same schema) there is no elegant way that I have seen to do that. 

Say we have:
```javascript
const fooSchema = z.object({ bar: z.string() });
const rootSchema = z.object({ foo: fooSchema });
```

If given `condition_1` we want to passthrough the extra keys when we parse, but in `condition_2` we don't for whatever reason, we have to duplicate the schema a little as:

```javascript
const fooSchema = z.object({ bar: z.string() });
const rootSchemaNoPass = z.object({ foo: fooSchema });
const rootSchemaWithPass = z.object({ foo: fooSchema.passthrough() });

if (condition_1) {
    return rootSchemaWithPass.parse(data);
}

if (condition_2) {
    return rootSchemaNoPass.parse(data);
}
```

Obviously with such small code/schemas that doesn't look too bad, but in larger projects with bigger data definitions it can get pretty ugly I think.  I think it would be better to just be able to do:

```javascript
const fooSchema = z.object({ bar: z.string() });
const rootSchema = z.object({ foo: fooSchema });

if (condition_1) {
    return rootSchema.deepPassthrough().parse(data);
}

if (condition_2) {
  return rootSchema.parse(data);
}
```

That way you don't have to store the "passthrough" on the schemas themselves and can just chose to allow extra keys at time of parsing

**Comment by asobirov** [comment]
+1

**Comment by joealden** [comment]
@colinhacks would you be open to re-opening this issue? I feel like as we already have `deepPartial`, something like this isn't too much of a stretch API wise (I don't know how complex this would be to implement though!)?

**Comment by gawi** [comment]
see #2062
