### ISSUE TITLE
Every schema can be associated with an error map - how?

### ISSUE THREAD

**Issue by OnkelTem** [colinhacks/zod#1135]
Here: https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md#schema-bound-error-map

> The `overrideErrorMap` message is then passed as `ctx.defaultError` into any schema-bound error maps. Every schema can be associated with an error map.

> ```ts
> z.string({ errorMap: myErrorMap });
> 
> // this creates an error map under the hood
> z.string({
>   invalid_type_error: "Invalid name",
>   required_error: "Name is required",
> });
> ```

I don't quite understand how can I do that with an array or an object?

Particularly `z.object()` takes its shape from the arg, doesn't it? So there is basically no place to pass the above mentioned error map:

```ts
const myObj = z.object({
  prop1: ...
  prop2: ...
  required_error: "Prop is required",   // Where should I place this?
}) 
```

For example, how to customize the _required_ error message for the `bar.foos` property?:

```ts
const foo = z.object({
  name: z.string()
})

const bar = z.object({
  foos: foo.array()
})
```

**Comment by CGamesPlay** [comment]
`z.object` accepts two arguments; the second is the `RawCreateParams` that allows you to specify the `errorMap`, etc.

**Comment by OnkelTem** [comment]
Thank you very much! I was not paying attention to the source code, trying to figure it out from the docs.
