### ISSUE TITLE
Does zod do type coercion out of the box?

### ISSUE THREAD

**Issue by blade2005** [colinhacks/zod#1141]
As the title says. I'm trying to determine if zod provides out of the box coercion of types. 

I'm moving from yup to zod and part of the solution has a schema validator that does a strict validate in yup then strips of unknown keys. It does the strict to skip any string coercion. 

If zod doesn't do any of that (I don't think it does) out of the box then  the method get's much simpler.

**Comment by scotttrinh** [comment]
Zod does not do any type coercion or transformation unless you explicitly add a `preprocess` or `transform` to your schema. Also, the default behavior of `ZodObject` is to strip unknown keys, not sure if that was part of the question.

**Comment by colinhacks** [comment]
As Scott said, it doesn't. Though I've been toying with the idea of providing some auto-coercing scalar schemas that you'd use like this:

```ts
import {z} from "zod";

z.coerce.string();
z.coerce.number();
z.coerce.boolean();
```

**Comment by blade2005** [comment]
Thank you both so much for answering the question. That really reassures me. I'm not against coercion so long as I can control when it happens.

**Comment by joshuat** [comment]
> As Scott said, it doesn't. Though I've been toying with the idea of providing some auto-coercing scalar schemas that you'd use like this:
> 
> ```ts
> import {z} from "zod";
> 
> z.coerce.string();
> z.coerce.number();
> z.coerce.boolean();
> ```

Really cannot overstate how much I would prefer this coercing solution to having to use `z.preprocess`. @colinhacks would you be open to a PR implementing this functionality as described in your comment? I know there has been a lot of conversation around coercing and the different ways to tackle it.
