### ISSUE TITLE
Circular dependency detected

### ISSUE THREAD

**Issue by ryanzec** [colinhacks/zod#1142]
I have Circular dependency checking in my project and when I include this library, I get this error:

<img width="869" alt="Screen Shot 2022-05-16 at 5 00 17 PM" src="https://user-images.githubusercontent.com/444206/168681885-329ebcc5-f39f-491f-858a-8761fde05922.png">

This makes my builds fails.

**Comment by colinhacks** [comment]
Fixed in v3.17.1

**Comment by ryanzec** [comment]
Pulled it down and no longer seeing those errors, thanks for the fix

**Comment by david-potgieter** [comment]
Seems issue was reintroduced in v3.17.6. 

Installed and tested v3.17.2 - v3.17.5 and no warning. v3.17.6 and up warning is present. I would suspect that `jsonStringifyReplacer` in "./helpers/parseUtil.ts" could potentially also be moved to "./helpers/util.ts"(https://github.com/colinhacks/zod/compare/v3.17.5...v3.17.6#diff-b89cb81c2ff2ce8f5647cfb7d9fcd505bd7271abebfb8de24230a0ebb022f1daR2)

@colinhacks can we reopen please?
