### ISSUE TITLE
Union of Enum values or object values

### ISSUE THREAD

**Issue by simonepizzamiglio** [colinhacks/zod#1145]
Is there any way to create a union validation of enum values or object values?

I tried the code below but it doesn't work:
```ts
import {z} from 'zod';

const Fruits = {
  Apple: "apple",
  Banana: "banana",
} as const;

const FruitEnum = z.nativeEnum(Fruits);

type Fruit = z.infer<typeof FruitEnum>; // "apple" | "banana"

const fruitValuesLiterals = Object.values(Fruits).map(value => z.literal(value)); // z.ZodLiteral<"apple" | "banana">[]

const fruitUnion = z.union(fruitValuesLiterals); // ERROR: Argument of type 'ZodLiteral<"apple" | "banana">[]' is not assignable to parameter of type 'readonly [ZodTypeAny, ZodTypeAny, ...ZodTypeAny[]]'.
```

[TS playground code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwF4F84DMoRHA5EiAE1wG4AoMgYwgDsBneAMSgFdgY64BeRMuOAIJgwAGwCmALjgAiAIbDx0gDR84AIVk1NsqdIBG2rcrJpZnavRjkqtBnGZsYAURoscPJADotMYADcxFzcACgd2OgBKaxgATzAxe1Z2bjgvYBp0MSgAHlj4iHRExyCQAD4SOAB6Spl5UTFpOAAfGQMtIwoLO0xHADVZERYxOgAZdiyBzh4AeT0AKzFKGE8-AaG6UKSOCM8QeWDVwYSuUtTPEXGoAYO1sQioqpqvAC0iMZgJkWy5BQbm1sMsmkpQA2gBdTq2eA9dgAVRowFoKS8LARtGCMJg-SOo0ukwe1TgTgASsTpsSpAIoABzNxiGjwApwPIJXCvQjvT7fOqKf76QHA8G4ODATg0CDwMx0YDUrR6cTMiBwMCyK4gMQfKBwJksvBQMSyQi0EQxOAg9kAFTiYgENBiSjgluttvtcE87qd8Rd4LBuE8QA)

**Comment by PabloLION** [comment]
A similar issue happened in `discriminatedUnion. Seems that TS engine cannot deduce the generic types from an identical array constructed with array in the `types: [...]`.

Current workaround I'm using is to manually expand all the variables.

**Comment by devklick** [comment]
It compiles OK if you create the union and the litterals in a single line, e.g.
```ts
const fruitUnion = z.union([z.literal('apple'), z.literal('banana')]); // type: z.ZodUnion<[z.ZodLiteral<"apple">, z.ZodLiteral<"banana">]>
```

However as soon as you try and split the creation of the litterals and union into multiple steps, it cant compile:
```ts
const fruitValuesLiterals = [z.literal('apple'), z.literal('banana')]; // type: (z.ZodLiteral<"apple"> | z.ZodLiteral<"banana">)[]
const fruitUnion = z.union(fruitValuesLiterals); // Argument of type '(ZodLiteral<"apple"> | ZodLiteral<"banana">)[]' is not assignable to parameter of type 'readonly [ZodTypeAny, ZodTypeAny, ...ZodTypeAny[]]'. Source provides no match for required element at position 0 in target.
```

Based on this, I'm thinking that it's not currently possible to achieve this. However It would be good to see this in the future.

**Comment by devklick** [comment]
Just to expand on my previous comment,
Just to add that my second example _does_ compile if you specify the type as a tuple with ZodLitteral types, e.g:
```ts
const fruitValuesLiterals: [z.ZodLiteral<'apple'>, z.ZodLiteral<'banana'>] = [z.literal('apple'), z.literal('banana')]; // type: (z.ZodLiteral<"apple"> | z.ZodLiteral<"banana">)[]
const fruitUnion = z.union(fruitValuesLiterals); // type: z.ZodUnion<[z.ZodLiteral<"apple">, z.ZodLiteral<"banana">]>
```

However I'm not sure of any way to build this type dynamically based on the values in the enum/const object

**Comment by devklick** [comment]
Just to expand on my previous comment, it _does_ compile if you specify the type as a tuple with ZodLitteral types, e.g:
```ts
const fruitValuesLiterals: [z.ZodLiteral<'apple'>, z.ZodLiteral<'banana'>] = [z.literal('apple'), z.literal('banana')]; // type: (z.ZodLiteral<"apple"> | z.ZodLiteral<"banana">)[]
const fruitUnion = z.union(fruitValuesLiterals); // type: z.ZodUnion<[z.ZodLiteral<"apple">, z.ZodLiteral<"banana">]>
```

However I'm not sure of any way to build this type dynamically based on the values in the enum/const object.

**Comment by PabloLION** [comment]
@devklick I think you are missing the point here: 

What I wanted was to use iteration with zod and something like [Template Literal Types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html#handbook-content). 

The point of this issue is to say that it only works with `z.union([z.literal('apple'), z.literal('banana')])` but not with `z.union(Object.values(Fruits).map(value => z.literal(value)))`. You are reiterating that in the first case it works and didn't mention the second case at all. (Tho AFAIK it is hard to achieve in TS.)

**Comment by devklick** [comment]
@PabloLION Thanks for clarifying. Can you elaborate on your workaround? Not sure what you mean by expanding the loop.

**Comment by PabloLION** [comment]
@devklick Sorry for the vagueness. I edited the post before. It's just like what you did.

**Comment by PabloLION** [comment]
Hi @colinhacks , would you mind checking this issue and decide if we are going to work on it? Thanks in advance.
