### ISSUE TITLE
Latest release's types not working?

### ISSUE THREAD

**Issue by Lilja** [colinhacks/zod#1161]
Excuse the horrible title, but I'm creating a PR over at trpc and some CI tool is telling me this:

```
$ next build
--
10:53:39.158 | info  - Loaded env from /vercel/path1/.env
10:53:39.404 | info  - Checking validity of types...
10:53:44.795 | Failed to compile.
10:53:44.795 |  
10:53:44.796 | ./node_modules/zod/lib/helpers/parseUtil.d.ts:1:15
10:53:44.796 | Type error: ',' expected.
10:53:44.796 |  
10:53:44.796 | > 1 \| import { type IssueData, type ZodErrorMap, type ZodIssue } from "../ZodError";
10:53:44.796 | \|               ^
10:53:44.797 | 2 \| import { type ZodParsedType } from "./util";
10:53:44.797 | 3 \| export declare const makeIssue: (params: {
10:53:44.797 | 4 \|     data: any;

```

I didn't have this error yesterday, so I'm assuming that this is relate to the latest release.
In fact, it looks like [this github actions job](https://github.com/colinhacks/zod/commit/44916fe7dee9413216ee0b24001cfbf835cda584#diff-cf85b3e0a8cdc5f1bfea0bff847e1d89dfbb182c744fd0bc95eae659117b70fd) is telling that there needs to be some fixes.

**Comment by colinhacks** [comment]
Shoot, sorry. I fixed this when I saw that failure but forgot to publish the new version. Fixed in 3.17.3.
