### ISSUE TITLE
Schema annotations

### ISSUE THREAD

**Issue by fgarcia** [colinhacks/zod#1166]
Reading the README I have not found a way to define schemas with custom annotations

Currently I extend my JSON Schemas to annotate a property as "sensitive", so I know which fields have privacy concerns, like, it should not be appear in logs and/or it can be affected by user privacy laws.

I do not mean adding the "sensitive" property to a Schema property, but just store any random key-value combo. That will open the door to similar ideas. Since they are non standard, it can be safely ignored by tools depending on Zod and not increase the maintenance burden.

**Comment by omonk** [comment]
@colinhacks is there any appetite for something like this?
