### ISSUE TITLE
Deep-nullable utility?

### ISSUE THREAD

**Issue by ian-schu** [colinhacks/zod#1169]
Simple request: can a utility be added which does exactly what `deepPartial` does, but makes properties `nullable` instead of `optional`? For instance, `deepNullable()`, as a first stab.

I tried my hand at this myself, but admittedly the source for `deepPartial` is ... pretty tricky to follow 🙂 

If there's a way to do this that I've missed, please steer me straight. Thanks!

**Comment by michaelhays** [comment]
@ian-schu Did you find a good solution to this? A `deepNullish()` method would also be super useful.

**Comment by ian-schu** [comment]
@michaelhays I'm afraid not. I did manage to work around this for my own purposes, but that was a matter of changing my design, rather than hacking a `zod`-based solution.
