### ISSUE TITLE
Don't let `invalid_type_error` replace the default `required_error`

### ISSUE THREAD

**Issue by kbongort** [colinhacks/zod#1174]
The default error when parsing `undefined` for a required value is "Required". When a value overrides its type error with `invalid_type_error`, that message also also overrides the default message for undefined values. I would expect that only `required_error` would override that message.

```
z.number().parse(undefined);
// Throws error with message "Required"

z.number({ invalid_type_error: 'Wrong type!' }).parse(undefined);
// Throws error with message "Wrong type!"
// Expected behavior: Throws error with message "Required"
```

**Comment by yogarasu** [comment]
I think this is a pretty critical issue, but I hope it will be merged sooner.

**Comment by waptik** [comment]
> It doesn't seem like `required_error` shows up in the error map either? At least not in the `ZodIssueCode` type, which means that there's no way to set a default or translate that error message. Which currently isn't an issue since it doesn't even show up because the type-error overrides it always, but yeah.

I can confirm that using `required_error ` even in `.string()` doesn't do anything so I had to use `.min()`
