### ISSUE TITLE
UUID parser is firing errors for valid UUIDs

### ISSUE THREAD

**Issue by pedroprado010** [colinhacks/zod#1186]
## Describe the bug

the UUID string validator doesn't work for UUIDs that have the third portion starting with a 0.

## To Reproduce

```js
const { z } = require('zod');
z.string().uuid().parse('30000000-0000-0000-0000-000000000000'); 
/*                                                            
    that will throw because of the first 0 at the third part of the UUID.
*/
```

**Comment by scotttrinh** [comment]
![image](https://user-images.githubusercontent.com/1682194/171935659-9ba640cc-8548-41b7-8d4f-033fe5641d90.png)

Seems like it's not a valid UUID?

**Comment by pedroprado010** [comment]
wow! seems so.. that's weird because postgres accepts that value as an uuid :sweat:

**Comment by scotttrinh** [comment]
Yeah this is the problem I have with built-in validators in general. There are a lot of different things you might mean when you say "UUID validation" or "email validation" or "url validation" so we end up having to be opinionated which means it doesn't work for some folks.
