### ISSUE TITLE
Zod 2?

### ISSUE THREAD

**Issue by lkj4** [colinhacks/zod#1195]
@colinhacks just read on your profile that you're working on Zod 2. Since I'm about to go all in with Zod on a bigger project it would be great if we could learn more about Zod 2, in particular if there'll be an upgrade path, if Zod 1 will be kept maintained and a rough ETA for Zod 2. Thanks.

Edit: Ok, I think your profile text is old and we are already past Zod __version__ 2, so I presume it's safe to go all in 🙂

**Comment by colinhacks** [comment]
Just updated the bio - it was massively out of date. Thanks for calling that to me attention :)
