### ISSUE TITLE
How to enable "eager validation" after first failed form submission?

### ISSUE THREAD

**Issue by ryancwalsh** [colinhacks/zod#1204]
Thank you so much for this amazing library.

I'm using Zod in a Mantine form on a Next.js app, and it's working well.

One possible UX improvement on my form would be for field validation to be "eager" (i.e. instant on every keyUp event) after the first time the visitor tries to submit a form with invalid values.

For example, I have this rule:

```
z
    .string()
    .max(64, { message: 'Maximum 64 characters' })
    .refine((acc) => acc === '' || mainnetRegex.test(acc), {
      message:
        'If you are providing a named NEAR mainnet account address (which is optional), it must be valid and end with `.near`. See https://docs.near.org/docs/concepts/account#account-id-rules for details.',
    })
    .optional()
```

If a visitor tries to submit the form and then sees that error, it would be ideal if the visitor could see the error message go away *immediately* whenever the field's value is edited such that it is valid.

How could I achieve this UX while using zod? Thanks!

**Comment by colinhacks** [comment]
That'll have to be handled by Mantine - out of scope for Zod. I suggest looking through Mantine's docs for this answer.
