### ISSUE TITLE
Issue with types? Using refine() with an array results in typescript linting error saying type is missing the message property. However, works in runtime. 

### ISSUE THREAD

**Issue by ryerrappa** [colinhacks/zod#1205]
Hello, I am using zod as a resolver with react hook form. I have a schema setup as follows:

```typescript

const mySchema = z.object({
  // some other properties
  myArray: z.array({
    // some properties
  })
  .min(1)
  .max(10)
  .refine(
    (item) => {
      // some validation
    },
    {
      message: "My error message"
    }
  )
});
```

When trying to access the error message like below, I get a linting error saying property 'message' does not exist on type. However during runtime there is no error and I can access the message properly.

```typescript
formState.errors.myArray.message
```

Any idea on how to resolve this?

**Comment by ryerrappa** [comment]
> Currently I'm using (errors.someField as any)?.message but that seems like a hack.
The example is constructed with Chakra UI & react-hook-form in mind but I guess the error might be similar with other libs.

If you don't want to use `any` you can use `@ts-expect-error` as a workaround for now.

Solution courtesy of [bennettdams](https://github.com/bennettdams). Discussion: https://github.com/react-hook-form/react-hook-form/discussions/7111#discussioncomment-2956401

**Comment by AustinShelby** [comment]
I tried to reproduce this issue but wasn't able to get the error: [https://codesandbox.io/s/issue-with-types-using-refine-with-an-array-results-in-typescript-linting-error-z9etol?file=/src/App.tsx](https://codesandbox.io/s/issue-with-types-using-refine-with-an-array-results-in-typescript-linting-error-z9etol?file=/src/App.tsx)

Can you show a full example where this error occurs?
