### ISSUE TITLE
How can I allow `null` as input value of a schema, but not as a valid output?

### ISSUE THREAD

**Issue by Svish** [colinhacks/zod#1206]
I'm trying to use `zod` and `react-hook-form` together, and find it a bit difficult to deal setting `defaultValues` in a way that makes both `react-hook-form`, `typescript` _and_ the actual schema validation happy.

Say you have this schema:
```ts
const zodSchema = z.number().int().nonnegative()
type ZodValues = z.input<typeof zodSchema>
// number <-- want null to be allowed here
type ZodValid = z.output<typeof zodSchema>
// number
```
Here both `ZodValues` and `ZodValid` does not allow `null` as a value.

If I add `nullable`, we get this:
```ts
const zodSchema = z.number().int().nonnegative().nullable()
type ZodValues = z.input<typeof zodSchema>
// number | null
type ZodValid = z.output<typeof zodSchema>
// number | null // <-- don't want null to be allowed here
```

Using `yup@0.32.11` (latest now), it seems I'm able to do it like this, which is what I want:
```ts
const yupSchema = number().nullable(true).required().integer().min(0)
type YupValues = TypeOf<typeof yupSchema>
// number | null | undefined
type YupValid = Asserts<typeof yupSchema>
// number
```

Is there any way I can write this schema with `zod`, so that the _input_ allows `null`, while the _output_ does not?

The issue is that `react-hook-form` preferably wants non-undefined default values for the input, and for e.g. `number` and `Date` inputs I'd really prefer to use `null` as I do not want to pick a random number or date to use as the default.

**Comment by scotttrinh** [comment]
You can achieve this with a transform, but that means that you're going to have to "pick a random number or date to use as the default" in the case where you pass `null` into the input. The difference between yup and zod is that zod considers itself a parser, so if you say a schema takes `number | null` and returns `number` you need to map everything from the input domain to the output domain, which requires that you pick a number for the `null` case.

I don't have a lot of experience with `react-hook-form`, but I suspect they don't really require the `defaultValues` to have the same type as the input type of the validation schema, right? In that case, is there a parsing/validation need for taking inputs of type `T | null`?

**Comment by Svish** [comment]
@scotttrinh That makes sense, but does `transform` happen before or after validation? I can for example transform into `NaN` if the value is `null`, but would the validation happen "on" `null` or `NaN` in that case?

Like, the following seems work type-wise, but not sure I understand what exactly happens with the validation in this case:

```
const zodSchema= z.number()
      .positive()
      .nullable()
      .transform((value) => value ?? NaN)

type ZodValues = z.input<typeof zodSchema>;
// number | null
type ZodValid = z.output<typeof zodSchema>;
// number
```

**Comment by Svish** [comment]
As for the `react-hook-form` part of it, I asked a question in their repo for that. Basically, their `useForm` only accepts a single generic for their `TFieldValues`, which is used for both `defaultValues` and the `handleSubmit`, meaning you have to pick one. I suppose I could just go with `z.input` for both, and then just trigger an extra `parse` before I pass it to the request-handler, or something like that, but yeah. nothing really `zod` related.

**Comment by scotttrinh** [comment]
> but does transform happen before or after validation?

It happens after input parsing, if that makes sense. The flow goes:

```mermaid
flowchart LR
  A[input] --> B{Nullable?};
  B -- null --> D[Transform];
  B -- number --> C{Positive?};
  B -- other --> F[Throw];
  C -- true --> D[Transform];
  C -- false --> F[Throw];
  D -- null --> G[NaN];
  D -- number --> H[number];
```

> meaning you have to pick one. I suppose I could just go with z.input for both, and then just trigger an extra parse before I pass it to the request-handler, or something like that, but yeah. nothing really zod related.

I don't think you need to trigger an extra parse, I believe the integration already passes it through the parser. You might need to add some type annotations in our submit handler or something like that, but I think you can/should trust the output of `react-hook-form` to have been run through the schema already. Let me know if you find this isn't the case and we can work with them to get it working properly.

**Comment by Svish** [comment]
Reading your flow diagram, it then seems that `null` would actually get through all of validation, without being stopped anywhere, and finally be transformed to `NaN`, which would then be considered "valid"?

**Comment by Svish** [comment]
Yeah, just confirmed it. `.nullable()` allows `null` to get through, which I guess I should've expected. But then I'm even less sure how to actually allow `null` type-wise, but not validation-wise 🤔

**Comment by scotttrinh** [comment]
Yeah, I think maybe that's the crux of the issue: the two types describes valid inputs and valid outputs. It doesn't describe the domain of expected inputs that might be sent (that is `unknown` really).

For my purposes, I don't care that much about the type of the form state since forms have a very loose set of data structures compared to my much more restricted domain model. Whatever works is fine and I trust that the schema does the right thing in all of the situations such that I can "trust" the parsed output. Does that make sense? I don't know how that squares with the various form libraries, though.

**Comment by scotttrinh** [comment]
> allows null to get through

Yeah, and that's why I said you'll have to map `null` to _something_ in the `number` domain since you're saying the input domain is `number | null` and the output is `number`. You have two choices: `null` is not a valid input, then you have `number` to `number`. `null` maps to a `number` like `NaN` or `0` or `-1` or whatever makes sense.

**Comment by Svish** [comment]
Discovered the `transform` function gets a `ctx` with an `addIssue` function, so this seems to be a workaround of sorts...

```ts
z
    .positive()
    .nullable()
    .transform((value, ctx): number => {
      if (value == null)
        ctx.addIssue({
          code: 'custom',
          message: 'X Cannot be null',
        });
      return value ?? NaN;
    })
```

That gets correct type, and stops it with a validation issue. Will be quite annoying to have to add that to every nullable number though, haha.

Does `zod` have any way to "extend" it with custom functions? Like, is it possible to add custom stuff to the "chain", like a `.nullNotAllowed()` or `creditCardNumber()` or something like that?

**Comment by alavkx** [comment]
I already commented in another issue, but it seems more appropriate here. I'm _terribly_ confused how to deal with `defaultValue` when using `zod` with `react-hook-form`. https://github.com/colinhacks/zod/issues/804#issuecomment-1198591366

FWIW I'm encountering similar struggles when attempting to work with number inputs, using `zod` as a `react-hook-form` resolver. It is.....pretty challenging to figure out.
https://codesandbox.io/s/stupefied-moser-0fpq94?file=/src/App.tsx

<h1>Given...</h1>
        <ul>
          <li> a strongly typed endpoint</li>
          <li> a matching zod schema (consider tRPC)</li>
          <li> a form design for HTTP PATCH; a partial update</li>
          <li> the need to represent NO CHANGE as an empty input</li>
          <li>
            HTML's native behavior to represent EMPTY as empty string ('')
          </li>
        </ul>
        <h4>How do you represent a number input?</h4>

**Comment by kharann** [comment]
I'm feeling some problems with this issue too when dealing with databases.

Values from databases are usually null. Ideally, I would parse them with zod and transform all nulls into undefined. Null has some weird behavior and therefore I would rather use undefined if I can. Does anyone know if it is possible to transform all nulls on outputs, but allow outputs on inputs?

**Comment by divmgl** [comment]
I'm facing this issue too when building forms. The value is correctly `null` because the type exists and is present in the object, but the value has not yet been picked.

**Comment by zoltanr-jt** [comment]
Hey @Svish!
This helped me:
 https://github.com/react-hook-form/react-hook-form/issues/8046#issuecomment-1073348421 
 
 I used the `DefaultValues` generic type to create
 
```
import {DefaultValues} from "react-hook-form";

export type FormType = z.infer<typeof FormSchema>

 export const initialFormData: DefaultValues<FormType> = {
  name: undefined,
  nested: {
    amount: 1,
    date1: undefined,
    date2: undefined,
    time: undefined
  }
};
```
then 

```
  const methods = useForm<FormType>({
    defaultValues: initialFormData,
    resolver: zodResolver(FormSchema)
  });
```

**Comment by lukasvice** [comment]
Setting the default values works with the `DefaultValues` type, as described in @zoltanr-jt's answer. But what about

```ts
const date = methods.watch('nested.date1')
```

This always returns the form field type set by Zod (`date`). But this is not true, because it can also be `undefined` if no value has been set yet.

**Comment by Svish** [comment]
@lukasvice Yep, I have the same issue. But, I think it needs to be fixed in `react-hook-form`, or at least in `@hookform/resolvers`, since it's not really a problem with `zod`. `zod` actually has the tools (`z.input` and `z.output`), but the `react-hook-form` types don't use the correct ones in correct context. `z.output` should only be used as the type for the submit-handler, while `z.input` should be used for `defaultValues`, `values` and things like `watch`, `setValue`, etc.

**Comment by TonyGravagno** [comment]
I've been challenged with this same issue. Documented the question in Discussions before I saw this Issue:  
https://github.com/colinhacks/zod/discussions/2431

🚨  I'm hoping this ticket gets re-opened because it's not a closed topic.

Ref https://github.com/colinhacks/zod/discussions/1953 where we're collaborating on code to generate a valid Default object from a Zod schema. Is this exactly what's done in React Hook Form?

While I am using react-hook-form, in code that is not using that great library I would still like to use Zod, so I'd prefer not to have to rely on the external library to generate defaults for this one.

At this moment I'm struggling with the simple concept where:  
`birthDate: z.coerce.date(undefined)`
`defaultData.birthDate` is null
and `.safeParse(defaultData)` validates `true` because it converts null into the date string for 1967/12/31.

I don't want the default. I'm intentionally setting the date as null or undefined because I want safeParse to fail until a valid value is set.

**Comment by Svish** [comment]
@TonyGravagno RHF simply has a `DefsultValues` type helper, which recursively converts a given type into partials (making everything optional).

Re your date issue, that's an issue with your own code. If you don't want `null` coerced into a date, then don't use coerce. Coerce simple passes whatever value it gets through `new Date`. If that gives you something wrong, don't use it.

**Comment by lukasvice** [comment]
Update: I ended up doing something like this:

```ts
const schema = z.object({
  age: z.number().positive()
});

type SchemaOut = z.input<typeof schema>;
type SchemaIn = Omit<SchemaOut, 'age'> & {
  age: SchemaOut[age] | null
}
```

Or use a `WithNullableFields` helper like this one: https://stackoverflow.com/a/72241609

**Comment by likerRr** [comment]
In case if someone still facing the issue. Zod has a dedicated paragraph on how to do [type refinements](https://zod.dev/?id=type-refinements), which in my case also works for `react-hook-form`. For example I have a form where the input value can be either `File | null`, but submit value must be strictly `File`. What I do:

```typescript
const schema = z.object({
  file: z
    .instanceof(File) 
    .nullable()
    .superRefine((arg, ctx): arg is File => {
      if (!(arg instanceof File)) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: 'Select a file',
          fatal: true, // abort early on this error in order not to fall down to the next refine with a null value
        });
      }

      return z.NEVER;
    })
    .refine(
      // here typescript already knows that the "file" is a File
      // But if we don't do "fatal: true" in superRefinement, zod will also pass null, despite TS says it's a File
      file => file.size < 10 * 1024 * 1024,
      `Size limit exceeded`,
    )
})

type FormInitial = z.input<typeof schema>;
type FormSubmit = z.output<typeof schema>;

// then use it with react-hook-form
const form = useForm<FormInitial, any, FormSubmit>({
  resolver: zodResolver(schema),
  defaultValues: {
    file: null, // accepts File | null
  },
});

form.handleSubmit(data => /** data here is a FormSubmit type **/)
```

I saw the answer with using [transform](https://github.com/colinhacks/zod/issues/1206#issuecomment-1597126130), but in my opinion the transform should be used for data transformation, e.g. changing it's type, shape or whatever. Refine is for validation purposes, which is the case when my schema accepts `null` value when I expect `File` in the output.

**Comment by likerRr** [comment]
> In case if someone still facing the issue. Zod has a dedicated paragraph on how to do [type refinements](https://zod.dev/?id=type-refinements), which in my case also works for `react-hook-form`. For example I have a form where the input value can be either `File | null`, but submit value must be strictly `File`. What I do:
> 
> ```ts
> const schema = z.object({
>   file: z
>     .instanceof(File) 
>     .nullable()
>     .superRefine((arg, ctx): arg is File => {
>       if (!(arg instanceof File)) {
>         ctx.addIssue({
>           code: z.ZodIssueCode.custom,
>           message: 'Select a file',
>           fatal: true, // abort early on this error in order not to fall down to the next refine with a null value
>         });
>       }
> 
>       return z.NEVER;
>     })
>     .refine(
>       // here typescript already knows that the "file" is a File
>       // But if we don't do "fatal: true" in superRefinement, zod will also pass null, despite TS says it's a File
>       file => file.size < 10 * 1024 * 1024,
>       `Size limit exceeded`,
>     )
> })
> 
> type FormInitial = z.input<typeof schema>; // { file: File | null }
> type FormSubmit = z.output<typeof schema>; // { file: File }
> 
> // then use it with react-hook-form
> const form = useForm<FormInitial, any, FormSubmit>({
>   resolver: zodResolver(schema),
>   defaultValues: {
>     file: null, // accepts File | null
>   },
> });
> 
> form.handleSubmit(data => /** data here is a FormSubmit type **/)
> const file = form.watch('file'); // "file" is "File | null"
> ```
> 
> I saw the answer with using [transform](https://github.com/colinhacks/zod/issues/1206#issuecomment-1597126130), but in my opinion the transform should be used for data transformation, e.g. changing it's type, shape or whatever. Refine is for validation purposes, which is the case when my schema accepts `null` value when I expect `File` in the output.

I have to correct myself. Since my solution works fine, I ended up using `transform` instead of `superRefine`, cause transform infers resulting type and it's very handful. I also made a little snippet which can be easily used as a wrapper over any zod type:

```typescript
const nullableInput = <T extends ZodTypeAny>(
  schema: T,
  message = 'Output value can not be null',
) => {
  return schema.nullable().transform((val, ctx) => {
    if (val === null) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        fatal: true,
        message,
      });

      return z.NEVER;
    }

    return val;
  });
};

// usage:
const schema = z.object({
  photo: nullableInput(z.instanceof(File)),
  name: nullableInput(z.string().min(1)),
  age: nullableInput(z.number().min(18), 'Please, provide age'), // with custom error message
});

export type FormInitial = z.input<typeof schema>; // { photo: File | null, name: string | null, age: number | null }
export type FormSubmit = z.output<typeof schema>; // { file: File, name: string, age: number }

```

There is also a separate issue, which describes why [`fatal: true`](https://github.com/colinhacks/zod/issues/2192) is important here.

**Comment by denchen** [comment]
> You can now use the `TTransformedValues` parameter of `useForm`:
> 
> const schema = z.object({
>   age: z
>     .number()
>     .positive()
>     .nullable()
>     .transform((value, ctx): number => {
>       if (value == null) {
>         ctx.addIssue({
>           code: "invalid_type",
>           expected: "number",
>           received: "null"
>         });
>         return z.NEVER;
>       }
>       return value;
>     })
> });
> 
> type SchemaIn = z.input<typeof schema>;
> type SchemaOut = z.output<typeof schema>;
> 
> const form = useForm<SchemaIn, never, SchemaOut>({
>   resolver: zodResolver(schema),
>   defaultValues: {
>     age: null
>   }
> });
> 
> Check out https://codesandbox.io/s/rhf-zod-defaultvalue-vxmncm?file=/src/App.tsx

@lukasvice Sorry to bring up an old issue, but your solution doesn't seem to work as far as type safety goes, with the latest versions of zod / react-hook-form. Using your exact code, I get a type error:

```
Type 'Resolver<{ age: number; }>' is not assignable to type 'Resolver<{ age: number | null; }, never>'.
  Types of parameters 'values' and 'values' are incompatible.
    Type '{ age: number | null; }' is not assignable to type '{ age: number; }'.
      Types of property 'age' are incompatible.
        Type 'number | null' is not assignable to type 'number'.
          Type 'null' is not assignable to type 'number'.ts(2322)
```

You can see the issue yourself in your own CodeSandbox if you update `react-hook-form` to at least 7.54.2.

**Comment by denchen** [comment]
@BrendanC23 

I just opened your CodeSandbox and see this:

<img width="629" alt="Image" src="https://github.com/user-attachments/assets/91a59166-3afc-4abc-853e-c9a8439357bf" />

**Comment by narbek-abd** [comment]
what about this:

```typescript
import { z } from "zod";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

export const schema = z.object({
  numberRequired: z
    .union([z.number(), z.null()])
    .pipe(z.number({ message: "This field is required" })),
});

export default function Page() {
  const f = useForm<z.input<typeof schema>>({
    resolver: zodResolver(schema),
    defaultValues: {
      numberRequired: null,
    },
  });
  const a = f.watch("numberRequired"); // number | null

  function onSubmit(data: z.output<typeof schema>) {
    console.log(data); // number
  }
}
```

**Comment by lukasvice** [comment]
> what about this:
> 
> import { z } from "zod";
> import { useForm } from "react-hook-form";
> import { zodResolver } from "@hookform/resolvers/zod";
> 
> export const schema = z.object({
>   numberRequired: z
>     .union([z.number(), z.null()])
>     .pipe(z.number({ message: "This field is required" })),
> });
> 
> export default function Page() {
>   const f = useForm<z.input<typeof schema>>({
>     resolver: zodResolver(schema),
>     defaultValues: {
>       numberRequired: null,
>     },
>   });
>   const a = f.watch("numberRequired"); // number | null
> 
>   function onSubmit(data: z.output<typeof schema>) {
>     console.log(data); // number
>   }
> }

I think this is a good approach. With Zod 3, you have to use `invalid_type_error` instead of `message`:
```ts
.pipe(z.number({ invalid_type_error: "This field is required" }))
```

Also, I don't think you need to specify the generic types in `useForm` with the latest resolver. Or you should add the output to ensure the correct types are used in the submit function.

```ts
useForm<z.input<typeof schema>, unknown, z.output<typeof schema>>
```

**Comment by narbek-abd** [comment]
Thanks. 
Helper function gives some typescript errors. Anyone knows how to fix it?
```typescript
function nullableInput<T extends z.ZodType>(schema: T) {
  return z.union([schema, z.null()]).pipe(schema);
}
```
Argument of type 'T' is not assignable to parameter of type '$ZodType<any, $InferUnionOutput<T> | null, $ZodTypeInternals<any, $InferUnionOutput<T> | null>> | $ZodType<...>'.
  Type 'ZodType<unknown, unknown, $ZodTypeInternals<unknown, unknown>>' is not assignable to type '$ZodType<any, $InferUnionOutput<T> | null, $ZodTypeInternals<any, $InferUnionOutput<T> | null>> | $ZodType<...>'.
    Type 'ZodType<unknown, unknown, $ZodTypeInternals<unknown, unknown>>' is not assignable to type '$ZodType<any, $InferUnionOutput<T> | null, $ZodTypeInternals<any, $InferUnionOutput<T> | null>>'.
      Types of property '_zod' are incompatible.
        Type '$ZodTypeInternals<unknown, unknown>' is not assignable to type '$ZodTypeInternals<any, $InferUnionOutput<T> | null>'.
          Type 'unknown' is not assignable to type '$InferUnionOutput<T> | null'.
            Type 'T' is not assignable to type '$ZodType<any, $InferUnionOutput<T> | null, $ZodTypeInternals<any, $InferUnionOutput<T> | null>>'.
              Type 'ZodType<unknown, unknown, $ZodTypeInternals<unknown, unknown>>' is not assignable to type '$ZodType<any, $InferUnionOutput<T> | null, $ZodTypeInternals<any, $InferUnionOutput<T> | null>>'.
                Types of property '_zod' are incompatible.
                  Type '$ZodTypeInternals<unknown, unknown>' is not assignable to type '$ZodTypeInternals<any, $InferUnionOutput<T> | null>'.
                    Type 'unknown' is not assignable to type '$InferUnionOutput<T> | null'.

**Comment by clemwo** [comment]
> Thanks. Helper function gives some typescript errors. Anyone knows how to fix it?
> 
> function nullableInput<T extends z.ZodType>(schema: T) {
>   return z.union([schema, z.null()]).pipe(schema);
> }
> 
> Argument of type 'T' is not assignable to parameter of type '$ZodType<any, $InferUnionOutput | null, $ZodTypeInternals<any, $InferUnionOutput | null>> | $ZodType<...>'. Type 'ZodType<unknown, unknown, $ZodTypeInternals<unknown, unknown>>' is not assignable to type '$ZodType<any, $InferUnionOutput | null, $ZodTypeInternals<any, $InferUnionOutput | null>> | $ZodType<...>'. Type 'ZodType<unknown, unknown, $ZodTypeInternals<unknown, unknown>>' is not assignable to type '$ZodType<any, $InferUnionOutput | null, $ZodTypeInternals<any, $InferUnionOutput | null>>'. Types of property '_zod' are incompatible. Type '$ZodTypeInternals<unknown, unknown>' is not assignable to type '$ZodTypeInternals<any, $InferUnionOutput | null>'. Type 'unknown' is not assignable to type '$InferUnionOutput | null'. Type 'T' is not assignable to type '$ZodType<any, $InferUnionOutput | null, $ZodTypeInternals<any, $InferUnionOutput | null>>'. Type 'ZodType<unknown, unknown, $ZodTypeInternals<unknown, unknown>>' is not assignable to type '$ZodType<any, $InferUnionOutput | null, $ZodTypeInternals<any, $InferUnionOutput | null>>'. Types of property '_zod' are incompatible. Type '$ZodTypeInternals<unknown, unknown>' is not assignable to type '$ZodTypeInternals<any, $InferUnionOutput | null>'. Type 'unknown' is not assignable to type '$InferUnionOutput | null'.

Here is a helper function that works for me:
```
import type { ZodType } from 'zod';
import { z } from 'zod';

/**
 * Returns a Zod schema that allows null input
 * but doesn't add null to the output
 * To be used for react hook form
 */
export const getZodNullInputRequiredOutput = <TOutput, TInput>(
  schema: ZodType<TOutput, TInput> & ZodType<TOutput, TOutput | null>,
) => {
  return schema.nullable().pipe(schema);
};

const schema = z.object({
  value: getZodNullInputRequiredOutput(z.string()),
});

type InputSchema = z.input<typeof schema>; // { value: string | null; }
type OutputSchema = z.output<typeof schema>; // { value: string; }
```
