### ISSUE TITLE
Allow setting a label and pass it through to error map

### ISSUE THREAD

**Issue by Svish** [colinhacks/zod#1208]
Don't remember the exact rule, but I believe there is a WCAG requirement that error messages should refer to the name of the field it's about. I.e. `Field is required` is less good than for example `"First name" is required`.

Would be great if we could add a label to our schema, which would be used in the default error map, _and_ be made available in custom error map functions.

```ts
const mySchema = z.object({
  firstName: z.string({ label: 'First name' }),
  dateOfBirth: z.date({ label: 'Date of birth' }),
})
```

I see there's already a `description`, but it's not documented anywhere, so not sure what that is for. If it's actually for a label, then I guess this would be solved simply by exposing that `description` in the error map somehow. Maybe it could come as part of the `ErrorMapCtx` object?

<img src="https://user-images.githubusercontent.com/142162/173804787-a9987eb7-946d-489b-b6b4-4d09679858ff.png" alt="screenshot" width="350"/>

**Comment by WazzaJB** [comment]
I had a stab at this, not sure it's necessarily right or in the right place though given I have attached the info to `issue` as opposed to context...

Find myself in need of this functionality too 👍 

![Screenshot 2022-07-04 at 15 27 33](https://user-images.githubusercontent.com/2930904/177174599-649cfc57-efe3-4880-b91b-bf7b570398cc.png)

Notice the addition of "type" and "description" alongside how I have interpolated the description into the error message, the gist below shows how I achieved it. Pretty nasty implementation just to show in principle how error messages can more closely resemble how Yup handles them.

https://gist.github.com/WazzaJB/2eca3df3369c91317edaad3ed96862a6

**Comment by zynth17** [comment]
any roadmap to implement this?
in `yup` they have label method to override the field name.
this comes in handy when validation an object, so we can rename each field with human readable text not object name.
