### ISSUE TITLE
ZodFormattedError Does not work for union type

### ISSUE THREAD

**Issue by cawa-93** [colinhacks/zod#1214]
I have an interface with a template property that can be either a number or an object. The typewriter does not correctly display the type for the formatted error

```ts
zod.object({
    template: zod
        .number()
        .or(zod.object({
            label: string().nullish(),
        }))
```

I want to get a formatted error type
```ts
ZodFormattedError<ZodInterface, string>
// Expected
// {_errors: string[]} |  {_errors: string[], label: {_errors: string[]}}

// Actual
// {_errors: string[]}
```

[Reproduction in playground](https://www.typescriptlang.org/play?ts=4.5.5#code/C4TwDgpgBAWg9gEwGJwE4FsCGxgQQUVVTQB4AVAGigFUoBeKAZ2FQEsA7AcwD56oBvALAAoKGKgB9CETSMAXDQDaAXQDcIgL5QAZFAAUZKBAAeudgkZRFmdiCoA6RzZArlUAPwCR4qwGkoHFAA1hAgcABmUGTK7grwyGhYOHiExKjkir7K3OrCWgqGJmYWUM4qHl6i4opBCuwArugARtLKcYgoGNi4BDLpZIoNza05mlAFRqYQ5pZwTQBWEADGwBVCVWKZAezBoRFRMe0JXcm9aRlZo3njUPXsQexwAO7sAJS5IiIA9ABUUCIAL0Q9jmixWenWPlw6DAABtsBAFECEN4fOJ7EMWqg9K9UWioCDsciQQtlsAIXj8eJ4S1YQpmGwuDj7CxWOhmQ1YbDWIwABY4iiUnwaV64vJin5fESgSCwRAASXYuFQ4UwS2gDEh4mhcIRdUaWKgAB9KlSoDSILDYkxWVxjVBObD7XcEBBwhw8LlhbkNJ9hDLoKk+PFOkkeqlSPFFcrVeqqAyODw-Us4OxmEY+PwtJhLKk-RAWRAYfDcO57BarfYpH1LF8vlASABaGjsEyQFZ4Ix9IA)

**Comment by stvkoch** [comment]
Depends the result of validation: in case of success should return `{_errors: string[]}`, otherwise will return `{_errors: string[], label: {_errors: string[]}}`

**Comment by cawa-93** [comment]
Fuck you stale bot

**Comment by cawa-93** [comment]
Fuck you stale bot

**Comment by carlgieringer** [comment]
Presumably the maintainers chose to enable stale bot. By saying "fuck you stale bot", you are indirectly saying "fuck the maintainers' choice to use stale bot". Please consider that many (all?) of the maintainers are volunteering their time, and rude language is not great way to thank volunteers.

If you object to the use of stale bot, maybe you could open an issue about it.

**Comment by psychedelicious** [comment]
I have the same issue. Here's a codesandbox demonstrating the problem: https://codesandbox.io/s/quirky-archimedes-u3sejx?file=/src/index.ts

`z.ZodFormattedError` does indeed seem to be incorrect for union types, though the formatted errors object is in the expected shape.
