### ISSUE TITLE
non-partial `record`?

### ISSUE THREAD

**Issue by benwest** [colinhacks/zod#1215]
Hey, I notice that the type created by `z.record` is `Partial<Record>`, and I can't see a way to avoid the `Partial`. I don't want to use `z.object` because I have one enum of keys that I want to use across many record types, with different value types.

Maybe z.record isn't the one for this. In other words how can I create a schema for keys in one place, and re-use it for many object schemas?

For example:

```ts
const Languages = z.enum(["en", "fr"])

const Translations = z.record(Languages, z.string())
const hello = Translations.parse({ en: "hello", fr: "bonjour" })
const v = hello.en // string | undefined

const Numbers = z.record(Languages, z.array(z.string()))
const numbers = Numbers.parse({ fr: ["un", "deux"] }) // should fail without 'en' key

**Comment by Svish** [comment]
If it's required to have a specific set of keys, then it's not really a "record", I would say. How about just creating a helper function to create these schemas instead?

```ts
function makeTranslation<T extends z.ZodTypeAny>(schema: T) {
  return z.object({
    en: schema,
    fr: schema,
  });
}

const Translations = makeTranslation(z.string());
const hello = Translations.parse({ en: 'hello', fr: 'bonjour' });
const v = hello.en; // string

const Numbers = makeTranslation(z.array(z.string()));
const numbers = Numbers.parse({ fr: ['un', 'deux'] }); // should fail
```

**Comment by mi-roh** [comment]
I have a similar Problem. 

Zod seams to type a little different as I would expect, compared with TS. 

f.e. 
```typescript
enum NamedEnum {
  list1 = 'List 1',
  list2 = 'List 2',
}

// TS Definition
type ListTs = Record<NamedEnum, string>

// Zod Definition - 'visually' the same definition as ListTs
const listSchema = z.record(z.nativeEnum(NamedEnum), z.string())
type ListZod = z.infer<typeof listSchema>

// TS List - all Enum-Values are required
const namedListTs: ListTs = {
  [NamedEnum.list1]: 'value 1',
  [NamedEnum.list2]: 'value 2',
}

// Zod List - all Enum-Values are optional
const namedListZod: ListZod = {
  [NamedEnum.list1]: 'value 1',
  // ... list2 is not required
}
// Zod List - a TS-Required works as expected
const namedListZodFixed: Required<ListZod> = {
  [NamedEnum.list1]: 'value 1',
  [NamedEnum.list2]: 'value 2',
}
```

Is there a way to add the required within the zod-eco-system? But in nested scenarios that's more of a problem.

**Comment by akomm** [comment]
Thanks for not only ignoring the issue with `exactOptionalProperties` and closing it without a single word, but now also hard-coding breakage in a featue version that makes using `exactOptionalProperties` pointless. Looks like this lib is now not upgradable and stuck at <3.14.x for me.

Becaue now if you use `exactOptionalProperties` I can not benefit of unassignability of `undefined` if not specified explicitly, because you'v hard-coded `undefined` into the type, instead of leaving the option to the user to use `exactOptionaProperties` and `.nullable()` where needed.
