### ISSUE TITLE
Property 'infer' does not exist

### ISSUE THREAD

**Issue by 7flash** [colinhacks/zod#1220]
![image](https://user-images.githubusercontent.com/4569866/175447934-01797006-914e-4efc-b06f-2330c737a2a2.png)

**Comment by mike-hogan** [comment]
I had the same issue, because I also had `@types/zod` in `package.json`.

**Comment by gino8080** [comment]
i have the same issue, but i don't have installed @types/zod

**Comment by cbrown01** [comment]
FWIW, my mistake was using `const` instead of `type`:

`export const Model = z.infer<typeof Schema>;` -- error
`export type Model = z.infer<typeof Schema>;` -- no error

**Comment by JacobWeisenburger** [comment]
Has this issue been resolved? If so, I would like to close this issue.

**Comment by mike-hogan** [comment]
> Has this issue been resolved? If so, I would like to close this issue.

Resolved for me, yes
