### ISSUE TITLE
'keyof typeof' js-object to zod-schema

### ISSUE THREAD

**Issue by cl10k** [colinhacks/zod#1221]
Hi,

we are slowly transitioning from a JavaScript code base to TypeScript. Due to the quantity of code and our inexperience with TypeScript, we have to live with both worlds for the foreseeable future.

We used simple js Objects as pseudo enums in the past:

**within a js file:** 

```
const pseudoEnum = {
  ELECTRIC: {someProp: true, anotherProp: "xxx"},
  PNEUMATIC: {someProp: false, anotherProp: "yyy"},
  HYDRAULIC: {someProp: true, anotherProp: "zzz"},
}
```
This allows us to type stuff like this:

**within a ts file:**
```
type Application: keyof typeof pseudoEnum
```
Which nicely restricts possible values for elements of type Application:
![image](https://user-images.githubusercontent.com/1145346/175484336-aefb28bc-1b3e-4944-9f1d-d9d3e2ffa8cb.png)

How can I mimic this behavior in a zod schema?
I spent quite a while playing with z.enum and z.nativeEnum, but I don't get it to resolve properly.

_I'd prefer not to rewrite our pseudoEnums since so much of our js code base relies on it..._

Thanks in advance
Nice regards
Christian

---
My apologies if you think that this does not belonging here. Feel free to close it. :)

**Comment by WilliamVearrier** [comment]
Since `z.enum` takes in an array containing the values, you can provide an array with those values. 
Two ways immediately come to mind:
 * `Object.keys(pseudoEnum)` but then you gotta do some type casting to make it the correct tuple type
 * Directly create the tuple yourself.

For `Object.keys` you can do as below
```ts
const applications = Object.keys(pseudoEnum) as ["ELECTRIC" , "PNEUMATIC" , "HYDRAULIC"];
```
This could then be feed into zod `z.enum(applications)`

A far better approach — in my opinion at least — would be to create the tuple yourself
```ts
// Typescript create typing of: const applications: readonly ["ELECTRIC", "PNEUMATIC", "HYDRAULIC"]
const applications = ["ELECTRIC" , "PNEUMATIC" , "HYDRAULIC"] as const;
```
It will be already be a tuple type `const applications: readonly ["ELECTRIC", "PNEUMATIC", "HYDRAULIC"]`
You can then base the `Application` off the new `applications` tuple
```ts
// type Application = "ELECTRIC" | "PNEUMATIC" | "HYDRAULIC"
type Application = (typeof applications)[number];
```
You can then add a typing to `pseudoEnums`
```ts
const pseudoEnums: Record<Application, {someProp: boolean, anotherProp: string}>  = {
  ELECTRIC: {someProp: true, anotherProp: "xxx"},
  PNEUMATIC: {someProp: false, anotherProp: "yyy"},
  HYDRAULIC: {someProp: true, anotherProp: "zzz"}
};
```
If you add or remove an entry, it will generate an error.
```ts
const pseudoEnums: Record<Application, {someProp: boolean, anotherProp: string}>  = {
  ELECTRIC: {someProp: true, anotherProp: "xxx"},
  PNEUMATIC: {someProp: false, anotherProp: "yyy"},
  HYDRAULIC: {someProp: true, anotherProp: "zzz"},
  NEW_APP: {someProp: true, anotherProp: "zzz"} // Object literal may only specify known properties, and 'NEW_APP' does not exist in type 'Record<"ELECTRIC" | "PNEUMATIC" | "HYDRAULIC", { someProp: boolean; anotherProp: string; }>'.ts(2322)
};
```
You can then feed this into zod `z.enum(applications)`

**Comment by cl10k** [comment]
Hello William,

thanks for your reply! I just wanted to let you know, that I read your message!
---
For the last couple of days I tried to wrap my head around it. I don't get it. The problem probably roots in my insufficient knowledge of typescript and I don't want to misuse the issues section as stackoverflow. 

I need some more time to play with your approach and learn how ts in general handles pseudoenums. I promise to get back to you! :)

**Comment by kasparas-ban** [comment]
You can do it like so:

```
const schema = z.object({
  ELECTRIC: z.object({ someProp: boolean, anotherProp: string }),
  PNEUMATIC: z.object({ someProp: boolean, anotherProp: string }),
  HYDRAULIC: z.object({someProp: true, anotherProp: "zzz"}),
})

type Keys = keyof z.infer<typeof schema> // "ELECTRIC" | "PNEUMATIC" | "HYDRAULIC"
```

**Comment by smhmayboudi** [comment]
```typescript
const schema = z.object({
  ELECTRIC: z.object({ someProp: z.boolean(), anotherProp: z.string() }),
  PNEUMATIC: z.object({ someProp: z.boolean(), anotherProp: z.string() }),
  HYDRAULIC: z.object({ someProp: z.boolean(), anotherProp: z.string() }),
});

type Keys = keyof z.infer<typeof schema>; // "ELECTRIC" | "PNEUMATIC" | "HYDRAULIC"
type Keys2 = keyof z.TypeOf<typeof schema>; // "ELECTRIC" | "PNEUMATIC" | "HYDRAULIC"
type Keys3 = keyof typeof schema.shape; // "ELECTRIC" | "PNEUMATIC" | "HYDRAULIC"
```
