### ISSUE TITLE
Request: Introduce a convert method, to allow for transforms that may fail

### ISSUE THREAD

**Issue by Duncan3142** [colinhacks/zod#1223]
When attempting a transform, it's possible that the transform may fail. In this case, it's necessary to return a typecast dummy value.

I think having a 'convert' method on ZodType, which could return a success or failure value, would make for nicer DX.

The convert method would essentially combine a refine and transform, where the refinement failure would be fatal but the transform is necessary to determine the refinement.

The following serves as an example:

```ts
const IdToUser = z
  .string()
  .uuid()
  .convert(async (id) => {
    try {
      const user = await getUserById(id);
      return z.success(user);
    } catch (e) {
      return z.failure([
        {
          code: "custom",
          message: "Unable to fetch user",
        },
      ]);
    }
  });
```

See https://github.com/colinhacks/zod/pull/1224 for a potential implementation

**Comment by kibertoad** [comment]
there is a pr waiting for verdict for this

**Comment by Duncan3142** [comment]
This issue appears to be stale, so I've created a new issue describing an alternate approach

https://github.com/colinhacks/zod/issues/1390

PR https://github.com/colinhacks/zod/pull/1389 is a potential implementation for the above
