### ISSUE TITLE
how to express number string

### ISSUE THREAD

**Issue by UNDERCOVERj** [colinhacks/zod#1240]
our team handle i64 into string，so how should we validate this number string type

**Comment by AustinShelby** [comment]
What kind of validations are you planning on doing? One thing you can do is first transforming the string into a [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) so you can do simple comparisons.

**Comment by UNDERCOVERj** [comment]
I just want to validate a string which is like numeric type。In class-validator, it is expressed as IsNumberString

**Comment by UNDERCOVERj** [comment]
>

**Comment by UNDERCOVERj** [comment]
> I just want to validate a string which is like numeric type。In class-validator, it is expressed as IsNumberString

**Comment by AustinShelby** [comment]
If by `i64` you mean the Rust primitive type https://doc.rust-lang.org/std/primitive.i64.html then you can either use `refine` to write a custom validator function to check if the string is a `BigInt`.

```ts
const numberString = z.string().refine((value) => {
  try {
    BigInt(value);
    return true;
  } catch (e) {
    return false;
  }
});
```

or use a regex to check if the string only contains numbers

```ts
const numberString = z.string().regex(/^[0-9]*$/)
```

**Comment by UNDERCOVERj** [comment]
> If by `i64` you mean the Rust primitive type https://doc.rust-lang.org/std/primitive.i64.html then you can either use `refine` to write a custom validator function to check if the string is a `BigInt`.
> 
> ```ts
> const numberString = z.string().refine((value) => {
>   try {
>     BigInt(value);
>     return true;
>   } catch (e) {
>     return false;
>   }
> });
> ```
> 
> or use a regex to check if the string only contains numbers
> 
> ```ts
> const numberString = z.string().regex(/^[0-9]*$/)
> ```

ok，thank you very much。Can I add numberString as a method in z？

**Comment by icecreamparlor** [comment]
Not solved yet.
Fixed with PR https://github.com/colinhacks/zod/pull/1570
