### ISSUE TITLE
Getter maxLength in ZodString has incorrect type (null)

### ISSUE THREAD

**Issue by ealmansi-uc** [colinhacks/zod#1246]
**Snippet:**

```typescript
const s = z.string().max(10);
type L = typeof s.maxLength;
```

**Expected:**

```typescript
type L = number | null        // or ideally just number
```

**Actual:**

```typescript
type L = null
```

**Setup:**
- zod v3.17.3
- typescript v4.7.4

**Context:**

This is the current implementation of `maxLength`.

```typescript
  get maxLength() {
    let max: number | null = null;
    this._def.checks.map((ch) => {
      if (ch.kind === "max") {
        if (max === null || ch.value < max) {
          max = ch.value;
        }
      }
    });
    return max;        // typescript considers max to be of type null here
  }
```

The issue here is that Typescript ignores callbacks when it comes to type narrowing (assumes that they won't have any side effects). See https://github.com/microsoft/TypeScript/issues/35593 and https://github.com/microsoft/TypeScript/issues/9998. Since the only other operation on the variable `max` is its assignment to `null`, Typescript will narrow down its type to just `null`.

**Potential Fixes:**

- Add an explicit return type annotation of `number | null`.
- Replace `.map` with a for-of loop.

**Comment by Balastrong** [comment]
If you have a look at `minLength` right above, the default value is `-Infinity` and typescript properly infers `number`.

Would be interesting here to know why it has been decided to use a different behaviour between min and max (infinity and null) and also why there's an `Array.map` with side effects instead of a return value.
