### ISSUE TITLE
Extending z with custom types

### ISSUE THREAD

**Issue by anthonyma94** [colinhacks/zod#1258]
I'm using [Day.js](https://day.js.org) extensively in my application. The way to check for dayjs type is to check instanceof dayjs (the function):
```js
import dayjs from "dayjs";
const date = dayjs();
console.log(date instanceof dayjs) // true
```

The param type of `z.instanceof` only accepts classes with constructors, but it works in runtime for checking instanceof dayjs. This means that I have to typecast dayjs as any every time I need it in instanceof:
```ts
const dateType = z.instanceof(dayjs as any);
```

Is there an option to extend `z` so that I can do something like `z.dayjs()`?

**Comment by anthonyma94** [comment]
So dayjs actually provides a class for me to use: `z.instanceof(dayjs.Dayjs)`. However, I would still like to know if it's possible to extend z with custom types.

**Comment by tiavina-mika** [comment]
I'm using dayjs, too. It will be nice if we can extend z with dayjs, moment or other custom types

**Comment by plehnen** [comment]
#metoo.
I am using it inside `z.preprocess(v => typeof v === 'string' && v.length && dayjs(v), z.instanceof(dayjs.Dayjs))`.

`z.instanceof(dayjs.Dayjs)` is not working. it throws "TypeError: Cannot read properties of undefined (reading 'name') at Object.instanceOfType [as instanceof]"

`z.instanceof(dayjs as any)` is not working. It turns the type to "any".

**Comment by Flo-Slv** [comment]
Hi guys,

I am still wondering how to add dayjs type with zod. Any update to deal with this use case ?

Thanks

**Comment by plehnen** [comment]
I ended up using: 
```
{
  myDayjsProp: z
    .string()
    .transform(v => (v.length && dayjs(v)) || undefined)
    .optional()
}
```

**Comment by Flo-Slv** [comment]
> I ended up using:
> 
> ```
> {
>   myDayjsProp: z
>     .string()
>     .transform(v => (v.length && dayjs(v)) || undefined)
>     .optional()
> }
> ```

Thanks for the workaround !

**Comment by Flo-Slv** [comment]
It will be nice to extend with custom types like moment or dayjs "natively".

Something like this: `z.daysjs()`
