### ISSUE TITLE
Strict function args

### ISSUE THREAD

**Issue by tonyxiao** [colinhacks/zod#1264]
Zod right now always adds `.rest(z.unknown())` to any function initiation and makes it impossible to validate that a function does not get extra parameters it does not intend

![image](https://user-images.githubusercontent.com/696842/179184877-1fed7a4d-7b7d-462b-b644-a7dd1e438924.png)

Is this the desired behavior? One could call `z.ZodFunction.create()` directly but feels a bit strange.

**Comment by colinhacks** [comment]
Fixed in `zod@3.19.0` 👍
