### ISSUE TITLE
Please add TypeScript support for `.extend()` method in the z.Schema type

### ISSUE THREAD

**Issue by ArsenBatyuchok** [colinhacks/zod#1275]
I find it very useful to add my types for Zod schemas, so that if I change the type, TypeScript helps me in highlighting the errors in my broken schemas. But as soon as I assign any schema `z.Schema<MyType>`, I can no longer extend this schema.
Here's a detailed example:
1. Without `z.Schema<MyType>` specification:
```
const mySchema = z.object({ ... });
const anotherSchema = mySchema.extend({ ... });
```
Works just fine, but no highlights if I have my types mismatched with the schema.

2. With `z.Schema<MyType>` specification:
```
const mySchema: z.Schema<MyType> = z.object({ ... });
const anotherSchema = mySchema.extend({ ... });
```
Here, I have my type definitions connected to Zod schemas, but I can no longer safely extend from `mySchema` (by safely, I mean type-safety, if I put @ts-ignore, it works just as expected).

Please suggest a workaround if any exists or add a type support for `extend` method in Schema type definition. Thanks!

**Comment by UNDERCOVERj** [comment]
can't agree more，I asked the question too。https://github.com/colinhacks/zod/issues/1271

**Comment by CoolColdUK** [comment]
You can do this using
`const anotherSchema:z.Schema<MyType> = mySchema.and(z.object({ ... }));`
