### ISSUE TITLE
.strip and .partial not available methods on ZodDiscrimatedUnion schema

### ISSUE THREAD

**Issue by mr-bjerre** [colinhacks/zod#1277]
I have a base generic equal to `z.ZodObject<{ [k: string]: any }>`.

Unfortunately the follwowing schema doesn't satisfy that requirement which seems like an error?

```typescript
export const schema = z
  .object({
    id: z.string().min(1),
  })
  .and(
    z.discriminatedUnion("type", [
      z.object({ type: z.literal("A"), payload: z.object({a: z.string()}) }),
      z.object({ type: z.literal("B"), payload: z.object({b: z.string()}) }),
    ])
  );
```

My base generic needs to be `z.ZodObject<{ [k: string]: any }>` which exposes `.strip` and `.partial` on the schema. A `z.discriminatedUnion` (nor `z.ZodIntersection`) schema does not which seems odd?

Shouldn't the following code be valid?

```typescript
// example 1 discriminated union
z.discriminatedUnion("type", [
      z.object({ type: z.literal("A"), a: z.string() }),
      z.object({ type: z.literal("B"), b: z.string() }),
  ]).partial()  // TS and runtime error

// example 2 intersection
z.object({
    a: z.string(),
  })
  .and(
    z.object({ b: z.string() })
  ).partial()  // TS and runtime error

// example 3 union
z.union([
    z.object({ a: z.string() }),
    z.object({ b: z.string() }),
  ]).partial()  // TS and runtime error
```

**Comment by roblabat** [comment]
Hello @mr-bjerre,

For me your examples shouldn't be valid, this behavior is normal as zod as a union as no partial method (if you have a union between an object and a number for example partial doesn't make any sense). Your examples should be implemented as following:

```ts
// example 2 intersection
z.object({
    a: z.string(),
  }).partial()
  .and(
    z.object({ b: z.string() }).partial()
  )

// example 3 union
z.union([
    z.object({ a: z.string() }).partial(),
    z.object({ b: z.string() }).partial(),
  ])
```

note that your first example can't be implemented as a discriminatedUnion need the discriminator ("type" property in your example) to be mandatory which is not compatible with a partial object.
