### ISSUE TITLE
New Feature - Variadic tuples with noUncheckedIndexedAccess

### ISSUE THREAD

**Issue by nicu-chiciuc** [colinhacks/zod#1278]
Variadic tuples were introduced in Typescript 4.0, and they allow some pretty nifty tricks.
If the [--noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) is enabled, it's possible to differentiate arrays that are guaranteed to have at least one element from simple arrays, like so:

```
type Array1<T> = [T, ...T[]];

const a: Array1<string> = []; // this will show an error
const b: string[] = []; // no error here
```
<img width="363" alt="example" src="https://user-images.githubusercontent.com/4076804/180491063-07e12dee-bcba-4852-a219-a1596c7c7077.png">

and it also correctly types if we want to access some index:

<img width="391" alt="example2" src="https://user-images.githubusercontent.com/4076804/180491067-dc6f336b-2f70-4c44-9133-7fc33b093a0c.png">

I used this approach in a previous project, but had to define manually all the necessary type guards to check if a standard array has at least one element.

https://github.com/nicu-chiciuc/dependent-ts/blob/59f92dc243bfdc53494fd6e3dfd13efbef026829/src/index.ts#L82

I was wondering if this is something that would be of interest to somebody.

**Comment by colinhacks** [comment]
I agree, this is a very useful pattern :) https://github.com/colinhacks/zod#nonempty
