### ISSUE TITLE
How can I compare and validate two fields?

### ISSUE THREAD

**Issue by kazumax75** [colinhacks/zod#1286]
There are two select tags that allow you to select integer values.
Both have the same list of items that can be selected

If the integer value of the item in the first select tag is less than the integer value of the item in the second select tag
If the integer value of the item in the second select tag is less than the integer value of the item in the first select tag, how do I make it a validation error?
How do I do this?

Or
When an item in the first select tag is selected
How do I make it so that the second select tag can only select integers after the first item?

**Comment by GabiGrin** [comment]
@kazumax75 I'm still new to zod, but what about using [refinements](https://github.com/colinhacks/zod#refine)?
Given
```
const data = z.object({value1: z.number(), value2: z.number()}); // value1 and 2 represent select tags respectfully
``
you can use `.refine` to make sure that value 2 is always greater (or equal?)
`data.refine((obj) => obj.value2 > object.value1)`

This will result in a validation error if value2 isn't greater than value1

Note that you may want to use [superRefine](https://github.com/colinhacks/zod#superrefine) for better errors
