### ISSUE TITLE
Add support to report invalid length

### ISSUE THREAD

**Issue by MrAmericanMike** [colinhacks/zod#1293]
So apparently this boils down to zod not supporting something like this. 

https://github.com/trpc/trpc/issues/2328

Would it be possible to add what's needed to get that kind of behavior "In real time"?

Of course on the example I mention the length, but it could apply to any other condition.

Thanks in advance.

**Comment by colinhacks** [comment]
As far as I know, TypeScript template literals cannot represent "string with n+ characters"
