### ISSUE TITLE
Validating a multistep form is behaving differently than with yup

### ISSUE THREAD

**Issue by Micah-S** [colinhacks/zod#1298]
Here's a multistep form using zod: https://codesandbox.io/s/pensive-ives-jzjwb3?file=/src/MultiStepForm.js
This is the same form using yup: https://codesandbox.io/s/unruffled-river-9fkxo?file=/src/MultiStepForm.js

The issue I have with zod is when submitting the form, only the current step's (step 3) data is available in the onSubmit call. Both examples are resolving using `xResolver(currentValidationSchema)` which only points to the validation for the current step, but I'm wondering why yup is returning the entire form while zod doesn't.

**Comment by iambryanhaney** [comment]
Zod's default behavior is to strip unknown keys from objects. You can use `.passthrough()` on your second and third schemas to ensure the keys remain through the final validation output.

https://github.com/colinhacks/zod#passthrough

**Comment by Micah-S** [comment]
Yep that's it, thank you!
