### ISSUE TITLE
Incorrect Input type when using `refine` with a type guard

### ISSUE THREAD

**Issue by mayorandrew** [colinhacks/zod#1308]
When using `refine` with a type guard, the Input type gets changed to `RefinedOutput` type. I do not expect this to be the desired behavior, because this breaks the Input type when used with transforms. See example:

```
import { z } from 'zod';

const schema = z.string().transform(v => 5 as number | undefined /* Imagine some lookup here */);

type input = z.input<typeof schema>;
//   ^ string

type output = z.output<typeof schema>;
//   ^ number | undefined

const refined = schema.refine((v): v is Exclude<typeof v, undefined> => v !== undefined);

type input2 = z.input<typeof refined>;
//   ^ number <-- wrong, should be string

type output2 = z.output<typeof refined>;
//   ^ number
```
[Link to CodeSandbox](https://codesandbox.io/s/zod-refine-type-issue-kg7mlh?file=/src/index.ts)

The potential cause is that the corresponding `refine` type definition returns `ZodEffect` with `RefinedOutput` instead of `Input`.
https://github.com/colinhacks/zod/blob/master/src/types.ts#L272

**Comment by colinhacks** [comment]
Calls to `.refine` can't change the inferred type. TypeScript is letting you do `v is Exclude<typeof v, undefined>` because the expecred return type of your refinement function is `unknown`—if it's falsy the check fails, otherwise it passes. In general, you shouldn't try to mess with type guards in Zod. Your use case is best handled with a transform

```ts
z.string()
    .transform((val) => 5 as number | undefined)
    .transform((val, ctx) => {
      if (!val) {
        ctx.addIssue({ code: z.ZodIssueCode.custom, message: "Not found" });
        return z.INVALID as never;
      }
      return val;
    });
```
