### ISSUE TITLE
How to create zod schema from existing value?

### ISSUE THREAD

**Issue by valerii15298** [colinhacks/zod#1317]
I have a such object:
```ts
const obj = {
  typeName: 'hmmm :)',
  attributes: {
    owner: '',
    country: {
      guid: 'it is a string',
      typeName: 'country',
      uniqueAttributes: {
        iso3_code: 'ddd',
        qualifiedName: 'ccc',
        iso2_code: 'aaa',
      },
    },
    qualifiedName: 'Hello, how are you',
    organization_id: '8113',
    name: 'Lorem',
    description:
      'Lorem ipsum',
  },
  guid: 'eferferferfwefwerfw',
  status: 'ACTIVE',
  displayText: 'regergergrgtergt',
  classificationNames: [],
  meaningNames: [],
  meanings: [],
  isIncomplete: false,
  labels: [],
}
```

Is there a tool to create zod schema type for this object instead of manually doing it?

**Comment by Shumuu** [comment]
There is no "one way" BUT what you could do is use an extension to create a type/interface from this object and use that interface/type with [ts-to-zod](https://github.com/fabien0102/ts-to-zod) to generate a schema

[VSCode Extension](https://marketplace.visualstudio.com/items?itemName=danielDing.jsontotype#:~:text=Open%20a%20json%20file%20in%20VS%20Code%20note%3A,%28%E2%8C%98%2BP%29%2C%20input%20json%20to%20type%2C%20and%20press%20enter.)
