### ISSUE TITLE
[Bug] Type inference does not work as expected when using catchall

### ISSUE THREAD

**Issue by egmacke** [colinhacks/zod#1322]
Using zod's type inference (schema first approach) I get typescript errors when using catchall.

Example:

```typescript
import z from 'zod';

const zschema = z
  .object({
    'main': z.string()
  })
  .catchall(z.number().optional());

const result = zschema.safeParse({
  'main': 'foo',
  'catch': 1
});

type Test = z.infer<typeof zschema>;
const foo: Test = {
  'main': 'foo',
  'a': 1
}
```

This example shows the expected behaviour for `safeParse` (which correctly validates the object), but it results in a typescript error when trying to instantiate an object using the infered type `Test`.

Expected behaviour:

`type Test` should resolve to something like:
```typescript
{
  main: string,
  [x: string]?: number
}
```

However it produces the following error given the example above:
```typescript
const foo: {
    [x: string]: number | undefined;
    main: string;
}
'foo' is declared but its value is never read.ts(6133)
Type '{ main: string; a: number; }' is not assignable to type '{ [x: string]: number | undefined; main: string; }'.
  Property ''main'' is incompatible with index signature.
    Type 'string' is not assignable to type 'number'.ts(2322)
```

**Comment by colinhacks** [comment]
Yeah, it turns out the `[x: string]: <type>` construct in TypeScript doens't actually act as a "catchall". All defined keys must also conform to that type. For some reason TypeScript lets Zod construct a type that can't actually be defined manually: 

```ts
type Something = {
  main: string;
  [x: string]: number;
}
// Property 'main' of type 'string' is not assignable to 'string' index type 'number'.
```

It's pretty weird, and you'll get errors if you every try to use that type. Basically it shouldn't be allowed to exist and you probably shouldn't use catchall unless the catchall schema generalizes all the defined keys.

**Comment by flaviut** [comment]
That's interesting--thank you for the explanation (and excellent project). I ran into this too, and wanted to include the error that I to make it a bit easier to search for:

```
Object literal may only specify known properties, and 'path' does not exist in type '{ name?: string | undefined; classes?: string[] | undefined; type: string; }'.
```
