### ISSUE TITLE
`.keyof()` relies on key order, resulting in unsound `.options` tuple type

### ISSUE THREAD

**Issue by betafcc** [colinhacks/zod#1325]
Saw this [awesome trick](https://github.com/colinhacks/zod/pull/1216/files#diff-44137e14e4c38858d2925367bcf2455388e24146f88934724da11d2f9ecaa7d2) by @ecyrbe transforming object keys into string tuple ordered by source declaration, but beware [TS treats key order differently than JS engines](https://2ality.com/2015/10/property-traversal-order-es6.html#traversing-the-own-keys-of-an-object):

```ts
z.object({ a: z.string(), '1': z.string() }).keyof().options()
// TS says it's ['a', '1']
// JS runtime it's ['1', 'a']
```

I believe `.options` is public API for enums, therefore this typing is unsound.
A simple solution that comes to mind is having an `UnorderedZodEnum` like

```ts
type UnorderedZodEnum<T extends [string, ...string[]]> = Omit<z.ZodEnum<T>, 'options'> & { options: Set<T> }
```

Or just downgrade the keyof to return `ZodSet` instead of `ZodEnum`.

A * mostly * non breaking change could be something like:

```ts
type UnorderedZodEnum<T> = Omit<ZodEnum<T>, 'options'> & { options: Repeat<typeof T[number], T['length']> }

type Repeat<N extends number, T, Acc extends T[] = []> = N extends Acc['length']
  ? Acc
  : Repeat<N, T, [T, ...Acc]>
```

Will still be breaking change in use-cases relying on contravariance or assignability, but those are exactly the cases that would be unsound in current version, eg:

```ts
const Enum = z.object({ a: z.string(), b: z.string() }).keyof()

// user relying on ordering of current API
const first: 'a' = Enum.options[0]
// Type '"a" | "b"' is not assignable to type '"a"'.

// needs to be cast instead
const first = Enum.options[0] as 'a'
```

A more non-breaking solution would be to try mimicking JS engines, beware of typescript `keyof` though, it seems to sometimes result in desired order (i really didn't get the rule on that), but only with object literals, not when the object comes from a generic param. Seems the safer would be to force the engine ordering with something like:

```ts
type ObjectKeys<T> = [
  ...Sort<enumUtil.UnionToTupleString<IntString<keyof T>>>, 
  ...enumUtil.UnionToTupleString<Exclude<keyof T, IntString<keyof T>>>
]
```

But to implement a 'Sort' for that would need some more possibly unsound tricks

**Comment by betafcc** [comment]
Managed to do an implementation of the last approach for reference

```ts
type ObjectKeys<T> = [
  ...Sort<enumUtil.UnionToTupleString<IntString<keyof T>>>,
  ...enumUtil.UnionToTupleString<Exclude<keyof T, IntString<keyof T>>>,
]

type Head<T> = T extends [infer H, ...any[]] ? H : T extends `${infer H}${string}` ? H : never
type Tail<T> = T extends [any, ...infer Rest] ? Rest : T extends `${string}${infer Rest}` ? Rest : never
type Take<N extends number, T extends any[], Acc extends any[] = []> = N extends Acc['length']
  ? Acc
  : T extends [infer Head, ...infer Rest]
  ? Take<N, Rest, [...Acc, Head]>
  : never

type Digits = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

type IntString<T> = T extends '0'
  ? T
  : T extends `${Exclude<Digits[number], 0>}${infer Rest}`
  ? `${Head<T>}${DigitString<Rest>}`
  : never

type DigitString<T> = T extends `${Digits[number]}${infer Rest}` ? `${Head<T>}${DigitString<Rest>}` : T

type Sort<T extends Array<any>, Acc extends Array<any> = []> = T extends []
  ? Acc
  : Insert<Head<T>, Acc> extends infer G
  ? Sort<Tail<T>, G extends Array<any> ? G : never>
  : never

type Insert<N, Acc extends Array<any>> = Acc extends []
  ? [N]
  : Compare<N, Head<Acc>> extends 'lt' | 'eq'
  ? [N, ...Acc]
  : Insert<N, Tail<Acc>> extends infer G
  ? [Head<Acc>, ...(G extends Array<any> ? G : never)]
  : never

type Compare<A, B> = CompareLength<A, B> extends 'eq'
  ? Head<A> extends Head<B>
    ? Compare<Tail<A>, Tail<B>>
    : CharToInt<Head<A>> extends Take<CharToInt<Head<B>>, Digits>[number]
    ? 'lt'
    : 'gt'
  : CompareLength<A, B>

type CharToInt<C> = Extract<{ [N in Digits[number]]: [N, `${N}`] }[Digits[number]], [any, C]>[0]

type CompareLength<A, B> = [A, B] extends ['', '']
  ? 'eq'
  : [A, B] extends [`${infer _}${string}`, '']
  ? 'gt'
  : [A, B] extends ['', `${infer _}${string}`]
  ? 'lt'
  : CompareLength<Tail<A>, Tail<B>>

```

So changing https://github.com/colinhacks/zod/blob/59768246aa57133184b2cf3f7c2a1ba5c3ab08c3/src/types.ts#L1944
to
```ts
  keyof(): ZodEnum<ObjectKeys<T>> {
```

Would probably work, but damn, guess the Set<T> one makes more sense

**Comment by ecyrbe** [comment]
No `keyof` is designed to feed zod enum schemas, that is why originaly i named it `.enum()` to conveys the use case. Using a set will defeat the purpose of it.  
  
Plus like the name suggest, it's used to represent enums not tuples. Enum have no order , your code should not rely on enum order, JavaScript and typescript gives no guaranty on object Key order, no point trying to develop workerounds to satisfy V8 algorithm when order can be completely different depending on the JavaScript engine. Typescript being unsound is completely expected and can't be evoided since typescript !==runtime JavaScript engine

**Comment by ecyrbe** [comment]
To clarify, even `options()` is expected to be unsound since you can't have guaranties on enum order

**Comment by ecyrbe** [comment]
I think Collin naming it `keyof` was a mistake, because it's not the keys(tuple) we are returning it's an enum.
@colinhacks if you want to comment.

**Comment by ecyrbe** [comment]
M'y proposition would then be to rename it into `.enum()` and add précision in the documentation about it's use case and it being unsound being expected

**Comment by betafcc** [comment]
@ecyrbe 
> `options()` is expected to be unsound
That already satisfies it for me, indeed I suspected it was the case that enum is unordered, just was surprised by the ordered tuple signature it has

Also I agree that `.enum` would be better naming in this feature as well, `.keyof` result doesn't reflect neither JS `Object.keys` nor TS `keyof` very well
