### ISSUE TITLE
z.string().url() validates url without a top-level domain.

### ISSUE THREAD

**Issue by koutselakismanos** [colinhacks/zod#1327]
z.string.url() validates "https://google"

**Comment by ajhenry** [comment]
URLs without TLDs are still URLs via [the spec](https://url.spec.whatwg.org/#example-url-components)

For example: `http://localhost`

If you don't want to allow urls without TLD, you'll need to use regex like this:
```ts
const urlValidator = /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)/
z.string().regex(urlValidator)
```

**Comment by ITwrx** [comment]
Thanks for the workaround, but maybe a `tld()` would be good to have. I'm guessing it's probably needed more often than the current `url()` implementation is, as well.

**Comment by schmoli** [comment]
FYI z.string.url() is current validating garbage like `foo:` (but interestingly enough not `http:`

**Comment by colinhacks** [comment]
We're using the built-in `URL` constructor to validate URLs. It's the closest thing to a standard available in JS. Anyone with other requirements can use their own regex easily.
