### ISSUE TITLE
Can not merge a record type into an object type

### ISSUE THREAD

**Issue by legends-killer** [colinhacks/zod#1333]
Hi 👋 
I want to rebuild the following types from ts type to zod type:
```typescript
type myType = {
  "204": never
  [t: string]: Record<string, {
    foo: string,
    bar: number
  }>,
} 
```
When I write the zod types like this, it shows me an error that `Argument of type 'ZodRecord<ZodString, ZodRecord<ZodString, ZodObject<{ foo: ZodString; bar: ZodNumber; }, "strip", ZodTypeAny, { foo: string; bar: number; }, { foo: string; bar: number; }>>>' is not assignable to parameter of type 'AnyZodObject'.`:
```typescript
const myTypeZod = z.object({
  '204': z.never(),
}).merge(
  z.record(
    z.record(
      z.object({
        foo: z.string(),
        bar: z.number(),
      }),
    ),
  ),
)
```
How can I merge a record type with `key: string` into an object type?

**Comment by colinhacks** [comment]
This is a job for `.catchall`

```ts
const myTypeZod = z
    .object({
      "204": z.never(),
    })
    .catchall(
      z.record(
        z.object({
          foo: z.string(),
          bar: z.number(),
        })
      )
    );
```

**Comment by jilv220** [comment]
Same. I cannot validate the keys (start with #) if using catchAll..

**Comment by pano9000** [comment]
I had a similar issue but the following StackOverflow solution was able to help:
https://stackoverflow.com/a/75546692

In short: They suggest using `z.intersection()` and it seems to be working, e.g. in my case:
```
const SchemaNavODataResponseValue = z.record(z.string(), z.union([z.string(), z.boolean() ]));

const SchemaNavODataResponseBodyBase = z.object({
  "odata.metadata": z.string()
});

const SchemaNavODataResponseBodySingle = z.intersection(SchemaNavODataResponseBodyBase, SchemaNavODataResponseValue)

type NavODataResponseBodySingle = z.infer<typeof SchemaNavODataResponseBodySingle>;
```

Just in case someone stumbles across this via google -> the github issue comes up first, but that stackoverflow link was a bit hidden (at least for me)
