### ISSUE TITLE
Support passthrough on z.record

### ISSUE THREAD

**Issue by 6XGate** [colinhacks/zod#1340]
Although zod support `passthrough` automatically on `z.instanceof`, and with explicit use of of the `passthrough` method on `z.object`; there seems to be no way to replicate this functionality with `z.record`. When writing a class decorator for Vue, I ran info this problem where parsing the existing property options for correctness resulted in a different object that the one on the component options. This prevented attaching new property options correctly.

**Comment by scotttrinh** [comment]
Can you give a quick example of what you're noticing here? Are you using a key schema? Do you need to leave the object untouched but assert that the input object has a certain shape?

**Comment by 6XGate** [comment]
Misunderstanding on how passthrouugh worked. Would be great if there is a method to bypass any transformation in `z.object` and `z.record`
