### ISSUE TITLE
Unparse/serialize

### ISSUE THREAD

**Issue by mwisnicki** [colinhacks/zod#1341]
It would be nice to use zod schemas to serialize data, effectively doing the inverse of parse method.

All transforms would have to be reversed and optionally fields with default values should be omitted.

One potential problem is that transforms are not bidirectional so that would have to be added first.

**Comment by colinhacks** [comment]
> One potential problem is that transforms are not bidirectional so that would have to be added first

Indeed, this is why Zod doesn't do this and why it probably never will. Limiting transforms to exclusively invertible operations is very not worth it imo. 

It's possible this will eventually be added as a new schema type: `z.codec(A, B, (arg: A)=>B, (arg: B)=>A)`. If you have thoughts on the API for that, I'm all ears.
