### ISSUE TITLE
Recursive type does not have same types after transforms

### ISSUE THREAD

**Issue by JoaoCnh** [colinhacks/zod#1353]
I must be doing something wrong or I'm thinking of a solution in a wrong way.

I have this schema and type

```ts
function transformInvalidArrayValues<T>(
  value: (string | T)[],
): T[] {
  return value.filter((val): val is T => !!val && isReferenced(val));
}

function isReferenced<T>(ref: string | T): ref is T {
  return typeof ref !== 'string';
}

const CountryTargetableSchema = z.object({
  countries: z
    .array(z.union([z.string(), CountrySchema]))
    .transform(transformInvalidArrayValues),
});

type CountryTargetable = z.infer<
  typeof CountryTargetableSchema
>;
```

The CountryTargetable type is, as expected, now an array of valid objects that respect the CountrySchema (not relevant since it's just other fields).

But now, I need to define a recursive type that extends this structure.

```ts
interface Node extends CountryTargetable {
  testing: string;
}

export const NodeSchema: z.ZodType<Node> = z.lazy(() =>
  CountryTargetableSchema.extend({
    testing: z.string()
  })
);
```

but this is giving a Type error:

```
The types of '_input.countries' are incompatible between these types.
Type '(string | { uid: string; title: string; locale: string; country_code: string; })[]' is not assignable to type '{ uid: string; title: string; locale: string; country_code: string; }[]'
```

seemingly ignoring the transforms that were performed by the schema.

I have a feeling I might be doing something wrong or thinking about things wrong or confusing something.

Does anyone have any idea what might be the issue here?

**Comment by colinhacks** [comment]
Zod infers both an input and output type — you can see this in the generic definition of ZodType:

```ts
export abstract class ZodType<
  Output = any,
  Def extends ZodTypeDef = ZodTypeDef,
  Input = Output
> { ... }
```

As you can see the default value of `Input` is `Output` unless otherwise specified. Because you didn't include a third argument for `ZodType`, you are implicitly telling Zod that the input and output should be the same. This will work in the meantime:

```ts
export const NodeSchema: z.ZodType<Node, any, any> = ...
```
