### ISSUE TITLE
Is there a way to serialize and restore a simple schema?

### ISSUE THREAD

**Issue by ha-sash** [colinhacks/zod#1354]
Hello! I wanted to try using one schema for parsing incoming data on the server and validating form fields. But at the same time, I would like to leave the schema description on the server side and not take this code into a separate package for reuse on the client.

**Comment by jonnytest1** [comment]
didnt find a way out of the box but i tihnk you can write a small serializer/deserializer with schema._def.shape()

**Comment by colinhacks** [comment]
Not currently. This problem is far better solved by using monorepo tools or frameworks that let you share code between the server and client.

**Comment by ha-sash** [comment]
Thanks a lot, I did just that, but а man can dream thought. )
