### ISSUE TITLE
pass context to default function 

### ISSUE THREAD

**Issue by jonnytest1** [colinhacks/zod#1366]
a schema like

```
z.object({
   somearg: z.someschema()
   otherarg:z.schema().default((context)=>({
        arg: context.parent.data.somearg.somneprop
   }))
})
```

would be a nice addition 
(depending on how its parsed i can see that this might be somewhat interesting if the field order is changed but i think thats something the developer should keep in mind - long term it might be a good idea to do all the other validating first before invoking the defaults 🤔)

**Comment by colinhacks** [comment]
This breaks compostionality and probably isn't possible to implement in a typesafe way. I'd implement this with a `.transform` on the top-level object.
