### ISSUE TITLE
Strip unknown types in a discriminated union when parsing

### ISSUE THREAD

**Issue by bundabrg** [colinhacks/zod#1367]
## Summary
Is it possible for a discriminated union to optionally ignore unknown values when parsing?

## Detail
Let say I have the following models:

```ts
export const BaseProviderResponseModel = z.object({
    type: z.string(),
    name: z.string(),
});

export const LocalProviderResponseModel = BaseProviderResponseModel.extend({
    type: z.literal("local"),
});

export const OAuthProviderResponseModel = BaseProviderResponseModel.extend({
    type: z.literal("oauth"),
    url: z.string().url(),
});

export const ProviderResponseModel = z.discriminatedUnion("type", [
    LocalProviderResponseModel,
    OAuthProviderResponseModel,
]);
```

When parsing a response using `ProviderResponseModel` I'm expecting to receive either a `type="local"` or `type="oauth"` and this works fine.

At some point in the future the data I parse may present other types I do not yet know about but I would like for them to just be stripped rather than throwing an error about an unknown discriminator value.

Am I missing an obvious way to do this?

**Comment by colinhacks** [comment]
> Am I missing an obvious way to do this?

Not that I know of. You could always do something like this I suppose:

```ts
z.any().array().transform(val => {
  return val.filter(item => ProviderResponseModel.safeParse(val).success)
});
```

I don't think Zod will support a "strip" mode in discriminated unions in the near future either - seems a bit niche to me. There's no equivalent of that in regular unions either.

**Comment by bundabrg** [comment]
Thanks for this. It worked well. For anyone in the future coming across this there is a typo above and should read:

```js
z.any().array().transform(val => {
  return val.filter(item => ProviderResponseModel.safeParse(item).success)
});
```

I use it in a schema something as follows:

```js


const ServerResponseModel = z.object({
   otherdata: z.string(),
   moredata: z.string(),
    providers: z
        .any()
        .array()
        .transform((val) => {
            return val.filter((item) => {
                return ProviderResponseModel.safeParse(item).success;
            });
        }),
});

```
