### ISSUE TITLE
Property 'brand' is missing in type ZodObject<{...}>

### ISSUE THREAD

**Issue by Brandon-Perry** [colinhacks/zod#1369]
Any idea as to what the problem might be? Example below. 
Zod 3.17.10
React 18.2.0
React-Native: 0.66.1

Property 'brand' is missing in type 'ZodEnum<["Adventurous", "Affectionate", "Calm", "Carefree", "Caring", "Cautious", "Cooperative", "Curious", "Disciplined", "Easy-Going", "Energetic", "Free-flowing", "Intense", ... 16 more ..., "Trusting"]>' but required in type 'ZodEnum<[string, ...string[]]>'.

**Comment by colinhacks** [comment]
Gonna need to see some actual code

**Comment by maxLabrys** [comment]
I just encountered this issue and it was because I had 2 different version of Zod installed. Thanks!
