### ISSUE TITLE
Why do I get custom error messages "sometimes"?

### ISSUE THREAD

**Issue by leafyshark** [colinhacks/zod#1371]
As you can see in the comparison below. The only difference being that the "Required" message is triggered when the error occurs, whereas the more verbose (custom) error message appears randomly, typically when I am working on the code.

<img width="855" alt="Screenshot 2022-09-01 at 23 10 51" src="https://user-images.githubusercontent.com/27443324/188021787-1728a285-652b-4f17-b777-3eedc1b08540.png">

<img width="839" alt="Screenshot 2022-09-01 at 23 10 34" src="https://user-images.githubusercontent.com/27443324/188021792-a292d0b7-680d-413f-b58b-0e59a84e331a.png">

It would be great if someone could help me figure out why this is happening? The code is fairly straightforward:

```
  mainImages: z
    .array(z.string())
    .min(1, { message: 'Please upload at least one image' }),
```

**Comment by lucas-certn** [comment]
I (may?) be having a similar issue - I'm using `errorMap` and it seems to be completely ignored when I use `refine`.

Works:

```ts
export const Limit = () =>
  QueryNumber({
    errorMap: () => ({ message: `Limit must be in range [${LIMIT_MIN}, ${LIMIT_MAX}]` }),
  })
    // .refine((limit) => limit >= LIMIT_MIN && limit <= LIMIT_MAX)
    .optional()
    .default(LIMIT_DEFAULT.toString());
```

doesn't

```ts
export const Limit = () =>
  QueryNumber({
    errorMap: () => ({ message: `Limit must be in range [${LIMIT_MIN}, ${LIMIT_MAX}]` }),
  })
    .refine((limit) => limit >= LIMIT_MIN && limit <= LIMIT_MAX)
    .optional()
    .default(LIMIT_DEFAULT.toString());
```

**Comment by colinhacks** [comment]
That initial `Required` error is probably happening because `undefined` is being passed into `mainImages` initially. Later (after some user interaction) an empty array is passed. 

```ts
  const schema = z
    .array(z.string())
    .min(1, { message: "Please upload at least one image" });

  schema.parse(undefined);
  /* ZodError: [
    {
      "code": "invalid_type",
      "expected": "array",
      "received": "undefined",
      "path": [],
      "message": "Required"
    }
  ]  */


  schema.parse([]);
  /* ZodError: [
    {
      code: 'too_small',
      minimum: 1,
      type: 'array',
      inclusive: true,
      message: 'Please upload at least one image',
      path: []
    }
  ] */
```

You can fix this be separately specifying a `required_error` message on the array schema.

```ts
const schema = z
  .array(z.string(), { required_error: "Please upload at least one image" })
  .min(1, { message: "Please upload at least one image" });
```
