### ISSUE TITLE
Type inference problem with extending generic ZodObject

### ISSUE THREAD

**Issue by mikitane** [colinhacks/zod#1374]
First of all, thanks for the great library! 🙏

I have a small problem with inferencing the type of a generic ZodObject's shape.

#### Problem description

I have a CMS API that sends localizations of different entities in a certain format. Simplified example of an article entity:
```json
{
  "title": "English title",
  "locale": "en",
  "localizations": [
    {
      "title": "French title",
      "locale": "fr"
    }
  ] 
}
```

This is the Zod-schema used for the articles:

```typescript
const Article = z.object({
  title: z.string(),
  locale: z.string(),
})
```

I wanted to make a helper function which takes a ZodObject as an input and extends it with localizations field:

```typescript
const withLocalizations = <T extends z.ZodObject<any>>(zodObject: T) => zodObject.extend({
  localizations: zodObject.array()
})
```

Then I would use it like so:

```typescript
const ArticleWithLocalizations = withLocalizations(Article)
```

Unfortunately, with this setup the TS compiler loses track of the original fields and thinks that `ArticleWithLocalizations` has only `localizations` field. Supposedly that's because of the any-type used in `withLocalizations`.

#### Partial solution

I found a solution by passing the shape to `withLocalizations` but I think this is quite verbose:

```typescript
const withLocalizations = <S extends z.ZodRawShape, T extends z.ZodObject<S>>(zodObject: T) => zodObject.extend({
  localizations: zodObject.array()
})

const Article = z.object({
  title: z.string(),
  locale: z.string(),
})

type ArticleType = typeof Article

const ArticleWithLocalizations = withLocalizations<ArticleType["shape"], ArticleType>(Article)
```

#### Question
Is there a way to infer the type of the shape inside `withLocalizations` without passing it explicitly?

**Comment by mikitane** [comment]
Just as an addition, this doesn't work either:
```typescript
const withLocalizations = <T extends z.ZodObject<T["shape"]>>(zodObject: T) => zodObject.extend({
  localizations: zodObject.array()
})
```

Just getting error: `Type 'T["shape"]' does not satisfy the constraint 'ZodRawShape'.`

I'm not that familiar with TypeScript to know if you can even reference a type variable like that.

**Comment by colinhacks** [comment]
Here's a version I got working:

```ts
const withLocalizations = <
    T extends z.ZodObject<ZodRawShape, any, any, any, any>
  >(
    zodObject: T
  ) =>
    z.object({
      localizations: z.array(zodObject),
      ...(zodObject.shape as T["shape"]),
    });
```

The rule of thumb is don't attempt to call any methods on the generic input - TypeScript isn't able to handle that.
