### ISSUE TITLE
Unable to do .partial and getting "TypeError: Cannot read properties of undefined (reading 'partial')"

### ISSUE THREAD

**Issue by srahimeen** [colinhacks/zod#1375]
I'm using zod in my NextJS project, and when trying to a .partial on a schema I get the a "TypeError: Cannot read properties of undefined (reading 'partial')"

Here is my setup.

Models.tsx

```
const TripSchema = z.object({
    id: z.string(),
    user_id: z.string(),
    name: z.string(),
})

type Trip = z.infer<typeof TripSchema>

export type { Trip, TripSchema }
```

I'm trying to validate the shape of form input (in a modal) as follows:

AddTripModal.tsx

```
import { useState } from 'react'
import { Button, Modal } from 'react-daisyui'
import { TripSchema } from './Models'

type ModalProps = {
    open: boolean
    onClose: () => void
}

const AddTripModal = (props: ModalProps) => {
    const [trip, setTrip] = useState({
        user_id: '',
        name: '',
    })

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target
        setTrip((prev) => {
            console.log(prev)
            return { ...prev, [name]: value }
        })
    }

    const handleSubmit = (e: React.ChangeEvent) => {
    
        e.preventDefault()

        console.log(trip)

        const optionalId = TripSchema.partial({
            id: true,
        })

        if (optionalId.safeParse(trip).success) {
            console.log('zod success')
        }
    }

    return (
        // jsx for form
    )
}

export default AddTripModal
```

In VSCode, it seems like eslint does not like my using TripSchema but does not give me any reason why:

![image](https://user-images.githubusercontent.com/9031145/188253770-7359172d-08a9-41ca-8c4d-8a58fb411a7a.png)

And when I visit the page and tap submit on my form, it does have an object with data from the form fields:

![image](https://user-images.githubusercontent.com/9031145/188253807-5e9a4f12-7350-4ea3-889a-0e998ac6ba9f.png)

But I get this error:

![image](https://user-images.githubusercontent.com/9031145/188253872-0f2c44c3-fb4f-4d28-aa9f-c412d897f4eb.png)

Any idea how to resolve this?

**Comment by colinhacks** [comment]
You are only exporting the `type` of your schema, not the schema itself.

```
export type { Trip, TripSchema }
```

So when you try to import the schema later and call a method on it, you're seeing this error. I'm surprised VSCode isn't showing you an more informative error. Try this intead

```
export { type Trip, TripSchema }
```

**Comment by srahimeen** [comment]
That was the issue. Thanks @colinhacks !
