### ISSUE TITLE
Schema with a `transform` results in an invalid intersection

### ISSUE THREAD

**Issue by danni** [colinhacks/zod#1378]
Given a schema like:

```ts
const workflowSchema = z.object({
      sequence: z.number(),
      state: z.nativeEnum(WorkflowState),
      in_bundle: z.boolean(),
      timestamp: z.string().transform(value => DateTime.fromISO(value)),  // Luxon Datetime
})
```

which is intersected with another schema to parse an object, e.g.:

```ts
const apiSchema = z.intersection(featureSchema, workflowSchema)
```

This is not built via `extends` because `featureSchema` is defined to be used directly from files as well as via the API.

Since upgrading Zod (from 3.2 to 3.18) this results in an invalid intersection. From the debugger I've shown that `timestamp` fails in `mergeValues`.

My workaround is to transform after merge, e.g.

```ts
const apiSchema = z.intersection(featureSchema, workflowSchemaNoTransform)
    .transform(value => ({ ...value, timestamp: DateTime.fromISO(value) }))
```

I don't know if there's a "fix" here. I get why it's failing. It would be good to get a more useful error message, rather than having to poke around in the debugger to realise why it fails.

**Comment by colinhacks** [comment]
Can you share a minimal reproduction?

**Comment by danni** [comment]
I do get `invalid_intersection_types`, but I don't get the key that's causing the failure. It's worth noting that `apiSchema` was then packed into a `z.array` to receive a list of objects from the API. I'll see if I can reproduce it in a minimal case.

**Comment by danni** [comment]
Okay here's a minimal case.

It would be nice if the `ZodError` had a `path` that pointed you to the broken field.

```ts
import * as z from "zod";
import { DateTime } from "luxon";

const featureSchema = z.object({
  type: z.literal("Feature"),
  timestamp: z.string()
});

const workflowSchema = z.object({
  timestamp: z.string().transform((value) => DateTime.fromISO(value))
});

const mergedSchema = z.intersection(featureSchema, workflowSchema);

console.log(
  mergedSchema.parse({
    type: "Feature",
    timestamp: DateTime.now().toISO()
  })
);

// Fails with
// ZodError: [
//  {
//    "code": "invalid_intersection_types",
//    "path": [],
//    "message": "Intersection results could not be merged"
//  }
// ]
```

[Sandbox](https://codesandbox.io/s/sweet-kapitsa-g39typ?file=/src/index.ts)

**Comment by grumpygreenguy** [comment]
Bump. Ran into this in our code recently; worked around it by dropping the shared fields and using `.extend` for good measure. The error was the same as in the example; no information as to why `mergeValues` failed --- which makes sense since `mergeValues` just returns `{ valid: false }` when it fails and it's only `ZodIntersection._parse` that adds the issue to the context :thinking:
