### ISSUE TITLE
Check if object has keys

### ISSUE THREAD

**Issue by lordrepha** [colinhacks/zod#1381]
```
z.object({}).resign( ( val ) => {
 return Object.keys(val) === 0 ? false : return
} )
```
It doesn't work.

**Comment by colinhacks** [comment]
This isn't particularly close to being valid Zod usage (or JS syntax). You might consider spending a bit more time looking over the basics before opening more issues. 

```ts
z.object({}).refine(( val ) => {
 return Object.keys(val).length === 0 ? false : true
})
```
