### ISSUE TITLE
Allow optional() typings to work also for non-optional but possibily undefined fields

### ISSUE THREAD

**Issue by GabriFila** [colinhacks/zod#1388]
Hello everyone, Zod is awesome!

While working with Zod I ended up in a particular situation, I didn't find any other reference to this problem except [this StackOverflow question](https://stackoverflow.com/questions/71477015/specify-a-zod-schema-with-a-non-optional-but-possibly-undefined-field) with no useful answer.

I prepared a [Code Sandbox](https://codesandbox.io/s/admiring-sara-7k0f70?file=/src/index.ts:0-575) to show the issue.

```ts
interface IFoo1 {
  somefield: string | undefined;
}

const schema1a: ZodSchema<IFoo1> = z.object({
  somefield: z.string().optional()
});

const schema1b: ZodSchema<IFoo1> = z.object({
  somefield: z.union([z.string(), z.undefined()])
});
```
When I declare a Typescript interface (`IFoo1`) with a required field, which can be both of a certain type and `undefined` I would expect that Zod would be fine with declaring that field as `optional()`. That didn't work, also using a `union()` type didn't work.

Do you have any idea how to solve it? IMHO I would allow `optional()` to accept a type that is required but could be `undefined` since from JS perspective they should be the same, but I'd like to hear more from you!

Thank you!

**Comment by d3jv** [comment]
Any updates on this?
