### ISSUE TITLE
Branded object types loose `z.ZodObject` functionalities

### ISSUE THREAD

**Issue by lukemorales** [colinhacks/zod#1392]
When branding an object all the `z.ZodObject` functionalities are lost, is that the expected behavior or is there something that can be fixed in the types when using `z.brand()`?

This happens on the latest version `3.19.0`.

Here's a minimal reproduction:
```ts
export const UserSchema = z.object({
  id: z.string(),
  name: z.string(),
  age: z.number().int().positive().min(18).max(99),
  email: z.string().email(),
}).brand<'User'>();

const age = UserSchema.shape.age.parse(28) // Cannot read properties of undefined (reading 'age')

export const UserDomain = UserSchema.strict() // UserSchema.strict() is not a function
  .merge( // UserSchema.merge() is not a function
    z.strictObject({
      id: UserId,
    })
  );
```

**Comment by EvanVujcec** [comment]
A workaround is using `.unwrap()` when trying to call `ZodObject` functions. Not sure if this is expected behavior and if it is it needs to be documented. Without looking to deeply at the source it's probably a typescript limitation.

**Comment by EvanVujcec** [comment]
Now that I think about it more, it does make sense that a branded object would not have `ZodObject` functions. Those functions are all mutations on the object which inherently breaks the idea of a branded object which is meant to be immutable. That's why `.unwrap()` exists. Remove the brand and make the object mutable.

**Comment by lukemorales** [comment]
> Those functions are all mutations on the object which inherently breaks the idea of a branded object which is meant to be immutable.

Not all of them are mutations necessarily, my reproduction contains one case where I'm not mutating the object: `UserSchema.shape.age.parse(28)`. A branded object still has keys, still has a shape, it might be interesting to have access to those methods in order to iterate, or access a specific property to use its parsing rules
