### ISSUE TITLE
Zod wiht useFieldArray from react-hook-form

### ISSUE THREAD

**Issue by yyykkkyyy** [colinhacks/zod#1396]
Hi, I'm very newbie.

I would like to use zod validation and useFieldArray from react-hook-form.

```
const schema = z.object({
  items: z.object(
    {
       name: z.string().min(1, 'Required'),
       startAt: z.date(),
       endAt: z.date(),
    },
  ).array(),
).sueprRefine((val, ctx) => {
  ctx.addIssue({
    code: z.ZodIssueCode.custom,
    message: 'TEST ERROR MSG',
    path: ['items', 0, 'name']
  });
);
```
I made above validation schema.
When I got some validation error, how can I set the error message to the form using useFieldArray() ?
My form fields use MUI Controller.

**Comment by bryantobing12** [comment]
what do you trying to achieve?
