### ISSUE TITLE
Strange Error with AngularV9 and Ionic

### ISSUE THREAD

**Issue by fr3shn3ss** [colinhacks/zod#1397]
I get the following errors with zod@3.17.3 and the latest Zod release when compiling a Ionic project which uses AngularV9. downgrading to zod@1.11 fixes it

`[ng] ERROR in node_modules/zod/lib/helpers/enumUtil.d.ts:4:10 - error TS2456: Type alias 'UnionToTuple' circularly references itself.
[ng] 4     type UnionToTuple<T, Tuple extends unknown[] = []> = [T] extends [never] ? Tuple : UnionToTuple<Exclude<T, GetUnionLast<T>>, [GetUnionLast<T>, ...Tuple]>;
[ng]            ~~~~~~~~~~~~
[ng] node_modules/zod/lib/helpers/enumUtil.d.ts:4:88 - error TS2315: Type 'UnionToTuple' is not generic.
[ng] 4     type UnionToTuple<T, Tuple extends unknown[] = []> = [T] extends [never] ? Tuple : UnionToTuple<Exclude<T, GetUnionLast<T>>, [GetUnionLast<T>, ...Tuple]>;
[ng]                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/zod/lib/helpers/enumUtil.d.ts:4:148 - error TS2574: A rest element type must be an array type.
[ng] 4     type UnionToTuple<T, Tuple extends unknown[] = []> = [T] extends [never] ? Tuple : UnionToTuple<Exclude<T, GetUnionLast<T>>, [GetUnionLast<T>, ...Tuple]>;
[ng]
        ~~~~~~~~
[ng] node_modules/zod/lib/helpers/enumUtil.d.ts:6:59 - error TS2315: Type 'UnionToTuple' is not generic.
[ng] 6     export type UnionToTupleString<T> = CastToStringTuple<UnionToTuple<T>>;
[ng]                                                             ~~~~~~~~~~~~~~~
[ng] node_modules/zod/lib/helpers/partialUtil.d.ts:4:29 - error TS2589: Type instantiation is excessively deep and possibly infinite.
[ng] 4         [k in keyof Shape]: ZodOptional<DeepPartial<Shape[k]>>;
[ng]                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/zod/lib/types.d.ts:354:14 - error TS2456: Type alias 'deoptional' circularly references itself.
[ng] 354 declare type deoptional<T extends ZodTypeAny> = T extends ZodOptional<infer U> ? deoptional<U> : T;
[ng]                  ~~~~~~~~~~
[ng] node_modules/zod/lib/types.d.ts:354:82 - error TS2315: Type 'deoptional' is not generic.
[ng] 354 declare type deoptional<T extends ZodTypeAny> = T extends ZodOptional<infer U> ? deoptional<U> : T;
[ng]                                                                                      ~~~~~~~~~~~~~
[ng] node_modules/zod/lib/types.d.ts:400:25 - error TS2315: Type 'deoptional' is not generic.
[ng] 400         [k in keyof T]: deoptional<T[k]>;
[ng]                             ~~~~~~~~~~~~~~~~
[ng] node_modules/zod/lib/types.d.ts:463:145 - error TS1256: A rest element must be last in a tuple type.
[ng] 463 export declare type OutputTypeOfTupleWithRest<T extends ZodTupleItems | [], Rest extends ZodTypeAny | null = null> = Rest extends ZodTypeAny ? [...OutputTypeOfTuple<T>, ...Rest["_output"][]] : OutputTypeOfTuple<T>;
[ng]
       ~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/zod/lib/types.d.ts:467:144 - error TS1256: A rest element must be last in a tuple type.
[ng] 467 export declare type InputTypeOfTupleWithRest<T extends ZodTupleItems | [], Rest extends ZodTypeAny | null = null> = Rest extends ZodTypeAny ? [...InputTypeOfTuple<T>, ...Rest["_input"][]] : InputTypeOfTuple<T>;
[ng]
      ~~~~~~~~~~~~~~~~~~~~~~`

**Comment by timdeschryver** [comment]
There's a TypeScript miss match between both libraries.
Zod uses TypeScript v4.1 which includes features that are not available for Angular 9 (using TypeScript v3.7).
