### ISSUE TITLE
[Request] Support for nested pick masks

### ISSUE THREAD

**Issue by zharinov** [colinhacks/zod#140]
First of all, thank you @vriad for your passion for addressing code/API quality problems.

Speaking of subject, let's say we have complex nested schema. For particular function we want to select the only fields we care about:

```typescript
const LocalPizzaClient = User.pick({
  firstName: true,
  contactInfo: {
    phoneNumber: true,
  },
  address: {
    street: true,
    building: true,
  }
});
```

Would it possible be to extend `.pick(...)` function to support nested masks? As an option, the extended mask notation also may not care of whether the nested field is object or array of objects.

**Comment by zharinov** [comment]
Oh, now I see you're planning it in project board. So I'm closing this issue.

**Comment by vriad** [comment]
The roadmap isn't up to date and I'm mostly using issues to keep track of todos these days.

**Comment by soerenmartius** [comment]
hey @colinhacks , first and foremost - thanks for this great library! Do you plan to implement pick and omit for nested objects anytime soon? Thank you!

**Comment by roshan-nihaal** [comment]
was this done?
