### ISSUE TITLE
Feature request. Enable or disable .strict() by argument

### ISSUE THREAD

**Issue by max-mykhailenko** [colinhacks/zod#1400]
For the staging environment, I want to provide additional protocol validation with `strict` parsing, but it can break something on production, so I see the next solution
`.strict(process.env.NODE_ENV === 'development')`
and it gives
* `.strict()` — strict mode enabled
* `.strict(true)` — strict mode enabled
* `.strict(false)` — strict mode disabled

Is it hard to implement?

**Comment by max-mykhailenko** [comment]
Please not stale this issue :) I hope that PR will be merged soon. @brunocrosier thank you for participating.

**Comment by JacobWeisenburger** [comment]
Is this what you are looking for?
https://github.com/colinhacks/zod/pull/1484#issuecomment-1284640538

**Comment by max-mykhailenko** [comment]
@JacobWeisenburger hi
```js
const rawSchema = z.object({ ... });
const schema = process.env.NODE_ENV === 'development' ? rawSchema : rawSchema.strict()
```

I have a lot of different schemas and don't want to create add condition before each.

**Comment by JacobWeisenburger** [comment]
Does this work for you?

```ts
function makeSchemaStrict<ObjSchema extends z.ZodObject<z.ZodRawShape>> ( objSchema: ObjSchema ) {
    if ( process.env.NODE_ENV === 'production' ) return objSchema
    return objSchema.strict()
}
```
