### ISSUE TITLE
Preprocess and parser Input type

### ISSUE THREAD

**Issue by sbking** [colinhacks/zod#1405]
When using `z.preprocess`, the parser's `Input` type is set to the wrapped parser's `Input` type. In most cases, this is probably incorrect, and this prevents using `z.preprocess` with frameworks like tRPC without type errors.

Example:

```ts
const parser = z.preprocess((data) => Number(data), z.number());

function handle(data: z.input<typeof parser>) {
  return parser.parse(data);
}

handle("42");
// ts-error: Argument of type 'string' is not assignable to parameter of type 'number'.
```

^ That's a very simplified example of how this works in tRPC. I'm not sure what the ideal API is here. Maybe if we could explicitly annotate the preprocess argument? e.g.:

```ts
const parser = z.preprocess((data: string | number) => Number(data), z.number());

type Input = z.input<typeof parser>;
assertEqual<Input, string | number>(true);
```

Or alternatively, should `preprocess` simply always have an `Input` type of `unknown`? This seems like it would make the most sense, because using preprocess assumes you can handle any unknown value.

```ts
const parser = z.preprocess((data) => Number(data), z.number());

type Input = z.input<typeof parser>;
assertEqual<Input, unknown>(true);
```

**Comment by sbking** [comment]
Thinking about this some more, I think a better solution would be to have some kind of `chain` API that allows you to pipe the result of one parser to another parser:

```ts
const numberParser = z.preprocess(Number, z.number().int().nonnegative());
const stringParser = z.string().chain(numberParser).transform((n) => [n]);

// Input: string
// Output: number[]
```

This would be essentially equivalent to:

```ts
const parser = z
  .string()
  .transform(Number)
  .refine((n) => z.number().int().nonnegative().safeParse(n).success)
  .transform((n) => [n]);
```

However using `refine` and `safeParse` is really tedious, and `refine` has incorrect types when used with type guards - see #1404

**Comment by colinhacks** [comment]
> Or alternatively, should preprocess simply always have an Input type of unknown? 

This is definitely what it should be, updated in `3.19.1`.

The `chain` API is on the roadmap (in my brain) and is discussed elsewhere so I'm gonna close this 👍
