### ISSUE TITLE
.optional().default() should infer type as optional

### ISSUE THREAD

**Issue by Eckhardt-D** [colinhacks/zod#1413]
## Background

This issue is making a case that when an object is defined with optional, but default values - the underlying type should still be optional. When default is not chained to optional, the type should be required. The use case is for usage of schemas as input as well as an interface.

### Example

```ts
const captureOptionsSchema = z.object({
  url: z.string().url(),
  settings: z.object({
    width: z.number().min(320).optional().default(1280),
    height: z.number().min(320).optional().default(720),
  }).optional().default({}),
})

type CaptureOptions = z.infer<typeof captureOptionsSchema>;

/**
  type = {
    url: string;
    settings: {
      width: number;
      height: number;
    }
  }
*/
```

While technically the type above is correct for explaining what the input params look like, in something like the following, you'll need to define a second type:

```ts
function capture(options: CaptureOptions /* <-- this needs to be a different type */) {
  const params = captureOptionsSchema.parse(options);
  // ...
}
```

`CaptureOptions` in this case is not the correct type, Since there are defaults on width & height and settings sets defaults, passing these options should not be required. The catch is that `params` needs to have those props as required for correct typing.

IMHO I think a `optional().default()` chain should set the property's type as optional and it should be the dev's responsibility to use e.g. `params.settings!.width!` in the usage, instead of having to define another interface or type for the input options with Omits and Picks and Partials etc.

I hope this makes sense. I have checked through the docs and issues first in hopes of not duplicating or missing something, but if I am - please close this, but if possible advise me on a best practice here. 😄 Thanks!

**Comment by DASPRiD** [comment]
`z.infer<>` does give you the output type, not the input type. For the input you want to use `z.input<typeof yourSchema>`.

**Comment by Eckhardt-D** [comment]
@DASPRiD Thanks so much, I must have missed this in the docs. Exactly what I wanted. Closing 🎉
