### ISSUE TITLE
change export from "import { z } from 'zod'" to "import { zod } from 'zod'"

### ISSUE THREAD

**Issue by OleksiiPro** [colinhacks/zod#1423]
Letter "Z" becomes a symbol of russian military in Ukraine - russian war. Zod - is a really useful and awesome package and we are really thankful to have such an open-source project. However, the letter "Z" become a symbol of evil, dictatorship, occupation, genocide ... and a lot of bad things, that shouldn't happen in our world

If you will consider changing it - we as consumers of this package will really appreciate it 

Thank you

**Comment by tylim88** [comment]
zod is also a supervillian btw

https://en.wikipedia.org/wiki/General_Zod

**Comment by scotttrinh** [comment]
I'm amenable to being sensitive to how our symbols can add stress to our everyday lives. As proposed, this would be a breaking change, and would have pretty far reaching implications for our documentation and code examples. Plenty of other ways to work around this import like `import * as zod from "zod"` which was the initial way the export was arranged, but I have a feeling that everyone who feels affected by this has already looked for a way to mitigate this in their own usage.

I can't speak for @colinhacks here, but I would support a different export name as either a minor _addition_ to the already exported `z`, or as a breaking change that was rolled up into other breaking changes in a Zod 4.0 release. There is no timeframe for something like that, and the documentation is probably more important anyway, so I don't have much hope that this will be easily mitigated any time soon.

**Comment by OleksiiPro** [comment]
@scotttrinh thank you for your support!

As you said, the proposed changes would lead to breaking changes, but the common usage is coming from the documentation, as it is usually followed as common practice. 

And changing documentation wouldn't lead to breaking changes along with adding a **zod** export as an alias

**Comment by zavarka** [comment]
Removing the letter z from everywhere is such a slippery slope. I bet for every letter in the alphabet there is a dictator who is committing or has committed similar atrocities. Let's be reasonable about this and focus on what matters.

Before you pile on me for saying this, I'm a Ukrainian, my family is in Ukraine, and I greatly sympathize with the sentiment above. Just want you to focus on adding features and fixing bugs.

**Comment by necauqua** [comment]
I am from Ukraine (so I guess my opinion has a credibility point or something), and while I applaud things like removing Z from brands - e.g. I have a box with a giant cringe Z on it from the samsung phone - removing the z shortcut thing from _this amazing library_ never ever occured to me (I've been a heavy user for the past few weeks) until I accidentally stumbled upon this issue.

I am fully onboard with the slippery slope argument - let's remove z from the latin aplhabet altogether, here in Ukraine we use cyrillic anyway lol

**Comment by ujjwal-kr** [comment]
After seeing this I have mapped ctrl+z to ctrl+❄

**Comment by mewc** [comment]
Lol
