### ISSUE TITLE
Document `.describe()`

### ISSUE THREAD

**Issue by rattrayalex** [colinhacks/zod#1443]
I don't think this feature is documented?

Related: https://github.com/StefanTerdell/zod-to-json-schema/issues/22

**Comment by rattrayalex** [comment]
I don't think this should be closed as stale, it's garnered a few upvotes since opening.

**Comment by JacobWeisenburger** [comment]
PRs are always welcome.

**Comment by rattrayalex** [comment]
Put one up: https://github.com/colinhacks/zod/pull/1819 feedback welcome!
