### ISSUE TITLE
ZodObject.merge() looses base shape type when schema is created via a function

### ISSUE THREAD

**Issue by callumgare** [colinhacks/zod#1453]
Given two schemas like:
```typescript
const baseSchema = z.object({
  foo: z.string()
});

const extentionSchema = z.object({
  bar: z.string()
});
```

If they are merged together like so:
```typescript
const mergedSchema = baseSchema.merge(extentionSchema);
```
The resulting schema should produce a type that combines both existing schema, which it does:
![Screen Shot 2022-10-03 at 16 04 42](https://user-images.githubusercontent.com/346340/193505076-b397807c-af02-4953-be2a-730647d40342.png)

However if a factory pattern is used to construct that merged schema like so:
```typescript
function createSchema<
  BaseSchema extends z.ZodObject<ZodRawShape>,
  ExtentionSchema extends z.ZodObject<ZodRawShape>
>(baseSchema: BaseSchema, extentionSchema: ExtentionSchema) {
  return baseSchema.merge(extentionSchema);
}
```
And a new schema is created using that function:
```typescript
const mergedSchema = createSchema(baseSchema, extentionSchema);
```

Then the type of resulting schema extends an any object which is not very helpful:
![Screen Shot 2022-10-03 at 16 08 49](https://user-images.githubusercontent.com/346340/193505361-dab2266d-94c6-4f4f-be27-ffadfc45920a.png)

I've created a live example here and you can observe the constructed types by hovering over `objectBasedOnMergedSchema` on line 22 and 31: https://codesandbox.io/s/zod-merge-typescript-issue-ohz657?file=/src/index.ts

**Comment by callumgare** [comment]
Good to know about `AnyZodObject`! Ta. Sadly that function is just a significantly stripped down version of the one I'm actually using and I think the one I have might be too complex to explicitly provide a return type for which is why I was hoping merge return type could be improved in this situation so I can use make use of the implicit return type. This my actual function is:
```typescript
export function createSchemaFromSuperset<
  BaseSchema extends z.ZodObject<any>,
  CommonSchema extends z.ZodObject<any>,
  CommonProps extends Exclude<keyof z.infer<CommonSchema>, number | symbol>,
> (
  baseSchema: BaseSchema,
  commonSchema: CommonSchema,
  requiredProperties: ReadonlyArray<CommonProps>,
  optionalProperties: ReadonlyArray<CommonProps> = []
) {
  type RequiredPropertiesObj = ObjectFromList<typeof requiredProperties, true>
  const requiredPropertiesObj: RequiredPropertiesObj = requiredProperties.reduce((r, key): RequiredPropertiesObj => {
    return {
      ...r,
      [key]: true
    }
  }, {} as RequiredPropertiesObj)

  type OptionalPropertiesObj = ObjectFromList<typeof optionalProperties, true>
  const optionalPropertiesObj: OptionalPropertiesObj = optionalProperties.reduce((r, key): OptionalPropertiesObj => {
    return {
      ...r,
      [key]: true
    }
  }, {} as OptionalPropertiesObj)

  return baseSchema.merge(
    commonSchema.pick(requiredPropertiesObj).merge(
      commonSchema.pick(optionalPropertiesObj).partial(optionalPropertiesObj)
    )
  )
}
```

**Comment by igalklebanov** [comment]
Hey 👋 

Same idea as the other issue I've replied to..

```ts
  function createSchema<Shape0 extends ZodRawShape, Shape1 extends ZodRawShape>(
    baseSchema: ZodObject<Shape0>,
    extentionSchema: ZodObject<Shape1>
  ) {
    return baseSchema.merge(extentionSchema);
  }

  const mergedSchema = createSchema(baseSchema, extentionSchema);

  const objectBasedOnMergedSchema: z.infer<typeof mergedSchema> = {
    bar: 42, // ts error.
  };
```

Let me know if that worked for you.
