### ISSUE TITLE
Bug?: Optional Tuple Values

### ISSUE THREAD

**Issue by stockson** [colinhacks/zod#1465]
I'm in a situation where I'd like to send an optional number of arguments in an array:

```ts
const schema = tuple([
	string(),
	number().optional()
])

type ZodType = z.infer< typeof schema >

// Conversion of type '[string]' to type '[string, number | undefined]' may be a mistake
// because neither type sufficiently overlaps with the other.
const ar = [ "foo" ] as ZodType
```

Is it possible to infer to `[ string, number? ]` instead of `[ string, number | undefined ]` ?

**Comment by ealmansi** [comment]
it's not exactly the same, but this might work for your use case:
```ts
const schema = z.union(
  [
    z.tuple([
      z.string(),
    ]),
    z.tuple([
      z.string(),
      z.number()
    ]),
  ]
);

type ZodType = z.infer< typeof schema >;
// type ZodType = [string] | [string, number]

```

**Comment by stockson** [comment]
This is perfect thanks @ealmansi

As a workaround, is it possible to treat a tuple as an object with index properties? Ex:
```ts
object({
	0: string(),
	1: number().optional()
})
```

For your solution, my actual tuple schema is more complex so copying/pasting it is a little painful in terms of staying dry. Is it possible to clone a tuple (or any schema) and then omit the index? For example:
```ts
const schema = tuple([
	string(),
	number()
])
const combinedSchema = union([
	schema,
	schema.omit({2: true})
])
```

Thanks for your help!

**Comment by ealmansi** [comment]
@stockson looks like your workaround works just fine:

```ts
const argsSchema = z.object({
  0: z.string(),
  1: z.number().optional()
});
type Args = z.infer<typeof argsSchema>;
const args1: Args = ["str"];
const args2: Args = ["str", 23];
```

otherwise you can remove duplication in the schemas with a bit of boilerplate:
```ts
const arg1 = z.string();
const arg2 = z.number();
const arg3 = z.date();
const args = z.union([
  z.tuple([arg1]),
  z.tuple([arg1, arg2]),
  z.tuple([arg1, arg2, arg3]),
]);
type Args = z.infer<typeof args>;
```

**Comment by scotttrinh** [comment]
Working as intended, thanks everyone for the helpful examples and discussion.
