### ISSUE TITLE
Validating dynamically named object keys

### ISSUE THREAD

**Issue by tzvc** [colinhacks/zod#1470]
Hi there,

I'm running into a blocker with my use case. I have to validate an object with an arbitrary number of properties and dynamic key names:

```typescript
{ [key: string]: string }
```

I need to validate both `key` and `value` for each property. Is there a way to describe that in a zod Schema?

Cheers!

**Comment by scotttrinh** [comment]
I think you're looking for [`z.record`](https://zod.dev/?id=records)
