### ISSUE TITLE
zod.preprocess causes compilation error starting from 3.19.1

### ISSUE THREAD

**Issue by azhiv** [colinhacks/zod#1473]
After the recent release v3.19.1, the following code started to fail [compiling](https://codesandbox.io/s/beautiful-khayyam-kx97bw?file=/src/index.ts:0-282):
```ts
import * as zod from "zod";

const schema = zod.object({
  failureReasons: zod.preprocess(
    rel => [rel],
    zod.array(zod.object({})),
  )
});

export class Editor<
  S extends zod.ZodType<zod.TypeOf<typeof schema>>
    = typeof schema                    // <-- the error pops here
> {
  constructor(public schema: S) {}
}

```
This is the error from sandbox:
```
Type 'ZodObject<{ failureReasons: ZodEffects<ZodArray<ZodObject<{}, "strip", ZodTypeAny, {}, {}>, "many">, {}[], unknown>; }, "strip", ZodTypeAny, { ...; }, { ...; }>' does not satisfy the constraint 'ZodType<{ failureReasons?: {}[]; }, ZodTypeDef, { failureReasons?: {}[]; }>'.
  The types of '_input.failureReasons' are incompatible between these types.
    Type '{}' is missing the following properties from type '{}[]': length, pop, push, concat, and 26 more.ts(2344)
```
@colinhacks The error is not reproduced with zod v3.19.0, I guess the root cause is this [commit](https://github.com/colinhacks/zod/commit/2893e1659875944198aff28a3ba404858f834ed8).

PS When I replicate the same setup in VSCode locally, the error is slightly different:
```
Type 'ZodObject<{ failureReasons: ZodEffects<ZodObject<{}, "strip", ZodTypeAny, {}, {}>, {}, unknown>; }, "strip", ZodTypeAny, { failureReasons: {}; }, { ...; }>' does not satisfy the constraint 'ZodType<{ failureReasons: {}; }, ZodTypeDef, { failureReasons: {}; }>'.
  The types of '_input.failureReasons' are incompatible between these types.
    Type 'unknown' is not assignable to type '{}'.ts(2344)
```
I couldn't locate the difference, but the general behaviour is still reflecting the error, so I post the issue as is.

**Comment by ecyrbe** [comment]
hello, 
i think issues are not just related to `preprocess`. The new ZodType definition change made my typescript compiler to become extremly slow and bug on many generics with the typescript error `definition is possibly infinite`.
I had to rolled back to v3.19.0

**Comment by mlev** [comment]
Also seeing this with v3.19.1. We have this preprocess type that converts a string to an array of strings:

```
export const oneOrManyStrings = z.preprocess((arg) => {
  return typeof arg === "string" ? [arg] : arg;
}, z.array(z.string()).optional());
```

The schema type resolves correctly to `string[] | undefined` but after a `parse` operation it gets resolved to `unknown`.

**Comment by azhiv** [comment]
Explicit generic types for ZodType seem to solve the issue.
```ts
export class Editor<
  S extends zod.ZodType<zod.TypeOf<typeof schema>, zod.ZodTypeDef, unknown>
    = typeof schema
> {
  constructor(public schema: S) {}
}
```
