### ISSUE TITLE
`discriminatedUnion` errors with `z.object().transform()`

### ISSUE THREAD

**Issue by caillou** [colinhacks/zod#1477]
[Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgNwBQFAxhAHYDO8AWiQGIQRwC8KAdBABGAKwCm1GAAoEMAJ5hRALn4AbYDFFQAhisn5MnfAEoANFk7LkfJlGB0A5pKNojfGNsYGoISdLkKzAwgXHgA+OD95UTMANx0AVyVzYKMjSlpGFhIAIS0oHn4hMQlIhUs+NQ1tXXxBPOMzOqhymztHZ1d3LU9oH1LouCaQ7nD+2ISkodT0+iY4VmJc1F4rYmAGalsQOy0NYgBVOmB6PX9RfDMAbQWOCDMF3KgAXTSKIA)

```ts
import { z } from 'zod';

const ZodFoo = z.object({type: z.literal('foo'), foo: z.string()})
  .transform(({type, foo}) => ({type, value: foo}));
const ZodBar = z.object({type: z.literal('bar'), bar: z.string()})
  .transform(({type, bar}) => ({type, value: bar}));

const ZodBaz = z.discriminatedUnion('type', [ZodFoo, ZodBar]);
```

I am not sure if this is even possible.

If not, is there a recommended workaround?

**Comment by azhiv** [comment]
What exactly are you trying to achieve? Discriminating types usually result in several **different** types. In your case they are both of the same one:
```ts
{
  type: 'foo' | 'bar',
  value: string;
}
```
If the main purpose of the transformations are further manipulations/refinements, will this be suitable for your needs:
```ts
const ZodFoo = zod.object({type: zod.literal('foo'), foo: zod.string()});
const ZodBar = zod.object({type: zod.literal('bar'), bar: zod.string()});
const ZodBaz = zod.discriminatedUnion('type', [ZodFoo, ZodBar])
  .transform(obj => ({
      type: obj.type,
      value: obj.type === 'foo' ? obj.foo : obj.bar,
  }));
```
?

**Comment by roblabat** [comment]
I've had the same issue and made this openned PR https://github.com/colinhacks/zod/issues/1171 fixing this issue and waiting for feed back or merge.
