### ISSUE TITLE
Optional support for tuples

### ISSUE THREAD

**Issue by sylvanaar** [colinhacks/zod#149]
I have tried everything I can think of - however something is preventing me from writing a function type for variable number of parameters.

I can very easily write a tuple in typescript that support a variable number of elements

```ts
    type OneOrTwo = readonly [number, Record<string, string>?] 

    const one: OneOrTwo = [1] as const;
    const likeOne: OneOrTwo = [1, undefined] as const
    const two: OneOrTwo = [1, {}] as const;
```

However I cannot figure out how to do the same with zod.

```ts
const contract = {
    parms1: z.tuple([z.number()]),
    parms2: z.tuple([z.number(), z.record(z.any()).optional()]),
    ret: z.string(),
};

const p2 = z.tuple([z.number(), z.record(z.any()).optional()]) 
const u = z.union(contract.parms1, contract.parms2); // type error

p2.parse([1] as const) // too_small
u.parse([1] as const) //  invalid_union
```

It appears that it is not supported - what is involved in supporting it?

Note that since my use case is function schemas - i need to support:

```
[1]
[1, {}]
[1, undefined]
```

**Comment by vriad** [comment]
Huh never actually considered this use case. This is on the roadmap.

For now I recommend creating a union of tuple schemas, instead of a single tuple of optional schemas.

**Comment by sylvanaar** [comment]
> Huh never actually considered this use case. This is on the roadmap.
> 
> For now I recommend creating a union of tuple schemas, instead of a single tuple of optional schemas.

I toyed around with the implementation - and surprisingly it just seems to work more naturally with a single tuple with 2 input parameters, the required tuple, and the optional tuple where you supply the elements in non-optional form.

Then changes to the implementation. 

Transform the second tuple into optionals (partial)
Then merge the 2 tuples together
Add something to know how many elements are required

In parse - modify the lower bound check of count to ensure at least count of required


Ends up looking like :
```ts
 const p2or3 = z.tuple([z.number(), z.null()] as const, [z.string()] as const)
```

**Comment by sylvanaar** [comment]
This will need #152 in order for the api (+ implementation) to be as nature as possible

**Comment by vriad** [comment]
Unfortunately I don't think this is worth bumping the minimum version to v4. There may be a way to provide TS4-specific functionality using project references...I'll look into it. If I can figure that out I'll provide an improved version of the ZodTuple that supports this.

**Comment by RonnieSan** [comment]
So no go for optional support? I wanted to use this for validating arguments being sent to dynamic methods (some of which are optional).

**Comment by DrParanoia** [comment]
Hey guys, is this still a work in progress? Would be nice ti have optionals support in tuples 😞

**Comment by npup** [comment]
My usecase is defining a list of data for image in md/x frontmatter.  I would like to define tuples with the img src and an optional img alt (or title) string:

.md/x
```
---
images: [ [ "foo.jpg", "Picture of foo" ], [ "bar.jpg" ] ]
---
```

.js:
```
z.tuple([ z.string(), z.string.default("An image") ]);
```

I would find optional elements in tuple very useful!

**Comment by DrParanoia** [comment]
Well, my use case is I am defining function argument schemas for Socket.IO event handlers (basically a schema for `...args`) using Zod. And not being able to provide optionals in tuples simply means that I am not able to have optional arguments in my event handlers 😢

**Comment by craftycodie** [comment]
>  (basically a schema for ...args) 

Same use case, same problem 🥱

**Comment by phaux** [comment]
@colinhacks You said it's on the roadmap but the issue is marked as wontfix by the bot.

**Comment by HananoshikaYomaru** [comment]
Oh no, this is missed out

**Comment by hoangqwe159** [comment]
@colinhacks can team support this issue, please?

**Comment by Taib-Rabah** [comment]
# A workaround to get optional support for tuples.

## Solution

We need to use `z.preprocess()` function to manually add `undefined` where it's needed so the parse doesn't fail.

```ts
// Note: Even tho the last item is optional, you still have to pass `undefined` if you want to skip it.
const _rangeWithStepSchema = z.tuple([z.number(), z.number(), z.number().optional()]);

// So we will add it before parsing the value using `z.preprocess()` function.
// - the first argument is a function that will be called to manipulate the value before parsing it.
// - the second argument is the schema that will be used to parse the value.
const rangeWithStepSchema = z.preprocess(preprocessHandler, _rangeWithStepSchema);

function preprocessHandler(value: unknown): unknown {
  // If the value is not an array or its length is less or more that 2, we return the original value.
  if (!Array.isArray(value) || value.length !== 2) return value;
  // Otherwise, we add `undefined` in the `step` position.
  const newValue = value.toSpliced(2, 0, undefined);
  return newValue;
}

// Examples: (won't throw an error)
rangeWithStepSchema.parse([0, 10]);
rangeWithStepSchema.parse([0, 10, undefined]);
rangeWithStepSchema.parse([0, 10, 5]);
```

## How to infer the correct type

If you want to infer the schema type:

```ts
type RangeWithStep = z.infer<typeof rangeWithStepSchema>;
```

you won't be able to use it in this case, even tho the parse won't fail:

```ts
const example: RangeWithStep = [0, 10]; // TS ERROR: Source has 2 element(s) but target requires 3.
```

a workaround for this is to infer the type like this:

First we will need a helper type to make the last item(s) of an array optional:

```ts
// The `Array` parameter is the array type, and the `Count` parameter is the number of items to make optional.
// The `_Counter` and `_OgArray` are private types (Don't use them) that helps track the number of optional items and to prevent infinite loops.
export type OptionalLast<
  Array extends unknown[],
  Count extends number = 1,
  _Counter extends any[] = [any],
  _OgArray extends unknown[] = Array,
> = Array extends [...infer StartItems, infer LastItem]
  ? _Counter["length"] extends _OgArray["length"] | Count
    ? [...StartItems, LastItem?]
    : [...OptionalLast<StartItems, Count, [..._Counter, any], _OgArray>, LastItem?]
  : Array;
```

Now we can infer the type like this:

```ts
type RangeWithStep = OptionalLast<z.infer<typeof rangeWithStepSchema>>;
```

and it will work just fine in this case:

```ts
const example2: RangeWithStep = [0, 10]; // no errors
```

## Clean solution

⚠️ This is the same solution but cleaner ⚠️

```ts
import { OptionalLast } from "./types";

const rangeWithStepSchema = z.preprocess((value) => {
  if (!Array.isArray(value) || value.length !== 2) return value;
  const newValue = value.toSpliced(2, 0, undefined);
  return newValue;
}, z.tuple([z.number(), z.number(), z.number().optional()]));

type RangeWithStep = OptionalLast<z.infer<typeof rangeWithStepSchema>>;
```

**Comment by Taib-Rabah** [comment]
## Simple solution

You can use `z.union` to make an item optional:

```ts
import { z } from "zod";

// instead of using this:
const rangeWithStepSchema = z.tuple([z.number(), z.number(), z.number().optional()])

// we use this
const rangeWithStepSchema = z.union([
  z.tuple([z.number(), z.number()]),
  z.tuple([z.number(), z.number(), z.number().optional()]),
]);

// which will result in this type
type RangeWithStep = z.infer<typeof rangeWithStepSchema>; // [number, number] | [number, number, number | undefined]
```

This solution works well for simple use cases, but for me I see repetitive code and repetitive type, so this solution isn’t the one I’m looking for :)

## My solution

It's too detailed to be considered just a comment. If you are interested, you can [read this blog article](https://tr20.hashnode.dev/optional-tuple-items-in-zod#heading-my-solution)

**Comment by rvion** [comment]
ping @colinhacks  can you re-open ?

**Comment by iorate** [comment]
I came across this issue and wrote an alternative to `z.tuple()` that supports optional elements.
[zod-tuple-with-optional](https://www.npmjs.com/package/zod-tuple-with-optional?activeTab=readme)

**Comment by cdauth** [comment]
It seems that with Zod 4, parameters marked with `.optional()` work as intended in tuples. On the other hand, the `zod-tuple-with-optional` package that used to be the workaround does not work with Zod 4 anymore.
