### ISSUE TITLE
Handling multiple forms with discriminated union

### ISSUE THREAD

**Issue by kwangCoveo** [colinhacks/zod#1493]
ValidationSchema = z.object({
  ParentBlock: z.object({    
    **choiceOfForm** : z.enum
    DataBlock: z.discriminatedUnion(**choiceOfForm**, [
                 z.object({ choiceOfForm = 1, empty fields})   //corresponds to the basic form
                 z.object({ choiceOfForm = 2, just username/pw fields)   //corresponds to less basic form
                 z.object({ choiceOfForm = 3, user/pw + many fields})   //corresponds to advanced form
          ])
      })
})

**choiceOfForm** is an ENUM corresponding to 3 radio buttons. The corresponding form depending on selection. 
I would like to use ZOD's discriminatedUnion function to enable the correct form validation block depending on which **choiceOfForm** is selected (1,2 or 3). Is there a way to pass the **choiceOfForm** variable to the discriminatedUnion (enumHere, ...) to do this?

Thank you

**Comment by suhaotian** [comment]
You should format your code first
