### ISSUE TITLE
Zod Structure

### ISSUE THREAD

**Issue by alandev2** [colinhacks/zod#1499]
I am trying to add more validation's types, but this structure is so hard to understand because all types are in same file `types.ts` 

Sugestion:
at the moment `types.ts` has 4000 lines, what do you guys think to split it in one folder `types` and create files by type, ex:
```md
src/types
src/types/string.ts
src/types/number.ts
```

**Comment by colinhacks** [comment]
Definitely not. It used to be this way and we had endless circular import issues, because ZodType has methods that return instances of its own subclasses. Trust me, recipe for disaster ✌️

**Comment by alandev2** [comment]
oh ok, it makes sense

**Comment by jasonkuhrt** [comment]
Out of curiosity would it still be an issue if this were an ESM package?

**Comment by IlyaSemenov** [comment]
That's odd. Typically the disaster happens on module-level code, and even then it's usually easily avoidable (such as always using `import { ... } from '.'`).

Will you be accepting a PR if someone split the huge `types.ts` into submodules and this actually worked?
