### ISSUE TITLE
Equality method to assert two zod schemas are the same

### ISSUE THREAD

**Issue by seanlaff** [colinhacks/zod#1512]
When using react, it's probable a zod schema ends up in a useEffect inside of a component or hook

```ts
const zodSchema = z.object({
  username: z.string()
});
// fetch some data over http
useEffect(() => {...}, [query, zodSchema]
```

Every render, `zodSchema` is a new reference, meaning we get stuck in an infinite loop.

Conventional wisdom is wrap the zod schema in a memo

```ts
const zodSchema = useMemo(() => (z.object({
  username: z.string()
}));
// fetch some data over http
useEffect(() => {...}, [query, zodSchema]
```

However, if we want to provide our users a hook that abstracts data fetching like this
```ts
// fetch some data over http
const [resp, err] = useFetchData(query, zodSchema)
```

it'd be best if the `useFetchData` hook handled the memoization for the caller, but to do that, we'd need a way to compare zod two zod schemas for equality to short-circuit early. A react hook may implement a deep equality for a usecase like this, but we don't have a great way to do that since a zod object has a complex structure of nested objects and functions.

In some ways, I suppose this is almost a request for a serialization function in zod (which I realize some 3rd party libs like `zodToJsonSchema` already provide).

**Comment by scotttrinh** [comment]
> Conventional wisdom is wrap the zod schema in a memo

One small suggestion:

If something doesn't depend on props, the conventional wisdom is to actually store it _outside_ of the component itself:

```ts
const zodSchema = z.object({
  username: z.string(),
});

export const MyComponent = (props: Props) => {
  useEffect(() => {}, [query]);
};
```

**Comment by JacobWeisenburger** [comment]
Has this issue been resolved?
