### ISSUE TITLE
Update email regex to use W3C's one?

### ISSUE THREAD

**Issue by timojuonoja** [colinhacks/zod#1515]
There is no 100% bullet proof email regex, but should you update it to use W3C's one? Currently I'm facing a bug that `a\b@c.com` is passed, when W3C's regex wouldn't pass it.

Current zod regex for email is:
```
(/^(([^<>()[\]\.,;:\s@\"]+(\.[^<>()[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i)
```

When [W3C suggests](https://html.spec.whatwg.org/multipage/input.html#email-state-(type=email)):
```
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
```

**Comment by Tyler-Murphy** [comment]
See also: https://github.com/colinhacks/zod/pull/1435

**Comment by timojuonoja** [comment]
@Tyler-Murphy PR #1435 does not fix this issue.

**Comment by Tyler-Murphy** [comment]
Sorry, I should have been clearer. I'm just pointing out its existence, since the W3C regex appears not to work with some of the test cases in #1435.

**Comment by mpartel** [comment]
This would also allow `+` in addresses like name+test123@example.com, which would be good.

**Comment by fvckDesa** [comment]
@timojuonoja "\" non è un carattere email valido, l'unico modo per usarlo è con le virgolette doppie intorno alla parte locale dell'email

**Comment by timojuonoja** [comment]
> @timojuonoja "\" is not valid email character, the only way to use it is with the double quotes around the local-part of email

Yes, you are absolutely right by the way.
We seem to have an error in our test cases after all... I'm closing this due to incorrect assumptions.
