### ISSUE TITLE
Add support to conditional typings 

### ISSUE THREAD

**Issue by lucassarcanjo** [colinhacks/zod#1523]
Hi there,

I've been working on a feature with dynamic schemas that I need to validate some rules, but I'm having trouble with typescript errors in `refine` or `superRefine`.

```ts
import { z } from 'zod';

// Dynamic condition that the user can change, for example
let isForm1Active = false;

// Basic schema
const form1Schema = z.object({
  name: z.string(),
  age: z.number(),
});

// Dynamic schema
const schema = z
  .object({
    form1: isForm1Active ? form1Schema : z.unknown(),
  })
  .refine((args) => {
    // args.form1.name is not accessible, ok

    if (isForm1Active) {
      // args.form1.name is still not accessible
      // maybe here, like in union types in typescript, this should work?
    }
  });

```

Is there another way to work with dynamic items without losing the type safety of zod?

Live preview:
https://stackblitz.com/edit/typescript-kaf78i?file=index.ts

Thanks in advance and congratulations on this lib, the syntax to validate everything is so neat!

**Comment by datner** [comment]
there are a few tools to achieve what you're trying to do
Did you try to use `z.union`, or more specifically `z.discriminatedUnion`?

**Comment by JacobWeisenburger** [comment]
@lucassarcanjo
Is the above answer satisfactory? Or do you have any questions?

I'd like to close this issue if there are no further questions.
