### ISSUE TITLE
z.date() does not pick custom error messages

### ISSUE THREAD

**Issue by igusiatin** [colinhacks/zod#1526]
Using latest `"zod": "^3.19.1"`
```ts
import { z } from "zod";
...
      dateOfBirth: z
        .date({
          required_error: "Please select a date and time",
          invalid_type_error: "That's not a date!"
        })
...
```
![Screenshot from 2022-10-27 12-22-23](https://user-images.githubusercontent.com/115006985/198247467-3b9bf5f6-1f3c-4467-9cd2-b51bb33ace07.png)

**Comment by shinnoki** [comment]
Same issue.

As a workaround, you can override error message by passing `errorMap`.

```typescript
      dateOfBirth: z
        .date({
          errorMap: (issue, { defaultError }) => ({
            message: issue.code === "invalid_date" ? "That's not a date!" : defaultError,
          }),
        })
```

It's nice if there's more convenient way to custom message.

**Comment by JacobWeisenburger** [comment]
The issue is here:
https://github.com/colinhacks/zod/blob/b898ee5763a0d374ffc8bb73572b03dec78e75a5/src/types.ts#L121

since the error code is `invalid_date` and not `invalid_type` then it returns the default error message.

```ts
const dateOfBirth = z.date( {
    required_error: "Please select a date and time",
    invalid_type_error: "That's not a date!"
} )

const invalidDate = new Date( '33/10/2022' )
const result = dateOfBirth.safeParse( invalidDate )
!result.success && console.log( result.error.issues[ 0 ].code )
// invalid_date
```

The more I think about this, I don't think this is a bug. It's just not intuitive. Maybe this should be documented or changed.

**Comment by igusiatin** [comment]
Argument of type '{ invalid_date_error: string; errorMap: (issue: ZodIssueOptionalMessage, { defaultError }: ErrorMapCtx) => { message: string; }; }' is not assignable to parameter of type '{ errorMap?: ZodErrorMap | undefined; invalid_type_error?: string | undefined; required_error?: string | undefined; description?: string | undefined; } & { coerce?: boolean | undefined; }'.

Types have to be fixed then

**Comment by JacobWeisenburger** [comment]
Perhaps this would help you:

https://github.com/JacobWeisenburger/zod_utilz#makeerrormap

```ts
import { zu } from 'zod_utilz'

const dateOfBirth = z.date({
    errorMap: zu.makeErrorMap({
        required: 'Please select a date and time',
        invalid_date: `That's not a date!`,
    }),
})

{
    const result = dateOfBirth.safeParse(undefined)
    !result.success && console.log(result.error.issues[0].message)
    // Please select a date and time
}

{
    const result = dateOfBirth.safeParse(new Date('33/10/2022'))
    !result.success && console.log(result.error.issues[0].message)
    // That's not a date!
}
```

**Comment by AdsonCicilioti** [comment]
Same problem here! :cry:

**Comment by Gust4voSales** [comment]
https://stackoverflow.com/questions/77465460/zod-coercion-to-date-custom-error-message?noredirect=1#comment136567416_77465460

recently happened to me as well!

**Comment by mderrick** [comment]
I'm overriding the error map for my date field to always display a generic "Invalid date" message yet I get the message "Invalid Input" instead when parsing values such as `09/09/9999`. Shouldnt this just render the only message I provided in the errorMap or am I misunderstanding it?

```
z.coerce
  .date({
    errorMap: () => ({
      message: "Invalid date"
    }),
  })
```

**Comment by Laura477** [comment]
Hello, same problem here and when I try to use the workaround that has been provided here, with overwriting the errorMap, I keep getting errors. Console output for reference: "ARGH, an error: Error: Objects are not valid as a React child (found: object with keys {errorMap}). If you meant to render a collection of children, use an array instead.". Any other ideas on how to set a custom error message other than the standard "invalid date" on invalid date errors would be very welcome

**Comment by Ibadetegashi** [comment]
Zod's .date() method does not support custom error messages directly.

_Solution:_ Ensure the Date is Passed as a String in format **("YYYY-MM-DD")**
Before using .date(), make sure the frontend passes the date as a properly formatted string ("YYYY-MM-DD") then in zod schema:
```
receipt_date: z
  .string({
    required_error: t("receiptDate.required"), // Custom required message
  })
  .date(); // Ensures conversion to a valid Date object 
```
const date = z.string().date();

date.parse("2020-01-01"); // pass
date.parse("2020-1-1"); // fail
date.parse("2020-01-32"); // fail
```

```
_Handling in Backend_
const parsedDate = new Date(receipt_date); // Convert "YYYY-MM-DD" string to Date object

**Comment by SantiagoMerlo1337** [comment]
same problem here.
