### ISSUE TITLE
[Feature suggestion] A way to chain/pipe validations

### ISSUE THREAD

**Issue by webNeat** [colinhacks/zod#1529]
Hello,

First of all, thank you for making and maintaining this awesome library.

I started using `zod` to validate forms on a frontend project, and found myself doing things like:

```ts
const FormData = z.object({
  age: z.string().transform((x, ctx) => {
    const value = parseInt(x)
    if (isNaN(value) || value < 0) {
      ctx.addIssue({code: z.ZodIssueCode.custom, message: 'should be a positif integer'})
      return z.NEVER
    }
    return value
  }),
  worked_days_in_month: z.string().transform((x, ctx) => {
    const value = parseInt(x)
    if (isNaN(value) || value < 0 || value > 31) {
      ctx.addIssue({code: z.ZodIssueCode.custom, message: 'should be an integer between 1 and 31'})
      return z.NEVER
    }
    return value
  }),
})
```

Since all values coming from the HTML inputs are strings, I have to validate them using `z.string` then use `.transform` to convert them to numbers and do additional validation.

I think it will be easier if after converting them to numbers, I could chain them to a `z.number` with some additional checks, something like:

```ts
const FormData = z.object({
  age: z.string().transform(x => parseInt(x)).chain(z.number().int().min(0)),
  worked_days_in_month: z.string().transform(x => parseInt(x)).chain(z.number().int().min(0).max(31)),
})
```

So my suggestion is to add a method `.chain` (or `.pipe` or other name ...) that behaves as follows:

```ts
const a: ZodType // with types: _input = A and _output = B
const b: ZodType // with types: _input = B and _output = C

const c = a.chain(b) // gives a ZodType with _input = A and _output = C
```

Let me know if this is something you would be interested in adding to the library, I can try to make a PR for it if you agree.

**Comment by samchungy** [comment]
You could use `preprocess()`?

Something like this:

```ts
const stringToNumber = (arg: unknown) =>
  typeof arg === 'string' && Number(arg) !== NaN ? Number(arg) : arg;

const FormData = z.object({
  age: z.preprocess(stringToNumber, z.number().int().min(0)),
  worked_days_in_month: z.preprocess(stringToNumber, z.number().int().min(0).max(31))
})
```

**Comment by timm-stelzer-e-farm** [comment]
Personally, I am not a fan of the `preprocess` style. 
1. You can't compose parsers, you have to write your own, "not-zod"-logic to make it work.
2. You have to nest, essentially, callbacks. `z.preprocess(z.preprocess(z.preprocess(customFoo, foo), bar), qux)`. Not very elegant.

I prefer https://github.com/colinhacks/zod#validating-during-transform, though its also sub-optimal, and shares some of the same issues.

I believe the thing "preventing" us from having "proper" chaining is that Zod parsers aren't Functors / Monads. In a different world, you would have something like `io-ts`, where you can do `a.chain(b).chain(c)`, where `a`, `b` and `c` are all parsers. I think that was discussed in a prior issue though, so I'm pretty sure the library authors are aware of this option :)

**Comment by samchungy** [comment]
tbh if you need to do that many nests you're probably overcomplicating your Zod type. Just my 2c.

**Comment by timm-stelzer-e-farm** [comment]
> tbh if you need to do that many nests you're probably overcomplicating your Zod type. Just my 2c.

Fair enough, though this type of composition is fundamental in functional programming, and since `zod` was explicitly inspired by `io-ts` (a library where this kind of composition is built-in), it isn't far-fetched to expect this kind of API.

**Comment by timm-stelzer-e-farm** [comment]
Looks like [pipe is now built-in](https://github.com/colinhacks/zod/releases/tag/v3.20) and should resolve this issue :) 

```ts
z.string()
  .transform(val => val.length)
  .pipe(z.number().min(5))
```

**Comment by webNeat** [comment]
@timm-stelzer-e-farm you're right, I will close this issue.
Thanks @samchungy and @timm-stelzer-e-farm for the valuable discussion, sorry I couldn't be more active in this thread.
