### ISSUE TITLE
required method expecting 0 arguments

### ISSUE THREAD

**Issue by m-salman-afzal** [colinhacks/zod#1535]
I'm trying to build schema validation with **partial and required**, but **required method is giving error saying it expects 0 arguments**. Here is a bit of code, where ValidationObjects are where schema has been defined,
```
static getSafeReportValidation(body: unknown) {
        const getSafeReport = SafeReportValidationObject.merge(AdminValidationObject)
            .merge(PaginationValidationObject)
            // .pick({
            //     anonymous: true,
            //     reportType: true,
            //     toDate: true,
            //     fromDate: true,
            //     adminId: true,
            //     adminType: true,
            //     currectPage: true,
            //     perPage: true
            // })
            .partial({anonymous: true, reportType: true, toDate: true, fromDate: true, adminId: true, adminType: true})
            .required();

        return getSafeReport.parse(body);
    }
```

**Comment by muhammadsalmanafzal** [comment]
any updates on this?

**Comment by m-salman-afzal** [comment]
For some reason, it started working for the latest version as of now (3.20.1). But I think, the required, partial and pick should be independent of each other. They should not be used in conjunction to each other. Like practically, partial should make the properties defined on object schema as optional (no need to first pick, then, partial). The required method should only make the properties inside its method as required, not the whole object. And then pick should be chosen when you need to do some refine functions on it.
Anyways, closing this function for now, because no reply.
