### ISSUE TITLE
When merging two zod objects (using .extend) they are deemed not equal

### ISSUE THREAD

**Issue by robmolloyntt** [colinhacks/zod#1539]
Apologies in advance if this is a problem with `@type-challenges/utils` but I've never known it to be wrong before. 

I need to get two separate types to align as I'm (annoyingly) working with two separate type systems; one pre-built the other inferred from a Zod schema. 

This works well other than using  `STest1.extend(STest2.shape)` where `STest1` & `STest2` are Zod schemas. Minimum viable example below

```ts
import type { Equal, Expect } from '@type-challenges/utils'
import { z } from 'zod'

const STest1 = z.object({ a: z.string() })
const STest2 = z.object({ b: z.boolean() })
const STest = STest1.extend(STest2.shape)

type TISTest1 = z.infer<typeof STest1> // irrelevant
type TISTest2 = z.infer<typeof STest2> // irrelevant
type TISTest = z.infer<typeof STest>

type TTest1 = { a: string }
type TTest2 = { b: boolean }
type TTest = TTest1 & TTest2

export type Cases = [Expect<Equal<TISTest, TTest>>]
```

**Comment by igalklebanov** [comment]
Unrelated to zod.

Example, this is not `Equal`:

```ts
Expect<Equal<{ a: "hi"; b: "bye" }, { a: "hi" } & { b: "bye" }>>
```

But it is `Alike`.

**Comment by JacobWeisenburger** [comment]
@robmolloyntt 
Is the above answer satisfactory? Or do you have any questions?

I'd like to close this issue if there are no further questions.
