### ISSUE TITLE
Allow array to return only valid items and not fail whole array

### ISSUE THREAD

**Issue by bmeverett** [colinhacks/zod#1547]
When validating an array, I would like to only return the valid items in an array and not fail if one item fails. 

This is a very basic example
```ts
const schema = z.object({
  arr: z.array(z.number())
})

const result = schema.safeParse({arr: [1,2,"3"]})
```

I would like this to return only the valid items
``` ts
arr: [1,2]
```

I tried using `refine` on the array, but it seems to only be called when the array validates correctly. Is there a way to do this, or is this something you'd be willing to support?

**Comment by JacobWeisenburger** [comment]
@bmeverett 
Is this what you're looking for?

```ts
const schema = z.object( {
    arr: z.any().array().transform(
        arr => arr.map( item =>
            z.number().safeParse( item ).success ? item : undefined
        ).filter( Boolean )
    ),
} )

console.log( schema.parse( { arr: [ 1, 2, '3' ] } ) ) // { arr: [ 1, 2 ] }
```

**Comment by bmeverett** [comment]
Thanks @JacobWeisenburger and @lucassarcanjo I think I can work with these.
