### ISSUE TITLE
Addition of ZodIssueCode.invalid_literal custom error message broken. 

### ISSUE THREAD

**Issue by pascallapointe** [colinhacks/zod#1551]
Reference commit: [Add invalid_literal issue](https://github.com/colinhacks/zod/commit/823dda93193ab23f07b7e4625e54b1e8528cc530#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410a)

ZodLiteral takes a `RawCreateParams`object that allow to customize error message.

That object is passed through `processCreateParams()`, but that function has not been updated to support the ìnvalid_literal` type.

Before the commit in reference, it was possible to customize the error message using the 'invalid_type_error' property. But since the issue code is now **invalid_literal** instead of **invalid_type**, the default error message is returned every time. ([types.ts#L118](https://github.com/colinhacks/zod/blob/c617ad3edbaf42971485f00042751771c335f9aa/src/types.ts#L118))

It still possible to customize the ZodLiteral error message by passing a custom ZodErrorMap, but I wonder if the current behavior brought by the change was really intended.

**Comment by colinhacks** [comment]
It's unfortunate but intended. The `required_error` and `invalid_type_error` fields are somewhat hacky ways to set custom error messages for some common issue codes. 

I'm considering adding a simpler way to define error maps, something like this:

```ts
z.literal("tuna", { 
  errorMap: {
    required: "Input is required",
    invalid_type: "Must be string",
    invalid_literal: "Not a tuna", 
  }
})
```

Thoughts?
