### ISSUE TITLE
Question: json map(string, object)

### ISSUE THREAD

**Issue by adeturner** [colinhacks/zod#1553]
Please can someone confirm if this is possible and steer me in the right direction? I've tried a number of ways but I'm not getting there

Sample that errors:

```javascript
  const MyobjJson = {
    "addresses": {
      "roger": {
        "address": "some street"
      },
      "peter": {
        "address": "other street"
      }
    }
  };
  
  const schemaAddress=z.object({
    address: z.string()
  });

  const schemaAddresses=z.map(z.string(), schemaAddress)
  
  const schemaMyobj = z.object({
    addresses: schemaAddresses
  });

  var r = schemaMyobj.parse(MyobjJson)
  console.log(r)
```

Error...

```txt
    ZodError: [
    {
      "code": "invalid_type",
      "expected": "map",
      "received": "object",
      "path": [
        "addresses"
      ],
      "message": "Expected map, received object"
    }
  ]
  ```

**Comment by adeturner** [comment]
The below seems to work, any observations very welcome. 
Coming from a Go background I guess I'm struggling with Go map = Typescript Map/Record

```javascript
  //const schemaAddresses=z.map(z.string(), schemaAddress)
  const schemaAddresses=z.record(schemaAddress)
    
  var v = r.addresses
  for (let k in v) {
    console.log(v[k as keyof typeof v].address)
  }
```

**Comment by lucassarcanjo** [comment]
Hi @adeturner,

In fact, the `z.map()` is based on the Map type of JS ([ref](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)) which is a bit different from the original JavaScript object. Your `MyobjJson` is a JS object and can be parsed with Zod with something like:

```ts
const schema = z.object({
  addresses: z.record(
    z.object({
      address: z.string(),
    })
  ),
});
```

Live example [here](https://stackblitz.com/edit/typescript-y4hkgk?file=index.ts).

The use of `z.record()` it's based on the Typescript behavior of [Record utility type](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type) which allows us to type correctly objects with dynamic properties.

**Comment by adeturner** [comment]
Thanks for confirming Lucas, much appreciated.  Really liking zod tbh, it makes mapping typescript to Go's struct/validate much easier.
