### ISSUE TITLE
Property 'datetime' does not exist on type 'ZodString'.

### ISSUE THREAD

**Issue by Esa-Kurniawan** [colinhacks/zod#1580]
Since i am new to zod, i've been reading the documentation for a while and found the [z.string().datetime()](https://github.com/colinhacks/zod#datetime-validation) method.

However, when I tried that method on my project, I got an error that's says `Property 'datetime' does not exist on type 'ZodString'`.
![image](https://user-images.githubusercontent.com/97936043/203324675-14450d4e-bb02-4db5-8cfb-0b91b53486b0.png)

do you guys have any workaround for this problem?

**Comment by lfDev28** [comment]
Ive just been using z.date(). Works fine with datetime strings for me...

**Comment by Esa-Kurniawan** [comment]
> Ive just been using z.date(). Works fine with datetime strings for me...



`z.date()` method will throw an error, if the date is in the form of a string  (e.g `2020-01-01T00:00:00.123Z`).

Since I need to check if the `date string` is a valid date or not, the z.date() method won't work for me.

**Comment by gabrielgrover** [comment]
would like to see this available as well

**Comment by Esa-Kurniawan** [comment]
> would like to see this available as well. In the meantime @Esa-Kurniawan you can unblock yourself by following the documentation here `https://github.com/colinhacks/zod#dates`. <img alt="Screen Shot 2022-11-26 at 12 37 30 PM" width="866" src="https://user-images.githubusercontent.com/12038578/204108074-6e4c781c-4599-4ad2-b6cc-7dab697e6603.png">

Yeah, I think I can use this `dateSchema` method for validating a `date string` for now, until the `z.string().datetime()` method is released.

**Comment by mauriciabad** [comment]
I see 2 important problems here:
1. Documentation should be only about released code. It doesn't make any sense that it explains how to use a function that's not implemented.
2. The npm release process is ineffective. The code has been merged 1 month ago but not released yet.

**Comment by padge** [comment]
I had to install version `3.20.0-beta.0` to access `.string().datetime()`.

https://github.com/colinhacks/zod/releases/tag/v3.20.0

**Comment by FabioCingottini** [comment]
`z.string().datetime()` is now available due to [v3.20.2 of zod being available!](https://www.npmjs.com/package/zod)

**Comment by Esa-Kurniawan** [comment]
The z.string().datime() has been released

**Comment by Esa-Kurniawan** [comment]
> `z.string().datetime()` is now available due to [v3.20.2 of zod being available!](https://www.npmjs.com/package/zod)
Alright, will mark this issue as fixed then.
