### ISSUE TITLE
Date tests are failing due to mismatching timezone

### ISSUE THREAD

**Issue by montedonioluiz** [colinhacks/zod#1581]
The following test (using `Jest`) is failing due to mismatching timezone. My timezone is `-03:00`, and if I create the date objects with my timezone, the tests pass. I believe that the Zod library might be handling something with the machine's timezone instead of the timezone of the dates passed

```ts
test("date parser error messages", () => {
  const schema = z.date();

  expect(getErrorMessage(schema.safeParse("2022-12-01"))).toEqual(
    "Expected date, received string"
  );
  expect(
    getErrorMessage(
      schema.min(new Date("2022-08-01")).safeParse(new Date("2022-07-29"))
    )
  ).toEqual(`Date must be greater than or equal to 8/1/2022`);
  expect(
    getErrorMessage(
      schema.max(new Date("2022-08-01")).safeParse(new Date("2022-08-02"))
    )
  ).toEqual(`Date must be smaller than or equal to 8/1/2022`);
});
```

![image](https://user-images.githubusercontent.com/36773088/203346017-213073af-3464-40e9-b1fa-1e7538f31118.png)

**Comment by denvaki** [comment]
hey, zod not applying timezone by itself. Just when validation error happens zod calling [Date's .toString() method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toString). This method applies timezone into string. it is standard function that could be overwritten with by prototype definition if you want.

Please close issues. :pray:

**Comment by montedonioluiz** [comment]
> hey, zod not applying timezone by itself. Just when validation error happens zod calling [Date's .toString() method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toString). This method applies timezone into string. it is standard function that could be overwritten with by prototype definition if you want.
> 
> Please close issues. pray

Thanks for clearing up! If I check using the initial 'minimum' date object, then it'll work regardless of timezone. I'll make the necessary changes, thanks again!
