### ISSUE TITLE
intersect mapped enum record and object

### ISSUE THREAD

**Issue by tim1uphealth** [colinhacks/zod#1582]
How would I create the equivalent to this with `zod`?
```
enum Status {
  NotStarted = 'not-started',
  InProgress = 'in-progress',
  CompletedSuccesfully = 'completed-succesfully',
  CompletedWithFailures = 'completed-with-failures',
  Failed = 'failed',
}
type StatusReports = {
  [k in Status]: number;
};

type StatusReport = StatusReports & {
  total: number;
};
const sr: StatusReport = {
  total: 5,
  [Status.NotStarted]: 1,
  [Status.InProgress]: 1,
  [Status.CompletedSuccesfully]: 1,
  [Status.CompletedWithFailures]: 1,
  [Status.Failed]: 1,
};
```
## problems I've encountered so far

defining the mapped key type  for `StatusReports` with `z.record()` and `z.nativeEnum(}` yields `Partial<Record<Status, number>>;`,  with the mapped properties incorrectly being optional
```
enum Status {
  NotStarted = 'not-started',
  InProgress = 'in-progress',
  CompletedSuccesfully = 'completed-succesfully',
  CompletedWithFailures = 'completed-with-failures',
  Failed = 'failed',
}
const StatusReports = z.record(z.nativeEnum(Status), z.number());
const sr: z.infer<typeof StatusReports> = {}; // const sr : Partial<Record<Status, number>>
```
even if the mapped key properties were correctly inferred as required, I haven't figured out a way to merge `z.record()` with `z.object({total: number})`
using `z.intersection()` like so complies but throws the following error when parsed at runtime
```
const StatusReportSchema = z.intersection(
  z.record(StatusReports, z.number().min(0)),
  z.object({ total: z.number().min(0) }),
);
```
`"Invalid enum value. Expected 'not-started' | 'in-progress' | 'completed-succesfully' | 'completed-with-failures' | 'failed', received 'total'"`

**Comment by santosmarco-caribou** [comment]
Hi @tim1uphealth, I don't think there's a way to intersect an `enum` or a `ZodNativeEnum` with a `ZodObject` right now.

I have some ideas on how we can change that. Check out this PR: https://github.com/colinhacks/zod/pull/1660
