### ISSUE TITLE
Typescript widening object properties of Zod enum type to string

### ISSUE THREAD

**Issue by akoltun** [colinhacks/zod#1590]
If I define `enum` and use it in the object, the object property still has the type of the `enum`:
```ts
enum A { a = "a" }

const a = { a: A.a }
// type of a is { a: A }
```

However, if I define the same enum using zod, the type of object property is `string` and not narrowed to enum anymore.
```ts
const A = z.enum(["a"])

const a = { a: A.a }
// type of a is { a: string }
```

**Comment by maxArturo** [comment]
Hey @akoltun ! It seems like you expect `A: z.EnumType`, as defined in `const A = z.enum(["a"])` to have an internally-defined `Enum` type, such that you could narrow down via its enumerators? 

At a glance not sure how it would work (I think an actual `Enum` can't be defined dynamically, but we _can_ validate the  values passed in – which is why I guess the output value is `Values<T>`). In any case, if you're looking for a quick solution, TS will use the expected definition if you pull in from an existing enum: 

```ts
  enum A {
    a = "a",
  }

  const enumValidator = z.enum([A.a]);

  const a = { a: enumValidator.Enum.a };
  // type of a is { a: A }
```

**Comment by elemti** [comment]
I'm running into a similar issue, my use case is like so

```
const a = z.enum(['A', 'B']).parse(123);
// type of a is 'A' | 'B'

const b = {
  x: z.enum(['A', 'B']).parse(123),
};
// type of b is { x: string; }

const c = {
  x: z.union([z.literal('A'), z.literal('B')]).parse(123),
};
// type of c is { x: 'A' | 'B' }
```

I would really prefer using zod enums to using zod unions because of the neater syntax

**Comment by akoltun** [comment]
My workaround for the moment is to use native enums and convert them to zod validator by `z.nativeEnum(...)` just in place in the schema.

```
  enum A {
    a = "a",
  }

  const a = { a: z.nativeEnum(A) };
  // type of a is { a: A }
```

**Comment by akoltun** [comment]
Thank you @maxArturo ,

Is there any difference between `{ a: z.enum([A.a]) }` and `{ a: z.nativeEnum(A) }` in terms of the result of schema validation?

I didn't discover any yet but maybe I'm not far enough.

**Comment by maxArturo** [comment]
Hi @elemti , I wonder if you have usecases where you need to define a schema in-line with an object? (such as below)
> const b = {
>   x: z.enum(['A', 'B']).parse(123),
> };
> // type of b is { x: string; }

I agree its surprising that TS will widen the type to `string` _inside_ an object, I'm curious about that and will look at it... but if you can use `z.object()` for the entire object then it will work as expected: 

```ts
  const main = z.object({
    x: z.enum(["A", "B"]),
  });

  type testType = z.infer<typeof main>;
  /**
    type testType = {
      x: "A" | "B";
    }
   */
```

@akoltun I took a look at the implementation, and except for the way the enums are stored and checked (an object for [nativeEnum](https://github.com/colinhacks/zod/commit/7df8da040617e885fccad712e93c243d07f66216#diff-b2d78a8c331a524ec680daa0f67782bb339a385936d615a61f66d486d9346d58R20) and an array for [Enum](https://github.com/colinhacks/zod/commit/3a4bf8db56db49f15cbe83d8e5c2bbfa9544b8c6#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410aR2713)) there's not that much difference -  for compatibility as the README says if I took a guess. Would love for someone more knowledgeable to chime in!

**Comment by elemti** [comment]
hi @maxArturo , usually I run into this problem when trying to use `.transform()` to enhance an object like this
```
const schema = z
  .object({
    x: z.enum(['A', 'B']),
  })
  .transform((it) => {
    // do transformations...
    return {
      ...it,
      y: z.enum(['A', 'B']).parse(123),
    };
  });
const enhancedObj = schema.parse({});
/*
  const enhancedObj: {
    y: string;
    x: "A" | "B";
  }
*/
```
I wonder if there's any better way to enhance / add new keys an object instead of doing this?

**Comment by JacobWeisenburger** [comment]
@akoltun 
Has your question been answered? Or do you have any other questions?

I'd like to close this issue if there are no further questions.

**Comment by JacobWeisenburger** [comment]
@elemti 
Here's one way it could be done. If this is not what you are looking for, feel free to open a new discussion and I'll do my best to help there.

```ts
const schema = z.object( {
    x: z.enum( [ 'A', 'B' ] ),
    y: z.string().or( z.number() ),
} ).transform( ( { x, y }, ctx ) => {
    if ( x == 'A' ) {
        const yResult = z.string().safeParse( y )
        if ( yResult.success )
            return { x, y: yResult.data }

        ctx.addIssue( {
            code: z.ZodIssueCode.invalid_type,
            expected: 'string',
            received: typeof y,
            path: [ 'y' ],
        } )
        return { x, y: y as string }
    }

    const yResult = z.number().safeParse( y )
    if ( yResult.success )
        return { x, y: yResult.data }

    ctx.addIssue( {
        code: z.ZodIssueCode.invalid_type,
        expected: 'number',
        received: typeof y,
        path: [ 'y' ],
    } )
    return { x, y: y as number }
} )
type Obj = z.infer<typeof schema>
// type Obj = {
//     x: "A"
//     y: string
// } | {
//     x: "B"
//     y: number
// }

console.log( schema.parse( { x: 'A', y: 'foo' } ) )
console.log( schema.parse( { x: 'B', y: 42 } ) )

const result = schema.safeParse( { x: 'A', y: 42 } )
!result.success && console.log( result.error.flatten() )
```

**Comment by akoltun** [comment]
> @akoltun I took a look at the implementation, and except for the way the enums are stored and checked (an object for [nativeEnum](https://github.com/colinhacks/zod/commit/7df8da040617e885fccad712e93c243d07f66216#diff-b2d78a8c331a524ec680daa0f67782bb339a385936d615a61f66d486d9346d58R20) and an array for [Enum](https://github.com/colinhacks/zod/commit/3a4bf8db56db49f15cbe83d8e5c2bbfa9544b8c6#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410aR2713)) there's not that much difference - for compatibility as the README says if I took a guess. Would love for someone more knowledgeable to chime in!

@maxArturo  Thank you for your research.


> @akoltun Has your question been answered? Or do you have any other questions?
> 
> I'd like to close this issue if there are no further questions.

@JacobWeisenburger, I understood the cause why the widening is happening as well as TypeScript limitations. Also I'm fine with workaround that I'm using. So, please, feel free to close the issue if other folks have no more questions.
