### ISSUE TITLE
Stop parsing by each field with error

### ISSUE THREAD

**Issue by ElYaiko** [colinhacks/zod#1605]
Is there a way to stop parsing each field with an error and return the string error, instead of keep parsing the others rules of the fields and get an array?
For example if I have a custom rule that makes a Http validation and the field has an error, I would not want to do the Http validation... an alternative would be to get in the context of `superRefine` if the field has an error.

Thanks!.

**Comment by denvaki** [comment]
I think it is matter of formatting error and getting first error from error array. By this snippet if you change order of schema fields it will influence on order of error msgs. That means you could define properties of schema in order you want get parsing msgs.

```typescript
import zod, { ZodError } from 'zod';

const response = {
    name: 1234,
    id: '',
}

const schema = zod.object({
    name: zod.string(),
    id: zod.number(),
});

try {
    schema.parse(response)
} catch(e) {
    if (e instanceof ZodError) {
        const formattedError = e.format();
        console.log(formattedError)
    }
}

// log: 
{
  _errors: [],
  name: { _errors: [ 'Expected string, received number' ] },
  id: { _errors: [ 'Expected number, received string' ] }
}
```

I hope it helped

**Comment by ElYaiko** [comment]
> I think it is matter of formatting error and getting first error from error array. By this snippet if you change order of schema fields it will influence on order of error msgs. That means you could define properties of schema in order you want get parsing msgs.
> 
> ```ts
> import zod, { ZodError } from 'zod';
> 
> const response = {
>     name: 1234,
>     id: '',
> }
> 
> const schema = zod.object({
>     name: zod.string(),
>     id: zod.number(),
> });
> 
> try {
>     schema.parse(response)
> } catch(e) {
>     if (e instanceof ZodError) {
>         const formattedError = e.format();
>         console.log(formattedError)
>     }
> }
> 
> // log: 
> {
>   _errors: [],
>   name: { _errors: [ 'Expected string, received number' ] },
>   id: { _errors: [ 'Expected number, received string' ] }
> }
> ```
> 
> I hope it helped

I understand but what I’m trying to do is that If I have for example:

```
const schema = z.object({
  …
  name: z.string().min(3).refine(async val => {
    …
    if(apiCall){
      …
      return true;
    }
  })
});
```

And the `min()` returns error, it will run the api rule anyways, I’m trying that if the `min()` has an error, don’t run to the other rules, so as a errors log I would get something like:

```
{
   _errors: [],
  name: { _error: ‘Invalid min value’ }’
  …
}
```

Is this possible to do?, Thanks.

**Comment by ElYaiko** [comment]
Sorry, closed by mistake _\

**Comment by DanielBreiner** [comment]
It is possible, but you need to implement the `min` yourself using `superRefine`.
https://github.com/colinhacks/zod#abort-early

```js
const schemaA = z.object({
  name: z
    .string()
    .min(3)
    .refine(async (val) => {
      if (true /* API call */) {
        return false;
      }
    }, "Invalidated by API call."),
});
const schemaB = z.object({
  name: z
    .string()
    .superRefine((val, ctx) => {
      if (val.length <= 3)
        ctx.addIssue({
          code: z.ZodIssueCode.too_small,
          inclusive: true,
          minimum: 3,
          type: "string",
          fatal: true, // <-- this prevents further validation
        });
    })
    .refine(async (val) => {
      if (true /* API call */) {
        return false;
      }
    }, "Invalidated by API call."),
});
const input = { name: "a" };
const resultA = await schemaA.safeParseAsync(input);
const resultB = await schemaB.safeParseAsync(input);
console.log(!resultA.success && resultA.error.issues);
console.log(!resultB.success && resultB.error.issues);
```
```
[
  {
    code: 'too_small',
    minimum: 3,
    type: 'string',
    inclusive: true,
    message: 'String must contain at least 3 character(s)',
    path: [ 'name' ]
  },
  {
    code: 'custom',
    message: 'Invalidated by API call.',
    path: [ 'name' ]
  }
]

[
  {
    code: 'too_small',
    inclusive: true,
    minimum: 3,
    type: 'string',
    fatal: true,
    path: [ 'name' ],
    message: 'String must contain at least 3 character(s)'
  }
]
```
