### ISSUE TITLE
ZodFormattedError does not propagate the custom error format to recursive fields

### ISSUE THREAD

**Issue by carlgieringer** [colinhacks/zod#1616]
`ZodFormattedError` accepts two type params. 

```ts
export type ZodFormattedError<T, U = string>
```

`T` is the type of the input schema and `U` is the type of each error entry. `U` is important when [providing a custom issue mapper](https://github.com/colinhacks/zod/blob/0c4fc53239e89b4349559c7cdb4bc50c5442ab49/src/ZodError.ts#L204). `ZodFormattedError` uses `T` to define the shape of the formatted error object, but it does not propagate `U` to the fields of this object. E.g.:

```ts
... ZodFormattedError<NonNullable<T>[K]>
```

This means that typing fails when trying to access custom error types of a `ZodFormattedError.

Example: the following code should pass typechecking [sandbox](https://codesandbox.io/s/typescript-playground-export-forked-f7llzb?file=/index.ts:0-310):

```ts
import { z } from "zod";

const Thing = z.object({
  name: z.string().min(2)
});

const result = Thing.safeParse({ name: "a" });
if (!result.success) {
  const formatted = result.error.format((issue) => ({
    code: issue.code,
    message: issue.message
  }));
  console.log(formatted.name?._errors?.code);
}
```

But instead it fails with `Property 'code' does not exist on type 'string[]'.ts(2339)'

**Comment by carlgieringer** [comment]
Hi, this issue has a simple fix, as presented in #1617.

**Comment by carlgieringer** [comment]
@colinhacks Hi, should I do anything in particular to have the PR for this issue reviewed? Thanks!

**Comment by JacobWeisenburger** [comment]
sometimes you just need to be a squeaky wheel. :D

I approved and merged it

**Comment by carlgieringer** [comment]
I wasn't sure how squeaky I should be. Thanks, @JacobWeisenburger!

**Comment by colinhacks** [comment]
@carlgieringer Unfortunately this has been reverted in 3.21 for causing infinite recursion & compiler slowdowns. It's possible this can be re-implemented in a way that avoids these issues (*maybe*) but I had to put out a fix asap and didn't have time to look into it.

**Comment by carlgieringer** [comment]
@colinhacks too bad! Was there an error report that would help me repro? I didn't encounter that issue, so I'm not sure how to validate the correctness of a re-implementation.

**Comment by romellem** [comment]
I know this is an old issue / thread, but if anyone has time, could they explain what the actual "recursive type" issue was? As [mentioned](https://stackoverflow.com/questions/74881472/slow-typescript-autocompletion-in-vs-code-for-zod), since it is just a "6 character change," it is hard to understand how that was able to have such a large performance impact
