### ISSUE TITLE
Better localisation support

### ISSUE THREAD

**Issue by yanickrochon** [colinhacks/zod#1622]
The ability to localize error messages should be made easier. For example, the default mapping make use of `util` in `../helpers/util` which does not seem to be exported.

Are localised errors a planned feature? If so, then `src/errors.ts` will have to export them externally (i.e. make them available). There is also the question of using [ISO-639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) with or without region names?

**Comment by JacobWeisenburger** [comment]
Has this issue been resolved? If so, I'd like to close this issue.
