### ISSUE TITLE
[Feature Request]: zod2 access to refinementData

### ISSUE THREAD

**Issue by tmtron** [colinhacks/zod#163]
in zod2 there's no way anymore to access the refinementData.  

This can be very convenient when we want to reuse the info to display hints in the GUI (e.g. _The password must have between 5 and 10 characters_, ..)

We could simply add the refinement data as a property to the check function: e.g. in `base.ts`: 

```ts
refinement = (
    check: (arg: Output) => any,
    refinementData: MakeErrorData | ((arg: Output) => MakeErrorData),
  ) => {
    const augmentedCheck = (val, ctx) => {
      if (!check(val)) {
        ctx.addError(
          typeof refinementData === 'function'
            ? refinementData(val)
            : refinementData,
        );
      }
    };
    augmentedCheck.refinementData = refinementData;
    return this._refinement(augmentedCheck);
  };
```

Then we can simply loop over all `ZodTypeDef.checks` and check the `refinementData` property is set

**Comment by vriad** [comment]
Custom error maps are the way to implement logic like this, check out the [Error Handling guide](https://github.com/vriad/zod/blob/master/ERROR_HANDLING.md) for details on that.

**Comment by tmtron** [comment]
I don't think custom error maps are useful in this case. I am happy with the individual error-messages.
What I want is to get a meaningful description of what the user should input, This should be displayed *before* they even enter a value.  

Example:  
* `temp = z.number().int().min(-10).max(30)`
* When the form is shown, I want to display: "Enter an integer between -10 and 20"

So you suggest that I first check which type it is (string, number, etc.) and per type pass all possibly invalid values to `safeParse()` before I show the form?

e.g. when a field is an integer, execute ALL of these:
* `temp.safeParse(Number.MIN_VALUE)` to check for a minimum
* `temp.safeParse(Number.MAX_VALUE)` to check for a the maximum
* `temp.safeParse(3.14)` to check for integer

Then what should we pass for strings to check the max. length??

Sounds like a very bad idea to me - compared to just looping over the refinements directly...

**Comment by shrugs** [comment]
based on my reading of https://github.com/vriad/zod/issues/76#issuecomment-673271898, when it comes to generating forms, it might be best to do something closer to

```ts
const MIN_LEN = -10;
const MAX_LEN = 30;

const schema = zod.object({
  myNumber: z.number().int().min(MIN_LEN).max(MAX_LEN)
})

const MY_FORM = {
  metadata: {
    myNumber: {
      helpText: `Enter an integer between ${MIN_LEN} and ${MAX_LEN}`,
      minLength: MIN_LEN,
      maxLength: MAX_LEN
    }
  },
  schema,
}
```

and then the form can use those values like 


```
const { metadta } = MY_FORM;

// ... for name in schema shape ...
<input type="number" name={name} min={metadata[name].minLength} max={metadata[name].maxLength} />
<p>{metadata[name].helpText}</p>
```

This way the static metadata is wrapping the schema, rather than the other way around.

**Comment by tmtron** [comment]
As pointed out here in https://github.com/vriad/zod/issues/138#issuecomment-685433879 this approach causes a lot of code-duplication and a maintenance nightmare.

**Code-duplication**

Even in a mid-sized business app, that has only 20 entities with 10 properties each, that would mean to have 20 redundant meta-objects with, a total of 200 redundant meta-fields plus 200 input definitions in HTML and many more constants.  
There is no need for this redundant code. It does not add any additional value. All the information is already defined on the zod object, so we can simply loop over the zod-fields and generate the meta-data and HTML form.  
Even a default `helpText` can easily be generated and tweaked per use case: e.g. different messages when the field has min/max or both.

**Maintenance**

In many apps you will have a frontend (e.g. react or angular), some shared typescript code and a node-backend.
The zod definition will be in shared code and can be used by the frontend and the backend.  
Now if someone of the backend development team adds a new validation (e.g. the field just had `min` and now they add `max`), it is possible (even likely) that they forget to update the metadata or form.

**Comment by vriad** [comment]
I don't like this solution because of this part: 

> we can simply loop over the zod-fields and generate the meta-data and HTML form

If you're looping over the fields of a Zod object schema to generate your form, you don't have any type information about the metadata available on each one. To use your example:

```ts
const userSchema = z.object({
  firstName: z.string()
    .min(5)
    .max(25)
    .nonempty()
    .meta({
      description: ' the users first name',
    }),
  name: z.string()
    .min(5)
    .max(25)
    .nonempty()
    .meta({
      description: 'the users name',
    }),
});

// Component.jsx
{ Object.keys(userSchema.shape).map(key => {
  const fieldSchema = userSchema.shape[key];
  // fieldSchema has virtually no type information inside this loop
}) }
```

Since you don't have type information there, I personally find this to be an anti-pattern that I don't want to encourage. Which is why I recommend writing a higher-level wrapper that stores your form field metadata like I suggest here: https://github.com/vriad/zod/issues/76#issuecomment-673271898. Better yet, the

There is some redundancy unfortunately. You can eliminate a lot of it by fleshing out the simple `ZodForm` class I proposed. Below is an example of how that would work:

```ts
import * as z from '.';

type MyFormInput<Key extends string = string> = {
  type: 'string' | 'number' | 'checkbox' | 'select';
  key: Key;
  label: string;
  placeholder: string;
  validator?: z.ZodSchema<unknown>;
};

class ZodForm<Inputs extends [...MyFormInput<any>[]] = []> {
  inputs: Inputs;
  constructor(inputs: Inputs) {
    this.inputs = inputs;
  }

  input = <Input extends MyFormInput>(
    input: Input,
  ): ZodForm<[...Inputs, Input]> => {
    return new ZodForm([...this.inputs, input]);
  };

  string = <Input extends Omit<MyFormInput, 'type'>>(
    input: Input,
  ): ZodForm<[...Inputs, MyFormInput<Input['key']>]> => {
    return new ZodForm([
      ...this.inputs,
      { type: 'string', validator: z.string(), ...input },
    ] as any);
  };
}
```

I have a lot of ideas around typesafe form definition but in the end, the best thing is to define your own TypeScript data structures that store the exact pieces of metadata you like. 
I would love if you (or anyone) built a form definition library on top of Zod since it's such a common use case. I have lots of ideas about how to build/define forms in a typesafe way. I've also tried to do this   I have lots of ideas regarding this @tmtron  I think expanding the `ZodForm` example into a more comprehensive form definition library would be extremely cool, and is the best way to solve your problem.

**Comment by tmtron** [comment]
>If you're looping over the fields of a Zod object schema to generate your form, you don't have any type information about the metadata available on each one.

Not sure what you mean. I have all type information and the loop just has to handle the different types, e.g.

```typescript
function foo(zodType: ZodType<any>) {
  const zodTypeDef = zodType._def.t;

  switch (zodTypeDef) {
    case ZodTypes.string:
      return handleString(zodType as ZodString);
    case ZodTypes.number:
      return handleNumber(zodType as ZodNumber);
    case ZodTypes.object:
      return handleObject(ctx, zodType as ZodObject<any>, keepExample);
    // etc..
}
```
There are some special cases to handle (like null, optional, etc.), but that is totally manageable.  
The only thing that is currently not available is the refinement-data. And this is because zod just swallows that valuable information for no apparent reason.

>I recommend writing a higher-level wrapper that stores your form field metadata

Zod already stores my meta-data (min/max, ..) and zod is type-safe (i.e. only string can have a regex validation). So why should I spend a lot of work to duplicate what is already there? And most of all: it does not solve the original issue:

> `temp = z.number().int().min(-10).max(30)`
> When the form is shown, I want to display: "Enter an integer between -10 and 20"

In your example the refinement data will still be hidden by zod and not be accessible.  
e.g. when you pass `z.string().min(2).max(5)` as `input`, then there is still no way to get the min/max values. You have to either extract them to constants or have duplication in the definition and the placeholder.

**Comment by kbkk** [comment]
Is there a way to access the refinement data in v3 @colinhacks?

If not, are there any obstacles to having it?
