### ISSUE TITLE
Type inference with `.default()` isn't telling the right thing

### ISSUE THREAD

**Issue by zihan-ch** [colinhacks/zod#1633]
If we have a Zod type:
```ts
const ExampleZod = z.number().default(0)
type Example = z.infer<typeof ExampleZod>
```

The type of Example is `number` but not `number | undefined`.

It already has a default value, why is it still required?

**Comment by amritk** [comment]
I just came across the same thing, did you figure it out?

**Comment by stockson** [comment]
I'm having the same issue "zod": "^3.20.2"

```typescript
const schema = object({
	foo: string().default("bar")
})
type SchemaType = z.infer< typeof schema >

// SchemaType is (vscode)
type SchemaType = {
    foo: string;
}
// workaround I'm using:
string().default("bar").optional() // however optional().default() doesn't work
```

**Comment by amritk** [comment]
@stockson try
`type` SchemaType = z.input< typeof schema >

**Comment by zihan-ch** [comment]
> I'm having the same issue "zod": "^3.20.2"
> 
> ```ts
> const schema = object({
> 	foo: string().default("bar")
> })
> type SchemaType = z.infer< typeof schema >
> 
> // SchemaType is (vscode)
> type SchemaType = {
>     foo: string;
> }
> // workaround I'm using:
> string().default("bar").optional() // however optional().default() doesn't work
> ```

z.infer is an alias of z.output

https://zod.dev/?id=type-inference

**Comment by stockson** [comment]
Got it, thank you @zihan-ch & @amritk !
