### ISSUE TITLE
[Bug]Error validate email

### ISSUE THREAD

**Issue by linhnvg** [colinhacks/zod#1638]
- I use zod and react-hook-form when I validate emails but adding a dash at the end doesn't trigger the error

- I tried using emailRegex in zod doc but no error trigger

- I'm wondering if the problem is there or not?

- I tried with yup and got the trigger error

```
import { useCallback, VFC } from "react";
import { SubmitHandler, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";

const auth = z.object({
  email: z
    .string()
    .email("正しいメールアドレスの形式で入力してください"),
  password: z.string()
});


const user = z.object({
  firstName: z
    .string()
    .min(1, { message: "1文字以上入力してください" })
    .max(10, { message: "10文字以下で入力してください" }),
  lastName: z
    .string()
    .min(1, { message: "1文字以上入力してください" })
    .max(10, { message: "10文字以下で入力してください" }),
  phoneNumber: z.string().regex(/^0\d{9,10}$/, {
    message: "正しい電話番号の形式で入力してください"
  }),
  role: z.enum(["admin", "user"])
});
```
![image](https://user-images.githubusercontent.com/39109300/205795003-f7fcd40f-0524-4714-9226-e664d4e4a938.png)

![image](https://user-images.githubusercontent.com/39109300/205794262-5b0b6c51-6ecf-4bfe-a500-a443cbc4ce8d.png)

![image](https://user-images.githubusercontent.com/39109300/205794327-b13a71ff-e8f0-4df6-8fae-7238d4b54a6e.png)

**Comment by powerfulyang** [comment]
Can you paste your codesanbox url directly? 
+ Do you register zodResolver?
+ You need to handle formState errors yourself.
```js
const schema = z.object({
  email: z
    .string()
    .email("error message")
});
```
```js
const {
    register,
    handleSubmit,
    reset,
    formState: { errors }
  } = useForm({
    resolver: zodResolver(schema)
  });
```
```jsx
{errors.email?.message && <span>{errors.email?.message}</span>}
```

**Comment by colinhacks** [comment]
I recommend using `.regex()` to use your preferred email validator. There are a lot of opinion's on what should be considered a valid email and Zod uses a fairly liberal regex intentionally.

**Comment by simPod** [comment]
But we should revert https://github.com/colinhacks/zod/pull/1648 until there's a solution found since it silently breaks apps for safari users.
