### ISSUE TITLE
Schema introspection of optional or required fields

### ISSUE THREAD

**Issue by dominikspiertz** [colinhacks/zod#1643]
Hello to everybody,
I am building my forms with zod as a validation solution. Currently I am struggling with finding out, if a field inside an object is required or not. I use this, to display the red asterisk next to a form field so that my schema definition from zod is used for the display and always in sync with the user interface. I have been using the following snippet which has worked out so far:

```ts
const isRequired = (name, schema) => !schema._def.shape()[name]?.isOptional(),
```

This introspects the schema deeper in the tree of my components and checks if inside the `_def.shape()` object there is a field with `name` that is not optional. 

Right now I have a more complex form approach where I am using `superRefine` to manually add issues for a field to be required so this approach doesn't work:

```ts
const schema = z.object({
  attendeeType: z.nativeEnum(AttendeeType),
  company: z.string().optional(),
}).superRefine(({ attendeeType, company }, { addIssue }) => {
  if (attendeeType === AttendeeType.BUSINESS && !company) {
    addIssue({
      code: TOO_SMALL, 
      inclusive: true,
      minimum: 1,
      path: ['company'], 
      type: 'string' 
    })
  }
})
```

Has someone an idea how I get this information for all cases?

**Comment by maxArturo** [comment]
Hi @dominikspiertz ! 

I think the naive approach for your scenario would be to recursively traverse the `_def` for each of your `ZodType`s, depending on how many `refinement`s and `superRefine`s you call, till you reach your first `instanceof ZodObject` class. Then you can continue calling the same method you were previously. 

Keep in mind, every time you call `x.refine()` or `x.superRefine()` you're wrapping your schema within a `ZodEffects` class (this is true for preprocessing as well I believe). You would have to do this:

```ts
  const AppComponent = z
    .object({ test: z.object({ first: z.literal("yes") }) })
    .superRefine((t) => t.test) // suppose this is valid
    .refine((t) => t.test.first);

  const innerObj = AppComponent.sourceType().sourceType()._def.shape();

```
so that involves checking each iteration for `ZodObject`. Its clunky but it will get your issue resolved. 

> Has someone an idea how I get this information for all cases?
If by this you mean "extract the innermost object schemas from all possible Zod types" then you'd have to look at each implementation, as some interfaces (but not all) expose their schema (some, like optional/nullable expose the `innerType` method). 

Unfortunately building zod-controlled forms seems like a special use case and you'd have to check that all your use cases are considered. Perhaps this is a candidate for a NPM package!

**Comment by micah-redwood** [comment]
> Unfortunately building zod-controlled forms seems like a special use case and you'd have to check that all your use cases are considered. Perhaps this is a candidate for a NPM package!

Hey @dominikspiertz , you're not the only one trying to use Zod for form validation (in my case React Hook Form), and finding a lot of pain points. If you do release a package, I would be happy to use it and give you feedback.

**Comment by maxArturo** [comment]
@dominikspiertz glad to hear you found a solution! If you're set, do you mind closing the issue? Thank you! 🙏

**Comment by maxArturo** [comment]
> Still this very inner type has the .optional() property, so calling .isOptional() still returns true, since it does not pick up the effects from zod in my case. Am I missing something? Does .sourceType() work different?

@dominikspiertz `sourceType()` "pulls out" the inner validator from the effects, so its a quality of life over `innerType()`:

```ts
  sourceType(): T {
    return this._def.schema._def.typeName === ZodFirstPartyTypeKind.ZodEffects
      ? (this._def.schema as unknown as ZodEffects<T>).sourceType()
      : (this._def.schema as T);
  }
```
Also, `optional()` is defined for all schemas so everything will have `.optional()` unfortunately. Feel free to do this instead (I tried it out locally and it _should_ work for arbitrary levels of nesting of `.refine()`: 

```ts
import { z, ZodEffects, ZodObject } from "./src";

const AppComponent = z
  .object({
    first: z.literal("yes").optional(),
    second: z.literal(33),
  })
  .superRefine((t, ctx) => {
    if (!t.first) {
      ctx.addIssue({ message: "error here", code: "custom" });
    }
  })
  .refine((t) => t.second)
  .refine((t) => t.second)
  .refine((t) => t.second)
  .refine((t) => t.second)
  .refine((t) => t.second)
  .refine((t) => t.second);

console.log("first", isRequired("first", AppComponent)); // false 
console.log("second", isRequired("second", AppComponent)); // true

function isRequired(name: string, schema: ZodEffects<any> | ZodObject<any>) {
  if (schema instanceof ZodEffects) {
    return isRequired(name, schema.sourceType());
  }

  const shape = schema._def.shape();
  const element = shape[name];
  return !element.isOptional();
}
```

Just keep in mind that if your innermost `ZodObject` has nested attributes, you'll have to make sure to traverse those yourself at the end. And if this helps solve your issue, please feel free to close it. Thanks!

**Comment by JacobWeisenburger** [comment]
@dominikspiertz 
Is the above answer satisfactory? Or do you have any questions?

I'd like to close this issue if there are no further questions.
