### ISSUE TITLE
Recursive type with discriminated union

### ISSUE THREAD

**Issue by tomaszferens** [colinhacks/zod#1644]
Hey 👋

How to transform this recursive discriminated union to zod?

```ts
interface TextInput {
  type: 'text-input';
}

interface Group {
  type: 'group';
  components: AppComponent[];
}

type AppComponent = TextInput | Group;
```

what would the zod version look like?

My attempt:

```ts
import { z } from 'zod';

const TextInputSchema = z.object({
    type: z.literal('text-input'),
});

const GroupSchema = z.object({
    type: z.literal('group'),
    components: z.array(ComponentSchema),
});

const ComponentSchema = z.discriminatedUnion('type', [TextInputSchema, GroupSchema]);

```

but that doesn't work due to the error that `[...] type is referenced directly or indirectly in its own initializer`.

**Comment by maxArturo** [comment]
Take a look at the [recursive types](https://github.com/colinhacks/zod#recursive-types). 
Something like this might work for you: 

```ts
type TextInput = {
    type: "text-input";
  };

  type Group = {
    type: "group";
    components: AppComponent[];
  };

  type AppComponent = TextInput | Group;

  const AppComponent: z.ZodType<AppComponent> = z.lazy(() => {
    return z.union([
      z.object({ type: z.literal("text-input") }),
      z.object({
        type: z.literal("group"),
        components: z.array(AppComponent),
      }),
    ]);
  });

  const component = {
    type: "group",
    components: [
      {
        type: "text-input",
      },
    ],
  };

  AppComponent.parse(component);
  console.log("success");
```

[playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwCwAUNXHDAJ5gCmcAKswB4wCSAdmACu8ALyJadek2YAuAjC4wAtMAHDyEtJRpU6jFnADiOQWDhiEEvdLn4A5ibAbdkgMa5IfZnxgBnOQCCYGAAwh4QXj4A2gC62nRa1BL6rEGh4ZGi7Ir8QvAAPkaO2hLufL7waWHgEd4wcsgAdABaJGzSADxVGXUAfOYojQA2AIbIDAAUEwCU5v2WLnRQzDCCUHyDgnzAERNRVpJNEABGAFbMrjATSCkNw8AKUCNDE-gK3CpqMPizaNMANAc6EczhcrgtJJCpCw7kMHswni97I4foDFlD3DVMv5BiMoE9Jt0sXUAUD0KT0TFpvFySUXGUKnBMZ46gMIZJbgQHBBTPg0ZDmbUfDj9ui6OyodDZPJFJ88nyyWh+ZIYsrEjo6ESWT5GmA8b5mBNBZlqaUIr4IENmMMIHZXr5BK5XMxfL4fmQgA)

**Comment by tomaszferens** [comment]
@maxArturo thank you! Do I need to duplicate all of the types tho? 😔

**Comment by maxArturo** [comment]
Hi @tomaszferens do you mean duplicating the type declaration, as well as the zod validator? If so, it seems to be an inherent limitation (nothing to do with Zod itself). I myself haven't looked into it deeply, but that seems to be the case for now.

**Comment by colinhacks** [comment]
Yes, you can't declare recursive types without the "manual" type declaration. This is a TypeScript limitation.
