### ISSUE TITLE
Match one or more schemas

### ISSUE THREAD

**Issue by chriskuech** [colinhacks/zod#1654]
`.union`/`.or` will match against each schema in order and return the first match. However, I want to match one _or more_ schemas. There currently does not seem to be a way to do that with Zod.

**Comment by santosmarco-caribou** [comment]
> `.union`/`.or` will match against each schema in order and return the first match. However, I want to match one _or more_ schemas. There currently does not seem to be a way to do that with Zod.

Hi @chriskuech, can you post an usage example?

At what circumstances would this be useful?

Thanks.

**Comment by chriskuech** [comment]
I think this was maybe a symptom of a bad initial design.
