### ISSUE TITLE
Is there a validation type for zod types themselves?

### ISSUE THREAD

**Issue by yulolimum** [colinhacks/zod#1656]
First of all, thank you for your work - great library!

Say I need to parse/validate an object where certain values need to be a zod schema type. Example:

```
const Schema = z.object({
  name: z.optional(z.string()),
  description: z.optional(z.string()),
  schema: z.optional(
    z.record(
      z.union([
        // z.zodStringType(),
        // z.zodNumberType(),
        // z.zodBooleanType(),
      ])
    )
  ),
});

function parseSchema(schema: Schema) {
  return Schema.safeParse(schema);
}

parseSchema({
  name: "User Schema",
  description: "This is a user schema.",
  schema: z.object({ firstName: z.string(), lastName: z.string() }),
});
```

Is there a built in way to achieve something like this?

**Comment by maxArturo** [comment]
Hi @yulolimum 

I don’t think there’s a “built in” way to accomplish this. However, It seems to me the easiest way to start on this would be to refine an `any` validator so that you can add your own checks via `instanceof`: 

```ts

const Schema = z
    .object({
      name: z.optional(z.string()),
      description: z.optional(z.string()),
      schema: z.optional(z.any()),
    })
    .refine((el) => el.schema instanceof ZodType, "This isn't a valid schema");

  Schema.parse({
    name: "User Schema",
    description: "This is a user schema.",
    schema: z.null(),
  });

```

From there, you can start further refining the validation to match your particular desired shape. This could get clunky if you are looking for optional, recursive or specific shapes, but at least it allows you to accomplish your objective.

**Comment by yulolimum** [comment]
@maxArturo 
Thank you! You got me thinking about this a bit differently.
I think I can get away with this validation: 
```
{
...
schema: z.optional(z.instanceof(z.ZodObject))
}
```
Using object type since it packs the most functionality for the end user to customize. I can then do a secondary validation for the values of the object. 

Closing, since this resolve my question. Thanks again!

**Comment by yulolimum** [comment]
Just adding to this incase people run into this:

If you are doing what I'm doing - defining a schema that validates for zod types - the references to the class in both the schema and the input need to come from the same dependency. Not sure if this is related to esbuild, or transpilers, or scope, or monorepo.

If your schema is defined in "package-a" (with zod as dep) and someone using your package in their own "package-b" has their own version or install of zod, the parsing fails. My tests inside "package-a" were passing, but the implementation started failing when I integrated the package in another. 

My "fix" for this was to do something like: 

```
{
...
schema: z.optional(z.function().args(z.custom<{zod: typeof z}>().returns(z.instanceof(z.ZodObject))))
}
```

and someone would use it like so: 
```
const input = (zod) => zod.object({}).passthrough()
```
