### ISSUE TITLE
date validation optional not working

### ISSUE THREAD

**Issue by rayanazzam1991** [colinhacks/zod#1671]
Hello i am trying to validate date but i want it optional that means if the user enter a date then validate it but if he/she left it with no value i don't want to validate it.
`birth_date: zod.date().optional(),`
that's not worked for me

**Comment by finaloop-igal** [comment]
Hey 👋🏻 

What errors are you getting?

**Comment by igalklebanov** [comment]
Hey 👋 

What errors are you getting?

**Comment by colinhacks** [comment]
Can't replicate, this is working for me.

```ts
const schema = z.object({
  birth_date: z.date().optional(),
});

schema.parse({});
```


My guess is that the form is returning a default value of `""` when no input is entered into the form. There's a few ways to handle this:

```ts
const schema = z.object({
  birth_date: z.date().optional().catch(undefined),  // any error will cause `undefined` to be returned
  birth_date: z.preprocess(val => val === "" ? undefined : val, z.date().optional()) // convert empty string to undefined with preprocess
})
```
