### ISSUE TITLE
Unexpected `z.coerce.boolean()` result with "false"

### ISSUE THREAD

**Issue by WORMSS** [colinhacks/zod#1672]
Yes, yes, it makes sense that what you are doing under the hood is `Boolean("whatever")` and that means `Boolean("false")` equates to true... 

But I believe this is a silly enough gotcha that it is worth to note in the docs.. 
Or even if there was a `z.coerce.boolean({ treatStringFalseAsFalse: true })` 

I just don't want people to get confused.. 

```ts
Number(String(123)) === 123 // makes sense
Boolean(String(false)) !== false // will be a head scratcher at first glance
```

**Comment by colinhacks** [comment]
Good call, just added some docs to this effect. This decision is discussed in slightly more detail at https://github.com/colinhacks/zod/issues/1630

**Comment by JacobWeisenburger** [comment]
Has this been addressed?

If so, can I close this issue?
