### ISSUE TITLE
[Date] Parsing of DateOnly strings

### ISSUE THREAD

**Issue by KennethHoff** [colinhacks/zod#1676]
3.20 introduced `z.string().DateTime()` for cleaner string->DateTime parsing. However, it only supports strings containing both Date _and_ Time

An API I'm working with includes only the Date part (today would be `2022-12-12`). This API is written in C# using the [DateOnly](https://learn.microsoft.com/en-us/dotnet/api/system.dateonly?view=net-7.0) struct.

The built-in JavaScript `new Date(<string>)` does work with DateOnly strings, so I don't see a huge reason not to support it as well. I don't know what the API for it would be though, but the two most obvious ones that I could think of are the following:

1. An additional option in the `string().DateTime()` function: `dateOnly: boolean`
2. A separate `string().Date()` function (or `string().DateOnly()`)

(As an aside, C# also has a [TimeOnly](https://learn.microsoft.com/en-us/dotnet/api/system.timeonly?view=net-7.0) struct, but I don't really see how that would be parseable into a JavaScript primitive)

**Comment by igalklebanov** [comment]
> I'm in favor of adding `.date()` and `.time()` methods for convenience.

Can I take a shot at these?

**Comment by JacobWeisenburger** [comment]
> Can I take a shot at these?

If you're asking for permission to submit a PR, please do. PRs are always welcome. Thanks.

**Comment by igalklebanov** [comment]
Not stale bro..

**Comment by igalklebanov** [comment]
Not stale bro.

**Comment by KrisBierma** [comment]
Any update on this?
