### ISSUE TITLE
v3.20 and v3.20.1 breaks my app for some reason

### ISSUE THREAD

**Issue by steida** [colinhacks/zod#1679]
Probably something (a regex?) iOS can't handle.

<img width="483" alt="Screenshot 2022-12-12 at 21 39 10" src="https://user-images.githubusercontent.com/66249/207149660-56fea993-66b7-4736-ad94-51e8ceee540d.png">

**Comment by jokull** [comment]
Yes, an improved regex for emails was introduced. It probably needs to be rolled back.

**Comment by colinhacks** [comment]
Reverted the change that causes this, upgrade to 3.20.2 to fix!
