### ISSUE TITLE
zod url fails when having port number and field/value pairs

### ISSUE THREAD

**Issue by JacobWeisenburger** [colinhacks/zod#1687]
### Discussed in https://github.com/colinhacks/zod/discussions/1479

<div type='discussions-op-text'>

<sup>Originally posted by **RicardoValero95** October 11, 2022</sup>
This url works fine
`"sqlserver://database-test.amazonaws.com;database=x;user=y;password=z;trustServerCertificate=true"`

But this doesn't
`"sqlserver://192.168.100.10:1433;database=x;user=y;password=z;trustServerCertificate=true"`

</div>

**Comment by igalklebanov** [comment]
If native `URL` doesn't think it is a valid url, should zod step in and have an opinion on this?

Just trying to align myself, don't take it as me questioning the validity of the issue/bug..

**Comment by colinhacks** [comment]
I'm opposed to changing from the existing implementation that uses `URL` - Zod should fall back on JavaScript built-ins whenever possible imo

**Comment by JacobWeisenburger** [comment]
@colinhacks thanks for the quick response. I know you are busy.
