### ISSUE TITLE
required should remove defaults

### ISSUE THREAD

**Issue by mwisnicki** [colinhacks/zod#1690]
At the moment required only removes optionality rather than defaults.
This leads to somewhat nonintuitive behavior:

```ts
const t = z.object({ foo: z.string().default("") });  // foo is optional in input
const t2 = z.required({ foo: true }); // foo is still optional in input
t2.parse({}); // is ok but shouldn't
```

**Comment by colinhacks** [comment]
It's true. Zod is going to have to implement a `ZodRequired` subtype so `.required()` behaves more reasonably. Hopefully next version.

**Comment by santosmarco-caribou** [comment]
👋 I went ahead and opened a PR for `ZodRequired`. https://github.com/colinhacks/zod/pull/1738

Feel free to leave your comments and sincere feedback.
