### ISSUE TITLE
Feature Request: pattern properties in `z.object({})`

### ISSUE THREAD

**Issue by robdasilva** [colinhacks/zod#1692]
JSON schema provides the possibility to define a regex that is tested against property names. If it matches, the respective property needs to fit the defined schema.

If I understand correctly, such functionality could already be implemented in `zod` using a refinement. However, I think, it would be beneficial to have this kind of functionality without the need for custom logic. That is, because then tooling built on top of `zod` could translate these requirements in a standardized way, e.g. JSON schema as mentioned above.

Proposal:
```typescript
const CustomProperty = z.string()

const objectWithPatternProperties = z.object({}).setKeyPattern(/^x-[a-z-]+$/, CustomProperty)
```

Haven't contributed to `sod` yet, but I'd be happy to give it a try myself :)

**Comment by igalklebanov** [comment]
Hey 👋

Why is `z.record` not suitable for your use case?

**Comment by robdasilva** [comment]
Wow, I think I read the docs three times. However, that one seems to have slipped through...

Thanks for pointing me there, @igalklebanov!
