### ISSUE TITLE
Is it normal that a Tuple is valid if a value is empty ? 

### ISSUE THREAD

**Issue by nmeuni** [colinhacks/zod#1693]
[Zod v.3.20.2]

Hello, I'm a in use case where I can have tuple like that: `[<1 empty>, "toto"]`
In this case the safeParse method return a success with `["toto"]` in `result.data`. Is this the expected behavior ?
I found no "simple" way to make the parser return an error. (Maybe by using .refine or by creating a custom rule)

Code to reproduce in RunKit
```ts
  var z = require("zod")
  
  const test = []
  
  test[1] = "toto"
  
  const ZodTupleTest = z.tuple([z.number(), z.string()]);
  
  ZodTupleTest.safeParse(test)
```

That said, it's a very usefull lib ;)

**Comment by JacobWeisenburger** [comment]
It looks like there was a merged PR fixing this. Can I close this issue?
