### ISSUE TITLE
Feature Request: Context Data for custom validations

### ISSUE THREAD

**Issue by softwarerero** [colinhacks/zod#1696]
It would be great if custom validations with refine or superRefine could access data that is given as a parameter to parse, parseAsync, safeParse or safeParseAsync.

Joi for example allows to give a context object as a second parameter to its validate function which then can be evaluated in custom rules.

**Comment by colinhacks** [comment]
Discussed extensively elsewhere: #84 #148

**Comment by fkrauthan** [comment]
I know this is currently closed but I would also love some way to pass context information to custom validators. For example, I want to validate duplicates but exclude the current object id (currently I have to add `id` as a field to my schema and then have to remove it again when saving the data in the database). Or for example, my validation might have stricter rules if it is an admin user vs a regular user.

Right now it seems like the only way is to add them to the actual schema, pass the data in and then remove it again from the schema before processing the safeParsed data (defeating slightly the idea behind safe parse in my opinion)

**Comment by jotatoledo** [comment]
The lack of this feature was a deal breaker - had to replace it with yup, which offers this function,  and refactor.
Would be nice to see sometime in the future.

**Comment by palerdot** [comment]
There are lot of valid use cases where we would need some kind of external data/context to validate our form against. For example, even a simple use case for email validation to prevent spammy domains, something like
```typescript
const schema = z.object(schemaDetails)
 .context({
    validEmailDomains: ["google.com", "gmail.com"]
  })

// or dynamically set data
schema.setContext(validEmailDomains: <DYNAMIC DATA FROM SERVER>)

// and use that in refine/superrefine
.superRefine((data, context) => {
   // we should be able to access this in our context
  const validDomains = context.validEmailDomains
})
```

I also think validation is not a 'pure function' when done this way is not the right way to look at this problem. We had a similar use case and we have to push the validation outside of the zod schema. This kind of defeats the purpose of schema validation. I hope zod team reconsiders their decision to not to support user-provided context data for `refine/superRefine`

**Comment by inoguez** [comment]
We need this!
