### ISSUE TITLE
How to write a tuple with spread type?

### ISSUE THREAD

**Issue by Newbie012** [colinhacks/zod#1701]
In TypeScript, you would write:

```typescript
type A = ["A", ...string[]];
```

How would you define that type definition using Zod?

[Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBALzgMyhEcBECIBNMDcAUDAJ5gCmcAggM60WwCiAjgK4CGANgDzUA0cAEIA+OAF4acCgA8YFAHa5awuAH44ACiHS5i5VI0wobKgC4U3BgEo4F5FYrEiAehdxcFWsCgVcJcipqCTgAbUxqTEEAOljaY2AFAHNQgF1U5zc4AGM2KF8FGCJsiAV4xGDJBGiYNjAuCk1Q6q5geShuTQjMa0Fq+KhEpM1raI58jlIR1OtM91z8xXhfWjYuIrJKOAAlLzX4KujE5EYeTYoIZAqRYjg4LIA9NSIX87gAYQALCmyAaxC6AxmOxuHxBLtVusbkQ7rDHmogA)

**Comment by igalklebanov** [comment]
Hey 👋 

Have you tried `z.array(type).nonempty()`?

**Comment by Newbie012** [comment]
While it gets me closer to my goal (`[string, ...string[]`), I need the first cell to be "A" (`["A", ...string[]`)

**Comment by igalklebanov** [comment]
Sounds like this would do..

```ts
z.array(z.string()).nonempty().refine(([first]) => first === 'A')
```

**Comment by Newbie012** [comment]
I had a feeling that I would require a `refine`. While it will work in runtime, the first cell is still typed as `string`. In order to avoid that, I need to make an assertion function:

```typescript
function startsWithA(v: [string, ...string[]]): v is ["A", ...string[]] {
    return v[0] === "A";
}

z.array(z.string()).nonempty().refine(startsWithA)
```

This does solve the issue, but with a cost of a custom declaring an assertive function. I was hoping for a more zod-"dy" approach.

**Comment by igalklebanov** [comment]
Well there's also..

```ts
z.tuple([z.literal('A')]).rest(z.string())
```

**Comment by Newbie012** [comment]
Perfection. Thanks!
