### ISSUE TITLE
Cannot get e.target.value

### ISSUE THREAD

**Issue by hypo-thesis** [colinhacks/zod#1716]
I have a select like this :

`  <select onChange={(e)=> console.log(e.target.value)} {...register('language')}
`
in which the change doesn't trigger `e` at all. Only by removing `{...register('language')` am I able to get the value. How can get the value on change?

**Comment by denvaki** [comment]
how Zod is connected to this issue?

**Comment by hypo-thesis** [comment]
> how Zod is connected to this issue?

Sorry, you are right. I am on the wrong hub.
