### ISSUE TITLE
Dynamic Validation

### ISSUE THREAD

**Issue by tarekdr** [colinhacks/zod#1724]
Hello, 
I have a for loop of inputs like this : 
```vue
<VField v-for="socialMedia in socialMediaChecked" :id="socialMedia.socialMedia.name">
    <VLabel v-if="socialMedia.checked">Customer's {{ socialMedia.socialMedia.name }} URL:</VLabel>
    <VControl v-if="socialMedia.checked" icon="feather:chevrons-right">
        <VInput type="text" placeholder="" autocomplete="" v-model="socialMedia.url"
            :key="socialMedia.socialMedia.id" />
    </VControl>
</VField>
```
and I want to do the same validation on them for every input and every input have a unique key , how to do a dynamic validation on these inputs using Zod?

**Comment by AndreiLucas123** [comment]
Well, it seems every input is already using `socialMedia.socialMedia.id` as unique `id`

There are libraries like VeeValidate to use zod with vue

You don't need to use it, but you can get some insights

You can create a custom directive to add a dynamic validation

**Comment by rayanazzam1991** [comment]
Hello 
is there any way to create dynamic schema using ZOD ?

**Comment by JacobWeisenburger** [comment]
@tarekdr 
Is the answer from @AndreiLucas123 satisfactory? Or do you have any questions?

I'd like to close this issue if there are no further questions.

---

@rayanazzam1991
I have answered your question over here:
https://github.com/colinhacks/zod/discussions/1746
