### ISSUE TITLE
How to add "examples" Openapi keyword to body request ?

### ISSUE THREAD

**Issue by clabnet** [colinhacks/zod#1725]
Hi, 
thanks for this great library.

How to add the "examples" to schema using zod ?
This is a snippet of my OpenApi3 Swagger schema. 
```
"/media": {
	"post": {
		"summary": "Return a media file with format and type as required",
		"tags": [
			"media"
		],
		"requestBody": {
			"content": {
				"application/json": {
					"schema": {
						"type": "object",
						"properties": {
							"mediaType": {
								"type": "string"
							},
							.... (omitted)
						}
					},
	---> ???			"examples": {     
						"example1": {
							"value": {
								"mediaType": "CHART",
								... (omitted)
							}
						},
     ... (omitted)
```

**Comment by santosmarco-caribou** [comment]
Zod does not have native support for this, but you can try the [`zod-to-openapi`](https://github.com/asteasolutions/zod-to-openapi) library.

**Comment by JacobWeisenburger** [comment]
@clabnet
Is the above answer satisfactory? Or do you have any questions?

I'd like to close this issue if there are no further questions.

**Comment by clabnet** [comment]
I Will try your proposal. Thanks. Merry Christmas.
