### ISSUE TITLE
.catch() does not preserve type with .optional()

### ISSUE THREAD

**Issue by firemuzzy** [colinhacks/zod#1737]
zod version: `3.20.2`
issue: `z.string().optional().catch(undefined)` comes out as `string` instead of `string | undefined`

```
const someSchema = z.object( {
  optionalCatch: z.string().optional().catch(undefined)
})
type Some = z.infer<typeof someSchema>

type WrongType = Some["optionalCatch"]
```

the type of `WrongType` comes out as `string` instead of `string | undefined` however the argument to `catch` does test for undefined.

**Comment by santosmarco-caribou** [comment]
I believe `ZodCatch` was designed wrongfully. I've already opened a PR to fix it.

https://github.com/colinhacks/zod/pull/1733

cc: @colinhacks

**Comment by JacobWeisenburger** [comment]
It looks like this PR was merged. Can we close this issue?

**Comment by santosmarco-caribou** [comment]
Yes
