### ISSUE TITLE
No `.endsWith` or `.startsWith` string methods on Deno

### ISSUE THREAD

**Issue by paudrow** [colinhacks/zod#1744]
I'm using Zod 3.16.1 with Deno and I'm not able to use the `.endsWith` or `.startsWith` string methods. As far as I can tell, all of the other string methods are supported, like `.regex`, `.url`, `.uuid`.

```
$ deno --version
deno 1.29.1 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4
```

**Comment by colinhacks** [comment]
Those methods weren't introduced as of Zod 3.16.1, I recommend upgrading to a more recent version.
