### ISSUE TITLE
Zod literal parse error missing 'received' field

### ISSUE THREAD

**Issue by SimonBerens** [colinhacks/zod#1777]
```ts
z.literal('a').parse('b')
```
throws the following error: 
```ts
[
  {
    "code": "invalid_literal",
    "expected": "a",
    "path": [],
    "message": "Invalid literal value, expected \"a\""
  }
]
```
It would be great if it included the `received` field so that you could tell what you got instead of the literal. This is especially useful for when you have unions of literals; the `received` field will help you find what literal you need to add.

**Comment by JacobWeisenburger** [comment]
Fixed Here: https://github.com/colinhacks/zod/commit/0b22204c6b17b77e36412784735ebcf793b5c3eb

**Comment by JacobWeisenburger** [comment]
Fixed Here:
0b22204c6b17b77e36412784735ebcf793b5c3eb
6252c757f8978da733485d120f77314bc1724ead
