### ISSUE TITLE
Fix zod enum `.option` property documentation in Readme

### ISSUE THREAD

**Issue by chabroA** [colinhacks/zod#1805]
> You can also retrieve the list of options as a tuple with the `.options` property:

According to the doc in the Readme, the `.option` property is supposed to return a tuple, but in the actual implementation, it returns an array. This is also illustrated by the example juste bellow in the doc:

> FishEnum.options; // ["Salmon", "Tuna", "Trout"]);

The doc should be updated to state that the `.options` properties return an array instead of a tuple

**Comment by JacobWeisenburger** [comment]
There is no native support for tuples in js. By returning an array, it is as close to a tuple as you can get in js. So I don't think this is an issue.

https://github.com/tc39/proposal-record-tuple
When tuples are added to js, then we can change zod to return a tuple. But until then, I think it's fine as is.

**Comment by chabroA** [comment]
> There is no native support for tuples in js. By returning an array, it is as close to a tuple as you can get in js

Indeed, but an array is not a tuple though. And since there is no tuple in JS, wouldn't it be more accurate (and less confusing for readers / users) to say in the doc that an array is returned rather than a tuple?

**Comment by JacobWeisenburger** [comment]
I don't really think it's problematic to call an array a tuple in js. However, if you feel very strongly about this, you are more than welcome to continue pushing for this.

**Comment by JacobWeisenburger** [comment]
https://github.com/colinhacks/zod/pull/1806#issuecomment-1382070912
