### ISSUE TITLE
Zod defaulting to optional properties

### ISSUE THREAD

**Issue by chriskuech** [colinhacks/zod#1812]
version: 3.20.2

# Repro
<img width="320" alt="image" src="https://user-images.githubusercontent.com/3680671/210465144-d81a1704-9b98-40be-bfe0-79c321c93c8d.png">

# Expected
No error.

# Observed
The inferred type of parsed values makes all properties optional.
```
Type '{ a?: string; }' is not assignable to type '{ a: string; }'.
  Property 'a' is optional in type '{ a?: string; }' but required in type '{ a: string; }'.ts(2322)
```

**Comment by chriskuech** [comment]
Looks like this was missing in tsconfig

```
compilerOptions: {
  strict: true
}
```

**Comment by JacobWeisenburger** [comment]
Did you figure it out? Or do you have any other questions?
