### ISSUE TITLE
Do we have any roadmap somewhere?

### ISSUE THREAD

**Issue by santosmarco-caribou** [colinhacks/zod#1815]
👋 Do we have any roadmap posted somewhere?

I want to contribute more but I don't have a clear way of where the library is heading. I'm submitting a lot of PRs but without any idea of what are the next steps for Zod.

That would be nice if we had a roadmap somewhere that I could use to guide my next PRs.

**Comment by JacobWeisenburger** [comment]
as far as I know, there is no roadmap or anything like that. I have just been trying to resolve as many issues as possible. There are a fair amount of them that are just waiting for someone to close. And there are a lot of issues that should be moved to Q&A. You are more then welcome to help with this if you would like. thanks for whatever help you are able to give.
