### ISSUE TITLE
ZodCatch should have an `input` of `any`

### ISSUE THREAD

**Issue by santosmarco-caribou** [colinhacks/zod#1816]
Everything fits a `ZodCatch`. Even if the underlying parsing fails, we return a `valid` result, with the catch value in the `data` field.

Any specific reason for not typing the `input` of `ZodCatch` as `any`?

**Comment by colinhacks** [comment]
You're right! Fixed.

**Comment by JacobWeisenburger** [comment]
has this been resolved?
