### ISSUE TITLE
Object key/value order changes after parsing

### ISSUE THREAD

**Issue by andrewrjohn** [colinhacks/zod#1850]
This seems like an odd behavior, and I don't know if this is intended or not. When using `z.object` the parsed return value matches the same key/value order as defined in the schema (not according to the original data).

Example:
```javascript
const Schema = z.object({
  one: z.number(),
  two: z.number(),
  three: z.number(),
})

const data = { three: 3, two: 2, one: 1 };

Schema.parse(data) // returns { one: 1, two: 2, three: 3 }
``` 

Is there a workaround for this? In my case the order of the key/values is very important because we are using the data object as a signature message, and if the order changes at all, then the signature will be different.

**Comment by JacobWeisenburger** [comment]
It seems that the order of the keys is determined by the schema not the value passed to `parse`.

Does this help?

```ts
const schema = z.object( {
    three: z.number(),
    two: z.number(),
    one: z.number(),
} )

console.log( schema.parse( {
    one: 1,
    three: 3,
    two: 2,
} ) )
// { three: 3, two: 2, one: 1 }
```
