### ISSUE TITLE
Method `.pick` / `.omit` might be misleading

### ISSUE THREAD

**Issue by wlcharlie** [colinhacks/zod#1854]
Hi there,

I was using zod with some great methods and found out `.pick/ .omit` might be a bit misleading.

[According to the document](https://zod.dev/?id=pickomit), both of the methods accept a object that contains a key with a value which looks like this:
```ts
const Recipe = z.object({
  id: z.string(),
  name: z.string(),
  ingredients: z.array(z.string()),
});

const JustTheName = Recipe.pick({ name: true });
const NoIDRecipe = Recipe.omit({ id: true });
```

but the [actual behavior](https://github.com/colinhacks/zod/blob/master/src/types.ts#L2152) (not sure was intended or a logic error) is just looping through the given object's key. No matter the value is there or not (truthy or falsy), as long as the key exist in the object it will just effect the schema which seems a bit pointless to having the value with it.

I suggest the value should be also consider, for example:
```ts
const shouldOmit = true

Schema.omit({
   name: shouldOmit, //true
   age: !shouldOmit //false
})

Schema.parse({ 
  name: 'Charlie',
  age: 20
})  // { age: 20 }
```

Any thoughts?

**Comment by JacobWeisenburger** [comment]
I think you are right. Good catch.

```ts
const userSchema = z.object( { name: z.string(), age: z.number() } )
const partialUserSchema = userSchema.omit( { name: true, age: false } )
// only gives compile time error                         ^^^

console.log( partialUserSchema.safeParse( {} ).success ) // true
// should give runtime error because `age` shouldn't be omitted and should be required
```

**Comment by igalklebanov** [comment]
> I suggest the value should be also consider, for example:

> const shouldOmit = true

> Schema.omit({
>    name: shouldOmit, //true
>    age: !shouldOmit //false
> })

> Schema.parse({ 
>   name: 'Charlie',
>   age: 20
> })  // { age: 20 }
> Any thoughts?

I find this adds type complexity without any gains. The runtime bug fix is very simple and doesn't require changing the API.

**Comment by wlcharlie** [comment]
@JacobWeisenburger @igalklebanov  Thanks for reply and the PR already! Great to see things going on :)

**Comment by colinhacks** [comment]
Agreed, I'll review the PR shortly. Thanks!
