### ISSUE TITLE
Typescript function return type error when creating new schema with ZodObject.merge() and ZodObject.partial()

### ISSUE THREAD

**Issue by callumgare** [colinhacks/zod#1879]
Not sure if I'm doing something wrong or it's an issue with zod. I'm trying to create a factory function to make a new ZodObject schema from two existing schemas. However I'm having trouble creating a return type for the function to match the new schema it returns. When I do this:

```typescript
function createSchemaWithMergeAndPartial2<
  BaseShape extends ZodRawShape,
  CommonShape extends ZodRawShape
>(
  baseSchema: ZodObject<BaseShape>,
  commonSchema: ZodObject<CommonShape>
): z.ZodObject<
  z.extendShape<
    BaseShape,
    {
      [k in keyof CommonShape]: z.ZodOptional<CommonShape[k]>;
    }
  >
> {
  return baseSchema.merge(commonSchema.partial());
}
```
typescript will complain about the returned value, saying `Two different types with this name exist, but they are unrelated`. I've made a [CodeSandbox](https://codesandbox.io/s/zod-merge-and-partial-typescript-issue-xil6we) to demonstrate the issue.

I could leave the return type off and let typescript figure it out itself but unfortunately this is just a stripped down example. In my actual project I have many factory functions creating new schema, many of which are composed of several nested factory functions and when I don't provide return types for these functions typescript complaining that `Type instantiation is excessively deep and possibly infinite.` so I'm hoping providing the return types will fix that issue.

**Comment by mmayla** [comment]
I have encountered a similar issue when working with version `3.22.4`. However, upon reverting to version `3.22.2`, everything functions as expected. Has there been any insight into what might be causing this discrepancy between versions?
