### ISSUE TITLE
Add a getter for `multipleOf` on `ZodNumber`

### ISSUE THREAD

**Issue by radekmie** [colinhacks/zod#1889]
While creating [`uniforms-bridge-zod`](https://www.npmjs.com/package/uniforms-bridge-zod), I had a need to get the resulting `multipleOf` to use it in a `<input type"number">`'s `step` attribute. Right now, I have to work around it a little:
```ts
type ZodNumberCheck = ZodNumberDef['checks'][number];
const step = field._def.checks.find(
  (check): check is Extract<ZodNumberCheck, { kind: 'multipleOf' }> =>
    check.kind === 'multipleOf',
);
```

_([source](https://github.com/vazco/uniforms/blob/6353c831673adc9a786932c4ab60483c59de3d9c/packages/uniforms-bridge-zod/src/ZodBridge.ts#L173-L181))_, but I thought that exposing it similarly to `maxValue` for `max` and `minValue` for `min` would be a nice feature.

I have to problems with that, though:
1. What if there are multiple `multipleOf`s? Ideally we'd need to calculate least common multiple of them, but maybe using the first one is enough?
2. What should be the name? `multipleOfValue` or `stepValue` stay in-align with `max`/`maxValue`, but aren't ideal.

I can file a PR for that.

**Comment by colinhacks** [comment]
Please do!

**Comment by radekmie** [comment]
It's definitely not stale - the PR is ready and waiting for a review.
