### ISSUE TITLE
`z.ZodType` and `refine` not working as expected

### ISSUE THREAD

**Issue by marcus13371337** [colinhacks/zod#1893]
Consider the following code:
```ts
const stringIsValid = (value: string): value is "a" | "b" =>
  ["a", "b"].includes(value);

const ASchema = z.object({
  type: z.string().refine(stringIsValid),
});

type A = z.infer<typeof ASchema>;

interface B {
  id: string;
  children: (z.infer<typeof ASchema> | B)[];
}

const BSchema: z.ZodType<B> = z.lazy(() =>
  z.object({
    id: z.string(),
    children: z.array(z.union([ASchema, BSchema])),
  })
);
```
type `A` is correctly inferred as:
```ts
{
    type: "a" | "b";
}
```

But when creating the `BSchema`, and assigning it to `z.ZodType<B>` I get the following error:
```ts
Type 'ZodLazy<ZodObject<{ id: ZodString; children: ZodArray<ZodUnion<[ZodObject<{ type: ZodEffects<ZodString, "a" | "b", string>; }, "strip", ZodTypeAny, { type: "a" | "b"; }, { ...; }>, ZodType<...>]>, "many">; }, "strip", ZodTypeAny, { ...; }, { ...; }>>' is not assignable to type 'ZodType<B, ZodTypeDef, B>'.
  The types of '_input.children' are incompatible between these types.
    Type '({ type: string; } | B)[]' is not assignable to type '({ type: "a" | "b"; } | B)[]'.
      Type '{ type: string; } | B' is not assignable to type '{ type: "a" | "b"; } | B'.
        Type '{ type: string; }' is not assignable to type '{ type: "a" | "b"; } | B'.
          Type '{ type: string; }' is not assignable to type '{ type: "a" | "b"; }'.
            Types of property 'type' are incompatible.
              Type 'string' is not assignable to type '"a" | "b"'
```

Is this a bug or am I doing something weird? Zod-version is `3.20.2` and typescript version is `4.8.4`

**Comment by JacobWeisenburger** [comment]
Can you just use `z.enum` instead of using `refine`?

```ts
const ASchema = z.object( {
    type: z.enum( [ 'a', 'b' ] )
} )
```

**Comment by JacobWeisenburger** [comment]
This doesn't have anything to do with `z.lazy`. But there is something weird going on.

```ts
const stringIsValid = ( value: string ): value is 'a' | 'b' =>
    [ 'a', 'b' ].includes( value )

const fooSchema = z.object( {
    type: z.string().refine( stringIsValid ),
} )

type Foo = z.infer<typeof fooSchema>
// type Foo = {
//     type: "a" | "b"
// }

type Bar = {
    children: Foo[]
}

const barSchema = z.object( {
    children: fooSchema.array(),
} ) satisfies z.ZodType<Bar>
//            ^^^^^^^^^^^^^^
// Type 'ZodObject<{ children: ZodArray<ZodObject<{ type: ZodEffects<ZodString, "a" | "b", string>; }, "strip", ZodTypeAny, { type: "a" | "b"; }, { type: string; }>, "many">; }, "strip", ZodTypeAny, { ...; }, { ...; }>' does not satisfy the expected type 'ZodType<Bar, ZodTypeDef, Bar>'.
//   The types of '_input.children' are incompatible between these types.
//     Type '{ type: string; }[]' is not assignable to type '{ type: "a" | "b"; }[]'.
//       Type '{ type: string; }' is not assignable to type '{ type: "a" | "b"; }'.
//         Types of property 'type' are incompatible.
//           Type 'string' is not assignable to type '"a" | "b"'.
```

**Comment by marcus13371337** [comment]
Thanks for your investigation! Yes changing to enum solves the problem. Wanted to report the potential bug though!

**Comment by JacobWeisenburger** [comment]
Do you have an example use case that can only be solved with refine? This way we would have a good test case for potential bug fixes.

**Comment by JacobWeisenburger** [comment]
`z.enum` requires a tuple type `[T, ...T[]]`. But your generic type `Keys` returns a union of the keys. I don't know a good way to convert unions to tuples. So if you were to change `Keys` to return a tuple of the keys, it would be easier to use `z.enum`. I don't have time to really dive into that right now. But I can try to come back to it later if you want. No guarantees on when I will be able to though.

An interesting read about converting unions to tuples:
https://stackoverflow.com/a/55128956/5321863

```ts
type Keys<T extends object> = {
    [ K in keyof T ]: K extends string
    ? T[ K ] extends object
    ? `${ K }.${ Keys<T[ K ]> }` | K
    : K
    : never
}[ keyof T ]

const MY_TREE = {
    a: {
        b: {
            c: {},
        },
    },
    b: {
        a: {},
        b: {},
    },
    c: {},
} as const

type MyTreeKeys = Keys<typeof MY_TREE>
// type MyTreeKeys = "a" | "b" | "c" | "a.b" | "a.b.c" | "b.a" | "b.b"
```

Hope this helps.

**Comment by JoelBeeldi** [comment]
Hello,

An exemple where you can only use refine : 

`import { z } from 'zod';

const idIsValid = (value: string): value is `${string}/${string}` => value.split('/').length === 2;

interface Entity {
    id: `${string}/${string}`;
    children: Entity[];
}

const EntitySchema: z.ZodType<Entity> = z.lazy(() =>
    z.object({
        id: z.string().refine(idIsValid),
        children: z.array(EntitySchema),
    })
);`

**Comment by JacobWeisenburger** [comment]
@JoelBeeldi 
Does this help?

```ts
const isValidId = ( value: string ): value is `${ string }/${ string }` =>
    value.split( '/' ).length === 2

const baseEntitySchema = z.object( {
    id: z.string().refine( isValidId ),
} )

type Entity = z.infer<typeof baseEntitySchema> & {
    children: Entity[]
}

const entitySchema = baseEntitySchema.extend( {
    children: z.lazy( () => entitySchema.array() ),
} ) as z.ZodType<Entity>
```

**Comment by marcus13371337** [comment]
Yes that would probably work. But just for the bug/librarys sake, what would happen if I accidently casted it to something incompatiable? I will give it a try to solve the issue, so the problem @JoelBeeldi posted would work out of the box!

**Comment by marcus13371337** [comment]
I mean that I think this is just something that should work "out of the box" and not force developers to use type assertions to get around the problem. I think I found the "bug" and fixed it in the following PR https://github.com/colinhacks/zod/pull/1905.

Feedback is welcomed!

**Comment by JacobWeisenburger** [comment]
I understand now. I think I missed "would" when I read what you said.

I agree that this is something that should work without type casting or assertions.

**Comment by marcus13371337** [comment]
After some investigations, I realized I misunderstood some things, here is the proper way to solve the problem that @JoelBeeldi  had!
```ts
 const idIsValid = (value: string): value is `${string}/${string}` =>
    value.split("/").length === 2;

  interface Entity {
    id: `${string}/${string}`;
    children: Entity[];
  }

  interface EntityInput {
    id: string;
    children: EntityInput[];
  }

  const EntitySchema: z.ZodType<Entity, z.ZodTypeDef, EntityInput> = z.lazy(
    () =>
      z.object({
        id: z.string().refine(idIsValid),
        children: z.array(EntitySchema),
      })
  );
```

Apparently, you need to define the "Input"-type of the schema, if you use `refine`/`transform` which is passed as the third argument. Something we maybe should add to the docs. Might submit a PR for that another time!

**Comment by JacobWeisenburger** [comment]
Do you think it still needs some kind of a bug fix? or would this be resolved with just a update to the docs?

**Comment by marcus13371337** [comment]
Update in the docs would be sufficient I would say, basically, if you use `z.lazy` (where you need to explicitly type the return value), you need to type the Input and the Output manually and pass it like this:
```ts
const MyLazySchema: z.ZodType<Output, z.ZodTypeDef, Input> = z.lazy(() => ...)
```

**Comment by JacobWeisenburger** [comment]
Sounds good. I'll see what I can do.

**Comment by JoelBeeldi** [comment]
Thanks for the help, it solve my issue (funny that i found it almost the same day as you).

I didn't known that you could/should specify input type in this situation.

Adding an example in the docs would be a good thing

**Comment by JacobWeisenburger** [comment]
@marcus13371337, @JoelBeeldi
Thanks so much for the discussion and examples. I have updated the docs:
https://github.com/colinhacks/zod#recursive-types

**Comment by marcus13371337** [comment]
Nice! Thanks for your support @JacobWeisenburger ❤️

**Comment by JacobWeisenburger** [comment]
Always happy to help.

**Comment by JacobWeisenburger** [comment]
Would you guys like your full name or user name shown here?

![image](https://user-images.githubusercontent.com/31667350/213476385-277930bb-56c0-4899-b50d-538e9ca5f9f8.png)

**Comment by marcus13371337** [comment]
Username! Thanks

**Comment by JoelBeeldi** [comment]
Username too and thanks for the maintenance of this awesome lib
