### ISSUE TITLE
When using `.catch` with default value, it can return invalid type

### ISSUE THREAD

**Issue by apstanisic** [colinhacks/zod#1895]
Since catch value allows us to pass `z.input` value, it won't fallback to default value.
`.catch` should either require `z.output` value, or zod should also parse value provided to catch.

[reproduction](https://codesandbox.io/s/musing-rumple-6iq8f9?file=/src/index.ts)

```ts
import { z } from "zod";
// this allows `.catch(undefined)` since `z.input` is `string | undefined`, but it should require `string`, since 
// default value will not be applied in case of an error
const stringSchema = z.string().default("hello").catch(undefined);
const stringResult = stringSchema.parse(111);
// ts says stringResult type is string, but value is undefined
console.log("stringResult", stringResult);
```

**Comment by JacobWeisenburger** [comment]
Confirmed

```ts
const stringSchema = z.string().optional().catch( undefined )
type StringSchema = z.infer<typeof stringSchema>
// type StringSchema = string
// should be `type StringSchema = string | undefined`

console.log( stringSchema.parse( 42 ) ) // undefined
```

**Comment by maxArturo** [comment]
Hi @JacobWeisenburger do you still see this issue? This seems correct under the latest version of `master` @ [this commit](https://github.com/colinhacks/zod/commit/a57fc2da3c48a5a2270e9684017d8bc056af8a40): 

```ts
const stringSchema = z.string().optional().catch(undefined);
type StringSchema = z.infer<typeof stringSchema>;
// `type StringSchema = string | undefined`
```

**Comment by JacobWeisenburger** [comment]
I'm using Deno, so I'm not sure how to test this on the latest version of master. But if you say it's working, I will trust you.

However, I think that we should still keep this open as a bug fix issue until the latest is released on npm/deno. What are your thoughts?

**Comment by maxArturo** [comment]
Yep sounds good!

**Comment by JesusTheHun** [comment]
Do you have an ETA for the next release ?

**Comment by apstanisic** [comment]
I think this issue is fixed. Reproduction now shows error correctly.
