### ISSUE TITLE
Use operator IN to filter a query by a JSON attribute.

### ISSUE THREAD

**Issue by neyanderson** [colinhacks/zod#1907]
Include the `IN` operator to filter by a JSON column. 

Something like that:
`const dbQuery: any = { 
      where: { 
        jsonField: {
          path: '$.jsonpath',
          in: ['value_1', 'value_2']
        },
      orderBy: {
        text_field: 'asc'
      }
    };`

**Comment by JacobWeisenburger** [comment]
Could you provide a some more info?
-  an example that includes something from zod
- More

**Comment by JacobWeisenburger** [comment]
Could you provide a some more info?

Perhaps:
- an example that includes something from zod
- a more comprehensive description of the problem you are trying to solve
