### ISSUE TITLE
`z.enum` does not allow adding a custom error for `invalid_enum_value`

### ISSUE THREAD

**Issue by StErMi** [colinhacks/zod#1913]
When. I define a `z.enum` I'm only able to define custom errors for `invalid_type_error` and `required_error` but not for `invalid_enum_value`.

When the user for example choose the "empty" option from the Select, the form will choose the `invalid_enum_value` but I cannot personalize the error.

Am I using it in the wrong way, or should `enum` expose that property to be customized?

**Comment by JacobWeisenburger** [comment]
Perhaps this will help you:
https://github.com/JacobWeisenburger/zod_utilz#makeerrormap

```ts
import { zu } from 'zod_utilz'

const errorMap = zu.makeErrorMap( {
    required: 'Custom required message',
    invalid_type: ( { data } ) => `${ data } is an invalid type`,
    invalid_enum_value: ( { data, options } ) =>
        `${ data } is not a valid enum value. Valid options: ${ options?.join( ' | ' ) } `,
} )

const enumSchema = z.enum( [ 'foo', 'bar' ], { errorMap } )
zu.SPR( enumSchema.safeParse( 'baz' ) ).error?.issues[ 0 ].message
// baz is not a valid enum value. Valid options: foo | bar
```

**Comment by StErMi** [comment]
Hi there @JacobWeisenburger I can define already the error inside the `errorMap`, what I would have thought is that I could also define directly in the main object instead of defining the error map given that `invalid_enum_value` is specific to the `z.enum`

**Comment by JacobWeisenburger** [comment]
You would think so, yes. However currently, `required_error` and `invalid_type_error` are the only error types that can be defined outside of an `errorMap`. At least, this is my understanding. Someone else is more than welcome to correct me.

**Comment by JacobWeisenburger** [comment]
@StErMi 
Was my answer satisfactory? or would you like to leave this issue open as an enhancement request?

**Comment by colinhacks** [comment]
> `required_error` and `invalid_type_error` are the only error types that can be defined outside of an `errorMap`

These keys, if present, are used to construct an error map that's used internally. That's why you can't pass either these in conjunction with the `errorMap` param:

<img width="780" alt="Screenshot 2023-01-29 at 3 59 00 PM" src="https://user-images.githubusercontent.com/3084745/215363533-a1257799-dc08-49f8-9769-15c71c9c4886.png">
