### ISSUE TITLE
Disable validations Per environments (i.e. do not validate on Production)

### ISSUE THREAD

**Issue by galarbel** [colinhacks/zod#1921]
Hi All,

this looks like a really great project, but I was looking for a way to set it up so that real-time validations will only be done on Non-Production environments.

the idea is to make sure that production environment will run as fast as possible.
similar to what redux have with their "production mode".

is there any way to achieve this?
are there any plans to add something like that?

Thanks,
Gal

**Comment by JacobWeisenburger** [comment]
Is this what you are looking for?

```ts
// for node use: process.env.ENVIRONMENT
const schema = Deno.env.get( 'ENVIRONMENT' ) === 'production'
    ? z.any()
    : z.string()
```

**Comment by galarbel** [comment]
something like this just might work :)
it'd be nice to see something like this built in though.

`z.configure({ production: true });`

this could potentially help with performance issues as was mentioned here:
https://github.com/colinhacks/zod/issues/205

thanks for the quick response.
