### ISSUE TITLE
Literal errors don't return received field on error 

### ISSUE THREAD

**Issue by rickmed** [colinhacks/zod#1923]
Examples

```javascript
const data = z.literal(4324).safeParse(431)
```
```javascript
const data = z.literal("something").safeParse("else")
```

return at data.error.issues schema:

```javascript
{
    code: 'invalid_literal',
    expected: 'something',
    path: [],
    message: 'Invalid literal value, expected "something"'
  }
```

But this example

```javascript
const data = z.string().safeParse(1)
```

return at data.error.issues schema

```javascript
  {
    code: 'invalid_type',
    expected: 'string',
    received: 'number',
    path: [],
    message: 'Expected string, received number'
  }
````

Is this expected behavior?

**Comment by JacobWeisenburger** [comment]
I don't know if this is ideal behavior, but it is the way the code works currently. PRs are always welcome.

**Comment by JacobWeisenburger** [comment]
It looks like this was already changed:
https://github.com/colinhacks/zod/commit/0b22204c6b17b77e36412784735ebcf793b5c3eb

It's just waiting to be released
