### ISSUE TITLE
`z.coerce.date().parse(null)` validates successfully

### ISSUE THREAD

**Issue by psychedelicious** [colinhacks/zod#1929]
This is a bit of a gotcha:
```typescript
z.coerce.date().safeParse(null).success // true
```

It's not technically unexpected, though:
```typescript
new Date(null) // Thu Jan 01 1970 10:00:00 GMT+1000 (Australian Eastern Standard Time)
```

I'm happy to PR a docs update briefly describing this gotcha, unless the project wants to address this by changing how `z.coerce.date()` works internally.

(IMO it should _not_ change `z.coerce.date()` as just calling `new Date()` without any other logic is very tidy.)

**Comment by JacobWeisenburger** [comment]
https://github.com/colinhacks/zod/pull/1930#issuecomment-1405139123

**Comment by psychedelicious** [comment]
(non-)issue addressed, thanks for your excellent work on zod!
