### ISSUE TITLE
issues with customizing error messages

### ISSUE THREAD

**Issue by J4VMC** [colinhacks/zod#1956]
Hi,

I'm using Zod with SvelteKit and [typesafe/i18n](https://github.com/ivanhofer/typesafe-i18n) to create a multilingual site.

One of the main requirements is to display localized error messages according to the selected locale.

At the moment, I have the following code blocks:

```ts
import { z } from "zod";
import { get } from "svelte/store";
import LL from "$i18n/i18n-svelte";

const contactSchema = z.object({
	name: z
		.string({
			required_error: get(LL).formRequiredError({ field: get(LL).name() }),
			invalid_type_error: get(LL).formInvalidError({ field: get(LL).name(), type: get(LL).text() }),
		})
		.min(3)
		.max(20),
	surname: z
		.string({
			required_error: get(LL).formRequiredError({ field: get(LL).surname() }),
			invalid_type_error: get(LL).formInvalidError({
				field: get(LL).surname(),
				type: get(LL).text(),
			}),
		})
		.min(3)
		.max(20),
	email: z
		.string({
			required_error: get(LL).formRequiredError({ field: get(LL).email() }),
			invalid_type_error: get(LL).formInvalidError({
				field: get(LL).email(),
				type: get(LL).email(),
			}),
		})
		.email(),
	company: z
		.string({
			required_error: get(LL).formRequiredError({ field: get(LL).company() }),
			invalid_type_error: get(LL).formInvalidError({
				field: get(LL).company(),
				type: get(LL).text(),
			}),
		})
		.min(3)
		.max(20),
	phone: z
		.string({
			required_error: get(LL).formRequiredError({ field: get(LL).phone() }),
			invalid_type_error: get(LL).formInvalidError({
				field: get(LL).phone(),
				type: get(LL).text(),
			}),
		})
		.min(3)
		.max(20),
	message: z
		.string({
			required_error: get(LL).formRequiredError({ field: get(LL).message() }),
			invalid_type_error: get(LL).formInvalidError({ field: get(LL).message(), type: get(LL).text() }),
		})
		.min(20)
		.max(3000),
});

export { contactSchema };
```

Right now, Zod is bypassing the locale consideration and just displaying the messages in whatever language is selected as the base.

Am I doing something wrong with Zod?

**Comment by colinhacks** [comment]
My guess is that this line resolves to a string synchronously, so future changes to the locale aren't reflected. The `required_error` message is being set at the time the schema is created. I recommended using an error map to specify errors that are "computed" at parse-time.

https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md

**Comment by J4VMC** [comment]
> My guess is that this line resolves to a string synchronously, so future changes to the locale aren't reflected. The `required_error` message is being set at the time the schema is created. I recommended using an error map to specify errors that are "computed" at parse-time.
> 
> https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md

Yes, you were right. In the end, I got it working, and now I'm using the error map as you recommended.

**Comment by dmoebius** [comment]
Just FYI: I ran into the same problem and solved it differently: I replaced all usages of the constant schema with a getter. 

So instead of
```
export const myschema = z.object(...);
```
I replaced it with
```
export const myschema = () => z.object(...);
```
I didn't had to change many usages. For example, I'm using Svelte superforms, and I simply replaced all invocations of
```
const form = await superValidate(mySchema);
```
with
```
const form = await superValidate(mySchema());
```
This way, superValidate always gets a new schema instance on each server request, and the LL variable is evaluated correctly and can be used in Zod messages, e.g.
```
z.object({
  name: z.string().min(1, get(LL).validationMessages.personRequired),
  ...
})

Hope this helps.

**Comment by vhochstein** [comment]
> Yes, you were right. In the end, I got it working, and now I'm using the error map as you recommended.

@J4VMC I m quite new to this Sveltekit stuff, but facing same issue. Do you think you can share your solution ?
Especially I am wondering about, how I might pass the LL method which I have in my PageServerLoad function to the custom ErrorMap to be able to use it ?

Thanks a lot for your support in advance
