### ISSUE TITLE
all properties are inferred as optional, even if strict and strictNullChecks are set to true

### ISSUE THREAD

**Issue by isaacfink** [colinhacks/zod#1958]
I have a simple validator and i am exporting the types like this
```
import type { z } from 'zod';
import type { cardValidator, imageBlockValidator, textBlockValidator } from 'validators';

export type ValidatedCard = z.infer<typeof cardValidator>;
export type ValidatedTextBlock = z.infer<typeof textBlockValidator>;
export type ValidatedImageBlock = z.infer<typeof imageBlockValidator>;
```

when I import the type into another package I am getting typescript errors along the lines of `object.property is possibly 'undefined'` i have seen some bugs here regarding this and usually the answer is to set `strict` to `true` in `tsconfig.json` but I've done that already and it still doesn't work
here is my `base.json` which is imported in all other packages
```
{
	"$schema": "https://json.schemastore.org/tsconfig",
	"display": "Default",
	"compilerOptions": {
		"composite": false,
		"declaration": true,
		"declarationMap": true,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"inlineSources": false,
		"isolatedModules": true,
		"moduleResolution": "node",
		"noUnusedLocals": false,
		"noUnusedParameters": false,
		"preserveWatchOutput": true,
		"strict": true,
		"target": "ES6",
		"outDir": "dist",
		"strictNullChecks": true
	},
	"exclude": ["node_modules"]
}
```
I have added the `strict` and `strictNullChecks` to `true` in the local configs as well just to make sure it wasn't an import issue and I still got the same error, after each step I reinstalled everything and restarted vscode just in case that was the issue but it didn't work

**Comment by colinhacks** [comment]
User error - not enough info to repro. Sorry! Make sure you're not accidentally `exclude`ing your source files. And make sure your tsconfig is properly extending base.json: `"extends": "./base.json"`.

**Comment by isaacfink** [comment]
@colinhacks what else should I add? I am away from my computer now but I'll post anything you suggest tomorrow
