### ISSUE TITLE
Extended use of .extend and .merge cause TS instantiation failures

### ISSUE THREAD

**Issue by tshelburne** [colinhacks/zod#1990]
I'm creating a migration tool for versioned data from a backend service, and I'm using Zod for both compile- and run-time type checks. My hope was to be able to express the types changing over time with `.extend` (eg. `const v2Type = v1Type.extend({ ... })`) so that it was more concise and consumable, but it quickly hits the "Type instantiation is excessively deep and possibly infinite.(2589)" error. (Probably related, https://github.com/colinhacks/zod/issues/1879)

The following are greatly simplified examples — in the actual use-case, I have schema factory functions and many properties defined on each version. But even with no properties defined, both `.extend` and `.merge` fail at the 15th version.

[Typescript Play for `.extend`](https://www.typescriptlang.org/play?ts=4.9.5#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgFBkDGEAdgM7wAqAnmAKYCMcAvCgHQQARgCs2lGAAoEaAJRkANm3gw2DDgC5+wGpjZQAPDFZsImOC3YcAfBWr0mxgEw9zxjnzYAPFTWJTZCkpwKgyOmsh82roGRuymruyONlS0DAlsAMwuFmyOHt5svv5yisqqMBnhkTp6hsbxORnJdmk5ACzZxhn5Pn7SJUEhMG1VUbWxJmbtzakO7ACsnextPYV9AaXB5fOjNTH1U8bzM-bpAGxLbPOrRf2BZQxnu9F1cYfsZyetxgDsl2c3dYDB4wH7PcYHdI-L5zNgADkuP0BxXuWwYcPB+ze6ThMPSAE5LnDkXdNkN8ZjXpMCXichwAAyXfEkjaDcoMykTBpuem0txcXh0+ks4FomAcDRaPZU7mWay2WbpDjOQX8kWoobKzmQulJBWnOlZVWWPJeXoosnsypSl5c96cJr676WDrGh3qy1qEY2iHYultPmWRZujgrM1rC1stQ7H1Y6l045AA)
[Typescript Play for `.merge`](https://www.typescriptlang.org/play?ts=4.9.5#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgFBkDGEAdgM7wAqAnmAKYCMcAvCgHQQARgCs2lGAAoEaAJRkANm3gw2DDgC5+wGpjZQAPDFZsImOC3YcAfBWr0mxgEw9zxjnxB6A5mwnIBImKS0jJyisqqMI6a-tq6Bkbspq7sjjZUtAwpbADMLhZsjh7evv5CouJSsmFKcCoMOTF8cXqGxskFOel2WQUALPnGOcVQPn4BFcHVCrX1MH1NLQntZv3dmQ7sAKyD7H0jY2WBlSE1EQxbizqtiSarxlvr9tkAbLtsWwelE0FVoTPnGAvK7xNpJe7sF5PXrGADs7xeX3G5V+pwBdUisJBNxW2Vh0M2bAAHO9YUijpM-mcMQwidjluDskSCdkAJzvInkn4nabhGkwVn0sF3NksgocAAM71ZXJRPP+fLmkqFtw6bglYrcXF44olsuOUwVs0iHA0WmuDJF4ustg22Q4zh1Wv1lLRipN0XNoNVEM4aVtz3FeSdliKnlG3zlhupSsaXpxjKDmssAxDnGG4cO3Oj6KVC3jlrVKeTnB2aY4+0zkYNVNzJsuBeFRdLViAA)

Any suggestions for workarounds or alternatives are greatly appreciated — I've started looking into the source, but I wanted to reach out before digging too deep.

**Comment by rijenkii** [comment]
Just got hit with the same problem, added a few `.merge`s and suddenly my types are too deep.
TS issue: https://github.com/microsoft/TypeScript/issues/34933

**Comment by colinhacks** [comment]
I looked into this, try `zod@beta` and let me know if the issue resolves.

**Comment by tshelburne** [comment]
> I looked into this, try `zod@beta` and let me know if the issue resolves.

This seems to resolve it. I'm having an issue with `.required()` not working as expected (I'm getting undefined as a valid option for every property on `z.object` whether I use `.required()` or not) so it's hard to test, but the base tests seem to be good. Thanks!

**Comment by tshelburne** [comment]
Scratch that — it looks like it just starts failing further down the line, and my computer was taking too long to compute the types. I'm seeing failures locally starting around the 19th or 20th type definition, using the same strategy as the Typescript Play links above.

**Comment by rijenkii** [comment]
In my case updating to the latest version actually helped (I assume that what was `zod@beta` is now included in `zod@3.20.6`).

**Comment by bradley-r-martin** [comment]
@tshelburne Im running into the same issue - with the same use case trying to version a schema. Did you ever get a solution working ?

**Comment by tshelburne** [comment]
No — we ultimately had to change a list of a union type into a dictionary of explicit types, it's disappointing but it works.
