### ISSUE TITLE
Access to the string email regex

### ISSUE THREAD

**Issue by andresBobsled** [colinhacks/zod#2003]
Could the string email [regex pattern](https://github.com/colinhacks/zod/blob/master/src/types.ts#L523) be exported?
Or accessed somehow by passing `zod.string().email()` as param?
### Motivation:
html input of `type="email"` is more permissive than `zod email`, alloing for example `a@b`, which zod does not allow.

Html input has the `pattern` [attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern).

We would like thus to be able to then pass the zod email regex pattern to the html pattern attribute, so then the browser can be in charge of not submitting the form if invalid, showing the appropriate error, etc. Otherwise, we have to call `onSubmit`, with `zod.SafeParse` and if not success manually set/show the error on the input.

Thank you.

**Comment by JacobWeisenburger** [comment]
> Could the string email [regex pattern](https://github.com/colinhacks/zod/blob/master/src/types.ts#L523) be exported?

PRs are always welcome.
