### ISSUE TITLE
Support some type-specific validations at top level

### ISSUE THREAD

**Issue by reviewher** [colinhacks/zod#2010]
```js
z.number().int(); // value must be an integer
```

No other type supports `int` validation.  Consider supporting the concise

```js
z.int(); // value must be an integer
```

**Comment by JacobWeisenburger** [comment]
Please explain more about your use case. Why do you need integer support for more than just number?

**Comment by reviewher** [comment]
That's the point.  `string` doesn't support `int`, `boolean` doesn't support `int`, etc.  `.int()` already implies that the value is a number. `z.number().int()` looks verbose compared to `z.int()`

**Comment by JacobWeisenburger** [comment]
seems a little pedantic, however, if you feel so strongly about this, feel free to submit a PR.

**Comment by colinhacks** [comment]
This deviates from TypeScript's type system in a way I don't like. The top-level `z` functions all correspond to an actual type in the type system and this would be the only exception. Also `.int()` would need to be expanded to support all the usual top-level parameters (`RawCreateParams`) so people aren't confused about why they're supported, and that would be weird/inconsistewnt. Also the current API reflects the fact that `.int()` is "just another refinement" that doesn't actually change the inferred type.

**Comment by JacobWeisenburger** [comment]
well said
