### ISSUE TITLE
ZodObject second generic arg is required after upgrading 3.20.2 -> 3.20.3

### ISSUE THREAD

**Issue by urugator** [colinhacks/zod#2012]
Hi, after upgrading from `3.20.2` to `3.20.3`, my code is broken, because `ZodObject` now requires at least 2 generic params, eg
```
ERROR in ./apps/api/src/app/utils/misc.ts:81:5
TS2707: Generic type 'ZodObject<T, UnknownKeys, Catchall, Output, Input>' requires between 2 and 5 type arguments.
    79 |   prefix?: P,
    80 | ): P extends ''
  > 81 |   ? z.ZodObject<T> | z.ZodObject<{ [key in keyof T]: z.ZodNull }>
       |     ^^^^^^^^^^^^^^
    82 |   :
    83 |       | z.ZodObject<CapitalizeAndPrefixProps<T, P>>
    84 |       | z.ZodObject<{
```
If this change was intended could someone help me fixing the code?
```typescript
export function outerJoinSchema<T extends z.ZodRawShape, P extends string = ''>(
  shape: T,
  prefix?: P,
): P extends ''
  ? z.ZodObject<T> | z.ZodObject<{ [key in keyof T]: z.ZodNull }>
  :
      | z.ZodObject<CapitalizeAndPrefixProps<T, P>>
      | z.ZodObject<{
          [key in keyof CapitalizeAndPrefixProps<T, P>]: z.ZodNull;
        }> {
  const prefixedSchema = prefix
    ? prefixPropsSchema(capitalizePropsSchema(shape).shape, prefix)
    : z.object(shape);
  const nullSchema = Object.keys(prefixedSchema.shape).reduce(
    (result, key) => {
      result[key] = z.null();
      return result;
    },
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    {} as any,
  ) as z.ZodObject<{ [key in keyof typeof prefixedSchema.shape]: z.ZodNull }>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return z.union([prefixedSchema, nullSchema]) as any;
}
```
The function takes zod shape and generates a union of the original shape and same shape where all props are null. Optionally the props are prefixed. Eg:
`outerJoinSchema({ foo: z.string() }, 'prefix')` 
=>
```ts
z.union([
  z.object({ prefixFoo: z.string() }),
  z.object({ prefixFoo: z.null() }),
])
```
Originally it was supposed to take schema instead of shape, but I couldn't make it work type-wise.

**Comment by urugator** [comment]
Oh perhaps am I supposed to use `ZodObjectDef` instead of `ZodObject`?

**Comment by SimplyLinn** [comment]
I think [this PR](https://github.com/colinhacks/zod/pull/1652) introduced an issue once it's compiled to a d.ts file.

The exclude method becomes this type declaration:
```ts
declare class ZodEnum<T extends [string, ...string[]]> extends ZodType<T[number], ZodEnumDef<T>> {
    exclude<ToExclude extends readonly [T[number], ...T[number][]]>(values: ToExclude): ZodEnum<Writeable<FilterEnum<T, ToExclude[number]>>>;
}
```

Wrapping the output of FilterEnum in Writeable makes the typechecker not see it as matching the constraint set by ZodEnum.

The wrapping of Writeable, I think, is due to the order of the createZodEnum functions overloads?

I will investigate whether my assumption is correct, and potentially open a PR

**Comment by SkyaTura** [comment]
+1 at this issue, this shouldn't be in a patch upgrade, broke many things. I recommend rolling back to 3.20.2 while it's unstable...

**Comment by colinhacks** [comment]
Apologies, fixed in 3.20.4.

**Comment by colinhacks** [comment]
@SkyaTura What other breaking changes have you experienced? Please file issues.

**Comment by SkyaTura** [comment]
@colinhacks it was something related to merging objects defs. Unfortunately I was on a rush and had to quickly undo the update in order to delivery some things.

I may test it again with the bugged version for you when things get calm over here ;)

**Comment by colinhacks** [comment]
@SkyaTura Ah good call: https://github.com/colinhacks/zod/issues/2016
Also fixed
