### ISSUE TITLE
Support validation of relative URLs

### ISSUE THREAD

**Issue by TechAurelian** [colinhacks/zod#2025]
Using a schema of
`urlLocal: z.string().url().optional(),`

will fail validation for a relative URL such as
`/blog/blog-post-1/`

I see this in the [Zod source code](https://github.com/colinhacks/zod/blob/master/src/types.ts#L686):

```ts
} else if (check.kind === "url") {
  try {
    new URL(input.data);
  } catch {
```

So without a `base` parameter `URL()` will throw an exception for relative urls. The [URL()](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) documentation explains:

> If `url` is a relative URL, `base` is required, and will be used as the base URL. 
> 
> TypeError | `url` (in the case of absolute URLs) or `base + url` (in the case of relative URLs) is not a valid URL.

I'm able to work around this issue using custom validation logic via refinements:

`urlLocal: z.string().refine((val) => new URL(val, 'http://localhost')).optional(),`

But maybe this should be built-in?

**Comment by JacobWeisenburger** [comment]
Can you provide some examples of invalid relative URLs?

**Comment by JacobWeisenburger** [comment]
@TechAurelian 
Is the above answer satisfactory? If so, I'd like to close this issue.

**Comment by JacobWeisenburger** [comment]
@TechAurelian, I'm going to close this issue. Feel free to reopen if you have more to say.
