### ISSUE TITLE
Many methods have massive compiler performance drawbacks

### ISSUE THREAD

**Issue by Nick-Lucas** [colinhacks/zod#2036]
I spent much of last week investigating why my work's codebase was taking 2-3 seconds to populate autocomplete or refresh code-intelligence during code changes, and after a lot of tsc tracing and replacing Zod types with `any`, I found that basically the entire time is being taken up processing Zod types - specifically those using masking (Extend, Omit, Pick) methods.

After removing all uses of masking and dropping back to Zod 3.19 on the suggestion of some comments in the issues, the codebase is now down to 1.5 seconds for autocomplete which is still a lot of time.

I've written this up in a little more detail [here](https://dev.to/nicklucas/typescript-runtime-validators-and-dx-a-type-checking-performance-analysis-of-zodsuperstructyuptypebox-5416) and have a small-scale reproduction [here](https://github.com/Nick-Lucas/gapstack/tree/main/packages/light-type-benchmarks) which was used in the benchmarks.

Eventually I do plan on a more in-depth benchmarking across a larger variety of methods, as these benchmarks are a somewhat blunt instrument, but it would be great to see type inference performance improved across the board as Zod is lagging behind the competition even in the most basic situations.

**Comment by mataslib** [comment]
I'm experiencing same behaviour. I did finally took time to debug why vscode autocomplete takes 10-15 sec to show in my codebase (which is just terrible while coding frontend) and tracked it down to zod being the culprit even for what I thought are simple schemas. Is there way to somehow blacklist zod from typescript completely? Current DX is not acceptable for me anymore, I would rather have working editor and type everything manualy.

**Comment by Nick-Lucas** [comment]
You can notate your Zod types with //@ts-igore (typing //@ts will give you a few options to try.

I've also heard a suggestion to wrap all the Zod types in a function explicitly returning a simple ZodType<YourInterface> and ignoring the input.

None of it's ideal of course

**Comment by mataslib** [comment]
I recorded the behavior:

![Animation](https://user-images.githubusercontent.com/5154014/219332694-26821dd1-5c41-49ea-b482-16071b74159e.gif)

**Comment by mataslib** [comment]
Interesting - I don't know whether it is related to zod, but this terrible behavior which I recorded on simple example is fixed when I set `"strict": true` instead of `"strict": false` in `tesconfig.json`.

**Comment by yykcool** [comment]
Previously in my case it was 10-15 seconds delay, restarting the TS server seemed to fix the problem temporarily. We did a couple of things:
- used `@typescript/analyze-trace` to eliminate some hotspots, found 1 instance of the typescript server being stuck in a recursive type for too long
- added //@ts-nocheck to every single file with schema definitions
- upgraded typescript to 4.9.4

Somehow the problem seems to have vanished after that...

**Comment by colinhacks** [comment]
@Nick-Lucas The performance has been improved dramatically in Zod 3.21, can you try it can report back? I looked at your repo but it wasn't clear to me how to re-run your benchmrak.

**Comment by Nick-Lucas** [comment]
Hey @colinhacks sure thing, I've been working on a more granular suite which is a little rough (variances of 5-10ms between runs are normal) but has been quite useful.

I've just updated my project at work to the latest and performance does look much better, the most expensive files in the codebase are no longer traced as related to Zod, which tracks with my experience dog-fooding light-types as a replacement. So definitely on the right lines!

I suspect that Zod's wrapping of types is part of the remaining losses, my light-type development has made of point of always modifying the generic types (ie '.optional' `return new LtType<TInput | undefined, TOutput | undefined>` instead of `ZodOptional<ZodType<etc>>`) when chaining to a new class instance, which has some tradeoffs but is proving very efficient for inference. extend/merge aren't possible to do cheaply today, it's actually most efficient to deprecate those methods and encourage users to do `object({ ...base.shape, ...extra.shape })` as TypeScript seems to play nicely when duplicate keys are in a spread object, but that can't be hidden inside a generic method because TS can't seem to do native merging when duplicate keys exist 😭

# Before

Zod: `3.20.6`
TypeScript: `4.8.2`

<img width="784" alt="image" src="https://user-images.githubusercontent.com/8896153/223089886-799da457-c014-4dd8-bd62-566955df20aa.png">

# Now

Zod: `3.21.2`
TypeScript: `4.8.2`

<img width="786" alt="image" src="https://user-images.githubusercontent.com/8896153/223089936-d3ecd08d-89be-49fb-b1d9-42ae5631eae1.png">

I'm aware typescript has also made some optimisations recently, but just haven't yet updated the suite to 4.9.x

In terms of running this for yourself:

```sh
git clone git@github.com:Nick-Lucas/gapstack.git
git checkout e33655ca3139c87264da2edcbdf3d42e62f1697f # just to pin the version

nvm use
yarn install

# Run the benchmarks
yarn light-type-benchmark-2:run 

# in theory these alternative scripts should stabilise the CPU cores in use between runs, though at least the Mac one I don't think works as i want yet
yarn light-type-benchmark-2:run:mac 
yarn light-type-benchmark-2:run:nux
```

# The suite from the blog post

The blog post suite actually traces the whole repo but I just pulled out the relevant bits for the writeup

```sh
# do the setup steps from above ^

# a directory called .trace/ will be created
yarn tsc:trace
```

**Comment by nawlbergs** [comment]
I too am concerned about cpu usage of zod. I'm a first time user:
- I've imported the lib into two different files (a schema defined in one... a parse function in another)... and my IDE (webstorm) is noticeably showing performance hits...  (im on a 2021 M1 - 32gig)
- comment out the zod import... file performance returns.

I'm concerned that if I implement this lib.. ill have to pull it out as other developers here have older/slower machines.

**Comment by divmgl** [comment]
Why are all of these issues being marked as stale? They're still ongoing issues.

**Comment by Nick-Lucas** [comment]
This particular issue was actually mostly resolved with a bugfix. I would open/find another one for general DX performance issues, which are definitely still present when used with tools like tRPC
