### ISSUE TITLE
It looks like `.refine()` removes `.shape`

### ISSUE THREAD

**Issue by chmac** [colinhacks/zod#2056]
Here's my example:

```typescript
const fooSchema = z.object({foo: z.string()})
type Foo = z.infer<typeof fooSchema.shape.foo>
const barSchema = z.object({bar: z.string()}).refine(({bar}) => bar.length > 0)
type Bar = z.infer<typeof barSchema.shape.bar>
```

In this case, `barSchema.shape` TypeScript complains:

```
Property 'shape' does not exist on type 'ZodEffects<ZodObject<{ bar: ZodString; }, "strip", ZodTypeAny, { bar: string; }, { bar: string; }>, { bar: string; }, { bar: string; }>'.ts(2339)
```

Is this intended behaviour? Or maybe I'm using `.refine()` incorrectly?

Thanks a lot for zod, I've been a loyal fan for many years and the project has only continued to improve. It's a real treat to define schemas once and use them for both types and at runtime. 🧡

**Comment by JacobWeisenburger** [comment]
Currently, this is working as expected. If you think this should be different, PRs are always welcome.

**Comment by chmac** [comment]
@JacobWeisenburger Thanks for the quick response. Do you think it would make sense to add something to the docs for `.refine()` that makes this clearer?

~~I assume that `.refine()` is not chainable in the usual fashion?~~ Hmm, no, maybe not, I just looked, and I can apply `.refine()` multiple times.

Is there another section of the docs where this is explained and I could submit a PR to add a link to the `.refine()` section?

**Comment by JacobWeisenburger** [comment]
`refine`, `transform`, `superRefine`, and maybe a few others return `ZodEffects`, which wraps another `ZodType`. You can access that type with `._def.schema`.

```ts
const fooSchema = z.object( { foo: z.string() } )
type Foo = z.infer<typeof fooSchema.shape.foo>
// type Foo = string

const barSchema = z.object( { bar: z.string() } ).refine( ( { bar } ) => bar.length > 0 )
type Bar = z.infer<typeof barSchema._def.schema.shape.bar>
// type Bar = string
```

Not sure where you would put this in the docs.

**Comment by maurer2** [comment]
Hello, how do you access the schema, when you have multiple refines, for example:

```ts
const barSchema = z
  .object( { bar: z.string() } )
  .refine( ( { bar } ) => bar.length > 0 )
  .refine( ( { bar } ) => bar.length < 10 )
type Bar = z.infer<typeof barSchema._def.schema.shape.bar> // I get an error when trying to access shape
```
Each refine seems to add a `ZodEffects<>`, so barSchema is now `ZodEffects<ZodEffects<ZodObject<{...}>>>.
Thanks

Cheers

**Comment by thewebartisan7** [comment]
> Hello, how do you access the schema, when you have multiple refines, for example:
> 
> ```ts
> const barSchema = z
>   .object( { bar: z.string() } )
>   .refine( ( { bar } ) => bar.length > 0 )
>   .refine( ( { bar } ) => bar.length < 10 )
> type Bar = z.infer<typeof barSchema._def.schema.shape.bar> // I get an error when trying to access shape
> ```
> 
> Each refine seems to add a `ZodEffects<>`, so barSchema is now `ZodEffects<ZodEffects<ZodObject<{...}>>>`. Thanks
> 
> Cheers

It seem like each refine require a deep access to shape via `_def.schema`, example:

`type Bar = z.infer<typeof barSchema._def.schema._def.schema.shape.bar>`

**Comment by mauriciosoares** [comment]
> Hello, how do you access the schema, when you have multiple refines, for example:
> 
> ```ts
> const barSchema = z
>   .object( { bar: z.string() } )
>   .refine( ( { bar } ) => bar.length > 0 )
>   .refine( ( { bar } ) => bar.length < 10 )
> type Bar = z.infer<typeof barSchema._def.schema.shape.bar> // I get an error when trying to access shape
> ```
> 
> Each refine seems to add a `ZodEffects<>`, so barSchema is now `ZodEffects<ZodEffects<ZodObject<{...}>>>`. Thanks
> 
> Cheers

I just found it easier to save the base schema in a variable, and the refined schema in another:

```ts
const baseBarSchema = z
  .object( { bar: z.string() } )

const barSchema = baseBarSchema
  .refine( ( { bar } ) => bar.length > 0 )
  .refine( ( { bar } ) => bar.length < 10 )
```

Now you can just do `baseBarSchema.shape` without having to do that `_def` hack

**Comment by alexrequelme** [comment]
I use this code to retrieves the `shape` of z.ZodEffects

```ts
// Accessing the shape of z.ZodEffects
const shape = schema.sourceType()._def.shape();
```

**Comment by christhornham** [comment]
I was able to use `.refine()` and `.shape` with the following if statement.

```typescript
if (schema instanceof ZodEffects) {
  // True when .refine() used on schema.
  console.log(schema._def.schema.shape);
} else {
  // True when schema does not include .refine()
  console.log(schema.shape);
}
```

**Comment by oliverterrell** [comment]
> Currently, this is working as expected. If you think this should be different, PRs are always welcome

Sassy response for making something incredible difficult to build customizations into. Looking forward to zod 4.
