### ISSUE TITLE
Custom schema example for template literals gives type error

### ISSUE THREAD

**Issue by becpeck** [colinhacks/zod#2074]
In the [Custom schemas](https://github.com/colinhacks/zod#custom-schemas) section of the docs, this example is given for creating a template literal schema:
```ts
const px = z.custom<`${number}px`>((val) => /^\d+px$/.test(val));
px.parse("100px"); // pass
px.parse("100vw"); // fail
```

As is, this example shows an error on val being passed into test:

> `Argument of type 'unknown' is not assignable to parameter of type 'string'.`

`z.custom()` takes parameter `check?: ((data: unknown) => any) | undefined`, while `test.()` takes parameter `string: string`.

I think ideally, there should be a way to annotate  or infer the type of `data`, but that section is pretty empty.
I found two ways around the type error, one of which would be good to update the docs with:
```ts
const pxWithAs = z.custom<`${number}px`>((val) => /^\d+px$/.test(val as string));
const pxWithTemplate = z.custom<`${number}px`>((val) => /^\d+px$/.test(`${val}`));
```

[Playground link showing the error and ways around](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgNwBQFA9NXAKIAeAhuADYCmWOeAFjDDABnAFy0A5sBi8ArgCMAdAGNc1FW2AA7XsyUBrIdSLFqAYiUyhMXAFohS3hxDMhFFZqtwwjOAF4UypbWIAA8AAYAJAiaMiByHFBo3mEAfAAUaQBuzGwAlH4pcNQAegA6xADU3hHUCjAcVlk5ubmU3gpgzFBCHGkARACMAAxD3n2tRXSdQq7tnd29gyOZAO7jZJNYzMBsVLRwACorEHArzACeQnBdEDKaxHDSXAk4UG4QHvDeAOpSvACCV38yECVlw4SiMTiCSSjFSGWyeQKRTKlWqtXqjUR1yuVigWnELUo7k8Pz+BycYDYzHqfgCFjBoUi0Vi8USyXSTSRvkKJXKVUYNTqDRgaWZiLQYSJQA)

I don't like either of these that much, and I'll probably be using `z.templateLiteral()` after #1786 is merged, but the docs example should be updated with whatever method is recommended to avoid the error.

**Comment by JacobWeisenburger** [comment]
Is this what you are looking for?

```ts
const px = z.custom<`${ number }px`>( x => /^\d+px$/.test( z.string().parse( x ) ) )
console.log( px.safeParse( '100px' ).success ) // true
console.log( px.safeParse( '100vw' ).success ) // false
```

If you found my answer satisfactory, please consider supporting me. Even a small amount is greatly appreciated. Thanks friend! 🙏
https://github.com/sponsors/JacobWeisenburger

**Comment by JacobWeisenburger** [comment]
Fixed here: https://github.com/colinhacks/zod/commit/174965739d17db348d445ab250fb2cf6bd7cdd51

This is still not a great example of z.custom, because you could easily use z.string().regex(), but I can't think of any good example that can't be solved with an already existing zod schema.

**Comment by matthewoates** [comment]
@JacobWeisenburger how about a more strict string validator that makes sure the first letter is capitalized? That makes sense for my CMS. I tried the following but I don't see how I can plug it back into the other validation rules - `z.custom<string>(Capitalize).min(3).max(50)`

My likely incorrect attempt: 
```js
const zCapitalized = (val: unknown) => {
  if (!(typeof val === 'string')) return false;
  const c = val[0];
  return c && c === c.toUpperCase();
};

export const NodeWithoutTimestampsSchema = z.object({
  // id: NodeIDSchema,
  WIP: z.boolean().optional(),
  slug: z
    .string()
    .min(3)
    .max(50)
    .regex(/^[a-z0-9\-]+$/),
  title: z.custom(zCapitalized).min(3).max(50),
  seoDescription: z.string().min(3).max(200),
  createdAt: z.string().min(1).optional(),
  updatedAt: z.string().min(1).optional()
});
```

**Comment by matthewoates** [comment]
Oh, it looks like [refine](https://github.com/colinhacks/zod#refine) is actually what I want here. Does anyone else find that confusing?
