### ISSUE TITLE
Typing generic functions (like a transformer) correctly

### ISSUE THREAD

**Issue by bjesuiter** [colinhacks/zod#2075]
Given the following function type: 
ChunkTransformFunc<P, R> = (chunk: P) => R

I want to be able to express: 

1. The Param should be of type P 
2. The Return Type should be of type R (normally unrelated to P) 

ChatGPT Gives me something like this: 

```ts
const ChunkTransformFuncSchema = z
  .function(z.zodTuple([z.unknown() as any]), z.unknown())
  .args(z.zodTuple([z.unknown() as any] as const))
  .transform((func) => {
    const [inputSchema, outputSchema] = z.getParsedType(func);
    return z.function(inputSchema[0], outputSchema);
  });
```

But this has some problems: 
1. z.zodTuple does not exist => rewriting to z.tuple() 
2. Then this line does not work anymore, due to readonly something somewhere: `.args(z.tuple([z.unknown() as any] as const));`

I would like to have something like a `z.generic()` function which allows a generic to be defined as input and to be retrieved as an output type for example. 
Maybe like this: 

```ts
z
.function(z.generic('P'), z.generic('R'))
.args(z.generic('P))
.returns(z.generic('R'))
```

**Comment by colinhacks** [comment]
This is known as a "higher-kinded type" and it isn't representable in TypeScript: https://github.com/microsoft/TypeScript/issues/1213

**Comment by klesun** [comment]
Just my 5 cents for future readers, HKT is actually kind of possible through `this`, albeit a bit verbose: https://github.com/microsoft/TypeScript/issues/40928
