### ISSUE TITLE
Recursive types doc example stop working with .brand()

### ISSUE THREAD

**Issue by petrovmiroslav** [colinhacks/zod#2076]
If there is a branded schema in the shape, [the recursive types doc example](https://zod.dev/?id=recursive-types) stop working.
``` ts
const baseCategorySchema = z.object({
  - name: z.string(),
  + name: z.string().brand("CategoryName"),
});

type Category = z.infer<typeof baseCategorySchema> & {
  subcategories: Category[];
};

const categorySchema: z.ZodType<Category> = baseCategorySchema.extend({
  subcategories: z.lazy(() => categorySchema.array()),
});
```
categorySchema has TS error:
TS2322: Type 'ZodObject<extendShape<{ name: ZodBranded<ZodString, "CategoryName">; }, { subcategories: ZodLazy<ZodArray<ZodType<Category, ZodTypeDef, Category>, "many">>; }>, "strip", ZodTypeAny, { ...; }, { ...; }>' is not assignable to type 'ZodType<Category, ZodTypeDef, Category>'.
   Types of property '_input' are incompatible.
     Type '{ name: string; subcategories: Category[]; }' is not assignable to type 'Category'. 
      Type '{ name: string; subcategories: Category[]; }' is not assignable to type '{ name: string & BRAND<"CategoryName">; }'.         Types of property 'name' are incompatible.
           Type 'string' is not assignable to type 'string & BRAND<"CategoryName">'.
             Type 'string' is not assignable to type 'BRAND<"CategoryName">'.

Thanks.

**Comment by JacobWeisenburger** [comment]
Everything is working as expected for me.

```ts
const baseCategorySchema = z.object( {
    name: z.string().brand( 'CategoryName' ),
} )

type Category = z.infer<typeof baseCategorySchema> & {
    subcategories: Category[]
}

const categorySchema: z.ZodType<Category> = baseCategorySchema.extend( {
    subcategories: z.lazy( () => categorySchema.array() ),
} )

console.dir(
    categorySchema.parse( {
        name: 'People',
        subcategories: [ {
            name: 'Politicians',
            subcategories: [ {
                name: 'Presidents',
                subcategories: [],
            } ],
        } ],
    } ),
    { depth: Infinity }
)
// {
//     name: 'People',
//     subcategories: [ {
//         name: 'Politicians',
//         subcategories: [ {
//             name: 'Presidents',
//             subcategories: []
//         } ]
//     } ]
// }
```
Try updating to the latest version of zod and see if that fixes it for you.

If you found my answer satisfactory, please consider supporting me. Even a small amount is greatly appreciated. Thanks friend! 🙏
https://github.com/sponsors/JacobWeisenburger

**Comment by petrovmiroslav** [comment]
> 

Sorry for misunderstanding. .parse() going on working. But there is a typescript error. I use the latest version of zod and Typescript v4.9.5.

<img width="965" alt="Screenshot 2023-02-21 at 20 01 08" src="https://user-images.githubusercontent.com/46135319/220424610-556ed888-54d3-4044-80ea-fe3ee1fb66dd.png">
<img width="965" alt="Screenshot 2023-02-21 at 20 01 22" src="https://user-images.githubusercontent.com/46135319/220424621-275f430e-6d4e-47c6-a701-58644d8a2fba.png">

**Comment by JacobWeisenburger** [comment]
I'm still not getting any errors.
![image](https://user-images.githubusercontent.com/31667350/220428316-eae6b197-9537-4d76-ad98-dd7e7276a5df.png)

Can you create a codesandbox or something that I would be able to see what you see?

**Comment by petrovmiroslav** [comment]
> codesandbox

Yes. Thanks
https://codesandbox.io/s/keen-butterfly-9gmigm?file=/src/index.ts

**Comment by JacobWeisenburger** [comment]
Thank you for bearing with me. I can confirm the error in the [codesandbox](https://codesandbox.io/s/keen-butterfly-9gmigm?file=/src/index.ts)

I'm using deno, and apparently it's stuck on zod v3.20.5

**Comment by colinhacks** [comment]
This happens because the inferred `input` and `output` types of brand are different. ZodBrand accepts `string` as input and returns `string & z.BRAND<"brand">` as output.  This will work:

```ts
const baseCategorySchema = z.object({
  name: z.string().brand("CategoryName"),
});
type CategoryInput = z.input<typeof baseCategorySchema> & {
  subcategories: CategoryInput[];
};
type CategoryOutput = z.output<typeof baseCategorySchema> & {
  subcategories: CategoryOutput[];
};

const categorySchema: z.ZodType<CategoryOutput, any, CategoryInput> =
  baseCategorySchema.extend({
    subcategories: z.lazy(() => categorySchema.array()),
  });
```

**Comment by petrovmiroslav** [comment]
It works! Thank you!

**Comment by petrovmiroslav** [comment]
One more question. 
`z.ZodType<CategoryOutput, any, CategoryInput>` doesn't contain any ZodObject methods. How can I use `.merge()` for example?
