### ISSUE TITLE
`z.enum` with generic array is breaking `z.object` inference 

### ISSUE THREAD

**Issue by hunterwilhelm** [colinhacks/zod#2077]
Source:
https://stackoverflow.com/questions/75523855/zod-enum-with-generic-array

I changed the source code to use the exact generics `z.enum` uses and it still didn't work.
```typescript
import { z } from 'zod';

function objectWithGenericEnum<U extends string, T extends Readonly<[U, ...U[]]>>(
    options: T
) {
    const enumValidator = z.enum(options);
    const a =  z.object({
        data: enumValidator,
    });
    return a.transform((v) => v.data); // Property 'data' does not exist on type '{ [k in keyof baseObjectOutputType<{ data: ZodEnum<Writeable<T>>; }>]: baseObjectOutputType<{ data: ZodEnum<Writeable<T>>; }>[k]; }'.(2339)
}
```

If we instead use this line, the data property is present.

```typescript
...
    const enumValidator = z.enum(['fish', 'sushi']);
...
// data is now defined
```

**Comment by JacobWeisenburger** [comment]
I have confirmed this

**Comment by colinhacks** [comment]
ZodEnum is designed to work with tuples of string literals `['a', 'b']`, etc. In the generic context, the generic hasn't been literalized so inference is going to be tricky. As a workaround use a typecast: `z.enum(options as [string, ...string[]])`

**Comment by JacobWeisenburger** [comment]
@hunterwilhelm
This seems to work for me:
```ts
function objectWithGenericEnum<U extends string, T extends Readonly<[ U, ...U[] ]>> (
    options: T
) {
    const enumValidator = z.enum( options as any as [ string, ...string[] ] )
    const a = z.object( {
        data: enumValidator,
    } )
    return a.transform( ( v ) => v.data )
}
```

Does this solve your problem?

**Comment by hunterwilhelm** [comment]
I'll ask and report back when [Andrew](https://stackoverflow.com/questions/75523855/zod-enum-with-generic-array) responds.

**Comment by kevich** [comment]
@JacobWeisenburger @colinhacks 

Solution with casting from generic to array of strings will solve problem with resolve of variable, but in this case [we will loose string literals in transform output](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgNwBQFmArgHYDGMwEdcEARgFYCmTA6sBgALAOI86PKMAYBROjRAAeACpweADxgTiAZzi6Y0ugHMAfAAoKcG+zDNWugFxwoPAIbFWAGwCecAG0VABo4ADoIlQCAXWiKAEpEa1s3GBooNmQwzl4mCwRk21tidxh3FyyJRQsIexY6fXd9egBrOggAdzYmwMNjE1CIsL7gUxjo+ODC9Hiwo3cGzGgQCwsAN0SAXjM4NbCSsvjKNCoKBkd4EwkpGXlFQREVKAXdJag8TfZuPhgHsWvpHIFCsAvh3PhQvgOPhonAeucGjAjhQYL4wDw4OJJIC7iA-k8Xm8PigwqNMFIlKj0RBMHArtjbsD8c9FsszJQzhd1EyhMICaz3nBPlkcj98tMigdyiSqiCwRCCNDYfCLpNpmhZvMBSt1lsdnspciUWiMbjmYTlkKSWSKVSeDTufdefzXmyyEA)

```typescript
function objectWithGenericEnum<T extends string>(
    options: readonly [T, ...T[]]
) {
    return z.object({
        data: z.enum(options as unknown as [string, ...string[]]),
    }).transform((v) => v.data);
}


const genericEnumWithTransform = objectWithGenericEnum(['a', 'b'] as const);
// type will be just string
type GenericEnumWithTransform = z.infer<typeof genericEnumWithTransform>;

const enumWithTransform = z.object({
        data: z.enum(['a', 'b'] as const),
    }).transform((v) => v.data);
// type will be 'a' | 'b'
type EnumWithTransform = z.infer<typeof enumWithTransform>;
```

**Comment by colinhacks** [comment]
This should be working in `zod@canary`, give it a shot @hunterwilhelm @kevich

**Comment by kevich** [comment]
@colinhacks Thanks!

I've checked it just now. And looks pretty good! Except one small point =)

For now I got return type from generic, that it can be also `undefined`

```typescript
import { z } from 'zod';

function objectWithGenericEnum<T extends string>(
    options: readonly [T, ...T[]]
) {
    return z.object({
        data: z.enum(options),
    }).transform((v) => v.data);
}


const genericEnumWithTransform = objectWithGenericEnum(['a', 'b'] as const);
// type will be 'a' | 'b' | undefined
type GenericEnumWithTransform = z.infer<typeof genericEnumWithTransform>;

const enumWithTransform = z.object({
        data: z.enum(['a', 'b'] as const),
    }).transform((v) => v.data);
// type will be 'a' | 'b'
type EnumWithTransform = z.infer<typeof enumWithTransform>;
```

But it's already something that I can work with!
