### ISSUE TITLE
The "exact" issue field isn't documented (used by too_big and too_small)

### ISSUE THREAD

**Issue by joeycumines-fctg** [colinhacks/zod#2080]
Per the title, I've noticed that the functionality added in #1620 (to address #1611) was never documented in [ERROR_HANDLING.md](https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md).

Feeling too lazy to make a PR myself, so this is just a PSA.

**Comment by colinhacks** [comment]
Updated, thanks!
