### ISSUE TITLE
export 'z' (imported as 'z') was not found in 'zod' (module has no exports)

### ISSUE THREAD

**Issue by TSMMark** [colinhacks/zod#2085]
With webpack. All I'm doing is:

```ts
import { z } from 'zod'
```

and webpack is not able to import it

```
WARNING in ./myFile.ts 56:10-18
export 'z' (imported as 'z') was not found in 'zod' (module has no exports)
```

**Comment by TSMMark** [comment]
I was able to circumvent this by adding to webpack config:

`resolve.alias.zod` -> `zod: path.resolve('./node_modules/zod/lib/index.umd.js')`

Not sure why this is needed but it seems umd.js was needed for me for some reason.

**Comment by colinhacks** [comment]
Without a webpack config I can't debug this. You really shouldn't have to use UMD in 2023.

**Comment by TSMMark** [comment]
I agree, this has not been an issue for any other package

**Comment by JacobWeisenburger** [comment]
Has this been resolved?

**Comment by colinhacks** [comment]
I couldn't reproduce this, but I made a tweak to the rollup configuration that may have fixed it. The OP will need to chime in

**Comment by JacobWeisenburger** [comment]
OP?

**Comment by JacobWeisenburger** [comment]
@TSMMark, I'm going to close this issue. Feel free to reopen if you have more to say.

**Comment by TSMMark** [comment]
Thanks + sorry I didn't respond – I've been sick the past few days. Just tested zod version `3.21.4` and unfortunately the issue still persists.

**Comment by asifurrahaman754** [comment]
> I was able to circumvent this by adding to webpack config:
> 
> `resolve.alias.zod` -> `zod: path.resolve('./node_modules/zod/lib/index.umd.js')`
> 
> Not sure why this is needed but it seems umd.js was needed for me for some reason, but was not used automatically.

it worked for me

**Comment by TSMMark** [comment]
@asifurrahaman754 That's great it worked for you too. Do you know what it is about your bundler setup that makes the umd necessary? I've had this same issue with a few more package since originally posting this, and I haven't been able to figure out what about our bundler (webpack, ts, etc) config is making this break without the resolve alias...
