### ISSUE TITLE
Min and max use spaces and characters.

### ISSUE THREAD

**Issue by louiss0** [colinhacks/zod#2088]
I have recently found out that When `z.string().max()` is used it also counts the Characters and spaces within each string. This is not good at all. Spaces are not characters they are just nothing. This is not a good idea I thought it would just count the actual characters only. This should not be done at all. The length of a string and how many characters are written are different things. Please make it so that spaces are ignored when the string is being evaluated or at least create an ignore spaces method.   

To prove that this is true I have decided to create a repo to showcase this problem https://stackblitz.com/edit/typescript-urjdak. It's a repo that uses random text to write up to 300 words. 

In order to test out my thesis all you have to do is remove one of the spaces and the test that I have created will just pass. 

If you want to understand what I'm talking about even more go to this site [Word Count Jet](https://www.wordcountjet.com/)
Then paste the below text in there

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu turpis egestas pretium aenean pharetra magna ac. Nisi vitae suscipit tellus mauris a. Vel risus commodo viverra maecenas accumsan lacus vel. NKEDnasjns aaeldm3ewo;sn ypkqw lie. 
```

**Comment by JacobWeisenburger** [comment]
> Spaces are not characters they are just nothing

If spaces are nothing, then why did you use about 120 of them in your message? Perhaps you could try writing your messages in the future without spaces and see how well it goes for you.

**Comment by louiss0** [comment]
> > Spaces are not characters they are just nothing
> 
> If spaces are nothing, then why did you use about 120 of them in your message? Perhaps you could try writing your messages in the future without spaces and see how well it goes for you.
> 
> But aside from all that, what are you hoping to accomplish here? Because the only goal I can understand from your message is to prove that spaces are nothing, which has nothing to do with zod.
> 
> Are you hoping that zod changes `z.string().max()` to not count spaces? How will that work for all the people that rely on zod to count the spaces?
> 
> Are you hoping that zod will give you a method to count words? This might be possible, but the way you are asking for this is not effective nor clear communication.

I'm hoping that spaces are not counted by default. That's what I'm looking for. The only reason to use spaces as a part of the word count is to be strict. I think that idea is a common mistake but if this is important an `ignoreSpaces()` method could be added instead. In fact I'd also add an ignore punctuation method as well.

**Comment by JacobWeisenburger** [comment]
> I'm hoping that spaces are not counted by default.

How will that work for all the people that rely on zod to count the spaces?

**Comment by louiss0** [comment]
> > I'm hoping that spaces are not counted by default.
> 
> How will that work for all the people that rely on zod to count the spaces?


I see the idea of counting spaces is important for some reason. I thought the decision to do this was based on laziness. But now I know that this is not the case. If spaces are not counted by default then a method called `includeSpaces` would be used. If not then a method called `ignoreSpaces` should be used instead.

**Comment by JacobWeisenburger** [comment]
> If spaces are not counted by default then a method called `includeSpaces` would be used

So you are saying that everyone who relies on the current default (counting spaces) should be required to change all of their code to use `includeSpaces`? And if they don't change their code, then their apps will stop working correctly? Do I have a good understanding of what you are saying?

**Comment by louiss0** [comment]
> > If spaces are not counted by default then a method called `includeSpaces` would be used
> 
> So you are saying that everyone who relies on the current default (counting spaces) should be required to change all of their code to use `includeSpaces`? And if they don't change their code, then their apps will stop working correctly? Do I have a good understanding of what you are saying?

I was saying that the fact that spaces are a part of the system is bad and that if devs want to include spaces in their validation. They should specify that. 

But since keeping spaces is important to you I just want an `ignoreSpaces` method instead. 

**The ability to ignore spaces is all that I want now**

**Comment by JacobWeisenburger** [comment]
> I was saying that the fact that spaces are a part of the system is bad

How are spaces being a part of the system bad? If you are going to make such arrogant statements, they need to be backed up with really good reasoning. But so far, I haven't seen any.

**Comment by JacobWeisenburger** [comment]
This is quite trivial to implement currently:

```ts
const schema = z.string()
    .transform( value => value.replaceAll( ' ', '' ) )
    .pipe( z.string().max( 5 ) )

console.log( schema.parse( '0 1 2 3 4' ) )
// 01234

const result = schema.safeParse( '0 1 2 3 4 5' )
!result.success && console.log( result.error.issues[ 0 ].message )
// String must contain at most 5 character(s)
```

Therefore, I don't think we should add `ignoreSpaces` to zod.

**Comment by louiss0** [comment]
> ```ts
>  z.string().max( 5 )
> ```

Ok then but it would be quite convenient. That's is what zod is good at as a library being practical and readable. Thanks for the solution.

**Comment by louiss0** [comment]
> This is quite trivial to implement currently:
> 
> ```ts
> const schema = z.string()
>     .transform( value => value.replaceAll( ' ', '' ) )
>     .pipe( z.string().max( 5 ) )
> 
> console.log( schema.parse( '0 1 2 3 4' ) )
> // 01234
> 
> const result = schema.safeParse( '0 1 2 3 4 5' )
> !result.success && console.log( result.error.issues[ 0 ].message )
> // String must contain at most 5 character(s)
> ```
> 
> Therefore, I don't think we should add `ignoreSpaces` to zod.

Ok then but it would be quite convenient. That's is what zod is good at as a library being practical and readable. Thanks for the solution.

**Comment by quarterpound** [comment]
Why is this issue so funny
