### ISSUE TITLE
Feature Request: Better ZodObject generics

### ISSUE THREAD

**Issue by geoffgscott** [colinhacks/zod#2089]
In TS projects I find I am frequently defining schemas based on an existing type using this process:

```ts
const userSchema: ZodSchema<User> = z.object({
    name: z.string(),
    email: z.string().email()
})
```

However the generic `ZodSchema` strips all the `ZodObject` properties like `partial` and `shape` from the type so when writing functions that take a ZodObject we need to typecast from schema to object. 

It would be very helpful to have a `ZodSchemaObject` generic that would map to type with all the properties of `ZodObject`

**Comment by JacobWeisenburger** [comment]
Is this what you are looking for?

```ts
const userSchema = z.object( {
    name: z.string(),
    email: z.string().email()
} ) satisfies z.ZodSchema<User>
```

If you found my answer satisfactory, please consider supporting me. Even a small amount is greatly appreciated. Thanks friend! 🙏
https://github.com/sponsors/JacobWeisenburger

**Comment by geoffgscott** [comment]
I don't think so because the intent would be to do something like this:

```ts
function foo<T extends object>(schema: ZodObject<T>){
   return schema.shape
}
```

**Comment by JacobWeisenburger** [comment]
Is this what you are looking for?

```ts
function foo<Schema extends z.AnyZodObject> ( schema: Schema ) {
    return schema.shape
}
```
