### ISSUE TITLE
Typescript Errors for flattened error object

### ISSUE THREAD

**Issue by jameswoodley** [colinhacks/zod#2101]
I am using SvelteKit and it's form actions. When my server.ts file returns a fail, SvelteKit puts the result into the `ActionData` object, which it assigns for you

<img width="315" alt="image" src="https://user-images.githubusercontent.com/52610563/221380911-9576c072-d512-40f6-bddd-9db56bf7d487.png">

I'm kicking back Zod validation errors:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/52610563/221380864-acbda672-d926-49ae-bffa-450b6cab9d65.png">

Everything actually works, so this could be deemed minor, but Typescript doesn't like the form.errors object
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/52610563/221380813-6009339c-4677-4ebe-90ef-8a9d93178283.png">

Reading the docs, I see the Extract type signature section, but not being a native TS guy, I'm getting a touch lost with it. Can anyone assist with how to get TS happy?

**Comment by JacobWeisenburger** [comment]
Please send a reproducible code example.

**Comment by jameswoodley** [comment]
It looks like restarting VS Code has removed these errors so I think we can close this, apologies
