### ISSUE TITLE
Recursive type with fixed and arbitrary keys causes type error.

### ISSUE THREAD

**Issue by nbramblett** [colinhacks/zod#2110]
I looked through the old issues and the closest I could find was [this](https://github.com/colinhacks/zod/issues/1436), but I confirmed that the fix does not apply here because I'm already in strict mode.

Version info:
**Typescript**: "^4.9.4"
**Zod**: "^3.20.2"

Verified that `"strict": true` is set in my tsconfig.json.

# The issue

I am trying to make a nested tree of arbitrary string keys where only the _leaf_ nodes have a defined structure.

```typescript
const DataFieldSchema = z.object({
  name: z.string(),
  description: z.string().optional(),
  required: z.boolean().optional().default(false),
  type: z.string().optional().default("string"),
});
type DataField = z.infer<typeof DataFieldSchema>;

type Nested = DataField | { [key: string]: Nested };
const NestedDataFieldSchema: z.ZodType<Nested> = z.lazy(() =>
  z.union([DataFieldSchema, z.record(NestedDataFieldSchema)])
);
```
I verified that the `Nested` type permits the structure I'm looking for.
```typescript
const x: Nested = {
  ANY: {
    FIELD: {
      description: "foo",
      name: "bar",
      type: "baz",
      required: true,
    },
  },
};
// satisfies the type
```

However, NestedDataFieldSchema throws the following compilation error:
```
Type 'ZodLazy<ZodUnion<[ZodObject<{ name: ZodString; description: ZodOptional<ZodString>; required: ZodDefault<ZodOptional<ZodBoolean>>; type: ZodDefault<...>; enumValues: ZodOptional<...>; }, "strip", ZodTypeAny, { ...; }, { ...; }>, ZodRecord<...>]>>' is not assignable to type 'ZodType<Nested, ZodTypeDef, Nested>'.
  Types of property '_input' are incompatible.
    Type '{ description?: string | undefined; type?: string | undefined; required?: boolean | undefined; enumValues?: { value: string; description: string; }[] | undefined; name: string; } | Record<string, Nested>' is not assignable to type 'Nested'.
      Type '{ description?: string | undefined; type?: string | undefined; required?: boolean | undefined; enumValues?: { value: string; description: string; }[] | undefined; name: string; }' is not assignable to type 'Nested'.
        Type '{ description?: string | undefined; type?: string | undefined; required?: boolean | undefined; enumValues?: { value: string; description: string; }[] | undefined; name: string; }' is not assignable to type '{ [key: string]: Nested; }'.
          Property 'description' is incompatible with index signature.
            Type 'string' is not assignable to type 'Nested'.
```

It seems to be an issue with the fact that DataField is a complex type, since when you use only primitive values at the leaf, it works fine (such as in the JSON example in the readme). My best guess is that there's an issue with it parsing arbitrary keys alongside well-defined keys.

The only workaround I've been able to find is to change the Nested type to 
```typescript 
type Nested = DataField | { [key: string]: Nested | string | boolean}
```
but this means losing the type guards around the defined keys, at which point I might as well just permit arbitrary JSON.

Am I just implementing this incorrectly? Any help on this would be appreciated, as it's a pretty serious hindrance to being able to rewrite some of the configuration JSON in our project.

**Comment by JacobWeisenburger** [comment]
This seems like a bug, but I'm not sure how to fix it
