### ISSUE TITLE
z.discriminatordUnion can't handle Unions

### ISSUE THREAD

**Issue by WORMSS** [colinhacks/zod#2121]
`z.discriminatordUnion()` can't handle `z.union()`

```ts
const baseAttribute = const baseAttribute = z.object({
  name: nameSchema,
  code: z.string(),
});
const linkAttribute = baseAttribute.extend({
  type: z.literal('Link'),
  options: z.object({
    code: z.string(),
  }),
});
const otherAttribute = baseAttribute.extend({
  type: z.union([
    z.literal('Time'),
    z.literal('GeoJson'),
    z.literal('Boolean'),
  ]),
});

export const attributeSchema = z.discriminatedUnion('type', [linkAttribute, otherAttribute]);
```

I've just seen that you want to deprecate discriminatedUnion from #2109 

But I was hoping this would be a super quick fix.
```ts
else if (type instanceof ZodUnion) {
  const accumulator = [];
  for ( const option of type.options ) {
    const types = getDiscriminator(option);
    if (types === null) {
      return null; // nested is of unknown type.
    }
    accumulator.push(...types);
  }
  return accumulator;
}
```

**Comment by JacobWeisenburger** [comment]
considering `discriminatedUnion` is going to be deprecated. I'm not sure any more work should be done on it.

@colinhacks thoughts?

**Comment by JacobWeisenburger** [comment]
@WORMSS, I'm going to close this issue. Feel free to reopen if you have more to say.

**Comment by stdedos** [comment]
Is there a plan for that depreciation? It seems that https://github.com/colinhacks/zod/issues/2106 was last updated last month.

Would there be a "quick fix" that would address this instead?

**Comment by dplantera** [comment]
> Is there a plan for that depreciation? It seems that #2106 was last updated last month.
> 
> Would there be a "quick fix" that would address this instead?

You might wanna checkout https://github.com/colinhacks/zod/pull/1845#issuecomment-1481606778  where [teunmooij](https://github.com/teunmooij) introduced a dedicated fix with z.enum support which could handle your usecase. z.enum works fine for primitive homogeneous discriminator properties like in your example. 

[zod.discriminatedunion](https://www.npmjs.com/package/zod.discriminatedunion).
