### ISSUE TITLE
UUID validation fails

### ISSUE THREAD

**Issue by cplummer-linq** [colinhacks/zod#2122]
Using Zod 3.20.6.

I have a guid that doesn't pass validation. Unit tests:

```
import { z } from 'zod';

describe('Validation Tests', () => {
  // f4405c78-1a39-4d59-9d8a-7e56d5e13294
  // 852e395d-693e-ed11-809a-c971856d9437

  it('should succeed, correctly', async () => {
    const schema = z.object({
      value: z.string().trim().uuid(),
    });
    const parsed = schema.safeParse({ value: 'f4405c78-1a39-4d59-9d8a-7e56d5e13294' });
    expect(parsed.success).toStrictEqual(true);
  });

  it('should succeed, but does not', async () => {
    const schema = z.object({
      value: z.string().trim().uuid(),
    });
    const parsed = schema.safeParse({ value: '852e395d-693e-ed11-809a-c971856d9437' });
    expect(parsed.success).toStrictEqual(true);
  });
});
```

**Comment by WORMSS** [comment]
```diff
- expect(parsed.success).toStrictEqual(true);

+ expect(parsed.success).toStrictEqual(true);
```

**Comment by cplummer-linq** [comment]
Hmmm... it's a generated guid from a SQL database. Can uuid() not be used on those types of values?

**Comment by WORMSS** [comment]
GUID or UUID? which is it making?

**Comment by cplummer-linq** [comment]
I'd like validate a GUID which can come from the NEWID() or NEWSEQUENTIALID() functions in SQL.
https://learn.microsoft.com/en-us/sql/t-sql/functions/newsequentialid-transact-sql?view=sql-server-ver16

They even call it UUID in their docs:
https://learn.microsoft.com/en-us/windows/win32/api/rpcdce/nf-rpcdce-uuidcreatesequential

**Comment by cplummer-linq** [comment]
I just retested, and using all upper case for that value didn't matter.

**Comment by cplummer-linq** [comment]
https://learn.microsoft.com/en-us/sql/t-sql/functions/newid-transact-sql?view=sql-server-ver16

![image](https://user-images.githubusercontent.com/103345240/222234896-62d76d5f-dfd8-4298-aced-b20ecc35c3e6.png)

https://www.rfc-editor.org/rfc/rfc4122

No, I haven't read this RFC, just providing links for reference.

**Comment by cplummer-linq** [comment]
Clarification. NEWSEQUENTIALID() is not RFC4122 compliant.

![image](https://user-images.githubusercontent.com/103345240/222240906-89824d9e-c860-4b01-ac4b-b7eb313682e4.png)

I'm guessing this is the answer, and that your uuid() method only supports RFC4122.

**Comment by jameswilliamknight** [comment]
Reproduced ([codesandbox link](https://codesandbox.io/p/sandbox/trusting-mayer-p2h4nv?file=%2Fsrc%2Findex.ts%3A19%2C44))

```ts
import test from "node:test";
import assert from "node:assert/strict";
import { z } from "zod";

const schema = z.object({
  foo: z.string().uuid(),
});

const valid = { foo: "aa78d6cc-f008-5138-6a42-115f5f7814d7" };

const invalid = { foo: "2cd1d902-9ef9-f669-f439-02a394b672ca" };

test("valid", () => {
  const result = schema.safeParse(valid);
  assert.ok(result.success);
});

test("invalid", () => {
  const result = schema.safeParse(invalid);
  assert.ok(!result.success);
});

```

```
Restarting 'src/index.ts'
✔ valid (2.122736ms)
✔ invalid (0.676192ms)
ℹ tests 2
ℹ pass 2
ℹ fail 0
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 9.598358
Completed running 'src/index.ts'
```
