### ISSUE TITLE
DeepPartial Array length validation

### ISSUE THREAD

**Issue by marcpaskell** [colinhacks/zod#2127]
Hi! So just stumbled upon this, it would appear that something in 3.8 broke the way array().min() works with deepPartial()

If you check this codepen 

https://codepen.io/pasco82/pen/GRXmJgV?editors=0011

with v 3.7.1

```
{
  "success": false,
  "error": {
    ....
  }
}
```

but with v 3.8.1

```
{
  "success": true,
  "data": {
    "clientContacts": []
  }
}
```

Is there a change in syntax i've missed somewhere?

thanks in advance 👍

**Comment by JacobWeisenburger** [comment]
Bug Confirmed:

```ts
const schema = z.object( { array: z.string().array().min( 42 ).optional() } )

// works as expected
console.log( schema.safeParse( {} ).success ) // true

// works as expected
console.log( schema.safeParse( { array: [] } ).success ) // false
```

```ts
const schema = z.object( { array: z.string().array().min( 42 ) } ).deepPartial()

// works as expected
console.log( schema.safeParse( {} ).success ) // true

// should be false, but is true
console.log( schema.safeParse( { array: [] } ).success ) // true
```

**Comment by colinhacks** [comment]
Good catch @marcpaskell - that's a seriously old bug.

**Comment by marcpaskell** [comment]
thanks all for jumping on this so quickly

**Comment by JacobWeisenburger** [comment]
this bug seems to be fixed, but now vscode is saying that `deepPartial` is deprecated
