### ISSUE TITLE
Inverse of `z.infer`?

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [colinhacks/zod#2131]
I am not looking to generate dynamic code from static code like in #53. `z.infer` goes from `z.ZodType` to "unwrapped" TypeScript types. How do you implement the inverse? I tried the following but does not seem to work:

```
X extends z.infer<infer Y> ? Y : never
```

**Comment by JacobWeisenburger** [comment]
It seems that you are asking for the ability to take a normal type and infer a zod schema from it. Is this correct?

this might be related to https://github.com/colinhacks/zod/discussions/1928

**Comment by make-github-pseudonymous-again** [comment]
Yep, going from an output type to a Zod schema type. That discussion is very relevant. So I guess it's just `z.ZodType<Output>` modulo details.

**Comment by JacobWeisenburger** [comment]
is it ok if I mark this as a duplicate of that?

**Comment by make-github-pseudonymous-again** [comment]
No problem! Go ahead.
