### ISSUE TITLE
Strict `z.tuple(...)`

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [colinhacks/zod#2133]
Can we have the equivalent of `z.object(...).strict()` but for tuples? Currently the tuple type is inferred as `[A, B, ...unknown[]]` which does not match `[A, B]`(TypeScript  4.9.4). Using `z.tuple([zodA, zodB]).rest(z.never())` does not solve the problem.

**Comment by make-github-pseudonymous-again** [comment]
Wait, shouldn't `z.tuple([zodA, zodB])` already map to the strict tuple type? Why is my usage generating the `...unknown[]` tail? Here is roughly what I am doing:

```ts
const schema = z.tuple([
	z.date(),
	z.number(),
	z.array(
		z.tuple([
			z.number(),
			z.number(),
		])
	),
]);

const parse = <S extends z.ZodTuple>(schema: S, ...args: z.infer<S>) => schema.parse(args);

parse(schema, new Date(), 3, [[1, 2], [3, 4]]);
```

**Comment by colinhacks** [comment]
It should and it does. You're likely seeing unexpected behavior because you don't have `"strict"" true` in your tsconfig.

![Uploading Screenshot 2023-03-03 at 1.04.10 PM.png…]()

**Comment by make-github-pseudonymous-again** [comment]
Thanks! `"strict"` was already true, but toggling `"strictNullCheck"` which was false had some effect.

**Comment by colinhacks** [comment]
@make-github-pseudonymous-again Ah, yeah. Gonna need that too. Actually it's the most important part lol.
