### ISSUE TITLE
Make `z.object().passthrough()` transform infered type

### ISSUE THREAD

**Issue by Sc0ra** [colinhacks/zod#2135]
When you are using the `passthrough` function on an object schema, you are effectively affecting the result of the `parse function and allow it to return additional keys.
However, the `z.infer` type utils doesn't reflect it

Indeed, the 2 following schemas return the same infered type

```ts

const schema1 = z.object({ foo: z.string() });
const schema2 = z.object({ foo: z.string() }).passthrough();

type Schema1 = z.infer<typeof schema1>
// Schema1 = { foo: string; }

type Schema2 = z.infer<typeof schema2>
// Schema2 = { foo: string; }

```

While there is a difference in the return of `parse`

```ts

const result1 = schema1.parse({ foo: 'test', bar: 'test' })
// result1 = { foo: 'test' };

const result2 = schema2.parse({ foo: 'test', bar: 'test' })
// result2 = { foo: 'test',  bar: 'test };

```

I think it would be useful to change the behaviour of `z.infer` (and thus the return type of the `parse` function) to reflect this difference.
For example:

```ts

const schema = z.object({ foo: z.string() }).passthrough();

type Schema = z.infer<typeof schema>
// Schema = { foo: string; [key: string | number | symbol]?: unknown; }

```

**Comment by colinhacks** [comment]
This has been added in Zod 3.21.
