### ISSUE TITLE
Feature request: Add "Did you mean X?"

### ISSUE THREAD

**Issue by timsuchanek** [colinhacks/zod#214]
When misspelling a property in an object type, I get such an error right now:
```
Error: 1 validation issue(s)

  Issue #0: unrecognized_keys at 
  Unrecognized key(s) in object: 'errorrFormat'

    at new ZodError (/root/code/runtime-validation/node_modules/zod/src/ZodError.ts:124:5)
```
It would be great, if a "Did you mean `errorFormat`?" could be shown.

[In Prisma Client, we're using `js-levenshtein` for that purpose](https://github.com/prisma/prisma/blob/32b25e4ca23d068e123548454b0461ea60cb4999/src/packages/client/src/runtime/utils/common.ts#L190) (after comparing all the 500 levenshtein implementations on NPM 😄  )

**Comment by vriad** [comment]
Hey Tim - excited to see you're using Zod! 

This feature might be a little too small to warrant adding Zod's first dependency :) But I'll see if I can copy/paste in a minimal Levenshtein implementation without increasing the bundle size too much. 🤙
