### ISSUE TITLE
Can't generically compose + transform schema without type error

### ISSUE THREAD

**Issue by johtso** [colinhacks/zod#2146]
Say I want to do something like this:

https://tsplay.dev/mq9bjm
```ts
import { z } from 'zod'

async function stripOuter<TData extends z.ZodTypeAny>(schema: TData, url: string): Promise<TData> {
  const zStrippedResponse = z
    .object({
      topLevelKey: schema,
    })
    .transform(data => {
      return data.topLevelKey
      //     ^?
    })
  
  return fetch(url)
    .then(response => response.json())
    .then(data => zStrippedResponse.parse(data))
}
```
I get the following type error:
```ts
Property 'topLevelKey' does not exist on type '{ [k in keyof baseObjectOutputType<{ topLevelKey: TData; }>]: baseObjectOutputType<{ topLevelKey: TData; }>[k]; }'.
```

Is this something I should be able to do? Any pointers where I'm going wrong?

**Comment by JacobWeisenburger** [comment]
Bug confirmed

```ts
function foo<Schema extends z.AnyZodObject> ( schema: Schema ) {
    return z.object( { bar: schema } ).transform( x => x.bar )
    //                                                   ^^^
    // Property 'bar' does not exist on type '{ [k in keyof baseObjectOutputType<{ bar: Schema; }>]: baseObjectOutputType<{ bar: Schema; }>[k]; }'.
}
```

**Comment by colinhacks** [comment]
This should be improved in `zod@canary`, give it a shot @johtso

**Comment by johtso** [comment]
@colinhacks all working with the latest release! You're an absolute legend getting that out so fast!

Is there by any chance a way to avoid having to assert that the generic schema is non-null? https://github.com/colinhacks/zod/blob/f9895ab1650ef3df9c598a8c43ede0160596ac2e/src/__tests__/generics.test.ts#L17

I feel like I actually want to type `TData` as something less generic.. I want to type it as any zod object schema.
Is there a way to do that? I tried `TData extends z.ZodObject<z.ZodRawShape>` but it's still saying `data.nested` could be undefined. I know the provided schema cannot result in undefined so it would be nice to be able to type it as that rather than using a non-null-expression.

**Comment by JacobWeisenburger** [comment]
> This should be improved in `zod@canary`

Is there a way to get `zod@canary` on deno?

**Comment by JacobWeisenburger** [comment]
@colinhacks 

Still a problem in `zod@canary`

```ts
// zod@canary
import { z } from 'zod'

function foo<Schema extends z.AnyZodObject> ( schema: Schema ) {
    return z.object( { bar: schema } ).transform( x => x.bar )
    //                                                   ^^^
    // Property 'bar' does not exist on type
    // '{ [k in keyof baseObjectOutputType<{ bar: Schema; }>]: baseObjectOutputType<{ bar: Schema; }>[k]; }'.
}
```

**Comment by johtso** [comment]
@JacobWeisenburger canary releases don't seem to be triggering, I _think_ this should fix it? https://github.com/colinhacks/zod/pull/2148

**Comment by daguitosama** [comment]
Im experiencing a very similar issue with the `safeParse` function return type:

```ts
function parseNameAndUpdateNameError(name: string): string {
    const nameSchema = z.string().min(1).max(10).trim()
    const result = nameSchema.safeParse(name);
    if(!result.success){
        var nameErrorMessage = result.error.issues[0].message;
        // update logic
    }
    return result.data;
    //            ^^^^
}

/**
* Error:
*   Property 'data' does not exist on type 'SafeParseReturnType<string, string>'.
*   Property 'data' does not exist on type 'SafeParseError<string>'.ts(2339)
*/
```

I have tested on `3.21.2` and the `canary` versions.

**Comment by daguitosama** [comment]
O I see, thanks so much for the help, I really appreciate it !

**Comment by JacobWeisenburger** [comment]
If you found my answer satisfactory, please consider supporting me. Even a small amount is greatly appreciated. Thanks friend! 🙏
https://github.com/sponsors/JacobWeisenburger

**Comment by colinhacks** [comment]
Thanks @johtso that fixed the CI 👍

@JacobWeisenburger that should be working now

**Comment by johtso** [comment]
@colinhacks just in case it got lost amongst the other messages, any thoughts on this? https://github.com/colinhacks/zod/issues/2146#issuecomment-1456174903

I can totally just live with telling typescript that the value will never be `undefined`, but very curious as to whether Zod already offers something for me to type my generic more accurately, or if it's something that might be worth adding..

**Comment by colinhacks** [comment]
Yeah, I noticed that and tried to fix it for a while. Then I realized it makes sense. `TData` can be any ZodSchema, including `ZodOptional`. When Zod "computes" the inferred type of a ZodObject, it adds the `?` to any schema might be optional. Because `TData` might be optional, the question mark gets added. It's weird but I think it's consistent & encourages defensive programming.

**Comment by johtso** [comment]
@colinhacks would it not make sense to be able to have my generic type variable extend something more specific in this case? I know I'm going to be dealing with non-optional `z.object` schemas.

**Comment by johtso** [comment]
Say I did something like this:
```ts
const nonOptionalObject = z.object({}).required()
function foo<TSchema extends typeof nonOptionalObject>(schema: TSchema, data: any) {
    const zUnwrapped = z
      .object({
        nested: schema,
      })
      .transform(data => {
        return data.nested
      })
   return zUnwrapped.parse(data)
```

Shouldn't the types convey the fact that the schema cannot result in undefined?
