### ISSUE TITLE
False positive for .email() validation with sub-domain present?

### ISSUE THREAD

**Issue by JK-WP** [colinhacks/zod#2154]
I've come across what I believe to be some false positives with the string `.email()` validation, where it doesn't appear to like subdomains. Here is a simple repro:
```
import { z } from 'zod';

const data = [
  'me@z.com',
  'me@y.z.com',
  'me@z.co.jp',
  'me@y.z.co.jp',
];

for (const email of data) {
  console.log(z.string().email().safeParse(email));
}
```
which produces:
```
{ success: true, data: 'me@z.com' }
{ success: false, error: [Getter] }
{ success: true, data: 'me@z.co.jp' }
{ success: false, error: [Getter] }
```
This is flagging up validation errors in my project for real email addresses resembling the 4th entry in the above repro.
I can see from the code that this behavior is driven by a rather formidable looking regexp; please could you clarify - is a validation failure on an address such as `me@y.z.co.jp` intentional? Thanks!

**Comment by fullstackzach** [comment]
Here's another valid example I noticed today, that can be common in the US.
`example@atlanta.k12.ga.us`

**Comment by pn320** [comment]
Is anyone else working on this, if not I'd be happy to pick it up!
