### ISSUE TITLE
`z.input` is lost with `.catch(someValue)`

### ISSUE THREAD

**Issue by apstanisic** [colinhacks/zod#2162]
When using `.catch`, I can no longer infer input value.
[reproduction](https://codesandbox.io/s/zod-catch-input-infer-yb0wo6) 

```ts
const schema = z.string().catch('String value')
// type is `undefined`, it should be `string`
type Input = z.input<typeof schema>
```

**Comment by colinhacks** [comment]
This is intentional. The inferred `Input` type represents the set of inputs that can be successfully parsed. When you add `.catch`, anything will pass validation so the `z.input` returns `unknown`.
