### ISSUE TITLE
Typecheck causes "heap out of memory" error 

### ISSUE THREAD

**Issue by cullylarson** [colinhacks/zod#2163]
`zod: 3.21.4`
`typescript: 4.9.5`

Running `tsc --noEmit` on a project that uses `zod` causes a "JavaScript heap out of memory" error.

This seems to only be an issue with zod `3.21.4`. Downgrading to `3.21.3` resolves it.

Sorry I don't have time to create a reproduction at the moment.

**Comment by cullylarson** [comment]
Potentially related to https://github.com/microsoft/TypeScript/issues/44299

**Comment by armtuk** [comment]
I am also having serious problems with memory issues. After adopting zod, my webpack frequently craps the bed with an out of memory error, and my IDE (IntelliJ) also seems to have serious problems with type introspection randomly just completely crapping out and suddenly I stop getting type errors in source files.  Using zod 3.20.6 and typescript 4.8.2. I've read various posts suggesting various things including upgrading, downgrading and such, and I'm not sure what to do.

**Comment by cullylarson** [comment]
@armtuk Not a solution, but FYI, TS isn't going to produce runtime issues. Once TS compiles to JS, it's out of the picture. Upgrading TS might help your IDE issues though.

**Comment by fergy-os** [comment]
We are experiencing the same problem with 3.21.4

@cullylarson the "heap out of memory" error happens during build time not at runtime,

**Comment by ymc9** [comment]
Having the same problem with 3.21.4.

**Comment by tvanantwerp** [comment]
I have a project using zod 3.22.3 and I had GitHub Actions failing with OOM errors on `tsc --noEmit` with TypeScript version 5 and up. I downgraded TypeScript to 4.9.5 and it worked fine. I tried going through the output of `tsc -p tsconfig.json --generateTrace traces --incremental false`, but couldn't find anything obvious and even swapping out complex types for `any` all over the place didn't seem to help much. I think it's a TypeScript issue.

**Comment by Wildhoney** [comment]
Can be fixed with adding a `resolutions` field to your root `package.json` as it's _probably_ cause by multiple versions of Zod.

For example:

```json
"resolutions": {
  "zod": "3.22.4"
}
```

**Comment by tmm1** [comment]
I'm running into this. With `zod@3.21.4` it works:

```
> tsc --build

       16.65 real        25.90 user         1.61 sys
```

but with `zod@3.22.0` or newer (same behavior seen w/ `3.23.8` and `3.24.0`):

```
> tsc --build
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 ELIFECYCLE  Command failed.
time: command terminated abnormally
       48.72 real        83.53 user         3.79 sys
```

raising `--max-old-space-size` is a workaround but typescript checking still takes much much longer than it used to.

This behavior is the same across node v20 and v22, and across various typescript versions (5.2 - 5.7).

**Comment by nerixim** [comment]
Same for me, had multiple versions of zod and @Wildhoney 's solution worked for me, thanks.

**Comment by RamatjyotSingh** [comment]
i was facing similar issue,,

I was importing my schemas from my schema package into api for type validation, which was causing it go OOM,  then with the help of chatgpt i did some change in package.json of my schema package and made a tsconfig for storing build output and made the api refer to types from build output and it somehow worked, used chatgpt for it

**Comment by NickDarvey** [comment]
> i was facing similar issue,,
> 
> I was importing my schemas from my schema package into api for type validation, which was causing it go OOM, then with the help of chatgpt i did some change in package.json of my schema package and made a tsconfig for storing build output and made the api refer to types from build output and it somehow worked, used chatgpt for it

what did you specifically do? same scenario and same problem for me

**Comment by RamatjyotSingh** [comment]
hi sorry couldnt duplicate the issue, i think the issue might be from different zod versions in differnt packages make sure all of them  have same version as dependency and then do a fresh install it might work then, lmk if it works
