### ISSUE TITLE
`z.enum().extract()`, and `z.enum().exclude()` should take variadic args

### ISSUE THREAD

**Issue by JacobWeisenburger** [colinhacks/zod#2168]
Before:
```ts
z.enum( [ 'foo', 'bar', 'baz' ] ).extract( [ 'foo', 'bar' ] )
```

After:
```ts
z.enum( [ 'foo', 'bar', 'baz' ] ).extract( 'foo', 'bar' )
```

I think this looks a lot cleaner, but I'm not sure of the implications for typescript. Any thoughts?

**Comment by galmarz** [comment]
@JacobWeisenburger z.enum accepts second a optional param, which I think makes rest params problematic here.

**Comment by JacobWeisenburger** [comment]
fair enough, perhaps just `extract` and `exclude` should take variadic args

**Comment by galmarz** [comment]
Small change so I created the PR to show the code. Personally I don't just mind passing array, but its not a huge change to support variadic args aswell.

**Comment by colinhacks** [comment]
I'd rather leave this as an array so we can support a parameters object down the road if necessary. Best to leave our options open for future API expansion.
