### ISSUE TITLE
z.string().email() allows slash in domain

### ISSUE THREAD

**Issue by the-bayer** [colinhacks/zod#2169]
Hello!

We noticed that parsing with `z.string().email()` method allows a slash in the domain of an email. However, I think I found the regex you use for checking emails, and a slash in the email does not match that regex, so it seems like this is a bug. Let me know if you have any other questions.

**Comment by joaoGabriel55** [comment]
I can work on that

**Comment by joaoGabriel55** [comment]
I saw here before start implementing and use slash for email is valid (e.g. test/test@test.com), take a look in this links:
https://en.wikipedia.org/wiki/Email_address#Local-part
https://www.ietf.org/rfc/rfc2822.txt

You can use this online validator too:
https://verifalia.com/validate-email

**Comment by colinhacks** [comment]
This is already addressed by https://github.com/colinhacks/zod/pull/2157 @joaoGabriel55 

Trying to save you some effort 🙏

**Comment by the-bayer** [comment]
@colinhacks Thanks for that change btw, super helpful 🙌🏼
