### ISSUE TITLE
Prisma XOR with Zod  > 3.21.1 not working

### ISSUE THREAD

**Issue by chrishoermann** [colinhacks/zod#2184]
We encounterd a bug when using generated prisma types with versions greater than `3.21.1`. 

You can reproduce the issue in the following repo:  https://github.com/chrishoermann/zod-prisma-types-bug

As you can read in the following discussion we first thought it was an issue with prisma, but after digging around and finding that the suspected type has been this way for a long time now @njdowdy found that this is a zod issue that happend somwhere in `3.21.2`

### Discussed in https://github.com/colinhacks/zod/discussions/2171

<div type='discussions-op-text'>

<sup>Originally posted by **chrishoermann** March  9, 2023</sup>
I've built a generator for prisma ([zod-prisma-types](https://github.com/chrishoermann/zod-prisma-types)) that throws a type error since prisma updated their `XOR` type in 4.11:

```ts
  type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

  /**
   * XOR is needed to have a real mutually exclusive union type
   * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
   */
  type XOR<T, U> =
    T extends object ?
    U extends object ?
      (Without<T, U> & U) | (Without<U, T> & T)
    : U : T
```

before this type update the following zod schema worked without problems:

```ts
export const UserCreateInputSchema: z.ZodType<Prisma.UserCreateInput> = z.object({
  id: z.string().cuid().optional(),
  email: z.string().email({ message: "Invalid email address" }),
  name: z.string().min(1).max(100).optional().nullable(),
  role: z.union([ z.lazy(() => UserCreateroleInputSchema),z.lazy(() => RoleSchema).array() ]).optional(),
  enum: z.lazy(() => AnotherEnumSchema).optional(),
  scalarList: z.union([ z.lazy(() => UserCreatescalarListInputSchema),z.string().array() ]).optional(),
  posts: z.lazy(() => PostCreateNestedManyWithoutAuthorInputSchema).optional(),
  profile: z.lazy(() => ProfileCreateNestedOneWithoutUserInputSchema).optional(),
  location: z.lazy(() => LocationCreateNestedOneWithoutUserInputSchema).optional(),
}).strict();

export const UserUncheckedCreateInputSchema: z.ZodType<Prisma.UserUncheckedCreateInput> = z.object({
  id: z.string().cuid().optional(),
  email: z.string().email({ message: "Invalid email address" }),
  name: z.string().min(1).max(100).optional().nullable(),
  role: z.union([ z.lazy(() => UserCreateroleInputSchema),z.lazy(() => RoleSchema).array() ]).optional(),
  enum: z.lazy(() => AnotherEnumSchema).optional(),
  scalarList: z.union([ z.lazy(() => UserCreatescalarListInputSchema),z.string().array() ]).optional(),
  lat: z.number(),
  lng: z.number(),
  posts: z.lazy(() => PostUncheckedCreateNestedManyWithoutAuthorInputSchema).optional(),
  profile: z.lazy(() => ProfileUncheckedCreateNestedOneWithoutUserInputSchema).optional(),
}).strict();

export const UserCreateArgsSchema: z.ZodType<Prisma.UserCreateArgs> = z.object({
  select: UserSelectSchema.optional(),
  include: UserIncludeSchema.optional(),
  data: z.union([ UserCreateInputSchema,UserUncheckedCreateInputSchema ]),
}).strict()
```

so a simple union was sufficient to satisfy typescript. in Prisma 4.11 typescript now throws the following error because, as I see it, the `Without<...>` type can not be satisfied with a union anymore:
```
Type 'ZodObject<{ select: ZodOptional<ZodType<UserSelect, ZodTypeDef, UserSelect>>; include: ZodOptional<ZodType<UserInclude, ZodTypeDef, UserInclude>>; data: ZodUnion<...>; }, "strict", ZodTypeAny, { ...; }, { ...; }>' is not assignable to type 'ZodType<UserCreateArgs, ZodTypeDef, UserCreateArgs>'.
  The types of '_type.data' are incompatible between these types.
    Type '(UserCreateInput | UserUncheckedCreateInput) & (UserCreateInput | UserUncheckedCreateInput | undefined)' is not assignable to type '(Without<UserCreateInput, UserUncheckedCreateInput> & UserUncheckedCreateInput) | (Without<...> & UserCreateInput)'.
      Type 'UserCreateInput & UserUncheckedCreateInput' is not assignable to type '(Without<UserCreateInput, UserUncheckedCreateInput> & UserUncheckedCreateInput) | (Without<...> & UserCreateInput)'.
        Type 'UserCreateInput & UserUncheckedCreateInput' is not assignable to type 'Without<UserUncheckedCreateInput, UserCreateInput> & UserCreateInput'.
          Type 'UserCreateInput & UserUncheckedCreateInput' is not assignable to type 'Without<UserUncheckedCreateInput, UserCreateInput>'.
            Types of property 'lat' are incompatible.
              Type 'number' is not assignable to type 'undefined'.
```

I'm currently a bit stuck on how to solve this issue because I don't really know how to implement the `Without<...>` type especially because the `z.ZodType<...>` does not provide the object helper methods that would have been my first guess on how to approach this. Any help is appreciated.
</div>

**Comment by ymc9** [comment]
Thanks for creating the issue @chrishoermann ! I'm working [zenstack](https://github.com/zenstackhq/zenstack) and hit by the same thing 😄.

**Comment by cimchd** [comment]
We have the same problem. Since almost 3 month now we are stuck to using zod in version 3.21.1. 
We put a resolutions entry at the top of our monorepo:
```json5
// package.json
{
  // ...
  "resolutions": {
    "zod": "<=3.21.1",
  }
}
```

**Comment by ymc9** [comment]
This issue has been here for a while 😄. Just wondering if it's on the radar for a fix soon.

**Comment by Intevel** [comment]
It seems like this bug does not occur in v4.16.1 of Prisma 👍🏼

**Comment by oceandrama** [comment]
@Intevel No, I can confirm same error with `prisma@14.16.1` and `zod@3.21.4`

**Comment by Intevel** [comment]
> @Intevel No, I can confirm same error with `prisma@14.16.1` and `zod@3.21.4`

Did you updated your @prisma/client aswell?

**Comment by oceandrama** [comment]
> Did you updated your @prisma/client aswell?

Yes, sure

**Comment by artem-alek** [comment]
Waiting for an update as well. Stuck here too

**Comment by ymc9** [comment]
If it's confirmed to be a bug, I'd like to try making a fix.

**Comment by ymc9** [comment]
Hi @colinhacks , we need some attention here 😄. Many people build Prisma related tools using zod and all likely blocked to some extent.

**Comment by fer112233** [comment]
This issue needs to get more attention!

**Comment by aronmal** [comment]
I do agree. I sadly have switched to dirzzle for new projetcs by now.

**Comment by laneme** [comment]
Zod sure has a lot of open issues for a validation library. No wonder its the most used these days.

This is probably gonna take some time to get picked up without a random dev stepping in.

**Comment by ksdaylight** [comment]
Hope this problem can be solved .

**Comment by Darkbound** [comment]
Here to add some weight to the issue

**Comment by dominic-schmid** [comment]
I've got that same problem. Is there any workaround in the meantime (that isn't downgrading)?

**Comment by CasperSK89** [comment]
We need this fixed :-)

**Comment by rickylabs** [comment]
Any news on this topic ? This is a blocking issue that prevent us to generate types from Prisma schema with latest Zod release

**Comment by KenAdams-AK** [comment]
setting up the following rule in `tsconfig.json` might be a solution.
```javascript
{
    "compilerOptions": {
        "strictNullChecks": true   
    }
}
```

**Comment by sergej2705** [comment]
When will the fix be released?

**Comment by colinhacks** [comment]
This fix has landed in `zod@beta`
