### ISSUE TITLE
Property 'ulid' does not exist on type 'ZodString'.

### ISSUE THREAD

**Issue by michealroberts** [colinhacks/zod#2186]
Not sure if this is a known issue, but on the latest version of zod (3.21.4*) throws a typescript error on ulids ...

<img width="548" alt="Screenshot 2023-03-11 at 12 08 09" src="https://user-images.githubusercontent.com/84131395/224483519-53ac6b92-d566-4255-b0d7-2ac491dc29ae.png">

*at the time of writing

**Comment by JacobWeisenburger** [comment]
Everything is working fine for me. Please send a full reproducible code example.

```ts
z.string().ulid() // no errors
```

**Comment by michealroberts** [comment]
Hi @JacobWeisenburger yes this was indeed my fault, I was referencing 3.21.4 is most places in the monorepo, but in the package with the fault it was referencing ^3.0.0., closing this as resolved.
