### ISSUE TITLE
z.object.pick could accept arrays

### ISSUE THREAD

**Issue by ivanquirino** [colinhacks/zod#2188]
When using `.pick` or `.omit`, it would be nice to have the method also accept an array with strings with keys to pick/omit. For example:
```javascript
z.object({
  name: z.string(),
  address: z.string(),
  phone: z.string()
}).pick(['name', 'phone']);
```
Has anyone thought of that? Any drawbacks? I would be happy to contribute.

**Comment by colinhacks** [comment]
That's been proposed and I'm opposed: https://github.com/colinhacks/zod/issues/1563
