### ISSUE TITLE
Exclude `NaN` from `z.number()` schema type

### ISSUE THREAD

**Issue by Drafter500** [colinhacks/zod#2189]
TS is fully okay with this kind of schema:
`z.number().default(Number.NaN)`

`z.number()` schema returns a number type and `NaN` is of type number. All good here. 
but when we feed an `undefined` value to this schema parser fails with `"message": "Expected number, received nan"`.
So it happily substituted provided `NaN` and then rejected it. 
If zod considers `NaN` as not a valid number, it should be reflected in the type level too. 

I know I can fix the error with `z.number().or(z.nan()).default(Number.NaN)`. But that is not my point. My point is to have typing inline with validation so that forgotten `.or(z.nan())` would be immediately spotted and not gonna cause unexpected validation failure on runtime.

**Comment by JacobWeisenburger** [comment]
I'm not sure that what you are asking for is possible. Because TypeScript considers `NaN` to be a `number` type, it is not possible to exclude it from the `number` type.
```ts
type Num = Exclude<number, typeof NaN>
// type Num = never
```

**Comment by colinhacks** [comment]
As Jacob said, not fixable under TypeScript's type system. There's no way to represent `Exlude<number, typeof NaN>` statically.

**Comment by make-github-pseudonymous-again** [comment]
I am not sure I understand what was discussed here. When I use `z.number()` I sometimes get this:

```js
error: [
  {
    "code": "invalid_type",
    "expected": "number",
    "received": "nan",
    "path": [
      0,
      "price"
    ],
    "message": "Expected number, received nan"
  },
  {
    "code": "invalid_type",
    "expected": "number",
    "received": "nan",
    "path": [
      0,
      "paid"
    ],
    "message": "Expected number, received nan"
  }
]
```
