### ISSUE TITLE
Object.nullable and Object.nonNullable

### ISSUE THREAD

**Issue by darkbasic** [colinhacks/zod#2190]
`Object.partial()` is very handy to make properties optional, but sometimes you want to make properties nullable instead (for example when you make SQL unions) and there is no method to do so.

I'm achieving the same result with custom functions but it's very inconvenient:

```
export function toNullableOrOptionalShape(
  shape: ZodRawShape,
  type: "nullable" | "optional"
): ZodRawShape {
  return Object.entries(shape).reduce<ZodRawShape>((acc, [key, value]) => {
    acc[key] = value[type]();
    return acc;
  }, {});
}

export function toNullableObject<
  T extends ZodRawShape,
  UnknownKeys extends UnknownKeysParam = UnknownKeysParam,
  Catchall extends ZodTypeAny = ZodTypeAny
>(
  object: ZodObject<T>
): ZodObject<
  {
    [k in keyof T]: ZodNullable<T[k]>;
  },
  UnknownKeys,
  Catchall
> {
  return new ZodObject({
    ...object._def,
    shape: () => toNullableOrOptionalShape(object.shape, "nullable"),
  }) as any;
}
```

I would love to have an `Object.nullable()` method and I could PR it if you are interested in having such feature.

We also need the equivalent of `Object.required` (`Object.nonNullable`?) to mark fileds as non-nullable.

**Comment by pleunv** [comment]
Also interested in this, have a similar use-case where the input schema is more permissive than the output schema (e.g. `initialValues` is inferred from an input schema and can have nullable values while submission data is using an output schema and _needs_ to have its values set). Would be handy if there was a way to base these schemas on one another.

**Comment by darkbasic** [comment]
@pleunv you're in luck then because I've just implement this and much more: https://github.com/colinhacks/zod/pull/2234

**Comment by ShravanSunder** [comment]
Would be great to have #2234

**Comment by darkbasic** [comment]
> Would be great to have https://github.com/colinhacks/zod/pull/2234

Would be great to at least know @colinhacks opinion about that PR.
I'm currently already using that PR via yarn patches but if he doesn't envision ever merging it I might start looking for alternatives.
If it's just a matter of him still not having enough time to review it I might be fine with the patches though.

**Comment by sezanzeb** [comment]
nonNullable should be equivalent to typescripts `NonNullable<>` type in my opinion. I have created a pull request for this: https://github.com/colinhacks/zod/pull/3141

**Comment by colinhacks** [comment]
I understand the impulse, but this is a little to niche to go into Zod core. This is better implemented with a transform. 

```ts
const A = z.string().nullable().transform((val, ctx) => {
  if(val === null) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: "Cannot be null",
      path: [],
    })
    return z.NEVER;
  }
  return val;
})

type A = z.infer<typeof A>;
// string
```
