### ISSUE TITLE
External Types Library using inferred types from Zod Schema not being declared correctly

### ISSUE THREAD

**Issue by bpneal** [colinhacks/zod#2194]
**Background:**

I have a TS node service that uses zod schemas for validation, and types inferred from these, ie:

```JS
export type MyType = z.infer<typeof mySchema>;
```

These types are then exported into a private NPM library, so I can use them across other projects making use of the TS node service.

```
tsc --emitDeclarationOnly
```

**Problem:**

The types, within the TS node service (where they are defined) are working correctly and as expected, however the types exported / imported from the NPM package are incorrect.

Consider the example below...

```JS
const mySchema = z.object({
  id: z.string(),
  x: z.number(),
  y: z.number(),
});

export type MyType = z.infer<typeof mySchema>;
```

**Expected:**

_This is how they are being correctly inferred within the Node Service code_

```JS
type MyType = {
  id: string;
  x: number;
  y: number;
}
```

**Actual:**

_This is how they are being imported from the npm package within external code_

```JS
type MyType = z.infer<z.ZodObject<{
  id: z.ZodString;
  x: z.ZodNumber;
  y: z.ZodNumber;
}>>
```

**Bug:**

The exported type definitions should correctly match the inferred types.

**Comment by MichiruNakam** [comment]
How this was solved? Its happening to me

**Comment by bpneal** [comment]
I resolved this by installing zod as a dependency of the project using the inferred types
