### ISSUE TITLE
Change in 3.21.2 breaks assignability of schema created from generics' parsed and inferred type

### ISSUE THREAD

**Issue by conorbrandon** [colinhacks/zod#2196]
I have a need to create a zod object schema that only has one key-value pair. This may not be exactly the best way to do something like this (and this is a contrived example), but in version 3.21.1, it was possible to assign the parsed data to the inferred type of a schema created through generic parameters:

```ts
import { z } from 'zod';

const createSchemaAndParse = <K extends string, VS extends z.ZodString>(key: K, valueSchema: VS, data: unknown) => {
  const schema = z.object({
    [key]: vSchema
  });
  const parsed = schema.parse(data);
  const inferred: z.infer<z.ZodObject<{ [k in K]: VS }>> = parsed; // this line errors in 3.21.2
  return inferred;
};
createSchemaAndParse('foo', z.string(), { foo: '' });
```

Unfortunately, with 3.21.2 (and above), the above line now produces a type error.

**Comment by chrishoermann** [comment]
Maybe related to this #2184?
