### ISSUE TITLE
Schema type returned with .transform()

### ISSUE THREAD

**Issue by ClementLaval** [colinhacks/zod#2199]
Hi, this is my target Type, (look at companyName):
<img width="331" alt="image" src="https://user-images.githubusercontent.com/82887830/225385816-d974e147-09ce-4755-ba67-4257c9013687.png">

I'm creating this Schema to represent the API part and transform data to fit my target Type:
<img width="856" alt="image" src="https://user-images.githubusercontent.com/82887830/225386156-842814fe-9086-4b0b-8702-b8e193dc6939.png">

He understood that companyName is missing compare to target Type.

Now let's add this key, and why not modify the output structure to fit with my Target:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/82887830/225389089-157d8411-2892-4832-8dc6-a4a7f511ab01.png">

Typescript is still complaining of missing companyName key.

**Comment by JacobWeisenburger** [comment]
Please send a full reproducible code example.
