### ISSUE TITLE
Feature request: is boolean true?

### ISSUE THREAD

**Issue by nimabrownlee** [colinhacks/zod#220]
Hey, 
First time using Zod. Is there a function like `nonempty()` for booleans? Or do you have to use refine?

`is(true)` or `is(false)`

**Comment by colinhacks** [comment]
If you want something that *must* be true, I recommend using `z.literal(true)`. In this scenario the inferred type signature will be `true`, not `boolean`. If you prefer the inferred type to be `boolean`, you should use refinements. It seems weird to use the term "nonempty" to apply to booleans. It's kinda weird for strings as well but 🤷‍♂️

**Comment by nimabrownlee** [comment]
@colinhacks

Hey, thanks for the quick response. My problem with literal was that I couldn't use a custom message. Is that possible?

**Comment by colinhacks** [comment]
Not currently :/ You can track that at #97

**Comment by nicolasey** [comment]
> If you want something that _must_ be true, I recommend using `z.literal(true)`. In this scenario the inferred type signature will be `true`, not `boolean`. If you prefer the inferred type to be `boolean`, you should use refinements. It seems weird to use the term "nonempty" to apply to booleans. It's kinda weird for strings as well but 🤷‍♂️

`z.literal<boolean>(true)` and your problem gets away

**Comment by finci-square** [comment]
> > If you want something that _must_ be true, I recommend using `z.literal(true)`. In this scenario the inferred type signature will be `true`, not `boolean`. If you prefer the inferred type to be `boolean`, you should use refinements. It seems weird to use the term "nonempty" to apply to booleans. It's kinda weird for strings as well but 🤷‍♂️
> 
> `z.literal<boolean>(true)` and your problem gets away

Came across this thread because I experienced the same issue. We have a form where we want the user to explicitly check the box to acknowledge terms.  This workaround is what i needed but not obvious!  

It seems to be more intuitive to do something like `.boolean().true()`.

**Comment by Herikle** [comment]
> @colinhacks
> 
> Hey, thanks for the quick response. My problem with literal was that I couldn't use a custom message. Is that possible?



3 years late but... you can do this:

`yourField: z.literal<boolean>(true, {
      errorMap: () => ({
        message: "Custom message here",
      }),
    }),`

**Comment by zacrodrigues** [comment]
@Herikle Nice man!! Thank you for share.

**Comment by oke-yomi** [comment]
> If you want something that _must_ be true, I recommend using `z.literal(true)`. In this scenario the inferred type signature will be `true`, not `boolean`. If you prefer the inferred type to be `boolean`, you should use refinements. It seems weird to use the term "nonempty" to apply to booleans. It's kinda weird for strings as well but 🤷‍♂️


Late solution here but this could also work: 
```
consent: z.boolean().refine((val) => val === true, {
    message: "Please read and accept the terms and conditions",
  })
```

**Comment by gio-shara-code** [comment]
@oke-yomi great solution, although you don't need to explicitly compare with `true` value like this `val===true`. Instead:
```ts
'privacy-policy': z.boolean().refine((val) => val, {
          message: 'Please read and accept the terms and conditions'
        })
```

**Comment by pierrejoye** [comment]
Just came across this as well. And found about coerce which looked promising but not :)

https://app.studyraid.com/en/read/11289/352179/boolean-schema-implementation

As described above, they are easy ways around that but it looks counter intuitive.

const result1 = coercedBoolSchema.parse("true"); // Returns: true
const result2 = coercedBoolSchema.parse(1); // Returns: true
const result3 = coercedBoolSchema.parse("false"); // Returns: true
const result4 = coercedBoolSchema.parse(0); // Returns: false
