### ISSUE TITLE
Bug: Inconsistent "Expected never, received array" in v2

### ISSUE THREAD

**Issue by mmeylan** [colinhacks/zod#222]
**Environment:**

> Node 12.18.2
> Webpack 4.44.2
> Zod 2.0.0-beta.21

```json
// tsconfig.json
// target: commonjs2
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2019",
    "lib": ["es2020"],
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": false,
    "inlineSourceMap": true,
    "inlineSources": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strictPropertyInitialization": false,
    "typeRoots": ["./node_modules/@types", "./typings"]
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*.test.ts", "**/*.it.ts"]
}
```

**Error**

I'm experiencing the following error when the parser encounters an **unknown field**: `Expected never, received array`. 

The weirdest thing is that this does not happen in local development, but it only happens when files are bundle with webpack and production mode.

**Expected result**

According to v2 doc: _By default Zod object schema strip unknown keys from the output._

**Code**

Here's a snippet of code that I have:

```typescript
const atAgencySchema = z
  .object({
    agencyId: z.string(),
    market: z.enum(['X', 'Y', 'Z']),
    name: z.string(),
  })

// ...
const record = { agencyId: 'id', market: 'Y', name: 'yo', skills: ['1'] } 
atAgenciesSchema.parse(record) // throws "Expected never, received array"
```

**Workaround**

Reverted back to v1, and used `nonstrict()`

**Comment by colinhacks** [comment]
I'm having trouble replicating this. If you could create a GitHub repo with a minimal reproduction that would be great.

**Comment by mmeylan** [comment]
Sure. Here it is: https://github.com/mmeylan/zod-bug-reproduction

**Comment by yhatt** [comment]
Hi, I've met the same trouble too. It seems that webpack's default Terser compression in production mode will break zod.

Preventing minify of function names that has starting from "Zod" have  helped me.

```javascript
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
  ...,
  optimization: {
    minimize: true,
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          keep_fnames: /^Zod/,
        },
      }),
    ],
  },
  ...
}
```

**Comment by colinhacks** [comment]
Okay I've identified the problem! Very silly mistake on my part in the parsing logic. Fixed in beta 22. Thanks for the great repro @mmeylan.

**Comment by mmeylan** [comment]
Awesome, thanks for the great work @colinhacks

**Comment by bvandercar-vt** [comment]
> Hi, I've met the same trouble too. It seems that webpack's default Terser compression in production mode will break zod.
> 
> Preventing minify of function names that has starting from "Zod" have helped me.
> 
> ```js
> const TerserPlugin = require('terser-webpack-plugin');
> 
> module.exports = {
>   ...,
>   optimization: {
>     minimize: true,
>     minimizer: [
>       new TerserPlugin({
>         terserOptions: {
>           keep_fnames: /^Zod/,
>         },
>       }),
>     ],
>   },
>   ...
> }
> ```

I am seeing a similar problem, @colinhacks , but with Vite / Vitest. Unless I add the following to my Vite config:

```typescript
   optimizeDeps: {
      exclude: ['vite'],
    },
   test: {
      alias: {
        zod: path.resolve('./node_modules/zod/lib/index.js'),
      },
```

I get "`Expected never, received <var type>`" when unexpected props are present. It essentially acts as a `.strict()` when Vite compiles-- adding the above to my config fixes the issue, but it's still a bug.
