### ISSUE TITLE
Keep type after parsing

### ISSUE THREAD

**Issue by Askhento** [colinhacks/zod#2226]
Is there any way to get which type parsed.
I am parsing some json file and would like to show different ui elements based on the actual type of keys.
For example I have key which could be a string, number or array of strings or numbers. 

@JacobWeisenburger 
Update0: 

Here I tried to achieve the idea using transform. Is there any better way to do this?
```js
const testType = z.union([
    z.string().transform((val) => {

        return {
            value: val,
            type: 'string'
        };
    }),
    z.number().transform((val) => {
        return {
            value: val,
            type: 'number'
        }
    })
]).array()

const testArray = [1, "string", 2, 3];

const parseResult = testType.safeParse(testArray);

if (parseResult.success) {
    console.log(parseResult.data);
} else {
    console.log(parseResult.error)
}
```

**Comment by JacobWeisenburger** [comment]
Please send a full reproducible code example.

**Comment by Askhento** [comment]
@JacobWeisenburger That is really good, but what if I want to get types even in nested object and arrays
```js
[
    { value: 'foo', type: 'string' },
    { value: 42, type: 'number' },
    { value: true, type: 'boolean' },
    {
        value: {
            foo: {
                value: 'foo',
                type: 'string'
            },
            bar: {
                value: 42,
                type: 'number'
            },
            type: 'someOtherMoreComplexSchema'
        }
    }
]
```
Do I need some kind of recursive call? 

Another option would be to get separate object with structure same as parsed data.  Does Zod provide an api for that?

**Comment by JacobWeisenburger** [comment]
> Do I need some kind of recursive call?

Most likely yes.

> Another option would be to get separate object with structure same as parsed data. Does Zod provide an api for that?

I don't think so.
