### ISSUE TITLE
Please use paths instead of array indices for nested schema objects

### ISSUE THREAD

**Issue by cybervaldez** [colinhacks/zod#223]
```
const test = zod
  .object({
    name: zod
      .object({
        firstName: zod.string().nonempty({ message: "First name can not be empty." }),
        middleName: zod.string(),
        lastName: zod.string().nonempty(),
      })
      .refine((name) => name.firstName === name.middleName, {
        message: "First and Middle Name must be the same", // refinement test.
      }),
  })
  .safeParse({
    name: {
      firstName: "",
      middleName: "estrada",
      lastName: "",
    },
  }).error.flatten();
```

console.log:
```
  fieldErrors: {
    name: (3) ["First Name can not be empty.", "Should be at least 1 characters", "First and Middle Name must be the same"]
  }
```

I have a component for each field and the lack of path prevents me from passing the error message to their respective components (ex: <FirstNameInput error={ {error.fieldErrors?.name?} }) />).  We can always use object.keys to achieve the current behavior as well.

Another issue is the error message becomes very unclear since they don't reference any paths in their message (ex: Should be at least 1 characters). The workaround here is to manually type the name inside the custom error message but that just isn't elegant especially if we'll be doing that per field.

**Comment by colinhacks** [comment]
This is the desired behavior of `.flatten()` — it's a utility method that flattens everything. Just use the normal error if you want full paths: 

```ts
{
  "success": false,
  "error": {
    "issues": [
      {
        "code": "too_small",
        "minimum": 1,
        "type": "string",
        "inclusive": true,
        "message": "First name can not be empty.",
        "path": [
          "name",
          "firstName"
        ]
      },
      {
        "code": "too_small",
        "minimum": 1,
        "type": "string",
        "inclusive": true,
        "path": [
          "name",
          "lastName"
        ],
        "message": "Should be at least 1 characters"
      },
      {
        "code": "custom",
        "message": "First and Middle Name must be the same",
        "path": [
          "name"
        ]
      }
    ]
  }
}

```

**Comment by flybayer** [comment]
@colinhacks I just ran into this problem. This totally renders the `formErrors.fieldErrors` useless. I urge you to reconsider this.

> If you're using Zod to validate the inputs from a web form, there is a convenient way to "flatten" a ZodError to a format that can be easily displayed to the end user.

I, and it seems the OP, fully expected the same flatten behavior at all levels of the object, not just the first level. The current behavior removes critical information from nested fields (the path to the field). I can't think of any case where that would be desirable 🤔 . Imo if you don't want to change this, then you should remove it all together :)

**Comment by flybayer** [comment]
Here's the workaround for 2 levels of validation:

```ts
  } catch (error) {
    const fieldErrors: any = {}
    for (const issue of error.issues) {
      if (issue.path.length > 0) {
        if (issue.path.length === 1) {
          fieldErrors[issue.path[0]] ??= []
          fieldErrors[issue.path[0]].push(issue.message)
        } else {
          fieldErrors[issue.path[0]] ??= {}
          fieldErrors[issue.path[0]][issue.path[1]] ??= []
          fieldErrors[issue.path[0]][issue.path[1]].push(issue.message)
        }
      } else {
        // form error
      }
    }
    return fieldErrors
  }

```

**Comment by colinhacks** [comment]
@flybayer I don't think your proposal is what the OP is asking for. @cybervaldez wants a full `path` array associated with each issue (correct me if I'm wrong). If you need that granularity of information, then you should use the raw `ZodError.issues` array.

The idea behind `flatten` is to easily collapse everything down to an object of depth one. I see now that this isn't particularly useful. Your proposal is essentially the opposite of a `flattening` 😛  It takes the `.issues` array and converts it into a nested keyed object. Seems like a really useful utility, but it should be a separate method. Maybe `treeify` or `denormalize` — any thoughts?

BTW you're using the `.formErrors` getter, which just delegates to `.flatten()`. I removed `.formErrors` from the documentation because `.flatten()` is more explicit. 

![Screen Shot 2020-11-27 at 9 38 43 AM](https://user-images.githubusercontent.com/3084745/100474080-ac5cfb80-3094-11eb-83fc-6796f7db2bce.png)

**Comment by cybervaldez** [comment]
> @flybayer I don't think your proposal is what the OP is asking for. @cybervaldez wants a full `path` array associated with each issue (correct me if I'm wrong). If you need that granularity of information, then you should use the raw `ZodError.issues` array.
> 
> 
> 
> The idea behind `flatten` is to easily collapse everything down to an object of depth one. I see now that this isn't particularly useful. Your proposal is essentially the opposite of a `flattening` 😛  It takes the `.issues` array and converts it into a nested keyed object. Seems like a really useful utility, but it should be a separate method. Maybe `treeify` or `denormalize` — any thoughts?
> 
> 
> 
> BTW you're using the `.formErrors` getter, which just delegates to `.flatten()`. I removed `.formErrors` from the documentation because `.flatten()` is more explicit. 
> 
> 
> 
> ![Screen Shot 2020-11-27 at 9 38 43 AM](https://user-images.githubusercontent.com/3084745/100474080-ac5cfb80-3094-11eb-83fc-6796f7db2bce.png)

I was referring to the index and @flybayer 's solution is exactly what I'm looking for since it tells us what fields is causing the error. Without that the error becomes very unclear forcing us to set a custom message for each
