### ISSUE TITLE
How can I access Request during a validation?

### ISSUE THREAD

**Issue by cfuj** [colinhacks/zod#2238]
My app will reuse a lot of rules, so I wanted to have those common rules in an external file

For some rules, I want to show more descriptive error messages depending on the user-type. If it's a developer, i want to explain exactly what's wrong, if it's an admin, I want to give them useful information, but if it's a user, I want to conceal the exact reason and just let them know a problem occurred.

I have a workaround that works pretty well. I'm just wondering if its the best way. My code is typescript, but I'll use JS for brevity

```ts
CommonValidations = {
    messages(req) {
        return {
            subjectRule: rule,
            messageKeyRule: ..refine(() => {
                if (!messageKeyRegexTest) {
                    if (req.user.isAdmin()) {
                        return "Failed to generate key, configuration error probably"
                    } else {
                        return "Something went wrong"
                    }
                }
            })
        }
    }
}
```

**Comment by JacobWeisenburger** [comment]
Please send a full reproducible code example.
