### ISSUE TITLE
How to modify schema using generic typed functions.

### ISSUE THREAD

**Issue by yatendra121** [colinhacks/zod#2244]
I just want to modify the schema using function and for that, i am using omit/pick functions in a generic typed function but omit/pick functions is not exist in generic typed functions for the schema.
Also, I have watched all functions of ZodType class but there is no omit/pick function.
A simple example is given below.
```ts

export const ProductSchema = z.object({
    id: z.string().uuid(),
    name: z.string(),
    quantity: z.number().int(),
    price: z.number().int(),
    salePrice: z.number().int(),
    description: z.string().nullable(),
    categoryId: z.string(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
  })

export type Product = z.infer<typeof ProductSchema>

  
export function excludeDBOptionalFields<T extends z.ZodTypeAny>(schema: T){

 //here getting type error
  return schema.omit({
     id: true,
     createdAt: true,
     updatedAt: true
  });
}

const FinalProductSchema = excludeDBOptionalFields<Product>(ProductSchema)

```
Thank you for your time and consideration.

**Comment by JacobWeisenburger** [comment]
Is this what you are looking for?

```ts
const ProductSchema = z.object( {
    id: z.string().uuid(),
    name: z.string(),
    quantity: z.number().int(),
    price: z.number().int(),
    salePrice: z.number().int(),
    description: z.string().nullable(),
    categoryId: z.string(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
} )
type Product = z.infer<typeof ProductSchema>

function excludeDBOptionalFields<T extends z.AnyZodObject> ( schema: T ) {
    return schema.omit( {
        id: true,
        createdAt: true,
        updatedAt: true,
    } )
}

const FinalProductSchema = excludeDBOptionalFields( ProductSchema )
```

If you found my answer satisfactory, please consider supporting me. Even a small amount is greatly appreciated. Thanks friend! 🙏
https://github.com/sponsors/JacobWeisenburger

**Comment by yatendra121** [comment]
@JacobWeisenburger thanks for your support.

Using the above codes, the problem has been resolved but that function is not proving typed safe schema.

By using your codes, I have done some changes and now that function is providing a typed safe schema.

codes are given below:
`export const ProductSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  quantity: z.number().int(),
  price: z.number().int(),
  salePrice: z.number().int(),
  description: z.string().nullable(),
  categoryId: z.string(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});

export function excludeDBOptionalFields<T extends z.ZodRawShape>(
  schema: z.ZodObject<T>
) {
  return schema.omit({
    id: true,
    createdAt: true,
    updatedAt: true,
  });
}
 const FinalProductSchema = excludeDBOptionalFields(ProductSchema);
`

Again thank you for helping!
