### ISSUE TITLE
Return data and errors

### ISSUE THREAD

**Issue by danvoyce** [colinhacks/zod#2258]
I'm finally getting around to taking Zod for a spin. I'm using `safeParse` so things don't blow up, however it would be great if there was a way that it would still return the parsed data as well as any errors it finds.

My use case: 

I'm fetching a large amount of data and would like to display it all, even if there are a few errors. I can do this by using things like `z.coerce` and `.nullable()`, and I believe I can use `transform` (however I'm trying to be wary of performance).

Ultimately i'd like to be informed if there are any errors so I can do something about them, but I don't want to prevent the user from using the app, as it's very likely they wouldn't notice anyway.

If `safeParse` could return something like this it would be awesome:

```ts
{
   data: ParsedData,
   error: Errors[]
   success: Boolean
}
```

**Comment by JacobWeisenburger** [comment]
Perhaps this would help you:
https://github.com/JacobWeisenburger/zod_utilz#partialsafeparse

If you found my answer satisfactory, please consider supporting me. Even a small amount is greatly appreciated. Thanks friend! 🙏
https://github.com/sponsors/JacobWeisenburger

**Comment by danvoyce** [comment]
Thank you @JacobWeisenburger, this is exactly what I need!
