### ISSUE TITLE
Error in regex for email validation in PR #1982 and #2058

### ISSUE THREAD

**Issue by fvckDesa** [colinhacks/zod#2267]
It was pointed out to me (https://github.com/colinhacks/zod/pull/1982#issuecomment-1487157041, #2154) that the regex I wrote has problems with some valid emails, I looked it again and I found the problem in the final part:
``` ts
([A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])*(\.[A-Za-z]{2,})+))
```
I got confused between domain name, subdomains and top level domain.
I also saw PR #2157 from @colinhacks who wants to make the email regex simpler so if he decides he doesn't want to change it I could fix it

**Comment by Shreyas-SAS** [comment]
So are you willing to change it or should I work towards fixing the regex issue?

**Comment by fvckDesa** [comment]
Yes, I fix it

**Comment by Shreyas-SAS** [comment]
> Yes, I fix it

oh ok. If you are confused at any step please ping me, maybe I can help with something.
