### ISSUE TITLE
Numbers Bypass z.string().emoji()

### ISSUE THREAD

**Issue by MauricioRojasCareers** [colinhacks/zod#2275]
Just found a weird bug that was verified by another dev... numbers will bypass the z.string().emoji() check... probably because emojis are represented as numbers... or something along the sorts. Anyway, trying to figure out a solution and will pull request it if someone doesn't already beat me to it!

**Comment by JacobWeisenburger** [comment]
https://github.com/colinhacks/zod/issues/2228
