### ISSUE TITLE
Any way to access siblings when defining schema?

### ISSUE THREAD

**Issue by mariusmarais** [colinhacks/zod#228]
I'm trying to replicate `yup.when`, which allows the schema to change based on values present in an object.

For instance, when creating a new audio recording, a type and name is necessary.  When completing the recording, the runtime is necessary too.

In yup one could do that with a `status = 'started' | 'complete'` check, where `complete` would make the `runtime` field required.

(I don't intend to change the schema vastly, but different refinements and optionality would be great.)

I realise I can do this with separate schemas (pick / omit / partial will help), but hoping I don't need to build a layer over Zod to decide which schema to run.

**Comment by mariusmarais** [comment]
I just realised that this is possible via `refine`... Awkward.

**Comment by colinhacks** [comment]
Excellent!
