### ISSUE TITLE
Restrict z.enum options to existing type

### ISSUE THREAD

**Issue by IlyaSemenov** [colinhacks/zod#2280]
### Problem

I want to restrict options passed to `z.enum` to the existing type.

```ts
type Status = 'new' | 'accepted' | 'closed'

z.enum(['new', 'accepted']) // OK
z.enum(['new', 'approved']) // Invalid choice - should be somehow disallowed
```

Is there an elegant way to statically validate the typings of enum options?

### Solutions tried

```ts
z.enum(['new', 'accepted'] as Status[]) // Argument of type 'Status[]' is not assignable to parameter of type '[string, ...string[]]'.
z.enum(['new', 'accepted'] satisfies Status[]) // Argument of type '("new" | "acepted")[]' is not assignable to parameter of type '[string, ...string[]]'.
z.enum<Status>(['new', 'accepted']) // Expected 2 type arguments, but got 1
z.enum(['new', 'accepted'] as [Status, ...Status[]]) // works, but ugly
z.enum(['new', 'accepted'] satisfies [Status, ...Status[]]) // works, but ugly
z.enum(['new', 'accepted'] as const satisfies readonly Status[]) // works, but could it be simpler?
```

at least a built-in helper would be useful:

```ts
z.enum(['new', 'accepted'] as z.EnumOptions<Status>) // self explanatory
```

**Comment by IlyaSemenov** [comment]
Perhaps we can update `EnumValues`:

https://github.com/colinhacks/zod/blob/51e14beeab2f469fcbf18e3df44653e1643f5487/src/types.ts#L3918

into this?

```ts
export declare type EnumValues<T extends string = string> = [T, ...T[]];
```

**Comment by IlyaSemenov** [comment]
Another option would be to update EnumValues to be less restrictive:

```ts
 export type EnumValues = string[];  // and similar updates in createEnum()
```

then the validation works just fine with simple `satisifes` test:

```ts
type Status = 'new' | 'accepted' | 'closed'

z.enum(['new', 'accepted'] satisfies Status[]) // OK
z.enum(['new', 'approved' satisfies Status[]) // Error: Type 'string' does not satisfy the expected type 'Status[]'
```

In #2312, @igalklebanov told that allowing `string[]` was a footgun. May be it is, I am not seeing how though. After all, `z.enum([])` is not a completely impossible scenario. Why would the user be disallowed to create a schema that knowingly never validates?

**Comment by IlyaSemenov** [comment]
Making EnumValues generic (see linked PR) is fully backwards compatible.

From what I have discovered `[string, ...string[]]` seems to be currently working not only to require at least one value but also as some kind of poor-man alternative to [Typescript 5.0 const generic modifier](https://github.com/microsoft/TypeScript/pull/51865) and blindly replacing it with `string[]` will create a regression for inferred types. Hopefully the maintainers will decide to bump to TS 5 at some point in future.

**Comment by IlyaSemenov** [comment]
There is a PR for implementing this improve which makes no harm.

**Comment by colinhacks** [comment]
Passing a generic into `z.enum<>()` breaks inference. Before [`const` parameters](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters) it used to require two generics to properly infer a tuple of string literals. In Zod 4 I'll bump the minimum version to 5.0 and there will be a more convenient way to do this.

Generally speaking, you aren't *supposed* to start with a type then try to write a Zod schema that's compatible with it. The goal is to define your types with Zod, so it's often inconvenient to go the other direction. This is one of those cases.

In the meantime I recommend using your own `Tuple` helper. It's not perfect but it works.

```ts
type Status = "pending" | "fulfilled" | "rejected";
type Tuple<T extends string> = [T, ...T[]];

const myEnum: z.ZodEnum<Tuple<Status>> = z.enum([
  "pending",
  "fulfilled",
  "rejected",
]);
```
