### ISSUE TITLE
Equality between properties of the schema

### ISSUE THREAD

**Issue by aminnairi** [colinhacks/zod#2284]
In the case of comparing two passwords for instance (`password` & `passwordConfirmation`), it would be great to have a way of comparing the two inside the schema.

```javascript
const registrationSchema = z.object({
  password: z.string(),
  passwordConfirmation: z.equals(schema => schema.password.value)
});
```

The schema is deliberately simplified for demonstration purposes.

Here above, the `equals` could be an operator that helps check if the value is equal (`===`) to the wanted property of the schema.

This could also be great to enable this operator with a `refine` when needed.

```javascript
z.string().refine((value, schema) => {
  return schema.password.value === value;
})
```

This would not mean breaking the API if this is another parameter that the `refine` method accepts.

Or, it could be a completely new method.

```javascript
z.string().compare((value, schema) => {
  return schema.password.value === value
})
```

> This would also be useful for unlocking cool things for dates for instance `z.date().after(schema => schema.beginDate.value)`

Either way, the point is that it would be awesome to be able to reflectively inspect values from our own schema for that particular case and others to come.

*Note: the code excerpts above are only pseudo-code blocks, the API might be changed completely, I didn't read the full source-code to adapt these examples.*

**Comment by joaoGabriel55** [comment]
Hello @aminnairi I sent a PR for that, but my solution is not type safe, cause is impossible get the current schema type in a `z.string()` method, something like:
```ts
equalsTo(field: CurrentSchema, message?: errorUtil.ErrMessage);

// usage:
const registrationSchema = z.object({
    password: z.string(),
    passwordConfirmation: z.string().equalsTo("password"), // impossible get the current schema type ({ password: string; passwordConfirmation: string; })
});
```

**Comment by Demivan** [comment]
Downside of the `refine` method is that it waits for the entire schema to be valid before it runs.
How about having `partialRefine` that will execute when specified fields are valid?
It can be made typesafe by using `keyof` because it is specified on the object schema.

```
const registrationSchema = z.object({
  name: z.string(),
  email: z.string().email(),
  password: z.string(),
  passwordConfirmation: z.string()
})
.partialRefine(
  ['password', 'passwordConfirmation'], // Does no require name and email to be valid to run
  (values) => { // `values` can be typesafe too by extracting only specified keys
    return values.password === values.passwordConfirmation;
  })
```

**Comment by aminnairi** [comment]
> Hello @aminnairi I sent a PR for that, but my solution is not type safe, cause is impossible get the current schema type in a `z.string()` method, something like:
> 
> ```ts
> equalsTo(field: CurrentSchema, message?: errorUtil.ErrMessage);
> 
> // usage:
> const registrationSchema = z.object({
>     password: z.string(),
>     passwordConfirmation: z.string().equalsTo("password"), // impossible get the current schema type ({ password: string; passwordConfirmation: string; })
> });
> ```
> 
> I think that using [zod refine](https://zod.dev/?id=refine) will help you

Thank you for your follow up response, I will definitely check out the package you linked!



> Downside of the `refine` method is that it waits for the entire schema to be valid before it runs. How about having `partialRefine` that will execute when specified fields are valid? It can be made typesafe by using `keyof` because it is specified on the object schema.
> 
> ```
> const registrationSchema = z.object({
>   name: z.string(),
>   email: z.string().email(),
>   password: z.string(),
>   passwordConfirmation: z.string()
> })
> .partialRefine(
>   ['password', 'passwordConfirmation'], // Does no require name and email to be valid to run
>   (values) => { // `values` can be typesafe too by extracting only specified keys
>     return values.password === values.passwordConfirmation;
>   })
> ```

Yes, it would be great to allow refining on the schema itself, hope this can be accepted as an enhancement!

**Comment by alexpeev9** [comment]
I have come with the following solution:

```
import { z } from 'zod'

let password = ''

export const registerSchema = z.object({
  password: z
    .string()
    .min(6, { message: 'Password must be at least 6 characters' })
    .refine((value) => {
      password = value
      return true
    }),
  passwordConfirmation: z
    .string()
    .min(6, { message: 'You must confirm your password' })
    .refine((value) => value === password, 'Passwords do not match')
})
```

I use a helper variable in which I save the state of the password, and this way, when I trigger only the passwordConfirmation validation, it will check and compare it.

```
trigger(['passwordConfirmation'])
```

**Comment by svenliebig** [comment]
Pretty sad that this is closed. Are there any solutions to this by now? @alexpeev9's solution might be okay for smaller schemas, maybe I would be possible to create something like a map to make things easier, but I would prefer when the library gives first hand support for this. Easy validations like "if `a` is selected, `b` should be required", are unnecessary complex to implement in my opinion.

**Comment by magnusriga** [comment]
Comparing values in an object schema is supported in both Zod v3 and v4, via `refine(..)`:

https://v3.zod.dev/?id=customize-error-path

https://zod.dev/api?id=path

**Comment by alexpeev9** [comment]
> I have come with the following solution:
> 
> ```
> import { z } from 'zod'
> 
> let password = ''
> 
> export const registerSchema = z.object({
>   password: z
>     .string()
>     .min(6, { message: 'Password must be at least 6 characters' })
>     .refine((value) => {
>       password = value
>       return true
>     }),
>   passwordConfirmation: z
>     .string()
>     .min(6, { message: 'You must confirm your password' })
>     .refine((value) => value === password, 'Passwords do not match')
> })
> ```
> 
> I use a helper variable in which I save the state of the password, and this way, when I trigger only the passwordConfirmation validation, it will check and compare it.
> 
> ```
> trigger(['passwordConfirmation'])
> ```

I wrote this code over a year ago, back when I wasn’t very familiar with Zod schemas. The approach isn’t good practice and should be avoided. Here’s the correct way to implement it:

```
export const emailRegisterSchema = z
    .object({
        username: z.string().min(3),
        password: z.string().min(8),
        repeatPassword: z.string().min(8),
    })
    .refine((data) => data.password === data.repeatPassword, {
        path: ["repeatPassword"],
        message: "Passwords do not match",
    });
```
