### ISSUE TITLE
z.infer to extract schema as a type

### ISSUE THREAD

**Issue by MauricioLudwig** [colinhacks/zod#229]
Hi, first of all.. awesome library! Was wondering how you get the schema as a type? In v1 you could do z.infer<...> but infer doesn't seemingly exist in beta, unless I'm missing something?

**Comment by MauricioLudwig** [comment]
Nvm. The issue occurs when you import z as: import * as z from 'zod';
It can't find infer.

Solved it by doing:
import * as z from 'zod';
import { TypeOf } from 'zod';

Not optimal but works..

**Comment by colinhacks** [comment]
It does exist in v2.

```ts
const schema = z.string();
type schemaType = z.infer<typeof schema>
```

**Comment by MauricioLudwig** [comment]
For some reason it can't find infer.

![image](https://user-images.githubusercontent.com/22146709/99625712-20622880-2a31-11eb-8d09-22b2500653bf.png)

Have to do this for it to work:

![image](https://user-images.githubusercontent.com/22146709/99625799-4ab3e600-2a31-11eb-8e0c-b721ac247f6f.png)
