### ISSUE TITLE
Deeply nested schema results in a huge bundle size

### ISSUE THREAD

**Issue by fehergeri13** [colinhacks/zod#2290]
I have a very complex schema, and when I try to build it, it produces a really big bundle size (1.2MB):

```text
zod-explode ❯ pnpm build
> tsup src/index.ts --format esm,cjs --dts --clean

CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v6.7.0
CLI Target: es2022
CLI Cleaning output folder
ESM Build start
CJS Build start
ESM dist/index.mjs 2.93 KB
ESM ⚡️ Build success in 43ms
CJS dist/index.js 4.90 KB
CJS ⚡️ Build success in 44ms
DTS Build start
DTS ⚡️ Build success in 942ms
DTS dist/index.d.ts 1.20 MB
```

I created an example repo for that: https://github.com/fehergeri13/zod-explode/blob/bc35120c51f43eed226102fad2341339958506e9/dist/index.d.ts

When I replace the `.object` with a custom implementation, I can reduce the bundle size to a much more sustainable size, but I'm not sure what I risk

```ts
function object<T extends ZodRawShape>(shape: T) {
  return z.object(shape) as ZodType<baseObjectOutputType<T>, ZodTypeDef, any>;
}
```

```text
DTS dist/index.d.ts 78.40 KB
```

https://github.com/fehergeri13/zod-explode/blob/master/dist/index.d.ts

Is there a way, to reduce the output size by default without this "hack"?

**Comment by fehergeri13** [comment]
Actually I found an even better solution, by extracting the result type of the `.object` function, it gives the correct output, and also reduces the bundle size:

```ts
type ObjR<T extends ZodRawShape> = ZodObject<T, "strip", ZodTypeAny, { [k_1 in keyof objectUtil.addQuestionMarks<baseObjectOutputType<T>, { [k in keyof baseObjectOutputType<T>]: undefined extends baseObjectOutputType<T>[k] ? never : k; }[keyof T]>]: objectUtil.addQuestionMarks<baseObjectOutputType<T>, { [k in keyof baseObjectOutputType<T>]: undefined extends baseObjectOutputType<T>[k] ? never : k; }[keyof T]>[k_1]; }, { [k_2 in keyof baseObjectInputType<T>]: baseObjectInputType<T>[k_2]; }>

function object<T extends ZodRawShape>(shape: T) {
  return z.object(shape) as ObjR<T>;
}
```

**Comment by rayepps** [comment]
My team and I are building out an [opensource version of our product](https://github.com/vesselapi/integrations), using zod heavily in our new library to do input validation. We just started, the codebase is still small, building with tsup produces an `index.d.ts` file thats `1.5MB` and ~30,000 lines of zod schema.

I'm going to try your solution right now @fehergeri13

**Comment by rayepps** [comment]
Gave your fix a try @fehergeri13, didn't help much in our library, only took us from `1.58mb` -> `1.52mb` index.d.ts file so still looking for a solution.

Any ideas from the zod team would be appreciated 🙏

**Comment by fehergeri13** [comment]
Can you somehow share the result bundle? I can't open the vesselapi/integrations, it's private.

**Comment by timheerwagen** [comment]
Any solutions yet?

**Comment by imnocat** [comment]
I was also looking for a solution to this.

**Comment by Atharv2433** [comment]
Actually I found an even better solution, by extracting the result type of the .object function, it gives the correct output, and also reduces the bundle size:

type ObjR<T extends ZodRawShape> = ZodObject<T, "strip", ZodTypeAny, { [k_1 in keyof objectUtil.addQuestionMarks<baseObjectOutputType<T>, { [k in keyof baseObjectOutputType<T>]: undefined extends baseObjectOutputType<T>[k] ? never : k; }[keyof T]>]: objectUtil.addQuestionMarks<baseObjectOutputType<T>, { [k in keyof baseObjectOutputType<T>]: undefined extends baseObjectOutputType<T>[k] ? never : k; }[keyof T]>[k_1]; }, { [k_2 in keyof baseObjectInputType<T>]: baseObjectInputType<T>[k_2]; }>

function object<T extends ZodRawShape>(shape: T) {
  return z.object(shape) as ObjR<T>;
}
Can it be part of the library by default somehow?
