### ISSUE TITLE
`.toLowerCase/UpperCase()` should infer to `Lowercase/Uppercase<string>`

### ISSUE THREAD

**Issue by brianblakely** [colinhacks/zod#2300]
The [Lowercase](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html#lowercasestringtype) and [Uppercase](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html#uppercasestringtype) types are relatively new to TS and already have [analogs in Zod](https://github.com/colinhacks/zod#strings).

When I do this:
```ts
const MySchema = z.string().toLowerCase();
type MyType = z.infer<typeof MySchema>;
```
I should get this:
```ts
type MyType = Lowercase<string>
```
In zod v3.21.4, I get this:
```ts
type MyType = string
```

**Comment by igalklebanov** [comment]
Hey 👋 

Despite `z.string()` always infers to `string` (and not `template literal` types), this actually makes sense.

- `Lowercase<string>` & `Uppercase<string>` extend `string`, so it shouldn't add any complexity to downstream inference.
- You can actually force inputs of a function to be lowercase / uppercase:

```ts
function fn<T extends Lowercase<any>>(str: T) {}

fn('moshe') // OK!
fn('Moshe') // type-error!
```

So having this in zod, removes the need for type-guards before passing `str` to the function.

**Comment by colinhacks** [comment]
TypeScript collapses `Lowercase<string>` to just `string`. The `Lowercase` built-in is intended for converting string literal types.

```
type MyType = Lowercase<string>
// => string
```

**Comment by pascalklaiss-lab** [comment]
this isn't the most efficient way but it does the trick.
```typescript
export const TO_LOWER_CASE_SCHEMA = z
  .string()
  .toLowerCase()
  .refine(val => isLowercase(val));


const isLowercase = (_: unknown): _ is Lowercase<string> => {
  return true;
};

```
