### ISSUE TITLE
zod@3.21.4 fails on firefox 68 : invalid identity escape in regular expression

### ISSUE THREAD

**Issue by mfo** [colinhacks/zod#2302]
Hi everyone, 

thanks for this awesome project.

Unfortunately I have to report a bug (minor? maybe?). But I'm working on a project that requires a large compatibility spectrum, up to ffx68.

Unfortunatelly ffx68 raises the following error: 
Maybe it's linked to : https://github.com/colinhacks/zod/blob/a263814fc430db8d47430cd2884d2cea6b11c671/src/types.ts#L556 ?

Downgrading to zod@3.20.2 fixed it.

Best

**Comment by tchak** [comment]
It looks like this regex was introduced in this PR https://github.com/colinhacks/zod/pull/2090

**Comment by colinux** [comment]
Fixed in 3.22.4  https://github.com/colinhacks/zod/commit/9340fd51e48576a75adc919bff65dbc4a5d4c99b
