### ISSUE TITLE
`z.record` makes all his attributes optional

### ISSUE THREAD

**Issue by Andyloz** [colinhacks/zod#2320]
Look at this:

![imagen](https://user-images.githubusercontent.com/58707456/231560761-aefdaf18-25e0-4e19-b30b-87a72c005cb0.png)

It should warn me about `foo` being missing, but isn't  because `z.record` produces this: `Partial<Record<"foo" | "bar", number>>`

Is that intentional because of some reason i don't understand? I read all the docs and I couldn't find anything.

Thank you :heart:

**Comment by JacobWeisenburger** [comment]
https://github.com/colinhacks/zod/discussions/2069

**Comment by Andyloz** [comment]
@JacobWeisenburger 
Well, I have seen that issue, but i don't touch anything related to `z.brand`.

I made a little research and I've found [where the issue is](https://github.com/colinhacks/zod/blob/master/src/types.ts)

Position 3328:5

Code:
`
export type RecordType<K extends string | number | symbol, V> = [
  string
] extends [K]
  ? Record<K, V>
  : [number] extends [K]
  ? Record<K, V>
  : [symbol] extends [K]
  ? Record<K, V>
  : [BRAND<string | number | symbol>] extends [K]
  ? Record<K, V>
  : **Partial<Record<K, V>>**;
`

If I remove the `Partial`, the properties become required as I need.

**Comment by lunelson** [comment]
I've offered a workaround using `z.custom` here: https://github.com/colinhacks/zod/issues/2623#issuecomment-1849464377
