### ISSUE TITLE
[Feature Request] Tuple type inspection

### ISSUE THREAD

**Issue by dsonet** [colinhacks/zod#2326]
<img width="384" alt="image" src="https://user-images.githubusercontent.com/457552/232147082-f1ff1f33-0690-4749-9834-4b3de2b10178.png">

As you can see, we can define a Tuple type with a name. TypeScript will infer them, so we can better understand this tuple type. 
I tried z.Tuple with the field description but seems doesn't work.

 Is there a way to achieve this in zod?

Thank you very much.

**Comment by conorbrandon** [comment]
Likely would require https://github.com/microsoft/TypeScript/issues/44939 to be implemented.
