### ISSUE TITLE
Benchmark with competitors

### ISSUE THREAD

**Issue by Lonli-Lokli** [colinhacks/zod#2327]
It would be great to have benchmarks with competitors like io-ts, runtypes, etc

See as example https://github.com/gcanti/io-ts/issues/133

**Comment by cdaringe** [comment]
if there was a blessed place to put such code, even checkin results from main, i could be game to add some cases. could be snazzy to--during ci--generate some results, possibly dump a little SVG chart showing commit history against perf.

deno does something akin to this: https://deno.land/benchmarks
