### ISSUE TITLE
Make zod globally available in the docs

### ISSUE THREAD

**Issue by alexrohleder** [colinhacks/zod#2336]
Hi there, thanks for the awesome lib!

I suggest that you make `z` globally available in your documentation, so we can try it out in the console.

The [dayjs lib](https://day.js.org/) does it and is very helpful; to test go to the website, open the console and type dayjs.

**Comment by extradosages** [comment]
I opened a PR for this last month: https://github.com/colinhacks/zod/pull/2254

**Comment by alexrohleder** [comment]
Solved by: https://github.com/colinhacks/zod/pull/2432

Zod is available via `Zod` on the console.

**Comment by maxijonson** [comment]
Was this removed? I don't see it anymore in either version docs...
