### ISSUE TITLE
Error.message returns unexpected value

### ISSUE THREAD

**Issue by oschade** [colinhacks/zod#2342]
Hello,

I found a bug in the types of ZodError.message. It should return a string, but returns an Error-Object. Either the Type or the return-value is wrong.

```
import { z } from 'zod'

const myString = z.string()

const results = myString.safeParse(5)

if (!results.success) {
  const message = results.error.message
  // type said message is a string, but got an Array with an Error-Object
  console.log('message:', message)
}

```

BTW: Thank you for this wonderful library!

**Comment by conorbrandon** [comment]
But it is a string?

`console.log('message:', typeof message) // message: string`

It just looks like an object because the [space parameter to JSON.stringify is 2](https://github.com/colinhacks/zod/blob/502384e56fe2b1f8173735df6c3b0d41bce04edc/src/ZodError.ts#L272).

**Comment by oschade** [comment]
Oh, sorry, the `message` variable has the form:

```
[
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "number",
    "path": [],
    "message": "Expected string, received number"
  }
]
```

but you are right, it is a string, it just looks like an array with an object.
I was expecting message to have the value of "Expected string, received number". Therefore, this is not a problem with the data type. I apologize for any confusion and have corrected the title accordingly. Thank you!

**Comment by oschade** [comment]
Ok, this is unexpected for me, but intentional for the author. I close this, because I think, there is nothing to fix here.

**Comment by conorbrandon** [comment]
I agree it is a bit unexpected 🤔. I think I ran into this same confusion when I was first experimenting with zod myself.
