### ISSUE TITLE
Add `ZodType#isType` as syntactic sugar for type predicate.

### ISSUE THREAD

**Issue by THEtheChad** [colinhacks/zod#2345]
## Problem
I primarily use Zod as a way to strongly type my API integrations. A scenario I find myself in quite often is one where the server performs logic that results in a response that is a union or has nested keys that are a union.

```ts
const User =  z.object({
    first_name: z.string(),
    last_name: z.string()
})

const Staff = User.extend({
    group: z.string(),
    isAdmin: z.boolean()
})

// this type of scenario
const Response = z.object({
    id: z.string(),
    user: z.union([ User, Staff ])
})
```

When accessing these responses inside my application, I have to perform some sort of type narrowing. My initial solution was a generic predicate whose arguments were the type I want to assert and the data I'm asserting against.

```ts
function isType<T extends ZodTypeAny>(schema: T, datum: unknown): datum is z.infer<T> {
    return schema.safeParse(datum).success
}

response.user.group // can't be accessed here

if( isType(Staff, response.user) ){
    response.user.group // no errors
}
```

The more often I found myself using it, the more I wished that Zod had a native way of doing this, specifically:

```ts
if( Staff.isType(response.user) ){
    response.user.group // no errors
}
```

**Comment by THEtheChad** [comment]
Seeing it written down, I'm not a huge fan of the method name. Maybe something like `test` makes more sense (and is a convention we're used to due to regex).

```ts
if( Staff.test(response.user) ){
    response.user.group // no errors
}
```

**Comment by JacobWeisenburger** [comment]
I remember seeing that someone else posted a very similar idea. I didn't think it was very long ago. But I can't seem to find it.

Anyway, I think they used the syntax `schema.check()` which would return a `boolean`

**Comment by THEtheChad** [comment]
@JacobWeisenburger Sounds identical, assuming they were using the type predicate signature `x is type` to allow for type narrowing. I wonder what kind of traction it had.

I'm working on an implementation in a draft PR now.

Considering `.check`, `.test`, and `.matches`.

**Comment by devunt** [comment]
It was proposed in #1113, but have been abandoned.

**Comment by THEtheChad** [comment]
Thank you, @devunt.

The explanation given there was that type predicates aren't provided because schemas can transform their inputs. This doesn't make sense to me, though, because the output type is known and that's what the type predicate is meant to validate.

```ts
const MyType = z.preprocess(
  (val) => String(val),
  z.string().transform((v) => Number(v))
);
 
// this is what we're asserting
 z.infer<typeof MyType> // number

const v = '2'
if( MyType.isType( v ) ){
    // this executes because v passes the type predicate test
}
```

I guess, after writing that, the confusing part is that the output type is a number, while the input is a string. But what we're asserting here is that v is parsable by `MyType`. So maybe the method name is confusing. Perhaps `.isParsable`?
