### ISSUE TITLE
The .url validation accepts `javascript:` schemas which could lead to cross-site scripting vulnerabilities

### ISSUE THREAD

**Issue by carlgieringer** [colinhacks/zod#2353]
The `.url` string validation currently validates for `javascript:` URLs which allows for cross-site scripting vulnerabilities if these URLs are re-displayed in a web app. ([codesandbox](https://codesandbox.io/s/zod-xss-example-l5ckgi)).

The validation also doesn't accept any options to override this behavior. Most people (including myself until recently) probably don't realize that this vulnerability exists, so it would be good to do the following (not mutually exclusive):

1. At least document it so that people are aware
2. Accept options to the `.url` validation to allow people to change the behavior
3. And probably best case change the default behavior of the validation to reject `javascript:` URLs.

**Comment by JacobWeisenburger** [comment]
This doesn't seem to be a problem with Zod, considering the URL constructor allows this.
```ts
console.log( new URL( 'javascript:alert("hi")' ).href )
// javascript:alert("hi")
```

**Comment by carlgieringer** [comment]
> This doesn't seem to be a problem with Zod, considering the URL constructor allows this.
> 
> ```ts
> console.log( new URL( 'javascript:alert("hi")' ).href )
> // javascript:alert("hi")
> ```

Is there not a difference between what a web browser's `URL` implementation should accept vs. what interfaces a validation library should expose? A browser's `URL` should probably be widely applicable, whereas I think a validation library would be wise to be more narrow in acceptable inputs, especially when not doing so may accidentally expose cross-site scripting vulnerabilities.

> > 1. At least document it so that people are aware
> 
> Since this is the base behavior of `new URL`, I'm not sure it's Zod's responsibility to document this.

It seems like a pretty low-effort improvement to mention in Zod's docs that, "the `.url` validator is based on the runtime's `URL` constructor, and so permits `javascript:` and other schemes." in order to clue people in that this validator could lead to cross-site scripting vulnerabilities.

> > 3. And probably best case change the default behavior of the validation to reject `javascript:` URLs.
> 
> Changing the default behavior is not something to be done lightly, as there may be many people relying on it to work the way it is now.

Agreed. But does Zod not follow semver, and does semver not allow breaking changes in major version upgrades?
