### ISSUE TITLE
.datetime() validation

### ISSUE THREAD

**Issue by sanfair** [colinhacks/zod#2357]
Hello, the current implementation for z.string().datetime() passes validation with incorrect values.

```javascript
const valid_date = z.string().datetime().parse('1234-12-12T12:12:12.123Z'); // valid.
const date_with_max_year = z.string().datetime().parse('9999-12-12T12:12:12.123Z'); // valid.

// Invalid time.
const date_with_invalid_seconds = z.string().datetime().parse('1234-12-12T12:12:99.123Z'); // valid, should throw error -> seconds can't be > 60
const date_with_invalid_minutes = z.string().datetime().parse('1234-12-12T12:99:12.123Z'); // valid, should throw error -> minutes can't be >= 60
const date_with_invalid_hours = z.string().datetime().parse('1234-12-12T99:12:12.123Z'); // valid. should throw error -> hours can't be > 24

// Invalid date.
const date_with_invalid_day = z.string().datetime().parse('1234-12-99T12:12:12.123Z'); // valid, should throw error -> day can't be > 31
const date_with_invalid_month = z.string().datetime().parse('1234-99-12T12:12:12.123Z'); // valid, should throw error -> month can't be > 12

console.log(new Date(valid_date)); // 1234-12-12T12:12:12.123Z
console.log(new Date(date_with_max_year)); // 1234-12-12T12:12:12.123Z

console.log(new Date(date_with_invalid_day)); // Invalid date.
console.log(new Date(date_with_invalid_month)); // Invalid date.

console.log(new Date(date_with_invalid_seconds)); // Invalid date.
console.log(new Date(date_with_invalid_minutes)); // Invalid date.
console.log(new Date(date_with_invalid_hours)); // Invalid date.
```

The same issue might be in ZodString.date() & ZodString.time() implementation (https://github.com/colinhacks/zod/pull/1766)

**Comment by JacobWeisenburger** [comment]
`z.string().datetime()` only checks that the string is a valid ISO date string. It doesn't check that the date is valid.

If you want to make sure it's also a valid date, you can do something like this:
```ts
const isoStringToDate = z.string().datetime().pipe( z.coerce.date() )
console.log( isoStringToDate.parse( '1234-12-12T12:12:12.123Z' ) )
// 1234-12-12T12:12:12.123Z

const result = isoStringToDate.safeParse( '1234-12-12T12:12:99.123Z' )
!result.success && console.log( result.error.issues )
// [ { code: 'invalid_date', path: [], message: 'Invalid date' } ]
```

If you found my answer satisfactory, please consider supporting me. Even a small amount is greatly appreciated. Thanks friend! 🙏
https://github.com/sponsors/JacobWeisenburger

**Comment by mulholo** [comment]
> However .pipe( z.coerce.date() ) will transform string to Date which is not expected on validation. And it also messes with features like [@anatine/zod-openapi](https://www.npmjs.com/package/@anatine/zod-openapi) in this case parameter will lose type info

I've been running this as two separate validation calls, without pipe. Then, I can just use the string value without coerce

**Comment by samchungy** [comment]
>However .pipe( z.coerce.date() ) will transform string to Date which is not expected on validation. And it also messes with features like [@anatine/zod-openapi](https://www.npmjs.com/package/@anatine/zod-openapi) in this case parameter will lose type info

Can I spruik my repo: https://github.com/samchungy/zod-openapi. We handle `.pipe()` ;)

**Comment by dev-nicolaos** [comment]
bump

**Comment by peterjdrb** [comment]
+1

**Comment by iRajatDas** [comment]
BUMP

**Comment by optislav** [comment]
+1

**Comment by samchungy** [comment]
Have you guys tried the latest version? If should cover those cases from what I recall
