### ISSUE TITLE
Change `formErrors` to produce normalized, deep object instead of `flatten()`

### ISSUE THREAD

**Issue by flybayer** [colinhacks/zod#236]
I use `error.formErrors` in every project, and it's used the default Blitz.js form abstraction for displaying form errors on the client.

**The problem is that this flattens the errors to a single level, loosing critical path information for nested object errors.**

You can see an example here:

```ts
const test = zod
  .object({
    name: zod
      .object({
        firstName: zod.string().nonempty({ message: "First name can not be empty." }),
        middleName: zod.string(),
        lastName: zod.string(),
      })
  })
  .safeParse({
    name: {
      firstName: "",
      middleName: "estrada",
      lastName: "",
    },a
  }).error.fieldErrors;
```

```
  {
    name: ["First Name can not be empty.", "Required", "Required"]
  }
```

Instead of the above, which is unusable, the result should be:

```
  {
    name: {
      firstName: ["First Name can not be empty."], 
      middleName: ["Required"],
      lastName: ["Required"]
  }
```

### Workaround for 2 levels 

```ts
  } catch (error) {
    const fieldErrors: any = {}
    for (const issue of error.issues) {
      if (issue.path.length > 0) {
        if (issue.path.length === 1) {
          fieldErrors[issue.path[0]] ??= []
          fieldErrors[issue.path[0]].push(issue.message)
        } else {
          fieldErrors[issue.path[0]] ??= {}
          fieldErrors[issue.path[0]][issue.path[1]] ??= []
          fieldErrors[issue.path[0]][issue.path[1]].push(issue.message)
        }
      } else {
        // form error
      }
    }
    return fieldErrors
  }
```

**Comment by colinhacks** [comment]
This is tricky. What should be the result if a refinement error is thrown on the `name` object?

```ts
const test = zod
  .object({
    name: zod
      .object({
        firstName: zod.string().nonempty({ message: "First name can not be empty." }),
        middleName: zod.string(),
        lastName: zod.string(),
      }).refine(val => false, 'Invalid name object.') // <= error here
  })
  .safeParse({
    name: {
      firstName: "",
      middleName: "estrada",
      lastName: "",
    },a
  }).error.fieldErrors;
```

To express this, there would have to be an additional layer at each level that can contain the errors _at_ that node of the tree plus some representation of the errors _within_ that subtree. The current implementation of `.flatten` sidesteps this by only going one level deep and using the `{ formErrors: [], fieldErrors: []}` construct.

Also like I mentioned in #223 I don't think you should use the `.formErrors` syntax. I also don't want to introduce a breaking change to it, so if we land on a good solution here, I plan to put this functionality behind a new method.

**Comment by colinhacks** [comment]
Ah! Thought of a far better approach: adding a `.getIssuesByPath(path: (string | number)[])` method, where you pass in a path and Zod can return all errors _at_ and _below_ that path:


```ts
const myForm = zod
  .object({
    name: zod
      .object({
        firstName: zod.string().nonempty({ message: "First name can not be empty." }),
        middleName: zod.string(),
        lastName: zod.string(),
      }).refine(val => false, 'Invalid name object.') // <= error here
  })

const myFormError = myForm.safeParse({
    name: {
      firstName: "",
      middleName: "estrada",
      lastName: "",
    },a
  })
  .error

myFormError.getIssuesByPath(['name']);
// => { issues: ['Invalid name object.'], subissues: ["First Name can not be empty.", "Required", "Required"] }

myFormError.getIssuesByPath(['name', 'firstName']);
// => { issues: ['First Name can not be empty.'], subissues: [] }

myFormError.getIssuesByPath(['name', 'lastName']);
// => { issues: ['Required'], subissues: [] }
```

**Comment by flybayer** [comment]
@colinhacks for the purposes of form errors, I don't care about object errors like you have on the `name` object. For forms, I always provide a specific path.

> myFormError.getIssuesByPath(['name']);
// => { issues: ['Invalid name object.'], subissues: ["First Name can not be empty.", "Required", "Required"]

This is still problematic because subissues omits the paths, which is the original issue we have here.

Also, I don't like the extra levels in the error objects, because I can't pass that to a form library. The form libraries want an error object that exactly matches the form value object. **This** is the whole point of this issue — to have a very easy way to convert a full zod error into an object that I can pass straight to form library.

You can implement it however you want as long as at the end of the day, I have some way to get this nice error object in ideally one line of code

**Comment by colinhacks** [comment]
The idea with my solution is that you can pass any path into `.getIssuesByPath`:

```ts
myFormError.getIssuesByPath(['name']);
// => { issues: ['Invalid name object.'], subissues: ["First Name can not be empty.", "Required", "Required"]

myFormError.getIssuesByPath(['name', 'firstName']);
// => { issues: ['First Name can not be empty.'], subissues: [] }

myFormError.getIssuesByPath(['name', 'lastName']);
// => { issues: ['Required'], subissues: [] }
```

Unfortunately Zod is capable of producing errors with path `["name"]` so I'm not inclined to ship a solution that just ignores those errors should they exist.

**Comment by flybayer** [comment]
Internally on `formErrors` access, you can make sure that an error on path `["name"]` doesn't exist and throw an error if it does.

Sure it's a slight tradeoff, but much less of a tradeoff than we currently have with `flatten()`! And a tradeoff that 90%+ will never run into.

**Comment by lukeramsden** [comment]
Using lodash a workaround for arbitrary levels becomes easier:


```ts
import {Schema} from 'zod';
import {get, set} from 'lodash';

const formikValidateWithZod = <T extends Schema<any>>(validationSchema: T) => (
  values: any,
) => {
  const result = validationSchema.safeParse(values);

  if (result.success) {
    return {};
  } else {
    const fieldErrors: Record<string, string> = {};
    for (const error of result.error.errors) {
      const currentErrorAtPath = get(fieldErrors, error.path);
      set(
        fieldErrors,
        error.path,
        currentErrorAtPath // if error already exists, append as new line
          ? `${error.message}\n${currentErrorAtPath}`
          : error.message,
      );
    }
    return fieldErrors;
  }
};

export default formikValidateWithZod;
```

Simple to make this return an array instead of a multi-line string.

**Comment by lukeramsden** [comment]
This is currently the function I'm using to validate a large, nested form, with arrays of items, using Formik to handle form state:

```ts
import * as z from 'zod';
import {get, set} from 'lodash';
import {FormikErrors} from 'formik';

const formikValidateWithZod = <T extends z.Schema<any>>(
  validationSchema: T,
) => <F = z.infer<T>>(values: F): FormikErrors<F> => {
  const result = validationSchema.safeParse(values);

  if (result.success) {
    return {};
  } else {
    const fieldErrors: FormikErrors<F> = {};
    const processError = (e: z.ZodError) => {
      for (const error of e.errors) {
        if (error.code === 'invalid_union') {
          error.unionErrors.map(processError);
        } else {
          const path = error.path.map((x) => x.toString());
          const currentErrorAtPath = get(fieldErrors, path);
          set(
            fieldErrors,
            path,
            currentErrorAtPath // if error already exists, append as new line
              ? `${error.message}\n${currentErrorAtPath}`
              : error.message,
          );
        }
      }
    };
    processError(result.error);
    return fieldErrors;
  }
};

export default formikValidateWithZod;
```

**Comment by Kayyow** [comment]
Thanks @lukeramsden, that's what I was looking for when I come across this issue.

I think adding a "treeify" method to ZodError is a good idea, it doesn't change the `flatten` method behavior which does what it is expected to do and adds the possibility of keeping the whole path of a nested property error (including array indexes). It would be really useful to display form errors 👍

**Comment by glennreyes** [comment]
Here's the workaround I am using to create the deep errors object for formik:

```ts
validationSchema.current?.safeParse(values)?.error?.errors?.reduce(
  (errors, error) =>
    error.path.reduce((a, b, level) => {
      if (level === error.path.length - 1) {
        a[b] = error.message;

        return errors;
      }

      if (!a[b]) {
        a[b] = {};
      }

      return a[b];
    }, errors),
  {} as { [key: string]: any },
);
```

**Comment by nfantone** [comment]
Came here for this. The current `flatten()` implementation produces rather underwhelming results, IMHO. Path information is completely lost.

```js
const Profile = z.object({ user: z.object({ name: z.string() } ) })
Profile.safeParse({ user: {} }).error.flatten()
// No "name" mention here
// { formErrors: [], fieldErrors: { user: [ 'Required' ] } }

```

Compare this to what `yup` does for the same.

```js
try {
 const schema = y.object({ user: y.object({ name: y.string().required() }) })
  schema.validateSync({ request: { user: {} } }, { abortEarly: false })
} catch (err) {
  console.log(err.inner)
 /*
  [
    {
      value: undefined,
      path: 'user.name',
      type: 'required',
      errors: ['user.name is a required field'],
      params: {
        value: undefined,
        originalValue: undefined,
        label: undefined,
        path: 'user.name',
      },
    },
  ]
*/
}
```

**Comment by AnzeKop** [comment]
Its been 4 years, has there been any activity regarding this topic at all? still feel like this is a key thing thats missing.

**Comment by akomm** [comment]
@AnzeKop 

I can tell that in a project with zod `3.22.4` it works as expected using `error.format()`.
In another project with zod `3.11.6` it does *not* work. 

You can then access any level like `errors.foo.bar._errors`, which would container the array of errors on the `foo.bar` field.
