### ISSUE TITLE
Multiple `ZodString` validations of the same type

### ISSUE THREAD

**Issue by j-murata** [colinhacks/zod#2375]
Currently, string validations such as `.max()`, `.min()`, `.startsWith()`, etc. seem to be able to register duplicate same type validations for the same schema.
Since these are contradictory definitions, shouldn't they raise an error on function call or be completely overwritten?
(My apologies if this is a specification intended for some use case I am not aware of.)
```js
const stringSchema
    = z.string()
        .min(1)
        .min(2)
        .startsWith('a')
        .startsWith('b')
    ;
console.dir(stringSchema._def.checks);
// [
//   { kind: 'min', value: 1 },
//   { kind: 'min', value: 2 },
//   { kind: 'startsWith', value: 'a' },
//   { kind: 'startsWith', value: 'b' }
// ]
```

For example, what about the idea of changing `schema._def.checks` to be managed by key-value object instead of an array, as shown below?
```js
// schema._def.checks
{
  min: 2,          // or { value: 2 }
  startsWith: 'b', // or { value: 'b' }
}
```

**Comment by Koaieus** [comment]
I think the idea of being able to compose the zod schemas through a pipeline of atomic constraints is quite nice.
I also think a properly designed schema does not contradict itself, e.g. for `min` or `max` it makes no sense to do this, figured adding constraints provides more clarity than overriding existing constraints of the same type.
The required additional logic of determining which constraints needs to be kept (e.g. `min(2)` should override `min(1)`) makes it even more fuzzy, no?

Only for `.startsWith()` I would see an exception in the case where you want to `or` all the different allowed starting strings, would be nice if it **could accept an array of allowed strings instead** (for now a `.refine()` is needed to achieve this)
