### ISSUE TITLE
Not able to assign computed array as Zod enum

### ISSUE THREAD

**Issue by pexeixv** [colinhacks/zod#2376]
I'm trying to create a Zod object in Astro which takes in `tags` as one of the properties. `tags` can be an array of 0 or more categories.

```ts
const blog = defineCollection({
  schema: () => z.object({
    title: z.string(),
    tags: z
      .array(z.enum(['CSS', 'Reference Docs', 'General', 'Astro']))
      .optional(),
  }),
});
```
The above code works fine (ie when I pass a statically typed array into `Z.enum()`. However, now I'm trying to the tags in an external JSON file and import it and pass a computed array into `Z.enum()`.

```json
[
    {
        "label": "css",
        "displayText": "CSS",
        "coverImage": "@assets/unsplash-image.jpg",
        "description": "Cascading Style Sheets is a language used to describe the visual presentation of web pages."
    },
    {
        "label": "reference-docs",
        "displayText": "Reference Docs",
        "coverImage": "@assets/unsplash-image.jpg",
        "description": "Reference docs are documents that provide information, instructions, or guidance on how to use a particular product, tool, or technology."
    },
    {
        "label": "astro",
        "displayText": "Astro",
        "coverImage": "@assets/unsplash-image.jpg",
        "description": "Astro is a static site builder that allows developers to use familiar technologies like JavaScript, CSS, and HTML to build modern websites."
    },
    {
        "label": "general",
        "displayText": "General",
        "coverImage": "@assets/unsplash-image.jpg",
        "description": "Does not belong to any other categories."
    }
]
```

```ts
// Import the above JSON data
import tagsJson from '@assets/tags.json'

// Created a computed array
const tagsArray = tagsJson.map(tag=>tag.displayText) as string[]
// Above line equals => ['CSS', 'Reference Docs', 'General', 'Astro']
```

When I pass this `tagsArray` into `Z.enum()`, I get the following error.

```txt
No overload matches this call.
  Overload 1 of 2, '(values: readonly [string, ...string[]], params?: { errorMap?: ZodErrorMap; invalid_type_error?: string; required_error?: string; description?: string; }): ZodEnum<[string, ...string[]]>', gave the following error.
    Argument of type 'string[]' is not assignable to parameter of type 'readonly [string, ...string[]]'.
      Source provides no match for required element at position 0 in target.
Overload 2 of 2, '(values: [string, ...string[]], params?: { errorMap?: ZodErrorMap; invalid_type_error?: string; required_error?: string; description?: string; }): ZodEnum<[string, ...string[]]>', gave the following error.
    Argument of type 'string[]' is not assignable to parameter of type '[string, ...string[]]'.
      Source provides no match for required element at position 0 in target.ts(2769)
```

**Comment by jussisaurio** [comment]
To create an enum the members of the enum need to be known at compile time. Since you're importing a JSON at runtime, TypeScript has no idea your array has those elements. All it knows is they are an array of strings (which you have asserted with `as`). You won't get a meaningful type out of that because:

1. TS has no idea what the string literals inside the array are, and
2. `string[]` isn't even guaranteed to contain any elements, as the error message shows:

```
Argument of type 'string[]' is not assignable to parameter of type '[string, ...string[]]'.
Source provides no match for required element at position 0
```

**Comment by pexeixv** [comment]
So there's absolutely no way to dynamically create an enum?

**Comment by jussisaurio** [comment]
You can replace the `as string[]` with `as [string, ...string[]]` which will then compile and do the runtime check, and the successful parse result will be `string`

**Comment by pexeixv** [comment]
Thank you so much!

**Comment by rstoermer** [comment]
Why isnt this working with a constant object, where all values are known at compile time?

```typescript
export const ApprovalStates = {
  1: "Submitted for approval",
  2: "Reopened",
  3: "Approved",
  99: "Closed",
} as const;
```

`z.enum(Object.keys(ApprovalStates))` returns the following error:

`Argument of type 'string[]' is not assignable to parameter of type '[string, ...string[]]'.
      Source provides no match for required element at position 0 in target.ts(2769)`

**Comment by nolawnchairs** [comment]
I need to use a Prisma generated enum, which is analogous to `Record<string, string>`. 

Can the zod devs please do something about this? It's nuts that this can't be done without an `as` override.

**Comment by movahhedi** [comment]
I think the reason of `[string, ...string[]]` is to required at least one element for the array.
`[]` is a valid value for the type `string[]`.
But it's very annoying.

**Comment by rudzky** [comment]
```typescript
const REASONS_OBJECTS = [
  {
    key: "reason 1",
    text: "Reason 1",
  },
  {
    key: "reason 2",
    text: "Reason 2",
  },
  {
    key: "reason 3",
    text: "Reason 3",
  },
] as const;

const REASONS = REASONS_OBJECTS.map(({ key }) => key);

const FormSchema = z.object({
  reason: z.enum([REASONS[0], ...REASONS.slice(0)]),
});
```

Well, something like this also works and we even get typesafety

**Comment by codart1** [comment]
@rudzky Genious! Thank you

**Comment by mauricekleine** [comment]
Actually, you could optimise it even more by doing this:

```ts
const REASONS_OBJECTS = [
  {
    key: "reason 1",
    text: "Reason 1",
  },
  {
    key: "reason 2",
    text: "Reason 2",
  },
  {
    key: "reason 3",
    text: "Reason 3",
  },
] as const;

const REASONS = REASONS_OBJECTS.map(({ key }) => key);

const FormSchema = z.object({
  reason: z.enum([
    REASONS[0] as (typeof REASONS_OBJECTS[number]), // this does the trick
    ...REASONS.slice(1)
  ]),
});
```

**Comment by Rot4tion** [comment]
```ts
import { z } from "zod";

const models = [{ id: "1", label: "Default" }] as const;

const aspectRatioArr = [
  { label: "1:1 1024x1024" },
  { label: "9:16 720x1024" },
  { label: "16:9 1024x720" },
] as const;
const numImages = [1, 2, 3, 4, 6, 8, 10] as const;

const FormSchema = z.object({
  num_images: z
    .number()
    .min(numImages[0])
    .max(numImages[numImages.length - 1])
    .default(1),
  model: z.enum(models.map((m) => m.label) as [string, ...string[]]),
  image: z.string(),
  aspect_ratio: z.enum(
    aspectRatioArr.map((a) => a.label) as [string, ...string[]]
  ),
});
```

**Comment by MohammadKurjieh** [comment]
A quick solution would be to do the following:

`z.enum(Object.keys(REASONS_OBJECTS) as [(keyof typeof REASONS_OBJECTS)])`

The type is not exactly correct, but it still output a valid string union type after validation.

**Comment by jamiemoyes** [comment]
I've created a couple helper utilities for this:

```
type ExtractTypeFromObj<T> = T[keyof T]

export const objectToEnum = <T extends object>(obj: T) => {
  type EnumType = ExtractTypeFromObj<typeof obj>

  return Object.values(obj) as [EnumType, ...EnumType[]]
}
```
The first type utility is to extract the type of my object's values (I use this elsewhere for type assertion when using  objects instead of enums), and the function grabs the values of the Object and assigns it to a structure which works with zod.enum()

Using an example from above:

```
const ApprovalStates = {
  1: "Submitted for approval",
  2: "Reopened",
  3: "Approved",
  99: "Closed",
} as const;

const approvalStates = z.enum(objectToEnum(ApprovalStates))
```

<img width="554" alt="Image" src="https://github.com/user-attachments/assets/6e3bc5f6-79df-42e0-b789-01a84b4ce4fe" />

This way passes through the types so that the zod schema can recognise them correctly.
