### ISSUE TITLE
Uncaught TypeError: Cannot convert a Symbol value to a number

### ISSUE THREAD

**Issue by despairblue** [colinhacks/zod#238]
The following code sample with throw said error because after the validation failed the `refine` function is still called:

```ts
z.union([z.number(), z.string().transform(z.number(), Number.parseFloat)])
  .refine((v) => v >= 1)
  .parse("foo");
```

This is supposed to accept `5` or `"5"` and reject anything that is not parsable into a positive number. 

But the refine will be called even if the union parsing failed and then `v` will be `Symbol("invalid_data")`

```
> z.union([z.number(), z.string().transform(z.number(), Number.parseFloat)]).refine((v) => v >= 1).parse("foo");
Uncaught TypeError: Cannot convert a Symbol value to a number
    at repl:1:92
    at Object.check (/home/despairblue/git/wunderflats/api/node_modules/zod/lib/cjs/types/base.js:167:34)
    at ZodUnion.parse (/home/despairblue/git/wunderflats/api/node_modules/zod/lib/cjs/parser.js:892:41)
> 
```

Without the refine it works as expected:

```
> z.union([z.number(), z.string().transform(z.number(), Number.parseFloat)]).parse("foo");
Uncaught ZodError: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "number",
            "received": "string",
            "path": [],
            "message": "Expected number, received string"
          }
        ]
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "number",
            "received": "nan",
            "path": [],
            "message": "Expected number, received nan"
          }
        ]
      }
    ],
    "path": [],
    "message": "Invalid input"
  }
]
    at new ZodError (/home/despairblue/git/wunderflats/api/node_modules/zod/lib/cjs/ZodError.js:73:28)
    at ZodUnion.parse (/home/despairblue/git/wunderflats/api/node_modules/zod/lib/cjs/parser.js:195:17) {
  issues: [
    {
      code: 'invalid_union',
      unionErrors: [Array],
      path: [],
      message: 'Invalid input'
    }
  ],
  addIssue: [Function],
  addIssues: [Function],
  flatten: [Function]
}
> 
```

Question regarding this. It seem `refine` function are not allowed to throw. ~~Does that mean a `refine` function **must** succeed?~~

Forget the last part as they can return `false` obviously.

**Comment by despairblue** [comment]
I thought about this for a bit. So what I actually need is a combination of `transform` and `refine`:

* `transform` takes a value of one type and returns a value of another type
	* it is not allowed to fail
* `refine` takes a value of one type and returns a boolean signaling if that value passes some validation
	* it can fail by returning `false`
	* it **can't** change the type of the value passed in

So what I actually wanted to do above is first, using `transform` to try to turn a string into a number, and if that succeeds using `refine` to make sure that the number is positive.

And doing so I hit the weird error where the `refine` function is typed to receive a number, but receives a Symbol instead. :shrug:

**Comment by despairblue** [comment]
I managed to do it by first refining, then transforming and then refining again:

```ts
const schema = z.object({
  positiveNumber: z
    .union([z.number(), z.string()])
    .refine(
      (value) => {
        const parsed = Number.parseInt(String(value));

        if (Number.isNaN(parsed)) {
          return false;
        } else if (!Number.isFinite(parsed)) {
          return false;
        } else {
          return true;
        }
      },
      { message: "mustBeTypeOf:number" },
    )
    .transform(z.number(), (value) => Number.parseInt(String(value)))
    .refine((v) => v > 0, { message: "mustBeMin:1" })
    .optional(),
})
```

Sadly I had to repeat the `parseInt` and actually I also need to try catch the first and second refinement for safety reasons, otherwise `schema.parse` and `schema.safeParse` could through.

So I end up with this:

```ts
const schema = z.object({
  positiveNumber: z
    .union([z.number(), z.string()])
    .refine(
      (value) => {
        try {
          const parsed = Number.parseInt(String(value));

          if (Number.isNaN(parsed)) {
            return false;
          } else if (!Number.isFinite(parsed)) {
            return false;
          } else {
            return true;
          }
        } catch {
          return false;
        }
      },
      { message: "mustBeTypeOf:number" },
    )
    .transform(z.number(), (value) => Number.parseInt(String(value)))
    .refine(
      (v) => {
        try {
          return v > 0;
        } catch {
          return false;
        }
      },
      { message: "mustBeMin:1" },
    )
    .optional(),
})

So now I'm just wondering if I'm doing something wrong :smile:

**Comment by despairblue** [comment]
In the code of v2 I can see that transformers probably could throw in the past:

https://github.com/colinhacks/zod/blob/f6759d0963e36f352fab9e688f19a5281af8ab35/src/parser.ts#L1066-L1089

Is this going to be added back?

**Comment by despairblue** [comment]
Actually I found a nice way to do it:

```ts
const toInt = z.transformer(z.any(), z.number(), Number.parseInt);
const schema = z.object({
  positiveNumber: toInt
    .refine((v) => v > 0, { message: "mustBeMin:1" })
    .optional(),
})
```

Only caveat is that it now reports that it received NaN instead of what it actually received:

For `schema.parse({positiveNumber: "foobar"})

```
    [
      {
        "code": "invalid_type",
        "expected": "number",
        "received": "nan",
        "path": [
          "positiveNumber"
        ],
        "message": "Expected number, received nan"
      }
    ]
```

But that's ok.

**Comment by colinhacks** [comment]
Glad this is working for you. Transformers can be very counterintuitive when you nest them inside other schemas, like you did in your first attempt. Best to keep all transforms at the top level where possible. 

The `Cannot convert a Symbol value to a number` error is a weird side effect of how Zod is implemented. If an error is detected, Zod sets the output to Symbol('invalid_data'). Zod is supposed to throw when this happens, looks like you find an edge case where that symbol continues through the parsing/validation chain. I'll look into this.

For now this seems solved so I'm going to close.

**Comment by despairblue** [comment]
@colinhacks thanks for the quick reply. Let me summarize what I've taken away from this, so I can make PRs to the readme and one with a failing test, if you like me to.

* Rules of Refinements
	* MUST NOT throw
	* failure MUST be notified by returning `false`
* Rules of Transformers
	* MUST NOT throw
	* input and output are parsed according to the first 2 arguments
	* transforms from one type to another MAY fail by returning a value that fails the output validation
		* example: 
			```ts
			// OK `lodash.toNumber` does not throw, but returns NaN if conversion fails
			z.transformer(z.any(), z.number(), lodash.toNumber)

			// OK
			z.transformer(z.string(), z.boolean(), value => {
				if (value === 'true') {
					return true
				} else if (value === 'false') {
					return false
				} else {
					// This will return a string, which fails the `z.number()` 
					// validation zod is going to do with the return value.
					return value as any
				}
			})

			// NOT OK `z.any()` passes everything along, but `Number.parseFloat`
			// sometimes returns NaN and sometimes throws, like for Symbols.
			z.transformer(z.any(), z.number(), Number.parseFloat)
			```
	* transforming from the same type to the same type MUST NOT fail (it cannot use the above trick and returning something that will fail
		* use a refine in combination with a transform for that
		* example
			```ts
			// NOT OK
			z.transformer(z.string(), z.string(), filePath => {
				const parts = filePath.split(".");
				
				if (parts.length > 1) {
					return parts[parts.length -1]
				} else {
					// What now? Return a wrong type? That would give a wrong error message.
					// We have to refine the string first making sure there is an extension.
				}
			})

			// OK
			z.string()
				.refine(
					// Now we know the string has at least 2 elements separated by a period.
					value => value.split(".").length > 1,
					{ message: "file path has not extension" }
				)
				.transform(z.string(), filePath => {
					const parts = filePath.split(".");
				
					return parts[parts.length -1]
				})
			```


@colinhacks 

1. Are my assumptions above correct regarding how to use transformations and refinements?
2. Would you accept a PR to the readme making some of those things clear (e.g. never to throw or how to fail transformations)
3. Still wondering about the commented out code in the parser that leads me to think that throwing from a transformer will be allowed in the future, is this going to come?
4. Should I create a PR with a failing test regarding the Symbol error (I would try to fix it too)?

Best.

**Comment by colinhacks** [comment]
This is a good writeup. To your points:

1. Transformation functions should never throw. I don't think the "trick" you're referring to should be documented as a valid/acceptable approach. Like you say elsewhere, you should use refinements to make sure the inputs are valid before calling `.transform`. The strong distinction between refinements and transformations is deliberate. The idea is that ALL modifications to the value occur within transformers, and nowhere else. 
2. Absolutely!
3. That commented section is just a remnant of a different implementation, I don't think it makes sense to catch errors in the transformation function. Though I suppose I could be convinced 🤷‍♂️  Perhaps I could introduce a new `ZodIssue` subtype for `failed_transformation`. Perhaps it makes sense for Zod to catch all transformation/refinement errors so you don't need to write separate try/catch logic for Zod errors and other unexpected errors. If you feel strongly about that, you could write it up as an RFP so the community can comment on it. Here's an example RFP you could use as a model: https://github.com/colinhacks/zod/issues/197
4. Also absolutely! Make sure you're forking the v2 branch. 👍

**Comment by despairblue** [comment]
I created 2 PRs, one for the bug and one for making it clear that refinements and transformers must not throw.

>  don't think the "trick" you're referring to should be documented as a valid/acceptable approach. Like you say elsewhere, you should use refinements to make sure the inputs are valid before calling .transform

Makes sense, but I'll probably just continue using it like this. The reason is that needing a refinement and a transformer to be kept in sync (which may also be defined in totally different places) is a bug that is just waiting to happen. Technically it's a clean separation of concerns, but the usability for the developer/team using this is hurt by this I fear.

Regarding 3. I currently went with defining all refinements and transformations in another file and wrap them in a try catch function, the refinement one returns just false on error and the transformer the value that was passed in. Seems to work so far.

**Comment by colinhacks** [comment]
Thanks for all your work on this! I merged these last night 🤙
