### ISSUE TITLE
Refine is taking precedence over optional, nullable, nonempty

### ISSUE THREAD

**Issue by cybervaldez** [colinhacks/zod#239]
I've been using .regex for my validations and recently [saw a tip in the docs](https://github.com/colinhacks/zod#strings) to use validator.js for that so I went ahead and tried it out using refine, now the problem is refine seems to take precedence over optional, nullable, nonempty. 

```
import * as zod from "zod";

import isDate from 'validator/es/lib/isDate'
import toDate from 'validator/es/lib/toDate'

let test = zod.string().optional().nullable().refine(isDate, { message : "Please use the format YYYY-MM-DD(e.g 1986-02-20, 1986/02/20)" })
console.log(test.safeParse("")) // error
console.log(test.safeParse(null)) // error
console.log(test.safeParse(undefined)) // error
```

**Comment by colinhacks** [comment]
This is expected. If you just want to refine the string schema, you should move the call to `.refine`:

```ts
zod.string().refine(isDate, { message : "Please use the format YYYY-MM-DD(e.g 1986-02-20, 1986/02/20)" }).optional().nullable();
```

Calling `X.optional()` is equivalent to `z.union([X, z.undefined()])`.
