### ISSUE TITLE
Email validation broken

### ISSUE THREAD

**Issue by timothyarmes** [colinhacks/zod#2396]
Hi,

zod is rejecting valid email addresses of the form a@b.c.com (note the two dots after the @).

**Comment by mauricedb** [comment]
Same here. And the email in question is actually used to send emails so definitely works. The actual email we are using is more like `abcde.abcd+1234567890123@abcdefg.com.test-google-a.com` where I replaced letters for other letters etc for privacy.

**Comment by reminjp** [comment]
#2274 should solve this. but not yet merged.

**Comment by cullylarson** [comment]
Another example of a failing address: `a@asdf.ka1.asdf.com`

**Comment by hkroger** [comment]
Is this moving or is there a version that we can downgrade to fix this?

**Comment by Dimrok** [comment]
Same for `first.last@physik.uni-muenchen.de`.

**Comment by Dimrok** [comment]
To give more context the current implementation favor speed over correctness, which is debatable. 
 
> // old version: too slow, didn't support unicode

```TypeScript
// from https://stackoverflow.com/a/46181/1550155
// old version: too slow, didn't support unicode
// const emailRegex = /^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))$/i;
//old email regex
// const emailRegex = /^(([^<>()[\].,;:\s@"]+(\.[^<>()[\].,;:\s@"]+)*)|(".+"))@((?!-)([^<>()[\].,;:\s@"]+\.)+[^<>()[\].,;:\s@"]{1,})[^-<>()[\].,;:\s@"]$/i;
// eslint-disable-next-line
// const emailRegex =
//   /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([0-9]{1,2}))\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([0-9]{1,2}))\])|(\[IPv6:(([a-f0-9]{1,4}:){7}|::([a-f0-9]{1,4}:){0,6}|([a-f0-9]{1,4}:){1}:([a-f0-9]{1,4}:){0,5}|([a-f0-9]{1,4}:){2}:([a-f0-9]{1,4}:){0,4}|([a-f0-9]{1,4}:){3}:([a-f0-9]{1,4}:){0,3}|([a-f0-9]{1,4}:){4}:([a-f0-9]{1,4}:){0,2}|([a-f0-9]{1,4}:){5}:([a-f0-9]{1,4}:){0,1})([a-f0-9]{1,4}|(((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([0-9]{1,2}))\.){3}((25[0-5])|(2[0-4][0-9])|(1[0-9]{2})|([0-9]{1,2})))\])|([A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])*(\.[A-Za-z]{2,})+))$/;
// const emailRegex =
//   /^[a-zA-Z0-9\.\!\#\$\%\&\'\*\+\/\=\?\^\_\`\{\|\}\~\-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;
// const emailRegex =
//   /^(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])$/i;
const emailRegex =
  /^([A-Z0-9_+-]+\.?)*[A-Z0-9_+-]@([A-Z0-9][A-Z0-9\-]*\.)+[A-Z]{2,}$/i;
// const emailRegex =
//   /^[a-z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-z0-9-]+(?:\.[a-z0-9\-]+)*$/i;
```

For those who want correctness, a `z.string().refine(...)` with your chosen regex or [validate.js](https://validatejs.org/) should do the trick.

**Comment by AlexandreBourdeaudhui** [comment]
Hey, same issue here with xxx@xxx.xxx-tech.sncf
Have we any ETA for the new release ? Wanna try it 🙌

**Comment by paradox37** [comment]
Just got a report from the user that his email is not accepted. Format is email@something.something-email.com. It would be nice for this to be fixed ASAP.

**Comment by intellix** [comment]
One email I see that fails is:
```
xxxxxxx@students.bcsc.k12.in.us
```

**Comment by micmcgrorty** [comment]
Apostrophes in names are also broken, so if your name is eg `O'Reilly` and that's in your email address it now fails Zod validation.

**Comment by DavidTimms** [comment]
@colinhacks I believe this issue is now fixed and the issue can be closed. All of the examples provided in this thread are successfully parsed by Zod 3.22.4.

**Comment by brilliantti** [comment]
Another example of failing address: mike@bike.com
Mystically these addresses are allowed: mikes@bike.com, mike@bikes.com, mike@dike.com or mike@ike.com

**Comment by willdspd** [comment]
A possibly related bug: Incorrectly formatted emails with multiple TLD 'dots' are incorrectly passing validation. For example, `johndoe@yahoo.co..uk` passes validation, which it shouldn't due to `..` between `co` and `uk`. I'm on version  `3.20.5`

**Comment by fuzzypawzz** [comment]
Danish/Swedish letters like ö or ø isn't accepted either. Those are valid to have in emails nowadays.

Just want to put it out there. Lmk if I should create a new issue for this :-)

**Comment by colinhacks** [comment]
I'm closing this since #2157 is the current final word on this. Nearly all the issues with dots and apostrophes have been resolved in Zod 3.22 or 3.23.

@fuzzypawzz Those characters aren't allowed in Gmail which is part of the rationale behind making Zod's email validation quite strict.

![Screenshot 2024-05-16 at 1 12 23 PM](https://github.com/colinhacks/zod/assets/3084745/3b3b9c7a-341a-402a-870b-e7df175357f4)

**Comment by fuzzypawzz** [comment]
@colinhacks Sorry for my bad example. It's correct that gmail doesn't allow those letters.
However there are email providers that allows those special letters, and it's an issue in Nordic enterprises - you could argue that's it is not a major issue, however we (the corp im working for currently) are not able to use the email validator from Zod, instead we would have to build our own custom validators.

**Comment by boblitex** [comment]
`bob_+.'b@gmail.com` also somehow passes zod validation. if I remove the last alphabet, then it doesn't pass, but adding that last 'b' makes it pass somehow
