### ISSUE TITLE
Validate unix timestamp (milliseconds)

### ISSUE THREAD

**Issue by giomarino** [colinhacks/zod#2398]
I didn't found any specific rule to validate unix timestamp, my object is structured like this:
```
{
   "start_date": 1683114592000,
   "end_date": 1683114627000
}
```

Attributes start_date and end_date are unix timestamp in milliseconds. I need also to express in my validation rule:
1. end_date must be greater than start_date
2. start_date must be greater than system time

**Comment by akomm** [comment]
```ts
import {z} from "zod"

const UnixDateRange = z.object({
    from: z.number().int().min(0),
    thru: z.number().int().min(0)
}).refine(({from, thru}) => from <= thru, "invalid range, from is greater than thru")

const unixDateRange = UnixDateRange.parse({
   from: 1683114592000,
   thru: 1683114627000
})
```
