### ISSUE TITLE
Skip regex() when optional() and string is empty ""

### ISSUE THREAD

**Issue by cybervaldez** [colinhacks/zod#240]
It makes more sense to only go through regex when the value is not empty for optional(), it removes overhead and it makes things more elegant. Currently to accomplish this requirement we need to allow empty in regex or to remove the empty fields from the formData before passing it to .parse

```
// Middle Name(optional)
const middleName = zod.string().optional().regex(/^[a-zA-Z0-9]+$/, { message: "Only alphabets and numbers are allowed." })
middleName.parse("");  // returns regex error message
```

My current workaround but honestly it really shouldn't go to that step since there's no need for regex to validate an empty string
```
// prepend $| to allow empties
const middleName = zod.string().optional().regex(/^$|[a-zA-Z0-9]+$/, { message: "Only alphabets and numbers are allowed." })

```

**Comment by colinhacks** [comment]
I don't support this, seems like a weird edge case. The regex checks should be run on any string that gets passed in. I recommend using a custom refinement:

```ts
zod.string().optional().refine(val => {
  return (val === "" || /^[a-zA-Z0-9]+$/.test(val));
}, { message: "Only alphabets and numbers are allowed." })
```
