### ISSUE TITLE
safeParse throws if refine throws

### ISSUE THREAD

**Issue by cdaringe** [colinhacks/zod#2401]
# Problem

`schema.safeParse(input)` should yield `.error` if it fails, but refinement that throws breaks the "safe" part of the contract. `.refine` isn't supposed to throw, but ...errors happen :)

# Discussion

```js
const schema = z.string().refine(() => { throw new Error("kaboom") });
schema.safeParse("weeeeeee"); // throws
// Uncaught Error: kaboom
```

I expected a `{ error: ZodError, success:false }`.

Could/should this be the norm? I did search existing issues for keywords, but didn't see discussion on this topic.

**Comment by cdaringe** [comment]
scram stalebot

**Comment by Malkiz** [comment]
This also happens if the `preprocess` function throws:

```
z.preprocess(data => { throw new Error('asdf') }, z.number()).safeParse(1)
```

**Comment by colinhacks** [comment]
This is behaving as intended currently. An error in a refinement is considered an application-level bug, not a validation error. The thinking is that catching this error in Zod would make it harder to debug actual real-life bugs, and you can always use `try/catch`. But if Zod catches these errors there's no way to opt-out of this and allow errors to bubble up.

**Comment by cdaringe** [comment]
> But if Zod catches these errors, there's no way to opt-out of this and allow errors to bubble up

I hear your argument. I may have some js bug inside my parse logic, and catching that isnt your intent. When calling .safeParse, semantically, it seems I’m completely operating within the context of a zod parsing operation and expecting failure as a possible output. If i was not expecting failure, i would have used .parse.

safeParse, in your position, is only catching failing validations. Its just that… its not really safe. I guess im caught up in the semantics. It seems more correct for a safe thing to handle errors than a safe thing to… change the return type relative to a sibling method. I would maybe advocate for .validate (which returns a Result like type) or .validateExn which throws. This is an ocaml convention that is p nice.

closing, but food for thought

**Comment by MarcusHSmith** [comment]
`.safeParse` is returning

```TypeError: Cannot read properties of undefined (reading '_parse')
    at ZodObject._parse (/Users/marcusmth/Documents/Primitives/turbo/node_modules/zod/lib/types.js:1739:37)
    at ZodObject._parseSync (/Users/marcusmth/Documents/Primitives/turbo/node_modules/zod/lib/types.js:129:29)```
    
    This doesn't feel right semantically
