### ISSUE TITLE
Generic transformers?

### ISSUE THREAD

**Issue by scotttrinh** [colinhacks/zod#241]
Thanks for a great library! Was doing some exploration for using, and was wondering if there was a way to make a "generic" transformer-like thing. I have a generic type called `Serialized` which basically maps a type that contains dates (recursively) to a type that swaps those properties for strings. This type is used for Postgres `to_json` and over-the-wire dates from API to client. It looks like:

```ts
export type Serialized<T> = {
  [P in keyof T]: T[P] extends Date
    ? string
    : T[P] extends Date | null
    ? string | null
    : T[P] extends any[]
    ? Serialized<T[P]>
    : T[P] extends any[] | null
    ? Serialized<T[P]> | null
    : T[P] extends object
    ? Serialized<T[P]>
    : T[P];
};
```

In my code, I'm currently manually creating schemas that `.extend` the base schema and replace the date(|null) properties with string(|null) manually, but I was wondering if there was a way to abstract that out such that I could, in essence, build up the `ZodObject._shape` dynamically?

**Comment by colinhacks** [comment]
Not currently I'm afraid. If you need separate schemas for the "string version" and the "Date version", then the `.extend` approach is your best bet. You might want to look into transformers, this _may_ be a good use case for them.

**Comment by scotttrinh** [comment]
> You might want to look into transformers, this may be a good use case for them.

Yeah, transformers definitely help with what I'm currently doing, but they are not generic: they require concrete schema(s) to work. A generic transformer would take one schema, introspect on it, and return a new schema with some transformation applied to it. I tried to quickly throw something together that looks at the private `_shape`, but IIRC the exported types didn't include what I would need to build it properly. If I get a chance to work on it some more, I'll open a PR against `v2` to add something like this, or at least expose any types that make it possible to publish as a separate package.

Thanks!

**Comment by GitUT** [comment]
I'm also in need of this functionality (if I understood correctly). I tried building schemas programmatically but couldn't get typescript to understand the type of the resulting schema.

Here's an excerpt of what I'm doing manually right now. Obviously it's very susceptible to bugs.

`// multi_cell
export const multiCellSchema = z.object({
    id: mysqlTypes.uintS.optional(),
    variety_id: mysqlTypes.uintS,
    multi_field_id: mysqlTypes.usmallintS,
});
export type multiCell = z.infer<typeof multiCellSchema>;
export const multiCellPartialSchema = multiCellSchema.partial();
export type multicellPartial = z.infer<typeof multiCellPartialSchema>;
export const multiCellQuerySchema = z.object({
    id: z.object({
        in: z.array(mysqlTypes.uintS).optional(),
        not: z.array(mysqlTypes.uintS).optional(),
        gt: mysqlTypes.uintS.optional(),
        lt: mysqlTypes.uintS.optional(),
    }),
    variety_id: z.object({
        in: z.array(mysqlTypes.uintS).optional(),
        not: z.array(mysqlTypes.uintS).optional(),
        gt: mysqlTypes.uintS.optional(),
        lt: mysqlTypes.uintS.optional(),
    }),
    multi_field_id: z.object({
        in: z.array(mysqlTypes.usmallintS).optional(),
        not: z.array(mysqlTypes.usmallintS).optional(),
        gt: mysqlTypes.usmallintS.optional(),
        lt: mysqlTypes.usmallintS.optional(),
    }),
})`
