### ISSUE TITLE
Proper way to use zod enum without using native enum.

### ISSUE THREAD

**Issue by UrielCh** [colinhacks/zod#2414]
I have a sample enum as an object:

```ts
export const timeFilter = {
    ANY: "" as const,
    DAY: "r86400" as const,
    WEEK: "r604800" as const,
    MONTH: "r2592000" as const,
}
```
and I want to build the type: `z.enum(["", "r86400", "r604800", "r2592000"])`

If I use the syntax `z.enum(Object.values(timeFilter))` that will failed `Object.values` will return the type `string[]`

I also tried to used a const array with a const type:
```ts
export const validTimeFilter = Object.values(timeFilter) as typeof timeFilter[keyof typeof timeFilter][];
```
by now the error is:
```
Argument of type '("" | "r86400" | "r604800" | "r2592000")[]' is not assignable to parameter of type '[string, ...string[]]'.
```

I do not want to use enum for various reasons.

And I'm sure that a typical case should be present in the Zod documentation.

---

The syntax: 
```ts
export enum TimeFilter {
    ANY = "",
    DAY = "r86400",
    WEEK = "r604800",
    MONTH = "r2592000",
}
z.nativeEnum(TimeFilter)
```
works but that is a native enum.

**Comment by markjaniczak** [comment]
If you declare your enum object like this:

```
const timeFilter = {
    ANY: "",
    DAY: "r86400",
    WEEK: "r604800",
    MONTH: "r2592000",
} as const
```

It will resolve to:

```
const timeFilter = {
    readonly ANY: "",
    readonly DAY: "r86400",
    readonly WEEK: "r604800",
    readonly MONTH: "r2592000",
}
```

If you use `Object.values` on that object you will receive the following type:
`("" | "r86400" | "r604800" | "r2592000")[]`

You can also create a helper enum type like this:
`type TimeFilterEnum = (typeof timeFilter)[keyof typeof timeFilter]`

Hope that helps.
