### ISSUE TITLE
Any reason why `transform` doesn't have access to other props of the object?

### ISSUE THREAD

**Issue by jayarjo** [colinhacks/zod#2417]
Any reason why `transform` and `refine` do not have optional access to all other props of the object? Could have been another property in context object.

**Comment by akomm** [comment]
I did not make the decision, but my guess why it is  that way and it makes sense:

Transform operates on `type`, which might or might not be part of an `object` composition. Zod is composible, a `type` does not make any assumptions about its surrounding, just about its evtl. wrapped inner type (sort of a child relation). For example array type is aware of its item type.

Just think about that everything you use within `z.object(...)` is a type by itself, independent of the object.
