### ISSUE TITLE
Removing extra validation to create looser version of schema to validate types only?

### ISSUE THREAD

**Issue by Jussinevavuori** [colinhacks/zod#2419]
I have a schema for my form, which validates that the data has certain values inputted, emails are actually valid emails and so on, the regular form validation stuff. However, I also need to save the intermediate, non-valid data to `localStorage` to allow closing the form and continuing later. Currently an extremely simplified version pseudo-implementation of the solution looks like the following:

```tsx
const formSchema = z.object({ email: z.string().email(), /* ... */ });

function Form() {
  useOnFormChange(state => localStorage.setItem("form", JSON.stringify(state))

  function getFormDefaultState() {
    const jsonStr = localStorage.getItem("form")
    return JSON.parse(jsonStr) as any // No validation step
  }
// ...
}
```

Attempting to validate the `JSON.parse(jsonStr)` result would not work as I allow saving for example malformatted or empty email strings to the email field. They only need to be valid at submission. I would love a feature such as

```tsx
const bareFormSchema = formSchema.recursivelyRemoveExtraValidations()
// Equal to z.object({ email: z.string(), /* ... */ })

function getFormDefaultState() {
    const jsonStr = localStorage.getItem("form")
    const object = JSON.parse(jsonStr)
    return bareFormSchema.parse(object)
}
```

I was unable to create a custom function that would implement this logic. It should maintain the type and structure, but none of the validations such as `.min()`, `.max()`, `.refine()` , `.email()` or other non-type-specific information.

**Comment by Armadillidiid** [comment]
What was your solution? I'm trying to persist a form to local storage, and it seems redundant to recreate the schema without extra validations. It would be nice to have a way to disable `refine`, `superRefine`, and other validations.
