### ISSUE TITLE
No way to merge multiple schemas. request function to merge deep multiple schemas like javascript object spread

### ISSUE THREAD

**Issue by markgarel17** [colinhacks/zod#2424]
v3.20.6

We got no way to merge the **3 or more schemas** into 1 schema.

GiftVehicle.ts file
```
export const VehicleSchema = merge CarSchema, TruckSchema and SuperCarSchema 

Goal:
VehicleSchema = z.object({
  authToken: z.string(),
  colour:  z.string(),
  options: z
    .object({
      giftMessage: z.string().optional(),
      isConvertible: z.boolean().optional(),
      hasHugeWheels: z.boolean().optional(),
    })
    .optional(),
})
```

If we use `merge`, for more than 2 e.g. `CarSchema.merge(TruckSchema).merge(SuperCarSchema)`

it doesn't copy the deeper `options` correctly. after test, the `TruckSchema.options.hasHugeWheels` disappears.

`union` or `discriminatedUnion`  is not making it due to the way it works. its not merging of object properties.

any suggestions? please help thank you...

.
.
.
.
.

GiftCar.ts file
```
export const CarSchema = z.object({
  authToken: z.string(),
  colour:  z.string(),
  options: z
    .object({
      giftMessage: z.string().optional(),
      isConvertible: z.boolean().optional(),
    })
    .optional(),
})

call giftCar API
```

GiftTruck.ts file
```
export const TruckSchema = z.object({
  authToken: z.string(),
  colour:  z.string(),
  options: z
    .object({
      giftMessage: z.string().optional(),
      hasHugeWheels: z.boolean().optional(),
    })
    .optional(),
})

call giftTruck API
```

GiftSuperCar.ts file
```
export const SuperCarSchema = z.object({
  authToken: z.string(),
  colour:  z.string(),
  options: z
    .object({
      giftMessage: z.string().optional(),
      isConvertible: z.boolean().optional(),
    })
    .optional(),
})

call giftSuperCar API
```

**Comment by grcodemonkey** [comment]
If you split out the options schemas then this is a much easier problem to solve.  

There is no "discriminator" field for the union, so there's no way to programmatically determine the correct scenario for type validation.

I would expect to see something more like this:

```
const CarOptionsSchema = z.object({
  type: z.literal('car'),
  giftMessage: z.string().optional(),
  isConvertible: z.boolean().optional(),
})

const TruckOptionsSchema = z.object({
  type: z.literal('truck'),
  giftMessage: z.string().optional(),
  hasHugeWheels: z.boolean().optional(),
})

const SuperCarOptionsSchema = z.object({
  type: z.literal('superCar'),
  giftMessage: z.string().optional(),
  isConvertible: z.boolean().optional(),
})

const CarOptionTypesSchema = z.discriminatedUnion('type', [CarOptionsSchema, TruckOptionsSchema, SuperCarOptionsSchema])

export const CarApiSchema = z.object({
  authToken: z.string(),
  colour: z.string(),
  options: CarOptionTypesSchema.optional(),
})
```

**Comment by markgarel17** [comment]
@grcodemonkey Hey, thank you for the advise. this gave me insight and was able to do in another way.

I should've been more clearer with the title too. to request a function that can merge deep multiple schemas.

`VehicleSchema = z.merge([
CarSchema,
TruckSchema,
SuperCarSchema
])`

with the same result as javascript object, and spread operator.

```
const vehicle = {
...Car,
...Truck,
...SuperCar
}
```

**Comment by sannajammeh** [comment]
Requesting to reopen this.

**Comment by lausek** [comment]
Can't you just use `intersection`/`schema.and(...)?

```typescript
const VehicleSchema = TruckSchema.and(CarSchema).and(SuperCarSchema)
```

**Comment by ptrxyz** [comment]
> Can't you just use `intersection`/`schema.and(...)`?
> 
> ```ts
> const VehicleSchema = TruckSchema.and(CarSchema).and(SuperCarSchema)
> ```

Depends on what you want to achieve:

```js
const s1 = z.object({ id: z.string() })
const s2 = z.object({ id: z.number(), prop: z.string() })
const totalAnd = s1.and(s2)   // { id = never }
const totalOr = s1.or(s2) // { id = number | string; prop = string }

const merged = merge(s1, s2) // { id = number; prop = string }
```

So, question: how would a function `merge` look like, that adds props from `s2` to `s1`, overwriting props in `s1` if already present?

**Comment by geoffreygarrett** [comment]
One problem is that:

```typescript
const VehicleSchema = TruckSchema.and(CarSchema).and(SuperCarSchema)
```

Results in a `ZodIntersection`, not a `ZodObject`, so I can't use `.passthrough()` on it. 

Also:

> So, question: how would a function merge look like, that adds props from s2 to s1, overwriting props in s1 if already present?

Yes, exactly like:

```typescript
const merged = {
...s1,
...s2
}
```

**Comment by geoffreygarrett** [comment]
In fact, this works for me:

```typescript
const VehicleSchema = z.object({
   ...TruckSchema.shape,
   ...SuperCarSchema.shape
});
```

**Comment by StiliyanKushev** [comment]
Why is this not supported yet?

**Comment by chriskuech** [comment]
I too would like this reopened please

**Comment by StiliyanKushev** [comment]
> In fact, this works for me:
> 
> ```typescript
> const VehicleSchema = z.object({
>    ...TruckSchema.shape,
>    ...SuperCarSchema.shape
> });
> ```
>    
> 
> 
> 
> 

This works in some cases but not In others. It fails to work where you have a more complex zod type such as when using `.optional()` for example.

**Comment by nanotower** [comment]
Will be useful, I agree. I was wondering how to do that and I got here.

**Comment by ggrantrowberry** [comment]
I would like to see this as well.

**Comment by MatkoMilic** [comment]
This would be useful for my scenario, basically I have a multi-step form that has three steps, each step has its own zod and react-form-hooks validation and I wish I can combine all three validations when I try to submit to database just in case. Would be sweet. This sometimes work and sometimes doesn't:

const VehicleSchema = z.object({
   ...TruckSchema.shape,
   ...SuperCarSchema.shape
});

**Comment by issam-seghir** [comment]
> This would be useful for my scenario, basically I have a multi-step form that has three steps, each step has its own zod and react-form-hooks validation and I wish I can combine all three validations when I try to submit to database just in case. Would be sweet. This sometimes work and sometimes doesn't:
> 
> const VehicleSchema = z.object({ ...TruckSchema.shape, ...SuperCarSchema.shape });

I have the same usecase , have you found a better way ? you still have a problem with the current method os spreading shape?
