### ISSUE TITLE
Validation order 2.0.0-beta.25

### ISSUE THREAD

**Issue by jrwm** [colinhacks/zod#243]
Hi, 

I've created a sandbox for a situation, when validation rules take strange order. 

Assuming having a schema like this 
`const formValuesSchema = z.object({
  name: z.string(),
  company: z.string(),
  email: z.string().email()
});`

I don't get an Invalid email error when email is filled, until the other fields are filled as well.
It happens on version 2.0.0-beta.25

https://codesandbox.io/s/elegant-drake-4ultm?fontsize=14&hidenavigation=1&theme=dark&file=/src/index.ts:27-137

**Comment by sylvanaar** [comment]
You mean, the shape check fails (invalid/missing fields), and that is preventing the `email()` refinement.

That is the algorithm, check if it is an object, then check if the object has the right shape, then check the types of the keys.

https://github.com/colinhacks/zod/blob/master/src/parser.ts#L322-L362

**Comment by jrwm** [comment]
Yeah, so it's not a bug, it's a feature. Although it is not convenient for displaying form validations errors to a user.

**Comment by colinhacks** [comment]
This is indeed a bug! @jrwm as you described, Zod tries to surface as many errors as possible. Thanks for pointing it out. It's fixed in beta 27:

```ts
import * as z from 'zod';

const formValuesSchema = z.object({
  name: z.string(),
  company: z.string(),
  email: z.string().email(),
});

formValuesSchema.parse({
  email: 'aaa',
});

/*
 [
   {
     code: 'invalid_type',
     expected: 'string',
     received: 'undefined',
     path: ['name'],
     message: 'Required',
   },
   {
     code: 'invalid_type',
     expected: 'string',
     received: 'undefined',
     path: ['company'],
     message: 'Required',
   },
   {
     validation: 'email',
     code: 'invalid_string',
     path: ['email'],
     message: 'Invalid email',
   },
 ];
*/
```
