### ISSUE TITLE
Creating default for a property in a recursive schema causes error

### ISSUE THREAD

**Issue by JimSchofield** [colinhacks/zod#2435]
Here is a minimal example:

```ts
export const mySchemaBase = zod.object({
  someOptionalThing: zod.boolean().default(true),
});

export type SchemaWithChildren = zod.infer<typeof mySchemaBase> & {
  children: SchemaWithChildren[];
};

export const finalSchema: zod.ZodType<SchemaWithChildren> = mySchemaBase.extend({
  children: zod.lazy(() => finalSchema.array()),
});

// Note that the type is correct, and when we parse, the parsing is fine
type MyType = zod.infer<typeof finalSchema>;
    // ^?
```

Error happens at `export const finalSchema`

When I check the type on the final line, it seems to be correct.  When I parse items, it seems to parse correctly giving the default value.  It appears to be an error with `finalSchema` because we are "helping" the type for the recursive schema using `zod.ZodType`.

Playground link: https://www.typescriptlang.org/play?ssl=17&ssc=10&pln=1&pc=1#code/JYWwDg9gTgLgBAKjgQwM5wF4QCZwGZQQhwDkW2JA3AFDUCmAHpLHAMYQB2q8IAngMqsAFnRDIAQmjpwAvJhwA6CACMAVnVYwAFAG9qcOKiJ0A8mBjBOyADYAVIcA4BzAFzzsC5RAjW6yDloAlArYdHjIAK7W2jBQEXSBADTUAL6BNPRM0PAwvGDSgiJiAOrAMEIAwg7W2FB0HLLuCo54dFAAPLn5EHhwfIWiElIAfHAAZHB6BsLANXUcbgMlZZXVtfUA2gC6NCkZjMzw7FzweI42S8hu5AoAWji2eXTtl6XlVbPrHKNy-cKDklQdAUjBg9Wwun0bDW82uimsyAwvC0QVkozOHAu-zECmQUCgyGRgSSqXStAA9OS4AA5CBguDlZA5EQMp5wYDodj4jQwRIoDi4ADuIgagukYDxQL55XFkscTnZ6AxdGoXWkAFleI98o0bi02p0nj18OdrJdhjQDAZKXAAHoAfiAA

**Comment by mr-kelly** [comment]
Same problem

**Comment by mr-kelly** [comment]
<img width="728" alt="image" src="https://github.com/user-attachments/assets/1da915bb-bbf2-4d14-8314-1231f81e2f9e">

Fix your playground by change `z.infer` to `z.input` 

@JimSchofield

**Comment by adamborowski** [comment]
@JimSchofield I think it still introduces some false inference here:

Just compare same field but parsed with different schemas

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAKjgQwM5wF4QCZwGZQQhwDkW2JA3AFDUCmAHpLHAMYQB2q8IAngMqsAFnRDIAQmjpwAvJhwA6CACMAVnVYwAFAG9qcOKiJ0A8mBjBOyADYAVIcA4BzAFzzsC5RAjW6yDloAlArYdHjIAK7W2jBQEXSBADTUAL6BNPRM0PAwvGDSgiJiAOrAMEIAwg7W2FB0HLLuCo5gETAAPLn5EHhwfIWiElIAfHAAZHB6BsLANXUcbgMlZZXVtfUA2gC6NCkZjMzw7FzweI42S8hu5AoAWji2eXTtl6XlVbPrHKNy-cKDklQdAUjBg9Wwun0bDW82uimsyAwvC0QVkozOHAu-zECmQUCgyGRgSSqXStAA9OS4AA5CBguDlZA5EQMp5wYDodj4jQwRIoDi4ADuIgagukYDxQL55XFkscTnZ6AxdGoXWkAFleI98o0bo48HQoJ0nj18OdrJdhjRKQY4AA9AD8tGox24cA4EAAMpwnIazBYrNYAIyNP5FIZAhQSqBArQcKLWYJGECmcyWTF2BzOa1U22O2iu+Ae73OP1pwMAJkaGKx4ajkrocYTSeM-vTNns8pztvtDqAA

<img width="712" alt="image" src="https://github.com/user-attachments/assets/04a5cc57-4263-4c65-a6f8-839fd172bf90" />
