### ISSUE TITLE
Representing a function with additional properties

### ISSUE THREAD

**Issue by ahuth** [colinhacks/zod#244]
Is it possible to represent a function that also has additional properties on it?

Thinking specifically of cases like [Storybook stories](https://github.com/storybookjs/storybook/blob/b8aa525731ac2933a2489da51e449f617236e093/lib/addons/src/types.ts#L255-L262):

```ts
// Simplified from the real type
interface Story<Args, StoryFnReturnType> {
  (args: Args): StoryFnReturnType;
  storyName?: string;
}
```

These are functions with some properties added to them. Something like

```js
function SomeFunc() {
  // ...
}

SomeFunc.storyName = "hello there";
```

I haven't been able to find any existing issues or documentation around this, but let me know if this has already been brought up. I also understand if this is too challenging or not a priority to implement.

Thanks!

**Comment by colinhacks** [comment]
No, I'm afraid that isn't possible to represent currently.
