### ISSUE TITLE
Question: How to validate a set of properties as required?

### ISSUE THREAD

**Issue by chmac** [colinhacks/zod#245]
Firstly, thanks for zod. I found some of the other tools in your comparison, but zod is the one that really seems to fit for my use case. Plus, I'm deeply impressed by the 3 letter name which was unused in npm and elsewhere! :-)

I have 3 properties, `foo`, `bar` and `baz`. If `bar` is present, then so must be `baz`. In other words, `bar` and `baz` must always be present or absent together. I couldn't figure out how to achieve this result in TypeScript, maybe I need union interfaces, I'm not sure. Is there a way to do it in zod?

I created a duplicate type that requires both `bar` and `baz` and I use that inside `.refine()` with a `.check()`, but I wonder if there's a clearer way to express what I'm trying to do?

**Comment by chmac** [comment]
I figured out that this is possible with `z.union()`. zod has tighter validation constraints that TypeScript in this regard! Here's a simple example:

```typescript
const f = zod.object({
  foo: zod.string()
})
const b = zod.object({
  bar: zod.string(),
  baz: zod.string()
})
const both = f.merge(b)
const schema = zod.union([f, both])
```

In my tests, `{foo: '', bar: ''}` will fail to validate against this schema. While the inferred TypeScript type will be:

```typescript
type S = {
    foo?: string;
} | {
    bar?: string;
    baz?: string;
    foo?: string;
}
```

This type actually allows `{foo: '', bar: ''}`, something to do with union types allowing properties which exist anywhere in the union. Anyway, this works for our use case (validating yaml data) even if the TypeScript typing isn't 100% accurate.

**Comment by colinhacks** [comment]
Good solution! Glad it's working for you 👍
