### ISSUE TITLE
Type that allows any type of schema?

### ISSUE THREAD

**Issue by andresespinosapc** [colinhacks/zod#2462]
I want a function to receive any zod schema as an argument. If I use `z.ZodSchema` as a the type of the argument it works mostly fine, but if I use `.transform` or `.pipe` in the schema I'm passing as an argument it breaks.

This is my function:
```javascript
import axios from 'axios';
import { z } from 'zod';

async function apiFetcher<O>(zodSchema: z.ZodSchema<O>, options) {
  const response = await axios.request<O>(options);
  return zodSchema.safeParse(response.data);
}
```

And here's what doesn't work:
```javascript
const DataSchema = z.object({
  expiration_date: z.string().datetime().pipe(z.coerce.date()),
});

const data = apiFetcher(DataSchema, {/* options */});
```

**Comment by dplantera** [comment]
I'd assume the generic section is applicable here https://zod.dev/?id=writing-generic-functions

**Comment by andresespinosapc** [comment]
Thanks @dplantera ! Haven't seen that in the documentation, it worked perfectly.

**Comment by movahhedi** [comment]
So the answer for me is `z.ZodTypeAny`.
