### ISSUE TITLE
UUID Parsing fixed but not released on NPM

### ISSUE THREAD

**Issue by aren55555** [colinhacks/zod#2468]
Hi there, we are using the latest published version from NPM `3.21.4`. We were having some trouble parsing the zero-ish UUIDs hard coded in our test cases. For example `00000000-0000-0000-0000-000000000001` or `00000000-0000-0000-0000-000000000002`. 

[This recent commit](https://github.com/colinhacks/zod/commit/37e9c550460e4edd144da90d903e878c119c5cc1) seems to have rectified this problem. 

Is there any way to cut an NPM release such that we can absorb this change without having to maintain our own fork?

Thanks!

**Comment by StephenGrable1** [comment]
@colinhacks thanks for being a regexpert to patch this

 is there a plan to cut an npm release for thse updates?

**Comment by ropbastos** [comment]
Also in need of this 👉👈

**Comment by MuhammadAli-208** [comment]
@ropbastos facing the same error. any luck on this?

**Comment by colinhacks** [comment]
Landed in 3.22.0
