### ISSUE TITLE
Incorrect type when preprocessed is used?

### ISSUE THREAD

**Issue by donaldpipowitch** [colinhacks/zod#2486]
Hi there! I don't know if this is a bug, but I was wondering why `preprocess` creates a very different type then without it. Here is my [example](https://codesandbox.io/s/lucid-brahmagupta-hsdljj?file=/src/App.tsx).

I was wondering why `role` accepts e.g. `'ADMIN'`, but why `status` doesn't accept `['ACTIVE']` and is `unknown` instead.

<img width="539" alt="image" src="https://github.com/colinhacks/zod/assets/1152805/6a1431c5-7e60-45dd-8db4-7eae77549fbd">

**Comment by guy-confetti** [comment]
I'm not an expert but using `z.effect` seems to fix the issue
```ts
export const usersFilterSchema = z.object({
  role: z.enum(["USER", "ADMIN"]).nullable().default(null),
  status: z.effect(userStatusSchema, { type: 'preprocess', transform: stringToArrayQuery })
});
```
