### ISSUE TITLE
`.optional().default()` doesn't make property optional in typeScript type inference

### ISSUE THREAD

**Issue by kevinwolfcr** [colinhacks/zod#2491]
Hello,

I've encountered an issue when trying to use .optional().default() on a Zod schema. Even when a property is marked as .optional(), the inferred TypeScript type requires the property to be present.

Here's a simple example to illustrate the problem:

```typescript
import { z } from 'zod';

const schema = z.object({
  name: z.string(),
  rootDir: z.string().optional().default("default/path"),
});

type SchemaType = z.infer<typeof schema>;

function processConfig(config: SchemaType) {
  // Function implementation...
}

const config = {
  name: "myApp",
};

processConfig(config); // TypeScript error: 'rootDir' is missing in type '{ name: string; }' 
```

In this example, TypeScript expects both 'name' and 'rootDir' to be present in the 'config' object, even though 'rootDir' is marked as optional with a default value in the Zod schema.

My expectation would be that, since 'rootDir' is marked as .optional(), it should not be required in the inferred TypeScript type. I would expect this code to compile without errors, and for Zod to apply the default value of 'rootDir' at runtime when it's not provided.

Is this the intended behavior or am I misunderstanding the usage of .optional().default()?

Thanks for your help!

**Comment by vtgn** [comment]
Hello,

I'm just a beginner with the use of zod library, but I suppose the .**default** method is not supposed to be used at the same time than the **.optional** method: indeed, the ".default" method's documentation says _"If the input is undefined, the default value is returned"_, so it includes the fact that the input may be undefined, so you don't need to add the ".optional" method.

But you're right that this case is not well managed by the library: it should be impossible to use these 2 methods at the same time, or else this case must be managed differently by generating no error.

Regards.

**Comment by scotttrinh** [comment]
This is working as intended but perhaps worth calling out in the docs. `default` causes the value to always be present since if it isn't, the default value is used. `infer` gets the type of the output value, in fact it is an alias of `output`. If you need a type of a valid input, there is an `input` type helper as well.

**Comment by kevinwolfcr** [comment]
> This is working as intended but perhaps worth calling out in the docs. `default` causes the value to always be present since if it isn't, the default value is used. `infer` gets the type of the output value, in fact it is an alias of `output`. If you need a type of a valid input, there is an `input` type helper as well.

Thanks for calling that out. I didn't knew the `.input()` existed before this. So this is working now:

```ts
const schema = z.object({
  name: z.string(),
  rootDir: z.string().default("default/path"),
})

function processConfig(config: z.input<typeof schema>) {
  // Function implementation...
}

processConfig({ name: "myApp"})
```

**Comment by huksley** [comment]
Could someone clarify how to get proper infer type and back in this situation?
I have a property which have default (I believe this is quite common) and it throws type inference of...

```
page: z.number().default(1),
```

https://gist.github.com/huksley/7d8c800d22cf5fa423e277ddc745a92f

**Comment by huksley** [comment]
@vtgn Thank you! I reiterated on your's and @scotttrinh detailed explanations and went with the following: I don't expose a "input" or "output" types separately as it generates too much types (if you have many zod schemas), instead I define schema type and when derive types from of that, as needed.

```ts
export type UserSchema = ZodSchema<
  z.output<typeof userSchema>,
  ZodTypeDef,
  z.input<typeof userSchema>
>;
```

**Comment by movahhedi** [comment]
So the point is using `z.input` for input and `z.output` (equivalent to `z.infer`) for output of the schema.
https://github.com/colinhacks/zod/issues/4179#issuecomment-3077449681
