### ISSUE TITLE
Custom error messages can't be modified with ErrorMap

### ISSUE THREAD

**Issue by vktrl** [colinhacks/zod#2492]
According to the [documentation](https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md#customizing-errors-with-zoderrormap) it should be possible to override all error messages, but it only works with custom errors only if the original message is undefined. Messages defined in refinements seem to be hardcoded and values returned by ErrorMap are ignored.

[codesandbox example](https://codesandbox.io/s/laughing-voice-10u0wk?file=/src/index.ts)

**Comment by adamsujeta** [comment]
I have opened an issue in react-hook-form [repo](https://github.com/react-hook-form/resolvers/issues/585). I realized that it was a mistake and it is an problem with zod and not react-hook-form. I have exactly the same problem I would love to be able to override every possible error message with ErrorMap but it is not working. Any updates on the issue?

**Comment by adamsujeta** [comment]
Looks like this PR is fixing the issue: https://github.com/colinhacks/zod/pull/2532

**Comment by thomaswinckell** [comment]
If I invert the condition here https://github.com/colinhacks/zod/blob/master/src/helpers/parseUtil.ts#L31, it works : 

Replace `message: issueData.message || errorMessage,` by  `message: errorMessage || issueData.message,`

I have not investigated so I don't know if inverting this condition have other consequences than fix this issue.

**Comment by colinhacks** [comment]
I think the current priority order makes more sense. It would be very odd if the error map couldn't be overridden by a special case defined at the level of an individual schema.

**Comment by vktrl** [comment]
Ok, that makes sense.
What I was trying to do is to use the message field as a code that gets replaced by a localized message down the line by the client. Solved the issue by using params.
