### ISSUE TITLE
Can I name my project ZodBus?

### ISSUE THREAD

**Issue by 3rd** [colinhacks/zod#2508]
Hey, thank you for Zod; it's great and we all love it.

I'm building an event bus that uses Zod to define the schema, infer everything, and validate the data.
Is it ok with you if I call it `ZodBus`?

It's on https://github.com/3rd/zodbus, and I just published it to NPM as `zodbus`, so that the name won't get sniped by trolls.

https://github.com/3rd/zodbus/assets/59587503/08d2c13c-cccd-407f-b14c-957d7dd5115d

**Comment by colinhacks** [comment]
Sure, I have no issues with this!

**Comment by 3rd** [comment]
Awesome, thanks again!
