### ISSUE TITLE
Why haven't we dropped a new release?

### ISSUE THREAD

**Issue by nicolassanmar** [colinhacks/zod#2530]
It's been a long time since the last `zod` release (almost 4 months), and there are a lot of useful changes since the last version.

Are we waiting until we complete something specific?

**Comment by nicolassanmar** [comment]
I'll ping @colinhacks for visibility, as this is already a few weeks old already

**Comment by scotttrinh** [comment]
I don't have a direct answer, but we _do_ publish canary releases, feel free to opt into a faster release cadence there!
