### ISSUE TITLE
Put typeName into `ZodTypeDef` interface

### ISSUE THREAD

**Issue by valerii15298** [colinhacks/zod#2543]
As we see here: https://github.com/colinhacks/zod/blob/master/src/types.ts#L56 `ZodTypeDef` only has `errorMap` and `description` but if check interfaces that extends `ZodTypeDef` we see that all of them have `typeName: ZodFirstPartyTypeKind` so why can’t we put typeName as property of `ZodTypeDef` ?

i also experience a problem when trying to programmatically explore zod schema at runtime like this:
```
declare const someSchema: ZodSchema;
console.log(someSchema._def.typeName; // getting ts error here
```
While we always know that `typeName` will be present in every zod type…

**Comment by dooleyb1** [comment]
@valerii15298 Currently experiencing the same ts error. Any update on getting your PR released?

**Comment by valerii15298** [comment]
No updates, this is the original PR and since it is stuck for a long time I wouldn't expect it to be resolved at any time soon or even at all
https://github.com/colinhacks/zod/pull/2459

I would recommend simply redeclare type locally in your project using typescript `declare` syntax as I did in my own project. It works fine.

Or if you wanna one time quck solution you can just use `ts-ignore` but I myself wouldn't go with it honestly...

**Comment by dooleyb1** [comment]
@valerii15298 Okay great, thanks mate appreciate it 🙇

**Comment by colinhacks** [comment]
Closing per https://github.com/colinhacks/zod/pull/2459

> console.log(someSchema._def.typeName)

I recommend casting `someSchema` to `ZodFirstPartySchemaTypes`, then you'll have access to `typeName` and TypeScript will automatically perform type narrowing for you if you `switch` on it's value.
