### ISSUE TITLE
Alias `z.infer` to `z.Infer`?

### ISSUE THREAD

**Issue by mikestopcontinues** [colinhacks/zod#2545]
Given that Infer is a type, are you open to aliasing it to a pascal-cased alternative? Similar for `z.input` and `z.output`?

**Comment by janhesters** [comment]
What's the difference anyways between `z.output` and `z.infer`?

**Comment by mikestopcontinues** [comment]
If memory serves, `infer` is an alias for `output`. It's still weird that these generic types are lowercase.

**Comment by janhesters** [comment]
@mikestopcontinues Thank you 🙏 Always wondered that.
