### ISSUE TITLE
Passing array to .endsWith

### ISSUE THREAD

**Issue by web-programmer-here** [colinhacks/zod#2551]
I want to validate emails from certain domains , example `yahoo.com, gmail.com, outlook.com`. Using `.endsWith` works perfectly for 1 domain but what if I want to validate it for all 3 domains? I can't pass an array of valid domains to `.endsWith`. 

Does `.endsWith` support array or just string?

**Comment by conorbrandon** [comment]
How about `z.string().regex(/gmail\.com|yahoo\.com|outlook\.com$/)`?

**Comment by antonyusupov** [comment]
I think you are using some library or framework maybe that will work. 
I've tried this way and actually that was great less typing it goes like this :
```
function validateEmail(email) {
  const emailRegex = /gmail\.com|yahoo\.com|outlook\.com$/;

  // checks the mails
  return emailRegex.test(email);
}

console.log(validateEmail('test@mail.com'));
console.log(validateEmail('example@gmail.com'));
```
 `validateEmail(email)`  will return true or false you can check the email valid or not valid.
This might differ on your code depends on library or framework you are using.

**Comment by colinhacks** [comment]
I'd recommend a regex or `.refine()` here.
