### ISSUE TITLE
TS Jest unsupported version warnings when running tests

### ISSUE THREAD

**Issue by jameschensmith** [colinhacks/zod#256]
When running tests in the v2 branch the output below is noticed.

```
ts-jest[versions] (WARN) Version 4.0.5 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=2.7.0 <4.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
```

This is due to a recent upgrade of the Typescript version without bumping the version for TS Jest. The following changes are recommended:

* Bump `ts-jest` from `25.2.1` to `26.4.4`
* Bump `jest` from `25.1.0` to `26.6.3`
* Bump `@types/jest` from `25.1.4` to `26.0.16`
* Change `tsConfig` key in `jest.config.json` to `tsconfig` (former is now deprecated)

**Comment by colinhacks** [comment]
Upgraded and fixed in beta 26!
