### ISSUE TITLE
Better type inference for arrays

### ISSUE THREAD

**Issue by willruggiano** [colinhacks/zod#2566]
```typescript
// This is what I want:
type A = [string, ...string[]];

const A = z.array(z.string()).min(1);
// But this is what I get
type  Z = z.infer<typeof A>; // string[]
```

**Comment by conorbrandon** [comment]
[`nonempty`](https://zod.dev/?id=nonempty) can do what you want. The docs are pretty clear regarding [`.min/.max/.length`](https://zod.dev/?id=minmaxlength).

> Unlike .nonempty() these methods do not change the inferred type.

**Comment by willruggiano** [comment]
Thanks!
