### ISSUE TITLE
Extending discriminated union types

### ISSUE THREAD

**Issue by willruggiano** [colinhacks/zod#2567]
In Typescript I can do something like this:

```typescript
type Nestable =
  | {
      has_children: false;
    }
  | {
      has_children: true;
      children: [string, ...string[]];
    };
```

and compose that with other types:

```typescript
type Prototype = {
  object: "block";
  id: string;
  created_at: Date;
  updated_at: Date;
};

export type Block = Prototype & Nestable;
```

such that I will get compile errors if I declare a block object like so:

```typescript
const b: Block = {
  object: "block",
  id: "xxx",
  ...
  has_children: false,
  children: ["yyy"] // <-- error: "children" does not exist on type
};
```

With zod, I can't achieve this in a similarly composable way. I can use discriminated unions to achieve the same type checking, but then I lose the ability to compose that type with other types.

```typescript
const Nestable = z.discriminatedUnion("has_children", [
  z.object({
    has_children: z.literal(false)
  }),
  z.object({
    has_children: z.literal(true),
    children: z.string().array()
  }),
]);

const Prototype = Nestable.extend({  // <-- error: property 'extend' does not exist on type ...
  // similar zodified schema declaration
});
```

I can do it slightly differently and make each type _in the discriminated union_ extend Prototype, but that is annoying. And still leaves me with an un-extendable "final type" (which is of type z.ZodDiscriminatedUnion<...>

I'm not requesting anything specific, unless there are features in flight that might make this easier to do, but rather looking for suggestions on how to implement such types with zod.

**Comment by elieven** [comment]
Very much needed

**Comment by conorbrandon** [comment]
I believe there's two ways to do this: `z.intersection` and the `.and` property of `z.ZodDiscriminatedUnion`? 

Unless I'm missing something 🤔  (which I very well could be, I also thought this was impossible until just now when I discovered this). It appears to work:

```ts
import { z } from 'zod'

const Nestable = z.discriminatedUnion("has_children", [
  z.object({
    has_children: z.literal(false)
  }),
  z.object({
    has_children: z.literal(true),
    children: z.string().array()
  }),
]).and(z.object({foo: z.string()}));

type N = z.infer<typeof Nestable>;

const Nestable2 = z.intersection(z.discriminatedUnion("has_children", [
  z.object({
    has_children: z.literal(false)
  }),
  z.object({
    has_children: z.literal(true),
    children: z.string().array()
  }),
]), z.object({foo: z.string()}));

type N2 = z.infer<typeof Nestable2>;

const validData = {
  has_children: false,
  foo: ""
};
console.log(Nestable.safeParse(validData));
console.log(Nestable2.safeParse(validData));

const validData2 = {
  has_children: true,
  children: [""],
  foo: ""
};
console.log(Nestable.safeParse(validData2));
console.log(Nestable2.safeParse(validData2));

const invalidData = {
    has_children: false,
    children: [""],
    foo: ""
};
console.log(Nestable.safeParse(invalidData));
console.log(Nestable2.safeParse(invalidData));

const invalidData2 = {
    has_children: true,
    foo: ""
};
console.log(Nestable.safeParse(invalidData2));
console.log(Nestable2.safeParse(invalidData2));
```

**Comment by conorbrandon** [comment]
The one caveat is this example will pass validation:

```ts
const b: Block = {
  object: "block",
  id: "xxx",
  ...
  has_children: false,
  children: ["yyy"] // <-- error: "children" does not exist on type
};
```

But I believe that's more of a function of zod's default "strip" behavior. If you want this to error, I believe adding a `.strict()` to the discriminated union member

```ts
z.object({
    has_children: z.literal(false)
  })
```
will do the trick.

**Comment by willruggiano** [comment]
Excellent! Thank you again!

**Comment by RahimGuerfi** [comment]
> I believe there's two ways to do this: `z.intersection` and the `.and` property of `z.ZodDiscriminatedUnion`?
> 
> Unless I'm missing something 🤔 (which I very well could be, I also thought this was impossible until just now when I discovered this). It appears to work:
> 
> ```ts
> import { z } from 'zod'
> 
> const Nestable = z.discriminatedUnion("has_children", [
>   z.object({
>     has_children: z.literal(false)
>   }),
>   z.object({
>     has_children: z.literal(true),
>     children: z.string().array()
>   }),
> ]).and(z.object({foo: z.string()}));
> 
> type N = z.infer<typeof Nestable>;
> 
> const Nestable2 = z.intersection(z.discriminatedUnion("has_children", [
>   z.object({
>     has_children: z.literal(false)
>   }),
>   z.object({
>     has_children: z.literal(true),
>     children: z.string().array()
>   }),
> ]), z.object({foo: z.string()}));
> 
> type N2 = z.infer<typeof Nestable2>;
> 
> const validData = {
>   has_children: false,
>   foo: ""
> };
> console.log(Nestable.safeParse(validData));
> console.log(Nestable2.safeParse(validData));
> 
> const validData2 = {
>   has_children: true,
>   children: [""],
>   foo: ""
> };
> console.log(Nestable.safeParse(validData2));
> console.log(Nestable2.safeParse(validData2));
> 
> const invalidData = {
>     has_children: false,
>     children: [""],
>     foo: ""
> };
> console.log(Nestable.safeParse(invalidData));
> console.log(Nestable2.safeParse(invalidData));
> 
> const invalidData2 = {
>     has_children: true,
>     foo: ""
> };
> console.log(Nestable.safeParse(invalidData2));
> console.log(Nestable2.safeParse(invalidData2));
> ```

Thank you very much!
