### ISSUE TITLE
Creating discriminated unions from functions

### ISSUE THREAD

**Issue by willruggiano** [colinhacks/zod#2569]
```typescript
export const Parent = (id: string, ...ids: string[]) => {
  const toObj = (i: string) =>
    z.object({
      type: z.literal(`${i}_id`),
      [`${i}_id`]: z.string()
    });
  return z.discriminatedUnion("type", [toObj(id), ...ids.map(toObj)]);
};

const P = Parent("system", "user");
type P = z.infer<typeof P>;
//   ^? { [x: string]: string; type?: `${string}_id` | undefined }

const P2 = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("system_id"),
    system_id: z.string()
  }),
  z.object({
    type: z.literal("user_id"),
    user_id: z.string()
  })
]);
type P2 = z.infer<typeof P2>;
//   ^? { type: "system_id"; system_id: string; } | { type: "user_id"; user_id: string; }
```

I am expecting the types, P and P2, to be identical

Maybe @conorbrandon will know :D

**Comment by willruggiano** [comment]
Closer, but not still not quite right:
```typescript
const system = "system";
const user = "user";
const P3 = z.discriminatedUnion("type", [
  z.object({
    type: z.literal(`${system}_id`),
    [`${system}_id`]: Id
  }),
  z.object({
    type: z.literal(`${user}_id`),
    [`${user}_id`]: Id
  })
]);
type P3 = z.infer<typeof P3>;
```

EDIT:

I _can_ do this:

```typescript
const system = "system" as const;
const user = "user" as const;
const P3 = z.discriminatedUnion("type", [
  z.object({
    type: z.literal(`${system}_id`),
    [`${system}_id`]: Id
  }),
  z.object({
    type: z.literal(`${user}_id`),
    [`${user}_id`]: Id
  })
]);
type P3 = z.infer<typeof P3>;
```

**Comment by conorbrandon** [comment]
Took that as a challenge 😆 . [Here's](https://www.typescriptlang.org/play?noErrorTruncation=true#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFA9AFS0Vy1wAiEcAnhAK5wCmANz5QswAHbFOPEQGNcYbjD6SwOMMJgc4YgIYg+AZzgAjPuIDmcAO7BifMcrgx2AAwMwoFlwH44AIQgOABo4YANGZgBtGAALMIBdAAoYmBgwAwAuampzYFjuYwA6ORBqEGAZHAMITBhqABUOdQBlSuAwOrCDbkNqAEYAZgBOABYADgBiLp6S-TEYAFpBgYG+gFYhgAYANm2ASginGL44SHEYABtDI2OL9RFNdSluAHIhEz57OAuICABrCxYaAAQjgiQA6nwLhcQnkXkYdHBzL9JNULopgBAxCFjIo4AYYjwLsQxC94KZtJ87MQDkxqBQ+AAPSCwOByMTuOB-ARwAC8cAAPABpfiMpQSIwABTUGg4Qr4wTgADUAHyJP4KjJwIVBAQ6C5apV7LVISKS0JibXxE1wSIARQtcEl1uV6HQkSF8T5KsQjDgUD4MG4UEtpo1HBdeoubp0CLEHEoaEo7M5zgA8sYAFZ8wUASVF4uIRncnjE5jVwC1ub23t9cH9geDluQhQgWb4MhgiQQfvrjz4WpbFzywn1iRcABIEMA0AB9WwuPZBXtwQpr7njqcz+fEFwhFsliyJPZLv1oPaJyj9uD1CAZzMC-NMwvFjwWH38gBKjZDjXUAv7GonDvLNHxVFUqBTeBJR0AN5hzAUoLgXMWCMZ97CLBsdGILELi0SJDzLEI10KQjzEieJ4jVEjbEyZDUJrXkfR7eskP0EBTCgIx+VowoQB0MBEnTLMa1jRA4AWANsNw-CRXELkFSAlCDBdW970fVCPSo9BKHrAMgxDFBCmIMI2nKXQlGIABVMRMTERJ8H7fAQnYziDAvCgk0grFOXNfkYLgrt8AMDh3D4EBnIIbgDGEfAPOvPyjPETBhAApo+CAyUVUobJ6zgAA9bwgA) the best I got:

```ts
import { z } from "zod";

/**
 * Do you ever find your computed property names being widened to `string`? Boy, is
 * [this](https://github.com/microsoft/TypeScript/issues/13948#issuecomment-1333159066)
 * the pointless helper type you've been looking for! (Well, it's a good solution, but shouldn't be needed)
 */
export const kv = <K extends PropertyKey, V>(key: K,val: V): { [P in K]: { [Q in P]: V } }[K] => {
  return { [key]: val } as any;
};
const toObj = <I extends string>(i: I) => {
  return z.object({
    type: z.literal(`${i}_id`),
    ...kv(`${i}_id`, z.string()),
  });
};
type ToObj<I extends string> = ReturnType<typeof toObj<I>>

const Parent = <const IDs extends readonly [string, ...string[]]>(...ids: IDs) => {
  const members = ids.map(toObj) as { -readonly [K in keyof IDs]: ToObj<IDs[K]> };
  return z.discriminatedUnion("type", members);
};

const P = Parent("system", "user");
type P = z.infer<typeof P>;
//   ^? type P = { type: "system_id"; system_id: string; } | { type: "user_id"; user_id: string; }
```

**Comment by conorbrandon** [comment]
I tried using a helper like `mapTuple`, instead of a type assertion on `members`, but unfortunately because the input array (`ids`) is heterogeneous, the return type becomes a union of all possible outputs based on the inputs. [For example](https://www.typescriptlang.org/play?noErrorTruncation=true#code/MYewdgzgLgBAtgQwA4BUCuSA2BTGBeGAHlElgEEAnCmbADymzABMIYLsEnxMBPGAbQRgeAGhgA6SUJ78AurLEBVAHwAKBFQBcMShRHAARttVRtu-mDRwD2CgpgBLZnQD82y9dsBKfMpiKvbQBvGABadk5uPn4AaUcwGABrbB4QADMdKlltRRgAX18YIIAoGDZsKDQKBI0KcUQkVUMfBFZpAG5ivM6SaHh8eGR0LGxVfgAicbEABnt1CgBzHzw-AAMAEiCNBbzVmFaYXqgvdqA):

```ts
const mapTuple = <const Arr extends readonly [any, ...any[]], U>(arr: Arr,cb: (t: Arr[number], index?: number) => U): { -readonly [K in keyof Arr]: U } => {
  return arr.map(cb) as any;
};
const m = mapTuple(["", 0], (arg) => `${arg}` as const);
```

**Comment by willruggiano** [comment]
I wonder if distributive conditional types can help in the `mapTuple` example. Will have to give it a try when I get time.

Regardless, thanks again for the help!

**Comment by conorbrandon** [comment]
No prob! I was literally just googling how to write `mapTuple` for heterogeneous tuples, seems like it's [impossible](https://stackoverflow.com/questions/66091118/mapping-tuple-typed-value-to-different-tuple-typed-value-without-casts), sadly.

**Comment by conorbrandon** [comment]
@willruggiano Also, correction, sorry! `const` type parameters aren't actually needed for `Parent`. (I've got so used to using them I forgot primitive arrays can be inferred literally without any extra help.)

```ts
const Parent = <IDs extends [string, ...string[]]>(...ids: IDs) => {
  const members = ids.map(toObj) as { [K in keyof IDs]: ToObj<IDs[K]> };
  return z.discriminatedUnion("type", members);
};
```
