### ISSUE TITLE
v2.0.0-beta.23: Non-enumerable properties are considered undefined

### ISSUE THREAD

**Issue by lantw44** [colinhacks/zod#258]
I use Zod to check the type of the error produced by [body-parser](https://github.com/expressjs/body-parser), but it fails since commit 0f47d2f13d08c9e8c04f64a86e078cd18f40652e because non-enumerable properties are ignored. Is it an intentional change, or it is considered a bug?

Zod works fine for enumerable properties.
```
> const zod = require('zod')
> let a = { message: 'x' };
> zod.object({ message: zod.string() }).parse(a)
{ message: 'x' }
```

But it fails for an Error object because `message` is non-enumerable by default.
```
> let e = new Error('x')
> zod.object({ message: zod.string() }).parse(e)
Uncaught ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "message"
    ],
    "message": "Required"
  }
]
```

If I manually set it to enumerable, it can be successfully validated.
```
> Object.defineProperty(e, 'message', { enumerable: true })
> zod.object({ message: zod.string() }).parse(e)
{ message: 'x' }
```

**Comment by sylvanaar** [comment]
This seems to imply that the own properties of `e` are compared to the type instead of the reverse.

**Comment by colinhacks** [comment]
Thanks for pointing this out! Fixed in beta 27 👍

```ts
import * as z from '.';

const e = new Error('x');
z.object({ message: z.string() }).parse(e);
// => { message: 'x' }
```

**Comment by lantw44** [comment]
It seems it is commit 19af28b014bb603bf58ad5116f8afcd6a24850d8 that fixes the problem, not the commit referenced above.

**Comment by colinhacks** [comment]
good catch I guess
