### ISSUE TITLE
Zod Preprocess returning unknown type

### ISSUE THREAD

**Issue by Royal-lobster** [colinhacks/zod#2588]
Same as https://github.com/colinhacks/zod/issues/1458, 

The type returned from [z.preprocess](https://zod.dev/?id=preprocess) is giving out type "unknown" instead of expected behavior of inferring from schema passed as second argument and throw the error on runtime if the processed value is different from schema.

```ts
const processedObject = z.preprocess(
    (v) => (typeof v === "string" ? JSON.parse(v as string) : v),
    z.array(jsonSchema),
) // typeof processedObject returning unknown
```

using zod v3.21.4

**Comment by colinhacks** [comment]
I can't replicate I'm afraid. Are you on the latest version?

<img width="495" alt="Screenshot 2023-08-05 at 6 45 24 PM" src="https://github.com/colinhacks/zod/assets/3084745/c286f8ab-862e-4883-9f8c-89933740c86b">

**Comment by Royal-lobster** [comment]
Oh revisiting it again, it works fine ! Thanks

**Comment by boringContributor** [comment]
Hey, I'm also facing this issue! :)

```typescript
export const ProxyTaskInputSchema = zod.object({
  webhook_config: zod.preprocess((input: { Item: Record<string, any> }) => unmarshall(input.Item), WebhookConfigSchema),
  event: zod.object({
    event_id: zod.string()
  })
})
```

with **WebhookConfigSchema** just being a simple  **zod.object({...})**

with that setup the **webhook_config** is always with type **unknown**

**Comment by rushil23** [comment]
+1, facing the same issue here!

**Comment by Wildhoney** [comment]
[I get it when adding the `preprocess` to a `function` type](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAKjgQwM5wF5wGZQiOAIgwgBNCBuAKCoGMIA7VeVWgCwFMRk4BeTAHQQARgCsOtGAAoA3lTgoQEAK4MYALkFgoHbRFodUqKfIVwpASj4A+OAEYANKYUYBDZSGEcolpwotOAL4W1HSMzHB6YOj8riLikrKmjADKysIgwBqC2KqSwIyWAshQAObGrJzcFlTBoTAAnmAccAAKeNF8gsAM2N4API3NENiRHajW1AD0U2YAegD8QA).

`amount` becomes `amount?: unknown` but `typeof schema` resolves it to a `number` just fine.

**Comment by enchorb** [comment]
For anyone having this issue, this discussion is still `open` https://github.com/colinhacks/zod/issues/3537
