### ISSUE TITLE
Include original class in schema for `z.instanceof()`

### ISSUE THREAD

**Issue by boywithkeyboard** [colinhacks/zod#2597]
It'd be great if the original class (e.g. `Uint8Array` for `z.instanceof(Uint8Array)`) could be included in the schema to allow for more flexibility.

**Comment by NextThread** [comment]
Hi, can I work on this

**Comment by JacobWeisenburger** [comment]
What do you mean by "include the original class"? Could you provide some pseudo code that shows how you would like to use this?

**Comment by boywithkeyboard** [comment]
@JacobWeisenburger sorry for the late response but i meant that the original class (in this example Uint8Array) should be somewhere included in the object of the schema (so if you log `z.instanceof(Uint8Array)` to console you can actually know that it should be the specified class).

This would allow other libraries to further analyze the schemas. No longer sure whether this is even needed.

As I personally don't have a use case for this any longer I'm closing this as completed, but feel free to re-open it if this should become a feature.

**Comment by ThomasAribart** [comment]
@JacobWeisenburger I'm having the need on https://www.dynamodbtoolbox.com/

I'm working on a `fromZodSchema` helper that translates zod schemas to DynamoDB-Toolbox schemas.

Binaries are a primitive of DynamoDB but there are no way to detect a zod binary schema at runtime:

```ts
import { string, binary } from 'dynamodb-toolbox'
import { z, ZodString } from 'zod'

const zodSchema = z.instanceOf(Uint8Array)

const fromZodSchema = (zodSchema) => {
  if (zodSchema instanceof ZodString) {
    return string()
  }

  ... // other types here

  if (zodSchema.instance === Uint8Array) { // <= Not possible
    return binary()
  }
}
```
