### ISSUE TITLE
Zod can not have an optional url

### ISSUE THREAD

**Issue by Hasanovic-Kahya** [colinhacks/zod#2599]
z.string().optional() is not a problem 
but z.string().url().optional() doesnt work
and z.url() doesnt exist 
i can just do it with z.string().regex()

**Comment by hudson-bruno** [comment]
I just tried and it works just fine, what exactly does not work? Just a reminder that if you want to pass null you should use `.nullable()` instead of `.optional()`

**Comment by amit548** [comment]
same problem :(

> z.string().optional() is not a problem but z.string().url().optional() doesnt work and z.url() doesnt exist i can just do it with z.string().regex()

same problem :(

**Comment by colinhacks** [comment]
I'm not sure what is being asked. This is currently working as expected.
```ts
z.string().url().optional().parse(undefined)
// => undefined
```

**Comment by JacobWeisenburger** [comment]
@Hasanovic-Kahya or @amit548 
Please send a full reproducible code example.
