### ISSUE TITLE
How to... ? Possible empty array, map'ing through it

### ISSUE THREAD

**Issue by smolak** [colinhacks/zod#2612]
Hi

Given I have this schema:
```ts
const keywordSchema = z.object({
  text: z.string(),
  url: z.string().url()
});

const post = z.object({
  // Keywords is always here, it is an array, can be empty, can have keywords in it
  // Using approach from example: https://zod.dev/?id=arrays
  keywords: keywordSchema.optional().array()
  // ... stuff
});
```

When I want to iterate over keywords:
```ts
const keywordTexts = post.keywords.map(({ text }) => text);
```

I get a TS warning about `text` being possibly `undefined`.

### Questions:

1. is this correct behavior? Given that `.map` can iterate over empty arrays, this is not a runtime problem but it is a TS one.
1. How can I achieve this scenario, in which I get all of the text values of keywords from the array of keyword objects, given that the array can be empty or full?

**Comment by conorbrandon** [comment]
I might not be understanding the problem? `keywords: keywordSchema.array()` (no `optional`) matches an array of any length, even empty ones.

I'm also assuming the variable `post` in the second code block is _not_ the same as the schema `post`. 

If that is the case, the reason it doesn't work is your schema allows `keywords` to be `({ text: string; url: string } | undefined)[]`, and you can't destructure from `undefined`.

If that is not the case, you're trying to access keywords on the _schema_ and map over the elements, which is not how zod works. You have to use the schema to parse something, and then can work with the result, as shown [here](https://zod.dev/?id=basic-usage).
