### ISSUE TITLE
string().trim() is not working. 

### ISSUE THREAD

**Issue by Jvst1n** [colinhacks/zod#2614]
As title, the whitespaces aren't trimmed after going through the zod layer.

**Comment by colinhacks** [comment]
I can't replicate. What version are you using?

**Comment by Jvst1n** [comment]
Hi colinhacks, 

Thanks for replying. I'm using zod@3.21.4. I also notice transform is not working as well while other validations are working well. 
schema.ts
`const INPUT_ITEM = object({
  name: string({
    required_error: "Name is required!",
  })
    .trim()
    .min(MIN_CHARACTER, {
      message: "Name cannot be empty!",
    })
});

const body = {
  item: INPUT_ITEM,
};

export const createItemSchema = object({
  body: object({ ...body }),
});

export type createItemInput = TypeOf<typeof createItemSchema>["body"];
`
validation.ts
`export const validateInputData =
  (schema: AnyZodObject) =>
  (req: Request, res: Response, next: NextFunction) => {
    try {
      schema.parse({
        body: req.body,
      });
      next();
    } catch (error) {
      if (error instanceof ZodError) {
        const response: ResponseBody = {
          status: "failed",
          data: null,
          error: error.errors,
        };
        return res.status(400).send(response);
      }
    }
  };
`

route.ts:
`
import {
  createItemSchema,
} from "../schemas";

this.app
      .route("/item")
      .post(validateInputData(createItemSchema), itemController.createItem);`

**Comment by colinhacks** [comment]
Still can't replicate, sorry.

```ts
import { z } from "./src";

const INPUT_ITEM = z.object({
  name: z
    .string({
      required_error: "Name is required!",
    })
    .trim()
    .min(1, {
      message: "Name cannot be empty!",
    }),
});

const body = {
  item: INPUT_ITEM,
};

export const createItemSchema = z.object({
  body: z.object({ ...body }),
});

console.log(createItemSchema.parse({ body: { item: { name: " colin " } } }));
// => { body: { item: { name: "colin" }}}
```
