### ISSUE TITLE
Zod compiles d.ts files with errors

### ISSUE THREAD

**Issue by NickPelov** [colinhacks/zod#2624]
My team recently noticed an issue that came up in the .d.ts files after zod compiled 1 of our schemas.

Original zod schema:
```ts
export const UserEventMetadataSchema = EventMetadataSchema.extend({
  userId: z.string().or(z.null()),
  journeyId: z.string(),
  locale: z.string(),
  os: z.string().optional(),
  device: z.string().optional(),
  browser: z.string().optional(),
})
```
The output in our d.ts file:
```ts
export declare const UserEventMetadataSchema: z.ZodObject<z.extendShape<{
    appVersion: z.ZodString;
    environment: z.ZodEnum<["production", "staging", "development"]>;
    clientVersion: z.ZodString;
   ....
},
```
The problem is that in the d.ts file Typescript cannot find the exported module extendShape:
![image](https://github.com/colinhacks/zod/assets/17296943/17d12ef9-486a-474e-81c3-009dea22f943)

Package versions:
```json
"dependencies": {
    "zod": "^3.21.4",
    "typescript": "^4.9.4"
  },
```

Does anyone know why the d.ts files are generated with typescript errors?

**Comment by mindler-sasu** [comment]
`extendShape` was moved to another namespace `objectUtil.extendShape`

**Comment by colinhacks** [comment]
Are you sure your `.d.ts` files are getting re-generated from your TypeScript source code? Or are these declarations handwritten? This seems to be an issue with having multiple Zod versions conflicting.

**Comment by NickPelov** [comment]
At the time we worked around the issue, but I recently noticed this issue was still open and we tried doing a clean install and re-generating our Typescript. The issue seemed to have resolved since the generated code now does not reference the z.extendShape at all. 
<img width="907" alt="image" src="https://github.com/colinhacks/zod/assets/17296943/a46d990b-4ab2-48ab-b7a2-160a7ba5da5f">
