### ISSUE TITLE
large schemas make it hard to read the type

### ISSUE THREAD

**Issue by Jared-Dahlke** [colinhacks/zod#2628]
first of all thanks for making this amazing project. it is one of my favorite libraries.

i have some really big zod objects in my project. You can see here what it looks like when i hover over a parsed object (`finalEntities`):
![image](https://github.com/colinhacks/zod/assets/32936978/54718237-dc98-4748-916f-3e96364b7c9a)

it shows the entire type definition and not the name. But if i do this with a regular ts type instead of zod, it would just show `Promise<SpaceType>` and allow me to easily navigate to that type.

sometimes i may have many large similar schemas in a union at which point it becomes almost impossible to read.

I'm trying to stay 100% inferred. so my app just uses the result of `const finalEntities = SpaceInstanceArray.parse(entities);`.
would be cool if i could hover over `finalEntities` and see the name of the schema and be able to go to the schema easily.

I tried using z.infer to get the type and then cast it as that type , like this:
```
type SpaceType = z.infer<typeof SpaceInstanceArray>;
 const finalEntities = SpaceInstanceArray.parse(
        entities
  ) as unknown as SpaceType;
```
but i still just see the entire type definition when i hover over finalEntities. Is there anyway to get around this or improve DX on this?

**Comment by scotttrinh** [comment]
I don't think there is a straightforward fix from our side on this: due to structural typing in TypeScript, TypeScript doesn't know that the return value of `parse` _should_ be called the other random name that happens to match exactly.

One thing you _can_ do is use an `interface` to name your inferred type like:

```ts
interface SpaceType extends z.output<typeof SpaceInstanceArray> {}

const finalEntities: SpaceType = SpaceInstanceArray.parse(entities);
```

Which will give it a name instead of the type literal.

**Comment by colinhacks** [comment]
As @scotttrinh there's nothing we can do here, it's a TypeScript limitation.
