### ISSUE TITLE
z.enum() cannot accept parameter from a json file

### ISSUE THREAD

**Issue by moseslucas** [colinhacks/zod#2630]
# What's the Issue

I have a json file that stores a list of slugs
```
/* dataSlugs.jsona */

{
  "slugs": ["one", "two", "three"]
}
```

Then I import this json and pass it as parameter to`z.enum`
```
import dataSlugs from './dataSlugs.json'

type DataSlugJson = {
  slugs: string[]
}

const slugs = (dataSlugs as DataSlugJson).slugs

export const mySchema = z.enum(slugs) /* this throws a type error */

```

I get the error:
<img width="896" alt="Screenshot 2023-08-04 at 7 52 38 PM" src="https://github.com/colinhacks/zod/assets/30344224/77b3898c-ad98-4e68-966e-e4286b22be3f">

I found in the docs about `z.enum`  can use `as const`

```
/* THIS WORKS */
const slugs = ["one", "two" "three"] as const
export const mySchema = z.enum(slugs)

```

```
/* BUT THIS DOESN't */
const slugs = (dataSlugs as DataSlugJson).slugs as const
 /* ERROR A 'const' assertions can only be applied to references to enum members, or string, number, boolean, array, or object literals.ts(1355) */
 
export const mySchema = z.enum(slugs)

```

How can I get a data from a json file, and pass it as parameter to `z.enum()` ?

## ZOD Version
`"zod": "^3.21.4"`

**Comment by NextThread** [comment]
hey can I work on this issue

**Comment by moseslucas** [comment]
@NextThread  yea man, thanks

**Comment by NextThread** [comment]
hi, I tried the same to do, and did some modification, now its perfectly working.

I need a lil bit help, I'm new to open source contribution.

What to do now to raise my PR?

can you please help me

**Comment by moseslucas** [comment]
@NextThread  have you created a PR already? couldn't see one by you

**Comment by NextThread** [comment]
no bro, I haven't

**Comment by NextThread** [comment]
@moseslucas there is no relevant file in the repo, so I'm confused where to change or add my codes.

**Comment by moseslucas** [comment]
@NextThread  Here's the guideline for creating a PR fix - https://github.com/colinhacks/zod/blob/1ecd6241ef97b33ce229b49f1346ffeee5d0ba74/CONTRIBUTING.md

<img width="1052" alt="Screenshot 2023-08-11 at 12 32 22 PM" src="https://github.com/colinhacks/zod/assets/30344224/f947a90f-708d-4cb4-93b5-4566546bcaf9">

**Comment by NextThread** [comment]
No, I mean this is what I did,


I have created a new json file that stores a list of slugs

Then I imported the json and pass it as parameter to z.enum()

separately I have created these two files.

Is it exactly what you are trying to do earlier?

**Comment by moseslucas** [comment]
Yes, that's exactly what I did

I have a json file that stores a list of slugs
```
/* dataSlugs.jsona */

{
  "slugs": ["one", "two", "three"]
}
```
Then I import this json and pass it as parameter to z.enum

```
import dataSlugs from './dataSlugs.json'

type DataSlugJson = {
  slugs: string[]
}

const slugs = (dataSlugs as DataSlugJson).slugs

export const mySchema = z.enum(slugs) /* this throws a type error */
```

What changes did you did @NextThread  to make this work ?

**Comment by NextThread** [comment]
added 2 lines, after -
const slugs = (dataSlugs as DataSlugJson).slugs

and before this-
export const mySchema = z.enum(slugs) /* this throws a type error */

**Comment by moseslucas** [comment]
Can I see your actual code that works @NextThread  , so I can test that if it works on me as well.

**Comment by NextThread** [comment]
sure, just 1 min, I'm on another machine, gimme 1 min

**Comment by NextThread** [comment]
![Screenshot 2023-08-11 105100](https://github.com/colinhacks/zod/assets/89125578/bb74a483-97ce-4013-b4d3-809ded46f8bd)
![Screenshot 2023-08-11 105049](https://github.com/colinhacks/zod/assets/89125578/0561064b-63e4-4cb7-a206-91a7fab2d7c0)

**Comment by NextThread** [comment]
please help me in contributing

**Comment by NextThread** [comment]
@moseslucas

**Comment by moseslucas** [comment]
I was outside driving sorry @NextThread  , I'm back now. I will try this

**Comment by moseslucas** [comment]
@NextThread  that worked, I guess this is the simplest form:
```
import z from 'zod'

import slugs from '../data/slugs.json'

export const slugsSchema = z.enum(slugs.slugs as [string])

```

## The Solution
is to use type assertion `as [string]`. The docs only mentions the usage of `as const` to define the value as tuple.
TIL about `[string, ...string[]]` - I didn't know you could spread the type `string[]` . 

## Fix
I guess this is up for the user to cast/assert the type of the value to be passed to `z.enum`. Maybe what we can do is to add this assertion `as [string]` in the z.enum section of the  Documentation.

**Comment by NextThread** [comment]
Ok thank.
 You so much, i may be need help in doing this, I will let you know, please help during this

**Comment by moseslucas** [comment]
Closing this now.
## Solution 
Is to assert your value like this

```
/* slugs.json */

{
  "slugs": ["one", "two", "three"]
}
```
```
import z from 'zod'

import slugs from '../slugs.json'

export const slugsSchema = z.enum(slugs.slugs as [string])
```

**Comment by moseslucas** [comment]
@NextThread  for sure. I'm open to help.  is there another way where we can chat? Discord maybe or email

**Comment by NextThread** [comment]
> @NextThread  for sure. I'm open to help.  is there another way where we can chat? Discord maybe or email

Sure, 

Email-   anuragr135@gmail.com 

Discord username-   anurag31oct
