### ISSUE TITLE
deepPartial does not work as expected with unions

### ISSUE THREAD

**Issue by khaled** [colinhacks/zod#265]
Consider the following: 

```typescript
const A = z.object({p1: z.string()});
const B = z.object({a: z.union([A, z.null()])});
const PB = B.deepPartial();
PB.parse({a: {}});
```

Running this yields the following error:
```
Error: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "string",
            "received": "undefined",
            "path": [
              "a",
              "p1"
            ],
            "message": "Required"
          }
        ]
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "null",
            "received": "object",
            "path": [
              "a"
            ],
            "message": "Expected null, received object"
          }
        ]
      }
    ],
    "path": [
      "a"
    ],
    "message": "Invalid input"
  }
]
    at new ZodError (/Users/kagrama/dev/cisco/dna/team-center/cli/node_modules/zod/src/ZodError.ts:134:5)
    at ZodObject.parse (/Users/kagrama/dev/cisco/dna/team-center/cli/node_modules/zod/src/parser.ts:171:17)
```

Ideally `deepPartial` would recurse through unions, taking the `deepPartial` of the union's members, where applicable.  I know that I can change `B`'s definition to:

```typescript
const B = z.object({a: z.union([A.deepPartial(), z.null()])});
```

...but this would seem to defeat the purpose of `deepPartial`.  I've got schemas nested to various levels of depth, and it seems that with `deepPartial`'s current behavior, I would have to duplicate schema definitions to achieve what I want...

**Comment by colinhacks** [comment]
From the README:

> Important limitation: deep partials only work as expected in hierarchies of object schemas. It also can't be used on recursive schemas currently, since creating a recursive schema requires casting to the generic ZodSchema type (which doesn't include all the methods of the ZodObject class).

You're right this is a limitation but it's also extremely hard to do it the "right way".

**Comment by khaled** [comment]
Thanks @colinhacks - that's unfortunate :(

Looks like `deepPartial` also does not work with records - i.e. there is no such thing as `z.record(SomeSchema).deepPartial()`...

**Comment by lukas-warrify** [comment]
Zod is a really cool validation library. However, I have to agree with @khaled. It would be nice, if `deepPartial()` works at least with arrays.
