### ISSUE TITLE
`z.preprocess` ignores `.optional()` modifier

### ISSUE THREAD

**Issue by Malkiz** [colinhacks/zod#2664]
zod version: 3.17.3

code:
```typescript
const schema = z.preprocess(data => data === '' ? undefined : data, z.number()).optional();

schema.parse(undefined) // works, returns undefined
schema.parse('') // throws
```

However, this works:
```typescript
const schema = z.preprocess(data => data === '' ? undefined : data, z.number().optional());
schema.parse(undefined) // works, returns undefined
schema.parse('') // works, returns undefined
```

I would expect the first schema to behave the same as the second schema.

**Comment by colinhacks** [comment]
This is behaving as intended, and I think it's actually important that these two behaviors can both be represented. Think of `.optional()` as wrapping the existing schema. It checks if the input is `undefined` upfront (before being parsed by the inner schema) and returns `undefined` if so. In the first example, the "optional" check happens even before the "preprocess".

**Comment by Malkiz** [comment]
It does make sense, thank you!
