### ISSUE TITLE
RFC: parse->parseSync, parseAsync->parse

### ISSUE THREAD

**Issue by colinhacks** [colinhacks/zod#267]
I think the Yup-style method naming makes more sense, where the plain `.parse` method returns a promise and `.parseSync` returns synchronously (skipping over any async refinements). Transformers complicate things; I you have an async transformer somewhere in your schema, I think `.parseSync` will just have to throw.

A sub-proposal is to rename the `safeParse` methods to simply `parse` and `parse` methods to `unsafeParse`. When I use Zod in a project, the method I end up using most commonly is `.safeParseAsync` which is pretty verbose. I strongly prefer the "safe" version of the methods, since it makes it's cleaner than a try/catch block and gives you back a statically typed `ZodError` on failure. I also use a lot of async refinements so I'm in the habit of calling the async method. Depending on how others use Zod, it may be worthwhile to switch these naming conventions. Or at least find a better name than `.safeParseAsync`.

Clearly this is a breaking change, I'm curious if others think it's worth it.

**Comment by jstewmon** [comment]
I can see why you'd develop a preference for the names based on your most common use cases. My point of view is that the existing names and the proposed names are acceptable. So, if there isn't a problem, even an ergonomic one, with the existing names, I wouldn't want to cause churn for every library consumer. After all, you're suggesting to change the behavior of the principal imperative interface of the library.

Did you have a transition plan in mind for this? Like adding an option to the existing methods to opt into the new behavior and log a deprecation warning when the default, exiting behavior is used?

**Comment by colinhacks** [comment]
Hm I agree it's probably not worth it in general. Guess it'll just be one of those quirks of the library. A better approach is to rename `safeParse -> validate` and `parse -> validateSync`. That achieves the same result without any breaking changes.
