### ISSUE TITLE
Allow number in enums

### ISSUE THREAD

**Issue by m-dressler** [colinhacks/zod#2686]
It would be helpful to allow numbered enums such as in this example

```typescript
const userMap = {
  1: { name: "John" },
  2: { name: "Bob" },
};

const ids = Object.keys(prices).map(Number) as [keyof typeof prices];
const idSchema = z.enum(ids);
```

While `"${number}"` could be used to index the userMap, if this were a network request, it would annoyingly also cause the request to format the numbers into strings. Respectively, I think there are valid use-cases where a numbered enum can be helpful.

**Comment by joshuat** [comment]
I added a workaround for this issue in #1118. I would love to see this functionality supported by zod.

**Comment by nghhoese** [comment]
Need this as well or a .exclude/.omit on the native enum. Right now im facing the problem that for Some methods i want to allow certain values of a enum. Right now im working around it using union and literals but that gives an ugly validation error

**Comment by mnahkies** [comment]
I've just bumped up against this implementing zod schema generation from openapi definitions.

Consider the openapi schema:
```
redirectStatusCode:
  type:
    - integer
    - "null"
  enum:
    - 301
    - 302
    - 307
    - 308
```

I'd ideally like to be able to output:
```
redirectStatusCode: z.enum([301, 302, 307, 308]).nullable()
```
With the resulting typescript type `301 | 302 | 307 | 308 | null`

For now I've used the `z.literal` workaround mentioned in #1118
```
redirectStatusCode: z.union([z.literal(307), z.literal(301), z.literal(302), z.literal(308)]).nullable()
```

**Comment by YaroslavFrolov** [comment]
`
export const STATUSES = {
  disabled: 0,
  active: 1,
  expired: 2,
} as const;

const status = zod.nativeEnum(STATUSES); // 0 | 1 | 2
`

**Comment by cdtut** [comment]
@colinhacks can PR be merged?

Better if it can support not only number but all primitive type like true, false, null, and undefined so can check different values in array.

**Comment by colinhacks** [comment]
Closing this per https://github.com/colinhacks/zod/pull/2980#issuecomment-2073499456

My plan for addressing this use case is to support an array values in ZodLiteral, which can then be expanded to support a variety of primitive types:

```ts
z.literal(["a", 2, 3n, false])
```

**Comment by bernaferrari** [comment]
would `z.literal(["a", "b"] == z.enum(["a", "b"]) == z.union(["a", "b"])`?

**Comment by DibyodyutiMondal** [comment]
So.. while `z.union([z.literal...]` is nice and all, I did something a bit differently while we wait for `z.literal(array)`

#### 1. Usually, I do not declare native enums, I just declare a readonly array of acceptable values. Notice that I have 2 such list of strings, and 1 list of numbers
```typescript
export const PROPERTY_STATUS = [
  'Not Started',
  'Under Construction',
  'Ready',
  'Sold',
  'Used',
  'Unused'
] as const;

export type PropertyStatus = typeof PROPERTY_STATUS[number];

export const TRANSACTION_TYPES = [
  'Lease',
  'Sale',
  'Rent',
  'Resale'
] as const;

export type TransactionType = typeof TRANSACTION_TYPES[number];

export const BHK_VALUES = [
  1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5
] as const;
export type BHK = typeof BHK_VALUES[number];

```

#### 2. So far so good. For string enumerations, using zod is so easy:
```typescript
// for status
z.enum(PROPERTY_STATUS);

// for transaction type
z.enum(TRANSACTION_TYPE)
```

#### 3. For number enumerations I use a refinement:
```typescript
z.number().superRefine(numberEnum(BHK_VALUES)),
```

#### 4. Here is the implementation of the refinement
```typescript
export function numberEnum<T extends number>(values: readonly T[]) {
  const set = new Set<unknown>(values);
  return (v: number, ctx: z.RefinementCtx): v is T => {
    if (!set.has(v)) {
      ctx.addIssue({
        code: z.ZodIssueCode.invalid_enum_value,
        received: v,
        options: [...values]
      });
    }
    return z.NEVER;
  };
}
```

**Comment by davidvalen95** [comment]
can do work around to validate as string first, then pipe to coerce to number
```
z.enum(["0","1"])
      .pipe(z.coerce.number())

```

for the context of this issues
```
const ids = Object.keys(prices).map(String) as [keyof typeof prices];
const idSchema = z.enum([ids])
      .pipe(z.coerce.number())
```

**Comment by JonathanCabezas** [comment]
> #### 3. For number enumerations I use a refinement:
> 
> ```ts
> z.number().superRefine(numberEnum(BHK_VALUES)),
> ```

The cleanest solution, exactly what I was looking for, THANKS @DibyodyutiMondal 

> can do work around to validate as string first, then pipe to coerce to number
> 
> ```js
> z.enum(["0","1"])
>       .pipe(z.coerce.number())
> ```
> 
> for the context of this issues
> 
> ```js
> const ids = Object.keys(prices).map(String) as [keyof typeof prices];
> const idSchema = z.enum([ids])
>       .pipe(z.coerce.number())
> ```

The schema inferred type is `Number` with your solution, and not an union of `Number` as expected @davidvalen95

**Comment by dsdavis4** [comment]
Is there an issue we can follow along with for implementation of z.literal with array types?

**Comment by vjau** [comment]
Is this v4 only ?

**Comment by mozmo15** [comment]
For those looking for a workaround/alternative, you can define this helper function:

```
export function getAsUnionOfLiterals<
  const T extends readonly [number, number, ...number[]],
>(
  constantNumbers: T,
): ZodUnion<
  [
    z.ZodLiteral<T[number]>,
    z.ZodLiteral<T[number]>,
    ...Array<z.ZodLiteral<T[number]>>,
  ]
> {
  const literals = constantNumbers.map((x) => z.literal(x)) as unknown as [
    z.ZodLiteral<T[number]>,
    z.ZodLiteral<T[number]>,
    ...z.ZodLiteral<T[number]>[],
  ];
  return z.union(literals);
}
```

Then call getUnionOfLiterals with your readonly number array like so:
```
const allowedNbs = [1, 2, 3] as const; 
const zodRepresentation = getAsUnionOfLiterals(allowedNbs);
```

This will define a union restricted only to the values in whatever read only array of numbers you pass it
