### ISSUE TITLE
Implementing a 'deep equality' schema

### ISSUE THREAD

**Issue by NitzanHen** [colinhacks/zod#270]
This is my first time developing an app with Zod. Sorry if I've missed something obvious!

Is it possible to create a Zod schema which checks, for an input, whether that input is an object which equals deeply to another, given object?
I've tried implementing that using literals, transformers, refinements and a combination of the three, but did not manage to find a good solution.

For exmaple, if I have `const obj = { x: 3, y: "y" }`, the schema would check for a given input `a`, if `a` is an object, which has two keys - `x` and `y`, whose values are `3` and `"y"` respectively.

Thanks!
P.S. I have a true appreciation for this library and for the solution it provides.

**Comment by colinhacks** [comment]
You should be able to do this by combining literals, tuples, and objects:

```ts
const asdf = z.object({
  x: z.literal(3),
  y: z.literal("y")
})
```

And reason why this isn't working for you?

**Comment by NitzanHen** [comment]
Well, in my case the main reason is that I've already defined these object somewhere else. Let me explain:

I'm working on an app which includes working with HMOs. Their data is static, so I've implemented it as a static record of readonly objects, something along the lines of:

```typescript
const HMOs = Object.freeze({
  hmo1: createHMO({ name: 'h1', displayName: 'hmo1', index: 0, /*...*/ } as const),  
  hmo2: createHMO({ name: 'h2', displayName: 'hmo2', index: 1, /*...*/ } as const),  
  hmo3: createHMO({ name: 'h3', displayName: 'hmo3', index: 2, /*...*/ } as const),  
  /*...*/
})
```

Where `createHMO` is a function that doesn't do much at runtime (only freezes the object), and its purpose is mainly to ensure that its argument `extends` a common 'template' interface (which I've defined using Zod, by the way). `createHMO`'s additional typing ensurence is very helpful to me, so I don't want to give it up.

Now, I'd like a way to check if a given object is an HMO (*any* HMO in the collection, not a specific one). Ideally, I could define a schema which goes something like this (`z.exact` would be the deep equality schema validator that I'm looking for, for the sake of the example):

```typescript
const HMOSchema = z.union([
  z.exact(HMOs.hmo1),
  z.exact(HMOs.hmo2),
  /*...*/
]);

interface HMO extends z.infer<typeof HMOSchema> {}
```

Which would provide me with both a runtime validator *and* a Typescript model - which is exactly what I'm using Zod for (and up until now, it has done that excellently!)

I *could* implement schemas using `z.object` and `z.literal`, however that would involve repeating myself a lot (fortunately, in my case the HMO model currently has a few simple fields, but for the sake of the discussion it may as well have many fields, including nested ones), and maintenance becomes a headache.

Another, more general point - even if I did implement this schema using Zod, I'd still need to redeclare the object, which again makes maintenance more troublesome.

For exmaple, if I define: 
```typescript
const exactSchema = z.object({
  x: z.literal(3),
  y: z.literal("y"),
  color: z.literal("#343434"),
 /* 20+ more fields, nested fields, and other troubles... */
})

type Exact = z.infer<typeof exactSchema>;

//Now, let's say I want to access the object's `color` property. unless I'm missing something, I have to declare:
const exact: Exact = {
  x: 3,
  y: "y",
  color: "#343434",
 /* 20+ more fields, nested fields, and other troubles... */
}

//Then:
console.log(exact.color);
```

A deep equality schema would allow to me to not repeat myself, such that if `exact` changes, `exactSchema` changes too.

**Comment by NitzanHen** [comment]
It is worth noting that I do not think that this feature is critical or should be in high priority; but I thought I should still report it, so that it's documented, and for the off chance that it would be simple to implement.

I don't have too much free time currently, but if it's still relevant when I do, I hope to be able to contribute.

By the way, the best workaround I came up with for the moment is to use a `z.union` of `z.any().refine(obj => obj === hmo)`, for each `hmo` object (strict equality seems to work in my case, for now at least), and define the `HMO` type myself. It seems to work at the moment, but I don't think it's a good solution by any means.

**Comment by colinhacks** [comment]
Thanks for the extra details. I understand your use case better now. I'm not interested in adding in a deep equality module into Zod, it's out of scope and is generally a hard problem 😛 

I recommend plain HMO schema and using a custom refinement coupled with something like [deep-equal](https://www.npmjs.com/package/deep-equal). 

```ts
import deepEqual from "deep-equal";
const HMOSchema = z.object({
  name: z.string(),
  ...
}).refine(val => {
  for(const hmo of HMOs){
    if(deepEqual(val, hmo)) return true;
  }
  return false;
}, { message: "This HMO isn't recognized." });
```

Doesn't give you granular error reporting but it gets the job done.

**Comment by NitzanHen** [comment]
Ok, that works well enough for now for me.

Thanks!
