### ISSUE TITLE
Please export ZodNonEmptyArray

### ISSUE THREAD

**Issue by lantw44** [colinhacks/zod#272]
The `nonempty` method of `ZodArray` returns `ZodNonEmptyArray`, but it isn't exported. Can it be exported in `src/index.ts`, so we can write `ZodNonEmptyArray<Schema>` instead of `ReturnType<zod.ZodArray<Schema>['nonempty']>` when declaring a function returning the result of `nonempty` method?

**Comment by lilred** [comment]
I just import it from `'zod/lib/cjs/types/array'`, you're saying it should be available at the top-level?

**Comment by lantw44** [comment]
> I just import it from `'zod/lib/cjs/types/array'`, you're saying it should be available at the top-level?

Yes, the API documentation only mentions `'zod'`, so I think it is unlikely that importing other paths is a supported way to use the library.

**Comment by colinhacks** [comment]
This is available for import in the most recent versions of Zod 3
