### ISSUE TITLE
object is marking all properties as optional

### ISSUE THREAD

**Issue by brielov** [colinhacks/zod#276]
I have this simple schema:

```typescript
let schema = z.object({
  email: z.string().email(),
  password: z.string()
})
```

When calling `safeParseAsync` on that schema, all keys in the `data` property are optional.

![Screen Shot 2020-12-26 at 13 12 29](https://user-images.githubusercontent.com/42145089/103155204-19d77700-477c-11eb-9467-024e1ef76a24.png)

I've tested this using both `latest` and `beta` version

**Comment by colinhacks** [comment]
This happens when you don't have `"strictNullChecks": true` in your tsconfig.json: https://github.com/colinhacks/zod#typescript-requirements
