### ISSUE TITLE
[zodv2] How do I get data of the model in refinement error message?

### ISSUE THREAD

**Issue by andreyfel** [colinhacks/zod#278]
Hi! I'm using zod v2 and stuck on one thing.
Let's say I have a schema like this:
```
const schema = z.object({
  start: z.number(),
  end: z.number(),
}).refine(
  ({ start, end }) => start <= end,
  { path: ['end'], message: `End must be greater than ${start}` }, // It won't work :(
);
```
So, I want the error message to point to the `end` field and it must contain the value of the `start` field.
It seems, there is no way to do that in zod2?
Am I missing anything?

**Comment by colinhacks** [comment]
You can do this with the `.refinement` method. It's a more powerful version of `.refine` for advanced use cases like this:

```ts
const schema = z
    .object({
      start: z.number(),
      end: z.number(),
    })
    .refinement(
      ({ start, end }) => start <= end,
      (arg) => ({
        code: ZodIssueCode.custom,
        path: ["end"],
        message: `End must be greater than ${arg.start}`,
      }) 
    );
```

**Comment by andreyfel** [comment]
Oh, great! That is what I need!
