### ISSUE TITLE
JSDoc for Zod methods

### ISSUE THREAD

**Issue by carlpaten** [colinhacks/zod#279]
Visual Studio Code uses JSDoc to populate pop-ups. It would be nice to view the docs within the editor.

@colinhacks if contributors write some docs are you interested in merging them?

**Comment by colinhacks** [comment]
Absolutely!!!

**Comment by autumnblazey** [comment]
could use [typedoc](https://typedoc.org/guides/installation/) to generate documentation and github actions to publish to github pages automatically, would be nice too!

If/when contributors decide to PR some documentation comments in, I could PR the typedoc config and the github actions to automate the publishing too
