### ISSUE TITLE
Regular Expression Denial of Service (ReDoS) [SNYK ISSUE] 

### ISSUE THREAD

**Issue by rushi-gaikwad-7** [colinhacks/zod#2836]
package is vulnerable to Regular Expression Denial of Service (ReDoS) due to using an inefficient pattern when validating emails.

**Comment by lukecarr** [comment]
Updating to [`v3.22.3`](https://github.com/colinhacks/zod/releases/tag/v3.22.3) resolves this. See PR #2824 and commit [`2ba00fe`](https://github.com/colinhacks/zod/commit/2ba00fe2377f4d53947a84b8cdb314a63bbd6dd4) for details.

**Comment by MateuszKikmunter** [comment]
This has been fixed [here](https://github.com/colinhacks/zod/pull/2824) as @lukecarr  mentioned above.

**Comment by H0llyW00dzZ** [comment]
SNYK still detect vulnerable about this package

**Comment by rushi-gaikwad-7** [comment]
I have updated to latest version(3.22.3) but still snyk detect vulnerability

**Comment by nestordabon** [comment]
Same issue still detect vulnerability scan

**Comment by colinhacks** [comment]
> I have updated to latest version(3.22.3) but still snyk detect vulnerability

It's possible you have a metadependency (a dependency of a dependency) that's still using an older version of Zod. Or snyk /`npm audit` just hasn't been updated.
