### ISSUE TITLE
Object.defineProperty(exports, "__esModule", { value: true });

### ISSUE THREAD

**Issue by Samantha-uk** [colinhacks/zod#288]
A confusing title?
I must admit I do not understand it.
I love zod, I kneel before zod!
THANK YOU for zod!!!

When I updated my packages from
`    "zod": "2.0.0-beta.29"`
to
`    "zod": "2.0.0-beta.30"`

My app started to fail, with the following in the web console.
```
exports.ZodCodeGenerator = ZodCodeGenerator;

});

Object.defineProperty(exports, "__esModule", { value: true });

var ZodDef = /*#__PURE__*/Object.freeze({
    __proto__: null
});
```

Reverting to `"zod": "2.0.0-beta.29"` made the problem go away.

**Comment by colinhacks** [comment]
At first blush...I have no idea. A lot of major changes were made to the file structure between 29 and 30. Is there an error message? What's your build system look like? Are you using a bundler?

**Comment by colinhacks** [comment]
It would also be useful to know what the Zod code is that triggers this. Does this happen on import, or only when you use certain methods/functions?
