### ISSUE TITLE
runtime-only unions?

### ISSUE THREAD

**Issue by mmkal** [colinhacks/zod#2880]
Hi there - I am wondering if there's a way to define optional or union types for the sake of backwards-compatibility that is stricter at compile time. For example:

```ts
const Input = z.object({ status: z.string().optional({ runtimeOnly: true }) })

const a: z.infer<typeof Input> = {} // compile-time error, z.infer<typeof Input> has type { status: string }
const b = Input.parse({}) // no error, `status` is optional at runtime, so it's allowed to be missing

b.status.slice() // compile-time error, the output type is `{ status: string | undefined }`
```

Similarly with union types:

```ts
const Input = z.object({ status: z.enum(['open', 'closed']).or(z.string(), { runtimeOnly: true })

const a: z.infer<typeof Input> = {.status: 'invalid' } // compile-time error, z.infer<typeof Input> has type { status: 'open' | 'closed' }
const b = Input.parse({.status: 'invalid' }) // no error, `status` is optional at runtime, so it's allowed to be missing

b.status // has type `string`
```

The idea being that you could make changes to schemas that have deployed clients who may send the old value for some amount of time - but the typescript compiler will catch any out-of-date usage to make it easier to get those clients up to date.

If this doesn't exist (I couldn't find it) - would you be open to a PR adding it?

**Comment by colinhacks** [comment]
I think letting runtime behavior & static types diverge is a bit anti-thetical, and your use case is better served by versioning your API in some more structured way (a layer on top of Zod).
