### ISSUE TITLE
z.string().email() does not validate successfully where emails have single quotes in them

### ISSUE THREAD

**Issue by Mansehej** [colinhacks/zod#2888]
`z.string().email()` fails validation when an email with a single quote (`'`) is used.

Example:
`o'leary@example.com`

This is allowed in RFFC 5332 as well.

**Comment by andybayer-grp** [comment]
Could we get a fix on this?

**Comment by coreyward** [comment]
+1 — seeing legitimate email addresses from Google Workspaces get flagged erroneously. E.g. 'brian.o'conner@toofast.example`

**Comment by Mansehej** [comment]
@colinhacks Could we please get an update on this?

**Comment by vaishu567** [comment]
Is this issue still open?
