### ISSUE TITLE
All properties is z.object are optional by default

### ISSUE THREAD

**Issue by karl-run** [colinhacks/zod#289]
The docs state the following:

> // all properties are required by default

However, in the newest version you can do the following (same as the dog example):

```
const dogSchema = z.object({
  name: z.string(),
  neutered: z.boolean(),
});

type Dog = z.infer<typeof dogSchema>;
/* 
erroneously equivalent to:
type Dog = { 
  name?: string; 
  neutered?: boolean;
}
*/

const fido: Dog = {
  name: 'Fido',
}; // This does not give any error
```

This seems to have broken in 1.2.4.

But even in version 1.2.3, you are able to do this:

```

const fido: Dog = {
  name: undefined,
  neutered: true,
}; // This does not give any error
```

Which shouldn't be possible, as the type is `string`.

**Comment by M-Zuber** [comment]
Make sure your tsconfig.json is set up properly
I just had this issue, since the `include` path in the config did not cover the files I was writing my validtors in.

**Comment by colinhacks** [comment]
Exactly. This happens when you don't have strictNullChecks enabled.

<img width="856" alt="Screen Shot 2021-01-12 at 11 24 53 AM" src="https://user-images.githubusercontent.com/3084745/104362562-cf1e6480-54c8-11eb-8293-1f37bf9b6f5f.png">

**Comment by karl-run** [comment]
Geez I was actually discussing with my colleague that "it _has_ to be something we missed in the docs". Turns out it was all the way at the top of the readme 🤦

**Comment by colinhacks** [comment]
Haha it happens! 🤙
