### ISSUE TITLE
Schema masking

### ISSUE THREAD

**Issue by colinhacks** [colinhacks/zod#29]
Spun off from #16.

See the discussion there about masking.

**Comment by vriad** [comment]
I implemented a basic version of masking but unfortunately it only works for (non-lazy) object schemas currently. A use case like the one described in #16 by @christophemarois (linearizing a recursive schema) is still not possible so I'm leaving this open.

**Comment by asktree** [comment]
I came here to request this feature, glad to see its being considered. I'm not really a fan of your `.mask` API-- to me it just seems best to give us a version of `.nonstrict()` that omits any unknown fields from the parsed output.
