### ISSUE TITLE
How to keep a TypeScript interface in sync with a Zod schema?

### ISSUE THREAD

**Issue by w1am** [colinhacks/zod#2903]
I have an existing project primarily written in TypeScript where we originally had no runtime validations for our data. As we're expanding our API and also have JavaScript users, I've decided to introduce Zod to validate our data at runtime.

**Example**
```ts
import { z } from 'zod';

interface MyData {
  name: string;
  age: number;
  isStudent?: boolean;
}

const MyDataSchema = z.object({
  name: z.string(),
  age: z.number(),
  isStudent: z.boolean().optional()
});
```

The challenge I'm facing is keeping the `MyData` interface and the `MyDataSchema` in sync. Every time I update the TypeScript interface, I have to manually update the Zod schema. This manual process is error-prone and can lead to inconsistencies.

I tried using `satisfies z.ZodType<MyTypescriptType>` (example below), but it doesn't handle optional types well.

```ts
const MyDataSchema = z.object({
  name: z.string(),
  age: z.number(),
  isStudent: z.boolean().optional()
}) satisfies z.ZodType<MyData>;
```

Is there an efficient way to enforce synchronization between a TypeScript interface and a Zod schema? Ideally, I'd like an approach where updating the interface would either automatically update the schema or at least throw an error if they're out of sync.

**Comment by jussisaurio** [comment]
`type MyData = z.infer<typeof MyDataSchema>`

**Comment by w1am** [comment]
> `type MyData = z.infer<typeof MyDataSchema>`

@jussisaurio I want to keep my typescript types

**Comment by maurer2** [comment]
Hello, I believe you can use something like this:

```ts
interface MyData {
  name: string;
  age: number;
  isStudent?: boolean;
}

const MyDataSchema = z.object({
  name: z.string(),
  age: z.number(),
  isStudent: z.boolean().optional()
}) satisfies z.ZodType<MyData>
```

You will get an TS error once the schema and types differ. It only works in strict mode and/or with strictNullChecks enabled.

**Comment by ArianHamdi** [comment]
Maybe helpful : https://github.com/fabien0102/ts-to-zod

**Comment by w1am** [comment]
> Maybe helpful : https://github.com/fabien0102/ts-to-zod

This tool has its limitations; it does not always generate accurate schemas.

**Comment by vanhanenjjv** [comment]
> Hello, I believe you can do something like this:
> 
> ```ts
> interface MyData {
>   name: string;
>   age: number;
>   isStudent?: boolean;
> }
> 
> const MyDataSchema = z.object({
>   name: z.string(),
>   age: z.number(),
>   isStudent: z.boolean().optional()
> }) satisfies z.ZodType<MyData>
> ```
> 
> You will get an TS error once the schema and types go out of sync, for example when the type is changed but not the schema and vice versa. It only works in `strict`-mode and/or with `strictNullChecks` enabled tho.

This doesn't seem to work for the case where I remove a property from the TypeScript interface. The Zod schema is still satisfied even with an additional property defined in the schema.

**Comment by Lukasz17git** [comment]
I keep my types in sync in this way: 

```typescript
// utility-types.ts file
export type ZodEntriesOf<T> = { [Key in keyof T]: z.ZodType<T[Key]> } //you can restrict it even more if you want.

////////////////////////////////////////////////////////

// schemas.ts file
interface MyData {
  name: string;
  age: number;
  isStudent?: boolean;
}

const MyDataSchema = z.object({
  name: z.string(),
  age: z.number(),
  isStudent: z.boolean().optional()
} satisfies ZodEntriesOf<MyData>)
```

This way you can ensure both types share the exact same entries and common types.

However it will not restrict/warn you from using more specific schema types in the fields from the types provided, like using a schema **without optional()** in an optional field, or providing only z.string() in a "string | number" type. If you need this kind of behavior just make "ZodEntriesOf" more strict using ternaries.
