### ISSUE TITLE
[Feature Request] Using Typescript Decorators for Object Schemas

### ISSUE THREAD

**Issue by Talha-T** [colinhacks/zod#291]
Right now, we declare object schemas like this:
```js
const dogSchema = z.object({
  name: z.string(),
  neutered: z.boolean(),
});
```
What if instead, we declared schemas with [decorators](https://www.typescriptlang.org/docs/handbook/decorators.html#property-decorators) so we didn't have to retype the associated class?
```js
class Dog {
    @zodProperty
    public name: string;
    @zodProperty
    public neutered: boolean;
    @zodProperty({ email: true })
    public email: string;
}


const myObj = { name: "blabla" } // Example request body
try {
    const myDog: Dog = getSchema(Dog.name).parse(myObj); // no need to rewrite schema, can use class multiple times
}
catch (err) {
}
```

**Comment by jeremyBanks** [comment]
I didn't realize that it was possible to use decorators and reflection to look at TypeScript types. Very cool! This looks like it might be a very powerful capability to build on top of. However, that page cautious us that they might not be stable yet:

> NOTE  Decorators are an experimental feature that may change in future releases.

> Some examples use the reflect-metadata library which adds a polyfill for an experimental metadata API. This library is not yet part of the ECMAScript (JavaScript) standard. However, once decorators are officially adopted as part of the ECMAScript standard these extensions will be proposed for adoption.

> NOTE  Decorator metadata is an experimental feature and may introduce breaking changes in future releases.

**Comment by colinhacks** [comment]
I disagree fundamentally with using classes to define object schemas. You lose all the functionality attached to ZodObject: pick, omit, extent, passthrough, etc.

**Comment by Talha-T** [comment]
I know this issue has been closed, but those functionality still can be attached to both property and object. You can pass parameters to decorators, and it is just another notation; no unusable functionalities.

**Comment by peterfotinis** [comment]
+1 on this

**Comment by jedwards1211** [comment]
Here's how I accomplish this: https://github.com/colinhacks/zod/issues/76#issuecomment-1887838005

**Comment by mcheung610** [comment]
+1 on this as well. The current zod setup is confusing and scatter. Not sure why you think having pick, omit, passthrough is a nice feature when all we want is a clear and concise way to define the validation.
