### ISSUE TITLE
Allow setting `typeName` in custom types

### ISSUE THREAD

**Issue by defrex** [colinhacks/zod#2917]
I'm using a custom type for `Decimal.js` fields like so

```ts
const decimal = z.custom<Decimal>(Decimal.isDecimal)
```

This is nice and simple, which is great! 

However, when building a UI based on an arbitrary zod-typed input, I use `_def.typeName` to determine the expected output type for the sake of formatting, etc. Currently custom fields are labeled as `ZodEffects`, which isn't particularly helpful.

Something like this would be great

```ts
const decimal = z.custom<Decimal>(Decimal.isDecimal, { typeName: 'ZodDecimal' })
```

Alternatively, a custom metadata solution as described in https://github.com/colinhacks/zod/issues/273 would also enable me to solve the problem.

**Comment by rotu** [comment]
Maybe it would be better to use a `Map` (or `WeakMap`) to keep track of this.

```js
const customTypeName = new Map()

const decimal = z.custom<Decimal>(Decimal.isDecimal)
customTypeName.set(decimal._def, "Decimal")

function getExtendedTypeName(someZodType){
  return customTypeName.get(someZodType._def) ?? someZodType._def.typeName;
}
```

**Comment by baloodevil** [comment]
I have the same need; I'm showing UI controls based on the typeName.  But when I changed a property from a ZodDate to a z.custom<Dayjs>... the typeName becomes ZodAny so I don't know to show a date picker in the UI.

**Comment by defrex** [comment]
> Maybe it would be better to use a `Map` (or `WeakMap`) to keep track of this.

It definitely feels worse to me to require an extra data structure taped to the side of Zod in order to track what type a field is, since Zod is supposed to be the source of truth for the schema.

I sortof understand the stance on custom metadata, but tracking type information feels like something Zod should support, IMO.
