### ISSUE TITLE
nativeEnum invalid_type_error not returning error on wrong enum

### ISSUE THREAD

**Issue by cjoecker** [colinhacks/zod#2919]
Zod returns `Invalid enum value` although `invalid_type_error` is set.

## Steps to reproduce

```ts
const schema = z.nativeEnum({MY_ENUM:"MY_ENUM"}, {
  invalid_type_error: "this is an error",
})

console.log("result", schema.parse("AAA"));
// returns error "Invalid enum value. Expected 'MY_ENUM', received 'AAA'"
```

## Expected behavior
When the type is wrong, Zod should return whatever I give in  `invalid_type_error`.
In the example, it should return `this is an error`

If `invalid_type_error` is meant to be used for something else, I would expect the following:
1. Add in the `nativeEnum` documentation section what is `invalid_type_error` for
2. Add with JS Docs what is `invalid_type_error` for
3. Add an `invalid_enum_error` to the `params` of `nativeEnum` where we can define a custom message.

**Comment by JacobWeisenburger** [comment]
Is this what you are looking for?

```ts
const schema = z.nativeEnum( { MY_ENUM: 'MY_ENUM' }, {
    errorMap: ( issue, ctx ) => {
        if ( issue.code === 'invalid_enum_value' ) {
            return { message: 'this is an error' }
        }
        return { message: issue.message ?? '' }
    },
} )

const result = schema.safeParse( 'AAA' )
!result.success && console.log( result.error.issues )
// [
//     {
//         received: "AAA",
//         code: "invalid_enum_value",
//         options: [ "MY_ENUM" ],
//         path: [],
//         message: "this is an error"
//     }
// ]
```

If you found my answer satisfactory, please consider supporting me. Even a small amount is greatly appreciated. Thanks friend! 🙏
https://github.com/sponsors/JacobWeisenburger

**Comment by cjoecker** [comment]
Hi @JacobWeisenburger, thanks for your answer. 
This issue is not about if it's possible to show a custom type error with `errorMap`
It is about how the `nativeEnum` helper is built since it is misleading that there is an `invalid_type_error` that is not documented and does not work as I intuitively would expect. So, I wrote in the points above what I would expect from the helper.

**Comment by JacobWeisenburger** [comment]
Thanks for your kind words. I was just trying to see if you are requesting a feature enhancement or just looking for a work around.

**Comment by jrmyio** [comment]
Also came accross this. Thought I customized all the errors until I found out `invalid_type_error` isn't actually applied in `z.nativeEnum`. This seems like a bug to me rather than an `enhancement`.

**Comment by fernandollisboa** [comment]
I can work on that! @JacobWeisenburger

**Comment by colinhacks** [comment]
You can now specify this error message with the `message` field #3169

**Comment by mv-joaopaulo** [comment]
This implementation hasn't fixed all scenarios, the message overwrites even the required error.
If the value is undefined, it should return the required error message.
If the value is defined but invalid, it should return the invalid error message.
