### ISSUE TITLE
Removing the type guards?

### ISSUE THREAD

**Issue by scotttrinh** [colinhacks/zod#293]
Saw the note about removing `check`, but if it is simply `safeParse().success`, why can we not implement it that way in the base type? I assume this has already been tried, but if there is a problem with that, it would be helpful to know what the problem is so that I don't accidentally reproduce the issue in my own usage.

**Comment by scotttrinh** [comment]
Wrote this little wrapper that seems to do the right thing:

```ts
function check<T>(schema: ZodSchema<T>, data: unknown): data is T {
  const parsed = schema.safeParse(data);
  return parsed.success;
}
```

— But still not clear why this can't be how `ZodType#check` is implemented to avoid having to import this helper when using a `ZodSchema`

**Comment by hixus** [comment]
Actually it's probably because of transformers transform types. For example:
```
const countLength = z.transformer(
  z.string(),
  z.number(),
  (myString) => myString.length
);

const originalString = "foobar"
if (countLength.check(originalString)) {
 console.log('originalString is number', typeof originalString) // would result wrong typecheck
}
```

**Comment by scotttrinh** [comment]
Ahh, that makes sense. So not only do we want to avoid the type guard in this situation, we should _always_ use the parsed data directly to avoid accidentally asserting something about a type before it has been transformed.

So to build off of your example:

```ts
const countLength = z.transformer(
  z.string(),
  z.number(),
  (myString) => myString.length
);

const originalString = "foobar";
const parsed = countLength.safeParse(originalString);
if (!parsed.success) {
  throw new Error("parsing error! oh no!");
}

parsed.data; // number
```

**Comment by scotttrinh** [comment]
@colinhacks 

Do you want me to take a swing at adding to the `v3` docs now that @hixus has helped enlighten me on this issue? I know it's a bit early to be documenting the API itself, but since this is more of a pattern, and I imagine the basic premise will hold throughout the refactor, seems like a worthwhile time to guide people toward to right usage maybe?

At any rate, the issue is definitely "resolved", so I'll close this now. Thanks again @hixus for helping me to understand!
