### ISSUE TITLE
What's the difference between AnyZodObject and SomeZodObject?

### ISSUE THREAD

**Issue by tonyxiao** [colinhacks/zod#2934]
When to use each? I can't seem to find any docs on this.

**Comment by farhan-helmy** [comment]
??????? why this suddenly got closed

**Comment by gajus** [comment]
@colinhacks Migrating between v3 and v4 and equally confused by this.

**Comment by gajus** [comment]
It looks like the equivalent in v4 is `type SomeZodObject = z.ZodObject<z.ZodRawShape>;`
