### ISSUE TITLE
safeParse method can return an ZodError object instead of success property

### ISSUE THREAD

**Issue by reiwa** [colinhacks/zod#295]
Is it possible to return an ZodError object? like this:

```
const maybeData = stringSchema.safeParse("billie")

if (maybeData instanceof ZodError) {
  // handle error then return
}

// underneath the if statement, TypeScript knows
// that validation passed
console.log(maybeData)
```

**Comment by colinhacks** [comment]
It's possible but more verbose. I don't really see a compelling reason for it.

**Comment by davidmdm** [comment]
@reiwa [myzod](https://www.npmjs.com/package/myzod) has this feature as the `try` api if this is an approach you strongly desire.
