### ISSUE TITLE
problem with z.nativeEnum with optional()

### ISSUE THREAD

**Issue by kerosan** [colinhacks/zod#296]
Hi, pls help me with validation of optional field of nativeEnum

https://codesandbox.io/s/react-hook-form-nestedvalue-forked-6gh4n?file=/src/App.tsx

related issue https://github.com/react-hook-form/react-hook-form/issues/3985

**Comment by jorisre** [comment]
👋🏻 
FYI: It's an react-hook-form issue

**Comment by colinhacks** [comment]
Looks like you figured this out on the other issue.
