### ISSUE TITLE
z.string().cuid2() validator doesn't conform to the upstream format

### ISSUE THREAD

**Issue by etareduction** [colinhacks/zod#2960]
Regex which is defined for cuid2 format validation doesn't conform to the one defined in the cuid2 library itself. 
It bothers me as i can't use this validator with ids generated by this elixir implementation of cuid2: https://github.com/joseph-lozano/cuid2

Said regex in the zod codebase:
https://github.com/colinhacks/zod/blob/master/src/types.ts#L549

Regex in the upstream cuid2 codebase:
https://github.com/paralleldrive/cuid2/blob/main/src/index.js#L105

**Comment by colinhacks** [comment]
Fair enough. Thanks!
