### ISSUE TITLE
z.string().email() fails when email contains an exclamation mark

### ISSUE THREAD

**Issue by devj3ns** [colinhacks/zod#2963]
`z.string().email()` fails with emails that contain an exclamation mark (`!`) e.g.

`a!test@googlecalender.com`

(This happened to me after upgrading from `3.21.4` to `3.22.0`.)

**Comment by santosmarco** [comment]
> Gmail allows exclamation marks in email addresses.

https://support.google.com/mail/thread/203940913?hl=en&msgid=203957798

Working as expected.

**Comment by gaberudy** [comment]
I noticed this as well, in fact I had a test that used to validate with the email:

```'test.and!#$%&*+-/=?^_`{|}~.stuff@example.com'```

that now fails.

**Comment by colinhacks** [comment]
See #2157
