### ISSUE TITLE
Problems while parsing the models when consuming prisma-generated zod models for typescript : 'You may need an additional loader to handle the result of these loaders'

### ISSUE THREAD

**Issue by GiovanniColonni** [colinhacks/zod#2965]
My issue is that I'm generating the zod models in the backend using the generator **zod-prisma** (link to the project here [here](https://github.com/CarterGrimmeisen/zod-prisma)), till here all good the types are working in the backend without problem. 
At this point I create a symbolic link between the folder in which i generate the types and from the frontend. 
Here things that to not work anymore and I'm getting this:

> ERROR in ../backend/src/db_types/listinoarticolo.ts 16:7
> Module parse failed: Unexpected token (16:7)
> File was processed with these loaders:
 > ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 > ./node_modules/source-map-loader/dist/cjs.js
 > You may need an additional loader to handle the result of these loaders. 
 
 > export interface MyModel extends z.infer<typeof AnotherModel> {
    .....
webpack compiled with 1 error `

Do you ever encounter any problem like this? I feel that the symbolic link is breaking something.
For reference:

Ract: 18.2.0
Zod: 3.22.4 (both frontend and backend) 

## UPDATE:

By copying the models folder instead of using a symbolic link solved the problem and so I start to think that is something related to CRA and the fact that is kind of outside the directory and so i created a config-override.js to solve this problem but still the problem persist with the symbolic link.

**Comment by colinhacks** [comment]
This doesn't seem to be a Zod issue
