### ISSUE TITLE
Using a (big) enum in a type predicate for `refine` causes "Expression produces a union type that is too complex to represent" error and type predicate not taken in account

### ISSUE THREAD

**Issue by andreww2012** [colinhacks/zod#2967]
Hello!

I'm using the following schema to represent something that is "likely enum" so to speak (where `Enum` is an arbitrary TypeScript numeric non-const enum):

```ts
const EnumZod = z.number().int().refine((v): v is Enum | (number & {}) => true);
```

This makes TypeScript to show a bit more useful type than just `number`:

![2023-11-15 14_45_59-zod-big-enum-error - playground ts](https://github.com/colinhacks/zod/assets/6554045/e69c5a46-07e8-47e8-9a2b-6acde9831620)

After deciding to update zod from `3.20.2` to the latest version as of time I'm writing this (`3.22.4`), `z.infer` started to remove `Enum` part of the type, but **only if this schema is used within `z.object`**:

```ts
const Schema = z.object({
  a: z.object({
    b: EnumZod,
  }),
  c: EnumZod,
});
```

![2023-11-15 14_51_49-● zod-big-enum-error - playground ts](https://github.com/colinhacks/zod/assets/6554045/660b99a3-8f4b-42f7-a00e-3c245fdedcec)

Moreover, if the enum contains more than 314 members (~related to Pi? :D~) AND the enum schema is used in a **nested** `z.object`, it's not even allowing to have such a schema:

![2023-11-15 14_55_46-● zod-big-enum-error - playground ts](https://github.com/colinhacks/zod/assets/6554045/8e24ce55-9227-4f3c-b497-fe287d89d5e4)

If I remove `a` member of `Schema`, the error will move to `z.infer`:

![2023-11-15 14_59_54-zod-big-enum-error - playground ts](https://github.com/colinhacks/zod/assets/6554045/5e36df55-2f40-4f16-89c4-2804ecb91470)

---

The exact version after which this behaviour began to be observed is `3.21.2`: https://github.com/colinhacks/zod/compare/v3.21.1...v3.21.2

**Comment by JacobWeisenburger** [comment]
perhaps you should use: https://github.com/colinhacks/zod#native-enums

**Comment by andreww2012** [comment]
@JacobWeisenburger I can't. I don't want the parsed value to be constrained only to the enum values. I want to allow all the integers, but preserve the enum in the inferred type.

**Comment by JacobWeisenburger** [comment]
seems like a code smell to me

**Comment by andreww2012** [comment]
That's what I have to deal with to parse external data being UGC (user generated content). Very rarely the values that have a well defined set of allowed values violate that constraint because users find a way to supply a bad value. 🤷‍♂️ Obviously I don't have any control of that data and thus I have to resort to things like this to at least give a hint of what type the field was intended to have.

**Comment by JacobWeisenburger** [comment]
I'm not really sure what you're trying to do because:

```ts
type foo = Enum | ( number & {} )
//         ^^^^^
// Cannot find name 'Enum'.
```

**Comment by andreww2012** [comment]
Like I said `Enum` is just an arbitrary numeric non-const enum. Any will do.

**Comment by JacobWeisenburger** [comment]
I guess I just don't understand how the type `MyEnumOrNumber` is somehow more valuable than the type `number`. They seem the same to me.

```ts
enum MyEnum { foo, bar }
type MyEnumOrNumber = MyEnum | ( number & {} )
const myEnumOrNumber: MyEnumOrNumber = MyEnum.bar
const number: number = MyEnum.bar
console.log( { myEnumOrNumber, number } ) // { myEnumOrNumber: 1, number: 1 }
```

**Comment by andreww2012** [comment]
They are technically equivalent. I'm using the described trick only to get an enum type when I hover over the variable/field having that type in the editor. I'm having to deal with dozens of such fields, so this helps me avoid mistakes & quicker discover an intended enum type. See the first screenshot in the first message - `Enum | (number & {})` is more valuable than simply `number` :)

**Comment by JacobWeisenburger** [comment]
This seems to be a bit out of scope for Zod. So realistically, I don't think this will be changed. But who knows.

**Comment by andreww2012** [comment]
This issue no longer seems to occur in `3.23.x`. 😄
