### ISSUE TITLE
BUG: Wrong email validation

### ISSUE THREAD

**Issue by valerii15298** [colinhacks/zod#2982]
There were introduced breaking changes in minor release for email validation.
Previously emails such as `som.el'user@example.com` were successfully validated using `z.string().email()`

In zod `3.21.4` such email is valid
But in zod `3.22.4` such email is invalid

Such emails should be valid, so this issue should be fixed I suppose.

**Comment by valerii15298** [comment]
Probably this commit did break this: https://github.com/colinhacks/zod/commit/2ba00fe2377f4d53947a84b8cdb314a63bbd6dd4#diff-52632a4861fc9d7dc2dacef13cd91d60286dd706c1bb57438b8ee6a579a8796a

**Comment by fernandollisboa** [comment]
I'd like to work on this, but unfortunately, I believe it's not going to happen:

https://github.com/colinhacks/zod/pull/3218#issuecomment-1945087788

**Comment by colinhacks** [comment]
Per https://github.com/colinhacks/zod/pull/2157 Zod now follows "Gmail rules" with vanilla .email() validation. That's the final word for now. For any other behavior I recommend .regex or a custom refinement.

For Zod 4 I plan to export several utility regexes, including some more forgiving email regexes. You'll be able to plug these into .email() to override the default behavior. Something like:

```ts
z.string().email(z.regex.RFC5322);
```

In the meantime here's how to customize the regex with superRefine:
```ts
const emailRegex =
  /^(?!\.)(?!.*\.\.)([A-Z0-9_'+-\.]*)[A-Z0-9_'+-]@([A-Z0-9][A-Z0-9\-]*\.)+[A-Z]{2,}$/i;

const emailSchema = z.string().superRefine((data, ctx) => {
  if (!emailRegex.test(data)) {
    ctx.addIssue({
      code: z.ZodIssueCode.invalid_string,
      message: "Invalid email address",
      validation: "email",
    });
  }
});
```
