### ISSUE TITLE
[Expo][Web][Metro] Unable to resolve "zod"

### ISSUE THREAD

**Issue by arekkubaczkowski** [colinhacks/zod#2983]
I am having an issue with compiling `zod` under expo web project using metro bundler. 
However it works on mobile within the same repository.
This is a completely new project so it utilizes the latest versions of all libraries.

The only error that I can see is this error which metro throws.
I couldn't find any other related logs so if you have idea how I can find that please guide me.

<img width="405" alt="Screenshot 2023-11-21 at 17 31 47" src="https://github.com/colinhacks/zod/assets/18654447/8d7d18cf-3310-4a4c-a1e6-dd566b229b84">

The error that I can see in browser actually doesn't say much and most likely comes from lack of properly bundled package.
<img width="944" alt="Screenshot 2023-11-21 at 17 32 53" src="https://github.com/colinhacks/zod/assets/18654447/b01a600b-c4cf-4574-96dd-6af1be1f6c1e">

tsconfig:

```{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true,
    "baseUrl": "./src",
    "paths": {
      "@/*": ["*"]
    },
    "skipLibCheck": true
  },
  "include": ["**/*.ts", "**/*.tsx", ".expo/types/**/*.ts", "expo-env.d.ts"]
}
```

babel.config.js

```
module.exports = function (api) {
  api.cache(true);

  return {
    presets: ["babel-preset-expo"],
    plugins: [
      "expo-router/babel",

      // optional, only if you ever use process.env
      "transform-inline-environment-variables",
      // NOTE: this is optional, you don't *need* the compiler
      [
        "@tamagui/babel-plugin",
        {
          components: ["tamagui"],
          config: "./tamagui.config.ts",
          logTimings: true,
          // @TODO: disable on production
          disableExtraction: true,
        },
      ],
      // NOTE: this is only necessary if you are using reanimated for animations
      "react-native-reanimated/plugin",
    ],
  };
};
```

**Comment by jmiller14** [comment]
this seems to be an issue with Expo's Metro config. I was able to solve it using the tip here: https://github.com/expo/expo/issues/23180

**Comment by arekkubaczkowski** [comment]
@jmiller14 thank you! that worked indeed!
