### ISSUE TITLE
Parse a boolean value represented by string logically

### ISSUE THREAD

**Issue by jlandowner** [colinhacks/zod#2985]
From https://github.com/colinhacks/zod/issues/1630#issuecomment-1824670600

Currently `z.boolean()` simply replesents `Boolean()` for coerce. So it handles string value as boolean along with the standard `Boolean()` specification.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean#boolean_coercion

```ts
const b = z.coerce.boolean()
b.parse("true");    // true
b.parse("false");   // true
b.parse("True");    // true
b.parse("False");   // true
b.parse("1");       // true
b.parse("0");       // true
b.parse("");        // false
b.parse(undefined); // false
b.parse("others");  // true
```

However we often need to handle string as boolean, `"false"` or `"0"` as `false`, such as parsing environment valiables.

Current workaround is like

```ts
const b1 = z.string().toLowerCase().transform(JSON.parse).pipe(z.boolean());
b1.parse("true");   // true
b1.parse("false");  // false
b1.parse("True");   // true
b1.parse("False");  // false
b1.parse("tRue");   // true
b1.parse("fAlse");  // false
b1.parse("1");      // ZodError
b1.parse("0");      // ZodError
b1.parse("others"); // ZodError
```

My suggestion is a new [string transformation](https://zod.dev/?id=strings): `z.string().boolean()`

The transforming specification in Go standard library's `strconv.ParseBool()` is good for it.

https://pkg.go.dev/strconv#ParseBool

>ParseBool returns the boolean value represented by the string. It accepts 1, t, T, TRUE, true, True, 0, f, F, FALSE, false, False. Any other value returns an error.

```ts
// Suggestions
const b1 = z.string().boolean()
b1.parse("true");    // true
b1.parse("false");   // false
b1.parse("True");    // true
b1.parse("False");   // false
b1.parse("tRue");    // ZodError in boolean transformation
b1.parse("fAlse");   // ZodError in boolean transformation
b1.parse("1");       // true
b1.parse("0");       // false
b1.parse("");        // ZodError in boolean transformation
b1.parse(undefined); // ZodError by string() as required
b1.parse("others");  // ZodError in boolean transformation

// false for undefined string
const b2 = z.string().boolean().default("false")
b2.parse(undefined); // false

// false for any boolean transformation errors and string errors
const b3 = z.string().boolean().catch(false)
b3.parse("tRue");    // false
b3.parse("fAlse");   // false
b3.parse("");        // false
b3.parse(undefined); // false
b3.parse("others");  // false
```

**Comment by jlandowner** [comment]
I read the code and found that I cannot implement the above syntax only with the change in `ZodString` but it must be changed in `ZodBoolean`.
I think it is not so different with implementing strict boolean parsing mode for coerce (syntax is different, off cource)

To be the changes only in `ZodString`, the syntax will be like

```ts
// false by default
const b2 = z.string().boolean().default("false")
b2.parse(undefined); // false
b2.parse("others");  // ZodError in boolean transformation

// false by default and for invalid string value
const b3 = z.string().boolean({ catch: false }).default("false")
b3.parse("");        // false
b3.parse("others");  // false
```

- default() arg value must be a string.
- catch() arg value also must be a string but it is not abled to parse to a boolean in catch(). So a parse error might have to be handled in the transformation.

**Comment by JacobWeisenburger** [comment]
> `const b1 = z.string().toLowerCase().transform(JSON.parse).pipe(z.boolean());`

If there is such a simple work around, then why should this be a part of zod core?

**Comment by jlandowner** [comment]
@JacobWeisenburger Thank you for your feedback.

My opinions are:
- `z.string().toLowerCase().transform(JSON.parse).pipe(z.boolean())` is not clear for users. As you can see #1630, many users are struggling to do this in different ways and sometimes mistake in their programs.
  It is worth to be on the lineup of builtin [string transformation](https://zod.dev/?id=strings) and helps many users in the future.
- It is gereral to set `"1"` or `"0"` as a boolean in environment variables for lot of tools or products but `JSON.parse()` does not works.
  I think boolean is a last piece of zod advantage in the area of environment variables parsing.

```ts
const envSchema = z.object({
  SERVER_URL: z.string().min(5, {message: "Required"}),
  SOMETHING_VALUE: z.string(),
  EXPIRE_DAYS: z.coerce.number().default(30),
  SOMETHING_NUMERIC_CONFIG: z.coerce.number().min(1),
  DEBUG: z.string().boolean(),
  ENABLE_SOMETHING: z.string().boolean(),
});
const env = envSchema.parse(Deno.env.toObject());
```

- I beleave that it is not much complex implementation. Sorry for my previous comment with lack of understaing of the zod architecutre. Now I am deepdiving zod codes.

**Comment by bhouston** [comment]
This is a really good idea.  I lost a couple hours of debugging today trying to figure out why "false" provided as a string to a ZOD parse function was resulting in "true" for a z.boolean() value.  I know it is fault of Boolean('false') being truthy, but this is a foot gun.  No one reasonable expects "false" to be parsed as Boolean true.

**Comment by bhouston** [comment]
Also I should add that this bug isn't present with Joi.  So when I converted over to Zod from Joi, this was a huge surprise.

**Comment by Soviut** [comment]
A really quick heads up, rather than invoking the entire `JSON.parse` the transform can also be just

```typescript
z.string().toLowerCase().transform((x) => x === 'true').pipe(z.boolean())
```

**Comment by jlandowner** [comment]
This issue is for a feature request and the implementation in PR #2989.

If you would like to discuss about workarounds, #1630 is a better place.

**Comment by bmunoz89** [comment]
This is what is working for me:

```javascript
z.enum(['true', 'false']).transform((value) => value === 'true')
```

**Comment by IlmariKu** [comment]
I didn't find any working solutions for my use case (query params), but I modified one [example from here](https://www.raulmelo.me/en/snippets/convert-booleanish-string-to-boolean-zod)

```
export const BooleanStringZod = z
  .string()
  .refine((value) => value === 'true')
  .transform((value) => value === 'true');
```

Now it does what I want. string "true" turns into boolean true, everything else is false.

**Comment by jlandowner** [comment]
See https://github.com/colinhacks/zod/pull/2989#issuecomment-2091965974

**Comment by vitorklock** [comment]
I'm going to leave a comment here in case anyone has the same problem as me and finds this same GitHub issue on Google.

I needed a schema that handles both boolean values and boolean strings such as `"true"` and `"false"`, turning them into a true boolean.
The solution I found was to use `z.preprocess`:
```
const schemas = {
    foo: z.preprocess((val) => {
        if (typeof val === "string") {
            if (val.toLowerCase() === "true") return true;
            if (val.toLowerCase() === "false") return false;
        }
        return val;
    }, z.boolean()),
}
```

**Comment by leandronn** [comment]
> I'm going to leave a comment here in case anyone has the same problem as me and finds this same GitHub issue on Google.
> 
> I needed a schema that handles both boolean values and boolean strings such as `"true"` and `"false"`, turning them into a true boolean. The solution I found was to use `z.preprocess`:
> 
> ```
> const schemas = {
>     foo: z.preprocess((val) => {
>         if (typeof val === "string") {
>             if (val.toLowerCase() === "true") return true;
>             if (val.toLowerCase() === "false") return false;
>         }
>         return val;
>     }, z.boolean()),
> }
> ```

Like a charm! 
Thank you.

**Comment by ThomasDupont** [comment]
Workaround works with :
true, 'true', 'True', false, 'false', 'False', 0, 1, '0', '1':

```typescript

const castStringToBool = z.preprocess((val) => {
  if (typeof val === "string") {
    if (['1', 'true'].includes(val.toLowerCase())) return true;
    if (['0', 'false'].includes(val.toLowerCase())) return false;
  }
  return val;
}, z.coerce.boolean());

```

perfect for env vars

**Comment by AlexSapoznikov** [comment]
> ```ts
> castStringToBool
> ```

The thing is you can not really re-use this if you'd like to do:
```castStringToBool.default(true)```
Or make it strict and be able to apply `nullish()`

**Comment by ilyazub** [comment]
> `export const BooleanStringZod = z.preprocess((val) => val === 'true', z.boolean()).default(false);`

Thank you @IlmariKu! This coercion finally worked for me today.

**Comment by alif-devcon** [comment]
Using the following schema, which is be better than `val === 'true'` as any invalid values will be flagged.
```
export const BooleanStringZod = z.union([
    z.literal('true').transform(() => true),
    z.literal('false').transform(() => false),
    z.boolean(),
]);
```

**Comment by ryanhs** [comment]
another alternative, that i use: 
```javascript
z.string().transform((v) => ['true', '1'].includes(v.toLowerCase())).default('false');
```

basically an enum. example use case: to parse query string to filter

**Comment by jlandowner** [comment]
Ref: https://github.com/colinhacks/zod/issues/1630#issuecomment-2937963862

**Comment by rlocatelli9** [comment]
For who are using the v3, as like me, this solution worked for me (I needed for query string):
```
...
isActive: z.preprocess(value => {
    return JSON.parse(value as string)
  }, z.boolean()).default(true),
...
```
In 'undefined' case, the default value is true.

![Image](https://github.com/user-attachments/assets/1e25afba-8345-494c-accd-de86709eafe3)

**Comment by angelod1as** [comment]
Maybe (just maybe) this issue being alive since Nov 2023 shows not planning it might not be the best solution... I have the same issue and solved with one of the workarounds. How can we bring this back to attention?

**Comment by jlandowner** [comment]
Zod 4 includes this feature as `z.stringbool()`.
See https://github.com/colinhacks/zod/issues/1630#issuecomment-2937963862

> A variant of the original suggestion has landed in Zod 4 as z.stringbool(): https://zod.dev/v4?id=stringbool
> 
> ```ts
> const strbool = z.stringbool();
> 
> strbool.parse("true")         // => true
> strbool.parse("1")            // => true
> strbool.parse("yes")          // => true
> strbool.parse("on")           // => true
> strbool.parse("y")            // => true
> strbool.parse("enabled")      // => true
> 
> strbool.parse("false");       // => false
> strbool.parse("0");           // => false
> strbool.parse("no");          // => false
> strbool.parse("off");         // => false
> strbool.parse("n");           // => false
> strbool.parse("disabled");    // => false
> 
> strbool.parse(/* anything else */); // ZodError<[{ code: "invalid_value" }]>
> ```

**Comment by Orel-A** [comment]
I didn't know `z.stringbool()` exist, so I used `z.coerce.number().pipe(z.coerce.boolean())` to avoid "0" from turning to true. Seems to work fine?
