### ISSUE TITLE
Feedback wanted: integration with the property-based testing library fast-check

### ISSUE THREAD

**Issue by DavidTimms** [colinhacks/zod#299]
Hello Colin et al.

First of all, thanks for your work on Zod. It has proved tremendously useful since I discovered it.

Over the past couple of weekends, I developed a little library to integrate Zod with the property-based testing library [fast-check](https://github.com/dubzzz/fast-check). It uses the schema information to automatically generate valid test data. It would be absolutely great to get some feedback before I finalize and release it. Would you consider using it? Do the docs make sense? etc.

https://github.com/DavidTimms/zod-fast-check

It's currently implemented against the Zod V2 beta branch, so I need to update it to work with V3 before it is ready to be released.

Thanks

**Comment by DavidTimms** [comment]
Just to let people know, I've released a new version which is compatible with Zod 3.

**Comment by colinhacks** [comment]
Just added this project to the Ecosystem section of the v3 docs. Great project! 

I'm realizing you've already implemented a complete mocking system on top of Zod. You may want to consider splitting this functionality into its own library that isn't coupled to fast-check. There's an open issue/project underway here, but I think development is slow/stalled: https://github.com/colinhacks/zod/issues/368. You already have more complete support than `zod-mocking` it appears.

Great work!
