### ISSUE TITLE
Show received value in ZodError for .nativeEnum

### ISSUE THREAD

**Issue by lilred** [colinhacks/zod#300]
I received a malformed payload today. `ZodError.message` looked as follows: "Input must be one of these values: A3, A7, ..., XB". Unfortunately I can't figure out what the offending value was, which would help me begin my investigation.

If someone modified the error formatting for `.nativeEnum` to include the value, would you accept that PR? Any doubts or caveats you'd like to see addressed?

**Comment by colinhacks** [comment]
I have this implemented locally, should be available in a Zod 3 release in the near future.

**Comment by colinhacks** [comment]
This is fixed in `zod@3.0.0-alpha.7`
