### ISSUE TITLE
Check if schema has a key

### ISSUE THREAD

**Issue by avahe-kellenberger** [colinhacks/zod#301]
**(zod v3)**

Could we add a way to check if a Zod object has a key (based on a string) at runtime?
e.g.:

```typescript
const Location = z.object({
  latitude: z.number(),
  longitude: z.number(),
});

Location.hasKey('foobar'); // false
Location.hasKey('latitude'); // true
```

... which would essentially just be:
```typescript
public hasKey(key: string): boolean {
  return this.shape[key] !== undefined
}
```

I'm not sure if something like this already exists, I've just been checking the shape.

---

To extend the question, is it possible to also do this with a `Schema`? (I'm aware `shape` doesn't exist on `Schema`, so this example doesn't work)
e.g.:

```typescript
import * as z from 'zod'

export const personSchema = z.object({
  firstName: z.string(),
  lastName: z.string(),
  email: z.string(),
  phoneNumber: z.string()
});

function hasKey(key: string, schema: z.Schema<any>): boolean {
  return schema.shape[key] !== undefined
}

console.log(hasKey('firstName', personSchema));
```

I have a use case where this would be very helpful; I'm hoping this is already possible, and I've just missed it in the documentation.

I've tried solving it by passing a Zod object into my use case via generics, but `ZodObject<T>` complains. I'm probably supposed to be using some other type?

**Comment by avahe-kellenberger** [comment]
I've solved the latter question for my use case, by utilizing the type `z.ZodObject<z.ZodRawShape>`. If there's a better way, please let me know.

**Comment by lilred** [comment]
I believe `.shape` is the intended approach here. For your question about `Schema`, it would help to understand what your use case is and why `ZodObject` doesn't solve it.

Cheers!

**Comment by avahe-kellenberger** [comment]
My previous comment actually addressed the second part of my question, I just needed to use `z.ZodObject<z.ZodRawShape>` instead of `z.Schema<any>`. Just took me a while to figure out that's what I needed.

Thanks!

**Comment by ivan-kleshnin** [comment]
`schema.shape` stopped working in latest Zod. What should we migrate to?

**Comment by lilred** [comment]
@ivan-kleshnin can you provide a repro in e.g. codesandbox?

**Comment by lilred** [comment]
@ivan-kleshnin sorry, I hadn't seen your edit. I agree with you that the change of type from `ZodObject` to `ZodEffect` is unfortunate. I don't know of a workaround except potentially grabbing the `shape` before the `refine`. Some other library users may know better; I'd recommend opening a new issue.

**Comment by ivan-kleshnin** [comment]
@colinhacks should I open a new ticket or it's a simple question you can immediately answer?

**Comment by lilred** [comment]
Opening a ticket is the superior option for two reasons:

1. People who search for the same question online are more likely to find the thread.
2. Colin may not be immediately available, but someone else might.

**Comment by ivan-kleshnin** [comment]
True, sorry. Unfortunately I have super limited time window today, like 🤯 . 
No time to properly format the issue. Will do that later if necessary.
