### ISSUE TITLE
`nonstrict` broken in zod 2 and 3?

### ISSUE THREAD

**Issue by f0rr0** [colinhacks/zod#302]
The `nonstrict` example in README does not seem to be working as expected with zod 2 or 3. TS 4.1
Specifically no index signature is added to the inferred type to allow arbitrary keys

**Comment by Shakeskeyboarde** [comment]
I'm actually having the opposite problem. The index signature _IS_ added, which makes the returned type completely useless, as all values are typed as `any`.

**Comment by colinhacks** [comment]
@f0rr0 - @Shakeskeyboarde is right - this is intentional for the reason described.
