### ISSUE TITLE
Cannot make discriminated unions with certain things / types break in weird ways

### ISSUE THREAD

**Issue by elieven** [colinhacks/zod#3052]
It seems that trying to make discriminated unions with certain things breaks some types - errors look something like this:

Argument of type: 
```
ZodDiscriminatedunion<
	"code",
	[
		ZodObject<
			{ code: ZodLiteral<"a">; a: ZodNumber }.
			"strip",
			ZodTypeAny,
			{ code: "a"; a: number },
			{ code: "a"; a: number }
		>,
		ZodObject<...>
	]
>
```

is not assignable to parameter of type `AnyZodObject`. 

Type:

```
ZodDiscriminatedunion<
	"code",
	[
		ZodObject<
			{ code: ZodLiteral<"a">; a: ZodNumber }.
			"strip",
			ZodTypeAny,
			{ code: "a"; a: number },
			{ code: "a"; a: number }
		>,
		ZodObject<...>
	]
>
```

is missing the following properties from type:

```
ZodObject<
	any,
	any,
	any,
	{ [x: string]: any },
	{ [x: string]: any }
>
```

:
- _cahced
- _getCached
-  shape
- strict
and 14 more

Here is an example [codesandbox](https://codesandbox.io/p/sandbox/angry-parm-vm86j5?file=%2Fsrc%2Findex.ts%3A23%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq4cg0lq0006356jcyzpyh6r%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq4cg0lq0002356jjc32u1u9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq4cg0lq0003356jsgnmwg3z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq4cg0lq0005356jdx873vru%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq4cg0lq0002356jjc32u1u9%2522%253A%257B%2522id%2522%253A%2522clq4cg0lq0002356jjc32u1u9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq4chsdz0002356jyyh0ydqx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A23%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A23%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clq4chsdz0002356jyyh0ydqx%2522%257D%252C%2522clq4cg0lq0005356jdx873vru%2522%253A%257B%2522id%2522%253A%2522clq4cg0lq0005356jdx873vru%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq4cg0lq0004356jbktmpqmd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clq4cg0lq0004356jbktmpqmd%2522%257D%252C%2522clq4cg0lq0003356jsgnmwg3z%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clq4cg0lq0003356jsgnmwg3z%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by nanotower** [comment]
This is happening to me as well. Any luck with this @elieven ? I can see you already closed the issue, so I suppose you solved the riddle. Could you please explain how to do that?
