### ISSUE TITLE
Staged computation

### ISSUE THREAD

**Issue by carlpaten** [colinhacks/zod#306]
Zod parsing currently is performed by a massive function `ZodParser` dispatching on the type of the current node to decide what operation to perform. This dispatch operation likely interferes with the JIT optimizer. Instead we could front-load it at schema creation time; each schema object would carry with it its own `parse` closure built compositionally.

**Comment by colinhacks** [comment]
I don't know enough to know how the current implementation impacts the JIT optimizer. Though currently each instance does contain it's own `parse` closure that closes over its own `def`. `ZodParser` is actually a function that returns a parser. Still separating out the parsing logic into individual subclasses is still preferable (for reasons you mention in #307). I already have this nearly implemented locally.

**Comment by colinhacks** [comment]
Just published `zod@3.0.0-alpha.7` which should solve this problem. Now all the parsing logic is split up between the various subclasses.
