### ISSUE TITLE
Zod continues to throw errors while using async refinements with react hook form when zod resolver mode is set to async

### ISSUE THREAD

**Issue by uehlbran** [colinhacks/zod#3066]
The title pretty much sums it up but, Zod throws errors when using async refinements via react hook form and Zod resolver even when you set mode to 'async'. This shouldn't be the case as it makes no sense. Refinements regardless of being async or not should not result in Zod throwing an error and instead should result in a validation error similar to any other function in Zod (e.g. min()). 

I don't think this is an issue with Zod (though maybe?) but, it absolutely is a failure of the docs to not cover this specific situation given that Zod is so commonly used with RHF.

EDIT: Turns out this was actually a misunderstanding on my part. I was under the assumption that validations ran in the order they were defined. (e.g. string().min().max().refine() meant that min and max would be validated and only if they passed would refine be called -- that is not the case). This combined with some logic on the backend made it seem as though the async calll was passing but in reality the promise was still getting rejected.

**Comment by JacobWeisenburger** [comment]
Please send a full reproducible code example.
