### ISSUE TITLE
Open Zod to externally-defined combinators

### ISSUE THREAD

**Issue by lilred** [colinhacks/zod#307]
To define a `ZodTypeDef` instance, one must pick a member of the enum `ZodTypes`. This is a problem for users wishing to define their own instances of `ZodType`, which requires a `ZodTypeDef` instance.

The solution is to factor the centralized aspects of Zod such that every combinator owns its error reporting, parsing logic, etc.

**Comment by lilred** [comment]
@colinhacks I'm not expecting you to implement this, but if you're open perhaps we could determine a process that would make you feel comfortable accepting PRs going in this direction.

**Comment by colinhacks** [comment]
Just released `zod@3.0.0-alpha.7` which eliminates ZodTypes. Now any subclass of ZodType that properly implements the `_parse` method is a first-class citizen.
