### ISSUE TITLE
Received error type for string array is different than expected

### ISSUE THREAD

**Issue by SufianBabri** [colinhacks/zod#308]
I'm using version **3.0.0-alpha.4** and defining my schema as:
```
const postSchema = z.object({
    message: z.string().min(10),
    tags: z.string().array().max(3),
});
```

The type suggested by VSCode for `errors.tags` is `(FieldError | undefined)[] | undefined`, however, if zod gives me `FieldError | undefined`.

**Comment by colinhacks** [comment]
Not sure what `errors` or `FieldError` are - it's not a type that exists in the Zod codebase. Are you using some other form library in conjunction with Zod?

**Comment by SufianBabri** [comment]
@colinhacks you're right. It is in react-hook-form's resolvers. :facepalm:

I really am sorry for posting it here.

Btw, thank you for this awesome library.
