### ISSUE TITLE
ZodBigInt#isOptional throws

### ISSUE THREAD

**Issue by moodysalem** [colinhacks/zod#3083]
from using zod-openapi-library
```
✘ [ERROR] TypeError: Cannot convert undefined to a BigInt
      at [object Object]
      at ZodBigInt._parse
  (file:///Users/moody/IdeaProjects/ekubo/api/node_modules/zod/lib/index.mjs:1570:26)
      at ZodBigInt._parseSync
  (file:///Users/moody/IdeaProjects/ekubo/api/node_modules/zod/lib/index.mjs:624:29)
      at ZodBigInt.safeParse
  (file:///Users/moody/IdeaProjects/ekubo/api/node_modules/zod/lib/index.mjs:654:29)
      at ZodBigInt.isOptional
  (file:///Users/moody/IdeaProjects/ekubo/api/node_modules/zod/lib/index.mjs:811:21)
      at OpenAPIGenerator.isOptionalSchema
  (file:///Users/moody/IdeaProjects/ekubo/api/node_modules/@asteasolutions/zod-to-openapi/dist/openapi-generator.js:588:26)
      at OpenAPIGenerator.generateSimpleParameter
  (file:///Users/moody/IdeaProjects/ekubo/api/node_modules/@asteasolutions/zod-to-openapi/dist/openapi-generator.js:193:32)
      at OpenAPIGenerator.generateParameter
```

**Comment by JacobWeisenburger** [comment]
Please send a full reproducible code example.

**Comment by moodysalem** [comment]
afaict you can create a zod bigint validator and call isOptional and it throws, not a complicated repro setup

**Comment by JacobWeisenburger** [comment]
then it shouldn't take you very long to do that and send it.

**Comment by moodysalem** [comment]
> then it shouldn't take you very long to do that and send it.

i'm sure it would take you less time to understand, reproduce, fix the issue and write a test case from the stack trace i already provided than _for me_ to provide a test case, it's very obviously related to this line in the code: 
https://github.com/colinhacks/zod/blob/3e4f71e857e75da722bd7e735b6d657a70682df2/src/types.ts#L1389
and it's called from isOptional with undefined. it would also throw from isNull afaict
https://github.com/colinhacks/zod/blob/3e4f71e857e75da722bd7e735b6d657a70682df2/src/types.ts#L500-L505

is that enough information?

**Comment by JacobWeisenburger** [comment]
> is that enough information?

Unfortunately it is not. Everyone else's time is just as valuable as yours. So you can produce a code sample that shows the bug you are trying to report, or this issue will be closed. Thanks for your understanding.
