### ISSUE TITLE
Empty error message gets evaluated as falsy and overriden

### ISSUE THREAD

**Issue by janglad** [colinhacks/zod#3101]
Doing this

```ts
import z from 'zod';

z.number().min(0, { message: '' }).parse(-1);
```
Results in an error of 
```
Error: [
{
"code": "too_small",
"minimum": 0,
"type": "number",
"inclusive": true,
"exact": false,
"message": "Number must be greater than or equal to 0",
"path": []
}
]
```
instead of having an empty message.

Would it be possible to explicitly check if the message is undefined rather than checking if it's falsy? After asking this on the Discord scotttrinh found the line causing this

https://github.com/colinhacks/zod/blob/3e4f71e857e75da722bd7e735b6d657a70682df2/src/helpers/parseUtil.ts#L31

**Comment by fernandollisboa** [comment]
I think I can manage that
