### ISSUE TITLE
add method to find if the given field is required

### ISSUE THREAD

**Issue by sajjathossain** [colinhacks/zod#3103]
I recently ran into a scenario where I need to know if the given field is required or not. but I was unable to find any solution for it. something like this would be nice. e.g.:
```ts
ZodSchema.isRequired("fieldName")
```

**Comment by JacobWeisenburger** [comment]
Is this what you are looking for?

```ts
const isFooRequired = !z.object( { foo: z.string() } ).shape.foo.isOptional()
```

If you found my answer satisfactory, please consider supporting me. Even a small amount is greatly appreciated. Thanks friend! 🙏
https://github.com/sponsors/JacobWeisenburger

**Comment by JacobWeisenburger** [comment]
Are you looking for a workaround or a new feature?

**Comment by sajjathossain** [comment]
> Are you looking for a workaround or a new feature?

a feature

**Comment by anugoyal998** [comment]
Can I start working on it? Please assign it to me

**Comment by anugoyal998** [comment]
Can I work on this feature?

**Comment by fernandollisboa** [comment]
I can work on that!

**Comment by colinhacks** [comment]
Sorry, this feature is too niche to merit inclusion in core, especially with `isOptional()` already existing. Closing 🤙
