### ISSUE TITLE
Update v2/beta instructions in readme

### ISSUE THREAD

**Issue by mmkal** [colinhacks/zod#312]
Hi, love the library!

In the readme found at https://github.com/colinhacks/zod and https://npmjs.com/package/zod (places I'd usually expect to find "blessed"/up-to-date docs), it says "Zod 2 is recommended for all new projects". On clicking through to the v2 branch, this seems to be very much not the case. The write up of why is very helpful, but it might be a good idea to update the v1 readme saying _v3_ is recommended for all new projects (with a brief explainer and/or link to issue on why v1 -> v3).

Or, if v1 is still the recommendation until v3 comes out of alpha/typescript 4.1 is more widely adopted, remove the message entirely?

**Comment by will-h4** [comment]
:+1: Would also like to know if v2 is still the recommended starting point for new projects. How alpha is alpha? :D

**Comment by laktak** [comment]
Also, on the V3 page: 

> Installation
> To use the beta of Zod 2 (recommended for new projects).
> npm install zod@beta

**Comment by colinhacks** [comment]
Thanks, all these documentation problems are fixed. 

I just published a new v3 alpha (`zod@3.0.0-alpha.7`) which represents a big rewrite and a lot of new features. I'm going to wait a few days to make sure there aren't any major issues, then I'll bump v3 to beta. Early next week hopefully. @laktak @will-h4 @mmkal
