### ISSUE TITLE
Avoid upper level index import to avoid require cycle

### ISSUE THREAD

**Issue by GlCap** [colinhacks/zod#315]
Hello, thanks for the amazing library.
I'm currently using the latest version of zod (3.0.0.-alpha-4) with react-native and I noticed a weird require cycle through my whole application:

> WARN     Require cycle: index.js -> src/Root.tsx -> src/routes/Router.tsx -> src/routes/stacks/Authentication.tsx -> src/screens/Authentication/index.ts -> src/screens/Authentication/SignInMail.tsx -> src/screens/Authentication/components/SignInForm.tsx -> node_modules/zod/lib/cjs/index.js -> node_modules/zod/lib/cjs/types/object.js -> node_modules/zod/lib/cjs/helpers/objectUtil.js -> index.js

I did some digging and I found this kind of import:

https://github.com/colinhacks/zod/blob/bb93ec5448d4b06ef3a458160e697babb2059980/src/helpers/objectUtil.ts#L3

I think it is somehow miss referencing this to my app package.json main script.
I tried renaming my entry point to something else but it still gave the warning.

thanks for your attention

**Comment by colinhacks** [comment]
I'll look into this, thanks for pointing it out.

**Comment by colinhacks** [comment]
@GlCap the newest v3 alpha (`zod@3.0.0-alpha.7`) has eliminated all cyclical imports which caused this issue (and many others). Can you upgrade (`npm install zod@next`) and let me know if your issue is resolved?

**Comment by prescience-data** [comment]
I found running a `madge` check on a pre-publish hook is a great way to catch these early! 
https://github.com/pahen/madge 

🧠

**Comment by colinhacks** [comment]
I love madge! That's a good tip. Now I'm just extremely paranoid about ESM modules not working after a bunch of mysterious issues last time. I'm 95% sure the cyclical imports were the root cause but I'm still not sure. Bundler compatibility issues are the bane of my existence.
