### ISSUE TITLE
feature request: zod.fallback() and zod.catch()

### ISSUE THREAD

**Issue by ehahn9** [colinhacks/zod#316]
zod is awesome!

Maybe this is already possible, but often I need more granular control of `safeParse`-like behavior... Something like:

```
const color = string().fallback('#000000');
const person = object({ name: string(), age: number() }).fallback({});
```

Or, maybe with more granular control (e.g. have the fallback be based on a `ZodError`):

```
const person = object( {name: string(), age: number() }.catch(err =>  { console.error(err.message); return {} );
```

(so `.fallback(foo)` is just `.catch(() => foo)`).

Thanks for listening/considering!

ps: some of this might be doable with `any().transform(val => xxx).string()` but seems super hacky and non zod-like since
you basically have to use JS/TS to coerce the value...

**Comment by ehahn9** [comment]
BTW, here's a better workaround I've come up with

```
export function fallback<T, U>(schema: Schema<T>, value: U): Schema<T | U> {
  return any().transform(val => {
    const safe = schema.safeParse(val);
    return safe.success ? safe.data : value;
  });
}
```

So, from original example:

```
const color = fallback(zod.string(), '#000000');
```

**Comment by ehahn9** [comment]
In case anyone is going down this path, the type signature for fallback() should really be:

```
export function fallback<T extends Schema<any>, U>(schema: T, value: U): T | Schema<U> {
```

This better preserves the fidelity of the original schema.

**Comment by colinhacks** [comment]
Yep your new version of `fallback` is better, since the subclass of the input is inferred (instead of everything getting cast to `z.Schema`, which is the abstract parent class that all Zod classes extend from). Here's an even better version:

```ts
export function fallback<T extends z.Schema<any>>(
  schema: T,
  value: T["_output"]
) {
  return z.any().transform((val) => {
    const safe = schema.safeParse(val);
    return safe.success ? safe.data : value;
  });
}
```

Since your fallback value should (presumably) conform to your schema...no need to infer its type separately.

This approach seems to largely resolve your issue. I have mixed feelings about putting this into core, mostly because I think few people would actually need/use it. I'll leave the issue open for a while to see if others chime in.

**Comment by ehahn9** [comment]
Awesome @colinhacks. Totally agree about keeping out of core...  Feel free to close this whenever you like!

Just to clarify my OP, the fallback value isn't _always_ compatible with `Schema<T>`. I've found this idiom most useful when I want to read an array of values (e.g. firestore records) but be tolerant of bad values:

```
// get some things, ignoring the invalid entries:
const things = zod.array(fallback(thingSchema, false))
const goodThings = compact(things)
```

**Comment by ehahn9** [comment]
In case anyone comes across this in the future, here's an even better (IMHO) approach which does not involve `safeParse` etc.:

```ts
import { any } from 'zod';

/**
 * Create a schema matches anything and returns a value. Use it with `or`:
 *
 * const schema = zod.number();
 * const tolerant = schema.or(fallback(-1));
 *
 * schema.parse('foo')      // => ZodError
 * tolerant.parse('foo')    // -1
 */
export function fallback<T>(value: T) {
  return any().transform(() => value);
}
```

**Comment by daniel-hampton** [comment]
> In case anyone comes across this in the future, here's an even better (IMHO) approach which does not involve `safeParse` etc.:
> 
> ```ts
> import { any } from 'zod';
> 
> /**
>  * Create a schema matches anything and returns a value. Use it with `or`:
>  *
>  * const schema = zod.number();
>  * const tolerant = schema.or(fallback(-1));
>  *
>  * schema.parse('foo')      // => ZodError
>  * tolerant.parse('foo')    // -1
>  */
> export function fallback<T>(value: T) {
>   return any().transform(() => value);
> }
> ```
Thanks for posting this approach. I had been looking for a way to provide a fallback value for some non-critical properties we read from Firestore. I didn't want to reject a whole document if something like an optional description was invalid.

**Comment by MaximSagan** [comment]
I think the problem with the approach mentioned is the lack of reporting. The error is swallowed so we are never really aware if there was a problem with our data. Even if we run a comparison of the input and the output afterwards (and even if somehow we could rule out differences being due to preprocess/transform), we still don't know _why_ the fallback was performed (which is the information a `ZodError` could give us).

I think the inbuilt `.fallback()` method may indeed be useful, in conjunction with a slight addition to the `SafeParseSuccess` type.

e.g.
```ts
export declare type SafeParseSuccess<Output> = {
    success: true;
    data: Output;
    fallbacksUsed: ZodError[]; // <-- Or perhaps a single ZodError instance, not sure.
};
```

used like this

```ts
const mySchema = z.object({
    a: z.string().fallback('fallbackString'),
    b: z.number().fallback(42)
    c: z.object({
        d: z.boolean().fallback(false)
        e: z.number().fallback(1337)
    })
})

const result =  mySchema.safeParse({
    a: 123,
    b: 345,
    c: {
        d: true,
        e: 'hello'
    }
});

console.log(result.success); // true
console.log(result.data);
// {
//     a: 'fallbackString', // <-- fallback used
//     b: 345,
//     c: {
//         d: true,
//         e: 1337 // <-- fallback used
//     }
// }
console.log(result.fallbacksUsed);
// Errors indicating that fallbacks occurred at paths "a" and "c.e"
```

**Comment by ThusSpokeNomad** [comment]
> In case anyone comes across this in the future, here's an even better (IMHO) approach which does not involve `safeParse` etc.:
> 
> ```ts
> import { any } from 'zod';
> 
> /**
>  * Create a schema matches anything and returns a value. Use it with `or`:
>  *
>  * const schema = zod.number();
>  * const tolerant = schema.or(fallback(-1));
>  *
>  * schema.parse('foo')      // => ZodError
>  * tolerant.parse('foo')    // -1
>  */
> export function fallback<T>(value: T) {
>   return any().transform(() => value);
> }
> ```

FWIW, here'a minor improvement I made to keep return type explicit rather than any:

```typescript
export function fallback<T>(value: T): ZodType<T> {
    return z.any().transform(() => value);
}
```

so that you could simply do:

```typescript
z.object({
    DB_HOST: z.string().or(fallback("store.local")),
    ...
}
```

and the final `DB_HOST` object would still be inferred as a `string` in this case.

**Comment by OoDeLally** [comment]
Building on @ThusSpokeNomad 's solution, here are some helpers to do simply the following:
- Pass a map of fallback values in an validated object
- Run handlers when fallback values are used, either per field (2nd function) or once per object (3nd function). I use it to report a Sentry error.

```ts
import { Dictionary, mapValues, ObjectIterator, size } from 'lodash';
import { z } from 'zod';

type FallbackHandler<T> = (foundValue: T, fallbackValue: T) => void;

export const fallbackValueZod = <T>(
  fallbackValue: T,
  onFallbackUsed?: FallbackHandler<T>,
): z.ZodType<T> =>
  z.any().transform((foundValue) => {
    onFallbackUsed?.(foundValue, fallbackValue);
    return fallbackValue;
  });

type ZodDictionary = Dictionary<z.ZodTypeAny>;

type ZodObjectWithFallbackValues<T extends ZodDictionary> = z.ZodObject<{
  [P in keyof T]: z.ZodType<z.infer<T[P]>>;
}>;

type FieldFallbackHandler<T, K extends keyof T> = (
  foundValue: T[K],
  fallbackValue: T[K],
  fieldName: K,
) => void;

/**
 * Zod object schema with fallback values.
 * handler() is called for every field fallbacked.
 * e.g.
 *  const mySafeObjectZod = zodObjectWithFallbackValues(myObjectZod, fallbackValues, (foundValue, fallbackValue, fieldName) =>
 *    console.warn(`${fieldName}: Invalid value '${foundValue}'. Fallbacked to ${fallbackValue}`),
 *  );
 */
export const zodObjectWithFallbackValues = <T extends ZodDictionary>(
  zodObject: z.ZodObject<T>,
  fallbackValues: { [P in keyof T]?: z.infer<T[P]> },
  handler?: FieldFallbackHandler<T, keyof T>,
): ZodObjectWithFallbackValues<T> => {
  const iteratee: ObjectIterator<T, z.ZodType<unknown>> = <P extends keyof T>(
    fieldZod: T[P],
    fieldName: P,
  ): z.ZodType<z.infer<T[P]>> => {
    if (!(fieldName in fallbackValues)) {
      return fieldZod;
    }
    return fieldZod.or(
      fallbackValueZod<T[P]>(fallbackValues[fieldName]!, (foundValue, fallbackValue) => {
        handler?.(foundValue, fallbackValue, fieldName);
      }),
    );
  };
  const zodFields = mapValues<T, z.ZodType<unknown>>(zodObject.shape, iteratee);
  return z.object(zodFields);
};

type FallbackValues<T extends ZodDictionary> = { [P in keyof T]?: z.infer<T[P]> };
type AggregatedFallbacksHandler<T extends ZodDictionary> = (usedFallbackValues: {
  [P in keyof T]?: { found: z.infer<T[P]>; fallback: z.infer<T[P]> };
}) => void;

/**
 * Zod object schema with fallback values.
 * handler() is called once if one or multiple fields were fallbacked.
 * e.g.
 *   const mySafeObjectZod = zodObjectWithAggregatedFallbackValues(
 *     zodObject,
 *     fallbackValues,
 *     (usedFallbackValues) =>
 *       console.warn(
 *         `Some fallback values were used: ${map(
 *           usedFallbackValues,
 *           ({ found, fallback }, fieldName) =>
 *             `${fieldName}: Invalid value '${found}'. Fallbacked to ${fallback}`,
 *         ).join('\n')}`,
 *       ),
 *   );
 */

export const zodObjectWithAggregatedFallbackValues = <T extends ZodDictionary>(
  zodObject: z.ZodObject<T>,
  fallbackValues: FallbackValues<T>,
  handler?: AggregatedFallbacksHandler<T>,
): ZodObjectWithFallbackValues<T> => {
  const parseAndAggregateErrors = (value: unknown): z.infer<z.ZodObject<T>> => {
    const usedFallbackValues: FallbackValues<T> = {};
    try {
      return zodObjectWithFallbackValues(
        zodObject,
        fallbackValues,
        (foundValue, fallbackValue, fieldName) => {
          usedFallbackValues[fieldName] = { found: foundValue, fallback: fallbackValue };
        },
      ).parse(value);
    } finally {
      if (size(usedFallbackValues) > 0) {
        handler?.(usedFallbackValues);
      }
    }
  };
  // Zod typing is simply too complicated to get it right, so we force it a little bit.
  return z.any().transform(parseAndAggregateErrors) as unknown as ZodObjectWithFallbackValues<T>;
};
```
