### ISSUE TITLE
z.ObjectID() ?

### ISSUE THREAD

**Issue by alexnix** [colinhacks/zod#318]
I am trying to integrate zod with Mongoose but I have an issue.

One of the fields is ObjectID... how should I define this in the schema? I tried z.string() but I does not work (even if I add the ObjectID as a string on my object before saving it, I guess Mongoose internally converts it back to ObjectID before calling the pre-validate hook so in the end I am getting an ObjectID again).

Any workaround? Maybe something like https://github.com/jquense/yup/issues/467

**Comment by davidmdm** [comment]
What exactly is your use case? Is it mapping user input to a mongo objectID? The way [myzod](https://www.npmjs.com/package/myzod) does this is via the map method.

```typescript
const objectIdSchema = z.string().map(value => new ObjectId(value))
```

Maybe zod might consider doing something like this? Otherwise you can try myzod which is similar to zod.

**Comment by alexnix** [comment]
Yeah, kind of that use case...
I found a workaround to use:

```z.union([z.any(), userSchema])```

with userSchema being the schema of the collection the field would point to.
Mongoose will do verify that the input is indeed a correct ObjectID so I am covered from the validation point of view.

I guess the only thing I could ask for now would be for a way to make it infer the type of the field to ```string | z.infer<typeof userSchema>``` (string cause when the object is sent from the the API as JSON, ObjectID becomes a string, and <typeof userSchema> because I might call populate on the field before returning the object).

**Comment by colinhacks** [comment]
Hi @alexnix. Sounds like `ObjectId` is a class? In that case you should use `z.instanceof`:

```ts
const User = z.object({
  id: z.instanceof(ObjectId)
})
```

This simply checks that the value passed into the `id` property is an intance of the ObjectID class. Docs are at https://github.com/colinhacks/zod#instanceof

**Comment by learndeviomartin** [comment]
> Hi @alexnix. Sounds like `ObjectId` is a class? In that case you should use `z.instanceof`:
> 
> ```ts
> const User = z.object({
>   id: z.instanceof(ObjectId)
> })
> ```
> 
> This simply checks that the value passed into the `id` property is an intance of the ObjectID class. Docs are at https://github.com/colinhacks/zod#instanceof

This works as long as you do the check on the server. I had the same problem with my next.js app when I tried to access the schema in my components.

It was an easy fix tho.

const User = z.object({
  id: z.instanceof(Object).transform((id) => id.toString()),
})

**Comment by adelowo** [comment]
> Hi @alexnix. Sounds like `ObjectId` is a class? In that case you should use `z.instanceof`:
> 
> ```ts
> const User = z.object({
>   id: z.instanceof(ObjectId)
> })
> ```
> 
> This simply checks that the value passed into the `id` property is an intance of the ObjectID class. Docs are at https://github.com/colinhacks/zod#instanceof

This doesn't work if It is coming from a HTTP request. are there ways to do that?

**Comment by andrinheusser** [comment]
> This doesn't work if It is coming from a HTTP request. are there ways to do that?

You should be able to use [preprocess](https://zod.dev/?id=preprocess)

**Comment by bbar** [comment]
Will this work?

```
import type { ObjectId } from 'bson';

const _id = z.custom<ObjectId>();
```

**Comment by catnug** [comment]
Hi,  when i try to guess your implementation, i think you probably want to achieve this 😎.

```typescript
import z from 'zod'
import mongoose from 'mongoose'

const paramsSchema = z.object({
  id: z.string().refine((val) => {
    return mongoose.Types.ObjectId.isValid(val)
  }),
})

//-------
paramsSchema.parse(req.params.id)  //pass the validation
```

**Comment by w3llcod3** [comment]
While the solution of [catnug](https://github.com/catnug) works, I have found that the solution of [bbar](https://github.com/bbar) works better. So here's it refactored:
```
    import mongoose from 'mongoose'

    const schema = z
      .object({
        _id: z.custom<mongoose.Types.ObjectId>(),
      })
```

The above solutions using `instanceof` does not really work if data is coming from an HTTP request.

**Comment by orimdominic** [comment]
In my case (data is coming from an HTTP request,) I used
```js
const mongoIdSchema = z.string().regex(/^[0-9a-f]{24}$/);
```
from [joi-objectid](https://github.com/mkg20001/joi-objectid/blob/8411c1199b1a4807a1a9aa570a9b5a86dae6ce20/index.js#L12)

**Comment by iarlen-reis** [comment]
I don't know if it was the best way, but for https requests, the simplest way I found was like this:

```typescript
// create a schema with zod:

export const getSignSchema = z.object({
  id: z.string(),
})

// using schema:

const { id } = getSignSchema.parse(request.params)

const sign = await Sign.findById(new ObjectId(id))
```

**Comment by reslear** [comment]
or simple ready solution using https://github.com/validatorjs/validator.js

```ts
import isMongoId from 'validator/es/lib/isMongoId'

const schema = z.object({
  id: z.string().refine(isMongoId),
})
```

**Comment by thanhtutzaw** [comment]
Why I can't use ObjectId for _id in zod shared types. It is using Turbo Repo to use in backend and frontend.

**Comment by bhrvarsani22** [comment]
> Hi, when i try to guess your implementation, i think you probably want to achieve this 😎.
> 
> ```ts
> import z from 'zod'
> import mongoose from 'mongoose'
> 
> const paramsSchema = z.object({
>   id: z.string().refine((val) => {
>     return mongoose.Types.ObjectId.isValid(val)
>   }),
> })
> 
> //-------
> paramsSchema.parse(req.params.id)  //pass the validation
> ```

This one working perfact..

**Comment by laneme** [comment]
> Update: but be careful sometimes it breaks the scheme ...

What you mean?

**Comment by DevNickJr** [comment]
```
    import mongoose from 'mongoose'

    const schema = z
      .object({
        _id: z.custom<mongoose.Types.ObjectId>().refine((val) => Types.ObjectId.isValid(val)),
      })

```

This is the solution I came up with. It works well especially for http requests when the value comes as a strin.
So the first part (custom) gives you the correcting typing you need for typescript and the second part (refine) casts and validates it to make sure its a valid ObjectId

**Comment by reslear** [comment]
> What you mean?

not good for collect all errors, `refine` display only error for this fields

**Comment by mattbodman** [comment]
> Hi, when i try to guess your implementation, i think you probably want to achieve this 😎.
> 
> ```ts
> import z from 'zod'
> import mongoose from 'mongoose'
> 
> const paramsSchema = z.object({
>   id: z.string().refine((val) => {
>     return mongoose.Types.ObjectId.isValid(val)
>   }),
> })
> 
> //-------
> paramsSchema.parse(req.params.id)  //pass the validation
> ```

this works for MongoDB ObjectId, too:

import { ObjectId } from "@mongodb";

...
return ObjectId.isValid(val);

**Comment by BCAPATHSHALA** [comment]
**How to make sure contentId is a valid ObjectId of Mongoose**

`import mongoose from "mongoose";
import { z } from "zod";

export const deleteContentSchema = z.object({
  contentId: z.string().refine((val) => mongoose.Types.ObjectId.isValid(val), {
    message: "Invalid contentId",
  }),
});`

**Comment by patilanz** [comment]
What about monorepo with common zed schemas betwen back and front?

I'm using 

`export const objectIdSchema = z.string().refine((val) => ObjectId.isValid(val)).transform((val) => new ObjectId(val));`

but import { ObjectId } from "mongodb"; breaks frontend as it requieres node types.

Any ideas?

**Comment by y-nk** [comment]
@patilanz [scroll up](https://github.com/colinhacks/zod/issues/318#issuecomment-1597660877)

**Comment by HelmerBarcos** [comment]
This worked for me:

Option A:  You receive a string (from JSON / request payload)  and you want to validate + transform it into a MongoDB ObjectId.
``` javascript
import { ObjectId } from "mongodb";
import { z } from "zod";


export const ResDtoSchema = z.object({
  _id: z
    .string()
    .refine((val) => ObjectId.isValid(val), { message: "Invalid ObjectId" })
    .transform((val) => new ObjectId(val)),
});
```

 Option B: You already have a MongoDB ObjectId (from a document), and you want to convert it into a string (hex) for your DTO response.

```javascript
import { ObjectId } from "mongodb";
import { z } from "zod";

export const ResDtoSchema = z.object({
  _id: z
    .instanceof(ObjectId)
    .transform((id) => id.toHexString()),
});
```

Option C: You use need  string validation then just use the Option A without the transformation.

**Comment by reslear** [comment]
hi @colinhacks 
So can we add as a standard in v4 
ObjectId in fact it is popular almost like uuid
instead of creating our own project by project.
let people use it and enjoy it.

**Comment by dandean** [comment]
Building on top of what @HelmerBarcos wrote, this will accept either `string` or `ObjectId` as input, but parse the field into `ObjectId`:

```ts
_id: z
    .union([z.instanceof(ObjectId), z.string()])
    .refine((val) => ObjectId.isValid(val), {message: 'Invalid ObjectId'})
    .transform((val) => new ObjectId(val))
```

The input type is:

`_id: string | ObjectId`

The output type is:

`_id: ObjectId`

**Comment by dbwodlf3** [comment]
use it like https://github.com/colinhacks/zod/issues/318#issuecomment-1517206696
its good.

more detail like this.

```ts
import { z } from "zod";
import type { ObjectId } from "bson";

export const ObjectIdCompatible = z.union([
  z.string().regex(/^[a-fA-F0-9]{24}$/),
  z.custom<ObjectId>()
]);
```

and customize more if you need.

in my case, i just need compile time checking compatibility between browser client and server side.

**Comment by Sbrjt** [comment]
I did it like [HelmerBarcos](https://github.com/colinhacks/zod/issues/318#issuecomment-3236942429)

```js
import { Types } from 'mongoose'
import { z } from 'zod'

const objectId = z
	.string()
	.refine(Types.ObjectId.isValid, 'Invalid ObjectId')
	.transform((id) => new Types.ObjectId(id))

export const postIdParamSchema = z.object({
	id: objectId,
})

export const reactionParamSchema = z.object({
	postId: objectId,
})
```
