### ISSUE TITLE
Why is positive and negative functions uses zero as the minimum and maximum value?

### ISSUE THREAD

**Issue by imaness** [colinhacks/zod#3187]
I'm reading different writings about if zero value is considered as `positive` but so far it all tells its neither positive nor negative.  Same goes with the `negative` function.  Although I can raise PR for this but just want to get the narrative first before I modify it. Thanks

```typescript
  positive(message?: errorUtil.ErrMessage) {
    return this._addCheck({
      kind: "min",
      value: 0,
      inclusive: false,
      message: errorUtil.toString(message),
    });
  }

  negative(message?: errorUtil.ErrMessage) {
    return this._addCheck({
      kind: "max",
      value: 0,
      inclusive: false,
      message: errorUtil.toString(message),
    });
  }
```

**Comment by JacobWeisenburger** [comment]
Please send a full reproducible code example.

**Comment by JacobWeisenburger** [comment]
I'm going to close this issue. Please feel free to reopen if if you are able to provide a full reproducible code example.
