### ISSUE TITLE
Proposal: Create a new schema with the types based on the describe value

### ISSUE THREAD

**Issue by ralphchristianeclipse** [colinhacks/zod#3193]
Is this possible or not?

seems the types are not showing here

```ts
export const Schema= z.object({
  __typename: z.literal('ProjectMember'),
  id: z.string(),
  attributeField: z.number().optional().nullable().describe('[attribute]'),
});
const SchemaWithAttributeOnly = Schema.pick(
  mapValues(
    Schema.shape,
    item => item.description?.startsWith('[attribute]') ? true : undefined,
  ),
);
```

**Comment by Sjoerd82** [comment]
I think I may need the same thing, although I'm not entirely understanding your code. In my case my schema has a "translations" property in which I want to allow all STRING, **and only string**, properties of that same model. Currently I'm doing a hardcoded pick, which is not only prone to mistakes or being outdated, you also can't  "deep-pick" anything, so it's also incomplete.
