### ISSUE TITLE
How does it add ? in keys

### ISSUE THREAD

**Issue by TahsinAyman** [colinhacks/zod#3199]
Hello, I am `Tahsin Ayman`. i was looking after solving a bug / contribute in this open source project but as i read the code i noticed something **confusing** 😕 . in the source code on line number `4464-4468`:
```ts
export class ZodOptional<T extends ZodTypeAny> extends ZodType<
  T["_output"] | undefined,
  ZodOptionalDef<T>,
  T["_input"] | undefined
> 
```
this is the code when i use `.optional()` class returns. here the `T["_output"]` is the one causing the output hense it shows `undefined`
as mentioned in:
#3186 
but i'm not sure how does it even add `?` after keys when it's a object ❓ 

e.g:
```ts
const schema = z.object({
  name: z.string().optional()
});
/*
type User = {
    name?: string | undefined;
}
*/
type User = z.infer<typeof schema>;
```
but when i create just `string().optional()`
```ts
const schema = z.string().optional()
/*
type User = string | undefined
*/
type User = z.infer<typeof schema>;
```
where does it even add `?` ❔

**Comment by hesxenon** [comment]
I believe this is done here: https://github.com/colinhacks/zod/blob/master/src/helpers/util.ts#L107

Basically every key that does not have `undefined` as its values constituent stays as it is, the rest is made as `Partial<T>` which adds the questionmarks.
