### ISSUE TITLE
Documentation broken link

### ISSUE THREAD

**Issue by ibr4qr** [colinhacks/zod#3204]
In page https://zod.dev/ERROR_HANDLING?id=zodissue, when clicking on here "You can see all the possible variants defined [here](https://zod.dev/src/ZodError.ts)." 

I get

```src" content="https://opengraph.githubassets.com/1cac1150838995e1f7d1643c00eee51a5d884f2054f995c9d3225b07b0eddb39/colinhacks/zod" /> alt" content="TypeScript-first schema validation with static type inference" /> width" content="1200" /> height" content="600" />```

**Comment by JacobWeisenburger** [comment]
works as expected for me

**Comment by ibr4qr** [comment]
when clicking here on the first page i got the content of the second image:


<img width="108" alt="Schermata 2024-02-01 alle 09 15 59" src="https://github.com/colinhacks/zod/assets/78034840/127f9505-c261-440a-a5b9-db44e8b2e268">


<img width="1018" alt="Schermata 2024-02-01 alle 09 16 02" src="https://github.com/colinhacks/zod/assets/78034840/14986e1e-edbe-4fbc-997e-f99ec5d74f22">

**Comment by ibr4qr** [comment]
<img width="870" alt="Schermata 2024-02-01 alle 09 18 13" src="https://github.com/colinhacks/zod/assets/78034840/bc55ee41-a37a-4ca2-8c04-3ddb809a66bc">

**Comment by ibr4qr** [comment]
<img width="1511" alt="Schermata 2024-02-01 alle 09 24 43" src="https://github.com/colinhacks/zod/assets/78034840/b18c864c-616a-4c32-8de3-75d8e088982b">

**Comment by JacobWeisenburger** [comment]
I tried it again and it is working as you have described. it seems that if you open the link in a new tab or open the link and then reload the page it works just fine. So I'm guessing this is something to do with client side routing.

**Comment by colinhacks** [comment]
Thanks @ibr4qr! Zod's docs are getting a big refresh soon and I'll make sure this is fixed.

**Comment by colinhacks** [comment]
Fixed in https://github.com/colinhacks/zod/commit/4a618ef798231cdf152e55e506e7f21096d27468 👍
