### ISSUE TITLE
Question: How to make optional field to become required again?

### ISSUE THREAD

**Issue by zhaoyao91** [colinhacks/zod#321]
some shema are shared. to make it weakner, some fields are optional. but in some cases such as fucntion args, I hope some fields to be set as required again. I didn't find a method to achieve this.

**Comment by colinhacks** [comment]
You're right, this should definitely be added. I'll implement this shortly.

In the meantime you can access the "inner" schema of a ZodOptional like this:

```ts
const optString = z.string().optional();
const justString = optString._def.innerType;
```

As you can see, `justString` is a normal string schema:

![Screen Shot 2021-03-09 at 2 34 57 PM](https://user-images.githubusercontent.com/3084745/110541282-c753f880-80e4-11eb-814a-8dbfb2481375.png)

**Comment by colinhacks** [comment]
The newest v3 alpha (`zod@3.0.0-alpha.7`) contains an `unwrap` method for doing this.

```ts
z.string().optional().unwrap(); // ZodString
```
