### ISSUE TITLE
Get valid data after safeParse failure

### ISSUE THREAD

**Issue by darioielardi** [colinhacks/zod#325]
I frequently find myself wanting to get data that passed validation after a `safeParse` failure.

To provide a bit of context, I am using zod ( v3 ) with NextJS to validate the `context.query` object, and I want to reload the page with only the valid query params if validation fails. It's pretty simple to strip fields based on the `error.path` looping through the returned errors, but there are still some cases like unknown fields presence that are not so easy to handle.

Any chance this is already possible / planned for development? I'd also be willing to work on it myself if it sounds like a valid feature.

**Comment by colinhacks** [comment]
Sorry, I'm not a fan of this. Parsing should be a binary operation that either succeeds or fails. This is a whole can of complexity that isn't worth introducing into core.
