### ISSUE TITLE
self reference types

### ISSUE THREAD

**Issue by alireza-bonab** [colinhacks/zod#326]
Self-reference types are not rare and in each project, it is possible to have a bunch of them.
```typescript

interface Label {
  name: string,
  value: string,
}

interface Button {
  name: string,
  value: string,
}

type View = Container | Button | Label;

interface Container{
  name: string,
  children: View
}

```

I couldn't find a solution to implement this using `zod`.

```typescript
const labelSchema = z.object({
  name: z.string(),
  value: z.string(),
});

const buttonSchema = z.object({
  name: z.string(),
  value: z.string(),
});

const containerShcema = z.object({
  name: z.string(),
  children: z.union([labelSchema, buttonSchema, containerShcema]).array(),
});

```

This will cause compiler error for `containerSchema` inside union array:
**`Block-scoped variable 'containerShcema' used before its declaration.`**

**Comment by alireza-bonab** [comment]
Found the answer:
[https://github.com/colinhacks/zod#recursive-types](https://github.com/colinhacks/zod#recursive-types)

**Comment by alireza-bonab** [comment]
I reopen this because I didn't satisfied with the way it validates self-referencing types.
I would like to let the team know that this needs another easier approach.

**Comment by dgreene1** [comment]
io-ts has the same limitation. Maybe it’s not something that can be solved without type hints. Just a casual observation.

**Comment by colinhacks** [comment]
It might be possible to solve this without typehints, there's an interesting discussion about that here: https://github.com/colinhacks/zod/issues/99

But Zod doesn't currently support it.

@alireza-bonab in the future, if you solve your own problem, close the issue so the maintainer doesn't have to worry about it 👍

**Comment by Gaubee** [comment]
Here is my solution. The idea is to proactively define the `Input`/`Output` types, avoiding the need to rely on `ZodRawShape` to infer the default behavior for `Input`/`Output`:

```ts
import { z } from "zod";

export type MyDemo = {
  owner?: MyDemo;
  children: MyDemo[];
};
type Z_MyDemo = z.ZodObject<
  /*ZodRawShape*/ {
    owner?: z.ZodLazy<Z_MyDemo>;
    children?: z.ZodLazy<z.ZodArray<Z_MyDemo>>;
  },
  /*UnknownKeys*/ z.UnknownKeysParam,
  /*Catchall*/ z.ZodTypeAny,
  /*Output*/ MyDemo,
  /*Input*/ MyDemo
>;

export const z_demo: Z_MyDemo = z.object({
  owner: z.lazy(() => z_demo),
  children: z.lazy(() => z_demo.array()),
});
```
