### ISSUE TITLE
nonPrimitive

### ISSUE THREAD

**Issue by Dinhero21** [colinhacks/zod#3269]
It would be nice if zod could parse "extended" functions (and also other extended types as well).

By extended function I mean an object that has a type of `function` and is an instance of `Function` and other methods not commonly found in a function object.

So, for example:

```js
function example () {}

example.displayName = 'some value'
```

Function (`Function.prototype`)s normally don't contain any `displayName` properties but this one does.

You could try to parse this in zod using `z.object({ displayName: z.literal('some value') })` but that would fail as `z.object`, instead of checking if the property isn't a primitive, checks if its type is of `object` (which it isn't, since it is of type `function) (and probably other stuff like not an array).

Having a `nonPrimitive` (or `weakObject` or similar) type here would be really helpful, as the following could be done:

```js
// or weakObject
z.nonPrimitive({
  displayName: z.literal('some value')
})
```

For more type safety you could also add a `typeof` (or `typeOf`):

```js
z.nonPrimitive({
  displayName: z.literal('some value')
})
  .typeof('function')
```

**Comment by Dinhero21** [comment]
I hackily solved my problem using custom types:

```js
z.custom(({ displayName }) => displayName === 'some value')
```

**Comment by JacobWeisenburger** [comment]
Do you have more of a concrete use case where this would be useful?

**Comment by m10rten** [comment]
Not seeing (yet) why this would improve Zod.

**Comment by JacobWeisenburger** [comment]
Please provide a concrete use case where this would be useful, or this issue will be closed.

**Comment by Dinhero21** [comment]
> Please provide a concrete use case where this would be useful

Probably not in API data validation but it could be useful in reflection-like situations where you want to, for example, find a class or function (`instanceof Function`) that has some specific deeply nested property that would be very awkward to check for with traditional js/ts.

I might be using the wrong library since ig zod wasn't really designed for these use cases but I'm not aware of any other existing ones. (maybe I should just write my own custom one)
