### ISSUE TITLE
Feature request: .exact type to prevent excess properties

### ISSUE THREAD

**Issue by dgreene1** [colinhacks/zod#327]
I’m migrating from io-ts to zod since I’d like a smaller package size, but one of the features I need is the `.exact` method. It’s a way to prevent an object from having more properties than the schema defines (or as Typescript calls it, “excess properties”).

~If this is a feature that you’d be interested in, I can submit a PR for it [just like I enhanced tsoa by adding an excess properties check into that library.](https://github.com/lukeautry/tsoa/issues/336) Or if zod already has something like this, I can’t add a PR enhance the docs. Or if zod already defaults to no excess properties, I can add to the readme for that.~

Update: I read the full readme and saw that zod does support this but doesn’t use the term exact or excess. I’ll submit a PR that adds those words to aid others in searching for these terms. Btw, bravo on taking this approach as the default! :)

**Comment by colinhacks** [comment]
Thanks! By default Zod v1 threw an error if unknown keys were present. As of Zod 2, the default behavior is to strip out unknown keys, like you mentioned. You can allow unknowns with `.passthrough()` or disallow them entirely with `.strict()`.

Feel free to submit this PR! Forking v3 would be best.
