### ISSUE TITLE
Use Input type for refine & superRefine 

### ISSUE THREAD

**Issue by ArnaudBarre** [colinhacks/zod#3272]
I'm running into this: https://github.com/colinhacks/zod/issues/2192

I'm quite ok with the behaviour, it helps know all errors for a form. But the types seems to lies to me because they are using `Output` instead of `Inuput`.

In my case the type are different because I use this wrapper:

```ts
  value.transform((v, ctx) => {
    if (v === null) {
      ctx.addIssue({ code: "custom", message: "Required" });
      return z.NEVER;
    }
    return v;
  });
```

Should the issue above be considered a bug or should the types be updated?

**Comment by JacobWeisenburger** [comment]
I'm closing this issue. Feel free to send a full reproducible code example to reopen it.
