### ISSUE TITLE
String length validation error messages can't distinguish between singular and plural count.

### ISSUE THREAD

**Issue by RockingThor** [colinhacks/zod#3273]
<img width="742" alt="Screenshot 2024-02-27 at 9 20 51 AM" src="https://github.com/colinhacks/zod/assets/121621183/3978c27a-8bad-480f-ad7e-3fdc30f58d21">

It always uses the "(s)" universally either it is 1 or 0 or >1. 

For example, if the zod schema is like this:

```
const SignUpFormSchema = z.object({
    alphabet: z.string().min(1)
});
```

If the user tries to submit the form without inputting anything the error message will be shown as:

`String must contain at least 1 character(s)`

The error message can be improved to:

`String must contain at least 1 character`

**Comment by colinhacks** [comment]
On further reflection, I'm not convinced the inconvenience of such a change for users is worth the marginal improvement to clarity here. Given Zod's current user base, many tens of thousands of tests would have to be very slightly updated to account for this change. I'm not convinced it's worthwhile. 

Zod 4 will also introduce a much easier method of customizing error messages, so hopefully fewer people will rely on the default messages too.
