### ISSUE TITLE
[Feature]: Allow Customizing the Error Message for `z.instanceof`

### ISSUE THREAD

**Issue by ITenthusiasm** [colinhacks/zod#3307]
## The Problem
Just like many others seem to be doing (#387, #3256), I'm trying to use Zod to validate files that are sent to the server via a web form. My schema looks like this:

```ts
// Server Side
const schema = z.object({ 
  picture: z.instanceof(Blob),
  // Other form field requirements ...
});
```

I'd like the error message that I send back to the client to be clear for users.

Something like
> File is required

is much more clear to users than
> Input not instance of Blob

Unfortunately, Zod doesn't seem to support custom error messages for the `instanceof` validator.

## The Solution
Developers could be allowed to specify a custom error message for this validator.

```ts
z.instanceof(Blob, "File is required")
```

Since many of the other validators allow customizing error messages, I was hoping that this would be an easy change?

**Comment by JacobWeisenburger** [comment]
Is this what you are looking for?

```ts
const schema = z.instanceof( Blob, { message: 'File is required' } )
const result = schema.safeParse( null )
!result.success && console.log( result.error.issues )
// [
//     {
//         code: "custom",
//         message: "File is required",
//         fatal: true,
//         path: [],
//     }
// ]
```

If you found my answer satisfactory, please consider supporting me. Even a small amount is greatly appreciated. Thanks friend! 🙏
https://github.com/sponsors/JacobWeisenburger

**Comment by ITenthusiasm** [comment]
Wow. I thought I vetted my options but I guess I didn't. :thinking: Sorry for the ignorant question. 🤦🏾‍♂️ And thanks for your help. I'll close the issue.

As for the support, I'll consider it! Though I'm not sure I'm in a position where I'm able to sponsor easily at this moment. Absolutely respect the `Stay Newlywed` goal, though! It's encouraging to see.


Best Wishes!
