### ISSUE TITLE
Generate a JSON schema from a `zod.object`

### ISSUE THREAD

**Issue by dipasqualew** [colinhacks/zod#331]
Love `zod`, so thanks for creating the library!

While working on an application, I want to share models and validators across repositories and components, the most common scenario being the backend application and the web frontend view. `zod` is great on this.

However, it would also be great to be able to generate a JSON Schema (https://json-schema.org) via the model definition (i.e. `zod.object`). These JSON objects can then be used to document API OPTIONS.

I believe that each of the zod field and option can be mapped to a JSON schema entity.

Few notes:

1. If there's no interest in implementing this feature, I am happy to jump on it with a fork & PR
2. If you believe that the feature would be out of scope of `zod` I am also happy to create a complementary package, i.e. `zod-json-schema` that exposes the utility function to convert the a `zod` object into a JSON Schema field.

Thanks again for the great library!

**Comment by colinhacks** [comment]
I think it's out of scope for the core library, but a separate `zod-json-schema` library would be awesome! I'd happily link to it from the README so it's easy to find. 

I'd hold off until Zod 3 drops though — there are some internal changes that will definitely impact your implementation. I'll bump this issue once it drops. 👍

**Comment by dipasqualew** [comment]
Cheers! Looking forward to Zod 3!

**Comment by colinhacks** [comment]
I think you could safely start developing this against the latest v3 (`npm install zod@next`). Just published `zod@3.0.0-alpha.7` which represents most of the major Zod 3 changes. I don't expect the API to significantly change at this point despite the fact it's technically still an alpha version. The changes will make it easier to implement something like JSON schema generation — for instance there's a way to access the `minLength` value of `z.array(z.string()).min(5)` (previously that wasn't possible).

**Comment by mrhammadasif** [comment]
> Hi, I have created a very basic implementation in zod-endpoints. This function transforms a zod schema into openapi spec. The models are defined as json schema.
> 
> https://github.com/flock-community/zod-endpoints/blob/master/src/openapi.ts

It doesn't seems to be compatible with zod@3.0.0

**Comment by mrhammadasif** [comment]
Have a look at my pull request for zod-to-json-schema library by @StefanTerdell

https://github.com/StefanTerdell/zod-to-json-schema/pull/2
