### ISSUE TITLE
url validation does not work as expected

### ISSUE THREAD

**Issue by adnbsr** [colinhacks/zod#3324]
``` typescript
import { z } from "zod";
import isUrl from "is-url";

console.log("zod", z.string().url().safeParse("javascript:void();"));
console.log("is-url", isUrl("javascript:void();"));
```
that gave output like

```
zod {
  success: true,
  data: "javascript:void();",
}
is-url false
```

*zod@3.22.4*, *is-url@1.2.4*

**Comment by colinhacks** [comment]
Zod passes the string into the `new URL()` constructor and checks for errors. At the moment, that's all it does. The exact implementation of `URL` is runtime-dependent, but Zod aims to prioritize language/runtime built-ins when possible.

I suggest passing the `isUrl` function into `.refine()` if you want other behavior.

```ts
z.string().refine(isUrl)
```

**Comment by SakarDev** [comment]
> Zod passes the string into the `new URL()` constructor and checks for errors. At the moment, that's all it does. The exact implementation of `URL` is runtime-agnostic, but Zod aims to prioritize language/runtime built-ins when possible.
> 
> I suggest passing the `isUrl` function into `.refine()` if you want other behavior.
> 
> ```ts
> z.string().refine(isUrl)
> ```

The URL constructor makes sense as a low-level API for parsing URLs, but Zod's `url()` validation should match what developers actually need, we're almost always validating web URLs (http/https, example.com), not every technically valid URL scheme.
Looking at that [issue](https://github.com/colinhacks/zod/issues/2236), seems like a lot of developers are surprised by this behavior :(

**Comment by foladipo-aforza** [comment]
This is indeed very surprising behaviour. I think there it should be mentioned in zod's documentation (under a section dedicated to `.url()`) to save future devs from expecting the wrong behaviour from `z.string().url()`. I can raise a PR if you want.
