### ISSUE TITLE
[Generic Types] zod doesn't extend zod? Does not return correct?

### ISSUE THREAD

**Issue by PauloFerreira25** [colinhacks/zod#3326]
Hello, please.
Shouldn't this work?

Shouldn't parse() return an object that extends zod?

![image](https://github.com/colinhacks/zod/assets/1591772/a276dd30-a195-4ad8-a0ce-13f25553fee0)

```typescript
import { z } from 'zod';

const zData = z.object({
  name: z.string(),
});
type zData = z.infer<typeof zData>;

const zTypeInParameters = <T>(params: z.ZodType<T>) => {
  return z.object({
    data: params,
  });
};
type zTypeInParameters<T> = z.infer<ReturnType<typeof zTypeInParameters<T>>>;

const zTypeInExtends = <T extends z.ZodType>(params: T) => {
  return z.object({
    data: params,
  });
};
type zTypeInExtends<T extends z.ZodType> = z.infer<ReturnType<typeof zTypeInExtends<T>>>;

const zTypeInExtendsTypeAny = <T extends z.ZodTypeAny>(params: T) => {
  return z.object({
    data: params,
  });
};
type zTypeInExtendsTypeAny<T extends z.ZodTypeAny> = z.infer<ReturnType<typeof zTypeInExtendsTypeAny<T>>>;

const zDataInst = zData.parse({ name: 'abc' });
const zTypeInParametersInst: zTypeInParameters<zData> = zTypeInParameters<zData>(zDataInst);
const zTypeInExtendsInst: zTypeInExtends<zData> = zTypeInExtends<zData>(zDataInst);
const zTypeInExtendsTypeAnyInst: zTypeInExtendsTypeAny<zData> = zTypeInExtendsTypeAny<zData>(zDataInst);

console.log(zTypeInParametersInst, zTypeInExtendsInst, zTypeInExtendsTypeAnyInst);

```

**Comment by colinhacks** [comment]
There's a difference between the type signature of a schema and the *inferred type* of that schema.

`zTypeInExtends` and `zTypeInExtendsTypeAny` have generic parameters that expect a ZodType instance, but you're passing in `{ name: string }`.

Are you trying to achieve something in particular here? Making this question more concrete would make it easier for me to help you.

**Comment by PauloFerreira25** [comment]
Hello,

Thank you very much for your attention and for responding so quickly.

"but you're passing in { name: string }". 
Yes, VSCode is reporting exactly that. But in this case, I am passing an object created by .parse(). Shouldn't this object be something that extends ZodType?

"Are you trying to achieve something in particular here?"
What I'm trying to do is create some generic types of objects created with Zod and assemble other objects also created by Zod.

In terms of logic, what I'm trying to do is very close to what I demonstrated.

I have an object created by zod, for example: zData.
A method that needs to receive an object created by zod , such as zTypeInParameters. And it returns a new Zod object with what was passed as a parameter inside.
And both need to have their type definitions.

Again, thank you very much for your attention.

**Comment by colinhacks** [comment]
`ZodType` is the base class for all Zod schemas. It has a bunch of methods on it like `.refine()`, `.optional()`, etc. 

The result of `.parse()` is just data. It's signature depends on the schema. There's nothing special about what Zod returns. In your example it just returns a plain object with type `{name: string}`. The result is not the instance of any class, and it has no way to refer to the schema that produced it. 

Feel free to ask follow up questions but I'm going to close for now.

**Comment by PauloFerreira25** [comment]
Hi, please don't close. I'll try to do better with what I need, so you can try to explain to me how to do it.

**Comment by PauloFerreira25** [comment]
```typescript
import { z } from 'zod';

// Example of a zod schema. I have several, one for each "entity"
const Users = z.object({
  name: z.string(),
});
type Users = z.infer<typeof Users>;

// Example of a zod schema that standardizes all returns from a rest
const RestResponseModel = <M>(model: M) => {
  return z.object({
    content: model,
  });
};

const user: Users = //What needs to be here? (1)
const ResponseModelUser: ResponseModel<Users> = //What needs to be here? (2)
```

What needs to be done to make it work?

**Comment by PauloFerreira25** [comment]
Hi, I think I found it

**Comment by PauloFerreira25** [comment]
```typescript
import { z } from 'zod';

const Users = z.object({
  name: z.string(),
});
type Users = z.infer<typeof Users>;

// Example of a zod schema that standardizes all returns from a rest
const RestResponseModel = <T>(schema: z.ZodType<T>) => {
  return z.object({
    content: schema,
  });
};

type RestResponseModel<T> = z.infer<ReturnType<typeof RestResponseModel<T>>>;

// Converting everything
const user: Users = Users.parse({ name: 'abc' });
const ResponseModelZodSchema = RestResponseModel(Users);
const ResponseModelUser: RestResponseModel<Users> = ResponseModelZodSchema.parse({ content: user });
console.log(ResponseModelUser);
```

**Comment by PauloFerreira25** [comment]
But now, I need to see how I convert this to be the same as what you describe in the documentation.

https://github.com/colinhacks/zod?tab=readme-ov-file#writing-generic-functions

Because I need to have a way to define the element of a generic type.

```typescript
const ResponseModelUser: RestResponseModel<Users>
```

**Comment by PauloFerreira25** [comment]
I don't know how I can get something that went through infer back to ZodType. Or something, accepted by ZodType

```typescript
// Example of a zod schema. I have several, one for each "entity"
const Users = z.object({
  name: z.string(),
});
type Users = z.infer<typeof Users>;

// Example of a zod schema that standardizes all returns from a rest
const RestResponseModel = <T extends z.ZodTypeAny>(schema: T) => {
  return z.object({
    content: schema,
  });
};

type RestResponseModel<T extends z.ZodTypeAny> = z.infer<ReturnType<typeof RestResponseModel<T>>>;

// Converting everything
const user: Users = Users.parse({ name: 'abc' });
const ResponseModelZodSchema = RestResponseModel(Users);
// Because the only way I can do it is by doing this "thing"
const ResponseModelUser: RestResponseModel<Users & z.ZodTypeAny> = ResponseModelZodSchema.parse({ content: user });
console.log(ResponseModelUser);
```

**Comment by PauloFerreira25** [comment]
Would it be possible to produce a new unit test, which instead of passing the data content together with the schema, would be separate elements?
That would work well in my scenario.

**Comment by PauloFerreira25** [comment]
```typescript 
import { z } from 'zod';

const Users = z.object({
  name: z.string(),
});
// creating a type with ZodType
type ZUsers = z.ZodType<Users>;
type Users = z.infer<typeof Users>;

const RestResponseModel = <T extends z.ZodTypeAny>(schema: T) => {
  return z.object({
    content: schema,
  });
};
type RestResponseModel<T extends z.ZodTypeAny> = z.infer<ReturnType<typeof RestResponseModel<T>>>;

const user: Users = Users.parse({ name: 'abc' });
const ResponseModelZodSchema = RestResponseModel<ZUsers>(Users);
const ResponseModelUser: RestResponseModel<ZUsers> = ResponseModelZodSchema.parse({ content: user });
console.log(ResponseModelUser);
```

Hi, I got better until it became "compatible" with everything. Forcing the typings and using the created elements.

Is there a way to improve this?
```typescript 
type ZUsers = z.ZodType<Users>;
```

Is there a way to have the type of an element without having to ask ZodType?

**Comment by PauloFerreira25** [comment]
```typescript
import { z } from 'zod';

// Example of a zod schema. I have several, one for each "entity"
const ZUsers = z.object({
  name: z.string(),
});

type ZUsers = typeof ZUsers;
type Users = z.infer<typeof ZUsers>;

// Example of a zod schema that standardizes all returns from a rest
const ZRestResponseModel = <T extends z.ZodTypeAny>(schema: T) => {
  return z.object({
    content: schema,
  });
};
type ZRestResponseModel<T extends z.ZodTypeAny> = typeof ZRestResponseModel<T>;
type RestResponseModel<T> = z.infer<ReturnType<typeof ZRestResponseModel<z.ZodType<T>>>>;

// Converting everything
const user: Users = ZUsers.parse({ name: 'abc' });
const ResponseModelZodSchema = ZRestResponseModel<ZUsers>(ZUsers);
const ResponseModelUser: RestResponseModel<Users> = ResponseModelZodSchema.parse({ content: user });
console.log(ResponseModelUser);
```

Okay, I think I can understand now.
z.infer creates a type that is no longer ZOD, it is similar to a POJO
Hence the incompatibility.
To have the 2 worlds, I need 2 types. One from "POJO", another from ZOD.
So when using it in the function, I use ZOD, but when using it when returning the function, I use "POJO".

**Comment by PauloFerreira25** [comment]
Thank you for your attention and patience
