### ISSUE TITLE
How to achive yup's when() utility? 

### ISSUE THREAD

**Issue by mzalevski** [colinhacks/zod#333]
Hi, in [yup](https://github.com/jquense/yup#mixedwhenkeys-string--arraystring-builder-object--value-schema-schema-schema) there is a `when()` utility which allows users to "adjust the schema based on a sibling or sibling children fields." Is there a way to contruct such conditionals in `zod` schemas? I could not find such utility in the documentation. If it's by design, please let me know! I'd love to define a schema similar to the one below (`adminSecret` is conditionally optional):

```
import * as z from "zod";

interface User {
  id: string;
  isAdmin: boolean;
  adminSecret?: string;
}

const userSchema: z.ZodSchema<User> = z.object({
  id: z.string(),
  isAdmin: z.boolean(),
  adminSecret: z.string().when("isAdmin", (isAdmin, schema) => {
    return isAdmin ? schema : schema.optional();
  }),
});

const blob = {
  id: "20ec0677-68d8-45b5-a522-16cff767ac6f",
  isAdmin: true,
};

// should throw an error because
// the blob has no adminSecret !
const user = userSchema.parse(blob);
```

**Comment by colinhacks** [comment]
I dislike the idea of this, since it breaks locality. Typically I recommend adding this as a custom refinement on `userSchema`.

```ts
const userSchema: z.ZodSchema<User> = z.object({
  id: z.string(),
  isAdmin: z.boolean(),
  adminSecret: z.string().optional()
}).refine(val => {
  return val.isAdmin ? val.adminSecret !== undefined : true;
}, { message: "Admin secret missing from admin user." });
```

**Comment by mzalevski** [comment]
Makes sense. Thanks @colinhacks! I've just read the `refine` docs again and its seems like I missed the possibility to access siblings in validation function.

**Comment by ChambreNoire** [comment]
The issue with this approach (as far as I can see) is that one can't infer that `adminSecret `is not undefined based on the value of `isAdmin`. So in, say, the `onSubmit`, one must perform more checks:
`const onSubmit = (data: z.infer<typeof userSchema>) => {
  data.isAdmin && doSomething(data.adminSecret) // nope 
  data.isAdmin && data.adminSecret && doSomething(data.adminSecret) // yup
}`
