### ISSUE TITLE
z.infer<T> infers optional fields even though no .optional() is specified

### ISSUE THREAD

**Issue by exones** [colinhacks/zod#3330]
Environment:
- zod v. 3.22.4
- TypeScript v. 5.2.2

Reproduction: https://stackblitz.com/edit/react-ts-awcdlz?file=App.tsx

If I specify a Zod schema like this:
```ts
const RequiredNameSchema = z.object({
  requiredName: z.string(), // should infer required field
  optionalName: z.string().optional(),  // should infer optional field
});

type RequiredNameType = z.infer<typeof RequiredNameSchema>;
```

The inferred type of `RequiredNameType` is (note that both fields are optional):
```ts
type RequiredNameType = {
  requiredName?: string; // PROBLEM: infers optional field
  optionalName?: string;
}
```

Expected inferred type (e.g. as found in the example here: https://zod.dev/?id=basic-usage):
```ts
type RequiredNameType = {
  requiredName: string;
  optionalName?: string;
}
```

Or am I missing something?

**Comment by sid507** [comment]
You need to parse it
console.log(RequiredNameSchema.parse(rabbit));
It throws the error

**Comment by sid507** [comment]
Hi @exones ,
I got your point,

tsconfig.json
{
  "compilerOptions": {
    "module": "esnext",
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "sourceMap": true,
    "lib": ["es6", "dom", "es2019"],
    "strict": true
  }
}

Try adding strict:true in tsconfig file. It will work

**Comment by Dmarcotrigiano** [comment]
My docker builds started breaking because of optional fields throughout a schema definition:
Definitions:
```ts
import { z } from "zod";

const riskQueryNoVectorZSchema = z.object({
    topic: z.string(),
    tags: z.array(z.string()),
    query: z.string(),
});

export const riskQueryZSchema = z.object({
    vector: z.array(z.number()).nonempty(),
    id: z.string(),
    payload: z.object({
        topic: z.string(),
        tags: z.array(z.string()),
        query: z.string(),
    }).required(),
}).required()
export const riskQueriesFromDisk = z.array(riskQueryNoVectorZSchema).nonempty()
```
Error:
```
TS2345: Argument of type '[{ topic?: string; tags?: string[]; query?: string; }, ...{ topic?: string; tags?: string[]; query?: string; }[]]' is not assignable to parameter of type 'RiskQueryBackupData'.
  
  Type '{ topic?: string; tags?: string[]; query?: string; }' is not assignable to type '{ topic: string; tags: string[]; query: string; }'.
    
    Property 'topic' is optional in type '{ topic?: string; tags?: string[]; query?: string; }' but required in type '{ topic: string; tags: string[]; query: string; }'.
```
    
 Adding `strict: true` fixes the following tsconfigs:
 
 ```json
 {
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "module": "commonjs",
    "types": ["node"],
    "emitDecoratorMetadata": true,
    "target": "es2021"
  },
  "exclude": ["jest.config.ts", "src/**/*.spec.ts", "src/**/*.test.ts"],
  "include": ["src/**/*.ts"]
}
```

```json
{
  "extends": "../../tsconfig.base.json",
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ],
  "compilerOptions": {
    "strict": true,
    "esModuleInterop": true
  }
}
```

**Comment by FernetB** [comment]
Same issue here but I put `strict: true` and still don't work

**Comment by exones** [comment]
> Hi @exones , I got your point,
> 
> tsconfig.json { "compilerOptions": { "module": "esnext", "noImplicitAny": true, "removeComments": true, "preserveConstEnums": true, "sourceMap": true, "lib": ["es6", "dom", "es2019"], "strict": true } }
> 
> Try adding strict:true in tsconfig file. It worked for me

Thanks, it worked indeed, but now I have to refactor a looooot of stuff in my TS project 😅

**Comment by brenc** [comment]
Saw this today in my NestJS project. I always had `strict: true` but for some reason they also set `strictNullChecks: false` by default. Commented that out and that fixed my inferred types.
