### ISSUE TITLE
z.undefined() behaves weird

### ISSUE THREAD

**Issue by wtlgo** [colinhacks/zod#3332]
I was trying to create a schema verifier for one pre-existing interface and stumbled into a weird problem.

This works:
![image](https://github.com/colinhacks/zod/assets/50925676/325c2dd6-a210-4bd5-994b-cdc3f7055bb7)

But these aren't:
![image](https://github.com/colinhacks/zod/assets/50925676/418fd9af-12a4-480e-af0d-1738413cf0e8)
![image](https://github.com/colinhacks/zod/assets/50925676/bb22da54-3e40-4b4e-8f6f-fd9e6951ab8a)
![image](https://github.com/colinhacks/zod/assets/50925676/e387d084-7e9b-4fa5-8a9c-14e36ae683cb)

I find this behavior to be weird. I understand where it might come from, but describing some project types with this library becomes impossible. Also, I would like to point out that in the real project, I have no control over the interface, so this example is from the wild.

**Comment by colinhacks** [comment]
Indeed, this is tracked here: https://github.com/colinhacks/zod/issues/635
