### ISSUE TITLE
Documentation for ZodCodeGenerator

### ISSUE THREAD

**Issue by Foo42** [colinhacks/zod#335]
I recently discovered the ZodCodeGenerator while browsing the source, and after discovering how to use it with some trial and error am keen to make use of it for some code generation within a project I'm on. However, I noticed there was no documentation for it and don't wish to rely on a feature which may not be considered part of the libraries stable API.

Is the lack of documentation intentional or accidental?

**Comment by colinhacks** [comment]
I'm afraid it's very intentional, in fact all that functionality was just removed in the newest version of Zod 3. It was something I was playing around with, but I don't think it makes sense for that to be in the core library. That said, if you (or anyone else reading this) wanted to split that out into a separate utility, I'd be happy to link to it in the readme. You can use my old implementation as a starting point (though it'll need some refactoring to work with the newest Zod 3 version, which eliminated the `ZodTypes` enum for the sake of easier extensibility).

**Comment by SuchMonkey** [comment]
This seems like something I would need...maybe?
Or maybe I'm just missing something else.

I am looking for a way to iterate over a Zod schema.
Either recursively or by first flattening the schema and working with paths.

To be precise:
From a given schema I want to derive (react) props for form fields, like type="text|number", required, etc...

What would be the best way to approach this?

**Comment by colinhacks** [comment]
True, the reason I added `ZodTypes` at all was so thing like this would be easier to implement. But it's still very much possible. Zod now exports a type called `ZodFirstPartySchemaTypes` which is a big union of all the types defined by Zod:

```ts
export type ZodFirstPartySchemaTypes =
  | ZodString
  | ZodNumber
  | ZodBigInt
  | ZodBoolean
  | ZodDate
  | ZodUndefined
  | ZodNull
  | ZodAny
  | ZodUnknown
  | ZodNever
  | ZodVoid
  | ZodArray<any>
  | ZodObject<any>
  | ZodUnion<any>
  | ZodIntersection<any, any>
  | ZodTuple
  | ZodRecord
  | ZodMap
  | ZodSet
  | ZodFunction<any, any>
  | ZodLazy<any>
  | ZodLiteral<any>
  | ZodEnum<any>
  | ZodEffects<any>
  | ZodNativeEnum<any>
  | ZodOptional<any>
  | ZodNullable<any>
  | ZodPromise<any>;
```

If you have an generic instance of ZodType, just cast it to `ZodFirstPartySchemaTypes` and use `instanceof` to differentiate:

```ts
const codegen = (_schema: z.ZodTypeAny)=>{
  const schema: ZodFirstPartySchemaTypes = "adsf" as any;
  if (schema instanceof ZodString) {
    schema._def.isEmail;
  }else if(schema instanceof ZodNumber){
    // etc
  }
}
```

TypeScript is smart enough to properly type `schema` inside each if statement (so you can access properties that are specific to a particular subclass).

**Comment by SuchMonkey** [comment]
Thank you very much for your insights :)

**Comment by HannesP** [comment]
I'm working on an RPC library for personal use, where I'm currently relying on io-ts. I just found out about Zod's much more convenient way to work with and would love to switch, but I'm dependent on being able to generate valid client code. Here's an example to describe the use case: https://github.com/farcry-ts/farcry#example
