### ISSUE TITLE
Question: Is there any way to turn a schema nullable if it has required fields inside?

### ISSUE THREAD

**Issue by juanpablob** [colinhacks/zod#3350]
Hello everyone! I have a schema like this:

```js
const firstSchema = z.object({
  field1: z.string().required(),
  field2: z.string().required(),
  field3: z.string().required(),
});

const secondSchema = z.object({
  myField: myCondition ? firstSchema : firstSchema.nullable(); // make a schema nullable() doesn't work because it has required fields inside. 
});
```
Is there any chance to make a schema fully nullable and "override" the required conditions of it? If not, would you suggest any workaround or ideas?

Thank you for your help! 💜

**Comment by colinhacks** [comment]
This isn't your question, but there is no `.required()` method in Zod. All schemas are "required" unless you make them optional with `.optional()`.

Given that, I'm confused by what the problem is. If you call `.nullable()` on your schema, it will allow `null` no matter what.
