### ISSUE TITLE
Question: superRefine on nested objects

### ISSUE THREAD

**Issue by MattyChance** [colinhacks/zod#3351]
Hi, I tried to play around with`.superRefine` to add some custom issues. I found that zod only supports these on the first level of an object schema. Could someone confirm with me that this is true? Or am i missing something?

```
export const AnotherSchema = z.object({
    id: z.string(),
    clientId: z.string(),
});

export const BaseSchema = z.object({
    key1: z.string().superRefine((val, ctx) => {
        ctx.addIssue({
            code: z.ZodIssueCode.custom,
            message: 'trouble looking'
        });
    }),
    key2: AnotherSchema,
});
```

if I add 
```
export const BaseSchema = z.object({
    key1: z.string().superRefine((val, ctx) => {
        ctx.addIssue({
            code: z.ZodIssueCode.custom,
            message: 'trouble looking'
        });
    }),
    key2: AnotherSchema,
});
```
This works fine. I can see:
```
ZodError: [
      {
        "code": "custom",
        "message": "trouble looking",
        "path": [
          "key1"
        ]
      },
      {
        "code": "invalid_type",
        "expected": "string",
        "received": "undefined",
        "path": [
          "key2",
          "clientId"
        ],
        "message": "Required"
      }
    ]
```
However moving the superRefine to key2's schema won't print out any issues like above.

If this is expected behaviour, how can I make zod to throw a custom issue or error on nested objects then?

Thank you.

**Comment by colinhacks** [comment]
Thanks for the bug report, I'll look into this.

In the future, it's easier to provide a single snippet of code, then specify a) how it behaves and b) how it should behave. I also don't know what data you were trying to parse, which is necessary to debug fully. 

Also consider adding the `ts` annotation onto your code blocks to get syntax highlighting:

````
```ts
// your code here
```
````

**Comment by colinhacks** [comment]
This is intended behavior. 

Inside the `superRefine` call, the first argument `val` is strongly typed. Because `AnotherSchema` failed validation, it doesn't run the refinement call, because Zod knows that the data doesn't conform to that type signature. In other words, Zod only runs refinements if parsing succeeds on the schema first.

![Screenshot 2024-03-22 at 4 08 00 PM](https://github.com/colinhacks/zod/assets/3084745/0e7bd6f2-cca3-4c77-802e-329bcebc5940)
