### ISSUE TITLE
Safeparse on error return all valid data, any defaults, and the errors

### ISSUE THREAD

**Issue by ddeisadze** [colinhacks/zod#3354]
Is there anyway to do this? In my schema, i have conditions and for certain fields default values.

calling safeParse(), I want to return all the errors, as well as the data that parsed successfully, and the data that had default applied.

Otherwise, I cant use safeParse and have to manually set defaults.

**Comment by colinhacks** [comment]
Returning some partially-validated data is not a good solution, that's messy and error-prone. There's also no way to provide any type safety for the returned data in the general case. I'm guessing your use case can be covered with `.default()` and `.transform()` but without further details it's hard to know.
