### ISSUE TITLE
Branded types inferred improperly by function when inside `ZodObject` passed as `ZodSchema`

### ISSUE THREAD

**Issue by thatvertigo** [colinhacks/zod#3363]
# Description

When passing a `ZodObject` containing a branded type to a function as a `ZodSchema`, the function infers the type of the branded field without the brand(IE turning `foo: string & z.BRAND<'brand'>` into `foo: string`). This means functions which seek to validate using Zod schemas generically are effectively unable to work with branded types.
# Example

```ts
// Should return exactly what it's passed
const schemaId = <T>(schema: ZodSchema<T>) => schema;

const myObject = z.object({ foo: z.string().brand('brand') });
const shouldEqualMyObject = schemaId(myObject); // T inferred as { foo: string } instead of { foo: string & z.BRAND<'brand'> }

type MyObject = z.infer<typeof myObject>; // { foo: string & z.BRAND<'brand'> }
type ShouldEqualMyObject = z.infer<typeof shouldEqualMyObject>; // { foo: string }
```

# Workarounds

Notably, this does *not* occur when `schemaId` takes a `ZodObject` like so
```ts
const schemaId = <T extends ZodRawShape>(schema: ZodObject<T>) => schema;
// ...
type ShouldEqualMyObject = z.infer<typeof shouldEqualMyObject>; // { foo: string & z.BRAND<'brand'> }
```
or when the generic `T` is for the whole `ZodSchema`
```ts
const schemaId = <U extends ZodSchema>(schema: U) => schema;
// ...
type ShouldEqualMyObject = z.infer<typeof shouldEqualMyObject>; // { foo: string & z.BRAND<'brand'> }
```

**Comment by colinhacks** [comment]
I can't replicate this, see https://www.typescriptlang.org/play?ts=5.3.3#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQVA9NXAMoAWEArgDbFxQCmMLUAOzjcAHgEMAxjDYBPOAHdGY+MBgByAM5wwYjRu7EKmFgKnAIQjRMbcQYgJLEAPABUAfAAorNuwC4UAHQAWiQuMmDcrm4AlIhcvPyW1rZi6JQUEhYa8CAyAPIARgBW3FJwALyBEMWlMB5ImBAQ-sgB2VDAAgDmHtEBBVBiAsQe+ANDpLFo0ZSZAtlwGszsxACiAI4sYmwAsvk1ZZXeKY4euYUlUjNwtHAucJ2Y3FA8nLpxjc2LMB3d6A-zGDcMScCCYD5NfztTpdOAAMkCACEAEoAQQAcgARJxqcbDNRudBUGDhbhwPYXWoVQKPZ5OEkRMFwc4HGBuMg3OgNSHfX6whGtFEY7G4wb4wloCgMslMVgcDZbXb7S7wSqtWlQemkplLOVrTbbCms9mciFfaF-NBAA

**Comment by thatvertigo** [comment]
Oh, weird. Glad it got fixed :)
