### ISSUE TITLE
z.union has no `_parseSync` method with bare literals

### ISSUE THREAD

**Issue by akre54** [colinhacks/zod#3364]
I'm getting an error when trying to call parse on a union with primitive literals:

```
const schema = z.union(['a', 'b'])
schema.parse('a') // Throws Error: option._parseSync is not a function
```

Using numbers or booleans gives the same results.

Changing the `union` to an enum or wrapping the literals in `z.literal` fixes the issue.

Zod version 3.22.4

**Comment by colinhacks** [comment]
I understand how this API could be useful, but it's intentional and I'm not planning to add support for literal values in `z.union`. This exact use case is already covered by `z.enum`.
