### ISSUE TITLE
Not able to change state inside refine 

### ISSUE THREAD

**Issue by aagatsharma** [colinhacks/zod#3368]
When i try to submit the form at first, the **firstField** doesnot get updated but when i submit the form again, the firstField gets updated. Can i know why i have to resend the form again to get updated state.

```typescript
const formSchema = z.object({
    email_phone: z.string().refine(
      (value) => {
        if (emailRegex.test(value)) {
          setFirstField("email");
          return true;
        } else if (phoneRegex.test(value)) {
          setFirstField("mobile_no");
          return true;
        } else {
          setFirstField("email");
          return false;
        }
      },
      {
        message: "Please enter a valid email or phone number",
      }
    ),
  });
```

**Comment by colinhacks** [comment]
This is dependent on your form library and not a Zod-specific issue. I don't have enough information to debug I'm afraid. I suggest putting some console.log statements into your refinement to make sure it's being called.
