### ISSUE TITLE
guidance following removal of intersection

### ISSUE THREAD

**Issue by jstewmon** [colinhacks/zod#337]
Hi, with the removal of `intersection`, I'm wondering what the best way to represent base shapes with conditional extensions? From looking at the diff, I suppose the recommendation is to use `merge` or `extend`, but that isn't very ergonomic with union types...

For example, I have a schema that validates oidc-provider client configurations that looks like this:

```ts
const clients = array(
  intersection(
    object({
      client_id: string(),
      grant_types: array(string()),
      redirect_uris: array(string()),
      tos_uri: string().url(),
      policy_uri: string().url(),
    }),
    union([
      object({
        application_type: literal("native"),
        token_endpoint_auth_method: literal("none"),
      }),
      object({
        token_endpoint_auth_method: z
          .enum(["client_secret_basic", "client_secret_post"])
          .optional(),
        client_secret: string(),
      }),
      object({
        token_endpoint_auth_method: z.enum(["private_key_jwt"]),
        jwks: object({
          keys: array(
            object({
              kty: string(),
              kid: string(),
              n: string(),
              e: string(),
            })
          ),
        }),
      }),
    ])
  )
)
```

It's a little busy, but you can see that there's a base schema that intersects with a union type for all of the conditional variants.

Without `intersect`, it seems like every type in the union has to be explicitly extended:

```ts
const clientBase = {
  client_id: string(),
  grant_types: array(string()),
  redirect_uris: array(string()),
  tos_uri: string().url(),
  policy_uri: string().url(),
};
const clients = array(
  union([
    object({
      application_type: literal("native"),
      token_endpoint_auth_method: literal("none"),
    }).extend(clientBase),
    object({
      token_endpoint_auth_method: z
        .enum(["client_secret_basic", "client_secret_post"])
        .optional(),
      client_secret: string(),
    }).extend(clientBase),
    object({
      token_endpoint_auth_method: z.enum(["private_key_jwt"]),
      jwks: object({
        keys: array(
          object({
            kty: string(),
            kid: string(),
            n: string(),
            e: string(),
          })
        ),
      }),
    }).extend(clientBase),
  ])
);
```

We can't use `[].map()` over the union argument because `map` doesn't preserve the input length in the output type.

Is there another way of continuing to express this, or is the expectation that every entry in a union has to be manually extended?

**Comment by colinhacks** [comment]
Hey @jstewmon — I think that's the right approach here. ZodIntersection added a lot of complexity that didn't seem worth it given how few valid use cases there are for it. It's also one of the few top-level functions (`z.intersection`) that weren't able to accept any schema type, which rubbed my the wrong way. 

I think this is a valid use case, but since the workaround is comparatively quite painless I recommend just extending each element of the union. But I'll leave this open; if a lot of people object here I'd consider adding it back in.

**Comment by jstewmon** [comment]
Agree that using `extend` isn't too bad, but it would be great to have a way to apply it over the union array. Maybe it's possible to write a small convenience function that can facilitate that while preserving the length to satisfy the union signature?

**Comment by colinhacks** [comment]
I've tried to get something like that working but never managed it. I don't believe it's possible without higher-kinded types: https://github.com/microsoft/TypeScript/issues/1213

**Comment by jstewmon** [comment]
I think [Mapped types on tuples] makes it possible to write this with a type cast. Here's a [Playground example] I hacked together (inline follows):

```ts
function tmap<T extends [any, any, ...any[]], Out>(a: T, fn: (item: T[number]) => Out): {[k in keyof T]: Out} {
  return a.map(fn) as {[k in keyof T]: Out};
}

function foo<T extends [number, number, ...number[]]>(args: T): void {
  for (const arg of args) console.log(arg)
};

foo(tmap([1, 2, 3, 4], i => i + 1))
```

[Mapped types on tuples]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#mapped-types-on-tuples-and-arrays
[Playground example]: https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFAtgQwA4B4AqiCmAHlPmACYDOiA2mmAJ4A0idTiAdJ69QLo-MB5EFAB8ACjQAuRDmbAw0sTBIppOamBAoARvgBOPAJSIAvCMRCoh6QG9qAa0Qwk9-PTjAZPaZYC+iGwAoREQ9fCgQPSQ0dnQMMXljNCo7R2dEV3dPHG8LYV8AbkDfQMDQSFgERGA4OFwCYlJKGk0dfWZW3T1mTnZO-V4ecTQ9AHMKNWtEADc4GDIA4Oq4PUQxCAQKKBYxxA8d8eMNsAo4ABt8djO4UYkxw2KistqxVEwxagBGZgAmZgBmZgAFn4TlM5hgiAA1IhPoZDEA

**Comment by colinhacks** [comment]
That works when `Out` is the same across all items in the tuple, but not if the type of an _individual element_ in the output tuple varies based on the type of that element in the input.

Here's my best attempt (doesn't work)

```ts
const tmap = <T extends [AnyZodObject, ...AnyZodObject[]], Out>(
  a: T,
  fn: (item: T[number]) => Out
): { [k in keyof T]: Out } => {
  return a.map(fn) as { [k in keyof T]: Out };
};

const extension = { test: z.boolean() };

const asdf = tmap(
  [
    z.object({
      asdf: z.string(),
    }),
    z.object({
      asdf: z.number(),
    }),
  ],
  <T extends z.AnyZodObject>(
    asdf: T
  ): z.ZodObject<T["_shape"] & typeof extension> => {
    return asdf.extend({ test: z.boolean() }) as any;
  }
);

const aasdfsdf = asdf[0].shape;
```

You still end up with a union type for each element:

![Screen Shot 2021-03-18 at 9 48 33 PM](https://user-images.githubusercontent.com/3084745/111729038-bff2c480-8833-11eb-85cd-8f43ffa40ca3.png)

**Comment by colinhacks** [comment]
Okay, this issue, combination with #351, have convinced me that it has worthwhile to keep ZodIntersection. Note that `.merge` is still going to allow key overwriting (like `.extend`). If you change all your calls of `A.merge(B)` to `A.and(B)`, your code should continue working as it did before the alpha.7 release. You'll need to upgrade to the latest alpha to get the `.and` method: `yarn add zod@next`
