### ISSUE TITLE
[Questtion] How do I make a mutually exclusive key?

### ISSUE THREAD

**Issue by 500-internal-server-error** [colinhacks/zod#3372]
I would like to have a config with either a value or an object, but with a name that matches the type - e.g., `userId: z.string()` XOR `userIds: z.object()`. I need exactly one of them to exist, like an XOR of keys. Is there a way I can express this type with zod?

```jsonc
{
    // input can be a single value for all options, or specify a different value for each option
    "userId": "abcd",
    "userIds": {
        "xyzw": "abcd",
        "ijk": "hjkl"
    }
}
```

I suppose I could wrap the entire thing in a `z.union()`, but that feels pretty unwieldy, especially if/when the number of fields (and thus the number of combinations) explodes:

```js
const schema = z.object({
    myMultiFormThing: z.union([
        z.object({ /* machineId = string, userId = string, groupId = string */ }),
        z.object({ /* machineId = string, userId = string, groupIds = array */ }),
        z.object({ /* machineId = string, userIds = array, groupId = string */ }),
        z.object({ /* machineId = string, userIds = array, groupIds = array */ })
    ])
});
```

Fortunately my config is not that complex yet, and worst case scenario I guess I can live with having the same key name for an object and value, but it would be nice if I can use the correct plurality for the key name.

**Comment by colinhacks** [comment]
I think I'd recommend just using the same key in this circumstance. Otherwise you're kinda working against TypeScript, since it can't represent XOR types natively.

Alternatively you can implement the XOR logic in a refinement but it isn't reflected in the static type signature - both fields are optional in this scenario.

```ts
z.object({
  userId: z.string(),
  userIds: z.string().array(),
}).refine(
  (val) => {
    // XOR
    return !!val.userId ^ !!val.userIds;
  },
  { message: "Specify userId or userIds" }
);
```

**Comment by acharyasaagar** [comment]
I have similar problem. 

I need to write a schema for a query which can be `{}` or `{ project: 123 }` or `{ task: 123 }`. In this query `project` and `task` can not be present together in the same query. Then I can have other parameters like `{ archived: false }` which can be present in any query. 

Currently what I am doing is: 

```ts

const mutuallyExclusiveKeys = [ 'project', 'task'] as const

const QuerySchema = z
  .object({
    project: z.string().optional(),
    task: z.string().optional(),
    archived: ZodStringToBoolean.optional(),
  })
  .refine(
    (data) => {
      const presentKeys = keys.filter((key) => data[key] !== undefined)
      return presentKeys.length <= 1
    },
    {
      message:
        `Only one of ${mutuallyExclusiveKeys.join(', ')} can be present in the query`,
    }
  )
```
**Is there a better way to achieve this ?**
