### ISSUE TITLE
Alternatives to using strict mode?

### ISSUE THREAD

**Issue by rollo-b2c2** [colinhacks/zod#3374]
Zod changes its behavior depending on if Typescript is using strict mode.

For example:

```
const User = z.object({
  username: z.string(),
});

type User = z.infer<typeof User>;
```

Non-strict:

```
type User  {
   username?: string
}
```

Strict:

```
type User {
   username: string
}
```

I can't help feel this is unexpected behavior, since field optionality has nothing to do with what mode typescript is running in.

I'm trying to add zod to an existing typescript codebase that doesn't use strict mode. Porting the whole codebase right now would be infeasible.

Is there any way to get the strict type output without having to port my entire codebase over?

**Comment by colinhacks** [comment]
> since field optionality has nothing to do with what mode typescript is running in

It has everything to do with it. One of the flags that are turned on in strict mode is `strictNullChecks` which essentially introduces `null` and `undefined` into the type system: https://www.typescriptlang.org/tsconfig#strictNullChecks

Without these, Zod can't easily distinguish between a required and an optional field, so everything gets marked as optional.

You might try only setting `strictNullChecks` to true, that may be an easier refactor.
