### ISSUE TITLE
Optional with Default failing type check (post -alpha.7)

### ISSUE THREAD

**Issue by prescience-data** [colinhacks/zod#339]
Not sure if I'm just "doing it wrong" but this was working prior to the latest alpha7 release:

#### Fails type check
![image](https://user-images.githubusercontent.com/65471523/111712665-35957980-88a2-11eb-86d7-30aa396316b8.png)

#### Upstream `env` schema:
![image](https://user-images.githubusercontent.com/65471523/111712698-45ad5900-88a2-11eb-8ccc-7462abe12e87.png)

### Possible cause:

The issue appears to be because ` z.string().optional()` is now typing as `() => string | undefined` whereas it was previously typing as `string | undefined`.

`Type 'undefined' is not assignable to type '() => string | undefined'.`

```typescript
// Cause
const env = z.object({
  TOKEN: z.string().optional()
})
// Type Error
const problem = z.object({
  token: z.string().optional().default(env.TOKEN)
})

```

Ultimately just want to make sure this is intentional before I refactor to solve it.

**Comment by colinhacks** [comment]
Hadn't considered this particular case! I consider this a bug. You should be able to pass in `undefined` as the default value of `z.string().optional()` if you want. Fixed in alpha.8.

**Comment by prescience-data** [comment]
Wow super fast fix! 🏃💨
