### ISSUE TITLE
refine() should not inherit type from custom()

### ISSUE THREAD

**Issue by AshotN** [colinhacks/zod#3393]
```ts
{
  id: z.string(),
  key: z.custom<"literal string">().refine(key => typeof key === 'string', {
    message: 'Key must be a string'
  })
}
```

In this schema the type of `key` is `"literal string"` which isn't accurate as really it can be `any` since no validation has narrowed the type

**Comment by colinhacks** [comment]
Once you use `z.custom`, you're on your own. It's intended as an escape hatch. The idea is to pass the refinement logic into `z.custom`:

```ts
z.custom<"literal string">((key) => typeof key === "string", {
  message: "Key must be a string",
});
```

**Comment by AshotN** [comment]
I don't think this should be closed. I get that custom is an escape hatch. My point is that the provided type is incorrect and TS gives warnings when treating the variable as anything besides what it's typed as. 

If custom is intended to be an escape hatch, the type should be 'any'
