### ISSUE TITLE
parameters and return type validation for functions

### ISSUE THREAD

**Issue by AndreaDelliGatti** [colinhacks/zod#3394]
Is there a way in zod to validate a function's parameters and its return type?
In the following example I have defined an object schema.
In the object there is a function that takes two parameters as numbers and returns void.
Then I defined an object in which there is a function that accepts a string and returns a boolean.
As you can see the output of the safeParse is success:true but in reality it is not correct as a result.

```typescript

import * as z from "zod";

const obj = {
    fn: (n: string) => { return true; }
}

const schema = z.object({
    fn: z.function(
            z.tuple(
                [
                    z.number(),
                    z.number()
                ]
            ),
            z.void()
        )
})

 // expected {success:false, error: ...}
let result = schema.safeParse(obj);

console.log(result); // received {success:true, data: ...}
```

![image](https://github.com/colinhacks/zod/assets/28861452/f62f9b32-7c26-49f7-8618-bbcb72ffa64a)

**Comment by colinhacks** [comment]
This isn't possible. TypeScript annotations aren't introspectable at runtime so there's no way for Zod to know what the expected parameter/return types are. 

The idea with `z.function()` is to make it easy to declare typesafe functions with `.implement()`

```ts
z.function(z.tuple([z.number(), z.number()]), z.void()).implement((...args) => {
  args[0]; // number
  args[1]; // number
});
```
