### ISSUE TITLE
Deep Partial registering as full original Schema when type is inferred (post -alpha.7)

### ISSUE THREAD

**Issue by prescience-data** [colinhacks/zod#340]
Post `-alpha7` release my Deep Partials are registering as the full type:

`TS2739: Type '{}' is missing the following properties from type '{ maxConnections: number; auth: "none" | "iponly" | "nbname" | "strong"; logFormat: string; }': maxConnections, auth, logFormat, platform`

### Reproduction

```typescript
import { z } from "zod"

export const TemplateOptionsSchema = z.object({
  maxConnections: z
    .number()
    .min(1)
    .max(65535)
    .default(env.PROXY_MAX_CONNECTIONS),
  auth: ProxyAuthSchema.default(env.PROXY_AUTH),
  logFormat: z.string().default(env.PROXY_LOG_FORMAT)
})

export const PartialTemplateOptionsSchema = TemplateOptionsSchema.deepPartial().passthrough()

export type PartialTemplateOptions = z.infer<typeof PartialTemplateOptionsSchema>

const  options: PartialTemplateOptions = {} // TS2739 error noted above...

```

### Issue

Was previously inferring the correct Deep Partial type when registering:

```typescript
export type PartialTemplateOptions = z.infer<typeof PartialTemplateOptionsSchema>
```

### Short Term Fix

Currently wrapping the type in `Partial<>`, but this seems counter to what would be expected:

```typescript
  options: PartialTemplateOptions = {} // Fail
  options: Partial<PartialTemplateOptions> = {} // Success
```

Just checking to see if this was intentional or unexpected behaviour?

**Comment by colinhacks** [comment]
This is tricky; it's actually related to the fact that you're setting default values. This was actually a bug in the old typing that I've now fixed. Once you've set a default value on the schema, the allowed input type and expected output type diverge. Previously this wasn't reflected in the types.

```ts
z.string().default('1234');
// input: string | undefined
// output: string
```

When you use `z.infer<typeof Z>`, it gives you the _output_ type (in this case `string`). What you want is `z.input<typeof Z>` instead.

This resolves the TypeScript error

```ts
export type PartialTemplateOptions = z.input<typeof PartialTemplateOptionsSchema>
const  options: PartialTemplateOptions = {} // TS2739 error noted above...
```

**Comment by prescience-data** [comment]
Ooh, that's interesting I hadn't actually noticed the `z.input` utility before!
Thanks for that!
