### ISSUE TITLE
how to validate external types

### ISSUE THREAD

**Issue by AndreaDelliGatti** [colinhacks/zod#3406]
is there a way in zod to validate external types not directly managed within my project?

in the example below I use a langgraph type to generate my own type. What I would like to do is create a zod schema to validate MyType.

```typescript
import { RunnableLike } from "@langchain/core/runnables";

export MyType = RunnableLike<string, number>
```

**Comment by colinhacks** [comment]
```ts
const MySchema = z.whatever() satisfies z.ZodType<MyType>
```

**Comment by floyergilmour** [comment]
the `whatever()` mehod doesn't seem to exist

```typescript
import { z } from "zod"

const MySchema = z.whatever() satisfies z.ZodType<LucideIcon>
```
