### ISSUE TITLE
Match only true

### ISSUE THREAD

**Issue by cdtut** [colinhacks/zod#3410]
There should be way to match true or false not both with z.boolean(). Example is field that can be a string or the value true. Some examples how it can look

```
z.union([
  z.string(),
  z.enum([true])
])

z.union([
  z.string(),
  z.boolean(true)
])

z.union([
  z.string(),
  true
])
```

**Comment by colinhacks** [comment]
Looks like you're looking for `z.literal()`

```ts
z.union([
  z.string(),
  z.literal(true)
])
```
