### ISSUE TITLE
Email validation fails on ampersand "&" sign

### ISSUE THREAD

**Issue by cbosman-docksters** [colinhacks/zod#3411]
Hi there,

I noticed the z.string().email() fails when the email contains an ampersand sign. This should be allowed.

Example:
`z.string().email().parse("test&test@test.com")`

**Comment by colinhacks** [comment]
Per #2157 Zod implements "Gmail rules" by default for email address validation. 

You can use `.superRefine` for custom behavior:

```ts
const emailRegex =
  /^(?!\.)(?!.*\.\.)([A-Z0-9_'+-\.]*)[A-Z0-9_'+-]@([A-Z0-9][A-Z0-9\-]*\.)+[A-Z]{2,}$/i;

const emailSchema = z.string().superRefine((data, ctx) => {
  if (!emailRegex.test(data)) {
    ctx.addIssue({
      code: z.ZodIssueCode.invalid_string,
      message: "Invalid email address",
      validation: "email",
    });
  }
});
```
