### ISSUE TITLE
The 'error' property does not exist in the type 'SafeParseReturnType

### ISSUE THREAD

**Issue by hugocruzlfc** [colinhacks/zod#3416]
I am trying to make a validator for my Config module  like this:

import { z as zod } from 'zod';

const validationSchema = zod.object({
  NODE_ENV: zod.string(),
  APP_PORT: zod.coerce.number().default(3000),
  DB_HOST: zod.string().min(4),
  DB_PORT: zod.coerce.number(),
  DB_NAME: zod.string(),
  DB_USER: zod.string(),
  DB_PASSWORD: zod.string(),
});

export type EnvVariables = zod.infer<typeof validationSchema>;

export const validate = (config: unknown) => {
  const result = validationSchema.safeParse(config);

  if (!result.success)
    return {
      error: result.error,
    };

  return { value: result.data };
};

![Captura de pantalla 2024-04-18 a las 14 11 53](https://github.com/colinhacks/zod/assets/55498983/6dfaf2e8-c84c-4ac8-90d2-4d6d972a57e6)

But I am getting this error:   Error' property does not exist in type 'SafeParseSuccess<{ NODE_ENV?: string; APP_PORT?: number; DB_HOST?: string; DB_PORT?: number; DB_NAME?: string; DB_USER?: string; DB_PASSWORD?: string; }>'.

Node Version: 20.11.0
Typescript Version: 5.4.5
Zod Version:  3.22.4

**Comment by colinhacks** [comment]
I'm not able to replicate: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgQwM4ogEzgXzgDMoIQ4AiZXCgbgCh6BjCAOw3gDc0AbYHNDGBsAykwAWAUxBo4AXmw4AdBABGAK0lMYACgT04cAHIB5ACIBRAPoWjANQBcipRyjBWAcx0BKADQG4AEEABWCrYJMAJQAVJ2plFkkoJkklVgBXEFUknyUcSSI0dJ5dAGYABkq-ALMAISsACRMRWOdXdy9vJRB3HQAWasM68KjW+KVE5NSMrJzBuGGjQIBZCzjcFxg3Tx9-IfqAVRELSPXldp354eDAkREAdSizM83tzv98bwZ6SQAPSFgcBgAE8wJI4BZWJw7Gg3GhVDxJFgFON3EQkgAeEFgiBEODcPgCISiCTSNAAPm+fwB8BY7C4vH4gnBCh0dKIwA8TnSrAA1qwIAB3VjeeTkxABOkcOBQJHFeAKAlM4msMRSGQuNDo4KwjCSNlsDkeL6MQzAPE6ACEsow8pc6SYKQwGG8AUMspg6SgrAlhj9cCSpCgThtdsD0D2fvw33dkk93sQ+N46UkIblJTyglk0foOaAA

Make sure you have `strict: true` in your tsconfig.json `compilerOptions`, that could be related.
