### ISSUE TITLE
Changelog for 3.22.5

### ISSUE THREAD

**Issue by samchungy** [colinhacks/zod#3420]
Hey Colin, was this an accidental release?

I was trying to spot a changelog or a diff but it doesn't look like anything changed? 😅 

<img width="667" alt="image" src="https://github.com/colinhacks/zod/assets/18017094/002bb6bc-85ab-41a1-b635-577332e49e5e">

**Comment by medv** [comment]
I felt a great disturbance in the Force, as if millions of voices suddenly cried out in ecstacy, and were suddenly silenced.

**Comment by colinhacks** [comment]
Yeah...there were no changes. The 3.23 beta accidentally got published to `latest` so I had to overwrite it with a new patch version 😅 

To all the formerly-ecstatic voices out there, try upgrading `zod@beta` and report any issues!

**Comment by samchungy** [comment]
> @samchungy You alluded to some changes that broke zod-openapi: [samchungy/zod-openapi#249](https://github.com/samchungy/zod-openapi/pull/249) Was this the additions to `ZodFirstPartySchemaTypes` or something else? I changed the default generic values in `ZodType` but I was hoping it wouldn't impact many people.

Ah, because we [extend ZodType](https://github.com/samchungy/zod-openapi/blob/3236ba908f57a2632f8bf44f189b51219470c04a/src/extendZod.ts#L83) the compiler gets cranky when the interface isn't identical: `All declarations of 'ZodType' must have identical type parameters.ts(2428)`

**Comment by colinhacks** [comment]
Ah gotcha. FFR you can entirely elide all the generics if you don't use them, might be a little more future-proof:

```ts
declare module "zod" {
  interface ZodType  {
    openapi<T extends z.ZodTypeAny>(this: T, metadata: ZodOpenApiMetadata<T>): T;
  }
}
```

**Comment by samchungy** [comment]
> Ah gotcha. FFR you can entirely elide all the generics if you don't use them, might be a little more future-proof:
> 
> ```ts
> declare module "zod" {
>   interface ZodType  {
>     openapi<T extends z.ZodTypeAny>(this: T, metadata: ZodOpenApiMetadata<T>): T;
>   }
> }
> ```

Hmm I thought I tried that at some point and the compiler complained to me.

But that looks like it works very well. Thanks!
