### ISSUE TITLE
Issue with inferring types from pipes.

### ISSUE THREAD

**Issue by mildfuzz** [colinhacks/zod#3461]
Using code that is almost verbatim lifted from docs:
```typescript
const forceNumber = z.union([z.string(), z.number()]).pipe(z.coerce.number())
```
Idea being to accept a number or string, and coerse to string or fail. The function works, unit tests are all fine, but type inference falls over like so:

```typescript
const forceNumber = z.union([z.string(), z.number()]).pipe(z.coerce.number())

const dataSchema = z.object({
  numberOrString: forceNumber,
})

type Data = z.infer<typeof dataSchema>

// parse any data into schema or fail
const parseSchema = <U>(data: any, schema: z.ZodType<U>): U => {
  return schema.parse(data)
}

// log Data
const logSchemaData = (data: Data) => {
  console.log(data)
}

function processDataAndLog(data: any) {
  const parsedData = parseSchema(data, dataSchema)
  logSchemaData(parsedData)
}

```

this gives us the following error:

![image](https://github.com/colinhacks/zod/assets/196705/a29b0833-870e-4ead-98fd-5ab677c77b6a)

**Comment by colinhacks** [comment]
I'd recommend checking out this guide for some pointers on writing generic functions that accept Zod schemas: https://github.com/colinhacks/zod?tab=readme-ov-file#writing-generic-functions

**Comment by mildfuzz** [comment]
Thanks @colinhacks, although having to infer the return type of a generic parsing function feels a bit icky. Wonder if there is a way to avoid that

**Comment by mildfuzz** [comment]
As it means that we're actually short circuiting the return type when we return the value of `schema.parse`, which could lead to human error that is not caught by TS

**Comment by mildfuzz** [comment]
I have found that 

```typescript 
const parseSchema = <Input, Output>(
  data: any,
  schema: z.ZodType<Output, ZodTypeDef, Input>,
): Output => {
  return schema.parse(data)
}
```

Fixes this without having to resort into type casting.

**Comment by colinhacks** [comment]
This is the recommended way to write that function:

```ts
// parse any data into schema or fail
const parseSchema = <U extends z.ZodType>(data: any, schema: U): z.infer<U> => {
  return schema.parse(data);
};
```

**Comment by mildfuzz** [comment]
> This is the recommended way to write that function:
> 
> ```ts
> // parse any data into schema or fail
> const parseSchema = <U extends z.ZodType>(data: any, schema: U): z.infer<U> => {
>   return schema.parse(data);
> };
> ```

Can I ask why is that recommended over what I've done? Just for my understanding
