### ISSUE TITLE
Can not use branded enum options

### ISSUE THREAD

**Issue by bohdan-shulha** [colinhacks/zod#3473]
Hi team,

Thanks for a great amount of work delivered!

_Not sure if it makes sense to use branded enums at all, but here is my case._

I have met an issue with my types: I am unable to use branded enum's options in TypeScript.

Minimal example:
```
export const AgentStatus = z.enum(["offline", "online"]);

console.log(AgentStatus.enum.offline);

export const AgentStatusBrand = z
	.enum(["offline", "online"] as const)
	.brand<"AgentStatus">();

console.log(AgentStatusBrand.enum.offline);
```

The last line gives the error:
```
src/domain/servers.ts:51:30 - error TS2339: Property 'enum' does not exist on type 'ZodBranded<ZodEnum<["offline", "online"]>, "AgentStatus">'.

51 console.log(AgentStatusBrand.enum.offline);
```

**Comment by colinhacks** [comment]
Calling `.brand()` wraps the schema in a ZodBranded instance. You'll need to unwrap to access the inner schema:

```ts
export const AgentStatusBrand = z
	.enum(["offline", "online"] as const)
	.brand<"AgentStatus">();

AgentStatusBrand.unwrap().enum.offline;
```

This is a good note though, and I'm looking into ways to avoid this in Zod 4.
