### ISSUE TITLE
z.merge not inferring types properly

### ISSUE THREAD

**Issue by zwhitchcox** [colinhacks/zod#3480]
The `CombinedType` in this code:

```ts
import { z, ZodObject } from 'zod'

const schema1 =  z.object({ providerId: z.string() })
const schema2 = z.object({ serviceId: z.string() })
const schema3 =  z.object({ date: z.date() })

function combineSchemas<
	T extends ZodObject<any, any, any>,
	U extends ZodObject<any, any, any>,
	V extends ZodObject<any, any, any>,
>(s1: T, s2: U, s3: V) {
	return s1.merge(s2).merge(s3)
}
const CombinedSchema = combineSchemas(schema1, schema2, schema3)
type CombinedType = z.infer<typeof CombinedSchema>
```

is not properly inferring the type. It should be 

```ts
{
  providerId: string;
  serviceId: string;
  date: Date
}
```

But the inferred type is:

```
type CombinedType = {
    [x: string]: any;
    serviceId?: unknown;
    date?: unknown;
}
```

[See Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgLwDRwFoQCYHkBGAVgKYDG8AvnAGZQQhwDkyOjAUG6RAHYDO8vUgAtiIAIYBGOAF44KAHQQiZGAAokYOgDdg2YlACS2AFwL+UYNwDmqgJRwKtzj35xBI8QCYZCpSXLqbvo6pMRGpsjy5pY29o7OfALComIAzD6+ygFI2GIwxBHyufl2Dk5s1ACu3OTAPHBcIPiWxADKyeK8ADxsAJAAKnDEAB753Ni8mDgE-jBdYtwAnugLy3CrAHyofQCqQ6PE45NYeFlzqytLl4tbfQBq+2MTU6ez81frH5vbG6q8EqZ+uheJ5TDtgalTHd7Ag+lBiDBKlBuG4JPIQPorMQ-p5bOjMdjeKknBQEq4AML0ZrcYjYdoeMQ+RrUtodMS8P5siTAtmeHkM4lsGCLMDEOCUpotbD9EVi2SRSzUfRdYWiiDUcVUqX0lIbNhAA)

**Comment by zwhitchcox** [comment]
Was able to get this to work with this code:

import { z, ZodObject } from 'zod'

const schema1 =  z.object({ providerId: z.string() })
const schema2 = z.object({ serviceId: z.string() })
const schema3 =  z.object({ date: z.date() })

type extend3Shapes<A extends object, B extends object, C extends object> = {
	[K in keyof A as K extends keyof B
		? never
		: K extends keyof C
			? never
			: K]: A[K]
} & {
	[K in keyof B]: B[K]
} & {
	[K in keyof C]: C[K]
}

function combineSchemas<
	T extends ZodObject<any, any, any>,
	U extends ZodObject<any, any, any>,
	V extends ZodObject<any, any, any>,
	A1 extends T['shape'],
	A2 extends U['shape'],
	A3 extends V['shape'],
>(s1: T, s2: U, s3: V) {
	return s1.merge(s2).merge(s3) as ZodObject<
		extend3Shapes<A1, A2, A3>,
		T['_def']['unknownKeys'],
		T['_def']['catchall']
	>
}

const CombinedSchema = combineSchemas(schema1, schema2, schema3)
type CombinedType = z.infer<typeof CombinedSchema>


[See Updated Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgLwDRwFoQCYHkBGAVgKYDG8AvnAGZQQhwDkyOjAUG6RAHYDO8vUgAtiIAIYBGOAF44KAHQQiZGAAokYOgDdg2YlACS2AFwL+UYNwDmqgJRwKtzj35xBI8QCYZCpSXLqbvo6pMRGpsjy5pY29o7OfALComIAzD6+ygFI2GIwxBHyufl2Dk5sMACeYMRwxAAe+dzYqQDKQmI1vAA8AIJ1jcTNvHB+KugAQgNN2CNj5OgAwtNDs6NZMAB8PghsAJAA2gDScJZwANbElRDUcP1iIycNMyOX17cT+3sA-HDcxFp9F9TE9BsMLlcbnBFl8fn8AUC9kiQQBdUy9Y4othUABkiH2x1O3Ah7zgEzRZMx2LgeN2hxOZzeUMWFMWVIoHGoAFduORgDw4FwQPhLMRWslxD19gAVFbgrB4DbdMTcSroFVquAazaofYAVTlawVBH8MGVqvVFq1qp1+wAaoaRsalRrLZrtbq9r0pM9ViNpQdGLwOjVGCjPb1vL7wXrA8HOsQwxH0tG1na4yHE+G2JtVLwJKZpeheJ5THri6lTHb7HSoMQYFyoMT8-IQPorMQ855bK3253eKl7A9MDgTSpul9U21Mz1vehI-PUrakQHGAB9PTUMOBnnnbgQADu3COV14Sa+q43xC3KMDpDywjEABsn2H9ptsRwuIlofQRf9sHFDwxB8IV-zFCUHjzSCJGLSDPDg4DBwqapakWP9RWwaVUJ8SJLGofRuiqGpmQwgCgJSD8gA)

Going to leave this open just to make sure it's the intended behavior

**Comment by colinhacks** [comment]
Things get weird when you call methods in generic contexts. The generic `T` "collapses" to its type constraint (`ZodObject<any,any,any>`) when you do something that requires it's type to be explicitly instantiated. This is a TypeScript limitation, and it's usually better to write your return type explicitly. 

Here's a more concise version that uses Zod's own utilities:

```ts
import { z, ZodObject, objectUtil, util } from "./src";

const schema1 = z.object({ providerId: z.string() });
const schema2 = z.object({ serviceId: z.string() });
const schema3 = z.object({ date: z.date() });

function combineSchemas<
  T extends ZodObject<any, any, any>,
  U extends ZodObject<any, any, any>,
  V extends ZodObject<any, any, any>
>(
  s1: T,
  s2: U,
  s3: V
): ZodObject<
  util.flatten<
    objectUtil.extendShape<
      objectUtil.extendShape<T["shape"], U["shape"]>,
      V["shape"]
    >
  >
> {
  return s1.merge(s2).merge(s3);
}
const CombinedSchema = combineSchemas(schema1, schema2, schema3);
type CombinedType = z.infer<typeof CombinedSchema>;
```

**Comment by zwhitchcox** [comment]
So, fyi if anyone finds this, this is what I ended up doing:

```ts
import {
  z ,
	type AnyZodObject,
  type ZodObject,
 type util
} from 'zod'

type ShapesCombine<
	T extends AnyZodObject[],
> = T extends [infer A extends AnyZodObject, ...infer B extends AnyZodObject[]]
	? A['shape'] & ShapesCombine<B>
	: T extends AnyZodObject ? T : {}

function combineSchemas<U extends AnyZodObject[]>(arr: U): ZodObject<util.flatten<ShapesCombine<U>>> {
	return arr.reduce((acc, step) => {
		return acc.merge(step)
	}, z.object({})) as any
}

const combined = combineSchemas([
	z.object({ hello: z.string() }),
	z.object({ world: z.string() }),
	z.object({ foo: z.string() }),
	z.object({ bar: z.string() }),
] as const)
```

[Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwFBzgLzgGiQSBgTzAFM4BBAO3wC0IATAeQCMArIgYxm1QOLhoZbtOKHiQCuMYABskAXzgAzKBBBwA5GjpqkSUXADKACwCGxAM4BhFY2DkiAHlwAVOEQAeMIuVpmylfkysHADaALrYAHxwALxwLu6e3r7BtgpEUGSuHl4+ftR0gUKYcAB0ZanpcABCWYm5FPkCQTBhobgA-GTBamYmxGqhcABkBn1Elta2DlURuABccbU5vg0BghxwnS4LCLI6CmLkHMAQ5HBsk3b6bIZEIMZm9gCqS0l5a81hEQAUxlBQCyeAEoFh8hPYJNISgopMYYIl7EZTOMrCAbHZnhEsYhcFAiDAxFAzn8oCU8bQxGwiN9fmw2MUzJ4wECYlFkDgcHiCUS4MY6SUQOkAObUxlEZm4WTFNAlCDrGDfXZAlkPXmUOQ6C7kRnnS5EWgxXVoqbXW73MzfYK4GVy5qKuC3KRSCALGWMqC2IXfFmyIHYHA2+X2gDu0CktFdJXdnu9cF9-sDdoQiggLvQUZgHvIXp9futsqDycYf0j0ezsfjSEGqq1jKBOiAA)

**Comment by Vipin382** [comment]
i tried your way @zwhitchcox  but it didn't work since in my case i want to make a single instance of hook form from two different zod schema and i tried and tried but finally i came up with this solution, i am putting it here if someone needs it for future for combining two zod schmas to create one single form instance which preserve the types 


`import { useForm, UseFormReturn, DefaultValues } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z, type ZodObject } from "zod";

type DeepMerge<T, U> = {
    [K in keyof T | keyof U]: K extends keyof T & keyof U
    ? T[K] extends object
    ? U[K] extends object
    ? DeepMerge<T[K], U[K]>
    : T[K]
    : T[K]
    : K extends keyof T
    ? T[K]
    : K extends keyof U
    ? U[K]
    : never;
};

function useMergedForm<
    Schema1 extends ZodObject<any, any, any>,
    Schema2 extends ZodObject<any, any, any>
>(
    schema1: Schema1,
    schema2: Schema2,
    defaultsValues: DefaultValues<z.infer<Schema1> & z.infer<Schema2>>
) {
    type MergedFormData = DeepMerge<
        z.infer<typeof schema1>,
        z.infer<typeof schema2>
    >;

    const mergedSchema = z.intersection(schema1, schema2)

    const formInstance: UseFormReturn<MergedFormData> = useForm<MergedFormData>({
        resolver: zodResolver(mergedSchema),
        defaultValues: defaultsValues,
        mode: "onSubmit",
    });

    return { formInstance, mergedSchema };
}

export default useMergedForm;
`
