### ISSUE TITLE
Looking for a way to reuse the same schema with `.merge`

### ISSUE THREAD

**Issue by Nxtivision** [colinhacks/zod#3481]
Hi,
Hope you're fine!

I would like some guidance here, because I did not find any answer through multiple researches, and it is maybe a bug. I would like to know if I'm doing wrong or if a bug is  likely to be suspected here or inside nestjs/swagger

Here are my schemas:

```typescript
// Some utils I would like to reuse

export const stringToDateString = z
	.string()
	.refine(val => !Number.isNaN(Date.parse(val)), {
		message: 'Invalid datetime string',
	})
	.transform(val => new Date(val).toISOString());

export const dateToDateString = z.date().transform(date => date.toISOString());

export const dateToDatelike = z.union([stringToDateString, dateToDateString]);

export const startAndEndDates = z
	.object({
		start_date: dateToDatelike,
		end_date: dateToDatelike,
	})
	.refine(
		({ start_date, end_date }) =>
			isBefore(new Date(start_date), new Date(end_date)),
		{
			message: 'La date de début dépasse la date de fin',
		}
	);
	
// ##### Phase schema #####

const base = z.object({
	// Some properties
});

export const PhaseSchema = base.merge(startAndEndDates.innerType());

// ##### Cycle Schema #####

const base = z.object({
	// Some properties
});

export const CycleSchema = base.merge(startAndEndDates.innerType());
```

If I'm doing this, I'm getting this error:

`Error: A circular dependency has been detected (property key: "start_date"). Please, make sure that each side of a bidirectional relationships are using lazy resolvers ("type: () => ClassType").`

This error is generated by `@nestjs/swagger`, but I'm not sure this is related, and I think the root cause is my schema.

It's worth noting that I also tried using `z.lazy()`, according to the mentionned error, in many ways but **without success**.

Is anyone can help here ? It could be interesting to have this kind of usecase directly in the documentation 😄 

Have a nice day

**Comment by colinhacks** [comment]
The "lazy resolvers" they're talking about isn't `z.lazy()`. That error is coming from Nest (I think) not Zod. I'm not familiar with Nest, but this seems to be a bug in their cycle detection. Or if you're using @anatine/zod-nestjs it may be a bug there.
