### ISSUE TITLE
Wrong default branch in github actions files

### ISSUE THREAD

**Issue by Jayllyz** [colinhacks/zod#3505]
According to the contribution guide : https://github.com/colinhacks/zod/blob/3156ccac0f38f9f13b43b89af69f4f3defc98e74/CONTRIBUTING.md?plain=1#L3

`main` is now the default branch, so `master` needs to be replaced in workflows files.

see: https://github.com/colinhacks/zod/blob/3156ccac0f38f9f13b43b89af69f4f3defc98e74/.github/workflows/test.yml#L6

I can open a PR if needed.

**Comment by colinhacks** [comment]
Fixed, thanks!
