### ISSUE TITLE
IPv6 validation error

### ISSUE THREAD

**Issue by avegao** [colinhacks/zod#3512]
IPv6 validation fails when the last two parts of the IPv6 are compressed, both when one or both are omitted. It does not happen if it is any other part. I have checked the regex you use in https://github.com/colinhacks/zod/blob/1247caf58d1c189155bd04c068be1c758ab77c1c/src/types.ts#L613 and I have also checked it in external tools and the zod behavior is reproduced.

```ts
const ip = '2001:4888:50:ff00:500:d::';
const schema = z.string().ip();
const { success } = schema.safeParse(ip); // false
```

```ts
const ip = '2001:4888:50:ff00:500:d:0:0';
const schema = z.string().ip();
const { success } = schema.safeParse(ip); // true
```

```ts
const ip = '2001:4888:50:ff00::d:0:0';
const schema = z.string().ip();
const { success } = schema.safeParse(ip); // true
```

**Comment by ffraenz** [comment]
I can confirm this issue. In my logs I found that `z.string().ip().safeParse('2a00:116a:105:2e70::')` results in "Invalid ip", although being perfectly fine. Thank you for reporting it and proposing a fix!
