### ISSUE TITLE
Zod error always blank in latest version of Chrome

### ISSUE THREAD

**Issue by agusterodin** [colinhacks/zod#3516]
I am using Zod inside Redux Toolkit Query to validate fetched data.

In the latest version of Chrome, the Zod error is always blank (only in this use-case).

Browser that isn't working as expected:
- Chrome 125.0.6422.77 (arm64, macOS)

![Screenshot 2024-05-22 at 8 02 28 PM](https://github.com/colinhacks/zod/assets/10248395/f3acdfcf-8de1-4644-bfa7-6f27f71f5b55)

Browsers that work as expected:
- Chrome 124.0.6367.209 (arm64, macOS)
- Safari 17.4.1 (19618.1.15.11.14)

![Screenshot 2024-05-22 at 8 02 38 PM](https://github.com/colinhacks/zod/assets/10248395/ed537a56-003b-4168-b7d7-0f97a194304d)

Minimal reproduction:
https://github.com/agusterodin/zod-error-not-appearing-in-chrome-bug/tree/main

**Comment by petequoterite** [comment]
I'm having this issue as well. I believe it has something to do with the way ZodError is put together.
I noticed that `zodError.hasOwnProperty('message')` is false., so i believe chrome thinks it doesn't have a message to display.

Interestingly if you cast the error to a string and log that you get the actual message as it used to because the toString function does return the message.

**Comment by agusterodin** [comment]
Good catch.

Out of curiosity, are you experiencing the problem while using in conjunction with Redux Toolkit Query? If not, what is the context?

I wasn’t able to recreate the bug on more trivial uses of the parse function.

**Comment by petequoterite** [comment]
Yep i'm using RTKQuery as well. But i don't think it matters? If you create a new ZodError in the console, you get the same output as far as i can see

Just running this code
```
try {
    z.string().parse(123);
} catch (e) {
    console.log(e);
}
```
outputs this
![Screenshot 2024-05-23 at 1 59 04 PM](https://github.com/colinhacks/zod/assets/137016715/3546bfae-048e-429c-b098-ed4910fce6eb)

But if instead i log `console.log(e.messsage);` then i get the message
![Screenshot 2024-05-23 at 1 59 56 PM](https://github.com/colinhacks/zod/assets/137016715/27796497-af66-464e-af9f-3f9685ef1d9b)

Interestingly if I log toString `console.log(e.toString())` then i get the same as above
![Screenshot 2024-05-23 at 1 59 56 PM](https://github.com/colinhacks/zod/assets/137016715/27796497-af66-464e-af9f-3f9685ef1d9b)

So i believe chrome has changed the way they display errors that are logged directly

**Comment by petequoterite** [comment]
If i just throw a regular (non-zod) error, chrome still displays the message as you'd expect - so there's something wrong with ZodError and i think it's that `message` is implemented as a `get` rather than using the inherited property

**Comment by CodeFromTheEmpty** [comment]
Experiencing the same error. 
Also same behaviour in console for the different test mentioned by @petequoterite 
try {
    z.string().parse(123);
} catch (e) {
    console.log(e);
}

How to handle this?

**Comment by justinline** [comment]
Can also reproduce, using rtkquery with zod and I get the following in arc browser: 
<img width="306" alt="Screenshot 2024-06-07 at 20 25 28" src="https://github.com/colinhacks/zod/assets/6620797/6388ade6-2d16-4aa8-aec6-ad78572dcdba">

**Comment by petequoterite** [comment]
For now i am using redux middleware to look specifically for `ZodError`s and manually logging `error.message` to the console
```
if (action.error.name === 'ZodError') {
    // log to console - this gets around the issue where chrome doesn't print the full message for zod errors
    // see https://github.com/colinhacks/zod/issues/3516
    // eslint-disable-next-line no-console
    console.error(action.error.message);
```

This works for logic within redux such as api calls, but not for anything outside which we do occasionly do :(

**Comment by CodeFromTheEmpty** [comment]
Anything new?
Cant implement zod with this bug.

**Comment by subalee** [comment]
Same issue but with tanstack/react-query however its not related to any solutions like this.

Its issue between zod - chrome

other browser such as safari or firefox

**Comment by agusterodin** [comment]
Appears to no longer be an issue
