### ISSUE TITLE
zod safeparse not working with nextjs server action useFormState hok

### ISSUE THREAD

**Issue by shahbaz4783** [colinhacks/zod#3527]
Im using zod for velidation, the form doesnt send correct data to server action function. it always returns **invalid fields**

This is form component:

```ts
'use client';

import * as z from 'zod';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import {
	Form,
	FormControl,
	FormField,
	FormItem,
	FormLabel,
	FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { loginFormInput } from '@/constants/form';
import Link from 'next/link';
import { loginSchema } from '@/validators/auth.schema';
import FormError from '../feedback/FormError';
import FormSuccess from '../feedback/FormSuccess';
import { loginAction } from '@/actions/auth/login.action';
import { useSearchParams } from 'next/navigation';
import { FaArrowLeft } from 'react-icons/fa';
import Submit from '../buttons/submit';
import { useFormState } from 'react-dom';

const LoginForm = () => {
  const [formState, formAction] = useFormState(loginAction, {
    error: '',
    success: '',
  });

  const searchParams = useSearchParams();
  const urlError =
    searchParams.get('error') === 'OAuthAccountNotLinked' &&
    'Please sign in with the same account you used originally.';

  const form = useForm<z.infer<typeof loginSchema>>({
    resolver: zodResolver(loginSchema),
    defaultValues: {
      email: '',
      password: '',
    },
  });

  return (
    <>
      <Form {...form}>
        <Link href={'/login'}>
          <FaArrowLeft size={20} />
        </Link>

        <form action={formAction} className="flex flex-col gap-4">
          {loginFormInput.map((data) => (
            <FormField
              key={data.id}
              control={form.control}
              name={data.name}
              render={({ field }) => (
                <FormItem>
                  <FormLabel>{data.label}</FormLabel>
                  <FormControl>
                    <Input
                      className="border-none bg-slate-100 py-6 shadow-none"
                      type={data.type}
                      placeholder={data.placeholder}
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          ))}
          <Link
            className="text-right text-sm font-semibold text-slate-500 hover:underline"
            href={'/forgot-password'}
          >
            Forgot Password?
          </Link>
          <FormError message={formState.error || urlError} />
          <FormSuccess message={formState.success} />
          <Submit title="Login" loadingTitle="Logging In..." />
        </form>
      </Form>
    </>
  );
};

export default LoginForm;
```

This is server action

```ts
'use server';
import { signIn } from '@/auth';
import { getUserByEmail } from '@/data/user';
import { sendVerificationMail } from '@/lib/mail';
import { generateVerificationToken } from '@/lib/tokens';
import { DEFAULT_LOGIN_REDIRECT } from '@/routes';
import { loginSchema } from '@/validators/auth.schema';
import { AuthError } from 'next-auth';
import * as z from 'zod';

interface LoginFormState {
  error?: {};
  success?: {};
}

export const loginAction = async (
  formState: LoginFormState,
  formData: z.infer<typeof loginSchema>,
): Promise<LoginFormState> => {
  const validateFields = loginSchema.safeParse(formData);
  if (!validateFields.success) return { error: 'Invalid Fields!' };

  const { email, password } = validateFields.data;

  const existingUser = await getUserByEmail(email);

  if (!existingUser || !existingUser.email || !existingUser.password) {
    return { error: 'Email doesnt exist!' };
  }

  if (!existingUser.emailVerified) {
    const verificationToken = await generateVerificationToken(
      existingUser.email,
    );
    await sendVerificationMail(
      verificationToken.token,
      verificationToken.email,
      existingUser?.name as string,
    );
    return { success: 'Confirmation email sent' };
  }

  try {
    await signIn('credentials', {
      email,
      password,
      redirectTo: DEFAULT_LOGIN_REDIRECT,
    });
  } catch (error) {
    if (error instanceof AuthError) {
      switch (error.type) {
        case 'CredentialsSignin':
          return { error: 'Invalid credentials' };

        default:
          return { error: 'Something went wrong' };
      }
    }
    throw error;
  }
  return { success: 'Email sent successfully!' };
};

```

This is schema
```ts
export const loginSchema = z.object({
	email: z.string().email({ message: 'Must be a valid email' }),
	password: z.string().min(3, {
		message: 'Password is required',
	}),
});

```

**Comment by callmedukey** [comment]
React hook form = client side 

You're getting no data on the server action because you are using "actions" on the form and react hook form ain't passing anything to the server.

Handlesubmit from react-hook-form needs to be passed to onSubmit.

**Comment by Saiguna7** [comment]
> Im using zod for velidation, the form doesnt send correct data to server action function. it always returns **invalid fields**
> 
> This is form component:
> 
> ```ts
> 'use client';
> 
> import * as z from 'zod';
> import { useForm } from 'react-hook-form';
> import { zodResolver } from '@hookform/resolvers/zod';
> import {
> 	Form,
> 	FormControl,
> 	FormField,
> 	FormItem,
> 	FormLabel,
> 	FormMessage,
> } from '@/components/ui/form';
> import { Input } from '@/components/ui/input';
> import { loginFormInput } from '@/constants/form';
> import Link from 'next/link';
> import { loginSchema } from '@/validators/auth.schema';
> import FormError from '../feedback/FormError';
> import FormSuccess from '../feedback/FormSuccess';
> import { loginAction } from '@/actions/auth/login.action';
> import { useSearchParams } from 'next/navigation';
> import { FaArrowLeft } from 'react-icons/fa';
> import Submit from '../buttons/submit';
> import { useFormState } from 'react-dom';
> 
> const LoginForm = () => {
>   const [error, seterror] = useState( "")
>   const [success, setsuccess] = useState( "")
>const [ispending, startTransition] = useTransition();
>   const searchParams = useSearchParams();
>   const urlError =
>     searchParams.get('error') === 'OAuthAccountNotLinked' &&
>     'Please sign in with the same account you used originally.';
>    const formaction=(values:z.infer<typeof loginSchema>)=>{ seterror("") 
>setsuccess("")
> startTransition(() => { 
> loginAction (values).then(data=>{
>if(data){
>if(data.success){
>form.reset()
>setsuccess(data.success)
>}else{
>seterror(data.error)
>}
>}
>})        
>})
> }
>   const form = useForm<z.infer<typeof loginSchema>>({
>     resolver: zodResolver(loginSchema),
>     defaultValues: {
>       email: '',
>       password: '',
>     },
>   });
> 
>   return (
>     <>
>       <Form {...form}>
>         <Link href={'/login'}>
>           <FaArrowLeft size={20} />
>         </Link>
> 
>         <form onSubmit={form.handleSubmit(formaction)} className="flex flex-col gap-4">
>           {loginFormInput.map((data) => (
>             <FormField
>               key={data.id}
>               control={form.control}
>               name={data.name}
>               render={({ field }) => (
>                 <FormItem>
>                   <FormLabel>{data.label}</FormLabel>
>                   <FormControl>
>                     <Input
>                       className="border-none bg-slate-100 py-6 shadow-none"
>                       type={data.type}
>                       placeholder={data.placeholder}
>                       {...field}
>                     />
>                   </FormControl>
>                   <FormMessage />
>                 </FormItem>
>               )}
>             />
>           ))}
>           <Link
>             className="text-right text-sm font-semibold text-slate-500 hover:underline"
>             href={'/forgot-password'}
>           >
>             Forgot Password?
>           </Link>
>           <FormError message={formState.error || urlError} />
>           <FormSuccess message={formState.success} />
>           <button type="submit"
>          disabled={isPending]
>    >
>{isPending?'loading....':' Submit'
>
></button>
>         </form>
>       </Form>
>     </>
>   );
> };
> 
> export default LoginForm;
> ```
> 
> This is server action
> 
> ```ts
> 'use server';
> import { signIn } from '@/auth';
> import { getUserByEmail } from '@/data/user';
> import { sendVerificationMail } from '@/lib/mail';
> import { generateVerificationToken } from '@/lib/tokens';
> import { DEFAULT_LOGIN_REDIRECT } from '@/routes';
> import { loginSchema } from '@/validators/auth.schema';
> import { AuthError } from 'next-auth';
> import * as z from 'zod';
> 
> interface LoginFormState {
>   error?: {};
>   success?: {};
> }
> 
> export const loginAction = async (
>   values: z.infer<typeof loginSchema>,
> ) => {
>   const validateFields = loginSchema.safeParse(formData);
>   if (!validateFields.success) return { error: 'Invalid Fields!' };
> 
>   const { email, password } = validateFields.data;
> 
>   const existingUser = await getUserByEmail(email);
> 
>   if (!existingUser || !existingUser.email || !existingUser.password) {
>     return { error: 'Email doesnt exist!' };
>   }
> 
>   if (!existingUser.emailVerified) {
>     const verificationToken = await generateVerificationToken(
>       existingUser.email,
>     );
>     await sendVerificationMail(
>       verificationToken.token,
>       verificationToken.email,
>       existingUser?.name as string,
>     );
>     return { success: 'Confirmation email sent' };
>   }
> 
>   try {
>     await signIn('credentials', {
>       email,
>       password,
>       redirectTo: DEFAULT_LOGIN_REDIRECT,
>     });
>   } catch (error) {
>     if (error instanceof AuthError) {
>       switch (error.type) {
>         case 'CredentialsSignin':
>           return { error: 'Invalid credentials' };
> 
>         default:
>           return { error: 'Something went wrong' };
>       }
>     }
>     throw error;
>   }
>   return { success: 'Email sent successfully!' };
> };
> ```
> 
> This is schema
> 
> ```ts
> export const loginSchema = z.object({
> 	email: z.string().email({ message: 'Must be a valid email' }),
> 	password: z.string().min(3, {
> 		message: 'Password is required',
> 	}),
> });
> ```
now i made some changes use it now it will work
