### ISSUE TITLE
typescript vs "plain javascript" in README

### ISSUE THREAD

**Issue by websocket98765** [colinhacks/zod#354]
Zod looks great. I tried to use it, but it appears it's not distributed as JavaScript, so it didn't work in my project. 

The ReadMe says `Plain JavaScript: works in browsers and Node.js` and also that it has [typescript requirement](https://github.com/colinhacks/zod#typescript-requirements), which seems at odds with the first statement.

Would you consider creating a JavaScript build that could be imported, so it works directly in JavaScript projects too please?

**Comment by colinhacks** [comment]
Zod absolutely is distributed as plain JavaScript — basically everything on `npm` is. Zod works just fine in a plain Node.js environment. Have you tried it?

Those requirements only apply if you're using it in a TypeScript environment. You're right, that could be confusing.

**Comment by websocket98765** [comment]
Thanks for the clarification.
