### ISSUE TITLE
object.props "required" but z.infer<T> returns  "optional" type?

### ISSUE THREAD

**Issue by 3fatty** [colinhacks/zod#3544]
deps:
typescript@4.9.4
zod@3.23.8

code:
<img width="466" alt="image" src="https://github.com/colinhacks/zod/assets/14211764/228e391b-1a1f-4018-b1a7-30aec76826fa">

ps: the "parse" & "safeParse" method works well

**Comment by maxmarchuk** [comment]
what does your tsconfig.json look like?
I noticed my schemas were doing the same if either `compilerOptions` contains `"strict": true` or no strict property, or also if `"strictNullChecks": false` was set.

**Comment by 3fatty** [comment]
> what does your tsconfig.json look like? I noticed my schemas were doing the same if either `compilerOptions` contains `"strict": true` or no strict property, or also if `"strictNullChecks": false` was set.

ah, you'r right 👍
I didn't realize that 
sorry and thank you
