### ISSUE TITLE
Feature Request: Autoscroll to Input Field on Validation Error

### ISSUE THREAD

**Issue by PrayanshParmar** [colinhacks/zod#3559]
#### Description

I would like to propose a new feature for the Zod library: autoscrolling to the input field when a validation error occurs. This enhancement aims to improve user experience by automatically directing users to the specific form field that has failed validation, thereby reducing confusion and enhancing usability.

#### Motivation

When a form submission fails due to validation errors, especially in lengthy forms, users often find it challenging to identify which specific field contains the error. Implementing an autoscroll feature would address this issue by smoothly scrolling the user to the erroneous input field and focusing on it. This makes the error more visible and the form more user-friendly.

#### Proposed Implementation

1. **Modify the `ZodError` class**: Add a new method to handle the autoscroll functionality.
2. **Scroll to First Error**: On validation failure, scroll to the first erroneous input field and focus on it.
3. **Integration with Form Libraries**: Ensure compatibility with popular form handling libraries like `react-hook-form`.

Here is a conceptual example of how the method might look:

```typescript
export class ZodError<T = any> extends Error {
  issues: ZodIssue[] = [];

  // Existing methods...

  // New method to scroll to the first error
  scrollToError(form: HTMLFormElement) {
    if (this.issues.length === 0) return;

    const firstIssue = this.issues[0];
    const fieldName = firstIssue.path.join(".");
    const input = form.querySelector(`[name="${fieldName}"]`);

    if (input) {
      input.scrollIntoView({ behavior: "smooth" });
      (input as HTMLInputElement).focus();
    }
  }

  // Existing methods...
}
```

#### Request for Guidance and Authorization
I am very interested in contributing this feature to the Zod library. I would appreciate any guidance or suggestions on how to best implement this feature according to the project's standards. Additionally, I would like to request authorization to proceed with developing this feature.

**Comment by digimuza** [comment]
I don’t think that this should be part of Zod; it implicitly ties Zod to the frontend, while Zod is used in the backend quite heavily.

This might help you
```ts
export class ScrollToError extends ZodError<T = any> {
  scrollToError(form: HTMLFormElement) {
    if (this.issues.length === 0) return;

    const firstIssue = this.issues[0];
    const fieldName = firstIssue.path.join(".");
    const input = form.querySelector(`[name="${fieldName}"]`);

    if (input) {
      input.scrollIntoView({ behavior: "smooth" });
      (input as HTMLInputElement).focus();
    }
  }
}
```
