### ISSUE TITLE
Wrong default error message for uuid validation

### ISSUE THREAD

**Issue by jordanworner** [colinhacks/zod#356]
I'm getting the following default error message for UUID errors using 3.0.0-alpha.30

`[ { "validation": "email", "code": "invalid_string", "message": "Invalid email", "path": [ "id" ] } ]`

looks like the validation is incorrectly set when adding an issue for UUID validation errors.

```js
if (this._def.isUUID && !uuidRegex.test(ctx.data)) {
  ctx.addIssue({
    validation: "email",
    code: ZodIssueCode.invalid_string,
    message: this._def.isUUID.message,
  });
}
```

**Comment by colinhacks** [comment]
Good catch 😬  Fixed in alpha.31.
