### ISSUE TITLE
Adding a `.required` helper on object (v3)

### ISSUE THREAD

**Issue by fabien0102** [colinhacks/zod#357]
Hello,

Since we have an amazing `z.object().partial()` helper (https://github.com/colinhacks/zod/tree/v3#partial) to mimic the typescript `Partial<>` util, this could be nice have the symetrical `Required<>` util.

Ideally, I would like something like this:
### `.required`

Inspired by the built-in TypeScript utility type [Required](https://www.typescriptlang.org/docs/handbook/utility-types.html#requiredtype), the `.required` method makes all properties required.

Starting from this object:

```ts
const user = z.object({
  username: z.string().optional(),
});
// { username?: string | undefined }
```

We can create a required version:

```ts
const requiredUser = user.required();
// { username: string }
```

**Comment by colinhacks** [comment]
Great idea, this has been on my to-do list for a long time. Now available in alpha.32, upgrade to the latest version to access this: `npm install zod@next`

**Comment by fabien0102** [comment]
Just amazing! Thanks for your reactivity, this was my last missing for a typescript to zod generator #teasing 😁
