### ISSUE TITLE
Clearer way to have optional objects that use their key's defaults

### ISSUE THREAD

**Issue by WesCossick** [colinhacks/zod#358]
Take, for example, the following TypeScript interface, which describes what the parsed and validated version of a config schema should look like:

```ts
interface ParsedConfig {
    foo: {
        one: string;
        two: string;
    };
    bar: {
        three: string;
        four: string;
    };
}
```

Take, also, the following type, which describes what the user could provide to customize the configuration of a program:

```ts
type UserConfig = undefined | {
    foo?: {
        one?: string;
        two?: string;
    };
    bar?: {
        three?: string;
        four?: string;
    };
}
```

To accomplish this with Zod, the schema must look like:

```ts
const schema = z.object({
    foo: z.object({
        one: z.string().default('1'),
        two: z.string().default('2'),
    }).default({}),
    bar: z.object({
        three: z.string().default('3'),
        four: z.string().default('4'),
    }).default({}),
}).default({});
```

Note the use of `.default({})` throughout, which forces Zod into using the default values of the keys within the objects. Without `.default({})`, Zod would throw an error indicating that the objects were required if one of the objects was missing entirely. If you try to use `.optional()` instead, then you could end up with an object that won't fit the `ParsedConfig`, like:

```ts
{
    foo: undefined,
    bar: undefined,
}
```

As a new user, this took quite a bit of trial-and-error to discover this. To help make it more clear as to how to accomplish this, along with making it more obvious what's going on whenever someone reads this code in the future, it may be useful to add a built-in function that accomplishes what `.default({})` accomplishes.

**Comment by colinhacks** [comment]
I understand your frustration but I don't really think there's anything actionable for me to do here. I'm not likely to add a method that's equivalent to `.default({})` becauase I don't know what I'd call it and `.default({})` isn't that verbose anyway. If you can think of an API that would make this config-parsing problem less painful, feel free to propose it here. Closing for now.

**Comment by WesCossick** [comment]
> `.default({})` isn't that verbose anyway

The problem really isn't that it's verbose, more that it's just unclear. Looking at the code sample above without all the context I provided would likely cause the reader to question why `.default({})` is present and what its purpose is.

What about introducing `.useDefaultsWithinObject()` or just `.useDefaultsWithin()`? That'd change the code sample I provided to:

```ts
const schema = z.object({
    foo: z.object({
        one: z.string().default('1'),
        two: z.string().default('2'),
    }).useDefaultsWithin(),
    bar: z.object({
        three: z.string().default('3'),
        four: z.string().default('4'),
    }).useDefaultsWithin(),
}).useDefaultsWithin();
```

I think this change makes it decently more clear what's going on. Thoughts?

**Comment by colinhacks** [comment]
Not a big fan. Seems like your main frustration here is that `.default({})` was necessary in the first place, and adding a new method doesn't solve that problem. This is just one of those scenarios where Zod's syntax is a little awkward; it's inevitable with a general-purpose tool.

**Comment by WesCossick** [comment]
> Seems like your main frustration here is that `.default({})` was necessary in the first place

I wouldn't say that's my main frustration, or even a frustration at all. I'm simply proposing a new function that, in cases where users currently write `.default({})`, would make it more clear that the purpose of the function was to instruct Zod to use the default values of the keys within an optional object. Using `.default({})` doesn't clearly indicate that you want to use the default values inside the object, whereas using something like `.useDefaultsWithin()` would make that clear.

A function like `.useDefaultsWithin()` would make users' code more understandable, and would help new users find the correct syntax to instruct Zod to use the default values of an optional object.

Is there a significant downside to adding a function like this?

**Comment by codebrainz** [comment]
Even though this was asking for improvement of it, :+1: for pointing out `.default({})` trick. I couldn't figure this out.
