### ISSUE TITLE
Proper inference of a string to typeof keyof Object

### ISSUE THREAD

**Issue by QuentinLemCode** [colinhacks/zod#3685]
Hello,

I'm starting using Zod and I haven't figure out how  to proper infer string union type from key of an object without using a type guard.

Here is a sample Zod schema : 
```ts
const obj = z.object({
  foo: z.optional(z.boolean()),
  bar: z.optional(z.boolean()),
})
```

And then I have a function that take a string in parameter and I would like to validate it's a key of the object and infer it.

```ts
function checkKey(key: string) {
  if (key in obj.keyof()) {
    // key is still of type 'string', should be 'foo' | 'bar'
}
```

Example stackblitz : https://stackblitz.com/edit/stackblitz-starters-qfu3yi?file=index.ts

Is this something possible without using type guard right now ? Maybe a potential feature ?

**Comment by sunnylost** [comment]
`obj.keyof()` returns a schema, you can't use it as a value, do something like this:
```ts
function checkKey(key: string) {
    const result = obj.keyof().safeParse(key)

    if(result.success) {
        needCorrectType(result.data, {})
    }
}
```
