### ISSUE TITLE
URL validator should be a regex

### ISSUE THREAD

**Issue by pitops** [colinhacks/zod#370]
Ok so, just noticed when i added a url validator that the following passes

```
https://anything
```

this is hardly a URL and `new URL()` is validating too early. 

I think a more refined regex is better than using `new URL()`. I know you had a regex before and you changed just because of a single use case that failed however thats hardly an encouragement to change the way a url is validated.

**Comment by colinhacks** [comment]
> a single use case that failed however thats hardly an encouragement to change the way a url is validated

I agree with this so which is why I'm in favor of leaving it as is. If I'd known about the `new URL()` approach when I first implemented URL validation, I would have absolutely used this approach. Falling back on a built-in language function is always better than trying to wrangle some dense regex.

**Comment by pitops** [comment]
@colinhacks how is this better when validation is passing on such a simple thing - which shouldn't pass as the aformentioned?

I get it - going with something built in but doesn't always means its better
