### ISSUE TITLE
[Question] How can I get field type from Zod object (reflection like)?

### ISSUE THREAD

**Issue by bnayae** [colinhacks/zod#371]
Assuming I'm having the following:

`
export const PersonSchema = z.object({
  email: z.string().email(),
  givenName: z.string(),
  birthday: z.date().optional(),
});
`

Can I check what's the type of specific field (reflection like)?
I'm passing it to a component via property  

`
{ schema: SchemaObjectDef<ZodRawShape> }
`
.i.e.
`
      <Formation
        schema={PersonSchema}
      />
`

Inside the component (Formation) I like to iterate on the schema definitions and get insight on each field.
For example to check whether it email, string, number, etc.

I'm doing kind of pattern matching and creating a dynamic subcomponent within the Formation control.

**Comment by bnayae** [comment]
Shape seem close to what I'm looking for but when I look on the JSON.Stringify of it I don't see the type anywhere.
It seems that it can be inferred from the attribute combination, but it feels a little risky to go on this path.

For Example:

```
export const PersonSchema = z.object({
  email: z.string().email(),
  givenName: z.string(),
  birthday: z.date().optional(),
  score: z.number().positive(),
});
```

Gives the following JSON for the score:

```
	"score": {
		"_def": {
			"minimum": {
				"value": 0,
				"inclusive": false
			},
			"maximum": null,
			"isInteger": false
		}
	}
```

It's hard to figure from it that 'score' is a positive number;

I was expecting to find something under _type, but it's undefined (PersonSchema.shape.score._type).

Do you have any suggestion?

**Comment by bnayae** [comment]
I can use guards on specific ZodType properties in order to identify the right type, but it is fragile to code refactoring, so it's risky.
The following code demonstrate the idea. Yet, I wonder whether there is a better way to handle it?

```
export const PersonSchema = z.object({
  email: z.string().email(),
  avatar: z.string().url().optional().nullable(),
  score: z.number().positive(),
});

const guardZodNumber = (candidate: any): candidate is ZodNumber => {
  let check = candidate;
  do {
    if (check?.int != null) return true;
    check = check?._def?.innerType;
  } while (check);
  return false;
};

const guardZodString = (candidate: any): candidate is ZodString => {
  let check = candidate;
  do {
    if (check?.email != null) return true;
    check = check?._def?.innerType;
  } while (check);
  return false;
}; 

const { score, email, avatar } = PersonSchema.shape;

const isNumber = guardZodNumber(score) ? true : false;
const isEmailString = guardZodString(email) ? true : false;
const isAvatarString = guardZodString(avatar ) ? true : false;
```

**Comment by colinhacks** [comment]
In TypeScript/JavaScript you can check whether a variable is an instance of a given class directly with `instanceof`:


```ts
const guardZodNumber = (candidate: any): candidate is ZodNumber => {
  return candidate instanceof ZodNumber;
};
```

Does that help?
