### ISSUE TITLE
zod import triggers an error in typescript

### ISSUE THREAD

**Issue by uriva** [colinhacks/zod#3737]
tsx v4.19.0
node v22.7.0
zod version: "^3.23.8"

tsconfig:

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "NodeNext",
    "allowImportingTsExtensions": true,
    "moduleResolution": "NodeNext",
    "noEmit": true,
    "esModuleInterop": true,
    "strict": true
  }
}
```

code:

```ts
import { z } from "zod";
```

yields in vscode

```txt
Cannot find module 'zod' or its corresponding type declarations.ts(2307)
```

but running it works

**Comment by Char99s** [comment]
Can you try setting the module to "esnext" and moduleResolution to "bundler"

**Comment by Char99s** [comment]
Can you try it like this?

`{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "allowImportingTsExtensions": true,
    "moduleResolution": "Bundler",
    "noEmit": true,
    "esModuleInterop": true,
    "strict": true
  }
}`

**Comment by uriva** [comment]
actually now it works. weird.

**Comment by bbsimonbb** [comment]
I struck this as well, and it was unpleasant. My project built fine, but I could not get rid of the error in the editor. I had some stray properties outside compilerOptions, that should have been inside. Oops. Might not be anything to do with zod at all, but there was no meaningful error.
