### ISSUE TITLE
values of type number are not accepted when key of NativeEnum is specified as a number type

### ISSUE THREAD

**Issue by 052hide** [colinhacks/zod#3759]
version: v3.23.8

```ts
const STRING_KEY_ENUM = {
  ten: 10,
  twenty: 20,
} as const
z.nativeEnum(STRING_KEY_ENUM) // OK

const NUMBER_KEY_ENUM = {
  10: 10,
  20: 20,
} as const
z.nativeEnum(NUMBER_KEY_ENUM) // Error: Argument of type '{ readonly 10: 10; readonly 20: 20; }' is not assignable to parameter of type 'EnumLike'.

const NUMBER_WITH_QUOTE_KEY_ENUM = {
  '10': 10,
  '20': 20,
} as const
z.nativeEnum(NUMBER_WITH_QUOTE_KEY_ENUM) // Error: Argument of type '{ readonly '10': 10; readonly '20': 20; }' is not assignable to parameter of type 'EnumLike'.
```

While using numbers as keys might not be a common pattern, I would expect consistent behavior regardless of the key type. However, it appears that enums with number keys and stringified number keys lead to different results, which seems unintuitive.

**Comment by sunnylost** [comment]
Because `enum` members can't be numeric. What you're doing is similar to:
```ts
// this is invalid
enum e {
  10,
  20
}
```

A solution is to transform value into string:
```ts
const NUMBER_KEY_ENUM = {
  10: '10',
  20: '20',
} as const
z.nativeEnum(NUMBER_KEY_ENUM) 
```

**Comment by 052hide** [comment]
> A solution is to transform value into string:
const NUMBER_KEY_ENUM = {
  10: '10',
  20: '20',
} as const
z.nativeEnum(NUMBER_KEY_ENUM) 

Thank you for the suggestion.

However, since I am generating my code from an API schema, I am unable to change the value to a string. Do you have any suggestions for handling this scenario without enforcing the value as a string?
