### ISSUE TITLE
[Feature Suggestion] String CSS selector

### ISSUE THREAD

**Issue by prescience-data** [colinhacks/zod#376]
Just a suggestion as it came up as a use-case for me today -

Currently, Zod string has secondary validators such as:

```typescript
z.string().url()
```

Would there be any interest in adding a validator for CSS selectors?

```typescript
z.string().selector()
// or
z.string().css()
```

I ended up using this package temporarily for reference: https://github.com/mdevils/css-selector-parse

## Psuedo example

I'm not super great with regex so this is only a start, but if it's something of interest I think it must be possible to write a matcher...  🤔

```typescript
// Basic start to regex pattern...
const cssRegex: RegExp = /(div|span|section|h1|h2|h3|h4|h5|h6|header|footer|nav){0,1}[#.]{1}[a-zA-Z][a-zA-Z0-9\-_]+/i
  
// Rule definition...
if (this._def.isCss && !cssRegex.test(ctx.data)) {
  ctx.addIssue({
    validation: "css",
    code: ZodIssueCode.invalid_string,
    message: this._def.isCss.message
  })
}

```

**Comment by colinhacks** [comment]
My feeling is that this feature is too niche to merit its own method. This is the first I've heard of someone validating CSS selectors actually. I'll leave this open for a while so people can chime in.

**Comment by WilliamIPark** [comment]
Chiming in:
I've landed here after searching for a way to use zod to validate CSS declarations, eg:
`color: rgba(0,0,0,0.5)`
`color: #FF0000`
`color: red`
`text-align: left`

and so on
