### ISSUE TITLE
Bug: Zod function types not inferred correctly

### ISSUE THREAD

**Issue by GiveMe-A-Name** [colinhacks/zod#3773]
# Detail
Zod types generate function always carry a unknown[] args.
But it's a difference from `(...args: unknown[]) => string;` between `() => string;`

# Code 
```ts
import { z } from "zod";

const myFunction = z.function().returns(z.string());

// MyFunction1 type is (...args: unknown[]) => string;
type MyFunction1 = z.infer<typeof myFunction>;

const f1: MyFunction1 = (x1: string) => "";

// Expect type is () => string;
type MyFunction2 = () => string;

const f2: MyFunction2 = () => "";

```

**Comment by colinhacks** [comment]
This is intentional. Zod chooses the widest possible type since you haven't constrained the arguments in anyway. You can then use `.args()` to specify as needed (or `.args([])` if there are no arguments).
