### ISSUE TITLE
Email validation extremely slow for a given string

### ISSUE THREAD

**Issue by kripod** [colinhacks/zod#378]
First of all, thank you for maintaining this library! It helps a lot with deploying uniform validation logic on both the server and the client.

Using zod v3, I decided to try some of the email addresses mentioned [in this article](https://www.netmeister.org/blog/email.html) and found out that the following string takes around **7 seconds to validate on a MacBook Pro from 2019.** The following string, even though not meant to be used as-is, caused the issue:

```
"put a literal escaped newline here\ <--"@domain
```

I noticed that the issue only happens when `@domain` is used at the end without a TLD (e.g. `.com`). Also, I noticed there’s a substantial loss of performance when specifying >20 chars before `\ `, as seen below in a minimalistic reproduction case:

```ts
import { z } from "zod"; // @3.0.0-alpha.33

const Email = z.string().email();
const prevTime = performance.now();
try {
  Email.parse('"xxxxxxxxxxxxxxxxxxxxxxxxxxx\\ ".x');
} catch {}
console.log(`${performance.now() - prevTime}ms`);
```

A live demo of the issue is [available on CodeSandbox](https://codesandbox.io/s/brave-shockley-ny1q0?file=/src/index.ts).

**Comment by colinhacks** [comment]
Very interesting. Regexes are weird. Just switched over to a new regex that solves this performance problem and #379. Published in alpha.39.

**Comment by kripod** [comment]
Thank you! 😊
