### ISSUE TITLE
z.coerce.number() return unexpected behavior when pass 17 character  

### ISSUE THREAD

**Issue by ayoubjemai** [colinhacks/zod#3782]
When I pass numeric or number that pass 17 character, it adds some number by himself : 

https://zod-playground.vercel.app?appdata=N4IgzgxgFgpgtgQxALhALwHQHsBGArGCAFwApgAdAOwAJqIsYAnCGAOQFc4cnlrN6mLDJU7dGJAJRUAvhJAAaEADcEAG3YwwKANogKNWnQbM2optV7kQARlt37D21ZkgAuoqVMwASyyUUIADMGABMwQAcINJAA

**Comment by sunnylost** [comment]
The issue isn't related to Zod, the number exceeds `Number.MAX_SAFE_INTEGER`.

**Comment by ayoubjemai** [comment]
@sunnylost so the only way to validate numeric string is just do custom validation or with .refine() method ?

**Comment by sunnylost** [comment]
Yes, manual validation is more accurate.
