### ISSUE TITLE
Typescript doesn't realize record can return undefined

### ISSUE THREAD

**Issue by toppsdown** [colinhacks/zod#3785]
Hey there. Just ran into an issue where typescript didn't realize that a key can not exist in a record. It assumes no matter what key you use, it will return the defined type.

```ts
import { z } from "zod"

const testContract = z.record(z.string(), z.number())

type TestType = z.infer<typeof testContract>

const testObject: TestType = {
  hello: 1,
  world: 2,
}

// Typescript has no problem with this, but I'd expect it to 
// complain about the potential for it to be undefined
const x: number = testObject["not in object"]

```

Is this expected behavior?

**Comment by sunnylost** [comment]
Yes, this is TypeScript's default behavior. If you want TypeScript to flag this potential issue, you can enable the [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig/#noUncheckedIndexedAccess) option in your `tsconfig.json`.

**Comment by toppsdown** [comment]
@sunnylost ah got it. Thanks.
