### ISSUE TITLE
Generate class from object schema

### ISSUE THREAD

**Issue by pierreis** [colinhacks/zod#38]
Just like function implementation, it would be interesting to create an object `implement(readonly: bool)` method, that would create an anonymous class having the following functionality:

- Has a `constructor(t?: Type)` that validates the object
- Defines getters and setters (if not readonly)
- May offer `assign(other: Partial<Type>)` or `with(other: Partial<Type>)`, that respectively assign or copies the object and assign values, then runs validation

This would help creating ES6 classes inheriting from this base class, with validation built-in:

```ts
class MyUser extends userSchema.implement() {
    set password(pw: string) {
        this.passwordDigest = hash(pw);
    }
}
```

There are a few unknowns for this: specifically, in case of nested objects that have an implementation, it would be great to return an instance of that implementation rather than a bare object. Some mapping between `ZodType` and implementation could theoretically be passed to Implement.

**Comment by vriad** [comment]
Hi Pierre,

This is a really interesting proposal. I was just considering introducing a `.wrap` method that would let you associate a (properly typed) value with a given schema. This would let you pass around a value AND it's associated validator as a single variable, which is pretty neat.

But your proposal would accomplish the same thing and have a lot more flexibility associated with it, which I like. 

1 & 3 are easy to implement.

2 isn't as easy. I can't figure out how to define getters and setters with generic/dynamic names. The best I could do is a `.set` and `.get` methods that accept a key as their first argument:

```ts
return class StructClass {
  value: T;
  type: ZodObject<T> = validator;
  
  constructor(val: T) {
    this.value = val;
  }

  set = <Key extends keyof T>(key: Key, val: T[Key]) => {
    (this.value as any)[key] = val;
  };

  get = <Key extends keyof T>(key: Key) => {
    return (this.value as any)[key];
  };

  assign = (data: Partial<T>) => {
    Object.assign(this.value, data);
  };
};
```

Do you know of a way to provide actual setters/getters? 

The last part you talk about (returning instances of the implementation) is really tricky to implement in a way that doesn't sacrifice type information. It'll take a more sophisticated structure for organizing collections of schemas into a "data model". I started writing proposal for a plugin system but I need to do more experiments before I know for sure if its feasible.

**Comment by pierreis** [comment]
That second part is actually not the most complicated. It can be done roughly this way (written on the fly, untested, probably doesn't work)

```ts
interface ObjectShapeImpl<T extends ZodObject<any>> {
    assign: (data: Partial<T>) => T;
    with: (data: Partial<T> => T;
}

interface ObjectShapeStaticImpl<T extends ZodObject<any>> {
    new (obj: unknown): Infer<T> & ObjectShapeImpl<T>;
    // + shape(), type() or anything needed
}
```

Then, the class can be returned as:

```ts
function construct<T extends ZodObject<any>>(type: T) {
    return class StructClass<T> {
        private readonly value: Infer<T>;
        constructor(obj: Infer<T>) {
            for (const key of type.shape()) {
                Object.defineProperty(this, key, { ... });
            }
        )
    } as ObjectShapeImpl<T>
}
```

**Comment by vriad** [comment]
I was referring to proper JavaScript getters/setters on a per-property basis. You're right that an "assign" method is not difficult to implement. I had already done so in my example `StructClass` definition - no interfaces/casting is required. Unless I'm missing something?

I'm not a fan of the registry idea. It doesn't work with mutually recursive types. I'm working on a tool now that lets you package your data models into a single "ZodDatamodel" instance that you can use to accomplish things like this. Because there's a guarantee that all your schemas are defined upfront, it's easier to handle the mutual recursion case.

For now I'd recommend implementing this externally to the library. It should be possible to write a generic function that accomplishes what you're trying to do.

**Comment by pierreis** [comment]
I am not sure to understand what you mean by proper getter / setter? This seems to be exactly what `defineProperty` is doing.

**Comment by vriad** [comment]
Ah you’re right! Sorry about that. Very cool approach.

**Comment by jonlambert** [comment]
Came across this issue today when searching around this subject. Was there a recommended approach for this in the end? :)

**Comment by sam-goodwin** [comment]
@jonlambert, FWIW, this is my approach.

```ts
import z from "zod";

type UnionToIntersection<T> = (T extends any ? (x: T) => any : never) extends (
  x: infer R
) => any
  ? R
  : never;

type ZodValue<T extends z.ZodType> = T extends z.ZodType<infer Output>
  ? UnionToIntersection<Output>
  : never;

interface ZClass<T extends z.ZodRawShape>
  extends Omit<z.ZodObject<T>, "parse"> {
  parse(value: unknown): InstanceType<this>;

  new (data: ZodValue<z.ZodObject<T>>): ZodValue<z.ZodObject<T>>;
}

function ZClass<T extends z.ZodRawShape>(shape: T): ZClass<T> {
  const schema = z.object(shape);
  return class {
    constructor(value: ZodValue<z.ZodObject<T>>) {
      Object.assign(this, schema.parse(value));
    }
  } as any;
}

class HelloObject extends ZClass({
  key: z.string(),
}) {}

new HelloObject({
  key: "",
});
```

Had to collapse unions to intersection as Zod's types are a bit messy. 

The one thing I can't seem to get to work is to have the types of `HelloObject.parse` return the created class `HelloObject` type. I am surprised that `InstanceType<this>` doesn't return the created class.


```ts
const o = HelloObject.parse(..)
// is the wrong type 😭:
{
    key: string;
} & {
    key: string;
}
```

**Comment by itschrono** [comment]
Here is my version (with correct parse typings) if you still need it:

schema.ts:
```typescript
import { z } from 'zod';

export interface ZSchemaInterface<
	T extends z.ZodRawShape,
	TObject = z.ZodObject<T>
> {
	new (data: z.infer<z.ZodObject<T>>): z.infer<z.ZodObject<T>>;

	schema: TObject;

	parse<TFinal extends new (data: z.infer<z.ZodObject<T>>) => InstanceType<TFinal>>(
		this: TFinal,
		value: z.infer<z.ZodObject<T>>
	): InstanceType<TFinal>;
}

export function ZSchema<
	T extends z.ZodRawShape,
	Type = ZSchemaInterface<T> & z.infer<z.ZodObject<T>>
>(
	schema: z.ZodObject<T>,
): Type {
	const res = class {
		static schema = schema;
		constructor(value: z.infer<z.ZodObject<T>>) {
			Object.assign(this, schema.parse(value));
		}
		static parse<T extends typeof res>(this: T, value: unknown): any {
			const parsed = new this(schema.parse(value)) as any;
			return parsed;
		}
	};
	return res as typeof res & any;
}

```

user.ts
```typescript
import { z } from 'zod';
import { ZSchema } from './schema';

export const UserSchema = z.object({
	id: z.string(),
	email: z.string(),
	fullname: z.string(),
	pwd: z.string(),
	locale: z.string(),
});
export class User extends ZSchema(UserSchema) {
	private __strictUserOnly() {}
}
export class UserPartial extends ZSchema(UserSchema.partial()) {
	private __strictUserPartialOnly() {}
}
```

**Comment by takagiy** [comment]
I've published an [npm package](https://www.npmjs.com/package/validated-extendable) for this. Here is a short example of the usage. (You can refer the README for more.)

```ts
import { Validated } from "validated-extendable";
import { z } from "zod";

const schema = z.object({
  name: z.string().min(1),
  age: z.number().nonnegative().int(),
});

/* You can define a class extending a zod schema */
class Person extends Validated(schema) {
  greet() {
    console.log(`Hello, I'm ${this.name}.`);
  }

  isAdult() {
    return this.age >= 18;
  }
}

/* Constructor will validate the input using the zod schema! */
const person = new Person({ name: "John", age: 25 });
// const invalidPerson = new Person({ name: "John", age: -1 }); // => Throws an error
```
