### ISSUE TITLE
How to use `instanceof` to class with private constructor

### ISSUE THREAD

**Issue by YutaUra** [colinhacks/zod#384]
first, I want to use zod with `firebase/firestore`. And there is [`FieldValue`](https://firebase.google.com/docs/reference/js/firebase.firestore.FieldValue) class use for `createdAt` or `updatedAt`.

So, I think like this to use zod with firebase
```typescript
import * as z from 'zod'
import firebase from 'firebase/app'

const ServerTimestampSchema = z.instanceof(firebase.firestore.FieldValue)

const UserSchema = z.object({
  name: z.string(),
  // ...
  createdAt: ServerTimestampSchema,
  updatedAt: ServerTimestampSchema
})
```

maybe, this works at run time, but typescript compiler throw this message.

```typescript
// ...
const ServerTimestampSchema = z.instanceof(firebase.firestore.FieldValue)
// Argument of type 'typeof FieldValue' is not assignable to parameter of type 'new (...args: any[]) => any'.
//  Cannot assign a 'private' constructor type to a 'public' constructor type.ts(2345)

// ...
```

If someone has any solutions, please tell me!!

**Comment by colinhacks** [comment]
Hm, interesting problem. Based on a quick review, it doesn't appear to be solvable inside of `instanceof`. The only way for Zod to infer the type of the class passed into `z.instanceof` is to constrain it to the form `new (...args: any[]) => any` and use the `InstanceType` utility: https://www.typescriptlang.org/docs/handbook/utility-types.html#instancetypetype. 

However, in your particular case you can easily build your own using `z.custom`, which was introduced specifically for things like this. It accepts an explicit type and lets you specify a custom refinement check (in this case, an `instanceof` check). Here's the code:

```ts
const ServerTimestampSchema = z.custom<firebase.firestore.FieldValue>(
  (data) => data instanceof firebase.firestore.FieldValue
);
```

**Comment by ScreamZ** [comment]
For those like me trying to validate a luxon `Duration` this « hack » is valid.

```ts
import { z } from "zod";
import { Duration } from "luxon";

const IntervalValidator = z.custom<Duration>((t) => t instanceof Duration);
```

**Comment by sweetcoco** [comment]
Here are schemas for common Firestore FieldValue and Timestamp cases:

```typescript
import { FieldValue, Timestamp } from "firebase-admin/firestore";
import { z } from "zod";

// this is a Timestamp from the database
export const TimestampSchema = z.custom<Timestamp>(
  (data) => data instanceof Timestamp
);

// this is a FieldValue instance, to be written to the database
export const FieldValueSchema = z.custom<FieldValue>(
  (data) => data instanceof FieldValue
);

// this is a FieldValue, specifcally ServerTimestampTransform, to be written to the database
export const FieldValueServerTimestampSchema = z.custom<any>(
  (data) => (data as Object).constructor.name === FieldValue.serverTimestamp().constructor.name
);
```
