### ISSUE TITLE
Is `z.effect()` safe to use?

### ISSUE THREAD

**Issue by lpww** [colinhacks/zod#3875]
First of all, thanks for this great validation library! I'm hoping to get some guidance from the maintainers around the use of `z.effect`. 

It has been mentioned in some issues as a way to perform preprocessing. However, it's not officially documented. Is this API intended for public use? 

https://github.com/colinhacks/zod/issues/2486
https://github.com/colinhacks/zod/issues/2942

**Comment by colinhacks** [comment]
Yes, feel free to use it! It's a bit of a poweruser API, and I'd rather the typical user stick with the conceptually simpler `z.preprocess()` and `.transform()` APIs. But it's absolutely part of the stable API. No guarantees for compatibility with Zod 4 (the upcoming new major version though) as I'll likely be refactoring how Zod handles "effects" like this.

**Comment by lpww** [comment]
Thanks @colinhacks
