### ISSUE TITLE
Objects are always inferred as partial in mac

### ISSUE THREAD

**Issue by ssahillppatell** [colinhacks/zod#3891]
### Environment
bun: v1.1.38
zod: v3.23.8
os: macOS Sonoma 14.5

### Reproduction
```ts
import { z } from "zod";

const Dog = z.object({
    name: z.string(),
    age: z.number(),
});
  
type DogType = z.infer<typeof Dog>;

const mydog: DogType = {
    age: 3
}  // this works without error. It shouldn't
```

I previously thought this is a VScode typescript server issue. Therefore I tested the same on NeoVim. But got the same error. Then I tried the same code on debian and the error for name being not present was there.

### Screenshot
![image](https://github.com/user-attachments/assets/5c47a095-a538-43a9-b715-eb618caab4e2)

**Comment by colinhacks** [comment]
This happens when you haven't enabled `"strictNullChecks": true` in your `tsconfig.json`: https://github.com/colinhacks/zod/issues/3875#issuecomment-2530764796
