### ISSUE TITLE
Upgrading from 3.23.8 to 3.24.0 causing error in TS compilation

### ISSUE THREAD

**Issue by stephenglass** [colinhacks/zod#3900]
Upgrading Zod from 3.28.8 to 3.24.0, when I run `tsc` CLI command for TS compilation it takes a while and then eventually gives me this error stack trace. My env is Node.js v20 running in Debian based dev container. Reverting Zod version back to `3.28.8` resolves this issue.

```
<--- Last few GCs --->

[80373:0x73afd50]   156815 ms: Scavenge 2044.8 (2084.1) -> 2042.9 (2088.1) MB, 4.71 / 0.00 ms  (average mu = 0.571, current mu = 0.667) allocation failure; 
[80373:0x73afd50]   157783 ms: Mark-Compact (reduce) 2046.8 (2088.1) -> 2045.6 (2084.1) MB, 557.91 / 0.00 ms  (+ 263.7 ms in 59 steps since start of marking, biggest step 6.8 ms, walltime since start of marking 847 ms) (average mu = 0.464, current mu = 0.

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0xb82d33 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [/usr/local/bin/node]
 2: 0xef0c50 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/usr/local/bin/node]
 3: 0xef0f37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/usr/local/bin/node]
 4: 0x1102ad5  [/usr/local/bin/node]
 5: 0x111a958 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 6: 0x10f0a71 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 7: 0x10f1c05 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 8: 0x10cf256 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
 9: 0x152b086 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
10: 0x7fac4e699ef6 
```

**Comment by colinhacks** [comment]
Without a reproduction this is virtually impossible to debug I'm afraid. This typically happens where there are multiple versions of Zod in a codebase. Try running `npm why zod` to see which versions exist in node_modules and why they were installed.

**Comment by stephenglass** [comment]
That is indeed the case. I'm using [Spotify Backstage](https://github.com/backstage/backstage) framework which internally uses version `3.23.8` of Zod while I attempted to upgrade to `3.24.0` in my own code. I assumed (perhaps wrongly?) that this would not cause any issues due to this being a semver minor update.

**Comment by colinhacks** [comment]
Unfortunately almost any change to Zod will involve some small changes to the type signatures. Any change, however small, can technically break a build if things aren't set up well. When there are external libraries that are too strongly coupled to a specific version of Zod (say, if they haven't set it up as a peer dependency properly) or if there are weird package manager resolution issues (like https://github.com/ciscoheat/sveltekit-superforms/issues/527) then it's possible for tsc to break.

That said, it's rare to get an OOM crash like the one you experienced.

It looks like Spotify Backstage doesn't treat Zod as a peerDependency which isn't great. That means you'll probably need to pin to the same version as them. You could consider upstreaming a PR to fix this but they're willing.

**Comment by stephenglass** [comment]
Thanks for elaborating on that, that was a very helpful explanation. I'll close this issue.

**Comment by samal-rasmussen** [comment]
Yeah I just updated from 3.23.8 to 2.24.1 and then typescript started hanging just saying loading... Found out a library of mine was using 3.23.8 still, and after upgrading that everything worked again. Thanks for the tip Colin. Cheers.
