### ISSUE TITLE
Feature request: ".maybe()" type

### ISSUE THREAD

**Issue by ryami333** [colinhacks/zod#391]
Hi there, thanks for the excellent library, I'm using it on a variety of projects now! A problem I have come across recently is that while building schema for third-party REST APIs (ie. APIs which I have no control/influence over) I have to type non-mandatory properties like this:

```ts
/*
 * Generated from:
 * https://developer.zendesk.com/rest_api/docs/support/attachments#json-format
 */
export const attachmentResourceSchema = zod.object({
  // The content type of the image. Example value: "image/png"
  content_type: zod.string().nullable().optional(),

  // A full URL where the attachment image file can be downloaded
  content_url: zod.string().nullable().optional(),

  // If true, the attachment has been deleted
  deleted: zod.boolean().nullable().optional(),

  // The name of the image file
  file_name: zod.string().nullable().optional(),

  // Automatically assigned when created
  id: zod.number().nullable().optional(),

  // If true, the attachment is excluded from the attachment list and the attachment's URL can be referenced within the comment of a ticket. Default is false
  inline: zod.boolean().nullable().optional(),

  // The URL the attachment image file has been mapped to
  mapped_content_url: zod.string().nullable().optional(),

  // The size of the image file in bytes
  size: zod.number().nullable().optional(),

  // An array of attachment objects. Note that photo thumbnails do not have thumbnails
  thumbnails: zod.array(zod.unknown()).nullable().optional(),

  // A URL to access the attachment details
  url: zod.string().nullable().optional(),
})
```

The use of both `.nullable()` _and `.optional()` is apparently necessary (I've cross-checked against many payloads). Sometimes the payload contains those nullified properties, and other times it omits them entirely (ie. they are undefined). Could there be a `.maybe()` method which consolidates these two validations? I would be open to alternative naming.

Thanks!

**Comment by ryami333** [comment]
Oh and before someone suggests using `.partial()` - not _all_ of the properties in my use-case actually maybe-typed. In the example I posted they happen to be, but there are quite a few schema in this system with some mandatory properties.

**Comment by colinhacks** [comment]
Not a fan of this for reasons I describe briefly in #403 

In your particular case, you could implement a maybe function to avoid some verbosity:

```ts
const maybe = <T extends z.ZodTypeAny>(schema: T)=>{
  return schema.optional().nullable();
};

// equivalent
maybe(z.string());
z.string().optional().nullable();
```
