### ISSUE TITLE
Type of a Schema ?

### ISSUE THREAD

**Issue by vjau** [colinhacks/zod#392]
Hi,
i would like to write a function that would accept a schema as a parameter.
```ts
const func = (schema:z.Schema<string>)=>{
   const result = schema.safeParse("foo");
}
```
However, the compiler says that `schema` has type   `ZodSchema<string, zod.ZodTypeDef, string> | ((_: unknown) => boolean)`
What is the correct type to use for the function ?

**Comment by fabien0102** [comment]
Works for me with `z.Schema` even with generic:

![image](https://user-images.githubusercontent.com/1761469/115110248-afd91c80-9f7a-11eb-81a6-a77b2e895ea3.png)

(I'm running the latest v3 version)

**Comment by colinhacks** [comment]
Like @fabien0102 said, you should write this function with a generic type. Though we can do even better:

```ts
const func = <T extends z.ZodSchemaAny>(schema: T)=>{
   const result = schema.safeParse("foo");
};
```

`z.ZodSchemaAny` is just an alias for `z.ZodSchema<any,any,any>`. This way, the function can infer the subclass of ZodSchema (e.g. ZodString, ZodNumber, etc), whereas in Fabien's code the inferred type `T` will always be `ZodSchema` (the base class). Subtle but important difference, I should probably document this better.
