### ISSUE TITLE
Can we store extra data on a chema?

### ISSUE THREAD

**Issue by dodio** [colinhacks/zod#393]
Can we store some data on a schema like defaultValue for a schema, description of it, so that we can create a value with defaultValue with a method like
```javascript
z.object({
  id: z.string(),
  status: z.enum(['on', 'off']).default('on'),
}).create()
// and then get an object : {id: '', status: 'on'}
```
for form initialization.

or we can have a method like 
``` javascript
z.number().exra({
  title:  'GitHub Stars',
  defaultValue: 0,
})
```

**Comment by colinhacks** [comment]
Not a fan of this for reasons explained in #76 and #138.

tldr: if you want to define a data structure containing metadata for your form fields, Zod should be a component within it, not the container for it. You would get stronger typing using an approach like this: #76 (comment)

**Comment by jedwards1211** [comment]
Here's how I accomplish this: https://github.com/colinhacks/zod/issues/76#issuecomment-1887838005
