### ISSUE TITLE
`min` and `max` methods for `ZodSet`

### ISSUE THREAD

**Issue by pnfcre** [colinhacks/zod#394]
Hi there,

I'd like to implement `min` and `max` methods for `ZodSet`, copying the code from `ZodArray` but checking for `Set.prototype.size` instead of `Array.prototype.length`. Is it all green for me to open a PR? I can't find any existing issues or PRs for this. Thanks!

Kind regards,
Hampus Kraft.

**Comment by pnfcre** [comment]
All right, after implementing this, I realized that it results in a lot of duplicate code and documentation, which probably is undesirable. A more sustainable approach is simply to `z.array(z.string()).transform((value) => z.set(z.string()).parse(new Set([...value]))).parse(["a", "a", "a"]) // => {'a'}`, allowing the input to be checked with regular `ZodArray` methods. Thanks though!

**Comment by pnfcre** [comment]
Here's a more elaborate example for anyone stumbling across this issue wanting to implement it too:

```ts
export const zodInputArray = <T extends z.ZodTypeAny>(schema: T, {min = 1, max = 50} = {}) =>
  schema
    .array()
    .min(min)
    .max(max)
    .transform((value) => z.set(schema).parse(new Set([...value])))

const schema = zodInputArray(z.number())

const result = schema.safeParse([])
assert(result.success === false)
console.log(result.error.issues)
/*
[
  {
    "code": "too_small",
    "minimum": 1,
    "type": "array",
    "inclusive": true,
    "message": "Should have at least 1 items",
    "path": []
  }
]
*/

console.log(schema.parse([1, 2, 3, 3, 3])) // => { 1, 2, 3 }
```

**Comment by colinhacks** [comment]
Great solution and a smart use of transforms + generics!  👏👏👏

You could also use refinements potentially if you really need the min/max checks to happen after the values are deduplicated.

```ts
const zodInputSet = <T extends z.ZodTypeAny>(
  schema: T,
  { min = 1, max = 50 } = {}
) =>
  z
    .array(schema).transform(val => new Set(val))
    .refine((val) => val.size >= min)
    .refine((val) => val.size <= max)
```
