### ISSUE TITLE
[Question] how do you sujeest to validate table?

### ISSUE THREAD

**Issue by bnayae** [colinhacks/zod#395]
I have a table which use an array of object for validation.
The problem is that when I validate the array it affects all rows.

``` js
export const PersonSchema = z.object({
  email: z.string().email(),
  givenName,
  familyName,,
}).array();
```

For example if I have a column of email, and it is valid on one row but invalid on the other both cell would show the error because the field name is 'email' on both.

**Comment by bnayae** [comment]
I got it, path[] has the index in it

**Comment by colinhacks** [comment]
Excellent, glad you figured it out. 👍
