### ISSUE TITLE
How to specify discriminant for union?

### ISSUE THREAD

**Issue by brmenchl** [colinhacks/zod#396]
I'm using zod for form input, and there is a single dropdown field that should determine the "level" of validation. Essentially, most fields can be empty until you mark the form as "Published", at which point, all the fields because required.

I had originally built out two schemas: the non-published schema, and the published schema, that extend from the optional schema and made the rest of the fields required. I then used `z.union([nonPublishedSchema, publishedSchema])` to represent the whole form schema.

Simplified Example: 
```typescript
const nonPublishedBookSchema = z.object({
  title: z.string().optional(),
  availability: z.enum(["Draft", "Review"]);
})

const publishedBookSchema = nonPublishedBookSchema.extend({
  title: z.string(),
  availability: z.enum(["Published"]);
})

export const schema = z.union([nonPublishedBookSchema, publishedBookSchema]);
```

However, the errors that come out of zod when flipping the dropdown to "Published" make it hard to determine what is truly incorrect about the form. If I have a field empty, the first part of the union error (for non-published) will tell me that the availability enum value is incorrect, and the second part of the union error (for published) will tell me that the field is required.

I'd like to be able to specify the availability field as a sort of switch between different schemas. Basically, i would associate a full schema with a value or a series of values, and the errors I'd like to get out of zod should be specific only to that schema. Is there some way to do this? I thought about doing a refinement at the root of the schema, but I wasn't sure.

**Comment by brmenchl** [comment]
This might be a duplicate/similar to this example in the comment https://github.com/colinhacks/zod/issues/117#issuecomment-674449188

**Comment by colinhacks** [comment]
You're right that it's the same concept discussed in #117 though I'm still not a fan of the solutions proposed there. You might consider writing a parser function that "toggles" between the two schemas based on the form data (similar to the "resolver" function proposed in #117):

```ts
const nonPublishedBookSchema = z.object({
  title: z.string().optional(),
  availability: z.enum(["Draft", "Review"]);
})

const publishedBookSchema = nonPublishedBookSchema.extend({
  title: z.string(),
  availability: z.enum(["Published"]);
})

const parseForm = (val: unknown) =>
  ['Published'].includes(val?.availability)
    ? publishedBookSchema.safeParse(val) 
    : ["Draft", "Review"].includes(val?.availability)
    ? nonPublishedBookSchema.safeParse(val)
    : new Error();
```

^ Not tested but you get the idea. I think this is best approach.
