### ISSUE TITLE
`.transform()` returning output types unioned with input types

### ISSUE THREAD

**Issue by djrollins** [colinhacks/zod#397]
Hi there,

I've been excitedly looking to into using Zod as it provides great type-safety compared to yup, but also doesn't require a programming style shift like io-ts, which isn't so palatable for my team.

I have unfortunately hit a bit of snag with type inference of `transform()` which is currently limiting our ability to adopt this, though I do wonder if if I am misunderstanding the intent of this function.

I am trying to create a reusable Schema for for the `Decimal` class from `decimal.js`, which is pretty pervasive throughout our code-base.

I'd like it to accept `number`, `string` and `Decimal` instances as input but ultimately transform them into `Decimals`

Here is my attempt:

```typescript
import * as z from "zod";
import { Decimal } from "decimal.js";

// const decimal = (): z.Schema<Decimal> =>
const decimal = (): z.Schema<Decimal | string | number> =>
  z
    .instanceof(Decimal)
    .or(z.string())
    .or(z.number())
    .refine((value) => {
      try {
        return new Decimal(value);
      } catch (error) {
        return false;
      }
    })
    .transform((value) => new Decimal(value));
```
My expectation here would be that `refine` would trigger an error during parsing if input could not be converted to a Decimal and `transform` would ensure that the output is a `Decimal`.

However if I make the return type of this function with `z.Schema<Decimal>` I get a type error because the inferred type is actually `z.Schema<Decimal | string | number>`.

Am I misunderstanding what `transform` is supposed to be doing here?

Further, it's a little sad that I have to try and construct the `Decimal` instance to validate the input and then have to do it again in the `transform` call. I do understand that `refine` does not actually change the type of the input so this makes sense. Something I'd like to see is something like the following where where `refine` (or some new function?) accepts a type guard that informs the output type. (I have no idea if this is possible though):

```typescript
// const decimalIdeal = (): z.Schema<Decimal> =>
const decimalIdeal = (): z.Schema<Decimal | string | number | undefined> =>
  z
    .instanceof(Decimal)
    .or(z.string())
    .or(z.number())
    .transform((value) => {
      try {undefined
        return new Decimal(value);
      } catch (error) {
        return undefined;
      }
    })
    .refine((value): value is Decimal => value instanceof Decimal);
```
Note that the return type also includes `undefined` in order to type check now. It was this that lead me to believe that `transform` is returning the output type union-ed with the input type.

Many thanks for this library and any help you may be able to provide!

EDIT:

For what it's worth, the inferred type when using `TypeOf` is actually correct, so I've been able to test that the result of the Schema does type check with the following code:

```typescript
const _typeCheckDecimal: z.TypeOf<ReturnType<typeof decimal>> = {} as Decimal;
const _typeCheckDecimalReverse: Decimal = {} as z.TypeOf<ReturnType<typeof decimal>>;
```
But this will need to be done for any object schemas that use the `decimal` type above. It would be nice if the type could be "correct" at the declaration site too, if possible.

**Comment by scotttrinh** [comment]
I think you just need to specify the `Input` type of the schema: `z.Schema<Output, Def, Input = Output>` and in the case of a transformed schema, the input is not the same as the output.

**Comment by djrollins** [comment]
> I think you just need to specify the `Input` type of the schema: `z.Schema<Output, Def, Input = Output>` and in the case of a transformed schema, the input is not the same as the output.

Oh wow, I that worked perfectly, thank you! It all makes sense now. As I didn't specify that argument, TypesScript's type inference saw they needed to be the same so it union-ed them.

I honestly never looked past the `Def` argument argument because it seemed complete opaque to me. I should go away and understand the full signature.

Thanks for the help. Closing this issue.

**Comment by colinhacks** [comment]
@djrollins It's worth noting that this would have worked exactly as expected if you hadn't tried to provide an explicit type. 

```ts
const decimal = () =>
  z
    .instanceof(Decimal)
    .or(z.string())
    .or(z.number())
    .refine((value) => {
      try {
        return new Decimal(value);
      } catch (error) {
        return false;
      }
    })
    .transform((value) => new Decimal(value));

const d = decimal();
type O = z.output<typeof d>; // Decimal
type I = z.input<typeof d>; // Decimal | string | number
};
```

Perhaps there was some reason you needed to do this, e.g. if `decimal` is actually a generic function that you simplified for the sake of the issue (in which case, thanks for doing that!).

On the subject of the redundant constructor calls, I'm seriously considering a new method that allows both transformation and refinements. Still not sure about the API but this is on my radar.
