### ISSUE TITLE
Existing object as omit function argument leads to schema being an empty object

### ISSUE THREAD

**Issue by akbo** [colinhacks/zod#402]
Hi there, 

I want to use `.omit` with the same argument on multiple schema declarations. To do this, I specify the fields to be omitted in an object and use that object for multiple `.omit` calls instead of writing the same `.omit` argument multiple times. However, when I do this, zod removes all properties from the object instead of only the ones I specified.

Here is an example:

```
import * as z from "zod";

// MyType1 has prop2 after omit as expected

const MyType1 = z
  .object({
    prop1: z.string(),
    prop2: z.number()
  })
  .omit({ prop1: true });

type MyType1 = z.infer<typeof MyType1>;

// MyType2 is empty!?!

const omitProps: { [prop: string]: true } = { prop1: true };

const MyType2 = z
  .object({
    prop1: z.string(),
    prop2: z.number()
  })
  .omit(omitProps);

type MyType2 = z.infer<typeof MyType2>;
```

What I expected to get is this
```
type MyType1 = {
    prop2: number;
}

type MyType2 = {
    prop2: number;
}
```

What I get instead is this
```
type MyType1 = {
    prop2: number;
}

type MyType2 = {}
```

I created a codesandbox of this example [here](https://codesandbox.io/s/zod-omit-problem-glfc9?file=/src/index.ts).

**Comment by fabien0102** [comment]
This is due to your type, `{ [prop: string]: true }` is too wide, as example, if you change this by `{ prop1: true }` or `{ [prop in "prop1"]: true }` this is working as expected:

![image](https://user-images.githubusercontent.com/1761469/115058020-101d7f00-9ee5-11eb-9d4d-c2ecc972fee8.png)

**Comment by akbo** [comment]
Thanks for the quick reply! 

I think I get it now. There are two layers: typing and parsing. The *type* of `omitProps` determines, what the typing system thinks is present after using `.omit` and the *value* of `omitProps` determines, what the parser expects. 

When I typed `omitProps` too broadly, I mislead typescript into thinking I want to remove all properties, while the parser still expects `prop2` to be present on the object.

So with my wrong type for `omitProps` we get this
```
MyType2.parse({ prop2: 3 }); 
// works fine

MyType2.parse({}); 
// 1 validation issue(s)
// Issue #0: invalid_type at prop2
// Required
```

**Comment by colinhacks** [comment]
@akbo exactly — that "typing vs parsing" thing is a subtle but tricky element of TypeScript that takes a long time to fully understand. 

In practice, using `as const` is a better way to achieve this:
```ts
const oldOmitProps = { prop1: true } as const; // => { prop1: boolean } 
const omitProps = { prop1: true } as const; // { prop1: true } 
```

It tells typescript to treat the value as a literal/constant value, so it infers the type of `prop1` as `true` instead of `boolean` (which is required for `.omit` to work right).

@fabien0102 REALLY appreciating your help on some of these issues! I've had a busy few weeks (new job).
