### ISSUE TITLE
Feature idea: `.maybe()` === `.optional().nullable()`

### ISSUE THREAD

**Issue by KATT** [colinhacks/zod#403]
Would be nice to have a `.maybe()` that's the same as `.optional().nullable()`. In GraphQL this is used a lot

**Comment by colinhacks** [comment]
It's interesting, but I'd prefer to keep things explicit. The term Maybe will mean different things to different people and this behavior is likely to be unintuitive.

**Comment by KATT** [comment]
What if it was another term? JS is a bit effed that we have both `undefined` and `null`, sometimes it's nice with a bit of help with it

**Comment by KATT** [comment]
https://github.com/colinhacks/zod/issues/391#issuecomment-826252393 is an decent workaround though!

**Comment by colinhacks** [comment]
Now that you mention it, I think I'd be open to calling this `.nullish()` since that's an established term in JS. I'll implement that before the stable v3 release.
