### ISSUE TITLE
(v3) Refinements don't respect custom error map

### ISSUE THREAD

**Issue by unleashy** [colinhacks/zod#414]
See codesandbox with example: https://codesandbox.io/s/silly-dirac-1q3j0?file=/src/index.ts

Instead, you must always use the refine function's second parameter, which is weird, inconsistent and doesn't seem intentional?

Thanks! The library is great.

**Comment by akomm** [comment]
For me, it does not seem like it makes any sense having refine messages handled by `errorMap`. It looks even like the `code` property had been intentionally excluded in second param of `refine`, using `Omit`:
```ts
export declare type CustomErrorParams = Partial<util.Omit<ZodCustomIssue, "code">>;
```

Why do you expect the `code` of the refine error being `invalid_type`? This code is used when parsing types like `string`, `number` against given values. On this code, the `received` and `expected` types are checked and a proper message based on those values provided. What you try to do would be ambiguous. You would need to create additional code and there you will probably notice that it does not make sense placing it in `errorMap`. At least it seams so from what you've wrote.

**Comment by unleashy** [comment]
I’m sorry, I’m not sure I understand. Zod’s error handling documentation specifically says that you can customise every error message produced by Zod through `errorMap`; `refine` by default returns a `custom` issue code, but the error message for some reason doesn’t go through `errorMap` when I definitely think it should, [especially when the documentation itself tries to handle a `custom` code in an error map here.](https://github.com/colinhacks/zod/blob/v3/ERROR_HANDLING.md#customizing-errors-with-zoderrormap)

The example I sent was an intentionally very minimal example, of course my actual error maps aren’t like that.

**Comment by akomm** [comment]
The example is weird, maybe something old not removed or adjusted in the alpha? Because it does not make any sense. It tests for custom error code, which is totally ambiguous. It could be any refine. And it generates a quite specific, non-generic message and also would fail on type-checking too.

**Comment by colinhacks** [comment]
Good catch @unleashy! Fixed in `zod@3.0.0-alpha.40` 👍

**Comment by unleashy** [comment]
Thank you! ❤

**Comment by shreyansqt** [comment]
@colinhacks I am facing the same issue in refine and superrefine. Check codesandbox: https://codesandbox.io/s/sweet-grass-gqb1g?file=/src/index.ts

I am using the latest version of zod there and in the example, I expect the `console.log` at line 16 of `index.ts` to be displayed when running `parse`, and the error message to be "errorMap error message".
