### ISSUE TITLE
Unknown keys are incorrectly permitted in Union types.

### ISSUE THREAD

**Issue by alan-codaio** [colinhacks/zod#418]
(v3) This is similar to the issue in #311, but I'd like some input since Zod does not throw an error in my case at all.

Zod doesn't allow unknown keys in Object schemas. Is it possible to be strict on typing for Object Unions, to be consistent with Typescript?

```
const A = z.object({
          a: z.number()
});

const B = z.object({
          a: z.number(),
          b: z.string()
});
const AB = z.union([A, B]);
        const c = {
          a: 1,
          b: 2,
        };

AB.parse(c); // => returns { a: 1 } but should throw an error.
```

```
interface A {
  a: number;
}
interface B {
  a: number;
  b: string;
}

const b: A | B = {a: 1, b: 2} // Type 'number' is not assignable to type 'string'.
```

**Comment by colinhacks** [comment]
In Zod 2+ (which I assume you're using), objects strips unknown keys from the output instead of throwing an error. This was done to make the inferred types more accurate for intersection types: https://github.com/colinhacks/zod/issues/106

If you want the old behavior, you need to be explicit:

```ts
const A = z.object({
  a: z.number(),
}).strict();

# convenience method
const B = z.strictObject({
  a: z.number(),
  b: z.string(),
});

const AB = z.union([A, B]);
```
