### ISSUE TITLE
Add docstrings to inferred type

### ISSUE THREAD

**Issue by jauco** [colinhacks/zod#423]
Given some code like:

```
import { z } from "zod";

const UserSchema = z.object({
  /**
   * The "ame" of the "usern" _not_ the "name" of the "user"!
   **/
  username: z.string(),
});

interface UserInterface {
  /**
   * The "ame" of the "usern" _not_ the "name" of the "user"!
   **/
  username: string;
}

type User = z.infer<typeof UserSchema>;

const foo: User = {
  username: "",
};

const bar: UserInterface = {
  username: "",
};
```

if I hover over `username: ""` of foo I don't see the docstring like I would when hovering over the username of bar

This is due to the fact that some of the mapped types are not quite homomorphic types (especially around addquestionmark) so typescript doesn't copy the metadata along to the new type. I think I might be able to change them into homomorphic types by using typescript 4.1's `[key in keyof T as ...]` syntax. 

Would you consider such a PR for merging? Are there any gotcha's that I should be aware of?

**Comment by colinhacks** [comment]
Good call! I hadn't dug deeply enough into the new ` as ` syntax. Very open to this. 

I'm not familiar enough with how TS handles docstrings to know if this will work. Curious to hear whether you can get this working.

**Comment by colinhacks** [comment]
I had to revert this due to #458. Not sure what the issue is here, feel free to take a look at it if you have some time.
