### ISSUE TITLE
.nullable and .default

### ISSUE THREAD

**Issue by mariusmarais** [colinhacks/zod#425]
EDIT: I see in https://github.com/colinhacks/zod/pull/421#issuecomment-830912340 it's not actually supposed to work this way... In which case I request that a "default() for nulls" or "default() handles nulls" be added, since I cannot figure out a way to do this without removing the null before passing to zod.

(Using 3.0.0-beta.1)

I expect `.nullable().default(...)` to not have `xxx | null` in the output type, in the same way that (redundancy aside) `.optional().default(...)` does not have `xxx | undefined`, but I'm not 100% sure my reasoning is correct.

Should `.default()` replace `null` values, so that `number().nullable().default(1) => number` or `number | null`?
Or does `.default()` only operate on `undefined`s?

Should the chaining order matter so that `number().nullable().default(1) => number` and `number().default(1).nullable() => number | null`?

Example:

```ts
// Given
export const PaginationInputSpec = z
  .object({
    page: z.number().default(1),
    perPage: z.number().default(100)
  })
  .nullable()
  .default({});

// I expect:
PaginationInputSpec.parse(undefined) => { page: number, perPage: number }
// AND
PaginationInputSpec.parse(null) => { page: number, perPage: number }

// but I get 
PaginationInputSpec.parse(...) => { page: number, perPage: number } | null
```

Is this a bug?

I can try to work around it with:
```ts
...
  .nullable()
  .transform((i) => i ?? undefined)
  .default({});
```
which removes the `| null` from the output type, but it DOESN'T ACTUALLY WORK AT RUNTIME, making the whole thing `undefined`.  I expected the "inner" defaults to then take effect, but they don't.

Using in a GraphQL API where input optionals can be entirely missing (`undefined`) or explicitly `null`.

**Comment by colinhacks** [comment]
Like you said there's no way to do this right now. I think I'm going to introduce a "preprocess" method that would let you attach logic like this to your schema prior to parsing, something like this:

```ts
const PaginationInputSpec = z
  .object({
    page: z.number().default(1),
    perPage: z.number().default(100),
  })
  .preprocess((val: unknown) => {
    return val ?? {};
  })
```

But for now the best way is to duplicatively define your defaults:

```ts
const PaginationInputSpec = z
    .object({
      page: z.number().default(1),
      perPage: z.number().default(100),
    })
    .nullable()
    .default({})
    .transform((val) => {
      return val ?? { page: 1, perPage: 100 };
    });
```

**Comment by mariusmarais** [comment]
Yes, ended up doing exactly that 😄

**Comment by Lonli-Lokli** [comment]
@colinhacks Can you please add such method now? Hope it's already possible?
