### ISSUE TITLE
Use existing interfaces and types to type check response from promise

### ISSUE THREAD

**Issue by AshwinTayson** [colinhacks/zod#429]
I understand the examples given for primitive types. But I quite dont understand a few things when I have to put all of them together.

If I have interfaces already do I have to use zodSchema to redeclare them? If yes, then this library would not be useful for existing big projects? Since everything have to be redeclared.

I'll give one example

```

interface Vehicle {
  name: string;
  model?: string;
  year: number;
}

interface Meta {
  id: string;
  url: string;
  description: string;
  meta: Meta;
}

interface Car extends Vehicle {
  supercar?: boolean;
  meta: Meta;
}

axios.get('....').then({data} => {
   // Validate that data is of type Car
})
```

So is validating the response from axios possible without declaring all the interfaces using zod types? Sorry if it seems like a newb question.

**Comment by colinhacks** [comment]
You have to switch to Zod. There's no way to validate data using TypeScript interfaces. They're not code, they're just annotations. When you compile TypeScript to JavaScript, those interfaces no longer exist, they get stripped away. This is exactly why Zod exists; it lets you define a schema that does runtime validation and gives you a static type (like an interface) that you can use elsewhere.

**Comment by captain-yossarian** [comment]
@AshwinTayson you can treat types as JSdoc annotations or just comments

**Comment by AshwinTayson** [comment]
@colinhacks I understand that. I thought we can use zod like typescript-runtime to use existing interfaces and types so that for a big typescript project this will save alot of time.

**Comment by colinhacks** [comment]
Nope Zod doesn't do that, it's just a schema library.
