### ISSUE TITLE
Deprecate string.nonempty?

### ISSUE THREAD

**Issue by alii** [colinhacks/zod#439]
It can be confusing using it with `.min` when they can both serve the same purpose. For example, it's impossible to what happens if I do the following without consulting the source code:
```ts
z.string().min(2).nonempty();
```

Does that remove my minimum length of 2 on `.min`? The answer is yes, but it's unclear. I think it would be better to make users just use `.min(1)` as that is far easier to read and look at.

**Comment by colinhacks** [comment]
Good call, I agree with this. I'll probably never remove support but I'll steer people towards `.min(1)`. Deprecated in #440.

**Comment by alii** [comment]
Awesome 👍🏻

**Comment by npearson72** [comment]
Granted `min(1)` produces the same result, but `nonempty` gives uniformity in messaging which makes for a better UX.

For example, if I have `min(1)` for all my required fields, the errors is `X field is required.`

But in the case where one of the fields has `min(4)`, I would like the initial error to be uniform with the other fields, but alas there's no way to do it without relying on a deprecated function.

**Comment by alii** [comment]
As a workaround, you could write `.min(1, 'Username must be at least 1 character');`

**Comment by npearson72** [comment]
> As a workaround, you could write `.min(1, 'Username must be at least 1 character');`

Yeah, that's a good way to go... but still forces one's hand w/rt message preference.

**Comment by jrmyio** [comment]
I don't like that nonempty will be removed, what do you need to do when you want something like:
    .min(1, {
        message: PhoneNumberErrorType.REQUIRED,
    })
    .min(6, {
        message: PhoneNumberErrorType.TOO_SHORT,
    })`

You will now get 2 errors instead of 1 when its an empty string.

**Comment by npearson72** [comment]
@jrmyio well in your case, why would you need the `min(1)`? Can't your `min(6)` message communicate what the user needs?

But yeah, overall to what I was saying, this does box you into what type of messaging you want to provide in your UX.

**Comment by jrmyio** [comment]
> @jrmyio well in your case, why would you need the `min(1)`? Can't your `min(6)` message communicate what the user needs?
> 
> But yeah, overall to what I was saying, this does box you into what type of messaging you want to provide in your UX.

Yes maybe, but I would prefer a:

"A phone number is required", without having to go into the details, as they really "forgot" this field.

and a "This phone number needs to be at least 6 characters.", when they really filled something in that is too short.
