### ISSUE TITLE
Error message order is incorrect

### ISSUE THREAD

**Issue by blessanm86** [colinhacks/zod#442]
Hi,

I notice that the error message ordering seems off. It always reports the `email` error first instead of `nonempty`.

```
const schema = z.object({
  email: z
    .string()
    .nonempty({ message: "Email is required" })
    .email({ message: "Email is invalid" })
});
console.log(schema.safeParse({ email: "" }));
```

I believe this is a regression as its works find in the last 2.** beta version.
https://codesandbox.io/s/ecstatic-sun-b1vk2?file=/src/index.ts

**Comment by colinhacks** [comment]
Fixed in beta4. Though note that the order in which you chain these methods is not relevant to the error ordering. It checks min > max > email > email > url > uuid, in that order (look at the implementation of ZodString to see why).

**Comment by blessanm86** [comment]
Great tried it out and works now. Thanks for the clarification.
