### ISSUE TITLE
[WIP] `Excessive stack depth comparing types 'ZodIntersection<?, U>' and 'ZodIntersection<?, U>'.`

### ISSUE THREAD

**Issue by clouedoc** [colinhacks/zod#443]
This is a WIP issue. I believe Zod (beta 4) is causing huge performances problem in my project. 

Ressource: https://github.com/microsoft/TypeScript/issues/43249

The performance problem happened after updating VSCode, so that might be the reason why it's happening.

I'll keep this issue updated

EDIT: this took a few hours of my life, solved by editing my workspace's settings.json

```json
{
  "typescript.tsdk": "../../node_modules/typescript/lib"
}
```

**Comment by dgreene1** [comment]
The real fix for this was merged in https://github.com/microsoft/TypeScript/pull/43527 but I don't know which version of TypeScript that will be released in.
