### ISSUE TITLE
3.0.0-beta.4 is marking properties as optional

### ISSUE THREAD

**Issue by brielov** [colinhacks/zod#446]
```typescript
const authSchema = z.object({
  email: z
    .string()
    .email()
    .transform(z.string(), (x) => x.trim().toLowerCase()),
  password: z.string().min(8),
});
```

Calling `authSchema.safeParseAsync()` returns data as optional.

```typescript
const result: {
    success: false;
    error: ZodError;
} | {
    success: true;
    data: {
        email?: string;
        password?: string;
    };
}
```

Also, safeParse is not working correctly. `if (result.success)` is not given me the data property, if it is negated the error property doesn't come up either. `if (result.success === true)` is working however.

I'm using version `2.0.0-beta.30`

**Comment by colinhacks** [comment]
#121 #276 #289
