### ISSUE TITLE
Missing index signature when using passthrough() and infer()

### ISSUE THREAD

**Issue by lo1tuma** [colinhacks/zod#452]
I’ve tried to update my projects from using zod v1 to zod v3. Unfortunately it seems like `passthrough()` does’t work in the same way as `nonstrict()` did before.

Example:

```ts
const foo = z.object({ foo: z.string() }).passthrough();
type Foo = z.infer<typeof foo>;
```

The inferred type `Foo` is now `{ foo: string; }`, but since I want to allow unrecognized keys I would expect something like `{ foo: string; [key: string]: unknown; }`.

Example with zod v1:

```
const foo = z.object({ foo: z.string() }).nonstrict();
type Foo = z.infer<typeof foo>;
```

The inferred type `Foo` is here `{ [x: string]: any, foo: string }`.

**Comment by lo1tuma** [comment]
I’ve just learned about `catchall()` in zod v3, which adds an index signature to the inferred type. I guess this would work for my case.
The question is, what would be the expected behavior for `passthrough()` here?

**Comment by colinhacks** [comment]
Fixed in 3.3.2. 

BTW Mathias, I just merged the  big performance enhancement PR in 3.3.2 so Zod's 200x faster now 😛

**Comment by lo1tuma** [comment]
Awesome @colinhacks. Thank you!

**Comment by gao-sun** [comment]
we're good with `.catchall(z.unknown())` (the correct type can be inferred):

```ts
const foo = z
  .object({
    id: z.string().optional(),
  })
  .catchall(z.unknown());

type Foo = z.infer<typeof foo>; // { [x: string]: unknown; id?: string; }
```

should `.passthrough()` has the same index signature? since their behavior looks the same. currently `.passthrough()` will not add `[x: string]: unknown;` to the inferred type.
