### ISSUE TITLE
`.regex()` migration Zod 1 to 3

### ISSUE THREAD

**Issue by jorisre** [colinhacks/zod#453]
Hi @colinhacks 

Congrats for the V3 🎉  ! That new version seems awesome 👏🏻 

I'm looking to update the zod resolver for react-hook-form and I don't know if it's an issue or not but I can't chain anymore `.regex`

```ts
import { z } from "zod";

const password = z
  .string()
  .regex(new RegExp(".*[A-Z].*"), "One uppercase character")
  .regex(new RegExp(".*[a-z].*"), "One lowercase character")
  .regex(new RegExp(".*\\d.*"), "One number")
  .regex(
    new RegExp(".*[`~<>?,./!@#$%^&*()\\-_+=\"'|{}\\[\\];:\\\\].*"),
    "One special character"
  )
  .min(8, "Must be at least 8 characters in length");
```

👉🏻  https://codesandbox.io/s/angry-proskuriakova-5rqvw

Should I use the `.and` method ?
Thanks!

**Comment by colinhacks** [comment]
Hey Joris, sorry for the lateness here. 

This should definitely be chainable...whoops. Somehow I overlooked the `regex` method when refactoring these methods for Zod 3. I just pushed a fix — available in Zod 3.1.0. Good catch 👍

**Comment by jorisre** [comment]
Thanks a lot! it works!

**Comment by SalahAdDin** [comment]
> Hi @colinhacks
> 
> Congrats for the V3 tada ! That new version seems awesome 👏🏻
> 
> I'm looking to update the zod resolver for react-hook-form and I don't know if it's an issue or not but I can't chain anymore `.regex`
> 
> ```ts
> import { z } from "zod";
> 
> const password = z
>   .string()
>   .regex(new RegExp(".*[A-Z].*"), "One uppercase character")
>   .regex(new RegExp(".*[a-z].*"), "One lowercase character")
>   .regex(new RegExp(".*\\d.*"), "One number")
>   .regex(
>     new RegExp(".*[`~<>?,./!@#$%^&*()\\-_+=\"'|{}\\[\\];:\\\\].*"),
>     "One special character"
>   )
>   .min(8, "Must be at least 8 characters in length");
> ```
> 
> 👉🏻 https://codesandbox.io/s/angry-proskuriakova-5rqvw
> 
> Should I use the `.and` method? Thanks!

Good reference, thank you.
