### ISSUE TITLE
.extend after .refine

### ISSUE THREAD

**Issue by jmacmahon** [colinhacks/zod#454]
```ts
const timespan = z.object({
    start: z.date(),
    end: z.date()
}).refine(startIsBeforeEnd)

const annotatedTimespan = timespan.extend({
    something: z.string()
})
// ^ Fails with error TS2339: Property 'extend' does not exist on type ...
```

I guess this is to do with it being difficult to define methods on a `ZodEffects` which may or may not be there depending on the first type parameter.

**Comment by JVictorV** [comment]
I thought I've had fixed it by accessing the inner type of the refinement with` .refine(...).innerType()` but it just skips it. My current solution unfortunately is to rewrite all the refinements manually on each extended schema

**Comment by colinhacks** [comment]
This isn't possible given the new Zod 3 architecture I'm afraid. 

Like you mentioned, refinements and transforms have been consolidated as "effects" and live in the ZodEffects class.  Zod is designed to validate a type, then pass that value through a chain of refinements/transforms (in that order). Splitting out your refinement functions is the best way to do this currently.

**Comment by alb7h** [comment]
I'm using zod on a form that can support password changes with and without a code. 

<details>
<summary>This is my validationSchema:</summary>

```ts
const validationSchema = z
  .object({
    password: z
      .string()
      .min(10, 'login:errors.passwordMinLength')
      .nonempty('common:formErrors.required'),
    passwordConfirm: z.string(),
  })
  .refine((data) => data.password === data.passwordConfirm, {
    message: 'login:errors.passwordMismatch',
    path: ['confirmPassword'],
  });

const validationSchemaWithCode = z
  .object({
    code: z.string().nonempty('common:formErrors.required'),
    password: z
      .string()
      .min(10, 'login:errors.passwordMinLength')
      .nonempty('common:formErrors.required'),
    passwordConfirm: z.string(),
  })
  .refine((data) => data.password === data.passwordConfirm, {
    message: 'login:errors.passwordMismatch',
    path: ['confirmPassword'],
  });
```

</details>

Ideally I'd like to extend it to add `code` as a required field, but because i'm trying to add a refinement for checking if the password is the same, I need to duplicate the schemas and add refine to both. Is there any easier way of representing this? Or maybe any examples of complex schemas where fields requirements changed based on selections. (I.E a `type` field can change the form subtly I.E on a travel form, if you're making a one way trip you just need outwards date, but on a return trip you also now need to make the return field required)

Apologies if this is off topic for this issue, but it seemed relevant.

**Comment by lilred** [comment]
- You can model your state as a tagged union, e.g. `{oneWay: true, departureDate: Date} | {oneWay: false, departureDate: Date, returnDate: Date}`.
- You can model your state with the password/confirm password thing in its own object, that way you can reuse its validation
- Worst case scenario, I wonder if you can `merge` or `intersect` schemas which are based on objects but have seen refinements?

**Comment by DenisGorbachev** [comment]
I've implemented this feature:

```
import { ZodObject } from 'zod'
import { AnyZodObject, objectInputType, objectOutputType, UnknownKeysParam, ZodEffects, ZodRawShape, ZodTypeAny } from 'zod/lib/types'
import { addEffect } from './addEffect'

export const mergeWithEffect = <Incoming extends AnyZodObject, T extends ZodRawShape, UnknownKeys extends UnknownKeysParam = UnknownKeysParam, Catchall extends ZodTypeAny = ZodTypeAny, Output = objectOutputType<T, Catchall, UnknownKeys>, Input = objectInputType<T, Catchall, UnknownKeys>>(a: ZodEffects<ZodObject<T, UnknownKeys, Catchall, Output, Input>>, b: Incoming) => {
  return addEffect(a.innerType().merge(b), a._def.effect)
}

export const mergeWithEffects = <aT extends ZodRawShape, bT extends ZodRawShape, aUnknownKeys extends UnknownKeysParam = UnknownKeysParam, aCatchall extends ZodTypeAny = ZodTypeAny, bUnknownKeys extends UnknownKeysParam = UnknownKeysParam, bCatchall extends ZodTypeAny = ZodTypeAny, aOutput = objectOutputType<aT, aCatchall, aUnknownKeys>, aInput = objectInputType<aT, aCatchall, aUnknownKeys>, bOutput extends { [x: string]: unknown } = objectOutputType<bT, bCatchall, bUnknownKeys>, bInput extends { [x: string]: unknown } = objectInputType<bT, bCatchall, bUnknownKeys>>(a: ZodEffects<ZodObject<aT, aUnknownKeys, aCatchall, aOutput, aInput>>, b: ZodEffects<ZodObject<bT, bUnknownKeys, bCatchall, bOutput, bInput>>) => {
  const base = a.innerType().merge(b.innerType())
  return addEffect(addEffect(base, a._def.effect), b._def.effect)
}
```

```
import { Effect, z, ZodType } from 'zod'
import { ZodTypeDef } from 'zod/lib/types'

export const addEffect = <Output = unknown, Def extends ZodTypeDef = ZodTypeDef, Input = Output>(base: ZodType<Output, Def, Input>, effect: Effect<unknown>) => {
  switch (effect.type) {
    case 'preprocess':
      return z.preprocess(effect.transform, base)
    case 'transform':
      return base.transform(effect.transform)
    case 'refinement':
      return base.superRefine(effect.refinement)
  }
}
```

```
import { expect, test } from '@jest/globals'
import assert from 'assert'
import { z } from 'zod'
import { mergeWithEffect, mergeWithEffects } from './mergeWithEffects'

test(mergeWithEffect.name, () => {
  const a = z.object({ name: z.string() }).refine(({ name }) => name.length > 0)
  const b = z.object({ surname: z.string() })
  const merged = mergeWithEffect(a, b)
  const result = merged.safeParse({ name: '', surname: '' })
  assert(!result.success)
  expect(result.error.errors.length).toEqual(1)
})

test(mergeWithEffects.name, () => {
  const a = z.object({ name: z.string() }).refine(({ name }) => name.length > 0)
  const b = z.object({ surname: z.string() }).refine(({ surname }) => surname.length > 0)
  const merged = mergeWithEffects(a, b)
  const result = merged.safeParse({ name: '', surname: '' })
  assert(!result.success)
  expect(result.error.errors.length).toEqual(2)
})
```

@colinhacks Should I open a PR?

**Comment by TomasHubelbauer** [comment]
I've worked around this by exporting my shared schema and a refiner function and then in the code sites that use it, extending the schema and wrapping the extended shema in the refiner:

`/packages/shared`:
```typescript
export const sharedSchema = z.object({ … });
export const refineExtendedSharedSchema = (schema: typeof sharedSchema) => schema.refine(({ … }) => …);
```

`/apps/call-site-n` (this only makes sense if there are multiple code sites sharing the basic schema):
```typescript
const siteSpecificSchema = refineExtendedSharedSchema(sharedSchema.extend({ … }));
```

This is a usable workaround, but it feels very inelegant. I was sure there was a better way before I found this issue. Would be great to get a word from @colinhacks on @DenisGorbachev's solution and whether there are any downsides which preclude it from being included in Zod - and if there aren't, if it could be included in Zod.

**Comment by bryanltobing** [comment]
to get the correct types. you need to type the params as generic

```ts
export function deleteAccountRequestSchemaWithRefine<
  T extends z.infer<typeof deleteAccountRequestSchema>,
>(schema: z.ZodSchema<T>): z.ZodSchema<T> {
  return schema.refine((data) => !(data.reason === 'Other' && !data.feedback), {
    message: 'Feedback must be filled',
    path: ['feedback'],
  });
}
```

**Comment by gilles-yvetot** [comment]
@bryanltobing Would you mind expending how you are using your solution? 
` T extends z.infer<typeof schema>,` this part is not working for me

**Comment by paldron** [comment]
```
function refineSchema<T extends z.Schema, R extends ReturnType<T["refine"]>>(
  schema: T,
): R {
  return schema.refine((values) => ....),
  ) as R;
}
```
This will resolve to correct types even in cases where the schema uses discriminatedUnion

@gilles-yvetot  eg.
`const customerSchema = refineSchema(z.Object({name: z.string().trim().min(3)}))`

**Comment by adamwgriffin** [comment]
The solution where we add the refinement via a function works pretty well but it feels awkward when using it with the rest of the Zod API, and once you get around to adding the correct types to the function, it can start to feel somewhat complicated. My solution was to just put the arguments for `refine()` inside of an array and then just call `refine(...args)` on any shared schema that needs to be extended. Still not the greatest solution because anyone using the code needs to understand that they should always call `refine()` with the args array but the readability is a bit more clear IMO and the amount of boilerplate is close to the same. This is what that solution looks like:

```typescript
const sharedSchema = z.object({
  start: z.date(),
  end: z.date()
})

export const startIsBeforeEnd: Parameters<
  (typeof sharedSchema)['refine']
> = [
  ({ start, end }) => start < end,
  {
    message: 'Start must be before end'
  }
]

const timespan = sharedSchema.refine(...startIsBeforeEnd)

const annotatedTimespan = sharedSchema.extend({ something: z.string()}).refine(...startIsBeforeEnd)
```

**Comment by vinicius507** [comment]
> I've implemented this feature:
> 
> ```
> import { ZodObject } from 'zod'
> import { AnyZodObject, objectInputType, objectOutputType, UnknownKeysParam, ZodEffects, ZodRawShape, ZodTypeAny } from 'zod/lib/types'
> import { addEffect } from './addEffect'
> 
> export const mergeWithEffect = <Incoming extends AnyZodObject, T extends ZodRawShape, UnknownKeys extends UnknownKeysParam = UnknownKeysParam, Catchall extends ZodTypeAny = ZodTypeAny, Output = objectOutputType<T, Catchall, UnknownKeys>, Input = objectInputType<T, Catchall, UnknownKeys>>(a: ZodEffects<ZodObject<T, UnknownKeys, Catchall, Output, Input>>, b: Incoming) => {
>   return addEffect(a.innerType().merge(b), a._def.effect)
> }
> 
> export const mergeWithEffects = <aT extends ZodRawShape, bT extends ZodRawShape, aUnknownKeys extends UnknownKeysParam = UnknownKeysParam, aCatchall extends ZodTypeAny = ZodTypeAny, bUnknownKeys extends UnknownKeysParam = UnknownKeysParam, bCatchall extends ZodTypeAny = ZodTypeAny, aOutput = objectOutputType<aT, aCatchall, aUnknownKeys>, aInput = objectInputType<aT, aCatchall, aUnknownKeys>, bOutput extends { [x: string]: unknown } = objectOutputType<bT, bCatchall, bUnknownKeys>, bInput extends { [x: string]: unknown } = objectInputType<bT, bCatchall, bUnknownKeys>>(a: ZodEffects<ZodObject<aT, aUnknownKeys, aCatchall, aOutput, aInput>>, b: ZodEffects<ZodObject<bT, bUnknownKeys, bCatchall, bOutput, bInput>>) => {
>   const base = a.innerType().merge(b.innerType())
>   return addEffect(addEffect(base, a._def.effect), b._def.effect)
> }
> ```
> 
> ```
> import { Effect, z, ZodType } from 'zod'
> import { ZodTypeDef } from 'zod/lib/types'
> 
> export const addEffect = <Output = unknown, Def extends ZodTypeDef = ZodTypeDef, Input = Output, Base extends ZodType<Output, Def, Input> = ZodType<Output, Def, Input>>(base: Base, effect: Effect<unknown>) => {
>   switch (effect.type) {
>     case 'preprocess':
>       return z.preprocess(effect.transform, base)
>     case 'transform':
>       return base.transform(effect.transform)
>     case 'refinement':
>       return base.superRefine(effect.refinement)
>   }
> }
> ```
> 
> ```
> import { expect, test } from '@jest/globals'
> import assert from 'assert'
> import { z } from 'zod'
> import { mergeWithEffect, mergeWithEffects } from './mergeWithEffects'
> 
> test(mergeWithEffect.name, () => {
>   const a = z.object({ name: z.string() }).refine(({ name }) => name.length > 0)
>   const b = z.object({ surname: z.string() })
>   const merged = mergeWithEffect(a, b)
>   const result = merged.safeParse({ name: '', surname: '' })
>   assert(!result.success)
>   expect(result.error.errors.length).toEqual(1)
> })
> 
> test(mergeWithEffects.name, () => {
>   const a = z.object({ name: z.string() }).refine(({ name }) => name.length > 0)
>   const b = z.object({ surname: z.string() }).refine(({ surname }) => surname.length > 0)
>   const merged = mergeWithEffects(a, b)
>   const result = merged.safeParse({ name: '', surname: '' })
>   assert(!result.success)
>   expect(result.error.errors.length).toEqual(2)
> })
> ```
> 
> @colinhacks Should I open a PR?

Trying out your approach right now and TypeScript seems to be unable to resolve the return type of `mergeWithEffect` :/

**Comment by YogiPristiawan** [comment]
> I've implemented this feature:
> 
> ```
> import { ZodObject } from 'zod'
> import { AnyZodObject, objectInputType, objectOutputType, UnknownKeysParam, ZodEffects, ZodRawShape, ZodTypeAny } from 'zod/lib/types'
> import { addEffect } from './addEffect'
> 
> export const mergeWithEffect = <Incoming extends AnyZodObject, T extends ZodRawShape, UnknownKeys extends UnknownKeysParam = UnknownKeysParam, Catchall extends ZodTypeAny = ZodTypeAny, Output = objectOutputType<T, Catchall, UnknownKeys>, Input = objectInputType<T, Catchall, UnknownKeys>>(a: ZodEffects<ZodObject<T, UnknownKeys, Catchall, Output, Input>>, b: Incoming) => {
>   return addEffect(a.innerType().merge(b), a._def.effect)
> }
> 
> export const mergeWithEffects = <aT extends ZodRawShape, bT extends ZodRawShape, aUnknownKeys extends UnknownKeysParam = UnknownKeysParam, aCatchall extends ZodTypeAny = ZodTypeAny, bUnknownKeys extends UnknownKeysParam = UnknownKeysParam, bCatchall extends ZodTypeAny = ZodTypeAny, aOutput = objectOutputType<aT, aCatchall, aUnknownKeys>, aInput = objectInputType<aT, aCatchall, aUnknownKeys>, bOutput extends { [x: string]: unknown } = objectOutputType<bT, bCatchall, bUnknownKeys>, bInput extends { [x: string]: unknown } = objectInputType<bT, bCatchall, bUnknownKeys>>(a: ZodEffects<ZodObject<aT, aUnknownKeys, aCatchall, aOutput, aInput>>, b: ZodEffects<ZodObject<bT, bUnknownKeys, bCatchall, bOutput, bInput>>) => {
>   const base = a.innerType().merge(b.innerType())
>   return addEffect(addEffect(base, a._def.effect), b._def.effect)
> }
> ```
> 
> ```
> import { Effect, z, ZodType } from 'zod'
> import { ZodTypeDef } from 'zod/lib/types'
> 
> export const addEffect = <Output = unknown, Def extends ZodTypeDef = ZodTypeDef, Input = Output, Base extends ZodType<Output, Def, Input> = ZodType<Output, Def, Input>>(base: Base, effect: Effect<unknown>) => {
>   switch (effect.type) {
>     case 'preprocess':
>       return z.preprocess(effect.transform, base)
>     case 'transform':
>       return base.transform(effect.transform)
>     case 'refinement':
>       return base.superRefine(effect.refinement)
>   }
> }
> ```
> 
> ```
> import { expect, test } from '@jest/globals'
> import assert from 'assert'
> import { z } from 'zod'
> import { mergeWithEffect, mergeWithEffects } from './mergeWithEffects'
> 
> test(mergeWithEffect.name, () => {
>   const a = z.object({ name: z.string() }).refine(({ name }) => name.length > 0)
>   const b = z.object({ surname: z.string() })
>   const merged = mergeWithEffect(a, b)
>   const result = merged.safeParse({ name: '', surname: '' })
>   assert(!result.success)
>   expect(result.error.errors.length).toEqual(1)
> })
> 
> test(mergeWithEffects.name, () => {
>   const a = z.object({ name: z.string() }).refine(({ name }) => name.length > 0)
>   const b = z.object({ surname: z.string() }).refine(({ surname }) => surname.length > 0)
>   const merged = mergeWithEffects(a, b)
>   const result = merged.safeParse({ name: '', surname: '' })
>   assert(!result.success)
>   expect(result.error.errors.length).toEqual(2)
> })
> ```
> 
> @colinhacks Should I open a PR?

should we PR this solution? @colinhacks

**Comment by lyle-smith** [comment]
I am pretty new to Zod and do not know if this is a very elegant solution and I feel like there are some semantic issues with what I am doing, but I had a goal of extending a UserSchema to allow for different roles to have different kinds of validation. I have refinement steps that I would like performed for every schema extending the UserSchema and refinement steps for one of the schemas extending the UserSchema, StudentSchema.

To have my StudentSchema include all of the properties from my UserSchema and retain the appropriate typing I use .and instead of .extend:


import { z } from 'zod';

export const userSchema = z.object({
  firstName: z
    .string()
    .min(1, 'First name is required'),
  lastName: z
    .string()
    .min(1, 'Last name is required'),
  email: z
    .string()
    .min(1, 'Email is required') // Ensures "required_error" triggers first
    .email('Not a valid email'),
  emailConfirmation: z
    .string()
    .min(1, 'Email confirmation is required')
    .email('Not a valid email'),
}).refine((data) => data.email === data.emailConfirmation, {
  message: 'Emails do not match',
  path: ['emailConfirmation'],
});


const studentSchema = z.object({
  dateOfBirth: z.coerce.date({
    required_error: 'Date of birth is required',
  }),
}).refine(
    (data) =>
      !userAgeUnder18(data),
    {
      message: 'Student too young to create an account.',
      path: ['dateOfBirth'],
    }
).and(userSchema);



I don't feel like this is the ideal way to solve this problem, but this seems to have done the trick for me after a couple hours of banging my head against the wall without finding any simple solutions. I'm not sure if there are any drawbacks to this approach, but it seems like one potential solution to a problem that seems pretty tricky.

**Comment by allen-liaoo** [comment]
You can export a function that takes a callback:
```ts
const sharedSchema = z.object({ … });
export const refineExtendedSharedSchema = (callback: (typeof sharedSchema => typeof sharedSchema)= ((s) => s)) => {
    return callback(sharedSchema).refine(...)
}
```

**Comment by edbordin-linktree** [comment]
I just found this at least partially works around the issue for a use-case where I want to add extra validation constraints to an externally packaged schema that has already had `.refine()` applied to it:

```
function extendZodEffects<T extends z.ZodEffects<z.ZodObject<any>, any, any>>(schema: T, extension: z.ZodSchema) {
  // We can't use .extend() after .refine(), so this is a workaround
  // See https://github.com/colinhacks/zod/issues/454 for more details
  return schema.superRefine((value, ctx) => {
    const result = extension.safeParse(value)
    if (!result.success) {
      result.error.errors.forEach((issue) => ctx.addIssue(issue))
    }
    return result.success
  })
}

//example usage:
const GenericSchema = z
  .object({
    type: z.string(),
    name: z.string()
  })
  .refine((value) => {
    return value.type === 'specific_type' ? value.name.startsWith('specific_name_prefix_') : true
  }, 'Type specific_type requires name to start with specific_name_prefix_')

const ConstrainedSchema = extendZodEffects(
  GenericSchema,
  z.object({
    type: z.literal('different_type')
  })
)```

**Comment by fregante** [comment]
@edbordin-linktree I rewrote your version for v4:

<details><summary>v4 version for error merging</summary>

```ts
const schema = z.object(...).transform(...);

export const alterEnvSchema = (callback: () => z.ZodSchema) => {
  schema = schema.check((ctx) => {
    const result = callback().safeParse(ctx.value);
    if (!result.success) {
      ctx.issues.push(...result.error.issues);
    }
  });
};
```

</details>

But unfortunately your solution only covers requirements, not defaults

**Comment by luisrudge** [comment]
yeah.. really unfortunate that we can't extend a refined schema :( custom functions are fine but ideally it should "Just Work ™"

```typescript
import { z } from 'zod/v4';

const SomethingWithTitle = z
  .object({
    title: z.string().min(1, 'Rubric title is required'),
  })
  .refine(
    (data) => {
      if (data.title.includes('test')) {
        return false;
      }
      return true;
    },
    {
      message: 'Title must not include "test"',
    }
  );

const SomethingWithTitleAndId = SomethingWithTitle.extend({
  id: z.number(),
});

const result = SomethingWithTitleAndId.safeParse({
  title: 'test',
  id: 1,
});

console.log(result);
/**
{
  success: true,
    data: {
      title: "test",
    id: 1,
  },
}
 */

```
