### ISSUE TITLE
typescript doc comments?

### ISSUE THREAD

**Issue by andykais** [colinhacks/zod#457]
Hi, I am working on integrating zod into one of my current projects. In the past I have used a combination of declared typescript types and manual validation. Zod is obviously a lot nicer to use on the validation side, but there is one piece from declaring types that I cannot find a replacement for in zod. That is [doc comments](https://typedoc.org/guides/doccomments/)

E.g. if I have the following struct defined:
```ts
interface Media {
  /**
  * The location of the media file
  */
  filepath: string
}
```

what would the equivalent comment look like in zod? These are important for my project, which relies on deno's documentation generation for user docs (see here https://doc.deno.land/https/raw.githubusercontent.com/andykais/ffmpeg-templates/main/lib/template_input.ts#Template)

**Comment by colinhacks** [comment]
Perhaps @jauco can speak to this?

**Comment by jauco** [comment]
I did a quick test in deno with:

```ts

import {z} from "./src/index.ts";

/**
 * bar blah bak
 */
export const foo = z.object({
    /**
     * foo asd bar
     */
    foo: z.number()
})

export type q = z.infer<typeof foo>

/**
 * bar
 */
 export function foob(): string {
     return ""
 }
```

and running deno doc test.ts returns docstrings for `foob` (a vanilla function) and for the variable `foo` (interpreted as a vanilla variable), but not for the contents of z.object() (logical because that is not a variable but an object literal inside an invocation) and also not for `q`. It appears deno does not use the typescript compiler logic to find type definitions for types, instead it just prints `type q = z.infer<typeof foo>` in the output. Which makes sense of course. It's much more straightforward.

A solution to this might be to add an inverse to `z.infer<>` where you can specify a typescript interface and then assert that your schema matches that interface. 

e.g.

```ts
/**
 * Some docstring
 */
interface MyInterface {
   /**
    * some other docstring.
    */
   prop: string;
}

const schema: z.schemaFor<MyInterface> = z.object({
   prop: z.string().min(5);
})

const schemaThatFailsTypeChecking: z.schemaFor<MyInterface> = z.object({
   prop: z.number()
})

```

where typescript would complain that the second z.object definition cannot be assigned to `z.schemaFor<MyInterface>`

This would also help people that use interfaces that are code-generated from some schema language.

**Comment by andykais** [comment]
It is a working approach, but it is not very DRY. All schemas need to be duplicated. Depending on how large your schemas are, this can become quite verbose

**Comment by andykais** [comment]
is there a way to tell zod that I am building a validator for a particular typescript type, but let typescript interpret the output type from zod? Essentially this:
```ts
const DateValidator: z.Schema<string> = z.string().transform(() => new Date())
```

will give the following error:
```
error: TS2322 [ERROR]: Type 'ZodEffects<ZodString, Date>' is not assignable to type 'ZodType<string, ZodTypeDef, string>'.
  Types of property '_type' are incompatible.
    Type 'Date' is not assignable to type 'string'.
const DateValidator: z.Schema<string> = z.string().transform(() => new Date())
      ~~~~~~~~~~~~~
    at file:///home/andrew/Code/development/ffmpeg-templates/lib/parsers/template.zod_v2.ts:23:7
```

which means that if I want typescript doc comments, I have to declare the input type, the zod validator _and_ the output type. Declaring the input type and the validator was doable, but this feels like way too much overkill

**Comment by andykais** [comment]
I _sort of_ found a solution, which looks like this:

```ts
type Input = {
  username: string
  birthday?: string
}

const Validator = z.object({
  username: z.string()
})


function zod_parse(zod_input: z.infer<typeof Validator>) {
  return Validator.parse(zod_input)
}

function parse(input: Input): z.infer<typeof Validator> {
  return zod_parse(input)
}
```

which will at least yell at me if the zod validator and typescript type get out of sync, but it doesnt account for optional params in the type declaration.

**Comment by scotttrinh** [comment]
In your example, the only issue is that you're using the wrong type for the schema. `Schema` takes three generic arguments: `Output, Ref, Input`, so as the error is telling you, your schema has an output type of `Date`, not `string`. You just need to use `Schema<Date>` or if you want to specify the input type: `Schema<Date, z.ZodTypeDef, string>`.

**Comment by andykais** [comment]
right, but is there a way to _intef_ the output type while constraining the input type only?

**Comment by andykais** [comment]
I imagine the syntax would look more like:
```ts
type InputType = { foo: string } 

const validator = z.object<InputType>({
  foo: z.string()
}).transform(x => x.foo)
```

**Comment by andykais** [comment]
darn. I was hoping this would work
```ts
const DateTimer: z.Schema<z.infer<typeof DateTimer>, z.ZodTypeDef, string> = z.string().transform(() => new Date())
```
but you cant infer a type before a variable is defined.
```
TS2448 [ERROR]: Block-scoped variable 'DateTimer' used before its declaration.
const DateTimer: z.Schema<z.infer<typeof DateTimer>, z.ZodTypeDef, string> = z.string().transform(() => new Date())
```

**Comment by scotttrinh** [comment]
> right, but is there a way to infer the output type while constraining the input type only?

Ahh, you have a case where you want to constrain the input type to get compile-time errors if you pass something unexpected, right? Makes sense.

Maybe something like this?

[CodeSandbox](https://codesandbox.io/s/gifted-newton-msbmd?file=/src/index.ts)

```ts
import test from "tape";
import { z } from "zod";

const constrainedParse = <In, S extends z.ZodType<any, any, In>>(
  schema: S,
  input: In
) => {
  return schema.safeParse(input);
};

const schema = z.object({
  foo: z.string().transform(Date)
});

const valid = { foo: new Date().toISOString() };
const invalid = { foo: 42 };

test("valid", (t) => {
  t.true(constrainedParse(schema, valid).success);
  t.false(constrainedParse(schema, invalid).success); // Compiler error
  t.end();
});

test("invalid", (t) => {
  t.end();
});
```

**Comment by andykais** [comment]
not exactly, what I want is to get compile time errors on the _zod definition_ because a typescript interface is my source of truth, and the zod parser is my implementation of the typescript interface. Your snippet does give me an idea though.

```
import * as z from 'https://deno.land/x/zod@v3.9.0/mod.ts'

interface Input {
  foo: string
  bar?: string
}


const InputParser = z.object({
  foo: z.string(), // typescript will yell if this field isnt present
  // bar: z.string(), // typescript unfortunately does not error whether this field is present or not
}).transform(data => data.foo)

const parse_factory = <Output>(schema: z.Schema<Output, any, Input>) => (input: Input) => schema.parse(input)

const parse = parse_factory(InputParser)
```
unfortunately optional parameters seem to slip through the cracks.

**Comment by scotttrinh** [comment]
@andykais 

Yeah, I mentioned this in a different comment today, but you'll find it hard due to structural typing to use the types as your source of truth. Since the type of your parser correctly implements the interface you've defined, it won't catch things like missing `null` or `undefined` or `optional` or even things like:


```ts
interface Foo {
  bar: "baz" | "quux";
}

const fooSchema: ZodType<Foo> = z.object({
  bar: z.literal("baz"),
});
```

You'll find it much easier and less prone to edge cases if you treat your schemas as the source of truth about the types/interfaces of your domain, if possible. Otherwise, you'll need to fallback on things like code generation to ensure that you're defining your schemas correctly.

**Comment by andykais** [comment]
> You'll find it much easier and less prone to edge cases if you treat your schemas as the source of truth

Well the whole point of this issue is that documentation tools using zod as the source of truth are insufficient. I understand that this is a limitation of the language though.

**Comment by colinhacks** [comment]
In TypeScript "inference" only happens inside of function calls or conditional types. The `z.infer` is just pulling out a previously inferred type from the schema, not actively "inferring" anything.

You can both constrain the input type and infer the output type using a utility function:

```ts
function infer<Output, T extends z.ZodType<Output, any, string>>(schema: T) {
  return schema;
}
const schema = infer(z.string().transform(val => new Date(val)));
type input = z.input<typeof schema>;
type output = z.output<typeof schema>;
```

Not sure if this helps with the broader problem though.

**Comment by andykais** [comment]
yeah this unfortunately doesnt help with the missing properties issue. Typescript is happy accepting a subset of the type specified. That means any unions only need to implement one acceptable type. I need a way to tell typescript that I need this function parameter to implement exactly this type

**Comment by andykais** [comment]
just going to add this to the pile of referenced issues under https://github.com/microsoft/TypeScript/issues/12936. That seems to be where the effort for "Exact" types is focused

**Comment by andykais** [comment]
So found a solution...Its a bit odd though.
```ts
// type-equality.ts

// Give "any" its own class
export class Any {
  private _: true  = true;
}

// Conditional returns can enforce identical types.
// See here: https://github.com/Microsoft/TypeScript/issues/27024#issuecomment-421529650
// prettier-ignore
type TestExact<Left, Right> =
  (<U>() => U extends Left ? 1 : 0) extends (<U>() => U extends Right ? 1 : 0) ? Any : never;

type IsAny<T> = Any extends T ? ([T] extends [Any] ? 1 : 0) : 0;

export type Test<Left, Right> = IsAny<Left> extends 1
  ? IsAny<Right> extends 1
    ? 1
    : "❌ Left type is 'any' but right type is not"
  : IsAny<Right> extends 1
  ? "❌ Right type is 'any' but left type is not"
  : [Left] extends [Right]
  ? [Right] extends [Left]
    ? Any extends TestExact<Left, Right>
      ? 1
      : "❌ Unexpected or missing 'readonly' property"
    : "❌ Right type is not assignable to left type"
  : "❌ Left type is not assignable to right type";

type Assert<T, U> = U extends 1
  ? T // No error.
  : IsAny<T> extends 1
  ? never // Ensure "any" is refused.
  : U; // Return the error message.

/**
 * Raise a compiler error when both argument types are not identical.
 */
export const assert: <Left, Right>(
  left: Assert<Left, Test<Left, Right>>,
  right: Assert<Right, Test<Left, Right>>
) => Right = (l, r) => r as any;
```

```ts
import { assert } from './type-equality.ts'

interface Foo {
  bar: string
  baz?: string
  bot: 'a' | 'b'
}

const FooValidator = z.object({
  bar: z.string(),
  baz: z.string().optional(), // removing this line gives the error
  bot: z.union([z.literal('a'), z.literal('b')]), // removing a literal from the union gives the error
})

assert({} as z.input<typeof FooValidator>, {} as Foo)
```

removing either of the fields commented on above gives an error like so:
```
TS2345 [ERROR]: Argument of type '{ bar: string; }' is not assignable to parameter of type '"❌ Unexpected or missing 'readonly' property"'.
assert({} as z.input<typeof FooValidator>, {} as Foo)
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I ripped the `type-equality.ts` implementation from an SO post which I cant find at the moment, but it does appear there are more sophisticated equality functions available. Like those mentioned in this issue https://github.com/microsoft/TypeScript/issues/27024

**Comment by andykais** [comment]
@ptboyer thanks for sharing. I ended up going with an existing library https://github.com/DetachHead/ts-helpers/issues/97. If thats missing some use cases then let them know! Until ts-helpers publishes to deno.land https://github.com/DetachHead/ts-helpers/issues/107, the imports look like this:
```ts
import { exactly } from 'http://esm.sh/@detachhead/ts-helpers@9.0.0-9b4a478c3a63affa1f7f29aeabc2e5f76583ddfc/dist/utilityFunctions/misc'
```

**Comment by umstek** [comment]
I think it works now :)
