### ISSUE TITLE
feature: prepare

### ISSUE THREAD

**Issue by bitlab-code** [colinhacks/zod#463]
What do you think about adding a new `.prepare()` method
- problem:
```typescript
const emailSchema = z.string().email()
emailSchema.parse(" aaa@bbb.ccc "); // throws Error
```
but - if trimmed - it's a valid email, I can accept it.

- solution:
 ```typescript
const emailSchema = z.string().email().prepare(v => v.trim())
// and more concisely
const trimmed = v => v.trim()
z.string(trimmed).email()
```

You can add a parameter (without breaking change) and/or a new method (i.e. prepare), both accept a value that is of type `T` just like transform

this is only a toy-example there're a lot of real use case

[edit]
this solution is inspired to .transform() but act before the validation.

**Comment by bitlab-code** [comment]
@colinhacks I've took a look at code, I can PR if you are interested in this

**Comment by colinhacks** [comment]
I was planning to implement this as a method called `preprocess`. Feel free to take a stab at this PR!

**Comment by bitlab-code** [comment]
Hi @colinhacks,  opened a draft PR #468 .
but there is and issue with `optional`, `nullable` and `default` (don't pass the test) 😕
