### ISSUE TITLE
New feature - custom methods

### ISSUE THREAD

**Issue by julianomqs** [colinhacks/zod#464]
Hello,

It would be nice if Zod accepted adding custom methods to the chain, like this:

```javascript
import { z } from "zod";

z.string().startingWithA().parse("B"); // error
```

The custom method would be like a `refine` but in the chain of methods of schema.

The use case would be more intuitive schemas, instead of importing `zod` and custom `refine` functions, I just import my custom schemas with the custom methods.

I use this for string functions like `cpfCnpj` (an SSN in my country), `phone`, etc.

I'm using Zod v2 and I managed to do this extending the `ZodString` class, but in Zod v3 the `ZodString` code changed and I couldn't make it work anymore, so I'm stuck in Zod v2.

Also extending the class would leave the code more susceptible to changes in the parent classes, like from Zod v2 to Zod v3, so a native solution would be better.

Thanks.

**Comment by colinhacks** [comment]
What's the proposed API for this?

FYI this isn't likely, subclassing is definitely the way to go here. Why don't you create another issue so I can help you fix your ZodString subclass code.

**Comment by julianomqs** [comment]
I will create another issue and share my code like you said.

Thank you.

**Comment by vuki656** [comment]
For anyone that encounters this inconvenience, you can create a wrapper around Zod that will do pretty much the same thing that @julianomqs proposes just without extending. 

This is pretty much the same thing @colinhacks proposed as a solution [here](https://github.com/colinhacks/zod/issues/465#issuecomment-847479217) in #465 except its put into a class and can behave almost identical as native `z` (zod methods) stuff.

Here is the custom wrapper example where you can create whatever you'd like: 

    export class zc {
        static trim = (data: string) => {
            return data.trim() === data
        }
    
        static requiredString = (): z.ZodEffects<z.ZodString, string> => {
            return z.string()
                .min(1, ValidationErrors.Required)
                .refine(zc.trim, ValidationErrors.Trim)
        }
    
        static string = (): z.ZodEffects<z.ZodString, string> => {
            return z.string().refine(zc.trim, ValidationErrors.Trim)
        }
    
        static email = (): z.ZodString => {
            return z.string().email(ValidationErrors.Email)
        }
    }


Usage: 

    export const userFormValidationSchema = z.object({
        company: zc.string(),
        department: zc.string(),
        displayName: zc.requiredString(),
        email: zc.email(),
        firstName: zc.requiredString(),
        lastName: zc.requiredString(),
        mobilePhone: zc.requiredString(),
        position: zc.string(),
    })

And you still have the ability to chain native `Zod` stuff on it like so: 

    export const customSchema = z.object({
        company: zc.string().nullable().optional(),
    })
