### ISSUE TITLE
Complex type coercion

### ISSUE THREAD

**Issue by mildfuzz** [colinhacks/zod#467]
We have an issue where we are using Zod to apply strong typing practices to our API layer

Trouble we have is using complex object over GET, as everything becomes a string over the wire. 

Are we able to attempt deep object coercion with Zod? Something like:

```typescript
const schema = z.object({example: z.number()})

const data = {example: '100'}

const coersedData = scheme.coerce(data) // {example: 100}

const brokenData = {example: 'lemon'}

scheme.coerce(brokenData) // Error
```

**Comment by scotttrinh** [comment]
You can use `refine` and `transform` for this. In your example, I think something like this should work:

```ts
import { z } from "zod";

const schema = z.object({
  example: z.string()
    .refine((maybeNumber: string) => /^\d+\.{0,1}\d*$/.test(maybeNumber)) // or whatever your domain wants here
    .transform((maybeNumber: string) => Number(maybeNumber)), // or parseInt or whatever
});

const data = { example: '100' };
const parsed = schema.parse(data);

const brokenData = { example: 'lemon' };
const safe = schema.safeParse(brokenData);
```

[TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFAxhAHYDO8D1AFgKYgCGcAvCgDoIAIwBW7ajAAUCCnDjsAHl3AAbdgC5BTKMDoBzKQEo58uAKjtMe9lKncAnsPYA5AK4hnULTr36jfAB8cAD0AHoAOsQA1BECCAAMADQAjGhRAFQAJCECMOxM9lxOrh5eRgEhIXDQcADurFz5AG7sUHAOEG7txLhcevVcdDAMcByWpvJ5UEMMmNAgdo7O7p5tPjC6BgG8wateRSX7bRVJodW1YFxQDOwAksM17Q1N7K1QFGhGlDT0THDEJo8fhIJQqMDqLQAchSCQSUPQlFojHgVxu7GIfDgLA43AEaNuUkBMC43yoyP+whwAGt2HQACJArGg5RqTRwKHqED0BFoJF-ZhcTDsLE4zhcAQMIXsAAK10JVIgtIZQLJQA)

**Comment by scotttrinh** [comment]
There isn't really a general purpose coercion that is safe for any arbitrary string inputs, I would think. Especially not if you consider unions that might be able to match both paths depending on what you're coercing into like a `"123"` being coercible into a `Number` or a `Date`, etc, or the string `10e1000` (like a git ref) being coercible into a `Number`.

Maybe a project like [`transit-js`](https://github.com/cognitect/transit-js) is closer to what you're looking for? Transit is more focused on making sure type information is deserialized correctly, but I believe it requires you to control both the sender and the receiver.

**Comment by scotttrinh** [comment]
You can also write your own parser with `z.custom` if you want to be able to leverage all of the plumbing that Zod provides, but your use case is not covered here.

If you provide some more realistic sample inputs, maybe we can collaborate on coming up with a helpful schema?

**Comment by mildfuzz** [comment]
Hmm, am I missing something? `z.custom` doesn't seem to be in the docs

**Comment by mildfuzz** [comment]
I guess for me, it's less about the false positives, and more about the usefulness of type coersion. I *know* that the object I sent over the wire confirms to my type, because I tested it before I made the request, but I also know that all my values will become strings in transit, and I want a convenient way to re-use the schema I have already defined to coerce the data back into the state I wish it to be in, if that make sense?

**Comment by scotttrinh** [comment]
>  I know that the object I sent over the wire confirms to my type, because I tested it before I made the request, but I also know that all my values will become strings in transit, and I want a convenient way to re-use the schema I have already defined to coerce the data back into the state I wish it to be in, if that make sense?

Seems like a good application of transit, but I _think_ you can write a helper that uses the `ZodShape` of your schema to do this conversion. I'm also interested in a general purpose solution since I have some code that serializes subresources as JSON in a database query and it would be nice to not have to write the separate transformer-based schemas that deserialize them.

> Hmm, am I missing something? z.custom doesn't seem to be in the docs

Yeah, not sure why they're not in the latest docs, but it's really just a refinement overt the `z.any` type: https://github.com/colinhacks/zod/blob/11aba3cc6bd430eec8260c4037265925709f924a/src/types.ts#L2839-L2845

**Comment by colinhacks** [comment]
@mildfuzz something like this will be possible in userland using [preprocess](https://github.com/colinhacks/zod/pull/468) once it's available. Currently you'd have to use the approaches Scott mentioned; there's no affordance for pre-parse transformations (only post).

**Comment by nicholaschiang** [comment]
@mildfuzz I encountered something similar and just used what @scotttrinh mentioned. I found that if you simply reuse your complex `refine` and `transform` types, your definitions can stay pretty readable:

```typescript
const date = z.string().refine((d) => !Number.isNaN(Date.parse(d))).transform((d) => new Date(d));
const Timeslot = z.object({
  id: z.string(),
  from: date,
  to: date,
  exdates: z.array(date).optional(),
  recur: z.string().optional(),
  last: date.optional(),
});
```

**Comment by mildfuzz** [comment]
Problem is when you want to do something to schemas you don't know about, for example using a schema to parse arbitrary GET requests in a reusable way.

**Comment by scotttrinh** [comment]
@mildfuzz what could you usefully assert about query parameters at runtime about an "arbitrary GET request" other than `Record<string, string>`?

**Comment by mildfuzz** [comment]
Well, this is sort of the point. I am using this in a generic http helper, so I don't know the schema ahead of time

```httpHelper<T>(schema: ZodType<T>){
//magic
}```

so we might have a data model like: 

```
const myAPiSchema = z.object({number: z.number(), string: z.string()})
```

I can then use the schema to check that data going to and from the API conforms to the schema. Works great, unless it's over GET, then all the values become strings and we need to add a transformer method to convert the data before parsing with zod.

**Comment by mildfuzz** [comment]
this is the actual code:
```typescript
export function apiFor<
  T extends BaseApiSchema,
  U extends Record<string, unknown>
>(apiPath: string, requestSchema: ZodType<T>, responseSchema?: ZodType<U>) {
  // eslint-disable-next-line consistent-return
  return async ({request, opts}: HttpParams<T>): Promise<ApiForResponse<U>> => {
    logger.debug(
      `apiFor: Request for ${apiPath}: ${
        requestSchema.check(request) ? 'Pass' : 'Fail'
      }`,
    )
    logger.debug(JSON.stringify(request, null, 4))
    const {method, body: parsedBody} = requestSchema.parse(request)
    const headers: HeadersInit = {
      'content-type': 'application/json-patch+json',
      accept: '*/*',
      ...(opts?.headers ?? {}),
    }
    const body = method !== 'GET' ? parsedBody : null
    const parsedOpts: RequestInit = {
      ...opts,
      ...(body ? {body: JSON.stringify(body)} : {}),
      headers,
      method,
      mode: 'cors',
      credentials: 'include',
    }

    const requestPath =
      method !== 'GET'
        ? apiPath
        : `${apiPath}?${new URLSearchParams(parsedBody).toString()}`

    try {
      const res = await fetch(requestPath, parsedOpts)
      if (responseSchema) {
        const clonedResponse = res.clone()
        if (responseSchema) {
          clonedResponse.json = async (): Promise<U> => {
            const json = await res.json()
            logger.debug(
              `apiFor: Response from ${apiPath}: ${
                responseSchema.check(json) ? 'Pass' : 'Fail'
              }`,
            )
            logger.debug(JSON.stringify(json, null, 4))
            return responseSchema.parse(json)
          }
        }

        return clonedResponse
      }
      return res
    } catch (e) {
      logger.debug(`API error: ${apiPath}`)
      logger.debug(e)
    }
  }
}

```

**Comment by scotttrinh** [comment]
@mildfuzz 

Yeah, that makes sense. I have a similar problem in my application where roundtrips over the network lose some fidelity like `Date -> String`, too. I haven't found a general purpose solution here, but being able to define a schema transformer would be a nice thing to have. Adding a special case of that transformation for `String -> T` seems like something the core library would not take on, and like I mentioned early, I don't think there is anything we could do to generically convert from `unknown -> T`.

We currently solve this by defining `Serialized<T>` schemas that extend the base schema with `String -> T` transformers. Something like this:
[TypeScript Playground](https://www.typescriptlang.org/play?ts=4.2.3#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFAxhAHYDO8YAplA-QMrUAWLIAQzgBeFADoIAIwBWLajAAUCCnDh0BIFgC5xTKMDoBzBQEoANCrjUoLATBbEAgjB3IxxOy1MW0JyjABPVjgABTYOOhFxAzAAVxgAHkDWCEw4VnYuXn4BAD5KGnomOAY2YAEAG2BkBzDMum4+QSiMiMacsRYAD3s6YiVLa1t7JxddGH0jUzEJgUZMaBAFBQ97TgmDQxMRXLUWAHc4ABFPFc91ya3zCl9-IJY4TjLK6trw+ii3CHi4xOSWVIlZ5VGrEOptbKCfJAA)

```ts
import { z } from "zod";

const personSchema = z.object({
  name: z.string(),
  createdAt: z.date(),
});
type Person = z.input<typeof personSchema>;

const serializedPersonSchema = personSchema.extend({
  createdAt: z.string().transform((dateString) => new Date(dateString)),
});
type SerializedPerson = z.output<typeof serializedPersonSchema>;
```

You could also [define your base schema to take a union of types as inputs and then use `transform` to unify them into your application's domain model](https://www.typescriptlang.org/play?ts=4.2.3#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFAxhAHYDO8YAplA-QMrUAWLIAQzgBeFADoIAIwBWLajAAUCCnDh0BIFgC5xTKMDoBzBQEoANCrjUoLATBbEAgjB3IxAVzrB6CgNpviOxZTM10YfSNTAF0TMXCBRkxoEAUFQQBPSRYAESCAeShOcINDExEAPjUWAHc4XPs0gUyc-MLioxNzCjQTShh01jgABTYOOhFxCHcYMGmAHn7WCEw4VnYuXn4BcrIgA), but I personally would prefer to do it explicitly.

**Comment by itsfarseen** [comment]
@scotttrinh I had exactly the same problem. I solved it by using superjson. No need to have more schemas or complicated transforms :)

Basically, serialize/deserialize using superjson instead of standard JSON module. Superjson emits metadata along with the values so that a Date() is serialized and deserialized back to a Date().

**Comment by scotttrinh** [comment]
@itsfarseen 

Yeah, that is a similar approach to Transit. 👍
