### ISSUE TITLE
feature request: 'shape'-like method for array()

### ISSUE THREAD

**Issue by ehahn9** [colinhacks/zod#484]
You can get the shape of an object schema but I don't see a way to get the schema for `array` items? Maybe:

- `array.shape`
- `array.unpack` (to follow the typescript terminology)
- `array.item` or `array.each`

I suppose the same could be asked about `record()`, etc.?

**Comment by GitUT** [comment]
I would also like this although you can work around it

**Comment by colinhacks** [comment]
It's `element` — sorry, not documented.
