### ISSUE TITLE
Add a custom context field to ParseParams

### ISSUE THREAD

**Issue by JonasZ95** [colinhacks/zod#487]
I would like to add an extra field called something like userContext to ParseParams which is passed to all parse and later refine calls. The idea behind this is allowing to set something like a API client as context which could be used with refine. Small example:

```
interface UserService {
  checkUniqueEmail(mail: string): Promise<boolean>;
}

const uniqueEmail = z.string().superRefine(async (mail, ctx) => {
  const userService = ctx.userContext as UserService;
  return await userService.checkUniqueEmail(mail);
});
```

**Comment by colinhacks** [comment]
I'd strongly recommend against this pattern. Implementing schemas that depend on certain params being passed into `.parse` breaks encapsulation. Schemas should contain all the information/configuration they need to do their job. This is especially bad since there's no way for Zod/TypeScript to enforce this. Consider using factories & closures to achieve this:

```ts
const schemaForService = (userService: UserService)=>{
  return z.string().superRefine(async (mail) => {
    return await userService.checkUniqueEmail(mail);
  });
}
```

**Comment by JonasZ95** [comment]
While I agree with you about how parse should work, It's also feeling wrong to recreate the whole schema. This is very relevant in React libs/apps which would either recreate the whole schema for each render call component is created or If you use 'useMemo'  each time an instance of the component is created. Since we also auto-generate the Zod schemas from our swagger specification, adding an extra field seemed to be the easiest way to do this. I tried to play around with a global cache, but It resulted in alot of boilerplate quote and the typescript compiler also had some problems properly deducing the types.
