### ISSUE TITLE
Unknown fields are optional

### ISSUE THREAD

**Issue by carlpaten** [colinhacks/zod#493]
This looks like a spec bug, tsc's `unknown` means "I don't care what's there as long as there's something". Meanwhile with Zod:

```tsc
const x = z.object({ a: z.unknown() });
// type T = {a?: unknown}
type T = z.infer<typeof x>;
```

Do you agree that this is a bug? Should we fix it in place, or surface a new combinator in order not to break backwards compatibility?

**Comment by colinhacks** [comment]
Fixed in 3.3.0 by #494

**Comment by lilred** [comment]
Reopening as the fix was rolled back https://github.com/colinhacks/zod/issues/519#issuecomment-874891729

**Comment by lilred** [comment]
Ah, that's embarrassing, I don't have permission to reopen this issue. @colinhacks would you please do that?

**Comment by colinhacks** [comment]
I've invited you to join the repo as an admin but it still says "invitation pending", maybe check spam? I just resent it as well 👍

**Comment by markandrus** [comment]
I just noticed this myself when [checking for equality](https://www.google.com/search?client=firefox-b-d&q=equ+refl+typescript) of the following two types:

```ts
type x1 = { x: unknown }
```

```ts
const x2 = z.object({ x: z.unknown() })
type x2 = z.infer<typeof x2>
// { x?: unknown }
```

```ts
type Equ<A, B> = [A] extends [B] ? [B] extends [A] ? {} : never : never
const pf: Equ<x1, x2> = {}
// error TS2322: Type '{}' is not assignable to type 'never'.
```

**Comment by Hives** [comment]
this seems to still be an issue
