### ISSUE TITLE
Support for number granularity

### ISSUE THREAD

**Issue by DavidRigglemanININ** [colinhacks/zod#501]
I'm just starting to get familiar with the library and have to say I am impressed so far with the ease use and ability to customize. One thing we use a lot in our schema validation that seems to be missing is granularity. In other words something like z.number().int().min(5).max(30).granularity(5) would allow 5, 10, 15, 20, 25, and 30. Without built in support, I assume the best way to accomplish this would be with refine or superrefine? And I assume those can be tacked on to the end of the built in validations so I don't have to reinvent those validators. Thanks so much!

**Comment by colinhacks** [comment]
Yep, I recommend a refinement for this, which, as you say, can be tacked on after the other methods. I don't think this feature is popular enough to merit a new method in core. You can make this logic very portable with function factories:

```ts
const multipleOf = (base: number)=>(val: number)=>val % base === 0;
const myNum = z.number().int().refine(multipleOf(5));
```
