### ISSUE TITLE
can Zod make each field of the schema optional?

### ISSUE THREAD

**Issue by zhenhao18** [colinhacks/zod#502]
I am using Zod to validate JSON format before adding or partial updating one document into the database, so each case will require a schema.
For adding, all the files can be nonoptional, for partial updating, all the fields need to be optional by default, I've tried to use z.optionsl(ExistingObjectSchema), or ExistingObjectSchema).optional(), both can't work as I expect. is Zod support this feature?

`
const  ExistingObjectSchema = z
            .object({
                name: z.string(),
                age: z.number()
            })
`
how to make both name and age optional? do I have to define a new schema like this?
`const  optionalSchema = z
            .object({
                name: z.string().optional(),
                age: z.number().optional()
            })
`

Thanks a lot.

**Comment by kontheocharis** [comment]
See https://github.com/colinhacks/zod#partial

**Comment by zhenhao18** [comment]
Wow, Thank you @kontheocharis ! that's what I expected!
