### ISSUE TITLE
Alternative to superstruct Describe

### ISSUE THREAD

**Issue by Djaler** [colinhacks/zod#503]
In Superstruct the Describe utility returns a type representing a struct for a given valid value type. This allows you to ensure you're writing your struct definitions properly.

```
type User = {
  id: number
  name: string
}

const User: Describe<User> = object({
  id: string(), // This mistake will fail to pass type checking!
  name: string(),
})
```

Is there a way to do something like this in zod?

**Comment by scotttrinh** [comment]
@Djaler 

If you already have a defined type before specifying the schema, you can use that type as the generic argument to `z.object` like this:

[TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFMAnmAKZwCqAzvVHALyIVxzDEAXHAB2AVxAAjdr1EBDEPWEsYUYCIDmFNFQDGEESuZsO3ZADoIkgFb1dMADyt2APgAUCWQOEWVazW4AlAA0cAD0YXAAKgAWwCxwIPEwcgDWjADuwAA22VhyOXAwEHBgciwJtAxwujF2qeoaAISyIgpKKOZ+jUHB2oEUQA)

```ts
import { z } from "zod";

type User = {
  id: number
  name: string
}

const User = z.object<User>({ // You get a type error here
  id: z.string(),
  name: z.string(),
})
```

**Comment by Djaler** [comment]
Hmm, I tried to change id to `z.number()`, but I still get an error.
[Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFMAnmAKZwCqAzvVHALyIVxzDEAXHAB2AVxAAjdr1EBDEPWEsYUYCIDmFNFQDGEESuZsO3ZADoIkgFb1dMADyt2APgAUCWQOEXxU9m4AlAA0siIKSijmKmqaQaFogRRAA)

**Comment by scotttrinh** [comment]
@Djaler ahh, you're totally right, it is expecting a `ZodShape` not a final type. I usually go the other way and infer the type from the schema, so I'm a bit rusty on this. I was pretty sure there was a way to do this, so lemme take another swing at it.

**Comment by scotttrinh** [comment]
@Djaler Figured it out!

[TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFMAnmAKZwCqAzvVHALyIVxzDEAXHAB2AVxAAjdr1EBDEPWEsYUYCIDmFNFQDGEESuZsow5ADoAWiQDKugBb0QcgDyt2APi4pzESQCt6XRgACgRZATNzFTVNEIBKABpZEQUlHxj1DQTktHiKIA)

```ts
import { z } from "zod";

type User = {
  id: number
  name: string
}

const User: z.ZodSchema<User> = z.object({
  id: z.string(),
  name: z.string(),
})
```

It's `ZodSchema`! h/t 🎩 to https://github.com/colinhacks/zod/issues/372#issuecomment-810905204

**Comment by Djaler** [comment]
Thanks, that's it.
I need this because sometimes types are provided from a library and I want to write a schema for it.

**Comment by Djaler** [comment]
Can you help me with one case?

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFwAdjAKZSYCGAxvXABLADOM0ATwA8AFQB8iCnDj06UAQC44IymiqYArjVYxgEGnAAWvfvIDymUTIAeDGsR4oAdAC0SAZVaH6IZkOY0AmJiABSyMPJKIgCUSsiuHl4+ftx8gkLxtJiMosESCFJwUPQwGlAG8RAARgBW9DohBdLS4ZEycgIANIVo0RRoQA

Similar, but working case - https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFwAdjAKZSYCGAxvXAArMDm9APABUAfIgpw49OlACeALjiCA2gF1KaKpgCuNVjGAQacABbAAzjGgyA8piGSAHgxrEzKAHQAtEgGVWx+hBmfmYaGWFhAAopGFkFQQBKBWQvX39A4O4+fhTaTEYhCNEEcTgoehgtKCMUiAAjACt6PUiSiQkYuI9mKChmGWjpGQSAGlK0BIo0IA

**Comment by scotttrinh** [comment]
Hmm, nothing comes immediately to mind here. Dynamic schema creation is definitely a hard thing to get working in my experience, so maybe someone else has some good ideas here?

**Comment by Djaler** [comment]
@colinhacks can you help, please?

**Comment by colinhacks** [comment]
This is the recommended way to write a schema that implements a particular static type, try it instead:
 https://github.com/colinhacks/zod/issues/372#issuecomment-826380330

**Comment by Djaler** [comment]
Sorry, I tried, but still don't understand how to do this
