### ISSUE TITLE
When using unions, .parse will not match to the correct type

### ISSUE THREAD

**Issue by markhughes** [colinhacks/zod#504]
Please see the example here: https://github.com/markhughes/zod-bug-minimum-repro

You will notice our union here:
https://github.com/markhughes/zod-bug-minimum-repro/blob/main/src/model.ts#L100-L112

We use this in our validator:
https://github.com/markhughes/zod-bug-minimum-repro/blob/main/src/validators.ts#L5-L15

Here is an example with the `accountId` key which would only match `CakeAcruSchema`:

https://github.com/markhughes/zod-bug-minimum-repro/blob/main/src/index.ts#L5-L31

When we run this, it seems to strip it out and revert to the base format:

```
$ ts-node src/index.ts
Starting test...
cakes in:
[{"cake":{"accountId":"f8abcccc","firmId":"483e0314","icon":"Acru","mixerId":"787521c1","name":"Default Cake","cakeId":"ea4ededc","cakeType":"Acru"},"recipients":[{"firstName":"Mark","lastName":"Hughes","email":"m@rkhugh.es","accessType":1}]}]

cakes parsed:
[{"cake":{"cakeId":"ea4ededc","mixerId":"787521c1","cakeType":"Acru","name":"Default Cake","icon":"Acru"},"recipients":[{"firstName":"Mark","lastName":"Hughes","email":"m@rkhugh.es","accessType":1}]}]    
Done in 2.85s.
```

However, if we go back to our union:
https://github.com/markhughes/zod-bug-minimum-repro/blob/main/src/model.ts#L100-L112

And move `CakeAcruSchema` under `CakeApplesSchema` - it seems to parse properly.

What has happened here?

**Comment by scotttrinh** [comment]
This seems like the case where the unions don't have a clear discriminant so the first union member that matches will be the schema that is used. If you redeclare the literal `cakeType` down to the individual schemas, it _should_ work?

```ts
export const CakeApplesSchema = CakeSchema.extend({
  transactionNo: z.string(),
  cakeType: z.literal(CakeType.Apple),
  type: z.nativeEnum(AppleType),
})
```
etc. etc.

Something like that?

**Comment by markhughes** [comment]
Ahh okay. I suppose `z.literal` will help "hint" towards the right match. Let me try it out and see.

**Comment by colinhacks** [comment]
Yeah, union schemas "short circuit" (return a value) as soon as one of its "option schemas" parses the input successfully. Plus a dedicated literal discriminator is required for discriminated unions to work properly; that's a TypeScript thing, not a Zod thing: https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions
