### ISSUE TITLE
Zod 3 `transform` breaking change

### ISSUE THREAD

**Issue by azhiv** [colinhacks/zod#505]
In version 2 we utilised `zod.transform` method to transform an object into an array, and validated each array item. Using `zod.array` directly resulted in parse error 'Expected an array, received object'.

Background: in Ember Data `hasMany` relations are essentially objects, but semantically they represent collections: they treat themselves as array-like structures with implementation of `map`, `filter` and others, and capable of returning a true array via `toArray` method.

Version 2 code:
```typescript
interface SyncHasMany<T> {
  // ...
  toArray(): T[];
}

function hasMany<T extends zod.ZodTypeAny>(itemSchema: T): zod.ZodTransformer<zod.ZodUnknown, zod.ZodArray<T>> {
  return zod.unknown().transform(
    zod.array(itemSchema),
    // In case it is hasMany we should convert it to plain Array so Zod can digest it.
    rel => Array.isArray(rel) ? rel as zod.TypeOf<T>[] : (rel as SyncHasMany<zod.TypeOf<T>>).toArray(),
  );
}
```

But in ver. 3 this approach is no longer available. The question is how can I achieve the same result now? I want zod to validate a `hasMany` relation using `zod.array(itemSchema)` schema as if the content of this relation was a plain array.

**Comment by colinhacks** [comment]
This should work:

```ts
interface SyncHasMany<T> {
    // ...
    toArray(): T[];
  }

  function hasMany<T extends z.ZodTypeAny>(itemSchema: T) {
    return z
      .unknown()
      .transform(
        // z.array(itemSchema),
        // In case it is hasMany we should convert it to plain Array so Zod can digest it.
        (rel) => {
          console.log(rel);
          return Array.isArray(rel)
            ? (rel as z.TypeOf<T>[])
            : (rel as SyncHasMany<z.TypeOf<T>>).toArray();
        }
      )
      .refine((arr) => {
        console.log(arr);
        return arr.every((el) => itemSchema.safeParse(el).success);
      });
  }
```

**Comment by azhiv** [comment]
Thanks for your answer @colinhacks 
Unfortunately, this approach doesn't produce detailed errors (as it did before in ver. 2). Consider the following setup:
```
const itemSchema = zod.object({
  value: zod.number().positive(),
});

const objectSchema = zod.object({
  items: hasMany(itemSchema),
});
```
So for an object
```
const obj = {
  items: [
    { value: 1 },
    { value: 0 },
  ]
};
```
I'd expect an error with `path: ['items', 1, 'value']` and `message: 'Value should be greater than 0'`

**Comment by azhiv** [comment]
@colinhacks The issue is not resolved. We haven't come up to a solution for the problem described above.

**Comment by colinhacks** [comment]
The solution to this is a `.preprocess` method that let's you apply arbitrary transformations to the input before it is parsed. This is on the roadmap. 

The reason this is so difficult is because Zod 3 now operates under a strict "parse, then transform" paradigm. We intentionally don't provide structured errors after data has been transformed. We want the paths inside ZodError.issue to be reflective of the input as it was passed into `.parse`. There is a long discussion about this design decision here that may be of interest: https://github.com/colinhacks/zod/issues/264

For now this works as a workaround:

```ts
function hasMany<T extends z.ZodTypeAny>(itemSchema: T) {
  return z
    .unknown()
    .transform(
      // z.array(itemSchema),
      // In case it is hasMany we should convert it to plain Array so Zod can digest it.
      (rel) => {
        console.log(rel);
        return Array.isArray(rel)
          ? (rel as z.TypeOf<T>[])
          : (rel as SyncHasMany<z.TypeOf<T>>).toArray();
      }
    )
    .superRefine((arr, ctx) => {
      return arr
        .map((el) => itemSchema.safeParse(el))
        .map((result) => {
          if (!result.success) {
            result.error.issues.map((iss, index) => {
              ctx.addIssue({
                ...iss,
                path: [index, ...iss.path],
              });
            });
          }
        });
    });
}
```

**Comment by azhiv** [comment]
@colinhacks `zod.preprocess` works great, thank you very much!

**Comment by colinhacks** [comment]
Excellent!
