### ISSUE TITLE
Combined refine/transform

### ISSUE THREAD

**Issue by dmurvihill** [colinhacks/zod#506]
Hello,

I'm using `transform()` to base64-decode a value. I'm bumping up against this requirement from the docs:

> ⚠️ Transformation functions must not throw. Make sure to use refinements before the transformer to make sure the input can be parsed by the transformer.

To satisfy this requirement, I am doing this:
```
const schema = string().refine(isBase64).transform(d => Buffer.from(d, 'base64'));

function isBase64(data: string): boolean {
  try {
    Buffer.from(data, 'base64');
  } catch {
    return false;
  }
  return true;
}
```

This implementation is a little silly since I am base64-decoding the object just to check whether I can base64-decode it.

Is there some way to memoize the `Buffer` object created in `refine` call, so that I don't have to double-decode?

**Comment by colinhacks** [comment]
This is a known limitation. Refinements and transforms will be combined into a single concept at some point in the near future. I'll post here when that happens. 👍

**Comment by pepakriz** [comment]
I'm interested in this feature request too.

**Comment by dmurvihill** [comment]
Thanks! Appreciate your hard work.

**Comment by jvliwanag** [comment]
Perhaps a more general approach to this request is to add a way of binding/flatmap of zod values.

**Comment by jvliwanag** [comment]
should we keep this open? it's a very common use case.

**Comment by denis-mludek** [comment]
The combination of refine/transform should be the first step to a more concise API.

A second step should be adding flatMap (or `then` in more JS terms) on validators which would be very handy, eg:

```
// Validate that a string is a valid number (e.g, query string param)
const stringToInt = ...

// unix time -> Date
const timestamp = ...

const timeStampFromQueryString = stringToInt.then(timestamp)
```

**Comment by Eoksni** [comment]
@denis-mludek isn't current `transform` exactly your `then` ?

**Comment by denis-mludek** [comment]
@Eoksni Nope, since `.tranform()` signature doesn't accept a Zod's type validator, I cannot be a `flatMap`.

This doesn't compile:

```
const intFromString = z
    .string()
    .refine((str) => Number.isFinite(Number.parseInt(str)))
    .transform(Number);

const timestamp = z.number().refine(n => {
    const date = new Date(n)
    if (isNaN(date.getTime())) false
    return true
})
.transform(n => new Date(n))

const timeStampFromQueryString = intFromString.transform(timestamp)
```

**Comment by carlpaten** [comment]
Would love this!

**Comment by femioladipo** [comment]
Not sure why this was never mentioned, but [`.preprocess()`](https://zod.dev/api#preprocess) exists which achieves this. So leaving this here to help people in the future as it did with myself.

```ts
const PET_OWNER_SCHEMA = z.object({ ... })

const PET_SCHEMA = z.object({
  age: z.number(),
  animal: z.enum(["cat", "dog", "fish"]),
  owner: z.pipe(
    z.string(),
    z.preprocess(
      (ownerRef) => client.fetch(ownerRef),
      PET_OWNER_SCHEMA
    )
  )
})
```
