### ISSUE TITLE
Merge behavior substitute in zod 3?

### ISSUE THREAD

**Issue by mathulbrich** [colinhacks/zod#508]
## Problem

Since `merge` method receives the same behavior than `extend` in `zod 3` I'm having some problems by merging two objects with same property key using `.and` intersection method. Look the following example:

```typescript
const Animal = z.object({
  properties: z.object({
    is_animal: z.boolean()
  })
});
const Cat = z.object({
  properties: z.object({
    jumped: z.boolean()
  })
}).and(Animal);

const cat = Cat.parse({ properties: { is_animal: true, jumped: true } });
assert.isDefined(cat.properties.jumped); // is not defined, only is_animal is defined
```
There's a way to get the same behavior of old `merge` from `zod 2` in `zod 3` considering this scenario? Using `zod 2` and `merge` method, the `properties` field is merged with both sub-fields.

**Version:** 3.2.0

## Workaround

The workaround that I found basically is something like this (but don't appear to be the best solution in the case you have more than one field):

```typescript
const Cat = z.object({
  properties: z.object({
    jumped: z.boolean()
  }).merge(Animal.shape.properties)
});
```

**Comment by MathUlbrich** [comment]
Can someone help me with that? Would be good if there's already a solution for that, but I don't know.

**Comment by colinhacks** [comment]
Intersections now deep-merge values, upgrade to `zod@latest` for this behavior.
