### ISSUE TITLE
bug: .transform() incorrectly changes ZodSchema

### ISSUE THREAD

**Issue by andykais** [colinhacks/zod#509]
the following snippet fails with error below. Adding a `.transform` method to a zod schema will alter the input type, when it should be only be altering the output type. The output type seems to correctly be just `number`.

```ts
import { z } from 'https://deno.land/x/zod@v3.2/mod.ts'

const percentage_parser = z.string().regex(/\d+%/).transform(str => parseFloat(str.slice(0, -1)) / 100)

function get_percentage(input: z.infer<typeof percentage_parser>) {
  return percentage_parser.parse(input)
}

const result: number = get_percentage('100%')
```

```
error: TS2345 [ERROR]: Argument of type 'string' is not assignable to parameter of type 'number'.
const result: number = get_percentage('100%')
```

here is a screenshot showing the full zod type declaration:

![screenshot(653)](https://user-images.githubusercontent.com/6627147/124212019-27b7dd00-dabc-11eb-9ec9-7e604499f694.png)

**Comment by davidmdm** [comment]
@andykais the code above works as intended. Your percent parser is a schema that transforms the type to a number. So effectively since:

```ts
z.infer<typeof percentage_parser> // evaluates to number because we transform to number

// the two below or equivalent
function get_percentage(input: z.infer<typeof percentage_parser>) { ... }
function get_percentage(input: number) { ... }

// and therefore the following does not and should not compile
get_percentage("of any string")
```

**Comment by andykais** [comment]
oh, alright then. Is there a way to derive the _input_ schema type? E.g. I know `.parse()` accepts an unknown, but its possible that we want to parse a typed data structure and it would be nice to declare the type parameter. E.g. something like this:
```ts
// the two below are equivalent
function get_percentage(input: z.ZodInputSchema<typeof percentage_parser>) { .. }
function get_percentage(input: string) { ... }
```

**Comment by davidmdm** [comment]
@andykais 

Each method returns a new schema. So you can create your input schema and use it's derived type, and create the transformed schema also.

```ts
const percent_input_parser = z.string().regex(/\d+%/)
const percentage_parser = percent_input_parser.transform(() => ...)

function get_percentage(input: z.infer<typeof percent_input_parser>) { ... }
```

**Comment by andykais** [comment]
If I have a sufficently complex and nested parser (e.g. its several objects nested and each does its own transforms) then it is very difficult to compose two different schemas, one for input and one that is transformed. Is there any way to derive the expected input from a schema with transforms?

**Comment by davidmdm** [comment]
Regardless I think you are using it wrong.
The point of schema is to take an unkown value and to give it a type. Sometimes it's to take an unknown value and transform it to a type given certain constraints.

But if you know the input type, you should use it instead of infer it. If you know it's a string and you want a number from it, you don't need zod at all to do that. Zod is useful if you do not know the type of your input, not to type it.

**Comment by andykais** [comment]
> But if you know the input type, you should use it instead of infer it. If you know it's a string and you want a number from it, you don't need zod at all to do that.

That's not exactly true. E.g. I want to input a number that is less than 5, I want a string but it should match a particular regex. There are tons of refinements that can be made which zod makes it easy to declare but that typescript cannot sufficiently express

**Comment by colinhacks** [comment]
@andykais You can use `z.input` instead of `z.infer`. This works for arbitrarily complex schemas and disregards transforms at all levels of depth in your schema. This behavior is documented here: https://github.com/colinhacks/zod#what-about-transforms.
