### ISSUE TITLE
There is no way to determine that an error thrown is a `ZodError`

### ISSUE THREAD

**Issue by giltayar** [colinhacks/zod#515]
In Zod v1, to determine whether a thrown error is an error thrown by Zod, I did `if (error.constructor.name === 'ZodError') {...}`.

In Zod v3, this is not possible anymore (at least when importing the module using ESM), because you minimize the source code, and the name of the constructor becomes `"n"` 😬.

Would love it if there was a way to know if the error is a Zod error. As a suggestion, have the `code` values all start with a `ZOD_ERROR` prefix, or have an `isZodError` field in the error, or perhaps even ensure that the constructor name will still be `ZodError`.

Currently, I'm working around this by a heuristic: checking that the error has a `path` property that is an array. 😱

BTW, kudos for adding ESM support! 🎉

**Comment by giltayar** [comment]
Actually, thinking about it, I can use `instanceof`. I remember that there was a problem with this, and it's not recommended anyway (because of problems with the error thrown from a different realm), but at least it works.

**Comment by colinhacks** [comment]
I use instanceof and I've never experienced any issues. What's the problem with it exactly?

**Comment by giltayar** [comment]
@colinhacks I actually don't remember 😊, but the code spefically uses `error.constructor.name`. But I _did_ have a problem. My guess is that I used Zod in another realm (e.g. a Node.js VM), it threw the exception, and I caught it in the main code.

But as I said above, once I realized I can use `instanceof`,  I'm fine with not fixing this. I'll close it.

And, again, thanks for the ESM support!

**Comment by colinhacks** [comment]
You bet :)

**Comment by giltayar** [comment]
I finally remembered why we used `error.constructor.name` (because it happened to us one day after closing this issue 😁). This happens when we `npm link` to a package that also uses Zod. In this case, we have TWO instances of Zod (one in the main package and one in the linked package), so if the linked package throws a `ZodError` and the main package catches it, it can't use `instanceof ZodError`, because each package has its own `ZodError`.

What we're currently doing as a hack to workaround this is:

```js
if (error instanceof ZodError || (process.env.NODE_ENV !== 'production' && error.constructor.name === ZodError.name)) ...
```

The reason we're doing the `error.constructor.name === ZodError.name` only in development is because `ZodError.name` is currently "n" because of the minification, and that seems slightly dangerous to us.

Is this esoteric? I dunno. From what I understand, `instanceof` is not recommended for errors precisely because of this problem (another similar problem to the `npm link` problem is in the browser when you call a function from one Realm, e.g. another frame, and you catch it in another realm. Each Realm may have their own `ZodError`).

Three ways to solve this problem:

1. Have `error.code` have a `ZOD_ERROR_` prefix for all Zod codes.
2. Have an `isZodError` property in the error.
3. Not minify the code, so error.constructor.name will return to being `ZodError`. I believe that even if you decide to minify it, you can instruct the minifier not to minify `ZodError`.

I would prefer option 1, because this is the recommended way of determining what an error is these days, but I understand that this may be a semver-major change. Otherwise, I prefer option 3.

If you would like, I can submit a PR that solves this in one of the above three ways.

**Comment by colinhacks** [comment]
I now manually set `this.name = "ZodError";` in the ZodError constructor so I believe your old approach should work again.

**Comment by giltayar** [comment]
Wow. Thanks! 🙏

**Comment by andredewaard** [comment]
```ts
error instanceof ZodError || (import.meta.env.NODE_ENV !== 'production' && error?.constructor?.name === ZodError.name)
```
Is this still the way to go? if i bundle this into a vite library and use it inside another project it keeps returning false. is there any reliable way to check if an error is an ZodError?

**Comment by patrickshipe** [comment]
@colinhacks I would love to see this issue reopened... We are converting a codebase from CJS to ESM. However, some dependencies still are using CJS which import zod. Even when `node_modules` is deduped and there is only one Zod version, the imported and required classes are "different." The `name` thing works, but given that it relies on an internal implementation detail of Zod, wouldn't it be best if we exposed a utility function so the solution wouldn't be so brittle as Zod evolves?
