### ISSUE TITLE
How to I get the value of a ZodLiteral?

### ISSUE THREAD

**Issue by SlateDave** [colinhacks/zod#517]
I have an example union like this:

```typescript
const example = z.union( [
    z.literal( 'A' ),
    z.literal( 'B' )
] );
```

What would be the correct way to get all the options as a string array like `('A' | 'B')[]`?

Some of my attempts include:
```typescript
const exampleOptions = example.options.map( ( literal ) => literal._def.value );
const exampleOptions = example.options.map( ( literal ) => literal._type );
const exampleOptions = example.options.map( ( literal ) => literal._input );
const exampleOptions = example.options.map( ( literal ) => literal._output );
```

Are any of my attempts valid or is there perhaps a better way? What are the differences between those methods?

**Comment by colinhacks** [comment]
Your first option would work.

`const exampleOptions = example.options.map( ( literal ) => literal._def.value );`

For convenience I just added a getter to the ZodLiteral class in v3.3.4, so you can now retrieve the value of a literal like this:

```ts
const tuna = z.literal("tuna");
tuna.value; // "tuna"
```

If you upgrade to 3.3.4, you can do this, which is cleaner:

```ts
const example = z.union( [
    z.literal( 'A' ),
    z.literal( 'B' )
] );
const exampleOptions = example.options.map( ( literal ) => literal.value );
```
