### ISSUE TITLE
`infer` adds `[x: string]: any;` to type even for strict objects

### ISSUE THREAD

**Issue by coreprocess** [colinhacks/zod#518]
```
import { ObjectId } from 'mongodb';
import * as z from 'zod';

export const TestSchema = z.strictObject({
    _id: z.instanceof(ObjectId),
    test: z.string().nonempty(),
});

export type Test = z.infer<typeof TestSchema>;
```
results in:

```
export type Test = {
    [x: string]: any;
    _id: ObjectId;
    test: string;
};
```

Which is problematic for MongoDB `insertOne` operations, as they cannot successfully make the `_id` optional. When I handcraft the type to

```
export type Test = {
    _id: ObjectId;
    test: string;
};
```

it works fine. But that means I would need to add thousands of lines of code to our project.

Any idea on how we can solve this?

It worked fine with Zod 2.

Edit: The problem gets introduces with 3.3.x. I downgraded tp 3.2.0 and it works fine now.

**Comment by colinhacks** [comment]
Fixed in 3.3.3!
