### ISSUE TITLE
Breaking change to typedef of `_refinement` & `superRefine` in 3.3.0

### ISSUE THREAD

**Issue by larrifax** [colinhacks/zod#520]
After upgrading from `3.2.0` to `3.3.4` I started getting Typescript compilation errors on my `_refinement`-calls.
The new behavior seems to have been introduced in `3.3.0`, and also affects the `superRefine` method.

The behavior can be seen in the example you have in the README for `superRefine`:
```
const Strings = z.array(z.string()).superRefine((val, ctx) => {
  if (val.length > 3) {
    ctx.addIssue({
      code: z.ZodIssueCode.too_big,
      maximum: 3,
      type: "array",
      inclusive: true,
      message: "Too many items 😡",
    });
  }

  if (val.length !== new Set(val).size) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: `No duplicated allowed.`,
    });
  }
});
```
This yields the following Typescript error on the method passed in to `superRefine`/`_refinement`:
`Argument of type '(val: string[], ctx: RefinementCtx) => void' is not assignable to parameter of type '(arg: string[], ctx: RefinementCtx) => boolean | Promise<boolean>'.
  Type 'void' is not assignable to type 'boolean | Promise<boolean>'.ts(2345)`

I can't see that this is mentioned in any changelog/readme, so it might be an unintentional change?

FYI, my Typescript version is `4.3.5`.

**Comment by colinhacks** [comment]
Fixed in 3.4.0, good catch!
