### ISSUE TITLE
Zod 3 : Partial on ZodEffects

### ISSUE THREAD

**Issue by Kayyow** [colinhacks/zod#525]
Hello, thanks for the awesome lib !

I had some schemas which use `.partial()` chained after `.refine()` (for example to validate that an `end` attribute is in the future of a `start` attribute).

```ts
z.object({
    ...
    start: dateFromString,
    end: dateFromString,
  })
  .refine(
    obj => obj.end > obj.start,
    {
      message: ':end must be later than :start',
      path: ['end'],
    },
  )
  .partial() <-- Property 'partial' does not exist on type 'ZodEffects<ZodObject<...>>'
```

After upgrading to Zod 3 they are not working anymore because the partial method doesn't exist on the ZodEffects class.

I didn't read anything about that in the migration guide, how am I supposed to handle such schemas in the v3 ?

**Comment by colinhacks** [comment]
This change is mentioned briefly in the third bullet point under "Breaking changes" [here](https://github.com/colinhacks/zod/blob/master/MIGRATION.md#breaking-changes-1) though this exact use case isn't covered.

In this case you'd have to place the refinement after the `.partial` and adjust the code to handle the potentially missing values.
