### ISSUE TITLE
Inferred all object properties are optional, when use strict: true

### ISSUE THREAD

**Issue by sadnessOjisan** [colinhacks/zod#533]
zod version: ^3.5.1
ts version: ^4.3.5

I saw #121 #276 #289 #498

And I tried this code.

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true, // <- changed
    "strictNullChecks": true, // <- added just in case
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

```ts
const User = z.object({
  username: z.string(),
})

type UserType = z.infer<typeof User>
```

The result is here.

![Screen Shot 2021-07-11 at 14 42 40](https://user-images.githubusercontent.com/13712715/125184137-49505b80-e256-11eb-944f-3734c118cf18.png)

I expected

```ts
{username: string}
```

Is there some my mistake?

**Comment by scotttrinh** [comment]
Yeah, I would suspect something related to your editor configuration is not working correctly. Verified that it works as expected with you example code on [TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFAxhAHYDO8AqgwKZRwC8KAdBACMAVm2owAFAgpw4AV3ZQ6AQxBsAXHyZRgdAObiAlABoKaA1RgBPMGzisOAFWu2eyXjswcAPFZsRMdgoAfEA) and I double checked it locally. My hunch is that your editor isn't finding your `tsconfig.json` file or is using a different one?

<img width="453" alt="Screen Shot 2021-07-11 at 2 47 16 PM" src="https://user-images.githubusercontent.com/1682194/125206795-05aa2180-e257-11eb-8cc6-dba4f969e557.png">
