### ISSUE TITLE
Optional without undefined union

### ISSUE THREAD

**Issue by brendo-m** [colinhacks/zod#539]
Sorry if this is an ignorant question but is it possible to create an object with an optional key without the `| undefined`?

i.e. this
```
type Foo = {
  bar?: string;
}
```

instead of the 
```
type Foo = {
  bar?: string | undefined;
}
```

You get when using `.optional()`.

**Comment by lilred** [comment]
Unfortunately the way optional fields are currently managed have some limitation, see e.g. [here](https://github.com/colinhacks/zod/issues/493). PRs most definitely welcome.

**Comment by colinhacks** [comment]
Nope that's not possible. They're treated identically by TypeScript so there's no reason for it. You can see that the `| undefined` gets automatically added by TS during any operation on the type, even trivial ones:

```ts
type Foo = {
  bar?: string;
};

type id<T> = T;
type NewFoo = id<Foo>; // { bar?: string | undefined }
```

**Comment by brendo-m** [comment]
Thanks for confirming!

**Comment by lilred** [comment]
@Katona a compiler flag for additional strictness sure sounds like the kind of thing Zod should handle gracefully... I don't know if as of today this is possible even in principle however.
