### ISSUE TITLE
[Question]: Typing advice for `superRefine()` methods on an obj, when the method provided is separated from the schema definition

### ISSUE THREAD

**Issue by polarathene** [colinhacks/zod#540]
Hello, new to TS and zod. Is it common practice to keep all logic coupled within the definition?

I am used to extracting out anything lengthy as may be the case for when using `.superRefine()`, but in that case I'm not sure what the advised approach is for handling typing to keep TS happy?

These are the two approaches I'm aware of, but perhaps there's a better way?

**Anonymous function has implicit typing from inference?:**
```ts
const dogSchema = z.object({
  name: z.string(),
  neutered: z.boolean(),
}).superRefine(
  (zobj, ctx) => { ... }
)

type Dog = z.infer<typeof dogSchema>
```

**Redundantly define the type anyway? (or at least for the values of interest in zobj):**
```ts
// Required to duplicate type definition...?
type zDog = {
    name: string;
    neutered: boolean;
}
const refineDog = (zobj: zDog, ctx: z.RefinementCtx) => { ... }

const dogSchema = z.object({
  name: z.string(),
  neutered: z.boolean(),
}).superRefine(
  refineDog
)

type Dog = z.infer<typeof dogSchema>
```

**Infer the type, but splits the schema into two stages:**
```ts
const _dogSchema = z.object({
  name: z.string(),
  neutered: z.boolean(),
})

// Better approach for large schemas?
type zDogRefine = (
   zobj: z.infer<typeof _dogSchema>,
   ctx: z.RefinementCtx
) => void
const refineDog: zDogRefine = (zobj, ctx) => { ... }

// Re-declaration of schema because type needed to be inferred to satisfy method provided to superRefine()
const dogSchema = _dogSchema.superRefine(refineDog)

type Dog = z.infer<typeof dogSchema>
```

**Comment by colinhacks** [comment]
Great question. You laid out the options well. There's no simpler option you're forgetting. Zod should probably export a `z.SuperRefinement<T>` alias so you don't need to type out ` (zobj: z.infer<typeof _dogSchema>, ctx: z.RefinementCtx) => void` - that's a little annoying. 

As for option 2 vs option 3, it depends on how portable you need the logic to be. If your refinement only requires certain fields ("values of interest") then redundantly refining the type signature maximizes portability. But then you need to update the type signature of `refineDog` manually if the schema changes. Tradeoffs... 🤷‍♂️ The main point is that you're not missing any options so do what feels best I suppose.

**Comment by polarathene** [comment]
> Zod should probably export a `z.SuperRefinement<T>` alias so you don't need to type out ` (zobj: z.infer<typeof _dogSchema>, ctx: z.RefinementCtx) => void` - that's a little annoying.

That'd be nice to have :)

---

I am commenting to add a note to others, that an additional gotcha regardless of approach is refinement on a schema converts it to a `ZodEffect` (as in, no longer a `ZodObject`), which means trying something like `schema.shape` as per the docs aren't valid anymore.

@colinhacks pointed this out in an past issue: https://github.com/colinhacks/zod/issues/454#issuecomment-848370721

> *refinements and transforms have been consolidated as "effects" and live in the ZodEffects class.*
> *Zod is designed to validate a type, then pass that value through a chain of refinements/transforms (in that order).*
> *Splitting out your refinement functions is the best way to do this currently.*

Thus if you want access to any of [these](https://github.com/colinhacks/zod#objects) for ZodObject / schema when exporting or composing with other schemas, you would may want to make the unrefined variant available.
