### ISSUE TITLE
Intersection cannot be assigned to `Schema` type

### ISSUE THREAD

**Issue by geigerzaehler** [colinhacks/zod#541]
Since v3.3 it is not possible anymore to give an explicit type definition for schemas of intersection types.The following code fails to type check.

~~~typescript
import * as zod from "zod"

interface Foo {
  foo: string;
}

const fooSchema = zod.object({
  foo: zod.string(),
});

interface Bar {
  bar: string;
}

const barSchema = zod.object({
  bar: zod.string(),
});

const interSchema: zod.Schema<Foo & Bar> = fooSchema.and(barSchema);
~~~

Typescript produces the following error
~~~plain
index.ts:19:14 - error TS2322: Type 'ZodIntersection<ZodObject<{ foo: ZodString; }, "strip", ZodTypeAny, { foo: string; }, { foo: string; }>, ZodObject<{ bar: ZodString; }, "strip", ZodTypeAny, { ...; }, { ...; }>>' is not assignable to type 'ZodType<Foo & Bar, ZodTypeDef, Foo & Bar>'.
  The types returned by '_parse(...)' are incompatible between these types.
    Type 'ParseReturnType<ZodObject<{ foo: ZodString; }, "strip", ZodTypeAny, { foo: string; }, { foo: string; }> & ZodObject<{ bar: ZodString; }, "strip", ZodTypeAny, { ...; }, { ...; }>>' is not assignable to type 'ParseReturnType<Foo & Bar>'.
      Type 'OK<ZodObject<{ foo: ZodString; }, "strip", ZodTypeAny, { foo: string; }, { foo: string; }> & ZodObject<{ bar: ZodString; }, "strip", ZodTypeAny, { ...; }, { ...; }>>' is not assignable to type 'ParseReturnType<Foo & Bar>'.
        Type 'OK<ZodObject<{ foo: ZodString; }, "strip", ZodTypeAny, { foo: string; }, { foo: string; }> & ZodObject<{ bar: ZodString; }, "strip", ZodTypeAny, { ...; }, { ...; }>>' is not assignable to type 'OK<Foo & Bar>'.
          Type 'ZodObject<{ foo: ZodString; }, "strip", ZodTypeAny, { foo: string; }, { foo: string; }> & ZodObject<{ bar: ZodString; }, "strip", ZodTypeAny, { ...; }, { ...; }>' is not assignable to type 'Foo & Bar'.
            Property 'foo' is missing in type 'ZodObject<{ foo: ZodString; }, "strip", ZodTypeAny, { foo: string; }, { foo: string; }> & ZodObject<{ bar: ZodString; }, "strip", ZodTypeAny, { ...; }, { ...; }>' but required in type 'Foo'.

19 const interSchema: zod.Schema<Foo & Bar> = fooSchema.and(barSchema);
                ~~~~~~~~~~~
~~~

A workaround is to use `.merge`.

~~~typescript
export const interSchema2: zod.Schema<Foo & Bar> = fooSchema.merge(barSchema);
~~~

However, this requires `fooSchema` to be an object and is not possible if `fooSchema` itself is annotated with `Schema<Foo>`.

**Comment by cjdell** [comment]
I've also run into this issue. I like to tightly couple all my schemas to the interfaces they represent. I cannot do this for intersection however even though I can have verified the parsed return type is assignable to the interface.

**Comment by scotttrinh** [comment]
You can use `ZodIntersection` to represent the intersected schema.

[TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFwAdjAKZSYCGAxvXAGIQSIVxYeALjgBnGFFoBzSmiqsINcYIgBlVgAt6IZnAC8KAHQQARgCt6rGAAoE-FSOSHxkmlOsBKADQU0HytR0jCzscABCzFB8AiaRIi7SsvKKyrFQ6lo6+kamFla29mmOzhLSnj5+AQpK8LQM6ZrazMUAWiQAkkFQopYwwIoAPE4ZTQPcEAB8XkYjOgMRUBMT2Zg8s8yGzDTE1mnr-hRAA)

```ts
import { z } from "zod";

interface Foo {
  foo: string;
}

const fooSchema = z.object({
  foo: z.string(),
});

interface Bar {
  bar: string;
}

const barSchema = z.object({
  bar: z.string(),
});

const interSchema: z.ZodIntersection<z.Schema<Foo>, z.Schema<Bar>> = fooSchema.and(barSchema);
```

**Comment by colinhacks** [comment]
@geigerzaehler This works:

```ts
interface Foo {
    foo: string;
  }

  const fooSchema:z.ZodSchema<Foo> = z.object({
    foo: z.string(),
  });

  interface Bar {
    bar: string;
  }

  const barSchema: z.ZodSchema<Bar> = z.object({
    bar: z.string(),
  });

  const interSchema = fooSchema.and(barSchema);
  type interSchema = z.infer<typeof interSchema>; // Foo & Bar
```

**Comment by geigerzaehler** [comment]
Thanks for posting the workarounds. It would make intersections a lot easier to use if it is possible to fix this though.

Using `zod.infer()` isn’t great since you can’t just look at the type and find it’s shape. This also doesn’t work if the type is defined in a different place but you want to ensure that it matches the schema type.

Using `z.ZodIntersection` is also not ideal. It gets really cumbersome to write the more types are intersected. It also requires you to give names to the constituent types so you don’t end up with

```typescript
type FooBar = { foo: string } | { bar: string };

const fooSchema = z.object({
  foo: z.string(),
});

const barSchema = z.object({
  bar: z.string(),
});

const fooBarSchema: z.ZodIntersection<
  z.Schema<{ foo: string }>,
  z.Schema<{ bar: string }>
> = fooSchema.and(barSchema);

```

**Comment by geigerzaehler** [comment]
I also realized that even with the workarounds it’s impossible to use the schemas in a generic function
```typescript
function parse<T>(value: unknown, zod.Schema<T>): T
```

which is exactly what we need.

**Comment by colinhacks** [comment]
The best way to write a generic function that accepts a Zod schema is like so:

```ts
function parse<T extends z.ZodTypeAny>(schema: T): T { ... } 
```

It should work for this use case. 

> This also doesn’t work if the type is defined in a different place but you want to ensure that it matches the schema type 

Everything that involves writing schemas the conform to pre-defined TS types is doing to be messy. It's just not what Zod was really designed for.

**Comment by geigerzaehler** [comment]
> It should work for this use case.

The signature you proposed doesn’t seem to match what we need. (I also noticed that I had a typo in the signature. I’ve fixed now). The idea of the generic `parse` function was to ensure that the type parsed by the schema matches the output type.


> Everything that involves writing schemas the conform to pre-defined TS types is doing to be messy. It's just not what Zod was really designed for.

Thanks for clarifying this. We would love to see this becoming easier though :slightly_smiling_face:

**Comment by colinhacks** [comment]
Everything is easier when you don't support chainable methods (a la https://github.com/mojotech/json-type-validation) but the fluent approach is one of Zod's main selling points. It's all tradeoffs.

Updated:

```ts
function parse<T extends z.ZodTypeAny>(schema: T): z.infer<T> { ... }
```
