### ISSUE TITLE
Make a field optional if some field have some expected value

### ISSUE THREAD

**Issue by pom421** [colinhacks/zod#542]
Hi, 

I would like to have some zod rules (like an optional), only if an other field have certain values. 

```
const schema = z.object({
    type: "full",
    name: z.string()
})

```

Now, how can I make the `name` field optional if the type field has the value "partial" ? 

I read about the refine function in documentation, but the logic seems to have a callback predicate with the input in parameter. 
In my case, I would rather prefer to be able to use some important primitive of zod like optional (but I can imagine other use cases where I would need to test against certain literals, etc.)

Any ideas?

**Comment by colinhacks** [comment]
This would have to be implemented as a union of two objects. This also gives you a more complete type signature.

```ts
const full = z.object({
  type: z.literal("full"),
  name: z.string(),
});

const partial = z.object({
  type: z.literal("partial"),
  name: z.string().optional(),
});

const union = z.union([full, partial]);
```

**Comment by pom421** [comment]
It works perfectly well ! 

Thanks @colinhacks for your quick answer and for your library! Very useful 🚀
