### ISSUE TITLE
Unable to extend/merge schema when using `z.Schema<Type>` 

### ISSUE THREAD

**Issue by AllySummers** [colinhacks/zod#549]
Apologies if this is already been reported or is something that cannot be fixed, I wasn't able to find it in the issues.

Assume you have the below schema:
```ts
interface Person {
    firstName: string,
    middleName?: string,
    lastName?: string,
    age: number,
    email?: string   
}

interface Employee extends Person {
    employeeId: string,
    manager: string
}
```

If you wanted to construct the Employee Schema to extend the PersonSchema, you are unable to do so if you create your schema with the type `z.Schema<Person>` as the `.extend` method apparently does not exist on the type `z.Schema<Person>`.

[Example with `z.Schema` (TS Playground)](https://www.typescriptlang.org/play?target=99&jsx=0&module=1#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgNwBQFwAdjAKZSYCGAxvXAAqMDOENiCnGFZgUHjAByzEPQBccCVFoBzADRCRIYMWIAbetNkB+BUtUaRcPcwlH6pxTGU11m4cxXy4NAK4gAI0ZLEXoQZmA9R3NXEQo0KloGJjYOAFFwPQgAT3oOegAPBhpiHi5efkErMLAs3PoASWIzZwt3OHCaT0YWlxV4qlZ+CXLxfgBlVgALMOYFZAA6SZnwgB5uMZoAPjgAXhQFiACAK3pWGAAKBHbMMTsZb0WYlQuAShDhbV0De3mF57ehzAMGA-GYejeH2stikDz+APe7W6fz8gUYgO0NAuAAZEdVwpF4a1XIDZpFARBgaCuhDXvE6RQhjQRhlajk8stZn9OWtWXU8jt9hs+DQecwFoVisQru0avzGs0DgioZ1ulAiX03nB6UA)

[Example without `z.Schema` (TS Playground)](https://www.typescriptlang.org/play?target=99&jsx=0&module=1#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgNwBQFwAdjAKZSYCGAxvXAAqMDOENiCnGFZgUHjAByzEPQBccCVFoBzADRCRIYMWIAbetNkB+BUtUaRcPcwlH6pxTGU11m4cxXy4NAK4gAI0ZLEXoQZmA9R3NXEQo0KloGJjYOAFFwPQgAT3oOegAPBhpiHi5efkErMLAs3PoASWIzZwt3OHCaT0YWlxV4qlZ+CXLxfgBlVgALMOY4AF4UADoIAIArelYYAAoEdswxOxlvZCWYlW2AShDhbV0DewVT86uVsBhgfmY9K5vrWykxyeZ1arl+7W6wL8gUYr20NG2AAZru1ZpFgS9Lks0T8sRB3p8urj4pdBsN4Blajk8pMZuEFqM+DRabNsUV6CVdqjMtTGs1lpi-p1ulAMaCLpc4CSgA)

**Comment by AllySummers** [comment]
I'd just like to note I was able to make a very quick and dirty "fix" for this with a custom type. 

[TS Playground link](https://www.typescriptlang.org/play?target=99&jsx=0&module=1#code/JYWwDg9gTgLgBAbzgLwDRwFoQCYHkBGAVgKYDGM6W2AyqQBbEgCGcAvnAGZQQhwDkyHHwDcAKFEwAnmGJwCJcrQbMAPABUAfHAC8mHPLIwVCUXDgBtANJxgAOzgBrYpIgc4agLoAuPTXqMmdSsPDVFWUNE7GGIoDiZSWQAFGIBnCHsTMzMOYCgUmAA5JhBiH3yoOwBzVFMskGBsbAAbYiKSgH4ymArbatqzJqZ8tuJOuHKqmqy4JkrSuFsAVxB8GKmsgOAmsYnerLDxKJi4hLgAUXAmiEliWWIAD2jbbBS4ZLz0xH64RjArm+IAElsF0en1psxbLMYqCqgdRKR0vk3ql0koAj4DIp-Kp3mlbFpdMgAHQQIiGAAUmSyOTyhWK8xJu0qFIAlOszPVGi0Rj4md0qmzSWAYMB0kwmmyOXBBsMGXzicypd9oQqlisYkL6rYKQAGdnfTZNBVK1nEo1CiAisVQyWssL2hFI+AXP7XW7o5iY8nY5SBV3-W6ElEfWyepjmx7EZ5Uw2Xd1AkEoRUC3rKiFMKFzKAm1Ms1lwB1AA)

**Comment by colinhacks** [comment]
To define Zod schemas that conform to a pre-existing type, this is the recommended approach: https://github.com/colinhacks/zod/issues/372#issuecomment-826380330

To your question, only `z.ZodObject` instances have the `extend` method. `z.Schema` is the base class of all Zod schemas, including `z.ZodObject`. 

I recommend against trying to keep Zod schemas aligned with separately defined interfaces like this when possible. The idea behind Zod is let users define their types once, instead of keeping runtime + static code synchronized. Though I understand there are sometimes unavoidable design considerations.
