### ISSUE TITLE
Specify valid keys in Record

### ISSUE THREAD

**Issue by danenania** [colinhacks/zod#55]
In TS, I can define an object like so:

`type Flags = Record<"flag1"|"flag2", boolean>` 

or:

`type Flags = {[k in "flag1"|"flag2"]: boolean}`

It doesn't seem there's any way to accomplish this now in zod? I have lots of TS types using this pattern with large unions that I *really* don't want to duplicate everywhere as `z.object` keys, so this would be handy to get full parity with TS.

**Comment by danenania** [comment]
Found a seemingly workable solution to this:

```
const ZodLiteralRecord = <
  KeyType extends string,
  ZodValueType extends z.ZodTypeAny
>(
  keys: KeyType[],
  zodValueType: ZodValueType
) =>
  z.object(
    keys.reduce(
      (agg, k) => ({
        ...agg,
        [k]: zodValueType.optional(),
      }),
      {} as Record<KeyType, z.ZodUnion<[ZodValueType, z.ZodUndefined]>>
    )
  );
```

**Comment by vriad** [comment]
Interesting proposal. I'm open to moving something like this into core. Leaving this open until I get around to doing so.

**Comment by scotttrinh** [comment]
There is a related feature of `Record` that I use all of the time, too. _Requiring_ all of the keys from an enum to be in the record. Like this:

```ts
enum Foo {
  BAR = "BAR",
  BAZ = "BAZ"
}

type FooMap = Record<Foo, string>;

const valid: FooMap = {
  [Foo.BAR]: "bar",
  [Foo.BAZ]: "baz",
};

const invalid: FooMap = { // Type error here
  [Foo.BAR]: "bar",
};
```

https://www.typescriptlang.org/play?#code/KYOwrgtgBAYg9nKBvAUFKAhAggJSgXigCJsciAaNTLALQOOxqJQF8UUAXATwAdhYEAWQCGPejmABjOACcAJgB54cclADOHGQEsQAcwB8AbnbSQGqADdhAGy1yAXALgixhVOgDaygHSkAuo5EAEbCMhRUXgi+tAHEIQBe4SzGKKbmOla2Dk4u9O5QkXDROLHBoUmGQA

**Comment by privatenumber** [comment]
I also have a similar need for providing a schema for record keys.

In my use-case, I have a schema where the keys must be a string of length 1.

Being able to do something like this would be the most intuitive:
```ts
z.record(z.string().length(1), z.boolean()); // where the key parameter for record only accepts string types
```

**Comment by colinhacks** [comment]
Consider implementing this yourself! There's nothing special about the schema types implemented in the core library, everything is just a subclass of ZodType. Use the implementation of `ZodRecord` as a model, it's only ~60 lines of code.

**Comment by akomm** [comment]
@colinhacks whenever I encouter something like that, I usually come up with the solution without even looking, but there is problem: there are probably a multitude of libraries used in a project. Adding *just* 60 lines per library is needed 5+ times often times and multiply this by 10-20 libraries and its not anymore just 60 lines. Now some of them update and your hack is broken.  

So it always boils down how common the use case is and imo this is a fundamental thing. Without the ability to specify the type for the key you also can not use it with newtypes.

**Comment by ByronBroughten** [comment]
> Its implemented in 3.9.8 (maybe earlier, did not check). It was not there in 3.5.1

Will you show me how this feature is implemented in 3.9.8? Just so I can verify whether it is implemented in my current version (3.8.2).

I often use record types in which unions define required keys, for cases in which all the values are the same type. I would appreciate this feature.

**Comment by akomm** [comment]
@ByronBroughten 
```ts
const keys = z.union([z.literal("flag1"), z.literal("flag2")])
const Flags = z.record(keys, z.boolean())
```

**Comment by low-ghost** [comment]
I was surprised to see that records with literals and zod enums work perfectly fine, as tests in this general area show https://github.com/colinhacks/zod/blob/cc8ad1981ba580d1250520fde8878073d4b7d40a/src/__tests__/record.test.ts#L10-L17 so perhaps [the bug directly above my comment](https://github.com/colinhacks/zod/issues/55#issuecomment-968135932) is solved?

There's a couple of interesting things though. Records in ts enforce that all of their keys are present. e.g.:
```ts
enum Something {
  F1 = "f1",
  F2 = "f2",
}
type SomethingNums = Record<Something, number>;
const f1: AssertEqual<SomethingNums, { f1: number; f2: number }> = true;
```
Note that the number fields are required and not `{ f1?: number; f2?: number }`. So the approach described again in @akomm's comment is not equivalent even in terms of the actual record parsing. So
```ts
const SomethingNumsZ = z.record(z.union([z.literal("f1"), z.literal("f2")]), z.number());
expect(() => SomethingNumsZ.parse({ f1: 1 })).to.throw("should throw due to missing f2");
```
fails to throw. That goes against my expectation at least. Same could be said of @danenania's solution, where the fields are explicitly and intentionally made optional.

In that line, I like this as a util:
```ts
export const RecordOf = <
  T extends Record<string, string>,
  ZodValueType extends z.ZodTypeAny
>(
  obj: T,
  zodValueType: ZodValueType
) => {
  type KeyType = T[keyof T];
  const keys = Object.values(obj);
  return z.object(
    keys.reduce(
      (agg, k) => ({
        ...agg,
        [k]: zodValueType,
      }),
      {} as Record<KeyType, ZodValueType>
    )
  );
}
```

and some tests to prove that RecordOf functions very similarly to ts's Record:

```ts
describe("RecordOf", () => {
  enum Ordinals {
    FIRST = "first",
    SECOND = "second",
    THIRD = "third"
  };

  const PlanetZ = z.object({
    name: z.string(),
    moons: z.number(),
  });

  // Well, at least the start of one
  const SolarSystemZ = RecordOf(Ordinals, PlanetZ);
  type SolarSystem = z.infer<typeof SolarSystemZ>;
  // The equivalent in pure ts. could infer from PlanetZ, but being explict/safe here
  type NativeSolarSystem = Record<Ordinals, { name: string; moons: number; }>;

  const testObj = {
    first: { name: "Mercury", moons: 0 },
    second: { name: "Venus", moons: 0 },
    third: { name: "Earth", moons: 1 },
  };

  it("should make a zod record type with provided keys and value", () => {
    // borrowed from zod's tests
    type AssertEqual<T, Expected> = [T] extends [Expected]
      ? [Expected] extends [T]
      ? true
      : false
      : false;
    const f1_: AssertEqual<NativeSolarSystem, SolarSystem> = true;
    // @ts-ignore _def doesn't have typeName on its type
    expect(SolarSystemZ._def.typeName).to.equal(
      "ZodObject",
      "should not be a ZodRecord, unfortunately, because we want to require all keys" 
    );
  });

  it("should parse a correct object", () => {
    expect(SolarSystemZ.parse(testObj)).to.deep.equal(testObj);
  });

  it("should throw on bad check", () => {
    // pull off 'first' to fail check. Note that this means the result requires all
    // enum fields to be present. use `.optional()` if that isn't intended
    const { first: _, ...restObj } = testObj;
    expect(() => SolarSystemZ.parse(restObj)).to.throw();
  });
});
```
