### ISSUE TITLE
Zod not working when imported across packages

### ISSUE THREAD

**Issue by krivachy** [colinhacks/zod#556]
We ran into an issue when upgrading from 3.2.0 to 3.5.1, that when we're importing Zod defined schemas across our package boundaries (which just means that Zod is installed multiple times, once in each package that uses it) Zod breaks and the validation doesn't actually run.

I've put together a small repo to reproduce this: https://github.com/krivachy/zod-object-bug

The setup is:
- There are two packages in the `packages/` directory
- packageA contains a validation: [zEmail](https://github.com/krivachy/zod-object-bug/blob/main/packages/packageA/src/emailValidation.ts)
- packageB contains a model that uses zEmail: [models.ts](https://github.com/krivachy/zod-object-bug/blob/main/packages/packageB/src/models.ts)
- test fails when it's imported, but passes when it's locally defined: [index.test.ts](https://github.com/krivachy/zod-object-bug/blob/main/packages/packageB/index.test.ts)
- The same version of Zod is installed in both [packageA](https://github.com/krivachy/zod-object-bug/blob/main/packages/packageA/package.json) and [packageB](https://github.com/krivachy/zod-object-bug/blob/main/packages/packageB/package.json)

If we install Zod once at a root package.json level it seems to work, but we'd like to have our packages define their own dependencies.

Other libraries work perfectly fine this way, so I'm a bit confused as to why Zod breaks with this setup? Any advice would be much appreciated, thanks!

**Comment by scotttrinh** [comment]
Interesting. It's even stranger than you indicate here since it _does_ run the validation and returns the correct result when the email is valid, but when it's invalid, it passes with a success but the data is empty. Feels like a bug maybe in schema's having different `this` references? Thanks for the report, seems like we should be able to fix it.

**Comment by krivachy** [comment]
Thanks @scotttrinh for looking into this.

> returns the correct result when the email is valid

Yeah, you're right, I didn't notice that! I pushed a testcase for [that as well](https://github.com/krivachy/zod-object-bug/commit/37c0425cc4ddd6dfa13b415e9eb726e3908fcf85).

So it seems like error collection isn't happening correctly.

Running my testcase through a debugger I can see (apologies for the transpiled JS code screenshot!):
![image](https://user-images.githubusercontent.com/5367669/127008464-8c135906-0609-4655-9602-36769d7671ba.png)

Briefly the execution order is:
1. When [this for loop](https://github.com/colinhacks/zod/blob/v3.5.1/src/types.ts#L1487-L1494) goes through the shape keys it invokes the email validation in my example code
2. The email validator gets invoked with the result being: `{valid: false}`
3. Then [handleParsed](https://github.com/colinhacks/zod/blob/v3.5.1/src/types.ts#L1466-L1485) handles the error and rather than hitting [the `invalid = true;` line](https://github.com/colinhacks/zod/blob/v3.5.1/src/types.ts#L1479) it hits the [tasks push line](https://github.com/colinhacks/zod/blob/v3.5.1/src/types.ts#L1481-L1483)

This leads me to believe that the issue is in the [`isInvalid` method](https://github.com/colinhacks/zod/blob/v3.5.1/src/helpers/parseUtil.ts#L200-L201) and `export const INVALID: INVALID = Object.freeze({ valid: false });` from one module isn't `===` to another installations, which now that I type out makes sense :)

Testing this locally by just changing the minified files in both modules to be (again apologies for the transpiled code and not Typescript code):

```
var isInvalid = function (x) {
    return x.valid === false;
};
exports.isInvalid = isInvalid;
var isOk = function (x) {
    return x.valid === true;
};
exports.isOk = isOk;
```

The line I expect to be hit is hit and the test passes! 🎉 🎉 🎉 

![image](https://user-images.githubusercontent.com/5367669/127010463-88b7800e-d75d-4264-a520-568e5a406c56.png)

I'm happy to submit a PR, but I'd like some guidance on how best to write a test for this? Is there a sensible way to even test this given the project's current test setup or should I just change the implementation?
