### ISSUE TITLE
Create union from array

### ISSUE THREAD

**Issue by Djaler** [colinhacks/zod#561]
I have an array of some codes (just a numbers) and I want to validate that object field contains one of them.
For example:
```
const HTTP_SUCCESS = [200,201];
```

In superstruct I can use `enums` function to do this:
```
const response = type({
   code: enums(HTTP_SUCCESS),
})
```

I tried to do something like:
```
const response = z.object({
    code: z.union(HTTP_SUCCESS.map(z.literal))
})
```
But this doesn't work because result of the map is an array, while z.union requires a tuple.

**Comment by Djaler** [comment]
I found a way to do this, but it's requires a casting to any, which I don't like to do.
```
function unionFromArray<T extends z.Primitive>(array: T[]): z.ZodUnion<[z.ZodLiteral<T>, ...Array<z.ZodLiteral<T>>]> {
    return z.union(array.map(item => z.literal(item)) as any);
}

const response = z.object({
    code: unionFromArray(HTTP_SUCCESS)
})
```

**Comment by colinhacks** [comment]
There's no built-in way to do this because it's kinda tricky to get the typing right. Using your code, the inferred type of `response` is `number`, instead of `200 | 201`. I'd recommend this instead:

```ts
function unionFromArray<
  T extends z.Primitive,
  Tuple extends Readonly<[T, ...T[]]>
>(
  array: Tuple
): z.ZodUnion<{ -readonly [k in keyof Tuple]: z.ZodLiteral<Tuple[k]> }> {
  return z.union(array.map((item) => z.literal(item)) as any);
}

const HTTP_SUCCESS = [200, 201] as const;

const response = z.object({
  code: unionFromArray(HTTP_SUCCESS),
});
```

**Comment by mmahalwy** [comment]
@colinhacks curious how this would work in a case where the array is not a constant where the value needs to be extracted. Say its:
```
const HTTP_SUCCESS = [{label: 'foo', status: 200}].map(s => s.status);
```
