### ISSUE TITLE
No option to define an error message for non-empty array

### ISSUE THREAD

**Issue by SlateDave** [colinhacks/zod#570]
I can define a non-empty string like this:

```ts
z.string().nonempty('This string should not be empty')
```

The same ``nonempty`` method exists for ``z.array()`` but it doesn't take an argument to define the error message.

I would like to do:

```ts
z.array().nonempty('This array should not be empty') // Right now throws "Expected 0 arguments, but got 1"
```

but right now I'm forced to write it like this:

```ts
z.array().min(1, 'This array should not be empty')
```

**Comment by colinhacks** [comment]
Yeah that's an oversight. Added in `zod@3.7.0`.
