### ISSUE TITLE
Recursive type: Type instantiation is excessively deep and possibly infinite. 

### ISSUE THREAD

**Issue by JorikSchellekens** [colinhacks/zod#577]
I'm running into a problem creating a parser for a fairly simple recursive type. The following errors with `Type instantiation is excessively deep and possibly infinite.  TS2589`:

```
type V = [V] | "Null"

const V : z.ZodSchema<V> = z.lazy(() =>
  z.union([
    z.tuple([V]),
    z.literal("Null")
]))
```

However a loosely similar type works fine:

```
interface V {
  a: [V]
}

const V : z.ZodSchema<V> = z.lazy(() => 
  z.object({
    a: z.tuple([V])
  })
)
```

The use of the Tuple is significant, using an array works fine for both.

I'd be willing to work on a pr but I had a poke around and didn't get far in finding out what causes this, if you have any tips on what might be causing it I can take another look.

**Comment by colinhacks** [comment]
This works if you do this:

```ts
const V: z.ZodSchema<V,z.ZodTypeDef, any> = z.lazy(() =>
  z.union([z.tuple([V]), z.literal("Null")])
);
```

The third generic parameter to `z.ZodSchema` is inferred from the first, and apparently passing a self-referential type in that case causes TypeScript to panic. 🤷‍♂️

**Comment by JorikSchellekens** [comment]
Perhaps some equivalence check gone wild. Oh well, thanks for the easy workaround!

**Comment by takahash** [comment]
A similar error occurs when TypeScript version is 4.3 or higher.

```
const C = z.object({
  foo: z.string(),
  bar: z.number().optional(),
})
```

```
utils/validations/schema.ts:4:11 - error TS2589: Type instantiation is excessively deep and possibly infinite.
4 const C = z.object({
            ~~~~~~~~~~
5   foo: z.string(),
  ~~~~~~~~~~~~~~~~~~
6   bar: z.number(),
  ~~~~~~~~~~~~~~~~~~
7 })
  ~~
```

I'm using version 4.1.5 now because I don't get this error with TypeScript version 4.1.5.
Next.js recommends TypeScript version 4.3.2 or higher, so if anyone knows how to avoid this error, please let me know.

**Comment by kotx** [comment]
I saw this in my vscode hints but nowhere in my actual builds. Turns out I had to uninstall the ts-next (Microsoft TypeScript Nightly) extension from vsc.

**Comment by nikkhn** [comment]
> 

you just saved me - thank you !

**Comment by shabbir-hossain132112** [comment]
> [@takahash](https://github.com/takahash)
> 
> This sounds similar to an issue where you might have two different versions of `zod` installed? Are you exporting `C` into a different project that might have a different version of `zod` also declared?

This is the root cause of the issue. And making sure I have only one version of zod installed for the project solved the issue. This answer should be the topmost voted one...

**Comment by mhm13dev** [comment]
> This sounds similar to an issue where you might have two different versions of zod installed? Are you exporting C into a different project that might have a different version of zod also declared?

So this is the issue. I was working in a monorepo. My shared package had a different version of zod than the one installed in my next.js package. When I upgraded to the same versions in both packages, the issue was fixed.

**Comment by 0x80** [comment]
@mhm13dev I thought I was going nuts 😅  I extracted some code into its own package to be published to NPM later. And  internally the code worked fine, but my other packages gave me this type inference issues. 

So glad I finally bumped into this 🙌

**Comment by wenzelbarboza** [comment]
Deleting and re-installing node_modules worked for me

**Comment by LarsOlt** [comment]
For people that use a pnpm monorepo like me, you can use [PNPM Catalogs](https://pnpm.io/catalogs) to use the same zod version for all monorepo packages without duplication the version number. After making this adjustment, deleting all node_modules folders and running pnpm i, the zod issue was fixed.

<img width="261" alt="Image" src="https://github.com/user-attachments/assets/7d3cc465-cfb4-4a07-896e-3b9f74596a5b" />

**Comment by bauchdj** [comment]
Also a monorepo issue for me. I am using bun workspaces. I have `apps/server`, `apps/web`, `packages/shared`

I moved most of my validators into `packages/shared` and left some in `apps/server`. The `validators.ts` in `apps/server` became incredibly slow because it was importing child z.ZodString constants from `packages/shared`.

Don't know why the import made it so much slower than having the constants in `validators.ts` but it did. Kind of interesting.

**Comment by PetrKubes97** [comment]
Since this is the first link that shows up on Google:

My problem was that IDE autoimported `import {z} from "zod/index";` instead of `import {z} from "zod";`

**Comment by capybarahero** [comment]
SImilar to @LarsOlt , my issue was different versions of zod in the same monorepo. `pnpm dedupe` did the trick for me.

**Comment by purecopy** [comment]
The same issue appeared with Astro Content Collections for me. `pnpm dedupe` also helped with this. Thanks @capybarahero

**Comment by SayedDileri** [comment]
> [@takahash](https://github.com/takahash)
> 
> This sounds similar to an issue where you might have two different versions of `zod` installed? Are you exporting `C` into a different project that might have a different version of `zod` also declared?

Thank you, this explanation solved it for me. 

I was using Zod `3.24.2` whilst another external library (OpenAI SDK) was using Zod `v4`. I simply upgraded mine to latest `4.3.5` and that was the fix.

**Comment by alirezarastineh** [comment]
Deleting and re-installing node_modules worked for me too
