### ISSUE TITLE
Auto infer type?

### ISSUE THREAD

**Issue by crobinson42** [colinhacks/zod#579]
I just started checking this library out and I think it's a really nice utility. I noticed some possible unnecessary code where I will define "schemas" and export them, I also have to have a second `type` export. What I was hoping for was a way to chain an optional method that returns an _inferred_ `type` as well as the value object.

Here is my code:
![image](https://user-images.githubusercontent.com/5973579/128930561-eccc1bd9-dd52-4edd-b0c9-38476b774e77.png)

What I would like to do is something like this:
![image](https://user-images.githubusercontent.com/5973579/128930639-e1d3b956-0606-412c-8475-293962849a4f.png)

**Comment by scotttrinh** [comment]
I'm not sure TypeScript can work that way: you're assigning to a `const` there which is a runtime construct. If you don't want to have to export your inferred type, you could just move the inferrence to the caller, but I'm not sure this is an ergonomic improvement:

```ts
const user: z.infer<typeof UserModel> = UserModel.parse(input);
```

FWIW, I tend to differentiate between the schema and the type it parses, which is purely stylistic:

```ts
export const userModelSchema = z.object({
  ...
});

export type UserModel = z.infer<typeof userModelSchema>;
```

**Comment by crobinson42** [comment]
@scotttrinh you are right 🤦🏽‍♂️. It's easy to get carried away _wishing for the perfect DX_ 😉.

Thanks for the reality check!

**Comment by crobinson42** [comment]
Thanks for the great lib, btw!! If you had a sponsorship or patreon I would put in a recommendation for my company to contribute.

**Comment by colinhacks** [comment]
@crobinson42 Like [this one](https://github.com/sponsors/colinhacks)? 😛

Glad Zod is working for you! Very cool to see companies using it.
