### ISSUE TITLE
Omit/Pick from a lazy object

### ISSUE THREAD

**Issue by Netfloex** [colinhacks/zod#591]
Is there a way to Omit/Pick on a recursive/lazy object?

I want to be able to use something like this:
```ts
type Test = {
	someKey: boolean;
	children: Omit<Test, "someKey">;
};

const test: z.ZodSchema<Test> = z.lazy(() =>
	z.object({
		someKey: z.boolean(),
		children: test.omit({someKey: true}) // This method does not exist
	})
);
```
But this does not work because `omit` does not exist there.

I discovered a "hidden" `schema` property on `ZodLazy`, so I tried using:
```ts
// ...
		children: test.schema.omit({someKey: true})
```
But this doesn't really help as it gives me a `RangeError: Maximum call stack size exceeded` error.

After some searching I found an answer for why those methods are not implemented:
https://github.com/colinhacks/zod/issues/56#issuecomment-636633007

How should I achieve this? And is this even possible?

**Comment by Netfloex** [comment]
I found a way without using `z.lazy`, by just extending base objects.

**Comment by leog** [comment]
> I found a way without using `z.lazy`, by just extending base objects.

Could you share what you found to resolve this, bumping to this problem too @Netfloex, thanks in advance!

**Comment by Netfloex** [comment]
I actually had no need for recursion so I made my problem a lot simpler. This is what I did:

```ts
// Typescript version

interface Base {
	baseOption: boolean;
	secondBase: number;
}

type BaseExtended = Base & {
	children: Base;
}

// Zod version

const baseSchema = z.object({
	baseOption: z.boolean(),
	secondBase: z.number()
})

const baseExtendedSchema = baseSchema.extend({
	children: baseSchema
})
```

Hope this helps
