### ISSUE TITLE
Zod exception should include the input data

### ISSUE THREAD

**Issue by Hurtak** [colinhacks/zod#595]
Hello.

When I run validator on incorrect data I get `ZodError` that does not contain the original data, only Zod info about what went wrong and on what path etc.
I think it would be beneficial to have the original data also included in the ZodError, since it would make the debugging much easier. 

## My use case:

I am communicating with API that is not well documented. The APIs responses are big and complicated (union types) and the structure of the responses is not documented at all, so I have to guess little bit. When there is an exception, the Zod error itself does not have enough information for me to fix it. So I had to wrap the Zod library, and in cases when the validation does not pass, I log the original data, along with the ZodError.

So my line of thinking was that adding the original data into the ZodError could make the errors much easier to understand and it would remove the need for wrapping the Zod library for me and probably other people.

## Proposal

Add input data into the `ZodError`

**Comment by scotttrinh** [comment]
I feel like people have mentioned being sensitive about logging input data, since it might include sensitive information, but I can't recall what the circumstances are exactly. I'm interested to hear people's experience here since we do something similar, but only ad-hoc and during development.

**Comment by Hurtak** [comment]
@scotttrinh yea, that's true, logging by default could be unsafe. So maybe some additional parameter (off by default) added to the parse functions that would add the input data into the error if passed?

**Comment by scotttrinh** [comment]
I feel like making it configurable could be a slippery slope, since it would open the door to having different kinds of use cases needing different things. Right now we have inversion-of-control by requiring wrapping, but that is also the most flexible approach. I wonder if some examples in the README would suffice for now while we considered what the core library could do to make it easier for consumers?

**Comment by colinhacks** [comment]
@scotttrinh Should be safe to add an `inputData` property on ZodError as long as it doesn't get logged by the `.message` getter. Then users who want to inspect/print the input can do so, but it's unlikely to get logged accidentally.

**Comment by rivatove** [comment]
Is the PR going to get merged? I need this functionality as well.

**Comment by rinarakaki** [comment]
What is the current status of this feature request?
