### ISSUE TITLE
Error "Intersections only support objects" when using transformation and passthrough

### ISSUE THREAD

**Issue by RobinTail** [colinhacks/zod#600]
Zod version 3.7.2.

Code sample to reproduce the issue

```typescript
const left = z.object({}).passthrough();
const right = z.object({
  id: z.string().transform((str) => parseInt(str))
});
const schema = z.intersection(left, right);
schema.parse({
  id: '123'
});
```

Throws an error
```
ZodError: [
  {
    "code": "invalid_intersection_types",
    "path": [],
    "message": "Intersections only support objects"
  }
]
```

The error itself is not clear enough, since **I'm certainly intersecting objects**.

After debugging it on the source code I figured out that perhaps it happens because parsed type on the `left` is `{id: string}` and on the `right` is `{id: number}`.
So it considers the field `id` to have unmatched types. But the error does not have a reference to the field: `path` is empty.

At the same time `left` does not declare the type of `id` field, it just passes the unknown fields through, so I'd say it should have less "priority" in the intersection.

I'd like to request the improvement of the intersection algorithms.
Maybe it should intersect object shapes before parsing their field types?

**Comment by colinhacks** [comment]
You're right that the error message needs to be generalized, but since the two schemas return incompatible outputs for the same input, I consider this correct behavior. What are you trying to accomplish exactly? Why not do this?

```ts
const right = z.object({
  id: z.string().transform((str) => parseInt(str))
}).passthrough();
```

**Comment by RobinTail** [comment]
In my example is a special case of intersection of a middleware and an endpoint input schemas. 

> Why not do this?

They are declared separately and intersected programmatically.
I'd like to intersect them using a native Zod method.
The scheme you proposed I would expect as the result of the intersection I mentioned because:
- it intersects object shapes first,
- and **then** handles unknown object properties.
