### ISSUE TITLE
object key constraint using enum

### ISSUE THREAD

**Issue by GaikwadPratik** [colinhacks/zod#601]
Hi @colinhacks,

An awesome library. Thanks!

This is more of a question than a bug. I've to create an object, more like `z.object`. But I want to restrict the keys of that object based on an Enum. For instance,

```
const enum ReferenceEntity {
  TestA = "testA",
  TestB = "testB"
}
```
Then in TS, I can define a  object like 
```
const obj = { [key in ReferenceEntity]: string }
```

How can I achieve this using `zod`? 

I've defined enum in `zod` using 
```
const ReferenceEntityZod = z.nativeEnum(ReferenceEntity);
```

How do I create `obj` now using `zod`?

**Comment by SlateDave** [comment]
Hi @GaikwadPratik,

I was just about to ask the exact same question when I saw your post.

In addition I was able to find out that the competing library [runtypes](https://github.com/pelotom/runtypes) handles this as follows:

```typescript
const ReferenceEntity = Union(Literal('TestA'), Literal('TestB'));
const obj = Dictionary(String, ReferenceEntity );

const test: Static<typeof obj> = {
    TestA: 'It works',
    TestB: 'Like this'
}
```

Sadly, I ain't got a clue how to do this with Zod as well.

**Comment by colinhacks** [comment]
This is now possible using `z.record` in Zod 3.9: https://github.com/colinhacks/zod/pull/663

**Comment by GaikwadPratik** [comment]
@colinhacks ,

Any thoughts/suggestions?

**Comment by scotttrinh** [comment]
@GaikwadPratik 

The new feature is equivalent to `Record<SomeEnum, T>`, which is equivalent to `[key in SomeEnum]` but it requires that every member of the enum be present as a key in the type:

```
enum E {
    A = "A",
    B = "B",
}
type A = Record<E, string>; // { A: string; B: string; }
type B = { [key in E]: string }; // { A: string; B: string; }
```

We should probably add a `partial` method on `ZodRecord` to support having partial records, but that's a separate feature from supporting key constraints.
