### ISSUE TITLE
Feature: String starts/ends with 

### ISSUE THREAD

**Issue by alii** [colinhacks/zod#604]
I was writing a validator for a hex color code and thought that being able to check that it started with a `#` would be a nice addition.

E.g.: `z.string().length(7).startsWith('#')`

**Comment by DASPRiD** [comment]
You can already do that:

```ts
z.string().length(7).regex(/^#/);
```

**Comment by agustif** [comment]
An updated version if you need supporting 3 and 8 digit hex too

  `color: z.string().min(4).max(9).regex(/^#/),`
This allows for
#FFF (White, simplified, it just becomes #FFFFFF)
and #00000080 (Black, with 80% transparency)

in case helps anyone looking for this
