### ISSUE TITLE
Tuple Behavior: strip by default

### ISSUE THREAD

**Issue by rubber-duck-software** [colinhacks/zod#613]
# Problem
Currently the behavior of Tuples is unintuitive when used for function arguments. 

## Without Zod
In javascript, something like what is below is entirely valid
```js
function maxLength5(str) {
    return str.length <=  5
}

const filteredList = ['apple', 'orange', 'pear', 'banana', 'strawberry'].filter(maxLength5)
```

## With Zod
This is a wonderfully powerful capability. However, if the `maxLength` function was wrapped with zod type checking, the above example would fail with error
```js
const maxLength5  = z.function()
    .args(z.string())
    .returns(z.boolean())
    .implement((str) => {
       return str.length <=  5
    })

const filteredList = ['apple', 'orange', 'pear', 'banana', 'strawberry'].filter(maxLength5)
```

### Error 
```js
ZodError: [
  {
    "code": "invalid_arguments",
    "argumentsError": {
      "issues": [
        {
          "code": "too_big",
          "maximum": 1,
          "inclusive": true,
          "type": "array",
          "path": [],
          "message": "Should have at most 1 items"
        }
      ],
      "name": "ZodError"
    },
    "path": [],
    "message": "Invalid function arguments"
  }
]
```

# Proposal
The default behavior for function argument tuples should instead be something analogous to stripping keys on objects. Any extra elements in a tuple should be removed and validation should pass so that the above example works as expected.

**Comment by rubber-duck-software** [comment]
Would a collaborator be open to a PR along these lines?

**Comment by colinhacks** [comment]
Sorry, I have this nearly done on my end. I'm wrapping up some other things before releasing 3.9.

**Comment by colinhacks** [comment]
Tuples now support rest parameters: https://github.com/colinhacks/zod/pull/663

Moreover, `ZodFunction` automatically adds `ZodUnknown` as the rest parameter to the arguments tuple, so your example now works as written.
