### ISSUE TITLE
Can't properly type `z.lazy` with an object validator that transforms fields

### ISSUE THREAD

**Issue by ivanbatic** [colinhacks/zod#615]
I'm trying to validate an object (with a recursive structure, but the issue is reproducible without it) which transforms fields into something that doesn't exactly match the given schema, and I have a hard time figuring out how to do it.

Here's an example:

```ts
const validator: ZodSchema<{ 
  foo: string 
}> = z.lazy(() => z.object({
  foo: z.number().transform((num) => num.toString()),
}));

/**
* The types of '_input.foo' are incompatible between these types.  
* Type 'number' is not assignable to type 'string'.
*/

```

So I assumed that I got it wrong, and figured that the type given to `ZodSchema` should match validation _before_ transformation, but that also doesn't seem to work.

```ts
const validator: ZodSchema<{ 
  foo: number // <-- CHANGED FROM STRING 
}> = z.lazy(() => z.object({
  foo: z.number().transform((num) => num.toString()),
}));

/**
* The types of '_input.foo' are incompatible between these types.  
* Type 'string' is not assignable to type 'number'. // <-- REVERSED ERROR
*/

```

Did I understand something wrong here? How should I do this properly?
Thank you!

------
Using
Zod 3.8.1
Typescript 4.4.2

**Comment by colinhacks** [comment]
Yeah this is tricky. `ZodSchema` actually accepts three properties:

`class ZodSchema<Output, Def, Input = Output> { ... }`

When you introduce transforms, the `Input` of your schema is different from the `Output`. But for the sake of backwards compatibility, `Input` is assumed to be equivalent to `Output` if it isn't specified explicitly. Here's how to make this work:

```ts
const validator: z.ZodSchema<
    { foo: string; }, // output
    any,
    { foo: number; } // input
  > = z.lazy(() =>
    z.object({
      foo: z.number().transform((num) => num.toString()),
    })
  );
```
