### ISSUE TITLE
Feature: Extend ZodObject with modified version of existing element

### ISSUE THREAD

**Issue by aspirisen** [colinhacks/zod#616]
Hello, is it possible to extend the original shape but check that the keys are taken from origin. 
For example i have such shape in module scope:
```
const SomeData = z.object({
  test: z.string(),
  test1: z.number(),
})
```

Add i would like to add more rules to this object (the API can be smth different)
```
function MyForm() {
  const t = useTransition()
  const FormValues = SomeData.deepMerge({ test1: z => z.min(10, { message: t.form.numCheck }) })
  const form = useForm({ resolver: zodResolver(FormValues) })

  return <>{/* do smth with form */}</>
}
```
And the TS will autocomplete the `test1` prop.

The case when it is needed is when you want to use the localization in i.e. React components because usually the translations are available in React context and not in global scope. Technically i can use the translation from some global object and use it when defining SomeData, but the issue will be is that when i change the language the error message will be the same because they are hardcoded and cannot react the translation change.

**Comment by colinhacks** [comment]
I've considered something like this for a long time. I'd probably call it `.mapKeys` or something. For now I haven't implemented it becauase there's a pretty convenient workaround:

```ts
const FormValues = SomeData.extend({ 
  test1: SomeData.shape.test1.min(10, { message: t.form.numCheck }) 
})
```

**Comment by aspirisen** [comment]
@colinhacks thanks, yes that is pretty good workaround, the one thing that would be nice to have is autocompletion and checking that extended object is compatible with "super" object.
