### ISSUE TITLE
zod/lib/external has no exported member 'infer'

### ISSUE THREAD

**Issue by dmmulroy** [colinhacks/zod#619]
I am having issues using `z.infer`. However, `z.TypeOf` (which looking at the types it appears `infer` is just an alias of `TypeOf`) is working.

```
const repaymentSchema = z.object({
  from: z.number(),
  to: z.number(),
  amount: z.string(),
});

export type Repayment = z.infer<typeof repaymentSchema>;
```

This results in the following error:
```
TSError: ⨯ Unable to compile TypeScript
src/splitwise/client.ts (11,27): Namespace '"/Users/dmmulroy/repos/ynab-splitwise-sync/node_modules/zod/lib/external"' has no exported member 'infer'. (2694)
```

Switching to the following works fine:

```
export type Repayment = z.TypeOf<typeof repaymentSchema>;
```

In vscode, the editor accurately infers the type when using `z.infer` but at compilation time it fails.

![infer working](https://user-images.githubusercontent.com/2755722/131260538-c329682a-5e9c-4909-9a9c-fdc38e83b7fc.png)

Here is my `tsconfig.json`:

```
{
  "extends": "@tsconfig/recommended/tsconfig.json",
  "compilerOptions": {
    "outDir": "./dist",
    "allowJs": true,
    "noErrorTruncation": true,
    "strictNullChecks": true
  }
}
```

**Comment by dmmulroy** [comment]
Ended up being a misconfiguration of `ts-node`

**Comment by Dealerpriest** [comment]
How exactly? I have theexact same issue. And I'm not using ts-node. The error just showed up suddenly, when I renamed a schema inside my schema file and saved. Boom. Suddenly infer was not recognized anymore. Any idea what could be the underlying problem?

**Comment by dmmulroy** [comment]
Ah I'm sorry, I can't remember what I changed and don't have access to the code anymore.
