### ISSUE TITLE
import lazy schema from other file module cause ts 4023

### ISSUE THREAD

**Issue by naivefun** [colinhacks/zod#622]
```
Exported variable '$ModelSchema' has or is using 
name 'IObjectPropertyDetails' from external module 
"~/packages/api/src/api/common/schema.schema" 
but cannot be named.ts(4023)
```
If I split schemas and import other schema which contains lazy properties, ts cannot infer the property correctly. I have to declare using zodschema<X>, is there other way?

**Comment by scotttrinh** [comment]
@naivefun 

Can you get a more concrete example of the issue you're having? Perhaps also a [CodeSandbox](https://codesandbox.io/) since it's about module issues?

**Comment by colinhacks** [comment]
@naivefun Just export `IObjectPropertyDetails` from `schema.schema.ts` as well and this error should go away.
