### ISSUE TITLE
Zod enums with any literals?

### ISSUE THREAD

**Issue by dartess** [colinhacks/zod#626]
Hi!

Is it possible to extend the functionality of zod enums to any literal, not just strings?

Examples of using:

```
z.enum([true, false, 'unknown'])
```

```
z.enum([400, 401, 404, 405, 500])
```

**Comment by dartess** [comment]
I tried to put together the validator I needed using `union`.

```ts
export function oneOf<TItem extends Primitive>(array: readonly TItem[]) {
    if (array.length < 2) {
        throw new Error('oneOf: too few elements');
    }
    const mappedArray = array.map(item => literal(item));
    type ItemType = (typeof mappedArray)[number];
    return union(mappedArray as [ItemType, ItemType, ...ItemType[]]);
}
```

But it takes a lot of effort to customize the error output:
```ts
case z.ZodIssueCode.invalid_union: {
    const unionIssues = issue.unionErrors.flatMap(error => error.issues);
    const unionExpected: string[] = [];
    unionIssues.forEach(unionIssue => {
        if (unionIssue.code === z.ZodIssueCode.invalid_type) {
            unionExpected.push(unionIssue.expected);
        }
    });
    if (unionExpected.length) {
        return { message: `custom union error text, expected: ${unionExpected.join(' | ')}, received: ${ctx.data}` };
    }
    return { message: `unknown union error: ${unionIssues.map(unionIssue => unionIssue.message).join(' | ')}` };
}
```

**Comment by scotttrinh** [comment]
I think you're correct in looking toward `union` as your solution here. Aside from customizing the error output, does using `union` work for your use case?

**Comment by dartess** [comment]
Seems to work) But I would like to see this solution out of the box.

Do you think that the union should be exactly the union of strings? I would like to understand the reasons for this decision.

**Comment by scotttrinh** [comment]
> Do you think that the enum should be exactly the enum of strings? I would like to understand the reasons for this decision.

I think the idea is that `enum` is related to the existing concept of TypeScript `enum`s which are either numbers or strings. Usable like this:

```ts
enum FruitEnum {
  banana = "banana",
  apple = "apple",
  orange = "orange",
}

const fruitEnumSchema = z.enum(["banana", "apple", "orange"]);

console.log(fruitEnumSchema.enum.banana); // "banana"
console.log(FruitEnum.banana); // "banana"
```

Gives you `enum`-like syntax but allowing using strings like a union of string literals. It attempts to bridge the gap between TypeScript's native `enum` and a union of string literals which is sometimes a nicer API than native enums.

**Comment by dartess** [comment]
Unfortunately, I didn't fully understand the idea.

Perhaps what I am suggesting will fit as a new method?  Or is it a bad idea?

**Comment by dartess** [comment]
My original problem was about the union of numbers.  I was surprised that the numbers don't go through.

**Comment by scotttrinh** [comment]
For a union of numbers, you'd want to use a `z.union([z.literal(1), z.literal(-1)])` (a union of number literals). `enum` is specifically a version of the existing TypeScript enum and string literal union concept.

> Perhaps what I am suggesting will fit as a new method? Or is it a bad idea?

I don' think we need a new method here, since `z.union` does the right thing from a type and parsing perspective. I believe making error reporting on `z.union` easier to override is probably the right approach here.

**Comment by dartess** [comment]
Thanks for answers!

>  I believe making error reporting on z.union easier to override is probably the right approach here.

Do I need to open an issue?

Do I need to close this?

**Comment by scotttrinh** [comment]
Per-schema error handling is definitely an issue we are already looking at (see #97), and I see that you've commented there already, so yeah, I'll close this and we can track toward a better solution for the error handling there.
