### ISSUE TITLE
TS assertion functions?

### ISSUE THREAD

**Issue by arv** [colinhacks/zod#630]
Can zod be used as ts assertion functions?

```ts
function assertNumber(v: unknown): asserts v is number {
  if (typeof v !== 'number') throw new Error();
}

function needsNumber(x: number) { ... }

declare const x: unknown;
assertNumber(x);
needsNumber(x);  // OK
```

**Comment by scotttrinh** [comment]
@arv 

Like type guards, we're unlikely to support it given that schemas can transform their inputs into completely different types such that only the resulting value can be safely assumed to be guarded. Luckily, `parse` itself throws so has a similar functionality:

[CodeSandbox](https://codesandbox.io/s/blissful-lamport-ycy34?file=/src/index.ts)
```ts
declare const x: unknown;
const parsed = z.number().parse(x);
needsNumber(parsed); // OK
```

—in general Zod is a utility for parsing input data, which is slightly different than validation. You can find more about the philosophical difference in [Alexis King's awesome article on the subject: Parse Don't Validate](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/).

If you have a schema that you're absolutely sure doesn't change it's input value, you can write a wrapper function to turn any such schema into a type guard or assertion functions:

```ts
function guardWith<T>(schema: z.Schema<T>, input: unknown): input is T {
  return schema.safeParse(input).success;
}

function assertWith<T>(
  schema: z.Schema<T>,
  input: unknown
): asserts input is T {
  schema.parse(input);
}
```

**Comment by arv** [comment]
Thanks. That seems like it might be sufficient for our use case.
