### ISSUE TITLE
Request: passthrough as an option to parse rather than a property of the type

### ISSUE THREAD

**Issue by yang** [colinhacks/zod#634]
Consider making passthrough a property of the parse operation rather than of the type.

If you have some zod types and want to parse some nested structure without stripping out unrecognized keys (analogous to the usual TS type-checking behavior on anything but literals), then currently, I believe you have to add `.passthrough()` to every type and construct a parallel family of types. Simply doing `.passthrough().parse()` on the top-most type doesn't seem to do it.

If you want some parse operations to strip and others to not, it's impossible without creating two parallel families of types.

**Comment by colinhacks** [comment]
Sorry this is by design. I don't like "modes" or parse parameters, schemas in Zod are designed to be self contained. If you need both variants, just assign the "passthrough version" to a separate variable

```ts
const schema = z.object({ name: z.string() });
const passthroughSchema = schema.passthrough();
```

**Comment by yang** [comment]
But it's not that simple, since you have to do this for every type, which is why you end up with two parallel DAGs of types - is this the intended DX?
