### ISSUE TITLE
Nesting Schemas

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [colinhacks/zod#637]
Is it possible to use zod schemas within other schemas? here a pseudocode.
```
const UserSchema = z.object({ username: z.string(), password: z.string()});

const LoginSchema = z.object({ usercredentials: UserSchema, accessToken: z.string()})
```

**Comment by Djaler** [comment]
Yes

**Comment by scotttrinh** [comment]
@sschneider-ihre-pvs 

It works exactly as you've pseudo-coded it 😆 
[TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFAxhAHYDO8AqgwKZQDK1AFmyAEM4AXhQA6CACMAVm2owAFEgCu7KHQEg2ALnFMowOgHMFASgA0cMAIYMA7tGK7kY-YZOm0pyjXpM4ADIQRobcfIIi4lKy8kpwqhzUUGzEbHQwwAIANgy6rBxh-AKWAtTUbLYAKhAA1mnOrjAGxmZeQA)

**Comment by sschneider-ihre-pvs** [comment]
Great :)
