### ISSUE TITLE
Email "////@////.////" is allowed

### ISSUE THREAD

**Issue by midgethoen** [colinhacks/zod#639]
I'm not an expert but shouldnt this fail?

```js
var zod = require("zod")

zod.string().email().parse('///@///.///')

```

https://runkit.com/embed/jnfvsg1uveyr

**Comment by scotttrinh** [comment]
Doesn't seem to violate the [rules](https://datatracker.ietf.org/doc/html/rfc3696). I don't think email email string validation is supposed to replace actually testing that the email works through some kind of signup email flow, so hopefully your application is already handling technically valid but unknown email addresses like this. FWIW: I definitely don't think we should be in the business of validating TLDs or anything like that.

**Comment by colinhacks** [comment]
Turns out almost every damn thing is a valid email: https://stackoverflow.com/questions/201323/how-can-i-validate-an-email-address-using-a-regular-expression

And in any case it's better to err on the side of permissiveness here.

**Comment by midgethoen** [comment]
Thanks for the responses,.

I  though it might be because of the nature of email addresses. i tested it using my email client; which did complain: 

![image](https://user-images.githubusercontent.com/4599476/133042043-b432bd71-da6e-401e-9298-733c6f041b01.png)

**Comment by midgethoen** [comment]
Thanks for the responses,.

I  though it might be because of the nature of email addresses. i tested it using my email client; which did complain: 

![image](https://user-images.githubusercontent.com/4599476/133042043-b432bd71-da6e-401e-9298-733c6f041b01.png)
