### ISSUE TITLE
es6 - Cannot read property '_parse' of undefined

### ISSUE THREAD

**Issue by Codii** [colinhacks/zod#643]
Hey all ! Thanks for the good work.

In my project, I am using `zod@3.8.1` and for some technical limitations I need to manipulate `z` objects into an es6 codebase. More specifically the `pick` operator.

So I have my object definition in TS package (built to es6) :

```typescript
export const Model = z.object({
  id: z.string().uuid(),
  name: z.string()
})
```

And in my es6 code I want to use a subset of this `Model`. Naively I do the following

```javascript
import { Model } from '@mystuff/models'

const ModelSubset = Model.pick({
  name: true
})
```

The inferred type of `ModelSubset` looks right. But on the runtime, when I do this : 

```javascript
const myValidModel = ModelSubset.parse({
  name: 'Kikoo'
})
```

`zod` throws me : 

```
TypeError: Cannot read property '_parse' of undefined
```

Redefining the object in the es6 package works though.. 🤔 

So, what am I missing ?

Thank you for reading and be well !

**Comment by colinhacks** [comment]
Is there a longer error with a stack trace?

**Comment by extradosages** [comment]
The quality of this error reminds me of the errors I get when I try to interface with a library using a different version of zod.

**Comment by scotttrinh** [comment]
> I have this same exact problem, though I do not do any building/compiling.

Just to clarify: You're using Zod in a vanilla JavaScript project without TypeScript?

**Comment by LucasForster** [comment]
Hey!

> `zod` throws me :
> 
> ```
> TypeError: Cannot read property '_parse' of undefined
> ```

I ran into the same error message and found this issue. Now while my problem is likely a different another one, I thought sharing this might still help others ending up here.

Essentially what I was doing is exporting a schema from one file, using it in another one to compose another schema, and then importing that composed schema back into the first file. While there isn't a cyclic dependency per se, it causes the mentioned error at runtime.

See this CodeSandbox for an example: https://codesandbox.io/s/patient-butterfly-hsg3q?file=/src/index.ts The message isn't as descriptive as in my local (larger) project, but removing this exact kind of import solved it for me. (Maybe this is generally "wrong" in terms of my tsconfig or simply unsupported by zod and I don't know it, but I would intuitively expect it to work 🙈.)
