### ISSUE TITLE
Reference other types in zod object

### ISSUE THREAD

**Issue by CalebDelbridge** [colinhacks/zod#644]
Is it possible to reference another value in an object to, let's say, check if the start time is before the end time [like in yup](https://github.com/jquense/yup#yuprefpath-string-options--contextprefix-string--ref)?

**Comment by balazsszekely** [comment]
Yes, as I know the best option is the [.refine()](https://github.com/colinhacks/zod#refine) function:

```
import { z } from "zod";

const schema = z
  .object({
    start: z.date(),
    end: z.date()
  })
  .refine((x) => x.start < x.end, {
    message: "End time must be greater than start time.",
    path: ["end"] //optional
  });
```

**Comment by colinhacks** [comment]
That's right. There's no equivalent of `yup.ref` in Zod. Everything is achievable with `refine` and `transform`.

**Comment by CalebDelbridge** [comment]
Great thank you
