### ISSUE TITLE
z.union.default Has Unexpected Type Error

### ISSUE THREAD

**Issue by FlorianWendelborn** [colinhacks/zod#646]
First of all, thanks for this excellent library. I’m currently tying too hard to integrate it everywhere I possibly can haha

I found a rather minor type issue. Not sure if I’m misusing it, but it seems to work as expected at run-time — just not at compile-time. When using `z.union`, using `.optional()` seems to not be possible, at least in this case that I encountered and simplified into an example. As far as I can tell, runtime seems to work as-expected after adding a `@ts-expect-error`.

## Reproduce

**Link**: [TS Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFApgHYCueA0sLcYhXF3AIIByASQCyPADJwAvAX7Cx+ADSduAMVEB5AOoBRAEqSCqzboUU0VAMYRaAZ3gAPfciUA6erWBWAFAG0lXZM4QAEYAVtTmMJ5IANasxABcKM4ANsAw1FAAhsme+JnuINn4AJTycMnUAObWiQEMIEEZnsXopX5JwWERUXCxbLUpaRnZuZjJEADuGSVlY5MZNUn1jVDNrYpcALrFLsTUmJn0yZFrEgB8cD19CQT5oEVlFdWJACytxZQUljbwAJ6OLjcHloPnaAU64UiMTiA1S6SyORYbGcMhEolK5SqizqjBWazQbW4HVCkKuMKScOGiLizkM2h0GLmUyg2OcyyaLQJGzg212+0Ox08pwuZP6cCRxBRgjRjyxr3eZCAA)

```ts
import { z } from "zod";

enum Kind {
    ANIMAL = "ANIMAL",
    FLOWER = "FLOWER",
}

const x = z
  .union([
    z.object({ kind: z.literal("animal"), legs: z.number() }),
    z.object({ kind: z.literal("flower"), flowers: z.number() }),
  ])
  .default(() => ({ kind: "animal", legs: 4 }));

const y = z
  .union([
    z.object({ kind: z.literal(Kind.ANIMAL), legs: z.number() }),
    z.object({ kind: z.literal(Kind.FLOWER), flowers: z.number() }),
  ])
  .default(() => ({ kind: Kind.ANIMAL, legs: 4 }));
```

### Expected Behavior

No type error is produced

#### `x`

```
No overload matches this call.
  Overload 1 of 2, '(def: { kind: "animal"; legs: number; } | { kind: "flower"; flowers: number; }): ZodDefault<ZodUnion<[ZodObject<{ kind: ZodLiteral<"animal">; legs: ZodNumber; }, "strip", ZodTypeAny, { ...; }, { ...; }>, ZodObject<...>]>>', gave the following error.
    Argument of type '() => { kind: string; legs: number; }' is not assignable to parameter of type '{ kind: "animal"; legs: number; } | { kind: "flower"; flowers: number; }'.
      Type '() => { kind: string; legs: number; }' is missing the following properties from type '{ kind: "flower"; flowers: number; }': kind, flowers
  Overload 2 of 2, '(def: () => { kind: "animal"; legs: number; } | { kind: "flower"; flowers: number; }): ZodDefault<ZodUnion<[ZodObject<{ kind: ZodLiteral<"animal">; legs: ZodNumber; }, "strip", ZodTypeAny, { ...; }, { ...; }>, ZodObject<...>]>>', gave the following error.
    Type 'string' is not assignable to type '"animal" | "flower"'.(2769)
```

#### `y`

```
No overload matches this call.
  Overload 1 of 2, '(def: { kind: Kind.ANIMAL; legs: number; } | { kind: Kind.FLOWER; flowers: number; }): ZodDefault<ZodUnion<[ZodObject<{ kind: ZodLiteral<Kind.ANIMAL>; legs: ZodNumber; }, "strip", ZodTypeAny, { ...; }, { ...; }>, ZodObject<...>]>>', gave the following error.
    Argument of type '() => { kind: Kind; legs: number; }' is not assignable to parameter of type '{ kind: Kind.ANIMAL; legs: number; } | { kind: Kind.FLOWER; flowers: number; }'.
      Type '() => { kind: Kind; legs: number; }' is missing the following properties from type '{ kind: Kind.FLOWER; flowers: number; }': kind, flowers
  Overload 2 of 2, '(def: () => { kind: Kind.ANIMAL; legs: number; } | { kind: Kind.FLOWER; flowers: number; }): ZodDefault<ZodUnion<[ZodObject<{ kind: ZodLiteral<Kind.ANIMAL>; legs: ZodNumber; }, "strip", ZodTypeAny, { ...; }, { ...; }>, ZodObject<...>]>>', gave the following error.
    Type '{ kind: Kind; legs: number; }' is not assignable to type '{ kind: Kind.ANIMAL; legs: number; } | { kind: Kind.FLOWER; flowers: number; }'.
      Type '{ kind: Kind; legs: number; }' is not assignable to type '{ kind: Kind.ANIMAL; legs: number; }'.
        Types of property 'kind' are incompatible.
          Type 'Kind' is not assignable to type 'Kind.ANIMAL'.(2769)
```

## Versions

**TypeScript**: `4.4.2`
**zod**: `3.8.2`

**Comment by FlorianWendelborn** [comment]
Actually, after tying to simplify this even further to a `union(literal, literal)`, I think I figured out a viable solution to this that requires no changes to `zod` (not sure if that would even be possible TBH).

It seems that `zod` is correctly typed, but TS doesn’t recognize that the default value returns only a part of the enum/string, so hinting that the return type is `as const` successfully resolves the type issue:

---

**Link**: [TS Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFApgHYCueA0sLcYhXF3AIIByASQCyPADJwAvAX7Cx+ADSduAMVEB5AOoBRAEqSCqzboUU0VAMYRaAZ3gAPfciUA6erWBWAFAG0lXZM4QAEYAVtTmMJ5IANasxABcKM4ANsAw1FAAhsme+JnuINn4AJTycMnUAObWiQEMIEEZnsXopX5JwWERUXCxbLUpaRnZuZjJEADuGSVlY5MZNUn1jVDNrYpcALrFLsTUmJn0yZFrEgB8cD19CQT5oEVlFdWJACytxZQUljb2ysB21HYUicXFc7i8vm4HVC4UiMTiA1S6SyOTyBSKpXKVUWdUYKzWaDaUICnVhVwRSSRw1RcymUBmWHGdJxzmWTRahI2cG2u32h2OnlOF3J-Vu6OS+DgmWscG+tke2Ne70+cvgAE9HC43B5aD52iSYd14aKAlSUZ4WGxnDIRKJMU8WWzVhyidwDV04b0KaahubLcRnIZtDpMbSFgMnQTXTzQXsDkcTi1zpdjTd-dbBLaFc84G9CR8LFZbHA1X8AUCUFrwbrIW7AobPddEb6RumbWJ7Yqlnj2et9fWPSKbj7ka24oH1MHQ0zw92Gr3OUoY3BnHH+YnJMLU4k25mxFKZars4s88UPkA)

```ts
import { z } from "zod";

enum Kind {
    ANIMAL = "ANIMAL",
    FLOWER = "FLOWER",
}

const xFixed = z
  .union([
    z.object({ kind: z.literal("animal"), legs: z.number() }),
    z.object({ kind: z.literal("flower"), flowers: z.number() }),
  ])
  .default(() => ({ kind: "animal" as const, legs: 4 }));

const yFixed = z
  .union([
    z.object({ kind: z.literal(Kind.ANIMAL), legs: z.number() }),
    z.object({ kind: z.literal(Kind.FLOWER), flowers: z.number() }),
  ])
  .default(() => ({ kind: Kind.ANIMAL as const, legs: 4 }));
```

---

I therefore think that this issue can be closed now, as rubber-duck debugging has yielded a good fix once again 🙂

However, as this was a bit counter-intuitive (at least for me), I’d say it’s still a good issue to have in case someone else stumbles into this or googles for a similar problem.

Not closing this myself now, as I’d prefer to confirm that there’s nothing `zod` can do to make the fix unnecessary. Perhaps I’m missing some possibility of getting this resolved forever without `as const`, or perhaps this could be a great addition to the documentation of `.default()` to always add `as const`

**Comment by FlorianWendelborn** [comment]
@stale Please don’t

**Comment by PabloLION** [comment]
I think this issue here is resolved, during which another new issue  about docs emerged. Maybe it's better to close this one and create a new issue?
