### ISSUE TITLE
z.enum for as const numbers?

### ISSUE THREAD

**Issue by mmahalwy** [colinhacks/zod#654]
This works nicely:
```ts
const VALUES = ["Salmon", "Tuna", "Trout"] as const;
const FishEnum = z.enum(VALUES);
// 'Salmon' | 'Tuna' | 'Trout'

```

But this does not work:
```ts
const VALUES = [1, 2, 3] as const;
const OrderEnum = z.enum(VALUES);
// 1 | 2 | 3
```
This is due to the requirement of having an array of strings, although a union of numbers work. 

Thoughts?

**Comment by dankolesnikov** [comment]
This would be very helpful to the problem I am currently facing at work, my data is represented as an array of numbers but because Zod is forcing to use string, creates ambiguity. 

Is there a reason why it has to be an array of strings and that it can't numbers?
@colinhacks Would love your input!

**Comment by mmahalwy** [comment]
@scotttrinh agreed that union _could_ work but the use case is for an already existing array.

**Comment by colinhacks** [comment]
Enums should never be numbers. By default enum values in TypeScript are numbers, but this is a footgun and an antipattern. 

```ts
enum Color { Red, Green };
Color.Red; // 0
```

If you add another color the actual under-the-hood value changes:
```ts
enum Color { Blue, Red, Green };
Color.Red; // 1
```

Which is the source of a lot of bugs and confusion. So Zod forces you to use strings.

This also lets you access the elements of the enum like so:

```ts
const Color = z.enum(["Red", "Green"]);
Color.enum.Red; // "Red"
```

Which is importany, and wouldn't be possible with numbers. 

I recommend writing a generic function that accepts a list of numbers and exports a `z.custom` schema:

```ts
const numberEnum = <Num extends number, T extends Readonly<Num[]>>(
    args: T
  ): z.ZodSchema<T[number]> => {
    return z.custom<T[number]>((val: any) => args.includes(val));
  };

  const nums = [1, 2, 3] as const;
  const schema = numberEnum(nums);
```

**Comment by mmahalwy** [comment]
Heads up, this is now broken with v3.9.3 @colinhacks

**Comment by scotttrinh** [comment]
@mmahalwy 

[CodeSandbox](https://codesandbox.io/s/determined-kilby-e09x4?file=/src/index.ts)

Am I setting this up incorrectly? It throws in my testing on 3.9.3 and 3.9.4 🤔

**Comment by mmahalwy** [comment]
@scotttrinh reproduced it here: https://codesandbox.io/s/dreamy-dawn-2b79i?file=/src/index.ts

I think when you have a union it breaks:

```ts
import { z } from "zod";

const schema = z.custom((val: any) => {
  return false;
}, `Error please`);

const objSchema = z.union([
  z.object({
    schemaValidation: schema,
    shouldBeNull: z.null()
  }),
  z.object({
    schemaValidation: schema,
    shouldBeNumber: z.number()
  })
]);

const result = objSchema.safeParse({
  schemaValidation: 1,
  shouldBeNumber: 1
});
console.log(result);
console.log(!result.success && JSON.stringify(result.error, null, 2));

```

**Comment by scotttrinh** [comment]
Ahh, I see. Others have reported issues with `union` lately, so I suspect that is the issue. Once @colinhacks has a chance to address, I'll keep an eye on this repro case.

**Comment by diogoazevedos** [comment]
@colinhacks this feature would increase the parity with the native TypeScript enum. Also would allow validation of a specific set of numbers.

I know it's possible to achieve the same validation using `union`, but the error is not as descriptive.

Numbers seem to be already supported, so it's a matter of adjusting the types:

https://github.com/colinhacks/zod/blob/ab75f4dad2a6738c019fe4edea6c8603c25ecb18/src/types.ts#L2940-L3012
