### ISSUE TITLE
Bug: "Required" Behavior Not Working 

### ISSUE THREAD

**Issue by rubber-duck-software** [colinhacks/zod#658]
### The Problem
It stands to reason that if I declare 
```js
const requiredSchemaA = schemaA.required();
```
 then
```js
requiredSchemaA.shape.someProp.isOptional() 
```
would be `false`. 

However, this is not necessarily the case. 

### Repro Steps 
Here is the playground.ts to reproduce
```js
const schemaA = z.object({
  someProp: z
    .string()
    .optional()
    .refine(() => true),
});

const requiredSchemaA = schemaA.required();

console.log(requiredSchemaA.shape.someProp.isOptional());
```

### Proposed Solution
Add a new type ```ZodRequired```. I realize a type like `ZodRequired<ZodOptional<ZodString>>` is a bit clumsy, but `ZodRequired` could successfully handle cases where ZodOptional is "hidden" by some other type (ie ZodEffects).

**Comment by nemonemi** [comment]
Hi, perhaps these two ticket are similar?
https://github.com/colinhacks/zod/issues/781
