### ISSUE TITLE
parameters for function schemas that have implement

### ISSUE THREAD

**Issue by mmahalwy** [colinhacks/zod#660]
For function schemas that use the `implement()` method, I noticed the `parameters` cannot be extracted. Any workaround there other than splitting it into two:

```ts
const _myFunction = z
  .function()
  .args(z.string(), z.number()) // accepts an arbitrary number of arguments
  .returns(z.boolean());

_myFunction.parameters() // works

const myFunction = _myFunction.implement((x) => {
    return true
  });
```

**Comment by colinhacks** [comment]
Nope, `.implement` just returns a plain function. It's possible to add properties onto a function, but that seems a little weird.

**Comment by mmahalwy** [comment]
@colinhacks makes sense. I guess only way is to split is as show in the example?
