### ISSUE TITLE
Is there a way to type-check for an instantiated Primitive's type?

### ISSUE THREAD

**Issue by TheMeteoRain** [colinhacks/zod#680]
Hello, is there a way to check if instantiated Primitive type is that type.
new Number() === number
new String() === string

I've had no luck. Here are some of my test cases
```
import * as s from 'superstruct'

// Checking for an empty object. Output true. This is correct
s.is({}, s.object({}))

// Checking for and empty object. Output false. This is correct
s.is({ propertyName: "propertyValue" }, s.object({}))

//  Checking for an object. Output true. I would like this to be false.
s.is(new Number(43), s.object())

//  Checking for number. Output false. I would like this to be true.
s.is(new Number(43), s.number())
```
I know why it would do this. It's an instantiated Number that has prototype of object.

I have ways to find out that these ones are a typeof number.
I figured if zod would like to support for this kind of type-checking in any other way.
I'm fine if earlier examples stays that way, because one can argue that instantiated Primitive's type is an object.

I would like to see a function that sees through the instantiated Primitive prototype and compare the real value inside.
Example:
```
s.typeof(new Number(43), 'number') // true
or
s.typeof(new Number(43), s.number()) // true

s.typeof(new Number(43), 'object') // false
or
s.typeof(new Number(43), s.object()) // false
```

**Comment by scotttrinh** [comment]
Maybe you're thinking of the `instanceof` schema?

[CodeSandbox](https://codesandbox.io/s/hungry-darwin-xbfwh?file=/src/index.ts)

```ts
import test from "tape";
import { z } from "zod";

const schema = z.object({
  foo: z.instanceof(Number)
});

test("valid", (t) => {
  t.true(schema.safeParse({ foo: new Number(42) }).success);
  t.end();
});

test("invalid", (t) => {
  t.false(schema.safeParse({ foo: "invalid" }).success);
  t.end();
});
```

**Comment by TheMeteoRain** [comment]
Seems like I accidentally posted a question about `superstruct` in `zod`. Thank you for the answer, nice to know it's possible in `zod`. I did try to search for the functionality before I started to read `superstruct` documenation.

**Comment by scotttrinh** [comment]
@TheMeteoRain 

Yeah, I was a little confused by all of the superstruct code, but I thought maybe you were trying to compare the two 😆 

superstruct is a great library that has totally different ergonomic goals and make different trade-offs, so I think between it and zod you'll probably find something that feels natural to you and your codebase. Best of luck!
