### ISSUE TITLE
z.object: properties are optional by default?

### ISSUE THREAD

**Issue by dmacthedestroyer** [colinhacks/zod#684]
When I use `z.object`, the fields within the object seem to be optional by default. I would expect the opposite. Is  this the expected behavior, or is there something I'm missing? It doesn't seem to be the behavior demonstrated in the [documentation](https://github.com/colinhacks/zod#objects).

os: windows
npm version: 7.24.1
node version: v14.16.0
typescript version: 4.4.3
zod version: 3.9.5

[repro repo](https://github.com/dmacthedestroyer/zod-fields-bug)

## Repro steps
```
npm init
npm install typescript zod
touch index.ts
```

`index.ts`:
```
import { z } from "zod";

const shape = z.object({
  foo: z.string(),
  bar: z.number(),
});

type Shape = z.infer<typeof shape>;
````

VS Code indicates that foo and bar are both optional:
```
type Shape = {
    foo?: string;
    bar?: number;
}
```

I'd expect them to be _not_ optional:
```
type Shape = {
    foo: string;
    bar: number;
}
```

Love the library, by the way -- you're a legend :)

**Comment by scotttrinh** [comment]
Yeah, you have to set `strict` in your `tsconfig.json` to get the correct type checking, so given your lack of config in your example, I think it doesn't default to `strict`?

**Comment by prescience-data** [comment]
I am experiencing this issue strangely when importing a schema from a second package in a monorepo.

When I copy the schema locally, and call `parse` it resolves correctly (ie `number`), however when I call parse on the imported on it resolves as `number | undefined`.

Bizarre  🤔

**Comment by scotttrinh** [comment]
@prescience-data I believe that's a different issue than this one, but I suspect different zod versions between the two repos? Try aligning them and see if that helps. If it doesn't feel free to open a new issue.
