### ISSUE TITLE
Type guard for parse function

### ISSUE THREAD

**Issue by TheMeteoRain** [colinhacks/zod#686]
Hello,

I was excited to use `zod` to validate my objects in typescript. I quickly ran into a problem.
parse function does return the correct type but not as type guarded.

https://github.com/colinhacks/zod/blob/9648f3f632280614e07da9621af6e1a8440d678c/src/types.ts#L168
For type guards to kick in, this line should be written like:
`parse(data: unknown, params?: Partial<ParseParamsNoData>): data is Output`

This becomes problem when I try to make if-statements to make sense of what exact type I'm currently dealing with:
![image](https://user-images.githubusercontent.com/14369871/135768751-0288031d-5614-4043-9d14-efd7d8a8f9a6.png)

Could this be possible change? Or are there some unseen outliers why this is not the case currently?

Type guards: https://www.typescriptlang.org/docs/handbook/advanced-types.html

**Comment by TheMeteoRain** [comment]
Just hopped on to look at https://github.com/colinhacks/zod/issues/630 seems like there are some techinal problems.

**Comment by TheMeteoRain** [comment]
Well I guess, my question is: could there be an option to do type guarding with `zod`. I'm fine doing my own little wrapper, but that could easily be supported by the library itself?

**Comment by scotttrinh** [comment]
@TheMeteoRain 

Yeah, as pointed out in the issue that you linked, we are not going to be adding type guards any time soon. We used to have them in v1, but due to how our "effects" system works, we are avoiding them.
