### ISSUE TITLE
`.refine` is being short circuited since 3.9.6

### ISSUE THREAD

**Issue by azhiv** [colinhacks/zod#690]
In our app we used to rely on the `.refine`s execution being chained, e.g.
```ts
const objectSchema = zod
  .object({
    length: zod.number(),
    size: zod.number(),
  })
  .refine(({ length }) => length > 5, { path: ['length'], message: "length greater than 5" })
  .refine(({ size }) => size > 7, { path: ["size"], message: "size greater than 7" });

console.log(
  objectSchema.and(objectSchema).safeParse({
    length: 4,
    size: 4,
  })
);
```
would yield two errors for both length and size. However, this behaviour is broken by 3.9.6.
Is there a way to execute all refines that are defined on the schema?
[Sandbox](https://codesandbox.io/s/tender-kare-xxyoz?file=/src/index.ts)

**Comment by azhiv** [comment]
Does it make sense to skip further refines only if they share the same `path`? This schema
```ts
const objectSchema = zod
  .object({
    length: zod.number(),
    size: zod.number(),
  })
  .refine(({ length }) => length > 5, { path: ['length'], message: "length greater than 5" })
  .refine(({ size }) => size > 7, { path: ["size"], message: "size greater than 7" })
  .refine(({ length, size }) => length !== size, { path: ['length'], message: "length cannot be equal to size" });

console.log(
  objectSchema.and(objectSchema).safeParse({
    length: 4,
    size: 4,
  })
);
```
could still yield two errors in this case and skip the last one because it doesn't add much info until the first issue is fixed.

**Comment by colinhacks** [comment]
Unfortunately I had to roll back the 3.9 change that prevented short-circuiting on refinements. The approach I used was somewhat ill-conceived and introduced several bugs like #688. I will re-introduce this functionality in 3.10 with a better implementation - working on that now. 

I understand your argument but I think all chained refinements should all be executed. I'll clarify in the docs that "coupled" refinements (where the nth refinement assumes all previous refinements have passed) is not recommended and should probably be rewritten as a single larger refinement.

**Comment by azhiv** [comment]
@colinhacks Just to be clear - my only concern is that among two refinements the second one is not executed if the first one is falsy. This is not convenient when used in form validation where all erroneous fields should be highlighted. The current zod's implementation only highlights the first field.
So are you working on a fix that will execute both refines in my first example?

**Comment by azhiv** [comment]
Great! I'm eagerly waiting for the changes)

**Comment by azhiv** [comment]
@colinhacks Upon 3.10 the following [example](https://codesandbox.io/s/cold-cdn-d2sou?file=/src/index.ts) gives a false positive result:
```ts
const objectSchema = zod
  .object({
    length: zod.number(),
    size: zod.number()
  })
  .refine(({ length }) => length > 5, {
    path: ["length"],
    message: "length greater than 5"
  })
  .refine(({ size }) => size > 7, {
    path: ["size"],
    message: "size greater than 7"
  });

console.log(
  objectSchema.and(objectSchema).safeParse({
    length: 4,
    size: 8
  })
);          // { success: true, ...
```
The first `refine` (for `length`) is being ignored.
