### ISSUE TITLE
Get the list of keys from a schema

### ISSUE THREAD

**Issue by efflam** [colinhacks/zod#692]
Hello,
I would like to know if there is an "official" way of getting the list of keys from a schema.
Given this schema :
```
const schema = z.object({
	civility: z.string().nonempty("Required field"),
	firstname: z.string().nonempty("Required field"),
	lastname: z.string().nonempty("Required field"),
});
```
I would like to retrieve this array :
```
["civility", "firstname", "lastname"]
```

The final goal is to automatically `pick` a subset of the full User object to pass it as default values to a form.

Thank you

**Comment by ppiwo** [comment]
For anyone else that stumbles upon this, I think there's a cleaner solution available now

https://zod.dev/?id=keyof
