### ISSUE TITLE
`ZodNumber.step` does not use the same logic as number input `step`

### ISSUE THREAD

**Issue by scotttrinh** [colinhacks/zod#702]
This implementation fails with cases like the following:

`23.9 % 0.01 = 0.009999999999998082`

_(the client enters a price, that must have at max 2 decimal places, = step(0.01))_

https://stackoverflow.com/questions/7037926/javascript-how-to-tell-if-one-number-is-a-multiple-of-another

https://stackoverflow.com/questions/3966484/why-does-modulus-operator-return-fractional-number-in-javascript

@StefanTerdell @colinhacks @scotttrinh 

For my case, it would be good a validation like max/minDecimals(), but maybe you can come up with better solutions.

_Originally posted by @SrBrahma in https://github.com/colinhacks/zod/issues/623#issuecomment-939585373_

**Comment by JacobWeisenburger** [comment]
Has this issue been resolved? I see that https://github.com/colinhacks/zod/pull/623 was merged, but not sure if that fixed this.
