### ISSUE TITLE
Check value against another value in schema

### ISSUE THREAD

**Issue by viduli-prime** [colinhacks/zod#709]
Maybe I missed it but is there a way to check the value of one property of the object against the value of another property of the same object? Like below,

```
const schema = z.object({
  lower: z.number(),
  upper: z.number()    // Check this value is greater than lower
})
```

**Comment by scotttrinh** [comment]
@viduli-prime 

You can use `refine` on the object schema itself to do arbitrary checks. Just note that `refine` returns a `ZodEffect` _not_ a `ZodObject` which is often a source of confusion and frustration. Here is a pattern that I've used lately:

```ts

export const uncheckedSchema = z.object({
  lower: z.number(),
  upper: z.number(),
});

export const checkRange =
  ({ lower, upper }: { lower: number; upper: number }) => upper > lower;

export const schema = uncheckedSchema.refine(checkRange);
```

The reason for the extra indirection is that if you need to `pick` or `extend` or do any other `ZodObject` method on the base schema, you'll need to add the refinement after calling that, and only if it still makes sense:

```ts
import { uncheckedSchema, checkRange } from "./module-a";

const extendedSchema = uncheckedSchema.extend({
  middle: z.number(),
}).refine(checkRange);

const pickedSchema = uncheckedSchema.pick({
  lower: true,
}); // you can't use that refinement here since `upper` isn't defined anymore!
```
