### ISSUE TITLE
Zod 3.10.1 not returning default values when schema uses `refine`

### ISSUE THREAD

**Issue by dio-az** [colinhacks/zod#717]
Hey,

I'm experiencing the following issue with Zod 3.10.1: the `parse` is not returning the default values when the schema uses `refine`.

Here's the code to reproduce the issue:

```js
const { deepEqual } = require('assert');
const { z } = require('zod');

const schema = z
  .object({
    a: z.string().default('foo'),
    b: z.number()
  })
  .refine(({ b }) => b > 0);

const result = schema.parse({ b: 1 });

deepEqual(result, { a: 'foo', b: 1 });
```

**Comment by colinhacks** [comment]
Oops. Fixed in zod@10.0.2. Just made some major changes to the parser in the 3.10 release and we're still working out some kinks.
