### ISSUE TITLE
Support for frozen/readonly

### ISSUE THREAD

**Issue by derolf** [colinhacks/zod#728]
I would like to have a way to declare an object with the following restrictions:
- All properties of the inferred type should be (recursively) `readonly`
- Parsing an object should (recursively) `freeze` it

```ts
import * as z from "zod";

export const Vector2 = z.frozenObject({
  x: z.number(),
  y: z.number(),
});

export type Vector2 = z.infer<typeof Vector2>;

const foo: Vector2 = { x: 1, y: 2 };

// the following should not be allowed by the compiler
foo.x = 42;

const bar = Vector2.parse('{ "x": 1, "y": 2 }');

// the following should not be allowed by the compiler and throw at runtime (because the object is frozen)
bar.x = 42;
```

**Comment by evantrimboli** [comment]
In conjunction, it would also be nice to be able to specify specific properties being readonly:

```typescript
export const Vector2 = z.object({
  x: z.number().readonly(),
  y: z.number().readonly(),
});
```

**Comment by jasonkuhrt** [comment]
Looking for this myself today.

**Comment by MaximeBernard** [comment]
@colinhacks could we reopen this? Seems like a nice feature.

We try to enforce eslint rule [prefer-readonly](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/prefer-readonly.md) and zod comes in our way :)
