### ISSUE TITLE
add jsdoc

### ISSUE THREAD

**Issue by jasonkuhrt** [colinhacks/zod#736]
<img width="849" alt="CleanShot 2021-10-27 at 20 24 03@2x" src="https://user-images.githubusercontent.com/284476/139165862-422ab562-2594-41e9-959a-ecc0a7e71726.png">

In the above it would be nice to know more about what `email` is. I think it means that it will validate for a valid email. However there is also `isEmail`. Generally JSDoc would be great for docs.

Also, if you rely on https://paka.dev/npm/zod for your docs then you'll get to re-use your JSDoc for your website doc. Full disclaimer I am the co-creator of Paka.

-- edit: Oh looks like docs extraction for Zod on Paka is broken, I'll look into that. For a working example you can check out https://paka.dev/npm/nexus.

**Comment by jasonkuhrt** [comment]
Another concrete use-case:

is `max` zero indexed or not?

<img width="782" alt="CleanShot 2021-11-01 at 08 08 38@2x" src="https://user-images.githubusercontent.com/284476/139669184-7366fd8c-75c8-4ea3-8843-f29eda0b3f17.png">

**Comment by jasonkuhrt** [comment]
> Only I think it'd be better to keep the type annotations in typescript, and just offer IDE descriptions. I'm not sure if that would be a degraded DX for js only consumers of this library

> I'm not sure how to automate that for maintainability.

VSC IDE already brings type benefits to JS users. The goal here IMO should be strictly about documenting things that fall outside the type system.

**Comment by colinhacks** [comment]
Completely agree, this definitely needs to happen. I'll try to do this over the weekend unless a PR appears in the meantime.

**Comment by jasonkuhrt** [comment]
TSDoc should be used and I suggest using the TSDoc eslint plugin to help.

**Comment by jasonkuhrt** [comment]
bump

**Comment by Gejsi** [comment]
I believe this issue should be re-opened.
JSDocs would greatly improve the DX, reducing the need to check the docs frequently.
Maybe, even adding some `@example`s for more complex functions, but leaving the type annotations to Typescript.
@colinhacks what do you think?

**Comment by nightknighto** [comment]
Sad

**Comment by michael-azogu** [comment]
need this

**Comment by kovaxis** [comment]
would love this as well
