### ISSUE TITLE
No exported member 'ParseParamsNoData'

### ISSUE THREAD

**Issue by bpc1985** [colinhacks/zod#738]
Hi,

Currently I use Zod with React Hook Form as validation schema. However when building code for production usage, I got this error:

**tsc && vite build

node_modules/@hookform/resolvers/zod/dist/types.d.ts:3:100 - error TS2694: Namespace '"/home/node_modules/zod/lib/external"' has no exported member 'ParseParamsNoData'.

export declare type Resolver = <T extends z.Schema<any, any>>(schema: T, schemaOptions?: Partial<z.ParseParamsNoData>, factoryOptions?: {

Found 1 error.**

Zod version is 3.11.6
React-hook-form 7.17.2
@hookform/resolvers 2.8.2

**Comment by kompot** [comment]
it's fixed in @hookform/resolvers 2.8.3
