### ISSUE TITLE
Recommended practice for literal error messages?

### ISSUE THREAD

**Issue by ricardo-rp** [colinhacks/zod#746]
At the moment, I'm using 
`terms: z.boolean().refine(value => value, 'You must accept terms and conditions.'),`
Since, as I understand, custom error messages are not yet supported for `z.literal(true)`
Is this the recommended practice or is there another, more practical way?

**Comment by colinhacks** [comment]
Currently `invalid_type_error` and `required_error` is actually supported in every Zod type, though I haven't documented them...

This works:

```ts
z.literal(true, {
  invalid_type_error: "Must be true"
});
```

**Comment by ricardo-rp** [comment]
@colinhacks Thank you. Works perfectly and is much cleaner.
