### ISSUE TITLE
Customizing array validation messages

### ISSUE THREAD

**Issue by Namchee** [colinhacks/zod#754]
Currently, `.array()` schema does not receives any arguments. It would be nice if it could accept `RawCreateParams` so we can customize their error messages. For example,

```ts
const schema = z.array(
  {
    required_error: 'This is required',
    invalid_type_error: 'This must be an array',
  },
);
```

**Comment by scotttrinh** [comment]
@Namchee 

The documentation is lagging a bit behind the latest changes, but `ZodArray` does indeed take a `RawCreateParams`. In fact, `z.array` takes two params, the schema of the element type and the `RawCreateParams`:

https://github.com/colinhacks/zod/blob/f4cd16d62ff79d7741c1f1d089265e589325b987/src/types.ts#L1245-L1248

I'll close this for now, but feel free to ask any followup questions. Updating the documentation for the last round of releases is something we should prioritize and get working soon, thanks for brining this up!
