### ISSUE TITLE
All properties are NOT required by default on inferred type

### ISSUE THREAD

**Issue by gibbok** [colinhacks/zod#757]
I am following the README, at this point

https://github.com/colinhacks/zod#objects

an example is provided stating that "all properties are required by default", but when inspecting the inferred types I see that all properties are **optional** instead.

Minimal reproducible example (zod v 3.11.6)
https://stackblitz.com/edit/react-ts-eihrxu

Hover on line 18 on `DogType`

I can see the inferred type as:

```
type DogType = {
    name?: string;
    age?: number;
}
```
when instead, accordingly to the doc should be:

```
type DogType = {
    name: string;
    age: number;
}
```

Questions:

- Is the document correct/updated?
- How to make sure the properties are not inferred as optional? If you would provide a working sample I would appreciate it

Thanks for your time and great work on zod!

**Comment by scotttrinh** [comment]
Our weekly report of this issue 😆 

You have to set your `tsconfig.json` to enable `strict: true`

![image](https://user-images.githubusercontent.com/1682194/141149987-d8ad43ed-b854-415e-bddc-2837b8271e44.png)

**Comment by gibbok** [comment]
@scotttrinh thanks for your answer
unfortuantelly our project suppor strict mode only via
https://github.com/allegro/typescript-strict-plugin
adding `//@ts-strict` in the file seems that does not work here

**Comment by scotttrinh** [comment]
@gibbok 

I'm unfamiliar with that tool, definitely seems cool! Unfortunately, I don't have any idea how to add support for that workflow: Zod itself _requires_ strict mode and if it's not present, this is the output of the type checker. Maybe it's worth opening an issue with that plugin?

**Comment by gibbok** [comment]
@scotttrinh yes sure, I will write to the other repo. Thanks for your help on this! 😄

**Comment by scotttrinh** [comment]
@gibbok no problem! if you get something working, feel free to report back here and we can update the readme to help anyone else who might hit up against this issue. 👍
