### ISSUE TITLE
zod object schemas being treated as partial

### ISSUE THREAD

**Issue by ksmithut** [colinhacks/zod#762]
The following example is using zod@3.11.6

```js
import { z } from 'zod'

const schema = z.object({
  type: z.string()
})

const foo = schema.parse(12)
```

This might be a bug with vscode (Version: 1.62.2), but when I hover over `foo`, it shows me that `foo.type` is optional:
<img width="622" alt="Screen Shot 2021-11-13 at 14 42 31" src="https://user-images.githubusercontent.com/1906967/141659975-12d6ff98-e0f6-4524-9099-4b5a533c3838.png">

The typescript cli (running `tsc`) doesn't complain about anything. So it's probably just something with vscode itself, but I wondered if maybe you might have some insight as to why that might happen so I can open the appropriate issue on their repo.

**Comment by kimroen** [comment]
Hi! This will happen if TypeScript is not running with the compiler flag [`strictNullChecks`](https://www.typescriptlang.org/tsconfig#strictNullChecks) enabled, which unfortunately is the default. I'd look to make sure you have a `tsconfig.json` file that either sets `strictNullChecks` directly, or enables `strict` (which also enables `strictNullChecks`).

You can run `tsc --init` to create a `tsconfig.json` file to start from if you don't have one.

VSCode should read the `tsconfig.json` file if available, but you might also need to reload VSCode to make it pick it up.

Hope that helps!

**Comment by ksmithut** [comment]
Ah, that was it. I did put a tsconfig in with that setting, but I’ve noticed other times that viscose doesn’t pick up changes to the tsconfig right away (or I have to full reload).
