### ISSUE TITLE
Documentation request: Why is `strict: true` required?

### ISSUE THREAD

**Issue by keenahn** [colinhacks/zod#769]
I'd love more details here, because `strict` mode is actually just a collection of a bunch of other flags. If you can point me to the relevant parts of the code base I'd be happy to submit a PR for the README :)

**Comment by scotttrinh** [comment]
Mostly it's related to how the compiler treats inferred types from the schemas. We could probably figure out which flag(s) are responsible. If you want to do a quick CodeSandbox experiment and submit an updated PR with a set of minimal flags, I'd be happy to review!

**Comment by JacobWeisenburger** [comment]
Did a PR get made for this?

**Comment by JacobWeisenburger** [comment]
I'm going to close this. Feel free to reopen it if need be.
