### ISSUE TITLE
Optional key

### ISSUE THREAD

**Issue by jasonkuhrt** [colinhacks/zod#774]
I'm working on a Zod schema for [Node package exports](https://nodejs.org/api/packages.html). Part of it looks like this:

```ts
export const ExportsCoreConditional = z.object({
  import: z.string().optional(),
  require: z.string().optional(),
  node: z.string().optional(),
  default: z.string().optional(),
})
```

The problem here is that the resulting type is e.g. `import?: string|undefined`. The actually correct type is `import?: string`. This is because a user will never be able to write `import: undefined` in their package.json file, since that is not valid JSON.

**Comment by jasonkuhrt** [comment]
So I tried this:

<img width="476" alt="CleanShot 2021-11-20 at 11 23 31@2x" src="https://user-images.githubusercontent.com/284476/142733636-d1679a45-a7ac-49ce-a8ba-3646bb72bc4f.png">


However TS still by default allows the `| undefined` possibility.

TS 4.4 has a solution to this however. I use this new compiler flag: https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes

And then it works:

<img width="469" alt="CleanShot 2021-11-20 at 11 25 47@2x" src="https://user-images.githubusercontent.com/284476/142733730-293747fa-73b7-43cc-831e-5220eade5582.png">

One problem this might have is that a consumer of my package might compile TS without this flag (likely will). If so, that seems like it will negate my package's effort to limit the possibility of `undefined` 😕 🤔 ?

**Comment by jasonkuhrt** [comment]
Hm, my solution does not work with `z.infer` it seems:

<img width="598" alt="CleanShot 2021-11-20 at 12 10 51@2x" src="https://user-images.githubusercontent.com/284476/142735123-81428cc7-89a3-4ab2-91ed-61477026d309.png">

**Comment by akomm** [comment]
I think its same issue as here: https://github.com/colinhacks/zod/issues/635

**Comment by jasonkuhrt** [comment]
Thanks @akomm yep looks like it.
