### ISSUE TITLE
ZodObject.merge: pick & omit Mask only infers added properties

### ISSUE THREAD

**Issue by akomm** [colinhacks/zod#775]
Zod: 3.11.6 (issue same also in 3.9.8 from which I'v updated)

```ts
const A = z.object({
  b: z.boolean(),
  x: z.number()
})
const B = A.merge(
  z.object({
    y: z.number()
  })
)

// resulting type correctly inferred: {b: boolean; x: number; y: number}
type C = z.TypeOf<typeof C>
const C = B.omit({}) // Mask only infers "y"

// resulting type correctly inferred: {b: boolean; x: number; y: number}
type D = z.TypeOf<typeof D>
const D = B.pick({}) // Mask only infers "y"

type E = z.TypeOf<typeof E>
// resulting type correctly inferred: {b: boolean}
const E = B.pick({b: true}) // Mask only infers "y"

type F = z.TypeOf<typeof F>
// resulting type correctly inferred: {x: number; y: number}
const F = B.omit({b: true}) // Mask only infers "y"
```

There is no type error passing the `right` properties from `ZodObject` that was the merge source.

Might be an issue with the order of instantiation of generics. The result is correctly mapped over the props and fails when wrong properties are passed to mask.

I'd rate this minor issue though, since it kind of works, just worser completion in IDE.

**Comment by JacobWeisenburger** [comment]
I think this answer should help. Let me know if you have any questions.
https://github.com/colinhacks/zod/issues/895#issuecomment-1026940911

**Comment by JacobWeisenburger** [comment]
Related to https://github.com/colinhacks/zod/issues/895. No PR yet that I can see.
