### ISSUE TITLE
Doc: The "required" property on z.string() doesn't exist, it should be the "required_error"

### ISSUE THREAD

**Issue by nemonemi** [colinhacks/zod#780]
In the String documentation there is this piece of code, however, these properties doesn't exist on the type for the string().
https://github.com/colinhacks/zod#strings
```ts
const name = z.string({
  required: "Name is required",
  invalid: "Invalid name",
});
```
The `required_error` and the `invalid_type_error` do exist, though.

**Comment by alveshelio** [comment]
Yeah, 

I think the doc needs to be updated. I'm facing some issues with `safeParse` too and I'm wondering if it's the docs that are not up to date or if I'm doing something wrong.

**Comment by JacobWeisenburger** [comment]
@nemonemi This issue has been fixed in the docs. https://github.com/colinhacks/zod#strings

Thanks for letting us about it.
