### ISSUE TITLE
schema.safeParse doesn't seem to have the appropriate signature.

### ISSUE THREAD

**Issue by alveshelio** [colinhacks/zod#782]
`zod`: `v3.11.6`
`TypeScript`: `v4.4.4`

I'm using `zod` to validate the body of my request. I expect to receive an email in the body.

Looking at the docs, I've created this:
```ts
const emailSchema = z.object({
      email: z.string().email(),
    })

    const result = emailSchema.safeParse({ email })
    if (!result.success) {
      res.status(400).json({ error: result.error.issues[0].message })
      return
    }
```

And according with the signature of `safeParse`, 
```ts
export declare type SafeParseSuccess<Output> = {
    success: true;
    data: Output;
};
export declare type SafeParseError<Input> = {
    success: false;
    error: ZodError<Input>;
};
export declare type SafeParseReturnType<Input, Output> = SafeParseSuccess<Output> | SafeParseError<Input>;
```
So it either returns a `SafeParseSuccess<Output>` if it validates successfully or `SafeParseError<Input>` if it fails.

However, when I try to return the message in the response, TypeScript get's mad, even though it returns the message
![image](https://user-images.githubusercontent.com/8176422/143164701-99aaffab-0476-4a2c-bb51-7941d5c5ec27.png)

I'm not sure what `safeParse` is supposed to to return. 

Any clarifications would be appreciated.

**Comment by karranb** [comment]
Hi @alveshelio, I had the same issue, I had to remove the line
```
     "strictNullChecks": false,
```
from my `tsconfig.json`,

**Comment by alveshelio** [comment]
Hi @karranb,

Thank you, however, I'm not sure it's a good thing to set `"strictNullChecks": false,` because this will have complications. If you set `"strictNullChecks": false,` then when you have this case
```ts
function trimAndLower(str: string) {
  return str.trim().toLowerCase()
}

const lowerTrimmedString = trimAndLower(null)
console.log(lowerTrimmedString)
```
 it will not complain on code analysis, it should plain that `null` isn't assignable to parameter `string`, and when you'll try to compile your code it will break, check here: 
https://www.typescriptlang.org/play?strictNullChecks=false&ssl=6&ssc=32&pln=1&pc=1#code/GYVwdgxgLglg9mABFATjAtgQTAEwDJwDuApigBQDOqAXIlWmAOYCUiA3gFCKIrFQgok9AHSoMZZqLgESKAMIBDCsQkcAvhw4QEVRABsipACpp06YjgDKYpogC8yU9nyHyYEHr3MtOuHuLCBoxkBrImGOZWNiyamgD0cYhGcPrECoKI6HC8iAoARnAgUMgAFsT6CkwgCozEADSIEHowEADWuQUAbuUwSABEAKIAHgroAA7+FH2I2Yh9AOolClAA5BSIAHLEhH3CHAmIAPJQZSiEMMoNtcVU6VAWiHkAnjzEWZ29jKXEyo1wZsQwFB1pUcN9EIRsnowRdEE9CihEBMFE9GChCrg9twgA

if you check tsconfig, `strictNullChecks` is set to false and you don't see any warning in the code, however if you change `strictNullChecks` to true then it will start complaining.

I'im sure there's a better way :)

**Comment by alveshelio** [comment]
Hi @karranb,

I had written a previous answer and I totally misread your answer :( really sorry. Your answer actually is the right way to go. Thank you
