### ISSUE TITLE
Guarantee on self-compatibility within minor versions?

### ISSUE THREAD

**Issue by CGamesPlay** [colinhacks/zod#785]
This issue is a bit nebulous; my apologies that I don't have anything specifically actionable to list here. Feel free to close if this sort of commentary is not welcome.

When a library exports zod schemas, sometimes the consumers of those libraries will extend those schemas in various ways. For example, consider the following:

```
import { z } as "zod";
import { DocumentSchema } from "library";

const CreateDocument = z.object({ data: DocumentSchema, publishNow: z.boolean() });
```

In this scenario, what version of zod is safe for the consumer to import? Naively, we would think that something that matches the same minor version would be sufficient--that is, if the library has zod `^3.11.2` then the consumer can as well. However, this is not the case. Consider that when library was published, `3.11.2` was the latest published version of zod. But today, `^3.11.2` resolves to `3.11.6`, and this code fails to compile (because `DocumentSchema` is missing properties `describe` and `description`).

There are a few solutions here.

1. Zod guarantees that the `.d.ts` files never change without a corresponding change in minor version. I think this is best, because it most closely matches semver. There may be additional considerations beyond the `.d.ts` files as well, I'm not totally sure.
2. Any package exporting a zod schema must provide a corresponding `peerDependencies` for zod. This is suboptimal, because consumers of the library who only want to use the schema (not extend it) are now required to manually list zod as a dependency.
3. Any package exporting a zod schema needs to pin a precise zod version and document that consumers extending the zod schema must use the identical zod version. This is suboptimal because it requires these consumers to read the documentation ahead of time, lest they encounter strange errors when they do the natural `yarn add zod` and attempt to use it.
4. ~~export zod from the library.~~ This is a non-solution because it requires that the library is the "one true zod", which means it doesn't play nicely with other libraries.

Apologies again for not having anything more substantial. Hopefully this issue sparks some useful discussion that can lead to a working solution.

**Comment by scotttrinh** [comment]
@CGamesPlay 

Thanks for bringing this up: it's a related to a very common pitfall with having Zod schemas across package boundaries. As you can appreciate as someone who has thought through this problem, I'm not sure we have a home-run conclusion for which way to encourage people to go. Since it's not really clear when the `.d.ts` file will change while cutting releases, I think the first solution, while best from a packaging perspective, might be too high friction for us maintainers. I think we absolutely should be a bit more careful when publishing versions to not break things in this way, but I'm unaware of anything automated that would help us here.

**Comment by CGamesPlay** [comment]
Respectfully, it is pretty clear to identify when the `.d.ts` files change: any modification to an exported type changes them. "Safe" changes are only those that are purely inside of internal files or function implementations. There may additionally be some cases where modifications to the `.d.ts` files are safe within a minor version, but these would be exceedingly rare (a new top-level method or class which does not reference any other Zod types).

If Zod were able to make this guarantee, then tilde version ranges would be safe in this context: both packages import `~3.11.2` and the change adding `describe` and `description` would have been released as `3.12.0`. Changes in major version are of course still be reserved for breaking backwards compatibility with consumers of Zod.

As far as reducing friction, a simple idea that comes to mind is to check the `.d.ts` files into git. If they change between versions, then we know that the new release should be a minor version.

**Comment by scotttrinh** [comment]
@CGamesPlay 

> Respectfully, it is pretty clear to identify when the .d.ts files change: any modification to an exported type changes them. "Safe" changes are only those that are purely inside of internal files or function implementations.

Yeah, that's a good point, and I think that you're right: we should endeavor to keep our public type interface as stable and semver-friendly as possible to avoid breakages in these public types. I'm not the one who cuts releases, so I definitely want @colinhacks 's input here, but having had this happen to me with the `record` type change (which at least bumped minor, I think?) it should be something we attempt to mitigate.

Thanks for brining this up!

**Comment by colinhacks** [comment]
The right way to handle this is peer dependencies — if a library directly relies on Zod it isn't an issue to require the user to install that alongside the package itself. This lets us rely on NPM's peerDependencies version ranging as well.
