### ISSUE TITLE
ZodObject with explicit type has an optional value can not be infered correctly after `omit` haven been called in Typescript.

### ISSUE THREAD

**Issue by xiaoyijun** [colinhacks/zod#787]
## Situation
When I define a custom ZodObjectType with explicit type, I found that this object can't not be infered correctly after `omit` haven been called in Typescript.

## Sample
```ts
import { z, ZodObject, ZodType } from "zod";

export type Guard<T extends Record<string, unknown>> = ZodObject<
  {
    [key in keyof T]: ZodType<T[key]>;
  }
>;

type User = {
    id: string,
    username: string,
    detail: string,
}

function testUser() {
    const userGuard: Guard<User> = z.object({
        id: z.string(),
        username: z.string(),
        detail: z.string(),
    });

    const omitUserGuard = userGuard.omit({ id: true, detail: true });

    console.log("Omit UserGuard Shape:")
    console.log(omitUserGuard.shape);
    console.log("----------------")
    console.log()
    console.log()

    console.log("Username from Omit UserGuard:")
    const { username } = omitUserGuard.parse({ username: 'Alex' });
    console.log(username)
    console.log("-----------------------")
}

type UserWithOptionalDetail = {
    id: string,
    username: string,
    detail?: string,
}

function testUserWithOptionalDetailGuard() {
    const userWithOptionalDetailGuard: Guard<UserWithOptionalDetail> = z.object({
        id: z.string(),
        username: z.string(),
        detail: z.string().optional()
    });

    const omitUserGuardWithOptionalDetail = userWithOptionalDetailGuard.omit({ id: true, detail: true })

    console.log("Omit UserWithOptionalDetailGuard Shape:")
    console.log(omitUserGuardWithOptionalDetail.shape)
    console.log("---------------------------------------");
    
    console.log()
    console.log()

    // this line of code will cause a problem: Property 'username' does not exist on type '{}'.
    const { username } = omitUserGuardWithOptionalDetail.parse({ username: 'Alex' })

    console.log("Username from Omit UserWithOptionalDetailGuard:")
    console.log(username)
    console.log("-----------------------------------------")
}

testUser()

console.log()
console.log()

testUserWithOptionalDetailGuard()
```
Both guards of the `User` and `UserWithOptionalDetail` type are correctly in console. but we can not build the typescript successfully.
![image](https://user-images.githubusercontent.com/10806653/143418511-0afe50fa-423c-4d09-aec8-490269fffe31.png)

Error message:
![image](https://user-images.githubusercontent.com/10806653/143417940-01228259-b9dd-4357-aa91-71e69ab3748e.png)

## Sample Code
you can reproduce the error by the source code below:
[typescript-playground.zip](https://github.com/colinhacks/zod/files/7601890/typescript-playground.zip)
```bash
npm i
sh ./run.sh
```

**Comment by scotttrinh** [comment]
@xiaoyijun 

Thanks for the detailed reproduction case here! Unfortunately, using Zod with explicit types like this isn't well supported in a lot of cases, and I don't think there is much buy-in from the maintainers here to prioritize supporting it. Having said that, I've personally found the Zod codebase to be understandable and if you have experience with type-level programming in TypeScript, we welcome these kinds of PRs!

Going to leave this open for now, but without someone stepping up to offer to tackle this, I don't have a lot of hope for it being addressed in the near future.

**Comment by xiaoyijun** [comment]
Thanks for your reply.
Currently I use normal zod object instead in case of the project I develop getting blocked.
Zod is an excellent project. Hope I'll have more spare time to research it more.

**Comment by xiaoyijun** [comment]
it seems we use this in a wrong way.
@simeng-li has resolved this problem in the pr above.
