### ISSUE TITLE
Schema only validating `.refine` when `object` passes.

### ISSUE THREAD

**Issue by ricardo-rp** [colinhacks/zod#788]
I'm using zod together with [react-hook-form](https://github.com/react-hook-form/react-hook-form) to create a user signup form. The schema is as follows: 
I am unsure as to whether this issue goes in [react-hook-form/resolvers](https://github.com/react-hook-form/resolvers) or here, so I am asking for support in both repos.

```
const schema = z
.object({
  name: z.string().nonempty('message'),
  email: z.string().nonempty('message').email('message'),
  password: edukPassword({ nonEmpty: 'message' }),
  confirmPassword: z.string(),
  cellphone: brazilianCellphoneNumber().nonempty('message'),
  privacyTermsAccepted: z.literal(true, {invalid_type_error: 'message',}),
})
.refine(({ password, confirmPassword }) => password === confirmPassword, {
  message: 'Passwords must match',
  path: ['confirmPassword'],
})

export const registerFormResolver = zodResolver(registerFormSchema)
```

The problem is, I am only getting an error on `.refine` when `.object` has passed. This results in the user not knowing they have entered an incorrect password confirmation until **after** they filled out the whole form.

Have I incorrectly built the schema for this useCase, or is the resolver incorrectly returning me formErrors?

**Comment by ricardo-rp** [comment]
I managed to find out that when I remove the `privacyTermsAccepted` field, the issue no longer happens.
Here's a codesandobx with the issue:

https://codesandbox.io/s/react-hook-form-zod-resolver-example-forked-2kl4w

**Comment by alveshelio** [comment]
I'm not exactly sure what's your problem. I've tested your codesandbox and when I enter the password and then the confirmation password and the field loses focus it displays the error message saying that the passwords must match
![image](https://user-images.githubusercontent.com/8176422/143505677-3cb88115-ca2f-46a8-80cb-699b40ee0abf.png)
As you can see the form isn't filled only password and confirmation are filled in.

By the way, you can change `mode: 'onBlur'` this helps for the performance, it will only run when a field loses focus.

**Comment by ricardo-rp** [comment]
@alveshelio 
![image](https://user-images.githubusercontent.com/30808767/143512495-3fbb8e14-0940-46e5-8564-74ee1c013b16.png)
Did you touch the checkbox before filling the inputs, or before the `delayError` of 1000ms kicked in? It seems it doesn't actually wait for the whole form to be dirty, but it does wait for the checkbox.
I ran the codesandbox both in brave browser and firefox to make sure it wasn't some browser-specific problem

**Comment by ricardo-rp** [comment]
I managed to solve it by replacing `.literal` with `.boolean` and using `.refine` to check wether the boolean is true. Here's a [fork](https://codesandbox.io/s/react-hook-form-zod-resolver-example-z-literal-issue-solution-b1vwx?file=/src/App.js) with the solution.
Still, it would be nice to know whether this is a bug or I was just improperly using `.literal`

**Comment by scotttrinh** [comment]
FWIW, Zod is intentionally designed to parse-first and then validate, so this is working as expected. Going to close, but there is definitely a need for a tool (or set of tools) that sit between Zod and common IO boundaries that can help with some of the boilerplate associated with things like form validation, and hopefully someone with some experience or need for this in the community will come forward with something there!
