### ISSUE TITLE
How to configure the z.date() method?

### ISSUE THREAD

**Issue by nemonemi** [colinhacks/zod#791]
I'd like to define different messages shown when this field is empty and when the value is incorrect, however, the documentation doesn't mention that this is possible, nor have any attempts of mine worked.

Is it possible to configure the `.date()` method, and if so, how?

**Comment by scotttrinh** [comment]
There is a newly added configuration option on most (all?) of the constructors that lets you define it:

```ts
z.date({
  invalid_type_error: "Next time, try a Date object.",
  required_error: "Please provide a Date.",
});
```

Documentation for a lot of the newest features is lagging: definitely an area we need to spend time improving!

**Comment by nemonemi** [comment]
For now, I've decided not to use schema validation, however, I remember I have attempted this exact approach, but it did nothing.
