### ISSUE TITLE
Safe Parse on a ZodFunction

### ISSUE THREAD

**Issue by JacobWeisenburger** [colinhacks/zod#802]
Is there a way to do safeParse with a ZodFunction? I would like to avoid throwing errors

``` ts
const unknownData = 'foo' // could be from user input, or api, or somewhere else
const doSomethingSchema = z.function()
    .args( z.literal( 'hello' ) )
    .returns( z.literal( 'hello world' ) )

const doSomething = doSomethingSchema.implement( x => `${x} world` )
doSomething( 'hello' ) // => 'hello world' // works
doSomething( unknownData ) // throws error

// maybe something like this
const safeDoSomething = doSomethingSchema.safeImplement( x => `${x} world` )
safeDoSomething( 'hello' ) // => SafeParseSuccess // works
safeDoSomething( unknownData ) // => SafeParseError // doesn't throw error
```

**Comment by yonkeltron** [comment]
Was this ever revisited? I'd love to see a `safeApply` method on `ZodFunction` but I don't know if I should open up another issue or not.

**Comment by Shuunen** [comment]
@yonkeltron same here

@JacobWeisenburger why did you closed this issue ?

I can't find any `safeImplement` or `safeApply`

**Comment by Violettica** [comment]
Since it's been two years and we still have no explanation as to why the issue was closed, can we reopen it? This feature sounds lovely.
