### ISSUE TITLE
Missing `types` field to `exports` in package.json

### ISSUE THREAD

**Issue by jakubmazanec** [colinhacks/zod#805]
`exports` field in package.json should look like this:
```JSON
"exports": {
    ".": {
      "require": "./lib/index.js",
      "import": "./lib/index.mjs",
      "types": "./lib/index.d.ts"
    },
    "./package.json": "./package.json"
  }
```
Otherwise TypeScript (v4.6.0-dev.20211201) errors: `Could not find a declaration file for module 'zod'. 'REDACTED/node_modules/zod/lib/index.mjs' implicitly has an 'any' type.`. Apparently, TS ignores the root `types` field.

Could this be fixed?

**Comment by scotttrinh** [comment]
Just leaving a quick note for ourselves here: here are the relevant docs from NodeJS about package.json entry points: https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#package-entry-points
