### ISSUE TITLE
Documentation for Custom Method

### ISSUE THREAD

**Issue by jjhiggz** [colinhacks/zod#812]
I noticed that a `z.custom` method exists and works in schema validation. I also could not find any documentation on this feature, despite that it was personally very useful for me. 

I'd love to contribute (please note this would be my first open-source contribution)

**Comment by scotttrinh** [comment]
@jjhiggz PRs welcome for documentation! Even something simple with a straightforward example is better than the big nothing we currently have!

**Comment by SagnikPradhan** [comment]
Yeah :+1: on this, `z.custom` is really helpful and should be documented.

**Comment by SagnikPradhan** [comment]
I will add it today I guess

**Comment by msheakoski** [comment]
This issue was prematurely closed. It is still a good idea to document `.custom`.
