### ISSUE TITLE
Add file type

### ISSUE THREAD

**Issue by jgradzki** [colinhacks/zod#814]
Hi, as stated in contributing documentation, Im creating this issue to propose implementing "ZodFile" type. 

I have already implemented this in my project (I had to overwrite some types etc), and I could make PR with this.
In my current implementation, I have checks for size(min/max) and mime type, I'm open to suggestions to add something more.

**Comment by JacobWeisenburger** [comment]
PRs are always welcome. Please explain more about this use case and provide some code examples show how it could be used. Is this something that would only work with node/deno or could this work for the browser too?

**Comment by andresgutgon** [comment]
I'm also interested in solving this issue 👍

**Comment by andresgutgon** [comment]
I would love an API like this for the `file` Zod type:

``` javascript
const avatar = z.file().type(["jpg", "png"]).size(1048576) // 1MB in bytes
```

I'm trying to do my own `ZodType` like `ZodString` is done for example.

But I'm not sure if there is another way. The way I'm trying looks super complex. Also Typescript is barking me all the time becasue `ZodType` only allow [core types](https://github.com/colinhacks/zod/blob/master/src/helpers/parseUtil.ts#L10-L31)

As far as I know a file to be validated need to stream their content in chunks so you can check if the size is not bigger than expected in `z.file().size(XXX)`. I was thinking that the input for this file would be an object with 3 keys:

``` javascript
const avatar = z.file().type(["jpg", "png"]).size(1048576) // 1MB in bytes

const result = await avatar.safeParseAsync({
  filestream: ReadableStream, // with this internally we create a NodeFIle
  filename: "my-avatar.jpg", // Necessary for creating the file
  mimeType: "image/jpg" // This is the data that is validated agains what developer wants.
})

The output would be a [File](https://developer.mozilla.org/en-US/docs/Web/API/File) (or NodeFile equivalent).
```

**Comment by jgradzki** [comment]
@andresgutgon I'm working on it now, I should make PR very soon. I made min/max instead of `size`, just like it is made in NumberType

**Comment by andresgutgon** [comment]
Very cool! But what would be the flow with this validation?

Should I have already the file created in my server in disk? And then check for `mimetype` and `size`?

What I was think was different `input` and `output` and inside the `FileType` the actual `file` is created and returned. 
This process would be always `async`.

I'm thinking in this because my use case is validate a request on a node server. 

1. I want to validate all my `fields` in the request
2. I want to validate all my `files` in the request.

With the approach in your PR I would need to process and create in disk all the files before running this parsing/validations right?

**Comment by andresgutgon** [comment]
Server validation for files are a big deal : )
I don't want to allow files of X type or more than Y Mb. @web-std/file is what [remix.run](https://remix.run) use under the hook. The export a `File` object as a global in the Node server https://github.com/remix-run/remix/blob/main/packages/remix-node/globals.ts#L49

Maybe is not easy to do fully compatible browser/server. Thanks for trying 💪

**Comment by jgradzki** [comment]
@andresgutgon [@web-std/file](https://github.com/web-std/io/tree/main/packages/file) added, but you will have to map request data to convert file stream to File i guess before passing for validation

**Comment by andresgutgon** [comment]
Ok cool

**Comment by jgradzki** [comment]
It's only dependencie and I'm thinking about another approach, I think i will change that you can pass constructor to file(), It's cleaner in overall i guess

I just realize that i forgot add documentation to README.

**Comment by jgradzki** [comment]
@andresgutgon I removed [@web-std/file](https://github.com/web-std/io/tree/main/packages/file) from dependencies. Node.js usage:

```js
import { File } from "@web-std/file";

z.file(File);
```
