### ISSUE TITLE
Which is the correct way to structure a zod scheme to represent a form?

### ISSUE THREAD

**Issue by StErMi** [colinhacks/zod#820]
Hi there,

maybe I'm using Zod in the incorrect way but I have two questions:

1) I need to represent a scheme where a field is a string and it's `required`. Required means that it's not null, not undefined, and must be at least 1 character length. As far as I see I need to declare the field with both `required_error` and `min(1)` to make it work because the default value of that field is `undefined` (that default value comes from backend)

```
const schema = z
        .object({
          name: z
            .string({
              required_error: "The name field is required",
            })
            .min(1, "The name field is required"),
        })
```

Is there a way to express that with only 1 rule?

2) The second problem is that I would like to use the scheme to validate fields in the scheme without filtering others. It seems that Zod (when used with `react-hook-form`) removes fields that are not included inside the schema validation.

How can I do that?

**Comment by colinhacks** [comment]
1. This is the best way. As far as Zod is concerned, these are two different kinds of errors.
2. Use `.passthrough`: https://github.com/colinhacks/zod#passthrough

**Comment by StErMi** [comment]
> 1. This is the best way. As far as Zod is concerned, these are two different kinds of errors.
> 2. Use `.passthrough`: [colinhacks/zod#passthrough](https://github.com/colinhacks/zod#passthrough)

Thanks for the answer @colinhacks. Do you have an example of `passthrough`. As far as I can see it's not something you can use when you define the schema.

Is this something that I should use on the https://github.com/react-hook-form/resolvers side?

**Comment by scotttrinh** [comment]
@StErMi 

`passthrough` just returns another schema. Here's one approach from the react-hook-form docs example:

```ts
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';

const schema = z.object({
  name: z.string().nonempty({ message: 'Required' }),
  age: z.number().min(10),
}).passthrough();

const App = () => {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(schema),
  });

  return (
    <form onSubmit={handleSubmit((d) => console.log(d))}>
      <input {...register('name')} />
      {errors.name?.message && <p>{errors.name?.message}</p>}
      <input type="number" {...register('age', { valueAsNumber: true })} />
      {errors.age?.message && <p>{errors.age?.message}</p>}
      <input type="submit" />
    </form>
  );
};
```

Or if you want to keep the original schema to have the default behavior, you can just pass a modified schema like this:

```ts
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';

const schema = z.object({
  name: z.string().nonempty({ message: 'Required' }),
  age: z.number().min(10),
});

const App = () => {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(schema.passthrough()),
  });

  return (
    <form onSubmit={handleSubmit((d) => console.log(d))}>
      <input {...register('name')} />
      {errors.name?.message && <p>{errors.name?.message}</p>}
      <input type="number" {...register('age', { valueAsNumber: true })} />
      {errors.age?.message && <p>{errors.age?.message}</p>}
      <input type="submit" />
    </form>
  );
};
```
