### ISSUE TITLE
Mapping readonly array to Zod union  

### ISSUE THREAD

**Issue by cefn** [colinhacks/zod#831]
Hi and thanks for Zod. It's been a joy to use. 

Being able to use the following would be even nicer, but it fails for a variety of hard-to-fix reasons...

```typescript
const items = ["a","b","c"] as const;
const unionSchema = z.union((items.map((item) => z.literal(item)));
```

I often use an `as const` array or object to simultaneously define types (guiding the compiler) AND sequences (used at runtime). 

For example in the toy case below, the `PRIORITIES` list defines the type of a `Priority` string, and can also be iterated to construct a dropdown menu for example. This is a common emerging pattern in typescript codebases. It can ensure that variants are defined once, and that none are missed in mapped types either at compile-time or runtime.

Defining a zod schema from an `as const` array hits a dead end for me. Perhaps it's impossible. Perhaps I am missing how to do this properly. If it's this hard, some kind of utility type could be needed.

# Problems

There are an interlocking set of problems...
* Zod not accepting `Readonly` definitions meaning the use of `as const` causes arguments to be rejected.
* the required arity of a union (at least two) meaning arrays of unknown length are not accepted - normally resolved by using readonly arrays with a known length
* a [weakness of typescript](https://github.com/microsoft/TypeScript/issues/44309), which can't keep the tuple nature when using e.g. map() 

# Solution: Utility Function

If a utility function was provided, I imagine overloaded signatures as follows...

```typescript
type ZodLiteralTuple<T extends readonly Primitive[]> = {
  readonly [K in keyof T]: ZodLiteral<T[K]>;
};

function createUnionSchema<T extends readonly []>(values: T): ZodNever;
function createUnionSchema<T extends readonly [Primitive]>(
  values: T
): ZodLiteral<T[0]>;
function createUnionSchema<
  T extends readonly [Primitive, Primitive, ...Primitive[]]
>(values: T): z.ZodUnion<ZodLiteralTuple<T>>;
```

Here, ZodLiteralTuple is a type to use as a type assertion after `Array.map`. It preserves tuple arity and projects each concrete literal found in T into a corresponding ZodUnionOptions datastructure. 

![image](https://user-images.githubusercontent.com/159819/146686024-e853dbc6-be11-4426-8f1b-6577b4ec9fcf.png)

## CASES 

* `createUnionSchema([])` should resolve to `z.never()`
* `createUnionSchema(["single"])` should return `z.literal("single")`
* `createUnionSchema(["first","second"])` should return `z.union([z.literal("first"), z.literal("second")])`
* `createUnionSchema(["first","second","third"])` should return `z.union([z.literal("first"), z.literal("second"), , z.literal("third")])`

# Solution: Adding Readonly

Allowing the Readonly signature for arrays passed into all Zod functions would address one element of the issue. I can raise this as a PR.

# Reference Example

The toy example below is based on an experimental todo example. Here, keys for an index are a tuple,: task priority first, task due date second. Endpoint arguments will eventually need to validate the keys passed when paging the index, so we would like to have a schema for priority (a union of priorities), and compose it with a schema for date.

Each attempt hits some limitation, shown as a compiler error.

# FIRST ATTEMPT - DERIVE FROM as const TUPLE OF STRINGS

Here, because of a weakness preserving tuple nature, PRIORITY_SCHEMAS has an unknown length, so fails the union arity check.

```typescript
import { z } from "zod";

type Priority = typeof PRIORITIES[number];

const PRIORITIES = ["urgent", "soon", "normal", "backlog", "wishlist"] as const;

const DATE_SCHEMA = z.number();

/** Compiler error due to arity:
Argument of type 'ZodLiteral<"urgent" | "soon" | "normal" | "backlog" | "wishlist">[]' is not assignable to parameter of type '[ZodTypeAny, ZodTypeAny, ...ZodTypeAny[]]
*/
const PRIORITY_SCHEMAS = z.union(PRIORITIES.map((priority) => z.literal(priority)))

const KEY_SCHEMA = z.tuple([PRIORITY_SCHEMAS, DATE_SCHEMA])
```

# SECOND ATTEMPT - DERIVE FROM  TUPLE OF SCHEMAS

Here, because of `z.union()` only accepting writeable arrays, it rejects a tuple defined with as const (`as const` ensures its length is known).

```typescript
import { z } from "zod";

type Priority = typeof PRIORITIES[number];

const PRIORITY_SCHEMAS = [
  z.literal("urgent"),
  z.literal("soon"),
  z.literal("normal"),
  z.literal("backlog"),
  z.literal("wishlist"),
] as const;

const PRIORITIES = PRIORITY_SCHEMAS.map((schema) => schema.value);

const DATE_SCHEMA = z.number();

/** Compiler error:  The type 'readonly [ZodLiteral<"urgent">, ZodLiteral<"soon">, ZodLiteral<"normal">, ZodLiteral<"backlog">, ZodLiteral<"wishlist">]' is 'readonly' and cannot be assigned to the mutable type '[ZodTypeAny, ZodTypeAny, ...ZodTypeAny[]]' */
const PRIORITY_SCHEMA = z.union(PRIORITY_SCHEMAS);

const KEY_SCHEMA = z.tuple([PRIORITY_SCHEMA, DATE_SCHEMA]);
```

**Comment by cefn** [comment]
I drafted an attempt at a generic literal union (allowing zero, one, or many) as drafted inline below, with some examples at the bottom. I'm sharing but there remains one problem and I don't know if it's fixable. I hypothesise it's do to with needing readonly for arity, but needing read/write for the current `z.union()` signature (possibly fixed by https://github.com/colinhacks/zod/pull/832)

I was defeated when my `ZodLiteralTuple` type was not accepted as a `[ZodTypeAny, ZodTypeAny, ...ZodTypeAny[]]` even when the arity of it's base literal array was provably `[Primitive, Primitive, ...Primitive[]]`. Hence I had to broaden the type to [ZodTypeAny, ZodTypeAny, ...ZodTypeAny[]] to get it to compile, and the inferred schemas are incorrect when a union is needed. They are correct for empty and for singleton...

```typescript
import {
  Primitive,
  z,
  ZodLiteral,
  ZodNever,
  ZodSchema,
  ZodTypeAny,
  ZodUnion,
} from "zod";

export type Optional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;

export type Immutable<T> = T extends (...args: any[]) => any
  ? T
  : T extends object
  ? ImmutableIndex<T>
  : T;

/** Recursive Readonly implementation for any (indexable) [[RootState]] such as
 * an array or object */
type ImmutableIndex<T> = Readonly<{
  [K in keyof T]: Immutable<T[K]>;
}>;

export type ValueOf<T extends {} | any[]> = T[keyof T];

type ZodLiteralTuple<T extends readonly Primitive[]> = {
  -readonly [K in keyof T]: ZodLiteral<T[K]>;
};

function mapZodLiterals<T extends readonly Primitive[]>(
  items: T
): ZodLiteralTuple<T> {
  return items.map((item) => z.literal(item)) as unknown as ZodLiteralTuple<T>;
}

function createUnionSchema<T extends readonly []>(values: T): ZodNever;
function createUnionSchema<T extends readonly [Primitive]>(
  values: T
): ZodLiteral<T[0]>;
function createUnionSchema<
  T extends readonly [Primitive, Primitive, ...Primitive[]]
>(values: T): z.ZodUnion<[z.ZodTypeAny, z.ZodTypeAny, ...z.ZodTypeAny[]]>;
function createUnionSchema<T extends readonly Primitive[]>(values: T) {
  if (values.length === 0) {
    return z.never();
  } else if (values.length === 1) {
    return z.literal(values[0]);
  } else if (values.length > 1) {
    const alternates = mapZodLiterals(values) as unknown as [
      ZodTypeAny,
      ZodTypeAny,
      ...ZodTypeAny[]
    ];
    const union = z.union(alternates);
    return union;
  }
  throw new Error("Array must have a length");
}

// EXAMPLES

const unionEmpty = createUnionSchema([]);
const unionSingle = createUnionSchema(["a"] as const);
const unionMore = createUnionSchema(["a", "b"] as const);

type Empty = z.infer<typeof unionEmpty>;
type Single = z.infer<typeof unionSingle>;
type More = z.infer<typeof unionMore>;

```

**Comment by cefn** [comment]
For contrast this is the code which I thought SHOULD work for this case but doesn't owing to union not accepting ZodLiteralTuple the two compiler errors reveal how the type expectations for ZodUnion and z.union prevent the code from working...

```typescript
import { Primitive, z, ZodLiteral, ZodNever } from "zod";

export type Optional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;

export type Immutable<T> = T extends (...args: any[]) => any
  ? T
  : T extends object
  ? ImmutableIndex<T>
  : T;

/** Recursive Readonly implementation for any (indexable) [[RootState]] such as
 * an array or object */
type ImmutableIndex<T> = Readonly<{
  [K in keyof T]: Immutable<T[K]>;
}>;

export type ValueOf<T extends {} | any[]> = T[keyof T];

type ZodLiteralTuple<T extends readonly Primitive[]> = {
  -readonly [K in keyof T]: ZodLiteral<T[K]>;
};

function mapZodLiterals<T extends readonly Primitive[]>(
  items: T
): ZodLiteralTuple<T> {
  return items.map((item) => z.literal(item)) as unknown as ZodLiteralTuple<T>;
}

function isTwoOrMore<T extends Primitive>(
  values: readonly T[]
): values is readonly [T, T, ...T[]] {
  return values.length > 1;
}

function createUnionSchema<T extends readonly []>(values: T): ZodNever;
function createUnionSchema<T extends readonly [Primitive]>(
  values: T
): ZodLiteral<T[0]>;
function createUnionSchema<
  T extends readonly [Primitive, Primitive, ...Primitive[]]
>(values: T): z.ZodUnion<ZodLiteralTuple<T>>;
function createUnionSchema<T extends readonly Primitive[]>(values: T) {
  if (values.length === 0) {
    return z.never();
  } else if (values.length === 1) {
    return z.literal(values[0]);
  } else if (isTwoOrMore(values)) {
    const union = z.union(mapZodLiterals(values));
    return union;
  }
  throw new Error("Array must have a length");
}

const unionEmpty = createUnionSchema([]);
const unionSingle = createUnionSchema(["a"] as const);
const unionMore = createUnionSchema(["a", "b"] as const);

type Empty = z.infer<typeof unionEmpty>;
type Single = z.infer<typeof unionSingle>;
type More = z.infer<typeof unionMore>;
```

**Comment by cefn** [comment]
So I have a working example of a union with overloads for empty, singleton and many against the unmodified zod. It removes the readonly flag from the MappedType so it's compatible with the writeable array declarations, although I think readonly is a better definition for the future it is less of a blocker for me, now.

```typescript
import { Primitive, z, ZodLiteral, ZodNever } from "zod";

type MappedZodLiterals<T extends readonly Primitive[]> = {
  -readonly [K in keyof T]: ZodLiteral<T[K]>;
};

function createManyUnion<
  A extends Readonly<[Primitive, Primitive, ...Primitive[]]>
>(literals: A) {
  return z.union(
    literals.map((value) => z.literal(value)) as MappedZodLiterals<A>
  );
}

function createUnionSchema<T extends readonly []>(values: T): ZodNever;
function createUnionSchema<T extends readonly [Primitive]>(
  values: T
): ZodLiteral<T[0]>;
function createUnionSchema<
  T extends readonly [Primitive, Primitive, ...Primitive[]]
>(values: T): z.ZodUnion<MappedZodLiterals<T>>;
function createUnionSchema<T extends readonly Primitive[]>(values: T) {
  if (values.length > 1) {
    return createManyUnion(
      values as typeof values & [Primitive, Primitive, ...Primitive[]]
    );
  } else if (values.length === 1) {
    return z.literal(values[0]);
  } else if (values.length === 0) {
    return z.never();
  }
  throw new Error("Array must have a length");
}

// EXAMPLES

const emptySchema = createUnionSchema([] as const);
const singletonSchema = createUnionSchema(["a"] as const);
const manySchema = createUnionSchema(["a", "b", "c"] as const);

type EmptyType = z.infer<typeof emptySchema>;
type SingletonType = z.infer<typeof singletonSchema>;
type ManyType = z.infer<typeof manySchema>;

```

**Comment by cefn** [comment]
Note I found that `z.enum()` directly fulfils this pattern for non-empty arrays of strings, which is my most common case, but I had passed over it, believing that related to Typescript enums (those are actually handled by `z.nativeEnum()`. 

So `z.enum()` can handle `["a"] as const`, `["a","b"] as const and so on.

It can't handle `[] as const` like the above implementation
It can't handle `[3,4,5] as const` like the above implementation can.
It can't handle `[3,true,"hello"] as const` like the above implementation can.

**Comment by Aaronius** [comment]
Thank you for asking this question and sharing your work! I was looking for exactly this and your solution saved me a bunch of time. I do think there is an opportunity for Zod to make this simpler.

**Comment by cefn** [comment]
Thanks, @Aaronius . 

If you want zod to handle arbitrary unions of literals from a const array (not just strings) , @colinhacks [considers](https://github.com/colinhacks/zod/pull/832#issuecomment-1002792950) there isn't much appetite/need for it. So visitors to the issue should maybe thumbs up this comment or comment below if you have const literal union use cases you think are important (other than const string arrays >= length 2 which are already supported).

For example, the above implementation of `createUnionSchema` can handle all of the cases below, but only the `manyStringsSchema` case is already supported by `z.enum()`

```typescript
const manyStringsSchema = createUnionSchema(["a", "b", "c"] as const);

const emptySchema = createUnionSchema([] as const);
const singletonSchema = createUnionSchema(["a"] as const);
const mixedSchema = createUnionSchema([3, "hello", true] as const);
const numericalSchema = createUnionSchema([3, 4, 5] as const);


type EmptyType = z.infer<typeof emptySchema>;
type SingletonType = z.infer<typeof singletonSchema>;
type ManyStringsType = z.infer<typeof manyStringsSchema>;
//...
```

**Comment by Aaronius** [comment]
My scenario is I have a list of "exemption payee codes" (from a United States W-9 form), which can be one of 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, or 13. Depending on the "tax classification", only certain exemption payee codes are valid. So, I'd like to be able to do something this:

```js
const exemptPayeeCode = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13] as const;

// Variants based on tax classification:
const individualExemptPayeeCodes: readonly ExemptPayeeCode[] = [1, 2, 3, 4, 6, 7, 11, 12] as const;
const llcExemptPayeeCodes: readonly ExemptPayeeCode[] = [1, 2, 3, 4, 6, 7, 11, 12] as const;
const cCorpExemptPayeeCodes: readonly ExemptPayeeCode[] = [1, 2, 3, 4, 5, 6, 7, 9, 11, 12] as const;
const sCorpExemptPayeeCodes: readonly ExemptPayeeCode[] = [1, 2, 3, 4, 5, 6, 7, 9, 11, 12] as const;
const partnershipExemptPayeeCodes: readonly ExemptPayeeCode[] = [1, 2, 3, 4, 6, 7, 11, 12] as const;
const trustEstateExemptPayeeCodes: readonly ExemptPayeeCode[] = [
  1, 2, 3, 4, 6, 7, 8, 10, 11, 12, 13,
] as const;
const otherExemptPayeeCodes: readonly ExemptPayeeCode[] = [
  1, 2, 3, 4, 6, 7, 8, 10, 11, 12, 13,
] as const;
```

And build validators for each of the variants. Right now, with Zod only, it's a bit of a pain.

Your solution gets me closer, but I have to make adaptations because if I do something like this:

```
createUnionSchema(individualExemptPayeeCodes)
```

TypeScript complains:

![image](https://user-images.githubusercontent.com/210820/156032917-775e38e9-2f50-40d1-9567-89d970b5cf04.png)

If I take off the `readonly ExemptPayeeCode[]` type from my constant arrays, it works, but I'd rather not because I want to ensure I'm not fat-fingering one of the payee codes in my array.

**Comment by cefn** [comment]
I can see how you want to ensure the validation of `individualExemptPayeeCodes` without affecting the type. Your requirement is colliding with weakness of Typescript itself, which might have been resolved with the [`satisfies`](https://github.com/microsoft/TypeScript/issues/47834) operator. However, currently looks like the type of `satisfies` that we both need might be being supplanted by a distinct feature request - [to inline type declarations](https://github.com/microsoft/TypeScript/issues/47920 )) in which satisfies does the opposite. 

I am trying to make the case for satisfies to be type-transparent [here](https://github.com/microsoft/TypeScript/issues/47920#issuecomment-1042423939) and [here](https://github.com/microsoft/TypeScript/issues/47920#issuecomment-1042728706)

For now I think you have to avoid broadening the type. A workaround (with some inelegant runtime consequences) is a block-scoped const declaration to artificially create compiler errors like...

```typescript
const individualExemptPayeeCodes = [1, 2, 3, 4, 6, 7, 11, 12] as const;
{
const checkIndividualExemptPayeeCodes: readonly ExemptPayeeCode[] = individualExemptPayeeCodes;
}
``` 

Another pattern with runtime consequences that I've seen as a workaround is something like...

```
function validatePayeeCodes<T extends ReadonlyArray<PayeeCodes>>(list:T): T{
  return list
}
const individualExemptPayeeCodes = validatePayeeCodes([1, 2, 3, 4, 6, 7, 11, 12] as const);
```

**Comment by cefn** [comment]
Actually looks from  [https://github.com/microsoft/TypeScript/issues/47920#issuecomment-1054480996 ](this comment) that the debate is maybe going in our favour!

That would mean in a future Typescript release you can do...

```typescript
const individualExemptPayeeCodes = [1, 2, 3, 4, 6, 7, 11, 12] as const satisfies readonly ExemptPayeeCode[]
```

**Comment by Aaronius** [comment]
That would be great! Thanks for this information. I figured it was more of a TS issue than a Zod one, but wasn't sure if Zod would be able to make it easier to deal with. Your information make sense though. I was basically doing `const checkIndividualExemptPayeeCodes: readonly ExemptPayeeCode[] = individualExemptPayeeCodes;`, so I'll stick with that or your other option until `satisfies` becomes a thing. You've been very helpful. Thank you.

**Comment by Aaronius** [comment]
@cefn What do you think about re-opening this issue (or I can create a new one) as a feature request for supporting this mapping of readonly array to Zod unions out-of-the-box. I'm finding myself using your solution quite frequently.

**Comment by cefn** [comment]
Certainly support it being added and the code I wrote is free for all. Makes sense to be led by actual demand but I am biased because **_I_** use it, but who knows how widely useful it is.

Good idea to create a new clean issue where this can be decided. 

A new issue could link issue to the reference implementation above, but state the feature more clearly/tersely - extending `z.enum()`  to allow arbitrary lengths (including 0 and 1) and arbitrary primitive member types, (including mixed primitive tuples).

**Comment by Aaronius** [comment]
I was having issues with your solution, @cefn. If I call it like this, for example:

```
createUnionSchema(
  countries.map((country) => country.value)
)
```

I'm getting this TS error:

```
  Overload 1 of 3, '(values: readonly []): ZodNever', gave the following error.
    Argument of type 'readonly ["A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M", ...("A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M")[]]' is not assignable to parameter of type 'readonly []'.
      Source has 1 element(s) but target allows only 0.
  Overload 2 of 3, '(values: readonly [Primitive]): ZodLiteral<Primitive>', gave the following error.
    Argument of type 'readonly ["A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M", ...("A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M")[]]' is not assignable to parameter of type 'readonly [Primitive]'.
      Target allows only 1 element(s) but source may have more.
  Overload 3 of 3, '(values: readonly [Primitive, Primitive, ...Primitive[]]): ZodUnion<[ZodLiteral<Primitive>, ZodLiteral<Primitive>, ...ZodLiteral<...>[]]>', gave the following error.
    Argument of type 'readonly ["A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M", ...("A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M")[]]' is not assignable to parameter of type 'readonly [Primitive, Primitive, ...Primitive[]]'.
      Source provides no match for required element at position 1 in target.
```

Maybe I'm misunderstanding the intended usage?

Anyway, I modified it for my needs. I'm sure there are reasons why it's inferior to your example. I'm adding it here in case it's helpful to anyone else. I'd love to hear if it's a poor solution or if there's a better way to use @cefn's solution.

```ts
import { Primitive, z, ZodLiteral } from "zod";

const createUnion = <
  T extends Readonly<[Primitive, Primitive, ...Primitive[]]>
>(
  values: T
) => {
  const zodLiterals = values.map((value) => z.literal(value)) as unknown as [
    ZodLiteral<Primitive>,
    ZodLiteral<Primitive>,
    ...ZodLiteral<Primitive>[]
  ];
  return z.union(zodLiterals);
};

function createUnionSchema<T extends readonly Primitive[]>(
  values: T
) {
  if (values.length === 0) {
    return z.never();
  }

  if (values.length === 1) {
    return z.literal(values[0]);
  }

  return createUnion(
    values as unknown as Readonly<[Primitive, Primitive, ...Primitive[]]>
  );
}

export default createUnionSchema;

```

**Comment by cefn** [comment]
I'll try to share what I can. 

In your most recent case you are hitting another weakness of typescript, I'm afraid. Take the below example...

```typescript
const countries = [{name:"United Kingdom", value:70000000}, {name:"France", value:50000000}, {name:"Holland", value:20000000}] as const;
const countryValues = countries.map((country) => country.value); // typescript fumbles this to (70000000 | 50000000 | 20000000)[]
const betterCountryValues = countryValues as [number, number, ...number[]]
const actualCountryValues = countryValues as [70000000, 50000000, 20000000]
```

In my view the type of `countryValues` should immediately be `[70000000, 50000000, 20000000]` but unfortunately it is not as you can see from hovering over [this playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBKCuYoCcCWBTCMC8MDaA3mAIYC26AXAEQCqYqU6AJjANKpgDmTIpVANDABuxADbxKAdgAMsudIC+gomUpUAYsmJhg6AcLESKAVnlylMFeWoAJEKNHam+keMoAmM7IUBdGMSxQSCgAbgAoIOg4EEQUAE8ANUNMHGjYtEwAOlJiAAcACnyEJGQ4gEocAD40krjM1wkykJgAehaYKDjczGA0XNgAM3hSACNRFKgAC1QICPAokfQoRmQAYRjapLcsXGL4rYksAPwwYcXkQVPR9AuYTPur87wfHzng-2AoeDF19MTknY1fYA-xYPAyLyCUyQmCeLw+IA) 

Typescript fumbles `countryValues` to be `(70000000 | 50000000 | 20000000)[]` when it should be `[70000000, 50000000, 20000000]` effectively throwing away all length and member information.

So an implementation that handles tuples doesn't have enough information to judge that it is either a length 0 tuple, or a length 1 tuple, or a length >=2 tuple. This is not a problem for const literal arrays, but it emerges from this typescript bug when you use a map function.

The easiest workaround is to fix up the type of `countryValues` directly to workaround for the typescript bug, and pass a more accurate type into my original implementation. For example this pseudocode (untested)...

```typescript
createUnionSchema(
  countries.map((country) => country.value) as [number, number, ...number[]]
)
```

...or if you like to code defensively...

```typescript
if(countries.length < 2){
  throw new Error(`Array ${countries} is of length ${countries.length} and cannot be used to define a literal union`)
}
type Value = typeof countries[number]["value"]
createUnionSchema(
  countries.map((country) => country.value) as [Value,Value, ...Value[]]
)
```

By contrast your implementation takes no notice of the type passed, eliminates all type checking and broadens anything you pass to `[Primitive, Primitive, ...Primitive[]]` regardless what it actually is (including if this creates a hidden runtime bug, since it's something else). This also destroys any potential for later inference that reflects the actual item passed in. For example `z.infer<typeof MySchema>` will end up being `Primitive` even when the original literal array used to create `MySchema` was `[true, false]` so therefore it should be narrowed to `true | false`. So following your approach the actual typing information from the original tuple is thrown away. You also rely on good luck that your forceful cast to `[Primitive, Primitive, ...Primitive[]]` doesn't create runtime errors which works for all the cases until it doesn't.

**Comment by Aaronius** [comment]
That makes a lot of sense.  I've learned a lot through your descriptions and your solution. Thank you for taking the time to explain everything so in depth.

**Comment by louwers** [comment]
Can these utilities be included with zod?

**Comment by cefn** [comment]
So far the answer from @colinhacks was no, as he feels it's a niche use. In my view it would be a replacement to extend enum (as it handles a superset of cases), but I'm not sure there's the appetite for it in zod right now.

> I don't think it's worth introducing something akin to createUnionSchema into core...creating unions of non-string primitive literals is pretty obscure use case IMO.
https://github.com/colinhacks/zod/pull/832#issuecomment-1002792950

( @Aaronius you might be entertained to know that your tax code example was central to my Medium article on a new Typescript feature... https://medium.com/@cefn/typescript-satisfies-6ba52e74cb2f )

**Comment by tiavina-mika** [comment]
> ```ts
> type MappedZodLiterals<T extends readonly Primitive[]> = {
>   -readonly [K in keyof T]: ZodLiteral<T[K]>;
> };
> ```

It's working if using directly an array:
```
createManyUnion(['page', 'blog'] as const)
```

but using map it's not working with
```
createManyUnion(options.map(option => option.value) as [string, string, ...string[]]);
```

Here is the code: [codesandbox](https://codesandbox.io/s/exciting-fermat-xqoehg)

**Comment by cefn** [comment]
Hi, tiavina-mika. The repro is really useful to understand what you are seeing!

You are facing two problems, none of which relate to the implementation of `createManyUnion()`

First of all, your use of `as` blasts away any potential for _inferring_ the type because you have _assigned_ a type. An expression only has one type. If you want an inferred type of options.map(option => option.value) to be `"page" | "blog"` this is inconsistent with using `as` (and therefore setting it to something else).  If you were to use `as` and align with your expectations your `options` would have to be declared `as const` and then you can write e.g. `const array = options.map((option): string => option.value) as unknown as ReadonlyArray<typeof options[number]["value"]> & [string, string, ...string[]] ;` . Equally `as ("page" | "blog")` would fix your problem. Having to explicitly duplicate that information is due to the second problem.

Second of all, Typescript's support for Array#map is totally crap. It doesn't even preserve arity even though the length of a mapped array is (by definition) the length of the original. It is incapable about reasoning about positional transforms (e.g. array position 0 will get mapped to X). 

So when either your own code (with as) or Typescript's own crapness assigns a type with only strings, nothing in `createManyUnion()` can possibly infer the original information. It's been thrown away. 

It's worth trying to decompose the stages of a complex sequence like this, to try and understand where the problem lies. You can inspect the type of an expression by using typeof. So looking at your case, and without `as` you get the following which makes it obvious that the type information has been lost even before you passed it to `createManyUnion()`...
![image](https://user-images.githubusercontent.com/159819/213661044-dc8d3e75-02db-41d0-989b-81590d67d708.png)

If it were me, I would probably use a const array to define all my values and then use typing to align other record structures, something like https://tsplay.dev/WylRdm ...

```
const VALUES = ["page", "blog"] as const;
```

**Comment by cefn** [comment]
Narrowing in on the problem of arity only, there is a somewhat elegant approach which gets as much done with inference as possible, but without refactoring much of your original code. I've shared it at https://tsplay.dev/N5OlZW 

It relies on you declaring your data structures with `as const` , and then 'augments' the inferred type with the correct arity using `& [string,string,...string[]]`. I had missed that you had also 'blasted away' the inferred type from the map function with an explicit `:string` declaration.

![image](https://user-images.githubusercontent.com/159819/213677928-900dee64-0b30-4f25-acf8-d079f021f845.png)

**Comment by audunolsen** [comment]
Came up with this myself. Works very well

```typescript

/**
 * Zod Helper for creating a tuple of literals. This is otherwise very verbose
 * because each array entry need to wrapped in `z.literal` call
 */
function createZodLiterals<const Literals extends ReadonlyArray<z.Primitive>>(
  ...literals: Literals
): { [Index in keyof Literals]: z.ZodLiteral<Literals[Index]> };

function createZodLiterals<const Literals extends ReadonlyArray<z.Primitive>>(
  ...literals: Literals
) {
  return literals.map((e) => z.literal(e));
}

export { createZodLiterals };

```

Uses an overload that returns a mapped array type to loosen TS a little as `map` will never return a tuple.

Usage:
```typescript
const foods = createZodLiterals('fish', 'broccoli');
const foodSchema = z.record(z.union(fields), z.boolean());

type FoodSchema = z.output<typeof foodSchema>
//         ^? type FoodSchema = { fish?: boolean | undefined, broccoli?: boolean | undefined }
```

Would be nice to have something like this already baked in the library. e.g. `z.literals`

**Comment by lorenzodejong** [comment]
Maybe a bit late to the party. But after reading through this issue thread i eventually decided upon a solution using type guards, which ensures it's covered both on type-level and on the actual runtime of the code.

```typescript
import { z } from 'zod';
​
export function isValidZodLiteralUnion<T extends z.ZodLiteral<unknown>>(
  literals: T[]
): literals is [T, T, ...T[]] {
  return literals.length >= 2;
}
​
export function constructZodLiteralUnionType<T extends z.ZodLiteral<unknown>>(
  literals: T[]
) {
  if (!isValidZodLiteralUnion(literals)) {
    throw new Error(
      'Literals passed do not meet the criteria for constructing a union schema, the minimum length is 2'
    );
  }
​
  return z.union(literals);
}
​
// Example:
const literalValues = ['a', 'b', 'c'] as const;
​
// ERROR: Argument of type 'ZodLiteral<"a" | "b" | "c">[]' is not assignable
// to parameter of type 'readonly [ZodTypeAny, ZodTypeAny, ...ZodTypeAny[]]'
z.union(literalValues.map((literal) => z.literal(literal)));
​
// Valid!
constructZodLiteralUnionType(
  literalValues.map((literal) => z.literal(literal))
);
```

**Comment by bacharSalleh** [comment]
> Maybe a bit late to the party. But after reading through this issue thread i eventually decided upon a solution using [type guards](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates), which ensures it's covered both on type-level and on the actual runtime of the code.
> 
> ```ts
> import { z } from 'zod';
> ​
> export function isValidZodLiteralUnion<T extends z.ZodLiteral<unknown>>(
>   literals: T[]
> ): literals is [T, T, ...T[]] {
>   return literals.length >= 2;
> }
> ​
> export function constructZodLiteralUnionType<T extends z.ZodLiteral<unknown>>(
>   literals: T[]
> ) {
>   if (!isValidZodLiteralUnion(literals)) {
>     throw new Error(
>       'Literals passed do not meet the criteria for constructing a union schema, the minimum length is 2'
>     );
>   }
> ​
>   return z.union(literals);
> }
> ​
> // Example:
> const literalValues = ['a', 'b', 'c'] as const;
> ​
> // ERROR: Argument of type 'ZodLiteral<"a" | "b" | "c">[]' is not assignable
> // to parameter of type 'readonly [ZodTypeAny, ZodTypeAny, ...ZodTypeAny[]]'
> z.union(literalValues.map((literal) => z.literal(literal)));
> ​
> // Valid!
> constructZodLiteralUnionType(
>   literalValues.map((literal) => z.literal(literal))
> );
> ```

that's the way 🚀

**Comment by AlanLes** [comment]
@lorenzodejong , @bacharSalleh I love the solution, but attempt with the need to map an array to the array of z.literals always before the actual function seems a little bit weird to me. So I came up with another solution which seems to be such another iteration to your solution @lorenzodejong :)

```
export function constructZodLiteralUnionType<T extends Primitive>(
  constArray: readonly T[],
) {
  const literalsArray = constArray.map((literal) => z.literal(literal));
  if (!isValidZodLiteralUnion(literalsArray)) {
    throw new Error(
      'Literals passed do not meet the criteria for constructing a union schema, the minimum length is 2',
    );
  }
  return z.union(literalsArray);
}
```
and the usage would be simple as:

```
const ARR = ['ab', 'cd', 'ef', 'gh'] as const;
const arrSchema = constructZodLiteralUnionType(ARR);
```

WDYT guys ? :)
