### ISSUE TITLE
Parse in Date Object but  zod _.date() gives error

### ISSUE THREAD

**Issue by MinKangChew** [colinhacks/zod#849]
I created a schema to validate a Date object
```
import {date, object} from "zod"

const createFigureSchema = object({
  bornDate: date({
    required_error: `bornDate is required`,
  }).nullable(),
)};
```
However, when I make a POST request with request body below:
```
const createFigurePayload = {
  bornDate: new Date("1925-07-11"),
}
```
It gives an error: `Expected Date, given string`

I tried to confirm the type of `bornDate` with `console.log(createFigurePayload.bornDate instanceof Date);`. It returns `true`. 

Need someone's help to explain why `_.date()` gives error despite parsing Date object!

**Comment by scotttrinh** [comment]
@MinKangChew 

JSON does not have a `Date` data type, so when the request is made, the date ends up being serialized as a `string` (typically it is the same as the output of `toISOString()`). This is true for many other types of objects, but `Date` is a pretty common one to notice this in!

There are a few ways to deal with this:

1. Use `z.string` instead: It'll be a string, and as long as your application doesn't need to really treat it like a `Date` object, this is fine most of the time.
2. Use `z.preprocess` to convert to a Date:
   ```ts
   bornDate: z.preprocess((a) => new Date(z.string().parse(a)), z.date()),
   ```
3. Use `transform` to make a ZodEffect that transforms a string into a date:
   ```ts
   bornDate: z.string().transform((a) => new Date(a))
   ```

**Comment by MinKangChew** [comment]
@scotttrinh Noted with thanks!!!

**Comment by Drarig29** [comment]
To achieve both validation and conversion, I did this:

```js
bornDate: z.preprocess((a) => new Date(z.string().parse(a)), z.date()).transform(a => new Date(a))
```

So that `obj.parse({ bornDate: '1925-07-11' })` is converted to a Date and `obj.parse({ bornDate: '1925-07-111111' })` fails with an error.
