### ISSUE TITLE
Possible to extend or merge across a union? 

### ISSUE THREAD

**Issue by teddycoleman** [colinhacks/zod#852]
Is it possible to extend or merge across a zod union? 

The use case I have here is that I have a polymorphic type which I store in a JSON field in my DB where I want to:
(a) represent the input I get which does not have an id on it
(b) represent what I get from the database, which now has an id on it

I've provided an example below - I tried a few other attempts without any luck. Please let me know if there's a way to do this - thank you!

```
// example:

const TestThing1 = z.object({
  type: z.literal('thing1'),
  // ... other properties not shared 
});
const TestThing2 = z.object({
  type: z.literal('thing2'),
  // ... other properties not shared 
});
const TestThing3 = z.object({
  type: z.literal('thing3'),
  // ... other properties not shared 
});

const ThingInput = z.union([TestThing1, TestThing2, TestThing3]);

const BaseThing = z.object({
  id: z.string().uuid(),
});
// I want to do something like this, but I get an error (see below)
const Thing = z.union([TestThing1, TestThing2, TestThing3].map(BaseThing.merge));

// Error 
Argument of type 'ZodObject<extendShape<{ id: ZodString; }, { type: ZodLiteral<"thing1">; } | { type: ZodLiteral<"thing2">; } | { type: ZodLiteral<"thing3">; }>, "strip", ZodTypeAny, { ...; }, { ...; }>[]' is not assignable to parameter of type '[ZodTypeAny, ZodTypeAny, ...ZodTypeAny[]]'.
  Source provides no match for required element at position 0 in target.ts(2345)
```

**Comment by scotttrinh** [comment]
It's not currently possible, but you could define base schemas that do not contain `id` and create a union from those, and then extend those base schemas to include an `id` and then make a union of those. _Slightly_ more verbose, but not by much!

**Comment by teddycoleman** [comment]
Gotcha, yeah I had a feeling I would need to do something like that. Thanks for taking a look!

**Comment by jjm340** [comment]
@scotttrinh Is this on a roadmap?

**Comment by scotttrinh** [comment]
> @scotttrinh Is this on a roadmap?

This is not on a roadmap and it's fundamentally not aligned with how unions work except in the case of unions of record-like objects and even in that case I don't think there would be a way to support type inference.

**Comment by jjm340** [comment]
To be clear Typescript supports this and it's awkward in Zod to do this because you have to nest under another key unless there's a workaround I'm not aware of.
