### ISSUE TITLE
UUID regex only validate Variant 1 UUIDs

### ISSUE THREAD

**Issue by narrowei** [colinhacks/zod#854]
Hey everyone,

When I tried to use the UUID function to validate this UUID: **b3ce60f8-e8b9-40f5-1150-172ede56ff74** it returns invalid UUID, but it's a validate UUID. After digging into the source code, I found the reason.

Here is the regex we are currently using (v3.11.6) for validate uuid: 
``` javascript
const uuidRegex = /^([a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}|00000000-0000-0000-0000-000000000000)$/i;
```
However the fourth part of the regex **[89ab][a-f0-9]{3}** only validate for Variant 1 UUIDs. 
[The definition of variant from Wikipedia](https://en.wikipedia.org/wiki/Universally_unique_identifier)

Not sure why the code limits the valid UUID to Variant 1 type?

**Comment by JacobWeisenburger** [comment]
I see that this was merged. Can I close this?
