### ISSUE TITLE
[feature request] Add a refinement for precision-safe integers

### ISSUE THREAD

**Issue by kmbt** [colinhacks/zod#859]
In order to encourage good practices on data integrity I believe that there should be a built-in refinement of `z.number().int().safe()` that makes a check of `Number.isSafeInteger()`. This way we would have an easy mean to check if the integer precision is not lost. 

This is especially important in cases where identifiers for data structures happen to be passed as `number` which sometimes takes place in data returned from JSON APIs.

**Comment by JacobWeisenburger** [comment]
This sounds like a good idea. Please feel free to submit a PR for this.
