### ISSUE TITLE
Docs on integrating with other OSS

### ISSUE THREAD

**Issue by chrbala** [colinhacks/zod#86]
It would be nice to have docs on how to integrate zod with other OSS. This would help people:
* identify whether zod will work well with their tech stack
* figure out how to use zod with their tech stack
* help zod validate its feature set. If the docs are hard to write, zod is probably missing something.

#### GraphQL
It seems like zod could be well suited for GraphQL validations. It would be handy to have a reference for the parallels of GraphQL types and their corresponding zod types, as well as any other suggestions for integrating zod into the GraphQL environment.

As a single small example:

```graphql
union Fish = Salmon | Tuna | Trout
type Catch {
  fish: Fish!
}
```

```js
const FishEnum = z.union([z.literal('Salmon'), z.literal('Tuna'), z.literal('Trout')]);
const Catch = z.object({
  fish: FishEnum,
});
```

Of course it's a bit less obvious when it comes to nullable types because GraphQL is nullable by default, and zod is required by default. 

#### React PropTypes
Seems like an integration that would make sense for libraries. Similar docs like those for GraphQL could make sense.

#### formik
Formik has [native support](https://formik.org/docs/guides/validation) for Yup schemas. Docs on integrating zod with formik would be nice!

**Comment by vriad** [comment]
I think it's a good idea to create a new INTEGRATIONS.md file in the repo describing best practices/patterns for integrating Zod with other OSS libraries, especially form libraries. Anyone who wants to write up one of these mini-guides, submit a PR and I'll happily credit you (link to Twitter, etc).

I'm currently using react-hook-form for a separate project so I will document the patterns involved in doing that in the near future. Are you using Formik + Zod? If so it'd be great if you wrote up a brief guide on doing that. I'll happily credit you in the README.

A few of the ideas you mention are better as standalone libraries built on top of "zod core". I'm considering building a GraphQL  library on top of zod. I haven't found a GraphQL framework that makes it easy to define a schema type once and generate variants of it for the various mutations (create, patch, etc). LOTS of duplicative types required even in massively popular libs like typegraphql.

**Comment by justincrich** [comment]
> I'm currently using react-hook-form for a separate project so I will document the patterns involved in doing that in the near future. Are you using Formik + Zod? If so it'd be great if you wrote up a brief guide on doing that. I'll happily credit you in the README.

If you have any examples I'd love to see them. I'm currently stuck getting my resolver to work right w their `useFieldArray` hook

**Comment by chrbala** [comment]
I am not using Formik + zod, but I am trying to establish what these integrations would look like before really investing in the stack. So, "not yet" is the short answer. I'm also not necessarily sold on either component just yet, since I'm trying to evaluate all the components together before making decisions.

I made a library some time ago with the main idea that it would be a single place to define the structure of objects. It was designed to be a pluggable system that allowed for modular integrations with various functions. It's old and crusty now, there are flaws in the design, it wouldn't play nicely with TS, and I don't actually use it for anything, but there may be some  ideas worth taking a look at.

Library: https://github.com/chrbala/single-schema
GraphQL integration module: https://github.com/chrbala/single-schema/blob/master/src/flatteners/graphql/README.md
Other modules, like PropTypes: https://github.com/chrbala/single-schema#modules

From a high level, a takeaway I had from building that was that if you create a single core schema with a number of tools coming out of it, you're bound to the lowest-common-denominator of functionality across the systems. e.g. if a module doesn't support unions, you can't have unions in any part of the schema unless you have a way of failing over to something that does something similar enough to unions to be compatible.

**Comment by chrbala** [comment]
I have [a bit of progress on an example](https://github.com/chrbala/zod-full-stack-example/tree/work-in-progress). It uses the in-progress zod transformations API and not everything works – don't rely on anything in the repo for now. I'm adding this repo to share progress here, but it shouldn't be trusted to be stable at this point.

**Comment by ryardley** [comment]
So far this works for me getting Zod to work with Formik (only semi-tested).

```ts
import * as z from 'zod'

class ValidationError extends Error {
  public name = 'ValidationError'
  inner: { path: string; message: string }[]
}

function createValidationError(e: z.ZodError) {
  const error = new ValidationError(e.message)
  error.inner = Object.keys(e.errors).map((k) => e.errors[k])
  return error
}

// Wrap your zod schema before passing it to Formik's `validationSchema` prop
export function toFormikYupSchema(schema: z.ZodSchema<any>) {
  return {
    validate(obj: any) {
      try {
        schema.parse(obj)
      } catch (err) {
        throw createValidationError(err)
      }
    },
  }
}
```

**Comment by ivosabev** [comment]
Formik integration would be nice, especially with Formik V3 coming soon.

**Comment by NitzanHen** [comment]
I'm not sure if this belongs here or in its own card, but in my recent project I integrated Zod with Mongoose; in essence, I left the mongoose schemas empty, and added a pre-validate hook for each:

```typescript
//Hotel is an inferred type from HotelSchema (referenced below), a Zod schema.
//Document is mongoose's Document
interface HotelDocument extends Hotel, Document {}

const hotelSchema = new mongoose.Schema({}, { strict: false });
hotelSchema.pre('validate', syncWithSchema(HotelSchema));

const HotelModel = mongoose.model<HotelDocument>('Hotel', hotelSchema);
```

`syncWithSchema` is meant to be generic enough to support any schema:
```typescript
const documentKeys = [
  ...Object.getOwnPropertyNames(Document.prototype),
  //Added those manually; doesn't seem like there are more keys that the prototype misses
  '$__',
  'isNew',
  'errors',
  '$locals',
  '$op',
  '_doc'
];

type NonDocumentKey<T> = keyof Omit<T, keyof typeof Document.prototype>;

/**
 * Retrieves all of the keys (property *names*) of the target object, which do not belong
 * to the Document class (i.e. all non-document property keys of the object).
 * @param target the object to extract keys from.
 */
function getNonDocumentKeys<T extends Document>(target: T): NonDocumentKey<T>[] {
  const targetKeys = Object.getOwnPropertyNames(target);

  return targetKeys.filter(key => !documentKeys.includes(key)) as NonDocumentKey<T>[];
}

/**
 * Returns a *function* used for mongoose middleware validation.
 * Ideally, we could use Zod's parsing methods directly in the mongoose middleware, but since it
 * does not have the option to *return* the validated object, and instead provides it as the `this` parameter,
 * we need to iterate over `this`, after having parsed the relevant fields, assigning fields existing in the parsed response 
 * and deleting those that aren't.
 *
 * @param schema the schema to parse incoming objects by.
 */
function syncWithSchema<T>(schema: z.Schema<T>) {
  return async function (this: Document & T) {
    const modelKeys = getNonDocumentKeys(this);

    const modelFields = pick(this, modelKeys);

    const model = await schema.parseAsync(modelFields);

    modelKeys.forEach((key: keyof T) => {
      if (key in model) {
        this[key] = model[key] as any;
      } else {
        delete this[key];
      }
    });
  };
}
```

It seems to work well at the moment, although I'll admit we didn't get to testing it rigorously.
I have not found the suggested INTEGRATIONS.md to contribute to, where could we add this to?
(of course, I'll add some more explanations & touches such that it's proper documentation)

**Comment by colinhacks** [comment]
Hey @NitzanHen I haven't created that file yet, but feel free to do so in your PR!

**Comment by robertLichtnow** [comment]
> So far this works for me getting Zod to work with Formik (only semi-tested).
> 
> ```ts
> import * as z from 'zod'
> 
> class ValidationError extends Error {
>   public name = 'ValidationError'
>   inner: { path: string; message: string }[]
> }
> 
> function createValidationError(e: z.ZodError) {
>   const error = new ValidationError(e.message)
>   error.inner = Object.keys(e.errors).map((k) => ({
>     message: e.errors[k].message,
>     path: e.errors[k].path.join('.'),
>   }))
>   return error
> }
> 
> 
> // Wrap your zod schema before passing it to Formik's `validationSchema` prop
> export function toFormikYupSchema(schema: z.ZodSchema<any>) {
>   return {
>     async validate(obj: any) {
>       try {
>         await Promise.resolve(schema.parse(obj))
>       } catch (err) {
>         throw createValidationError(err)
>       }
>     },
>   }
> }
> ```

I've created a small library for this specific purpose
https://github.com/robertLichtnow/zod-formik-adapter
