### ISSUE TITLE
Minified ESM file produces giant messages on error

### ISSUE THREAD

**Issue by Luke-zhang-04** [colinhacks/zod#865]
![image](https://user-images.githubusercontent.com/55749227/150037898-a00d7f9f-6b84-4f0e-acea-42f96585f291.png)

Node gives me this massive error when something goes wrong, with Zod, taking away from the actual error itself. I tried using sourcemaps but that doesn't work either. I'm not sure why index.mjs is minified, can we remove the uglifying step from Rollup?

**Comment by JacobWeisenburger** [comment]
Related to [CommonJS vs ESModules deployment issues : uglification #844](844)

**Comment by Luke-zhang-04** [comment]
Closing in favour of #844 then

**Comment by JacobWeisenburger** [comment]
I'm sorry. I wasn't trying to mean that you should close this issue. I just wanted to track that this is similar to another issue, so that we know it's not just 1 person having this issue. Feel free to reopen this if it is still a problem for you.

**Comment by colinhacks** [comment]
Fixed in 3.13.
