### ISSUE TITLE
class as argument for function schema

### ISSUE THREAD

**Issue by S222em** [colinhacks/zod#870]
Hello,

I was wondering how I can get my TS class as a argument to a function without having to recreate the class in zod.

```ts
class Something {
   public id: number
}

// Error
z.function().args(Something)
```

The actual argument will be a instance of Something

Thanks!

**Comment by lorefnon** [comment]
You can use the [instanceof](https://github.com/colinhacks/zod#instanceof) function. 

```
z.function().args(z.instanceof(Something))
```

**Comment by S222em** [comment]
Thanks!
