### ISSUE TITLE
`.pick()` mask allowing non-present props when present props are defined

### ISSUE THREAD

**Issue by prescience-data** [colinhacks/zod#895]
### Example
```typescript

// Original schema
const FooSchema = z.object({
  foo: z.string(),
  bar: z.string()
})


const CorrectlyFailingSchema = FooSchema.pick({
  notARealProperty: true // This causes TypeScript error as expected.
})


const IncorrectlyPassingSchema = FooSchema.pick({
  foo: true,
  notARealProperty: true // Once an existing property is added to the mask, any non-defined props can pass as well.
})

```

This became an issue today where after passing through a bundler (esbuild), a non-descriptive error started throwing on `e.t._parse`: 
```
TypeError: Cannot read properties of undefined
```

The issue occurred because I had removed a property `"title"` from the original schema, but not from the `pick()` mask, so `title._parse()` was throwing as `title` was now undefined.

**Comment by noyan-alimov** [comment]
Ideally typescript should cause an error.
I implemented to show a helpful error message.
Example schema:
```ts
const fish = z.object({
  name: z.string(),
  age: z.number(),
  nested: z.object({}),
});
```
And then:
```ts
fish.pick({ name: true, color: true })
```
Doing this should show `color key does not exist in object schema. Available keys: name,age,nested`

**Comment by prescience-data** [comment]
Additional context:

<img width="633" alt="image" src="https://user-images.githubusercontent.com/65471523/151722206-16e1dbee-8ece-43aa-8482-54cfe149de48.png">

**Comment by JacobWeisenburger** [comment]
This seems answered, may I close this?

**Comment by prescience-data** [comment]
> This seems answered, may I close this?

Is there an associated PR? I haven't see anything as yet, so best to keep it alive until merged imo.

**Comment by JacobWeisenburger** [comment]
Ok sounds good. Just doing a little house keeping. It's hard sometimes to tell if an issue is done or not.
