### ISSUE TITLE
How to model nominal types

### ISSUE THREAD

**Issue by akefirad** [colinhacks/zod#896]
I've got a simple nominal type:
```typescript
export type Id = string & { readonly "": unique symbol };
export interface Hero {
  id: Id;
  name: string;
}
```
How can I create a schema for `Hero`? I tried `ts-to-zod`, but it doesn't seem to be able to handle the case. Is there any way to model this on zod?  (Note: I don't need to use ts-to-zod, I can write the schema manually as long as I know how to do it.)
Thanks.

**Comment by scotttrinh** [comment]
[This comment](https://github.com/colinhacks/zod/issues/678#issuecomment-962387521) provides a kind of solution here (updated for your example):

```ts
export type Id = Brand<'Id', string>;
export function isValidId(id: string): id is Id { 
  //                 Note the type guard ^^^^^^^
  return true; // Or whatever validation makes sense
}
export const IdSchema = z.string().refine(isValidId);

const id: Id = IdSchema.parse('682a8518-a062-4078-9ae0-4b8184e5fe00')
```

That thread also discusses some branding at some length, too, so might be worth reading through.
