### ISSUE TITLE
optional().default() getter doesn't allow returning undefined

### ISSUE THREAD

**Issue by lostfictions** [colinhacks/zod#897]
Given the following snippet:

```ts
import { z } from "zod";

const checkIfOnPath = (executableName: string) => false;

const parsed = z.string()
  .nonempty()
  .optional()
  .default(() => ["a", "b", "c"].find(checkIfOnPath))
  .parse(undefined);
```

I get this error:

```
No overload matches this call.
  Overload 1 of 2, '(def: string): ZodDefault<ZodOptional<ZodString>>', gave the following error.
    Argument of type '() => string | undefined' is not assignable to parameter of type 'string'.
  Overload 2 of 2, '(def: () => string): ZodDefault<ZodOptional<ZodString>>', gave the following error.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.(2769)
```

[(TS Playground link.)](https://tsplay.dev/WP7Rkm)

My expectation is that `.default()` with a function on `ZodOptional<ZodString>` should be able to return `string | undefined`, but it only accepts a function that returns `string`.

Further, at runtime this works just fine -- if the default getter returns `undefined`, `.parse()` doesn't throw, and its return value is `undefined` as I expect.

**Comment by didavid61202** [comment]
really need this too

**Comment by noyan-alimov** [comment]
Type casting could be a workaround.

```ts
import { z } from "zod";

const checkIfOnPath = (executableName: string) => false;

const parsed = z.string()
  .nonempty()
  .optional()
  .default(() => ["a", "b", "c"].find(checkIfOnPath) as string)
  .parse(undefined);
```

**Comment by scotttrinh** [comment]
The spirit and intention of `default` is to return a value of the base type (in this case `string`), as you've noticed. Since you'd like to define an optional default here, you can use `transform` instead:

[CodeSandbox](https://codesandbox.io/s/nervous-liskov-su1du?file=/src/index.ts)
```ts
const schema = z
  .string()
  .nonempty()
  .optional()
  .transform(
    (maybeString) => maybeString ?? ["a", "b", "c"].find(checkIfOnPath)
  );
```

**Comment by scotttrinh** [comment]
Feel free to continue this thread to discuss the concepts here, but this is definitely "working as intended".

**Comment by lostfictions** [comment]
@scotttrinh Thanks! Using `transform` makes sense to me. I see in the source now that `default` behaves this way because its argument is annotated specifically to strip `undefined`. And I think I understand the reasoning where `default` shouldn't be allowed to be `undefined` even on an optional type (where even though it might make sense from the perspective of the type system, it might be confusing in terms of UX).

But just to make sure I understand, this means that `.optional().default()` and `.default()` are effectively the same thing? Given this constraint, the former is effectively redundant and there's never a reason one would reach for it, right?
