### ISSUE TITLE
Object validation custom message

### ISSUE THREAD

**Issue by JanChodorowski** [colinhacks/zod#901]
Hi! I'm trying to rewrite yup validator to zod and have an issue with custom object message.

I have a dropdown that by default has value of `null` and when an item is selected the value is for example`{label: 1, value : 1}`. Using yup I validated only for the object not to be null and outputted message of 'please select X value'.

So the yup validator looks like this - I don't care about particular object properties since they're hardcoded, I only care about the object not being null.

```
const schema = yup.object().shape({
  companyType: yup
    .object()
    .required('Please select X value')
    .typeError('Please select X value'),
```

When, on the other hand, I use zod the schema looks like this - I define the properties even though I don't care about them, and there is no way of defining custom error message. When selectField is `null` the message is `Expected object, received null` and I have no idea whether it is modifiable or how.

```
const zodSchema = z.object({
  selectField: z.object({
    value: z.string(),
    label: z.string(),
  }),
```

I would like to do something like this
```
const zodSchema = z.object({
  selectField: z.object({
    value: z.string(),
    label: z.string(),
  }).nonNullable('Please select X value'),
```

Any tips? :)

**Comment by scotttrinh** [comment]
The second argument to `z.object` is a `CreateParams` object that has a few ways of setting the error message. We don't have a lot of good documentation on this, but here is a quick example and CodeSandbox to help!


[CodeSandbox](https://codesandbox.io/s/sharp-dream-kk21y?file=/src/index.ts)

```ts
const zodSchema = z.object({
  selectField: z.object({
    value: z.string(),
    label: z.string(),
  }, {
    invalid_type_error: 'Please select X value'
  }),
```

**Comment by JanChodorowski** [comment]
Thanks! That's it!
