### ISSUE TITLE
`z.infer` creates object types with optional keys

### ISSUE THREAD

**Issue by avin-kavish** [colinhacks/zod#905]
When creating an object like,

```ts
  const Schema = z.object({
    email: z.string()
  })

  type Schema = z.infer<typeof Schema>
```

The created type is,

```ts
  type Schema = {
    email?: string
  }
```

But according to the documentation the keys should be required.

**Comment by scotttrinh** [comment]
This is typically a sign that you do not have `strict: true` and/or `strictNullCheck: true` in your `tsconfig.json` as required in the [installation instructions from the README](https://github.com/colinhacks/zod#installation).

**Comment by luisgregson** [comment]
Is there any way around this? I've added zod to an existing project which does not have `strict: true` or `strictNullCheck: true` enabled. We're working on getting to the point where we can enable the `strict` flag, but would like to use zod right away.

We're using it on a graphql api to add some extra validation on input objects (our graphql implementation does the default graphql validation of required fields and basic types, but zod will add things like min string length). However, the types returned by `.parse(inputObject)` are less accurate than `inputObject` as every key is now optional.

If it's not possible right now that's fine, it just seemed a bit odd that every object key becomes optional: tsc without `strict` won't throw if my code attempts to access an optional field, but at least my editor will warn me, whereas now i get warnings on everything.

**Comment by itayganor** [comment]
> Is there any way around this?

+1

In lots of projects, adding `strict: true` will result in a major refactor. Is there anything that could be done in order to bypass this?
