### ISSUE TITLE
Branded helper

### ISSUE THREAD

**Issue by steida** [colinhacks/zod#917]
Instead of:

```ts
type Age = Branded<number, "Age">;

const Age = z
  .number()
  .min(0)
  .max(100)
  .refine((a: number): a is Age => true);
```

Zod can provide a simple helper:

```ts
const Age = z
  .number()
  .min(0)
  .max(100)
  .brand('Age');
```

What do you think? 

---

This line:

```ts
.refine((a: number): a is Branded<number, "Age"> => true)
```

to this line:

```ts
.brand("Age").
```

I suppose it's a tiny change but would improve DX a lot.

---

Or something like that?

```ts
const brand =
  <B extends string>(brand: B) =>
  <T extends string | number>(a: T): a is Branded<T, typeof brand> =>
    true;

.refine(brand("Age"))
```

---

OK, this is what I reiterated. Still, I suppose it should be part of the official Zod API. 

```ts
export type Branded<T extends string | number, B extends string> = T & {
  readonly __brand: B;
};

export const branded =
  <B extends string, T extends string | number>(
    brand: B,
    predicate?: Predicate<T>
  ) =>
  (a: T): a is Branded<T, typeof brand> =>
    predicate ? predicate(a) : true;
```

**Comment by steida** [comment]
This line:

```ts
.refine((a: number): a is Branded<number, "Age"> => true)
```

to this line:

```ts
.brand("Age").
```

I suppose it's a tiny change but would improve DX a lot.

**Comment by steida** [comment]
Or something like that?

```ts
const brand =
  <B extends string>(brand: B) =>
  <T extends string | number>(a: T): a is Branded<T, typeof brand> =>
    true;

.refine(brand("Age"))
```

**Comment by steida** [comment]
OK, this is what I reiterated. Still, I suppose it should be part of the official Zod API. 

```ts
export type Branded<T extends string | number, B extends string> = T & {
  readonly __brand: B;
};

export const branded =
  <B extends string, T extends string | number>(
    brand: B,
    predicate?: Predicate<T>
  ) =>
  (a: T): a is Branded<T, typeof brand> =>
    predicate ? predicate(a) : true;
```

**Comment by JacobWeisenburger** [comment]
What problem are you trying to solve with `Branded` or `brand`? Please explain how this would be helpful and why you think it should be part of the official Zod API.

**Comment by steida** [comment]
I'm using branded types a lot. I almost never use plain types. Why? Long answer: Domain Modeling Made Functional from Scott Wlaschin. Short answer: It's really good.

> why you think it should be part of the official Zod API.

Because it would be useful for a lot of people.

```ts
// A custom branded type.
const Friendliness = z.number().min(1).max(5).refine(e.branded("Friendliness"));
```

Sorry I didn't provide more detailed reasoning.

**Comment by brudil** [comment]
We use branded types a fair bit, so I'm happy to chime in on how they can be used.

With TypeScript's structural typing, we can't utilise the type system to ensure zod is being used. Branded types are a way to create a unique type which can only be assigned then parsing with zod. This allows us to use the type system to ensure validation is happening.

As an example;

Defining a schema such as
```ts
const Schema = z.object({ age: z.number().min(18) });
```

And we can use the inferred type from our schema within a param for example.
```ts
function save(data: z.infer<typeof Schema> ) {}
```

TypeScript's structural typing means there are no guarantees that input needs to have been parsed by zod first.

```ts
save({ age: 16 }) // perfectly valid and types.
```

Branded types allow us make a type 'unique'.

```ts
export type Branded<T, B> = T & { __brand: B };
```

If we revisit the save function from above
```ts
function save(data: Branded<z.infer<typeof Schema>, 'ageSchema'> ) {}
```

We've now ensured that this case is no longer possible

```ts
save({ age: 16 })
// TS2345: Argument of type '{ age: number; }' is not assignable to parameter of type 'Branded<{ age: number; }, "ageSchema">'.   Property '__brand' is missing in type '{ age: number; }' but required in type '{ __brand: "ageSchema"; }'.
```

**Comment by JacobWeisenburger** [comment]
Thanks. That really helps. I think I can see the use case for this. Not sure if zod will add this, but you are more then welcome to submit a PR.

**Comment by steida** [comment]
@brudil Branded types are generally used only for primitive types, especially string and number. Using them for objects is not safe, spreading is not checked. There are some hacks, but I don't know how reliable they are. I experimented with branded arrays, and as I remember, it was reliable. Anyway, my example enforces only primitive types (string and number), because it's well-known usage.

**Comment by steida** [comment]
Leaving it here to discuss the proper branding implementation 

https://leebyron.com/til/opaque-types/

**Comment by colinhacks** [comment]
I'll I've been considering a dedicated API for branded types for a long time (#3) but I don't think it makes sense. If you want the result of `.parse` to be pretty (e.g. `Age`), you have to declare that type separately. At that point you might as well cast or use `z.custom`:

```ts
type Age = Branded<number, "Age">;

const ageSchema: z.ZodType<Age> = z.string().refine(...) as any;
const ageSchema = z.custom<Age>()
```
