### ISSUE TITLE
Type Error when recursive types with default

### ISSUE THREAD

**Issue by shuijinliuxi** [colinhacks/zod#923]
```
type NodeType = {
    id: string;
    parent?: NodeType;
};

export const NodeTypeSchema: z.ZodSchema<NodeType> = z.lazy(() =>
    z.object({
        id: z.string().default(''),
        parent: NodeTypeSchema.optional()
    })
);
```

typescript 4.5.5 error:

Type 'ZodLazy<ZodObject<{ id: ZodDefault<ZodString>; parent: ZodOptional<ZodType<NodeType, ZodTypeDef, NodeType>>; }, "strip", ZodTypeAny, { ...; }, { ...; }>>' is not assignable to type 'ZodType<NodeType, ZodTypeDef, NodeType>'.
  The types of '_input.id' are incompatible between these types.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'

**Comment by EdsterG** [comment]
You need to specify and input type and an output type:
```
type NodeInputType = {
    id?: string;
    parent?: NodeInputType;
};

type NodeOutputype = {
    id: string;
    parent?: NodeOutputype;
};

export const NodeTypeSchema: z.ZodSchema<NodeOutputype, z.ZodTypeDef, NodeInputType> = z.lazy(() =>
    z.object({
        id: z.string().default(''),
        parent: NodeTypeSchema.optional()
    })
);
```
