### ISSUE TITLE
Discriminated Unions are available?

### ISSUE THREAD

**Issue by jjm340** [colinhacks/zod#924]
I see a reference to [Discriminated Unions](https://github.com/colinhacks/zod#discriminated-unions) in the documentation, but in the latest version of zod, `3.11.6`, I can't access them, is there going to be a release soon to get this feature?

**Comment by JacobWeisenburger** [comment]
I confirmed this issue.

```ts
const item = z
    .discriminatedUnion( "type", [
//   ^^^^^^^^^^^^^^^^^^
// Property 'discriminatedUnion' does not exist on type 'typeof import(".../node_modules/zod/lib/external")'.
        z.object( { type: z.literal( "a" ), a: z.string() } ),
        z.object( { type: z.literal( "b" ), b: z.string() } ),
    ] )
    .parse( { type: "a", a: "abc" } )
```

@colinhacks are you able to answer this one?
