### ISSUE TITLE
z.object().passthrough() not working with objects like Buffer

### ISSUE THREAD

**Issue by TillaTheHun0** [colinhacks/zod#925]
Thanks for Zod!

Perhaps I am using this incorrectly, or missed something in the docs. I wanted to use a zod schema to parse an object containing a field that points to a `Buffer` , more generally an object that implements `Reader` (`Buffer` does), but that detail isn't important for this. I didn't expect native support for `Buffer`, so I figured I could use `z.object({ ... }).passthrough()`, checking for the methods on `Buffer` I cared about, but then passing through the whole object to keep the internals working.

What seems to happen is that I get back an object that has the `bytes()` function, but the rest of the fields _do not_ passthrough. So fundamentally, it seems that `passthrough()` isn't working for this case, unless i'm using it incorrectly.

Here is a reproduction using Deno:

```js
import * as z from "https://cdn.skypack.dev/zod@^3";
import { Buffer } from "https://deno.land/std@0.125.0/io/buffer.ts";

const FooSchema = z.object({
  bar: z.string(),
  // stream is a Buffer, but passthrough all fields
  stream: z.object({
    bytes: z.function(),
  }).passthrough(),
});

const throws = FooSchema.parse({
  bar: "fizz",
  stream: new Buffer(new Uint8Array(4).buffer),
});

console.log("typeof Buffer: ", typeof new Buffer(new Uint8Array(4).buffer));

// this throws because another method has been stripped that bytes() uses internally
console.log("throws.stream.bytes(): ", throws.stream.bytes());
```

**Comment by EdsterG** [comment]
Why not just do the following:
```
const FooSchema = z.object({
  bar: z.string(),
  stream: z.instanceof(Buffer),
});
```

**Comment by TillaTheHun0** [comment]
@EdsterG great question. I'm assuming `z.instanceof` runs `instanceof`, which looks at the prototype chain. What is passed won't always be an instance of `Buffer`. It could be a POJO that implements the `Reader` interface, in which case `z.instanceof` will not work.

**Comment by EdsterG** [comment]
ZOD uses `Object.keys` to retrieve the keys of an object. In your case `Object.keys(Buffer(''))` doesn't return anything useful. In order to fix this zod will have to recursively iterate over the prototypes of the object, which I don't think is reasonable.
I'd recommend finding a common base class that you can call `instanceof` against or use a union:
```
const FooSchema = z.object({
  bar: z.string(),
  stream: z.union([z.instanceof(Buffer), z.instanceof(Reader)]),
});
```

**Comment by TillaTheHun0** [comment]
@EdsterG Thanks for the suggestions! When I say `Reader` I am referring to Deno's [io interface](https://medium.com/deno-the-complete-reference/reader-writer-seeker-and-closer-in-deno-2838c9f6b233). It's just a TS type, so I don't think I could pass to `instanceof`. Though it sounds like there are some other limitations to my approach, regardless.

There is actually a piece of code that validates the right shape farther upstream from my zod schema, so really a "is not nil" would suffice for me. Does `zod` have that sort of thing? I know there's `any`, but that allows `nil` values, IIRC.

**Comment by EdsterG** [comment]
@TillaTheHun0 the type you need to handle this case is not possible to specify in TypeScript. So your best bet is it let the type be `any` but add an refinement to validate the input further.

```
const FooSchema = z.object({
  bar: z.string(),
  stream: z.any().refine(
      (val: any) => val !== undefined /* or some other check to ensure proper format */,
      message: "stream must be defined",
  ),
});
```

**Comment by TillaTheHun0** [comment]
Looks great! I'll go ahead and use that approach. I'll go ahead and close this issue.

**Comment by mpurdon** [comment]
if you come here later, this is the version that I used when `instanceOf(Buffer)` was failing on a `Buffer.from()` constructed value.

```typescript
const FooSchema = z.object({
  bar: z.string(),
  stream: z.unknown().refine(
    (val) => val !== undefined,
    {
      message: "stream must be defined",
    }
  ),
});
  ```
