### ISSUE TITLE
Breaking change in 3.9.0 can cause undefined `this` errors

### ISSUE THREAD

**Issue by callum-mellorreed-privitar** [colinhacks/zod#937]
I've just upgraded from an early 3.x to 3.11.6 and spent a fair while debugging this, so I'm raising it to help others in the same situation. It may be helpful to revert or document the change too.

---

Commit d47eadc in 3.9.0 changed `() => {}` arrow functions to `function() {}` methods. With arrow functions `this` is bound lexically and will always point to the containing class, but with methods the value of `this` changes with how you call it. This breaks any direct call of a zod method which refers to `this` internally.

Using `parse` as an example which internally calls `this.safeParse`, the following code works as expected before 3.9.0, and throws `Cannot read property 'safeParse' of undefined` after 3.9.0.

```ts
const parse = isAsync ? myZodSchema.parseAsync : myZodSchema.parse
const result = await parse(values)
```

To fix it, you must avoid reassigning `parse` and instead call it directly from your schema.

```ts
const result  = await (isAsync ? myZodSchema.asyncParse(values) : myZodSchema.parse(values))
```

**Comment by scotttrinh** [comment]
Thanks for pointing out this breakage @callum-mellorreed-privitar. I don't have anything more general to say about breaking changes, but wanted to add that `bind` should get you closer to what you had before:

[CodeSandbox](https://codesandbox.io/s/nostalgic-knuth-w789z5?file=/src/index.ts)
```ts
const parse = isAsync 
  ? myZodSchema.parseAsync.bind(myZodSchema) 
  : myZodSchema.parse.bind(myZodSchema)
const result = await parse(values)
```

**Comment by callum-mellorreed-privitar** [comment]
No problem, thanks for the fix!
