### ISSUE TITLE
Enums should support an omit method

### ISSUE THREAD

**Issue by jasonkuhrt** [colinhacks/zod#970]
Example of what has to be done right now:

```ts
const a = z.nativeEnum( { a: 1, b: 2 } as const )
const b = z.nativeEnum( Remeda.omit( a._def.values, [ 'a' ] ) )

b._def.values.b // works
b._def.values.a
//            ^
// Property 'a' does not exist on type 'Omit<{ readonly a: 1; readonly b: 2; }, "a">'.
```

I'm not sure how to do it with zod enums actually.

This issue would be asking for native and zod enums though to support an omit method.

**Comment by JacobWeisenburger** [comment]
Here's how you do it with zod enums

```ts
const foo = z.enum( [ 'a', 'b' ] )

type WithoutA = Exclude<z.infer<typeof foo>, 'a'>
const bar = z.enum(
    foo.options.filter( x => x !== 'a' ) as [ WithoutA, ...WithoutA[] ]
)

bar.enum.b // works
bar.enum.a
//       ^
// Property 'a' does not exist on type 'Values<[WithoutA, ...WithoutA[]]>'.
```

**Comment by colinhacks** [comment]
There's an argument that this should be a top-level `z.omit` utility, which has been suggested elsewhere.

```ts
const a = z.nativeEnum( { a: 1, b: 2 } as const )
const omitted = z.omit(a, z.literal(2));
```

Once we have a `ZodEmit` schema type, we can add a global `.omit` method on the base ZodType.

**Comment by jasonkuhrt** [comment]
@colinhacks in your example you're omitting by value?

**Comment by colinhacks** [comment]
> AND method helpers too?

Yep that's what I mean by "add the `.omit` method on the base `ZodType`". This would add the `.omit` method to all Zod schemas.

**Comment by jasonkuhrt** [comment]
Pleae re-open

**Comment by jasonkuhrt** [comment]
Pleae re-open

**Comment by jasonkuhrt** [comment]
Please re-open

**Comment by deriegle** [comment]
I was able to get this working using `.refine`. Of course it could be easier, but it was good enough for my solution.

[Typescript Playground](https://www.typescriptlang.org/play?ssl=14&ssc=11&pln=1&pc=1#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgNwBQFApgHYCueAyjAIYz0DOiFccMJCHAC8BAcQj4ANLzjBaABRwBzKNU7dR+eUoir1nabIDGuMABtqMasREFT4S9dIy0VU7U7xaEGAGEzJxs7ZFkAOlp2YAA3agBRBhAAChZ2LgBKcLVMeWokpK80znSALjhCjm5gbjiAD2NzemJqAB5Uyqk4dq4whwsrGwA+EWGKrjgAQmFRbs5ewIHidMoKGABPMGo4ADlfAMdFkLD5TGooFvXNiEw4H38F50HKPheAele4AD0AfipZF4BgL4QA)

```ts
import { z } from 'zod';

enum Status {
  todo = 'todo',
  inProgress = 'inProgress',
  completed = 'completed',
}

const notCompleted = z
  .nativeEnum(Status)
  .refine((status): status is Exclude<Status, Status.completed> => status !== Status.completed);

type NotCompleted = z.infer<typeof notCompleted>;
     // ^?
```

**Comment by colinhacks** [comment]
`ZodEnum` now has a `.exclude()` method that implements this behavior as of Zod 3.21.

Top level `z.omit` is probably not going to happen so I'm going to close.

**Comment by nullndr** [comment]
Would it be possible to add the `.exclude()` method also in `ZodNativeEnum`?

I have a case where I need to exclude from a prisma enum a specific value:

```typescript
const validationSchema = z.object({
  ...
  type: z.nativeEnum(Prisma.AutomationType),
  ...
});
```

Currently I can recreate the native enum schema with a `ZodEnum`, and then call `.exclude()` on it, but my `AutomationType` would grow huge so I would like a simpler approach.
