### ISSUE TITLE
How do I map an array of values into discriminated union options

### ISSUE THREAD

**Issue by JacobWeisenburger** [colinhacks/zod#989]
### Discussed in https://github.com/colinhacks/zod/discussions/985

<div type='discussions-op-text'>

<sup>Originally posted by **Aaronius** February 28, 2022</sup>
I'd like to be able to map an array of string values into discriminated union options and use them with `z.discriminatedUnion`. Here's what I'm trying to do:

```ts
const validationSchema = z.discriminatedUnion("taxClassification", Object.values(TaxClassification).map(taxClassification => {
  return z
    .object({
      taxClassification: z.literal(taxClassification),
      exemptPayeeCode:
        taxClassificationExemptPayeeCodeSchemaMap[taxClassification],
      exemptFatcaCode:
        taxClassificationExemptFatcaCodeSchemaMap[taxClassification],
    })
});
```

I can't though because "Source provides no match for required element at position 0 in target." 

I would typically try to type my mapped array as `[ZodDiscriminatedUnionOption, ZodDiscriminatedUnionOption, ...ZodDiscriminatedUnionOption[]` before passing it into z.discriminatedUnion, but Zod doesn't seem to expose the `ZodDiscriminatedUnionOption` type. Is there a better way?</div>

**Comment by JacobWeisenburger** [comment]
I have played around with this and I don't really see a good solution without changing zod's code. Even if I manually export `ZodDiscriminatedUnionOption`, I'm still running into problems. In my opinion, this is a bug. I think that you should be able to do what you are trying to do.

**Comment by Aaronius** [comment]
Re-open please.

**Comment by Aaronius** [comment]
@JacobWeisenburger Are you able to re-open this?
