### ISSUE TITLE
Type Inference : Named Types with nested schemas in objects

### ISSUE THREAD

**Issue by julienfdev** [colinhacks/zod#993]
Hey everyone!
I've recently discovered Zod and this is quite a marvel! Congrats @colinhacks and every contributor for the awesome work !

I've got an "issue" that can be quite annoying when dealing with complex objects, let me explain with this short example : 

```typescript
const foo = z.object({
    name: z.string(),
    birthdate: z.date()
})
type Foo = z.infer<typeof foo>

const bar = z.object({
    property: z.string(),
    foo
})
type Bar = z.infer<typeof bar>
```

Here i defined two schemas, a practical example would be : Foo is a Person, and Bar is an Order or something, it doesn't matter.
When I infer the type of Bar, I would like the final output to look like this : 

```typescript
type Bar = {
    property: string;
    foo: Foo;
}
```

Of course right now, this is impossible, I've searched the docs and tried a few things, but unfortunately nothing worked.

**What the inferred type looks like (no surprise here)**
```typescript
type Bar = {
    property: string;
    foo: {
        name: string;
        birthdate: Date;
    };
}
```

**What i've tried so far, without any luck**
```typescript
const bar = z.object({
    property: z.string(),
    foo: foo as z.ZodSchema<Foo>
})
```

```typescript
const bar = z.object({
    property: z.string(),
    foo: foo.transform((arg): Foo => { return arg })
})
```

**My terrible workaround**
```typescript
type Bar = { property: string, foo: Foo }
```

**Why I consider it important**
With large DB infrastructures, having understandable and clear typings is essential, while Zod allows me to really enforce typing, I would really like to have a clear type hinting from VSCode when using z.infer<T>. The workaround is fine but it's static.

Have anyone figured out how to achieve such behavior ?

Cheers!
Julien

**Comment by julienfdev** [comment]
PS: even if it's not exactly the same things, it works that way with nativeEnum right now : 

```typescript
enum DayOfWeek {
    MONDAY,
    TUESDAY,
    WEDNESDAY,
    THURSDAY,
    FRIDAY,
    SATURDAY,
    SUNDAY
}

const schema = z.object({
    id: z.number(),
    day: z.nativeEnum(DayOfWeek)
})
```

When using z.infer to cast it:

```typescript
type Schema = {
    id: number;
    day: DayOfWeek;
}
```

This is what i'm trying to achieve with schemas instead of enums

**Comment by colinhacks** [comment]
Thanks for the detailed explanation. Unfortunately to the best of my knowledge this isn't possible in typescript and likely never will be. There's no way to tell the compiler what the inferred type should be named. Just because you declare a runtime variable named `Foo` doesn't mean there is a type with that name. For instance, this is totally legal; note that both the runtime and static variables have the same name - they're distinct entities.

```ts
const Foo = z.object({
    name: z.string(),
    birthdate: z.date()
})
type Foo = "whatever";
```   

This works with nativeEnum because `DayOfWeek` ia a named TypeScript type that exists independently of Zod, which isn't possible for most schema types.

**Comment by julienfdev** [comment]
Hey @colinhacks thanks a lot for your answer!
I understand the issue, Thanks a lot !

**Comment by OnkelTem** [comment]
So far no solution was provided. While there is one, of course not that shiny.

```ts
import { z } from "zod";

type Foo = {
  name: string;
  birthdate: Date
}
const foo: z.ZodType<Foo> = z.object({
    name: z.string(),
    birthdate: z.date()
})

type Bar = {
  property: string;
  foo: Foo;
}
const bar: z.ZodType<Bar> = z.object({
    property: z.string(),
    foo
})
```

[TypeScript Playground link]https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFMAnmAKZwBiEEcAvIhXHAHYCGIegC44AZxhRgvAOaUeAI2CwAFsX4wRcACIb6FNBQDGEXhKytRyAHQAtEgBU69ADwsIAPg4prEBQCt6IxgACgRuHj5BLRsJKVkQgEoAGgjFZRg1PStrdU0kg0SqWgY4ACF+KG9wnjAcBlgaUTjpOQjMS2ZWSkMTM3gFSpz7YicGFwqoL04bP0DgsLS4OogG2hyWhJSljohCqgogA()

**Comment by jaredmcateer** [comment]
> So far no solution was provided. While there is one, of course not that shiny.
> 
> import { z } from "zod";
> 
> type Foo = {
>   name: string;
>   birthdate: Date
> }
> const foo: z.ZodType<Foo> = z.object({
>     name: z.string(),
>     birthdate: z.date()
> })
> 
> type Bar = {
>   property: string;
>   foo: Foo;
> }
> const bar: z.ZodType<Bar> = z.object({
>     property: z.string(),
>     foo
> })
> [TypeScript Playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFMAnmAKZwBiEEcAvIhXHAHYCGIegC44AZxhRgvAOaUeAI2CwAFsX4wRcACIb6FNBQDGEXhKytRyAHQAtEgBU69ADwsIAPg4prEBQCt6IxgACgRuHj5BLRsJKVkQgEoAGgjFZRg1PStrdU0kg0SqWgY4ACF+KG9wnjAcBlgaUTjpOQjMS2ZWSkMTM3gFSpz7YicGFwqoL04bP0DgsLS4OogG2hyWhJSljohCqgogA)

I've come up with something that is slightly less verbose especially when dealing with really large shapes that you only have a few properties you want to alias. It uses Matt Pocock's [`Prettify` utility type](https://www.totaltypescript.com/concepts/the-prettify-helper) and intersections so there is a caveat around type intersection compile performance.

[Typescript Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcBEyEAJvgNwBQFApgB6SxwwCeY1cAClNTDMJswA8AFQB8cALyI4AbQDScYADs4Aa2rMImOMIC6ALh3zd6OADJEaSgGMISgM7xMECJJQA6CACMAVtWswABQIFHBhcEoAhiDUhsjujlDKAOaBAJQANKHhXsCwABbEkTCxHkUl6RRoaRQsbHAAYi5u8cqY1FCCddRaWC6ilFS2DvBekVAtnr7+QSHhcGA4bLDMcQkwSUqpmdlhzhBVNd1wAELjblw8fAKCrUrtnd29Y1DiFkj7hk0QZOgDFAB6AHhAB6AH4KEA)

Sorry to resurrect a dead issue, but this is what was at the top of my web search so I hope this could be helpful to future vistors.
