### ISSUE TITLE
Confusing docs for .parse

### ISSUE THREAD

**Issue by callumlocke** [colinhacks/zod#996]
Bit confused by the docs for [parse](https://github.com/colinhacks/zod/tree/70615e6a4e05adafe7e471f4706e90f8ee798292#parse):

> Given any Zod schema, you can call its `.parse` method to check `data` is valid. If it is, a value is returned with full type information! Otherwise, an error is thrown.
> > IMPORTANT: In Zod 2 and Zod 1.11+, the value returned by `.parse` is a _deep clone_ of the variable you passed in. This was also the case in zod@1.4 and earlier.

OK, but what does it return now? I would have assumed a deep clone. I looked in the changelog but it just says "Parsing no longer returns deep clone".

**Comment by colinhacks** [comment]
Good call, just pushed a clarificaiotn
